### ISSUE TITLE
Пара пожеланий

### ISSUE THREAD

**Issue by apan65** [SthephanShinkufag/Dollchan-Extension-Tools#1000]
Можете добавить топ тредов как кнопку на панели скрипта, а то топ прячется за панелью. http://clip2net.com/clip/m11339/ed553-clip-11kb.jpg
И еще добавить функцию автообновления капчи, а то постоянно ввожу тухлую.

**Comment by UserNaem** [comment]
Кнопку "Топ тредов" можно нажать, хотя попасть по ней не очень легко. Можно сдвинуть её повыше с помощью пользовательского CSS:
`
.bb{
bottom: 20px;}
`
А интервал обновления капчи можно изменить на вкладке "Посты":
![g_-_technology_-_4chan_-_firefox_developer_editi 07 12 16 13-00-32](https://cloud.githubusercontent.com/assets/21028464/20959537/429a5c04-bc7d-11e6-819f-3f3f3ef0695a.png)

**Comment by apan65** [comment]
Действительно, проглядел с капчей. Спасибо все сделал.
