### ISSUE TITLE
Не открывается translate.yandex.com

### ISSUE THREAD

**Issue by sooqua** [SthephanShinkufag/Dollchan-Extension-Tools#1001]
При включенном скрипте не работает translate.yandex.com.
Tampermonkey зависает и начинает греть проц, помогает лишь его перезапуск в chrome://extensions/

**Comment by UserNaem** [comment]
Не получилось воспроизвести на Tampermonkey 4.1.10 с Chromium 51.1, ничего не зависает

**Comment by sooqua** [comment]
У меня dev:
**Version 56.0.2924.18 dev (64-bit)**
Если я могу предоставить более подробную информацию, напишите. Пока добавил translate.yandex.com в @exclude

**Comment by sooqua** [comment]
Проблема решилась сама по себе.
