### ISSUE TITLE
Не обновляется скрипт

### ISSUE THREAD

**Issue by OskarZeta** [SthephanShinkufag/Dollchan-Extension-Tools#1004]
Добрый день. Итак, по порядку:

> браузер и его версия

Firefox 50.1.0

>используемая версия скрипта

16.8.17.0.762075a

>имиджборд, на котором встретилась ошибка

Сразу ВСЕ

>пошаговые действия для воспроизведения ошибки

Несколько дней назад появилась плашка с предложением обновить скрипт до версии 16.11.14.0, вот только обновления не происходит - при этом настройки на старой версии сбились на дефолтные, причём даже после удаления-попытки установить последнюю версию скрипта установилась почему-то 16.8.17.0.762075a. И так происходит после каждого перезапуска браузера - каждый раз сбиваются настройки скрипта и вылезает плашка с обновлением, которое не происходит.

**Comment by SthephanShinkufag** [comment]
Да, были проблемы с нумерацией версий.
Сейчас, наверное, уже всё нормально?

**Comment by OskarZeta** [comment]
Да, всё в порядке, спасибо.
