### ISSUE TITLE
The Clear button (clear innaccessible threads) doesn't work 

### ISSUE THREAD

**Issue by slavking** [SthephanShinkufag/Dollchan-Extension-Tools#1006]
on firefox 45.5.0 ESR

**Comment by slavking** [comment]
Still doesn't work! 
В Изабранное>Очистить, кнопка не Очистить не работает.

**Comment by stetzen1** [comment]
Подтверждаю, действительно не работает.
Chrome 53/55, расширение из стора 16.12.28.0

**Comment by SthephanShinkufag** [comment]
Все работает.
Что пишет в консоли ошибок (`Ctrl+Shift+J`) при попытке очистки?

**Comment by SthephanShinkufag** [comment]
What writes in error console  (`Ctrl+Shift+J`) when attempting to clear the Favorites?

Что пишет в консоли ошибок (`Ctrl+Shift+J`) при попытке очистки?

**Comment by slavking** [comment]
Это странно, теперь Clear работает нормально, не дан-два раньше не хотело. Я сделал по другому, нажал кнопку Clear, а тогда быстро кнопку Deleting..., тогда после 2-3 секунда стало работать.
Вот консола:
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create Dollchan_Extension_Tools.user.js:2445:7
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create Dollchan_Extension_Tools.user.js:2445:7
TypeError: parent is null
updateFileFields()
 thread-38468916.html:935
<anonymous>
 thread-38468916.html:1516
_createResponder/responder()
 prototype.js:4481
 thread-38468916.html:935:7
no element found thread-38466812.html:1:1
TypeError: parent is null
updateFileFields()
 thread-38472211.html:935
<anonymous>
 thread-38472211.html:1516
_createResponder/responder()
 prototype.js:4481
 thread-38472211.html:935:7
no element found thread-38466812.html:1:1
no element found thread-38466812.html:1:1
no element found thread-38468916.html:1:1
no element found thread-38466812.html:1:1
no element found thread-38472211.html:1:1

**Comment by SthephanShinkufag** [comment]
Hmm. But Clear button was nothing to do with the Deleting button.
Prototype errors from your log is just warnings that are not associated with the problem.
Other errors is native errors of krautchan's page and not related to script.

> теперь Clear работает нормально
So, everything is fine now? That was so strange bug.
