### ISSUE TITLE
brchan.org обновил движок

### ISSUE THREAD

**Issue by Oduvanchik7227** [SthephanShinkufag/Dollchan-Extension-Tools#1008]
Админы переехали на новый движок. Запилишь поддержку? А то после отправки webm вылезает ошибка громоздкая и приходится перезагружать страницу. Очень будем признательны, Степан.

**Comment by SthephanShinkufag** [comment]
Вроде бы всё корректно работает. Видимо, тамошние админы сами все подпилили.
Ну и слава Богам.

Что исправил:
- теперь сажа детектируется правильно,
- убрал родной счетчик постов,
- переименовал кнопку "Создать тред" в списке тредов

**Comment by SthephanShinkufag** [comment]
Может, еще что-то подправить?

**Comment by pngcrypt** [comment]
Форматирование текста хорошо бы на тэги переделать [b] [s] [u] [i] [spoiler]

**Comment by Oduvanchik7227** [comment]
Большое спасибо!
