### ISSUE TITLE
невозможно добавить в избранное более 31 треда на 2ch.hk

### ISSUE THREAD

**Issue by stetzen1** [SthephanShinkufag/Dollchan-Extension-Tools#1009]
Заголовок должен говорить сам за себя. При попытке добавить 32й тред происходит одно из трёх:
1)не происходит ничего (звезда становится желтой, но тред не добавляется в список)
2)новодобавленный тред заменяет собой последний добавленный
3)тред добавляется, но исчезает из избранного после перезагрузки страницы
Браузер - Chrome 53/55 (проверялось на обоих), расширение из стора 16.12.28.0

Консоль выдает следующее:

Unchecked runtime.lastError while running storage.set: QUOTA_BYTES_PER_ITEM quota exceeded
    at setStored (chrome-extension://ipnoalfffblkaodfmipjjgkfbgcfadad/Dollchan_Extension_Tools.user.js:4552:25)
    at saveFavorites (chrome-extension://ipnoalfffblkaodfmipjjgkfbgcfadad/Dollchan_Extension_Tools.user.js:4874:3)
    at chrome-extension://ipnoalfffblkaodfmipjjgkfbgcfadad/Dollchan_Extension_Tools.user.js:16239:6

**Comment by SthephanShinkufag** [comment]
Я уже не знаю, что делать с этим вашим расширением.
Хромохранилище НЕПРИГОДНО для хранения данных куклоскрипта.
Перевести скрипторасширение на localstorage? Я могу. Но избранное перестанет быть общим для всех борд.

**Comment by SthephanShinkufag** [comment]
Пофиксил. Теперь при превышении лимита в синхронизируемом хранилище `chrome.sync`, данные записываются в `chrome.local`.
Залил обновленное расширение, пробуйте.
Синхронизируемом хранилище очень быстро заканчивается, как я сказал ранее, поэтому синхронизация избранного/настроек между разными ПК работать не будет.
