### ISSUE TITLE
Add minimum video width

### ISSUE THREAD

**Issue by ganego** [SthephanShinkufag/Dollchan-Extension-Tools#1010]
**Problem:**
Some webms are very narrow (for example if filmed vertically). So the width is for example only 200px. 
This means, that the time slider is too small to be useful. This problem gets worse, the higher page zoom you use.

**Solution:**
Add an option to have a minimum video width. But do *not* scale height accordingly.

**Code example:**
Here is my proposal:
*After* line 12855 I added:
```javascript 
var minVideoSize = 700;
if (data.isVideo && (minVideoSize > width)) {
    this._oldL = (Post.sizing.wWidth - minVideoSize) / 2 - 1;  // calculates the left coordinate so that the div will be centered
    this._width = minVideoSize; // without this zooming will not work well
    width = minVideoSize; // setting width will set the child element's (<video>) width too, because it inherits the width
}
```

minVideoSize should be gotten from somewhere in the config obviously.

Thank you.

By the way, the similar problem appears with audio files (especially when using a higher page zoom) - the time slider gets very narrow.

**Comment by SthephanShinkufag** [comment]
Sup.
I almost made this option, but then I got a problem. Firefox ignores bigger width.
I don't want to introduce this feature for chrome only.
![webm-cntrl](https://cloud.githubusercontent.com/assets/1059874/21940036/7435008e-d9d3-11e6-9847-a6476047c071.png)

**Comment by UserNaem** [comment]
This looks like a Firefox bug. Why not add this feature and report it on Bugzilla?

**Comment by SthephanShinkufag** [comment]
Even with css `object-fit: fill` controls do not stretch. Very strange.

![webm-fill](https://cloud.githubusercontent.com/assets/1059874/21940941/89398e9c-d9d7-11e6-9f33-fa2f8a35fbad.png)

**Comment by ganego** [comment]
I only use FF (nightly 53 at the moment) and I have the code I posted, in my script.
Works like expected - the control bar is full width like it would be in your chrome screenshot.
I tested it with a completely new profile and tampermonkey and greasmonkey - works.
If you can be bothered you could try if FF52/53 changed something? You can get the nightly (v53) from here: https://www.mozilla.org/en-US/firefox/nightly/all/

**Comment by SthephanShinkufag** [comment]
@ganego, hmmm, really. This bug is already fixed in Nightly.
M'kay, I suppose Firefox devs will apply changes in next stable version.
Check the commit.
