### ISSUE TITLE
dobrochan tripcodes ajax

### ISSUE THREAD

**Issue by Al-faqun** [SthephanShinkufag/Dollchan-Extension-Tools#1011]
"На 2сh.hk, 4chan.org и dobrochan.ru аякс теперь использует JSON API борд вместо загрузки HTML."
Сижу на современной кукле (любой из последних) на доброчане - трипкоды не видны, Вместо них 'Анонимус'.
Сижу на версии от 2016.3.9 - трипкоды работают как надо.
Верните, пожалуйста, а? С сентября уже жду. Апи доброчана никто менять не собирается, надежда только на вас. Спасите мир.

**Comment by Y0ba** [comment]
Пока что можешь найти в скрипте `.jsonBuilder = DobrochanPostsBuilder;` и заменить на `.jsonBuilder = null;`. Позже добавлю настройку.

**Comment by SthephanShinkufag** [comment]
@Al-faqun, доброчановские АПИ не отдают трипкод, к сожалению.
Это, скорее не к нам вопрос, а к тамошним одминам.

http://dobrochan.com/d/res/24370.xhtml#61806
<img src="http://dobrochan.com/src/png/1606/--624.png">

Старые версии не используют АПИ доброчана, поэтому там трипокды есть.

**Comment by SthephanShinkufag** [comment]
`"Настройки"` > `"Посты"` > `"dobrochan: использовать json API"`

Проверяйте.
