### ISSUE TITLE
Что-то не так с проверкой обновлений скрипта

### ISSUE THREAD

**Issue by UserNaem** [SthephanShinkufag/Dollchan-Extension-Tools#1012]
Стояла v16.12.28.0.e3b3e2b, тыкаю "Check now" - отвечает "You have latest version!". Если обновить вручную, ставится v16.12.28.0.f02f6d7.

Firefox 52.0a2 (2017-01-15) (64-bit), Nightly 53.0a1 (2017-01-15) (64-bit).

**Comment by SthephanShinkufag** [comment]
Всё правильно. Это последняя нумерованная версия.
https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/commit/3a05f45e9c5fdc1fcf51c590672ac13889001e85

Я обновляю номер версии по желанию леваой пятки.

Вручную вы берете последний коммит.

**Comment by SthephanShinkufag** [comment]
"Check now" сверяет номер v16.12.28.0. Он в послоедних билдах одинаковый. Сделано это для того, чтобы не заёбывать народ каждодневными обновлениями (которые могут содержать непроверенные баги).
Если я вижу, что скрипт стабилен, и прошёл некий срок, то я обновляю номер версии.

**Comment by UserNaem** [comment]
А, хорошо. Спасибо.

**Comment by SthephanShinkufag** [comment]
Та нема за що. Спрашивайте, родной.
