### ISSUE TITLE
И снова brchan.org

### ISSUE THREAD

**Issue by Oduvanchik7227** [SthephanShinkufag/Dollchan-Extension-Tools#1014]
Степан, прости, но у меня та же проблема, как выяснялось, не ушедшая: ошибка при отправке webm. Версия куклы последняя, автообновление, хром последний. В чем может быть причина? Или надо писать админу?

Вот текст ошибки - http://pastebin.com/nmpKFp9B
Если не сложно, то зайди, пожалуйста, в /rus  и запость webm, может я такой один.

**Comment by SthephanShinkufag** [comment]
Вчера постил webmки, все было ок.

**Comment by SthephanShinkufag** [comment]
Браузер?

**Comment by SthephanShinkufag** [comment]
Щас в хроме проверю.

**Comment by SthephanShinkufag** [comment]
Все постится.
Судя по ошибке, у вас какие-то проблемы со спеллами.
Попробуйте отключить спеллы.
Дайте список ваших спеллов, если можете.

**Comment by SthephanShinkufag** [comment]
Либо найдите сами спелл-источник проблемы, и скажите мне какой, если не хочется палить весь список.

**Comment by Oduvanchik7227** [comment]
Вот спеллы для брчана.

#img[rus,193428](=248,47@337x288) |
#img(=77,34@255x255) |
#img(=7,81@300x300) |
#img[rus,89181](=48,81@600x824) |
#ihash[rus,2258](78120832)

**Comment by Oduvanchik7227** [comment]
Удалил спеллы, ошибка пропала. Спасибо за оперативный ответ. Тему можно закрывать.

**Comment by SthephanShinkufag** [comment]
Исправлю, тогда закрою.

**Comment by Oduvanchik7227** [comment]
Попробовал вычислить неугодный спелл методом исключения - на первый же (#imgrus,193428) мне выдает ошибку "Ошибка: неизвестный спелл: imgrus (строка 1, столбец 8)".

**Comment by SthephanShinkufag** [comment]
```
#img[rus,193428](=248,47@337x288) |
#img(=77,34@255x255) |
#img(=7,81@300x300) |
#img[rus,89181](=48,81@600x824) |
#ihash[rus,2258](78120832)
```

> #imgrus
Вы неправильно его скопировали. Спелла `#imgrus` не бывает, конечно же.

**Comment by Oduvanchik7227** [comment]
Верно, гитхаб порезал скобки. 

Вставил Ваш вариант, ошибка на 1 строке в 5 столбце, применить невозможно.
В общем, я спеллы удалил, ибо морально устарели, но не возникнет ли ошибка снова при скрытии по изображениям или еще каким параметрам?

**Comment by pngcrypt** [comment]
Степан, добавь еще луковый домен плиз: brchanansdnhvvnm.onion

**Comment by SthephanShinkufag** [comment]
Теперь вебмки должны поститься с любыми спеллами.
Формат числа в спеллах, приведенных выше, неверен, и устарел. Вместо запятой в дробном числе нужно использовать точку.

```
Было:
#img[rus,193428](=248,47@337x288)
Надо:
#img[rus,193428](=248.47@337x288)
```

> добавь еще луковый домен плиз: brchanansdnhvvnm.onion

Добавил.
