### ISSUE TITLE
Реквест: помечать в избранном треды, в которых есть непрочитанные ответы на твои посты

### ISSUE THREAD

**Issue by lunafag** [SthephanShinkufag/Dollchan-Extension-Tools#1016]
Форчановое расширение, например, выделяет курсивом.

**Comment by SthephanShinkufag** [comment]
Можно зойпелить, и да.

**Comment by SthephanShinkufag** [comment]
Пробуйте.
Я толком не тестировал, наверняка возможно какое-то неправильное поведение. Пишите, допилю.

**Comment by UserNaem** [comment]
Работает. Спасибо.
![test_-_ _ _-_foxfire 25 01 17 20-11-23](https://cloud.githubusercontent.com/assets/21028464/22295954/87f379a0-e33a-11e6-9d19-693e72873f7b.png)

**Comment by SthephanShinkufag** [comment]
О, забыл скобки убрать. Они там не нужны.

**Comment by lunafag** [comment]
Что-то не заводится у меня. Что делаю: оставляю пост, закрываю вкладку, отвечаю на этот пост с телефона, в другой вкладке обновляю избранное, ответов не видно.  Пробовал на 2ch.hk и форчане. Конфиг нулевой, делал сброс, вот отладочная информация:
`{
	"version": "16.12.28.0",
	"location": "http://boards.4chan.org/b/thread/720227971#p720244722",
	"nav": {
		"ua": "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2950.4 Safari/537.36 OPR/44.0.2475.0 (Edition developer)",
		"Firefox": false,
		"Presto": false,
		"WebKit": true,
		"Chrome": true,
		"Safari": false,
		"isGM": true,
		"isES6": false,
		"isChromeStorage": false,
		"isScriptStorage": false,
		"isGlobal": true,
		"scriptInstall": "Monkey",
		"hasTemplate": true,
		"hasWorker": true,
		"canPlayMP3": true,
		"canPlayWebm": true
	},
	"cfg": {
		"timePattern": "nn+dd+yy+w+hh+ii-?s?s?",
		"hideBySpell": 0,
		"expandPanel": 1,
		"language": 0,
		"cfgTab": "info"
	},
	"sSpells": [
		"#wipe(samelines,samewords,longwords,symbols,numbers,whitespace)"
	],
	"perf": [
		[
			"Imageboard check",
			0
		],
		[
			"Config loading",
			0
		],
		[
			"Init",
			8
		],
		[
			"Read my posts",
			0
		],
		[
			"Replace delform",
			48
		],
		[
			"Parse delform",
			56
		],
		[
			"Parse postform",
			16
		],
		[
			"Init keybinds",
			0
		],
		[
			"Init page",
			4
		],
		[
			"Add panel",
			4
		],
		[
			"Init AJAX",
			0
		],
		[
			"Preload images",
			0
		],
		[
			"Audio links",
			0
		],
		[
			"Video links",
			8
		],
		[
			"Image names",
			4
		],
		[
			"Reflinks map",
			20
		],
		[
			"Apply CSS",
			8
		],
		[
			"Display page",
			0
		],
		[
			"Infinity scroll",
			0
		],
		[
			"Hide posts",
			12
		],
		[
			"Scroll page",
			0
		],
		[
			"Всего",
			188
		]
	]
}`

**Comment by SthephanShinkufag** [comment]
Пошагово и *подробнее*, пожалуйста. Откуда постите, как постите, как и когда открывается окно.
У меня работает.

**Comment by SthephanShinkufag** [comment]
Может, вы не установили последний билд скрипта?
https://raw.github.com/SthephanShinkufag/Dollchan-Extension-Tools/master/Dollchan_Extension_Tools.user.js

**Comment by lunafag** [comment]
Немного поэкспериментировал. Работает, если между постом и ответом на него нет других постов. Если сделать пост, а на него два ответа подряд, то все равно показывает 1 ответ. Если делаю пост, жду, пока появятся другие посты(не ответы на мой), затем отвечаю на свой, то не срабатывает вообще. Как проверял: держу одну вкладку открытой(в каком-нибудь треде, избранное закрыто), отрываю вторую вкладку с каким-нибудь другим тредом на том же имиджборде, оставляю в этом треде пост. Закрываю вторую вкладку. Открываю тред, в который постил(тот, что был во второй вкладке), на телефоне, делаю ответ на пост, который оставил с компьютера. Затем в первой вкладке открываю избранное, жму обновить. Общее количество новых постов отображается верно, но если посмотреть код, то количество ответов на пост равняется нулю.
![untitled](https://cloud.githubusercontent.com/assets/1881351/22307946/0e752616-e356-11e6-858a-7b30c117fc97.png)
![untitled2](https://cloud.githubusercontent.com/assets/1881351/22308007/44eb586e-e356-11e6-99b1-bcb268e8a9a1.png)

**Comment by SthephanShinkufag** [comment]
Обнаружил баг, если открывать избранное в треде другой доски борды.
Если открывать избранное на той же доске, то работает.
Вы смотрели избранное с другой доски?

**Comment by lunafag** [comment]
Видимо с другой. Попробовал с той же, работает.

**Comment by SthephanShinkufag** [comment]
Ну вот, локализовали проблему. Завтра выясню, чому мои посты на другой доске не детектируются.

**Comment by SthephanShinkufag** [comment]
Предварительно, проблема в переменной, хранящей массив моих постов. Для каждой доски массив номеров моих постов свой, я об этом не подумал.

**Comment by SthephanShinkufag** [comment]
@lunafag, проверяйте.

**Comment by Efirion** [comment]
Теперь у текущего домена спрашивается всё избранное. Т.е. обновляя с форчана, у него спрашиваются треды других борд, например ычана.

**Comment by Efirion** [comment]
Кнопка Clear всё ещё проверяет всё избранное. Или так задумано? Сперва думал что оно не работает, оказывается долго идёт от верхних свёрнутых борд к текущей.
