### ISSUE TITLE
Обновление треда иногда сбрасывает позицию скролла

### ISSUE THREAD

**Issue by CherryPerry** [SthephanShinkufag/Dollchan-Extension-Tools#1019]
При обновлении треда позиция скролла сбрасывается куда то вверх иногда. Причины назвать не могу, это происходит редко. Возможно связано с постингом, ибо после него этот баг всплывает быстрее, нежели когда просто обновляешь.
Появилось после обновления хромого до 56 версии.

Хромоног:
Версия 56.0.2924.76 (64-bit)

Кукла:
var version = '16.12.28.0';
var commit = 'bc59572';
<details>

![scroll reset](https://cloud.githubusercontent.com/assets/9081555/22406705/d67ae302-e668-11e6-9d24-60fd9c04da22.gif)

</details>

**Comment by Y0ba** [comment]
Скорее всего дело в карте ответов. Если она появляется (т.е. на пост первый раз отвечают) или становится слишком большой и заходит на вторую строку, то скролл сползает вверх. Возможно перед вставкой постов стоит запоминать позицию скролла и восстанавливать её после, как это сделано со сворачиванием тредов на доске.

**Comment by SthephanShinkufag** [comment]
О, Йоба появился. Шалом! А я тут опять по чуть-чуть скрипт ковыряю.

**Comment by SthephanShinkufag** [comment]
@Y0ba, он там гифку внизу прилепил. Новые посты там не появляются вообще &mdash; просто тупо бросает вверх пр нажатии на кнопку `[Получить новые посты]`.

**Comment by SthephanShinkufag** [comment]
Или я в глаза долблюсь. Гифка короткая. не ясно.

**Comment by Y0ba** [comment]
@SthephanShinkufag по гифке сложно понять, да. Просто я сказал про похожую проблему о которой мне известно.

**Comment by VisualKei** [comment]
Видно, что бросает аж на полсотни постов вверх, так что про появление новых постов и сказать-то нечего. Но вряд ли столько может дать карта ответов, тред-то на автообновлении.

**Comment by SthephanShinkufag** [comment]
Chrome Версия 56.0.2924.76 (64-bit)

Не могу добиться бага.

**Comment by CherryPerry** [comment]
Вечером проверю, появляются ли посты при сбросе скролла или нет.

**Comment by SthephanShinkufag** [comment]
Лучше попробуйте определить алгоритм, при котором гарантированно получается этот баг.

**Comment by CherryPerry** [comment]
При сбросе скролла новые посты появляются.
Но я так и не понял, почему это происходит, пробовал на /test постить.

> Если она появляется (т.е. на пост первый раз отвечают) или становится слишком большой и заходит на вторую строку, то скролл сползает вверх.

Попробовал оба варианта не тесте, не удалось воспроизвести баг.

Можно ли какой-нибудь хук повесить на скролл, чтобы получить, что именно вызывает скролл?

**Comment by Smugl** [comment]
Подтверждаю проблему. Пощу в тред, листаю вниз. Потом, при обновлении, где бы я не находился, кидает к посту или рядом с ним.

**Comment by Oduvanchik7227** [comment]
Аналогичная проблема. Заметил, что "отбрасывать наверх" начинает только после отправки сообщения, иногда на ~10, а иногда и на все ~50 постов.
Chrome 56.0.2924.76 (64-bit)

**Comment by SthephanShinkufag** [comment]
Всё-таки жду ответа, как добиться этого поведения, и от чего оно зависит. Может, от каких-либо настроек. Есть ли такое поведение на других бордах, кроме сосача? Не имею возможности сидеть в хроме на имейджбордах в ожидании этого бага. Пару раз постил &mdash; все нормально. Сообщите, если увидите подозрение на причину этого явления.

**Comment by Smugl** [comment]
У меня все по дефолту, настройки сбрасывал и там и там. Проявляется когда обновляется тред (или автообновление).

**Comment by SthephanShinkufag** [comment]
В консоли ошибок что-нибудь пишет?

**Comment by Smugl** [comment]
Пусто.

**Comment by desudesutalk** [comment]
@SthephanShinkufag у меня был такой баг в моём скрипте. И только в хроме. Вернее он там до сих пор есть, ибо я его так и не победил (ибо забил на скрипт).

Проявляется он не всегда, но проще всего сделать так - открыть тред на автообновлении и переключиться на другую вкладку. Как придёт пара новых постов - вернуться к треду. И вот тогда прям явно увидишь как скролл отбрасывает. В своём скрипте я грешил на собственную рукожопость + какие-то хитрые особенности вебкита для случая когда идёт репеинт вместе с добавлением пачки новых нод.

И есть ещё одно подозрение, чисто фантазия: ссылка с `href="#"` может баговать в хроме и приводит вот к такой прокрутке. Попробуй `href="javascript:;"` - вдруг поможет?

**Comment by SthephanShinkufag** [comment]
> забил на скрипт

Вы больше не разрабатываете ddt?

**Comment by SthephanShinkufag** [comment]
И спасибо за описание, сейчас буду пробовать.

**Comment by desudesutalk** [comment]
Не, я про своего *убийцу куклоскрипта* - Юки-скрипт. Вот его я забросил ибо конкурировать не реально. А с ддт всё в порядке, просто там пока нечего делать.

**Comment by SthephanShinkufag** [comment]
Блджад. ребята, хть убейте. Сидел джва часа на сосаче в Chrome 56 (Tampermonkey). Никак не могу добиться. Уже и извращался по всякому с постингом, с тасованием вкладок, с хешем в адресе, с ответами другим самому себе. Однако, хоть бы что. ЧЯДНТ?

**Comment by SthephanShinkufag** [comment]
Может, кто-то видео запилит? Чтобы с нуля, начиная с открытия браузера.

**Comment by Oduvanchik7227** [comment]
> Может, кто-то видео запилит?
Не знаю, чем тебе это может помочь, но я записяль.
https://youtu.be/RQmt-46kwpk

**Comment by SthephanShinkufag** [comment]
@Oduvanchik7227, спасибо!

**Comment by Oduvanchik7227** [comment]
Так и отбрасывает. Причем теперь даже если не постишь ничего. Ждём обновление Хрома?

**Comment by SthephanShinkufag** [comment]
К сожалению, сколько я не пытался, добиться бага мне не удалось. Видимо, я что-то не так делаю. Честно признаюсь, я хром редко использую. Это мне надо целенаправленно на постоянной основе пользоваться хромом и сидеть на двощах 24/7, чтобы что-то выловить.

**Comment by SthephanShinkufag** [comment]
Может, у вас есть какие-то хроморасширения, которые конфликтуют со скриптом? У меня нет идей.

**Comment by Oduvanchik7227** [comment]
Из активных: Тамперманки, юБлок Ориджин, Session Buddy и friGate. Может, конфликтуют. У меня была проблема с обновлением скрипта (соседний ишью), поэтому отпишусь через сутки-двое, авось баг пропадет сам собой.

**Comment by SthephanShinkufag** [comment]
Попробуйте временно отключить все расширения, и посмотреть.

**Comment by Smugl** [comment]
Есть какие-нибудь движения? В некоторых тредах отписывают о похожих проблемах, у всех кукла. Возможно дело в конфликте с uBlcok, у меня тоже установлен.

**Comment by Y0ba** [comment]
@Smugl Есть. Я скоро добавлю исправление для скролла, который появляется из-за реф-карты (смотри мой первый пост тут). Скорее всего это решит и проблему описанную в этом Issue, по крайней мере скролл при появлении новых постов должен будет пропасть.

**Comment by qxces** [comment]
Да, похоже это как-то связано с ответами на посты. У меня это происходит когда я пишу несколько постов в тред и получаю на них ответы. Далее переключаюсь на другую вкладку или сворачиваю браузер. Потом проходит обновление и меня перекидывает на первый написанный мною пост.

Пробовал выключать все расширения, баг не от этого.

**Comment by Y0ba** [comment]
Попробуйте последнюю версию из гитхаба. Я отключил функции скролла для скриптов макабы, если проблемы были там, то они должны уйти.

**Comment by Smugl** [comment]
Поставил. И всё равно иногда сбрасывает.

**Comment by CherryPerry** [comment]
Версия 58.0.3029.96 (64-bit)
v17.2.13.0.e37e571.es6

Баг больше не проявляется.
