### ISSUE TITLE
Скрытие и просмотр поста при позиции скролла в конце страницы

### ISSUE THREAD

**Issue by CherryPerry** [SthephanShinkufag/Dollchan-Extension-Tools#1022]
Порядок действий:
1. Доскролить до самого конца страницы
1. Скрыть пост (последний или предпоследний)
1. Попробовать посмотреть скрытый пост наведя на него указатель

[https://yadi.sk/i/2fCVt0cr3Cy72X](https://yadi.sk/i/2fCVt0cr3Cy72X)

Если после скрытия скролить страницу, а потом смотреть пост, то баг не проявляется.

Хромоног:
Версия 56.0.2924.87 (64-bit)

Кукла (ES6):
const version = '16.12.28.0';
const commit = '07fde78';

**Comment by SthephanShinkufag** [comment]
Мамо, чому хром такое глючное merde? Я хренею просто.
