### ISSUE TITLE
Псевдокукла на Абучане

### ISSUE THREAD

**Issue by Oduvanchik7227** [SthephanShinkufag/Dollchan-Extension-Tools#1023]
Степан, Наримаша прикрутил свою куклу, можешь её удалить, пожалуйста? Она какая-то дефектная и только глаза мозолит — маленькие кнопки, маленькие тэги, положение не меняется.
![8](https://cloud.githubusercontent.com/assets/23468001/22809798/c00020ac-ef45-11e6-8e4a-45bef88d930f.png)

И вопросик: стикеры отвалились, это твой протест или у меня лагает?
![9](https://cloud.githubusercontent.com/assets/23468001/22809957/b317cc4a-ef46-11e6-9ea0-ddb827a9d312.png)

**Comment by SthephanShinkufag** [comment]
Уже исправлено в последних коммитах.

**Comment by SthephanShinkufag** [comment]
А вот насчет стикеров я посмотрю.

**Comment by Oduvanchik7227** [comment]
А почему у меня виснет, когда нажимаю "Обновить"?

**Comment by SthephanShinkufag** [comment]
> "Обновить"

Что вы имеете в виду?

**Comment by Oduvanchik7227** [comment]
![8](https://cloud.githubusercontent.com/assets/23468001/22810047/57fa1d1c-ef47-11e6-9a37-905f9c3c0d23.png)
Каждый раз так. Может я что делаю неправильно? Грузит до бесконечности. Помню, разок выскочила надпись "Обновление! Тыкай!", но это было давно и неправда, в ручном режиме никогда у меня не обновляется почему-то.

**Comment by SthephanShinkufag** [comment]
Если вы установили скрипт через Tampermonkey, при первой попытке кроссдоменного запроса Tampermonkey спрашивает у вас на разрешение этого действия. Возможно, вы проигнроировали это сообщение, или нажали отмену, вот он вам и блокирует.

У меня все работает.

**Comment by SthephanShinkufag** [comment]
Насчет стикеров - они ведь недоступны же. Нажимаю на каталог стикеров, а там пустая страница. Видимо, Абу віпилил єтот функционал, либо сделал его только для владельцев пасскодов.
https://2ch.hk/makaba/stickers/
При чем тут кукла?

**Comment by Oduvanchik7227** [comment]
Виноват, отныне стрикеры, вероятно, доступны исключительно владельцам пасскода, просто сбросились настройки.
![8](https://cloud.githubusercontent.com/assets/23468001/22810354/4434dcd4-ef49-11e6-916e-b7d4d7f39c8b.png)
Переставил расширение, все заработало, псевдокукла пропала. Спасибо.

**Comment by SthephanShinkufag** [comment]
Насчет обновлений, возможно вы имеете в виду загрузку последнего коммита?
Скрипт детектирует только апдейт версии, который происходит раз в месяц-два.
зайдите в https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/commits/master, прокрутите вниз, и увидите, что коммит  `Version update` был Dec 28, 2016. Я не изменял версию с декабря.
(Хотя, пора бы уже).
Чтобы установить скрипт с последнего коммита, не нужно нажимать "Обновить", в этом нет смысла.
Просто установитье по ссылке со страницы https://github.com/SthephanShinkufag/Dollchan-Extension-Tools

**Comment by SthephanShinkufag** [comment]
> расширение

Вы имеете в виду, переустановили скрипт в тамперамнки?
Я хроморасширение не изменял, оно еще старое.

**Comment by Oduvanchik7227** [comment]
Я сейчас удалил Тамперманки, установил заново, добавил скрипт со страницы http://www.freedollchan.org/scripts/ и дважды протыкал "Разрешать домену всегда". Проблема зависания (при нажатии на "Проверить сейчас") ушла, пишет "У вас стоит самая последняя версия!". 
![8](https://cloud.githubusercontent.com/assets/23468001/22810768/b816f8ba-ef4b-11e6-963e-7862132ea308.png)
Что происходит, когда я тыкаю вот сюда?

**Comment by SthephanShinkufag** [comment]
> Что происходит, когда я тыкаю вот сюда?

Я написал выше. Проверяется версия скрипта. Она равна `16.12.28.0`. 28 декабря 16 года я обновил версию. С тех пор версия не меняется. Я могу на днях обновить номер версии, тогда у вас выскочит "доступна новая версия".
 Версия обновляется, только когда скрипт стабилен и имеет мало багов. Сейчас почти такое время пришло. Я много чего исправил.
Если менять номер версии с каждым исправлением (а коммитов может быть по пять на дню), то это может быть чревато, если вдруг с новым коммитом, содержащим ошибку у всех ляжет скрипт, например.

**Comment by Oduvanchik7227** [comment]
Понял вроде бы. Коммит - фикс бага, версия - стабильно без багов на всех у всех. Когда жму "проверить" - ничего не происходит, пока вы не дадите комманду. Когда обнова с вашей стороны - происходит само и мне ничего тыкать не надо?

**Comment by Oduvanchik7227** [comment]
Так, у меня опять какой-то баг. Посты двоятся, первый из них ни на ссылки, ни на открытие картинки не реагирует, второй в порядке. Как тогда на Новере, один в один. 
![8](https://cloud.githubusercontent.com/assets/23468001/22811435/dd8d861e-ef4f-11e6-9108-6b19e9ebd1dc.png)
![9](https://cloud.githubusercontent.com/assets/23468001/22811439/e01bbe6e-ef4f-11e6-9783-4c182350dbf8.png)

**Comment by Oduvanchik7227** [comment]
![10](https://cloud.githubusercontent.com/assets/23468001/22811489/2ea2e0ee-ef50-11e6-92fd-f027191bd1b5.png)
Даже при простом обновлении треда.

**Comment by Y0ba** [comment]
Это где происходит? Очевидно кукла конфликтует со встроенным скриптом.

**Comment by Oduvanchik7227** [comment]
Это на Абучане. Скрипт в Тамперманки один - доллчан, только что установил заново.

**Comment by SthephanShinkufag** [comment]
Это сосач. Попробуйте отключить куклоскрипт, а потом отключить встроенное автообновление треда макабы. После этого включить скрипт.

**Comment by SthephanShinkufag** [comment]
Без куклоскрипта:

![14861580547870](https://cloud.githubusercontent.com/assets/1059874/22811660/d1b4d150-ef48-11e6-9b79-72481eb06420.jpg)

**Comment by Oduvanchik7227** [comment]
Вроде бы помогло, благодарю. За "зеленый плюс" отдельное спасибо.

**Comment by SthephanShinkufag** [comment]
Теперь надо  сделать, чтобы куклоскрипт подавлял встроенное автообновление. Исправлю - закрою issue.

**Comment by Oduvanchik7227** [comment]
Желательно пяткой в нос.
