### ISSUE TITLE
Поддержка WebM в Edge / Support WebM in Edge

### ISSUE THREAD

**Issue by Kagami** [SthephanShinkufag/Dollchan-Extension-Tools#1024]
Перенос из #941.

Т.к. куклоскрипт теперь поддерживает Microsoft Edge, имеет смысл реализовать поддержку WebM с целью дальнейшей популяризации этого формата.

Дано: Edge начиная с версии 14 (Windows 10 Anniversary Update), поддерживает форматы VP9, Opus и контейнер WebM через MSE API. [Подробнее.](https://brionv.com/log/2016/04/07/windows-10-insider-build-14316-supports-opus-vp9-opus-in-webm-sorta/)

Многие имиджборды, однако, отображают загруженные пользователями видео через обычный элемент `<video>`, который в Edge напрямую не проигрывает WebM. Один из вариантов решения проблемы состоит в том, чтобы загрузив скриптом видео, на лету разделить его на два файла, в каждом из которых присутствует только один трек (VP9 или Opus) и скормить их браузеру через вызовы MSE. Экспериментальная реализация этого способа доступна [здесь](https://github.com/Kagami/webmify).

Это, однако, не решает всех проблем. Многие загружаемые видео имеют треки в форматах VP8 и/или Vorbis, которые в Edge не поддерживаются совсем. Есть вариант решения через проект [ogv.js](https://github.com/brion/ogv.js), в котором как раз реализована поддержка декодирования VP8/Vorbis в Edge в реальном времени на JavaScript. (Может возникнуть желание добавить туда и VP9/Opus, но это будет априори медленнее нативного кода, декодирующего поток через MSE API. Тем более что для VP9 нужно намного больше ресурсов.)

Т.е. предлагаемый черновник реализации:
* Использовать метод webmify для проигрывания VP9/Opus
* Использовать ogv.js для проигрывания VP8/Vorbis

Готов помочь по всем техническим вопросам, связанным с WebM.

Также есть вероятность, что поддержка дополнительных форматов `<video>` в Edge решается какими-нибудь плагинами или аддонами (по аналогии с Internet Explorer), но я мало что про это знаю.

**Comment by desudesutalk** [comment]
Лучше допили свой юзерскрипт. Добавь туда ogv.js и [webp.js](http://webpjs.appspot.com/). Его тогда можно будет использовать где угодно, а не только на бордах и с куклоскриптом.

(*просто не хочу чтоб из-за майкрософтоподелия куклоскрипт потяжелел на два с половиной мегабайта*)

**Comment by Y0ba** [comment]
Ну webmify вполне можно интегрировать, благо webm-парсер в скрипте уже есть. А вот декодер VP8/Vorbis только в виде отдельного скрипта. Можно добавить в API куклы событие открытия видео, которое этот второй скрипт будет перехватывать и обрабатывать.

**Comment by desudesutalk** [comment]
Лучше сделать хук и отдельный скрипт который решает все проблемы. А так как вебмки популярны на бордах, описать этот доп.скрипт в инструкции по установке куклы на эдж.

**Comment by Kagami** [comment]
>просто не хочу чтоб из-за майкрософтоподелия куклоскрипт потяжелел на два с половиной мегабайта

Включать ogv.js в релиз, думаю, не стоит. Есть вариант с подгрузкой куда-нибудь в localStorage при активации опции в настройках.

>Лучше допили свой юзерскрипт

Я думал об этом, но я не знаю (не придумал) как решить задачу в общем виде. Т.е. чтобы любой `<video>` на странице был соответствующим образом исправлен. А в куклоскрипте уже имеется поддержка кучи имиджборд, за пределами которых WebM не особо-то и нужен (т.к. сайловладелец может просто MP4 использовать или переписать на MSE API).
К тому же, куклоскрипт очень популярен, а про какой-то специальный юзерскрипт очень мало кто знает/будет знать. Людям просто негде брать информацию об этом, а устный обмен работает плохо.

>Лучше сделать хук и отдельный скрипт который решает все проблемы

Да, как вариант. Только я думаю лучше инструкцию не где-то на отдельной странице, которую никто не прочитает (серьёзно, пользователи практически не читают документацию), а прямо в настройках рядом с активацией подобной опции.

**Comment by Y0ba** [comment]
> а прямо в настройках рядом с активацией подобной опции.

Лучше прям в открытом окошке видеофайла (типа кодек не поддерживается, скачайте скрипт по ссылке, чтобы посмотреть видеофайл). Тогда можно будет интегрировать и в сафари, а то там сейчас полуработающий VLC-плагин.

**Comment by desudesutalk** [comment]
@Y0ba,  ну вообще отлично звучит.

Кстати, есть хоть одна борда куда можно загрузить ВебП?

**Comment by Kagami** [comment]
Да, так тоже хорошо. Правда, у сафари тогда будут поддерживаться только VP8/Vorbis. Которые по иронии как раз и наиболее популярные в обычных вебм-тредах.
И да, ogv.js довольно-таки экспериментален, на слабых устройствах на больших разрешениях он, вероятно, может нехило тормозить. На обычном десктопе какой-нибудь VP8 480p (довольно распространённый вариант), впрочем, должен работать нормально.

@desudesutalk есть erlach.co с BPG.

**Comment by desudesutalk** [comment]
> erlach.co с BPG.

Ого, такой фантастики не ожидал.

**Comment by SthephanShinkufag** [comment]
@Y0ba 
> в сафари сейчас полуработающий VLC-плагин

VLC Web Browser plugin package для последних iOS не работает: http://www.videolan.org/vlc/download-macosx.ru.html
Поддерживается устареший Mac OS X 10.5 Leopard. У меня есть виртуалки с El Capitan и Yosemite. В них плагин не устанавливается вообще.

**Comment by SthephanShinkufag** [comment]
И да, если честно тоже не хочу добавлять в куклу десяток килобайт кода ради Edge. Идеально было бы выводить сообщение с предложением скачать webmify/ogv.js.

**Comment by Kagami** [comment]
При таком подходе остаётся проблема генерализированного исправления проигрывания `<video>` с WebM.

На многих сайтах элемент  `<video>` добавляется на страницу динамически. Это значит надо инджектить юзерскрипт вообще на всех страницы всех сайтов и динамически проверять все добавляемые/изменяемые ноды? Звучит неразумно. Возможно, есть вариант лучше, но я его не знаю.

Если же куклоскрипт каким-то образом, используя свои знания о списке имиджборд и особенностям проигрывания WebM на них, может передать во внешний скрипт, допустим, DOM-элемент, который нужно проиграть, это было бы намного проще. (ogv.js не юзерскрипт, кстати, а библиотека.)

**Comment by SthephanShinkufag** [comment]
У куклоскрита есть (API)[https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/wiki/dollchan-api].Мы можем добавить новое событие при открытии вебмки. Ваш скрипт будет только слушать `onmessage`.

**Comment by Kagami** [comment]
Так отлично, вроде как всё должно работать. А какие идеи насчёт активации? Просто скопировать список имиджборд из куклы?

**Comment by SthephanShinkufag** [comment]
Ну, если вы хотите ограничить свой скрипт несколькими имиджбордами, можно взять список из https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/wiki/supported, и то там 85% вебмки не поддерживают. Можно ораничиться сосачем, форчаном, краутчаном, 8чаном, и еще парочкой на ваш вкус.

**Comment by SthephanShinkufag** [comment]
Я сейчас чутка занят, в общем, вечером добавлю событие `showwebm` в API куклы.

**Comment by desudesutalk** [comment]
> динамически проверять все добавляемые/изменяемые ноды? Звучит неразумно.

Есть такой метод: https://davidwalsh.name/detect-node-insertion Можно так ждать инсерта тега `<video>` и обрабатывать его.

Так как скрипт выйдет монстром на несколько мегабайт, то его надо запускать только там где он действительно нужен (а для идиотов сделать чек что мы в Едже, иначе сразу выходить). По этому разрешения скрипат должны быть прописаны чётко, а в инструкции к нему описать как через настройки Тамперманки запустить его на сайте которого нет в разрешениях.

**Comment by Kagami** [comment]
@SthephanShinkufag А, я не знал просто, что в куклоскрипте `@include *`. Но ведь полный список можно выдрать из скрипта из массива `ibEngines`, так? Я так понимаю, имиджборды с поддержкой WebM это все домены на движках макаба, форчан, 8чан и краутчан в этом массиве?

>вечером добавлю событие showwebm

Ага, спасибо, для начала попробую webmify просто на него перевести.

@desudesutalk

>https://davidwalsh.name/detect-node-insertion

Интересно.

>Так как скрипт выйдет монстром на несколько мегабайт

Есть же вариант подтягивать основное тело уже после успешного детекта. Звучит слегка по-вирусному, конечно.

>а в инструкции к нему описать как через настройки Тамперманки запустить его

Тоже неплохой способ.

В принципе, если движков с поддержкой WebM немного и сайты надо всё равно прописывать, то особая поддержка от куклоскрипта и не нужна получается. Разве что с точки зрения юзабилити, сразу объяснить пользователям, что надо сделать, чтобы вебмки заработали.

---

В идеале, конечно, такая проблема должна решаться чем-то вроде плагина, который активируется браузером для неизвестных кодеков. Но не уверен, что Edge вообще поддерживает что-либо подобное. А в Safari так ещё и куча проблем с ним (то ли недоработка его авторов, то ли API кривое и не позволяет сделать хорошо).

**Comment by desudesutalk** [comment]
@Kagami, если подумать то можно намутить довольно интересный проект который сделает хорошо много кому. А именно написать экстеншен который будет минимальными затратами детектить на всех открываемых страничках присутствие вебэм/вебп (а то и bpg) и уже если надо вживлять весь нужный ворох толстых библиотек и отображать контент.

Ещё могу напомнить про [Range request](http://stackoverflow.com/questions/15561508/xmlhttprequest-206-partial-content) - можно вытянуть первый килобайт к примеру и по нему принять решение можем ли мы это как-то воспроизвести.

В итоге может выйти довольно годно.

**Comment by Kagami** [comment]
Так ведь WebP/BPG не загрузишь на сайт, который его не поддерживает. Тут же вся проблема в том, что на сайте фича (WebM) сделана только для двух браузеров.

**Comment by desudesutalk** [comment]
Но ты же сам мне дал ссылку на борду которая поддерживает bpg.

Ну ладно, я всего лишь предложил идею. Не настаиваю.

**Comment by SthephanShinkufag** [comment]
@Kagami 
> Но ведь полный список можно выдрать из скрипта из массива ibEngines, так?

Часть борд детектируется по ibEngines. Особенно это касается Tinyboard и Vichan.
Там скрипт детектирует имиджборду по нодам.

**Comment by SthephanShinkufag** [comment]
И вы имели в виду ibDomains, наверно.

**Comment by Kagami** [comment]
Ага, понятно. Тогда можно добавить основные, а дополнительные пусть пользователь вводит сам через настройки.

Я так думаю, для начала можно сделать по-простому — требовать наличие куклоскрипта, использовать его API, требовать ввод дополнительных доменов. А потом уж можно подумать как улучшить.

**Comment by SthephanShinkufag** [comment]
Зойпилил.
Юзерскрипт для проверки:

```js
// ==UserScript==
// @name            DollchanAPI webm listener test
// @namespace   DollchanAPI
// @version         0.1
// @include         *
// ==/UserScript==

function getDollchanAPI() {
	return new Promise((resolve, reject) => {
		var onmessage = ({ data, ports }) => {
			if(ports && ports.length == 1 && data == 'de-answer-api-message') {
				clearTimeout(to);
				document.defaultView.removeEventListener('message', onmessage);
				resolve(ports[0]);
			}
		};
		document.defaultView.addEventListener('message', onmessage);
		document.defaultView.postMessage('de-request-api-message', '*');
		var to = setTimeout(() => {
			document.defaultView.removeEventListener('message', onmessage);
			reject();
		}, 5000);
	});
}

function runAPI() {
	getDollchanAPI().then(port => {
		port.onmessage = ({ data }) => {
			switch(data.name) {
				case 'registerapi':
					for(let key in data.data) {
						if(data.data[key]) {
							console.log(`API ${ key } зарегистрирован.`);
						} else {
							console.log(`API ${ key } недоступен.`);
						}
					}
					break;
				case 'webmshow':
					console.log('Webm открыт: ', data.data);
					break;
			}
		};
		port.postMessage({ name: 'registerapi', data: ['newpost'] });
		port.postMessage({ name: 'registerapi', data: ['webmshow'] });
	}).catch(() => console.log('Старая версия куклы без поддержки API.'));
}

setTimeout(runAPI, 0);
```

**Comment by SthephanShinkufag** [comment]
Сразу скажу, тестил в Лисе. Приеду домой, проверю на десятке в Edge. Заодно надо реализовать проверку возможности воспроизведения и сообщение о необходимости установки стороннего скрипта.

**Comment by Kagami** [comment]
Спасибо!

>DollchanAPI.notify('webmshow', src);

А `obj` можно ещё? Саму видео-ноду т.е.

**Comment by Y0ba** [comment]
Я уже предложил добавить `ID`. Ноды таким образом передавать нельзя.

**Comment by SthephanShinkufag** [comment]
```js
console.log('Webm открыт: ', document.querySelector('video[src="' + data.data + '"]'));
```

**Comment by Kagami** [comment]
Точно, протупил.
Кстати, а вот в этот code path попадают MP4 видео, которые разрешает тот же 8chan?

**Comment by SthephanShinkufag** [comment]
@Kagami , теперь не попадают.

**Comment by desudesutalk** [comment]
А если захочется чтоб попадали?

**Comment by SthephanShinkufag** [comment]
> А если захочется чтоб попадали?

А надо? Товарища интересуют только вебмки.
API всегда можно расширить, ежеличо.

**Comment by SthephanShinkufag** [comment]
Могу откатить последний коммит, может я не так понял, и вам mp4 тоже надо.

**Comment by Kagami** [comment]
Нет, так лучше. (Я мог бы и сам проверить, конечно, но так по-моему правильнее. Всё-таки событие API webmshow не должно возвращать MP4.)

**Comment by desudesutalk** [comment]
Мне кажется лучше вынести проверку расширения файла в скрипт срабатывающий на вызов. А колл назвать `videoshow`. И ещё не забыть про мрзешки - может кому-то захочется прикрутить таким образом свой плеер с клёвыми фичами?

**Comment by desudesutalk** [comment]
Кстати реально, есть для доброчана скрипт который умеет кроме всего прочего играть FLAC (доброчан его даёт загружать) и при этом ещё показывает обложку трека если есть и что-то там ещё прикольное делает.

Я бы сделал вообще `mediaplay` на все случаи жизни.

**Comment by Kagami** [comment]
О, точно, вебмки ещё на доброчане есть. Надо будет список составить.
Ну мне особо без разницы. Главное, чтобы не хуже, чем сейчас.

**Comment by SthephanShinkufag** [comment]
```js
				case 'expandmedia':
					const src = data.data;
					console.log(src.match(/\.([^&\.]+)(?:&|$)/i)[1] + ' открыт:', src);
					break;
```

**Comment by SthephanShinkufag** [comment]
Правда, сейчас оно посылает только то, что скрипт может обрабатывать &mdash; картинки и видео.
jpg, png, gif, webm, mp4

А вот на mp3, flac, pdf и прочее &mdash; события нет. Срипт их не обрабаотыват, они открываются в новой вкладке.

**Comment by SthephanShinkufag** [comment]
Добавил [описание](https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/wiki/Dollchan-API#2-expandmedia--%D1%80%D0%B0%D1%81%D0%BA%D1%80%D1%8B%D1%82%D0%B8%D0%B5-%D0%BA%D0%B0%D1%80%D1%82%D0%B8%D0%BD%D0%BE%D0%BAwebm)

**Comment by SthephanShinkufag** [comment]
У вас могут возникнуть вопросы, чому такой странный способ получить расширение файла

```js
const ext = src.match(/\.([^&\.]+)(?:&|$)/i)[1];
```

если можно же

```js
const ext = src.split('.').pop();
```

Тут есть подводный камень из-за тиниборд-досок. Там ссылка на вебмки имеет вид: 
/player.php?v=https://media.8ch.net/file_store/c8ffa85eefded7750fb04566119d458bf7e0dddc92308450d0d894834685ba8e.webm&t=Have%20you%20ever%20had%20a%20dream%20like%20this%20%28Metal%20Remix%29.webm&loop=1

**Comment by SthephanShinkufag** [comment]
А, не, ребята, я вас обманул!
В скрипте уже есть преобразовывалка

```js
			if(aib.tiny) {
				src = src.replace(/^.*?\?v=|&.*?$/g, '');
			}
```
АПи отдает правильный src! Значит, смело можно пользовать

```js
const ext = src.split('.').pop();
```

Поправил пример в описании.
Гомен насай.

**Comment by SthephanShinkufag** [comment]
Суть токова: если в MS Edge нет слушателей события `expandmedia`, то уведомлять о необходимости скачать скрипт @Kagami . Ссылку я пока там не указал, тому що пока не знаю.

**Comment by Kagami** [comment]
Ага, я тогда отпишу как сделаю.

**Comment by SthephanShinkufag** [comment]
Я завтра вечером улетаю в тёплые страны на некоторое время, так что вы без меня потерпите пару недель, bitte.
Может, @Y0ba в дело таки втянется.
Ежели что, с телефона буду следить.

**Comment by VisualKei** [comment]
@SthephanShinkufag, хорошего отдыха!

**Comment by Kagami** [comment]
В общем, перевёл webmify на куклоапи. Слегка потестил на дваче и 8чане, заявленный функционал работает (VP9/Opus после полной загрузки), вроде всё ок.

ogv.js теперь буду прикручивать для VP8/Vorbis. В Safari тоже ogv.js должен работать, т.е. сообщение о необходимости установки скрипта надо и для неё выводить (если это не будет конфликтовать с VLC-плагином, конечно). Ну и муксинг на лету надо сделать, а то долго ждать, пока целиком файл загрузится.

**Comment by SthephanShinkufag** [comment]
Есть запощенные VP9 где-нибудь? Перекликал кучу вебмок на сосаче, там везде vp8, однако.

**Comment by Kagami** [comment]
В этом треде в начале например: https://2ch.hk/media/res/74282.html

**Comment by SthephanShinkufag** [comment]
@Kagami, хм, ну вот во втором посте №74284 есть vp9/opus. Да, уже не пишет, что формат не поддерживается, но идет бесконечное ожидание!

**Comment by SthephanShinkufag** [comment]
Edge 14.14393. Что-то ни одна vp9 вебмка не воспроизводится. Может, это старая версия? Просто мне лень ставить десятку, сижу с виртуальной машины.

**Comment by Kagami** [comment]
Только что попробовал с последней куклой, у меня работает. Стоит always on для VP9 в about:flags?

**Comment by SthephanShinkufag** [comment]
нет)))

**Comment by Kagami** [comment]
Вот здесь инструкция: https://github.com/Kagami/webmify#install
Ещё перезапустить надо.

**Comment by SthephanShinkufag** [comment]
Невнимательность, ой да.
Issue закрывать, или еще чего пилить вдруг будете? ogv.js, все дела.

**Comment by Kagami** [comment]
Пока нет, может позже. Закрою тогда пока.

**Comment by SthephanShinkufag** [comment]
Кстати, vp8 тоже воспроизводятся, но только звук, без видеоряда.

**Comment by Kagami** [comment]
Ага, это если Opus дорожка попадается.
