### ISSUE TITLE
Сделать ссылки кликабельными на Абучане

### ISSUE THREAD

**Issue by PekaFat** [SthephanShinkufag/Dollchan-Extension-Tools#1026]
Возможно ли это с помощью куклы?
В [каталоге](https://2ch.hk/b/catalog.html) они кликабельные, а в самих тредах - нет.
![image](https://cloud.githubusercontent.com/assets/13280748/22861225/0039651e-f12d-11e6-8804-75f0f10a6c22.png)
![image](https://cloud.githubusercontent.com/assets/13280748/22861226/05e34b24-f12d-11e6-9abf-9ecf46e06a22.png)

Неудобно постоянно выделять вручную все ссылки.

**Comment by SthephanShinkufag** [comment]
Я тут ничего поделать не могу, увы. Абу-кодеры накодили какую-то ахинею:

```js
Stage('Удалятель ссылок, уродливый, как твоя мамаша','linkremover',    Stage.DOMREADY,     function(){
	if(!window.thread.board) return; //не запускаем на главной
    //link remover
	window.linkremover = function() {
		if(window.thread.board=='b') {
			var x = $("a[href^='http']:not([href*='store.steampowered.com/app/444520']):not([href*='life.ru']):not([href*='2ch.pm']):not([href*='2ch.hk']):not([href*='2ch.pm']):not([href*='twitch.tv/abu1nyasha']):not([href*='2chtv.ru']):not([href*='telegram.me/twochannel']):not([href*='telegram.me/dvachannel']):not([href*='change.org']):not([href*='vk.com/ru2ch']):not([href*='itunes.apple.com']):not([href*='youtube.com']):not([href*='youtu.be']):not([href*='twitter.com']):not([href*='2channel.hk'])").contents().unwrap();
		}
	};
	linkremover();
```

ссылки принудительно удаляются уже после куклоскрипта. Причем очень коряво.

Кланяйтесь в ноги Абу, пусть выпилит эту х**ню.

**Comment by SthephanShinkufag** [comment]
Можно конечно сделать setTimeout... Но все это выглядит очень глупо - сначала выпиливание ссылок макабой, потом запиливание куклоскриптом. Вся страница будет дергаться.

**Comment by SthephanShinkufag** [comment]
Не хочу бороться с маразмом владельца 2ch.hk
Если он решил сделать этот корявый костыль, значит он так хочет.
Просите, чтоб выпилил, в общем.

**Comment by VisualKei** [comment]
`not([href*='life.ru'])`
Лiл. Это походу вовсе не маразм.

**Comment by desudesutalk** [comment]
![image](https://cloud.githubusercontent.com/assets/7350093/22865522/0f25efda-f177-11e6-93ea-73113476a50a.png)

**Comment by desudesutalk** [comment]
@SthephanShinkufag напомни пожалуйста у тебя была идея своей борды, что с ней? И ещё у тебя был клёвый собиратель статистики борд. Не могу вспомнить или найти ссылку.

**Comment by SthephanShinkufag** [comment]
Ага. Причем я визуально замечаю. как вначале загружаются нормальные ссылки, а потом через полсекунды они преобразовываются в текст.
А потом через полсекунды еще куклоскрипт их будет обратно преобразовывать, хех?
Причем `window.linkremover` переопределяется, и приравнять его `window.linkremover = function() {}` при инициализации куклы не возымеет эффекта.

**Comment by SthephanShinkufag** [comment]
@desudesutalk , борда существует! Полу-самописная, за основу взял легкий и примитивный tinyIb. У меня тут есть халявный хостинг, но там поддерживается только php5.3, и тиниборд я туда припаять не могу. А под своей кроватью сервер держать лень. Все собираюсь допилить разметку и выкатить в широкие массы, там делать не много.
Собиратель статистики пока отключен.

**Comment by desudesutalk** [comment]
Ого! Ну тогда будем с нетерпением ждать открытия.

**Comment by VisualKei** [comment]
Кстати, гипотетический вопрос - а можно было бы это обойти, запретив переопределение через `Object.defineProperty()`, или есть какие подводные камни?

**Comment by SthephanShinkufag** [comment]
@VisualKei, кстати, весьма годная идея, я как-то не догадался. Щас попробую.

**Comment by SthephanShinkufag** [comment]
`Object.defineProperty(window, "linkremover", { writable: false, configurable: false });`

Работает! Щас запилю коммит!
@VisualKei, данке вери вери мач!

**Comment by VisualKei** [comment]
Смотри, опять абу скрипт блочить начнёт, лол.
В прошлый раз ты его конечно оче годно на чистую воду вывел.
