### ISSUE TITLE
Дублирование постов на сосаке

### ISSUE THREAD

**Issue by Xowk** [SthephanShinkufag/Dollchan-Extension-Tools#1028]
В последние дни обнаружилось, что посты на сосаке появляются в двух экземплярах. Выглядят они одинаково, но 1 некликабельный и без номера, а второй нормальный. Это касается только новых сообщений. При обновлении треда дубли исчезают. В сочетании со скачками вверх, как-то совсем грустно становится. Браузер хромой 56.0.2924.87 (64-bit).

**Comment by qxces** [comment]
Подтверждаю. Возникает после автообновления треда.
![2017-02-13 17_57_18- 27 _b_ - webm- p p a](https://cloud.githubusercontent.com/assets/23480616/22888186/e89a5dde-f215-11e6-9ebc-521722569ec9.png)
![2017-02-13 17_57_04- 26 _b_ - webm- p p a](https://cloud.githubusercontent.com/assets/23480616/22888197/ec827fd0-f215-11e6-8ead-06ed1b4c4f8f.png)

**Comment by VisualKei** [comment]
[Процидурку](https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/issues/1023#issuecomment-278839465) проделали?

**Comment by qxces** [comment]
Да, все работает. Можно закрывать, думаю.
