### ISSUE TITLE
Скролл треда на харкаче

### ISSUE THREAD

**Issue by anonymous909090** [SthephanShinkufag/Dollchan-Extension-Tools#1030]
Время суток доброе.
Чет уже неделю или около того слетает прокрутка в тредах. Такое подозрение, что слетает до последнего на момент открытия поста ибо f5 в принципе временно решаете проблему. Выглядит само явление как перешел в другой  тред, читаешь там себе, возвращаешься (отработало автообновление) - ты посреди треда.
Бровзер хром, борда абучан, скрипт v17.2.13.0.3a65251.es6. Я такой не один страдаю (страдал), остальные то ли молчат и ленятся issue создавать, то ли хер пойми, починили как-то.
Спасибо.

ПС: алсо новый зеленый цвет "есть новые посты не в твой адрес" в иконках заголовков вкладки мне не нравится, старый желтый был лучше.

**Comment by Y0ba** [comment]
Попробуйте последнюю версию из гитхаба. Я отключил функции скролла для скриптов макабы, если проблемы были там, то они должны уйти.

**Comment by anonymous909090** [comment]
Не помогло. Алсо, не упомянул, что периодически это возникает и при жамкании руками на "обновить тред". Не всегда но иногда - при условии новых постов - прокрутка мгновенно улетает.

**Comment by CherryPerry** [comment]
const version = '17.2.13.0';
const commit = '508cea3';

Не помогло.

**Comment by SthephanShinkufag** [comment]
Йоба, верни назад скролл, если народ пишет что не помогло.

**Comment by anonymous909090** [comment]
Бумп, епт :)

**Comment by SthephanShinkufag** [comment]
Duplicated issue. Refs to #1019
