### ISSUE TITLE
Дублирование постов.

### ISSUE THREAD

**Issue by Garitos** [SthephanShinkufag/Dollchan-Extension-Tools#1032]
При автообновлении треда дублируются посты.  причем один из них неактивный - на него ни ответить. ни картинку просмотреть и т. д. а второй - обычный.
Версия v17.2.13.0.3a65251
Chrome 56.0.2924.87
Win 7

**Comment by Y0ba** [comment]
Уже исправлено в последней версии с мастера: [ES5](https://raw.github.com/SthephanShinkufag/Dollchan-Extension-Tools/master/Dollchan_Extension_Tools.user.js), [ES6](https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/raw/master/src/Dollchan_Extension_Tools.es6.user.js)

**Comment by Garitos** [comment]
Потрясающе. Пока я дописывал описание - уже ответили.

**Comment by Smugl** [comment]
Обновите хромовское расширение. Скрипт хром режет при перезапуске.

**Comment by SthephanShinkufag** [comment]
> Обновите хромовское расширение

Done
