### ISSUE TITLE
Replacing name image for brchan.org

### ISSUE THREAD

**Issue by Lourens-Rich** [SthephanShinkufag/Dollchan-Extension-Tools#1033]
Sorry, could you help me with autoreplacing download name of image on brchan.org? This imageboard show original name of files before upload. Thank you for any answer from you.

**Comment by WagonOfDoubt** [comment]
This can be done quite easily:
In class Brchan function init:
```javascript
let imgLinks = $Q('.fileinfo > a');
for (let a of imgLinks) {
    let filename = $q('.postfilename', a.parentElement).innerText;
    a.setAttribute('download', filename);
}
```
Here is my [commit](https://github.com/WagonOfDoubt/Dollchan-Extension-Tools/commit/ed512c473acdba60c1aada5bc78c98e6940174f9) for testing.
I would make a pull request, but there is more in it. This feature is quite handy and could be implemented for other boards, but it would not be as elegant. Also it most probably should be optional.
Короче, @Y0ba, сделай.

**Comment by Lourens-Rich** [comment]
@WagonOfDoubt, thank you! I'm so happy!

**Comment by SthephanShinkufag** [comment]
> Короче, @Y0ba, сделай.

Сделал.
