### ISSUE TITLE
Работа с NoScript

### ISSUE THREAD

**Issue by desudesutalk** [SthephanShinkufag/Dollchan-Extension-Tools#1037]
Я не знаю почему детект носкрипта не пашет, но мне пришлось изменит в скрипте дефолт на `nativeXHRworks = false` чтоб постинг под носкриптом заработал. На мой взгляд эту опцию нужно сделать так чтоб `GM_xmlhttpRequest` использовался всегда когда доступен.

И ещё такой момент, `GM_xmlhttpRequest` не отправляет `referer` (а то и вообще никакие заголовки), так что его надо указывать самостоятельно. Vichan/Infinity проверяют реферер и без него постить не дают.

**Comment by zaibatel** [comment]
Новая версия скрипта с поддержкой гуглкапчи не дает постить при отключении абу-скриптов. Почему так?
Раньше можно было выключить весь js на майлоче и включить только куклу.

**Comment by SthephanShinkufag** [comment]
@desudesutalk

> GM_xmlhttpRequest не отправляет referer

Удалите Greasemonkey, ставьте Violentmonkey/Tampermonkey.  У гризманки наблюдаются проблемы с реферером, на vichan-досках даже не даёт постить (8ch.net, lolifox.org, etc).
Я считаю эту проблему багом обезьяны.

**Comment by SthephanShinkufag** [comment]
@zaibatel 

Мало того, вы не сможете и без куклы постить.

Вам нельзя блокировать `https://www.gstatic.com/recaptcha/api2/v1514934548259/recaptcha__ru.js`

Скрипт recaptcha__ru.js отвечает за рекапчу, он её генерирует.

**Comment by soredake** [comment]
https://github.com/greasemonkey/greasemonkey/issues/2599
https://github.com/greasemonkey/greasemonkey/pull/2723
