### ISSUE TITLE
(2chan.su) Новые посты в тредах подгружаются после формы удаления постов

### ISSUE THREAD

**Issue by malamut2014** [SthephanShinkufag/Dollchan-Extension-Tools#1039]
http://bbs.2chan.su/
Движок -- модифицированная TinyIB (https://github.com/SecondChannel/BBSEngine)

**Comment by malamut2014** [comment]
А ещё треды неправильно разворачиваются и ссылки на посты (>>no) криво работают

**Comment by SthephanShinkufag** [comment]
Борда мертва.
