### ISSUE TITLE
Неполная предзагрузка картинок

### ISSUE THREAD

**Issue by AnotherShoha** [SthephanShinkufag/Dollchan-Extension-Tools#1043]
После какого-то из обновлений Хрома кукла будто отваливается на половине страницы. Если открыто более одной страницы мейлача, то подгружается только до ~100 постов, дальше blob на пикчах и не открываются webm-ки . Для меня сама суть куклы в пред загрузе картинок (люблю читать дохлые треды). Как это можно исправить?

**Comment by Y0ba** [comment]
Скорее всего проблема в том, что все изображения сохраняются в ОЗУ, а его не хватает если их слишком много. Можно сохранять всё это в IndexedDB (там уже можно занимать до половины свободного места на жёстком диске). Функционал останется тем же (т.е. нормально чтение дохлых тредов и возможность их полного сохранения средствами куклы). Ещё лучше можно было бы сделать при помощи ServiceWorkers и Cache API, но из юзерскрипта их использовать никак нельзя.

**Comment by AnotherShoha** [comment]
Я тоже подумал, что дело в оперативке, но проблема в том, что больше уже некуда
![12](https://cloud.githubusercontent.com/assets/26465738/24011712/ce1d1a36-0a7b-11e7-86f8-8420963ebd6a.PNG)

Искал способ искусственно дать Хрому (ещё!) больше, но внятного результата нет. Если что, куклу использую из под Tampermonkey, а не отдельным плагином. Как поправить?

**Comment by Y0ba** [comment]
Скорее всего это внутреннее ограничение. У меня уже есть наполовину написанный патч. Может даже сегодня допишу до конца.

**Comment by AnotherShoha** [comment]
Лучи добра тебе. А то я пробовал использовать браузер (вместо Хрома), но дерьмо зашло слишком далеко. Но это скорее вина Макаки. Помню, раньше /b нормально работал на 10 страниц и дохлые треды были с пикчами ещё день

**Comment by SthephanShinkufag** [comment]
Duplicated issue => #1002
