### ISSUE TITLE
Многочисленные баги на 8ch.net

### ISSUE THREAD

**Issue by lordtenma** [SthephanShinkufag/Dollchan-Extension-Tools#1044]
Скрипт конфликтует с внутренним скриптом борды.
Не прогружается каптча
Не работает редирект после отправки поста
Не подсвечиваются свои посты
На работает видео превью

**Comment by SthephanShinkufag** [comment]
> Не прогружается каптча

На какой борде? Что за браузер? Каков тип установки сприпта?
Зашел в /test/ - выскакивает попап с предложением ввести капчу. Ввёл, отправил пост, все нормально.

> Не работает редирект после отправки поста

Что за редирект?

> На работает видео превью

Тоже не понял, что вы имеете в виду.

Подробнее, bitte. распишите по каждому багу. Можно с картинками.

**Comment by lordtenma** [comment]
>На какой борде? Что за браузер? Каков тип установки скрипта?

/V/, Firefox Nighty 55.0a1, через макаку 3.10
>Тоже не понял, что вы имеете в виду.

Пикрелейтед
https://puu.sh/uN9uq.png
>Зашел в /test/ - выскакивает попап с предложением ввести капчу. Ввёл, отправил пост, все нормально.

Не знаю из за того ли что я куки почистил, но буквально только что попробовав отправить пост каптча начала появляться. Однако попап висит всего 5 секунд и исчезает прямо во время ввода каптчи, ввести ее за это время получилось попытки с десятой.
>Что за редирект?

После отправки пост отправлялся бесконечно, если обновить страницу то пост оказывался запощен но скрипт не определял его как "свой" пост. Пофиксилось само собой вместе с каптчей.

**Comment by SthephanShinkufag** [comment]
> попап висит всего 5 секунд и исчезает

Настройки - Общее - Автоматически закрывать уведомления
Отключите же.

**Comment by SthephanShinkufag** [comment]
Вообще эту опцию надо выпилить, не знаю, нужно ли такое поведение кому-то.

**Comment by lordtenma** [comment]
>Настройки - Общее - Автоматически закрывать уведомления
>Отключите же.
Спасибо, помогло.
