### ISSUE TITLE
Оставлять оригинальное имя файла при скачивании

### ISSUE THREAD

**Issue by WagonOfDoubt** [SthephanShinkufag/Dollchan-Extension-Tools#1045]
В продолжение #1033.

На большинстве борд пирилейтед сохраняется на сервере с именем из цифр. Оригинальное имя файла как правило отображается в `span.filesize` сразу после `.de-img-name`.

Современными браузерами поддерживается атрибут [download](https://www.w3schools.com/TAGS/att_a_download.asp), который открывает диалог сохранения файла при клике на ссылку, а так же позволяет указывать дефолтное имя файла при сохранении.

[Коммит для брчана](https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/commit/beec375ef4576ad8a366496368508654524d90f9) хорошо работает, однако он добавляет фичу локально для брчана и принудительно. Так, теперь левый клик по ссылке теперь открывает диалог сохранения вместо открытия на новой вкладке. С одной стороны это удобно, клик средней кнопкой по-прежнему открывает на новой вкладке, но некоторым может показаться не очень.

Следующие фичи можно реализовать:

- [x] **Добавить опцию "скачивать картинки по клику", которая просто добавляет к `.de-img-name` атрибут `download`.**
- [x] Регекспом выдирать оригинальное имя файла из `span.filesize` и присваивать его атрибуту `download`. На разных бордах верстка этого блока отличается, кроме того, часто на отдельных досках имени файла не отображается вовсе. Такое поведение скорее всего следует подразумевать по умолчанию при включенной вышеупомянутой опции, либо как отдельный пункт.
- [x] Заменять текст `.de-img-name` (если не включена опция "Скрывать имена картинок") на оригинальное имя файла, если оно доступно.
- [x] Так же добавлять ссылкам атрибут title с оригинальным именем.
- [ ] При включенной опции "Скрывать имена картинок" скрывать так же все содержимое `.filesize`. Сейчас оно выглядит так: 
> Файл: :mag: jpg-(80.83KB, 550×367, 0chan i love you so fucking much.jpg)

Должно же так:

> :mag: jpg

- [ ] Сделать все, что сказано выше применительно к ссылке с превью. Картинка должна разворачиваться как обычно, но при вызове "сохранить как..." из контекстного меню будет сохраняться оригинальное имя.

- [ ] Так же добавить превью атрибут `alt` с именем файла.

Еще следует помнить о типе аттачмента, для разных типов в `.filesize` может содержаться разная инфа. Например, для музыки дефолтная Кусаба пишет исполнителя и название песни, так что обычный регексп может не сработать.

Написание регулярок так же нетривиальная задача. В отличие от брчана, где зой-няша поместил имя файла в свой span с уникальным классом, разработчики большинства движков с этим не заморачивались. Имена файлов могут содержать пробелы, запятые, и другие знаки, которые с первого взгляда хотелось бы использовать как разделители.
Для примера выше (с нульчем) регулярка будет такая: `/\((?:.*,\s)(?:.*,\s)(.*)\)/g`.

Нюансов тут много, но функция безусловно полезная. Наиболее полезным является сохранение по клику, это реализовать проще всего, имя файла можно оставить на потом.

**Comment by SthephanShinkufag** [comment]
Убрана опция `"Картинки"` > `"Скрывать имена картинок"`.
Новая опция: `"Картинки"` > `"[Не изменять][Настоящие][Скрывать] имена картинок"`.

`[Не изменять]` &mdash; не применет никаких изменений.
`[Настоящие]` &mdash; заменяет содержимое ссылок на оригинальные имена, если они существуют. Слишком длинные имена сокращаются при помощи троеточия: `Shinku_Rozen_Ma...png`. Также, добавляет атрибут `download` с оригинальным именем картинки, чтобы при скачивании по этой ссылке картинка сохранялась с оригинальным именем.
`[Скрывать]` &mdash; действует также, как и старая опция `"Скрывать имена картинок"`, заменяя содержимое ссылки на расширение картинки без имени. Также добавляет атрибут `download` с оригинальным именем.

Так как существует огромное разнообразие форматирования и оформления информации о картинках на разных бордах, исправлен детектор имён картинок и информации о картинках для большинства существующих борд и движков. Проверены почти все имейджборды на работоспособность детектирования инфы о ширине-высоте, имени, оригинальном имени, местонахождении ссылки и тамбнейла. Детектор теперь гибкий, скрипту теперь вообще по барабану, он будет раскрывать картинки даже если не будет никакой информации о картинках вообще (например, на http://m-ch.ml/b/wakaba.html).

**Comment by SthephanShinkufag** [comment]
И да.

Вариант "[Настоящие]" не имеет никакого действия, кроме добавления атрибута `download`, если имейджборд не содержит инфы об оригинальных именах картинок (/b/ Ычана, например), или ссылки УЖЕ содержат оригинальные имена (Сосач, например).
