### ISSUE TITLE
#Баг 4Chan cannot create now tread

### ISSUE THREAD

**Issue by y0shir** [SthephanShinkufag/Dollchan-Extension-Tools#1048]
Comodo Dragon Версия 48.12.18.249 Версия скрипта 17.2.13.1 с гугл стора 4chan 
При попытке создать тред выскакивает ошибка о необходимости заполнения капчи. Оказывается, куклоскрипт скрывает капчу, которая используется для создания тредов, и заменяет её капчей, которая используется для создания отдельных постов.

**Comment by SthephanShinkufag** [comment]
Пробуйте.
