### ISSUE TITLE
Лойсы в /po/ мейлача  #Баг

### ISSUE THREAD

**Issue by Dezaimasu** [SthephanShinkufag/Dollchan-Extension-Tools#1050]
Собственно сабж.  Кнопки Двачую/RRRAGE! не работают. Не совсем понял из ответа Йобы, это так и надо, или когда-нибудь починится?

[https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/issues/995](url)
>Это ты про кнопки Двачую/RRRAGE? Они и не тестируются. А при AJAX-обновлении они не обновляются.

**Comment by SthephanShinkufag** [comment]
Исправлено в bb9a14c28f3c6013c5920cd1740ce4421dc0693f
