### ISSUE TITLE
Моргание картинок при включенной маскировке #Баг

### ISSUE THREAD

**Issue by Dezaimasu** [SthephanShinkufag/Dollchan-Extension-Tools#1052]
Если включена маскировка картинок, и в посте помимо картинки есть ютубовская превьюшка, то наведение мыши на превьюшку картинки постоянно триггерит туда-сюда эту маскировку, т.е. картинка при наведении курсора моргает подобно кошмару эпилептика.
Как минимум на форчане такое.
Проблема где-то в том, что дивка .de-video-obj, которая контейнер ютубовской превьюшки,находится не там, где сама ютубовска превьюшка .de-video-thumb, т.е. справа от картинки, а намного левее, поверх самой картинки. И я так понимаю мышиные ивенты превьюшки картинки и превьюшки ютуба дерутся друг с другом.
Алсо самый верхний край превьюшки картинки, ~20 пикселей, выглядывает из под .de-video-obj, и по нему ховер работает как и должен.

Я в этих вопросах не очень, но если тупо повесить на .de-video-obj дивку display: {inline-block;} , то она уедет вправо от картинки, не будет расхождения в позиции превьюшки ютуба и её контейнера, на превью картинки ничего не наезжает и ховер не глючит. 

![screenshot from 2017-03-30 12-02-22](https://cloud.githubusercontent.com/assets/1636242/24496482/0aa90a76-1541-11e7-95b8-2c482e4f854d.png)

**Comment by SthephanShinkufag** [comment]
В обычных постах уже есть `.de-video-obj-inline { display: inline-block; }`
Эта проблема наблюдается только в оп-постах.
А вот для оп-постов не все так просто. Я бы и туда повесил `inline-block`. Но я этого не сделал &mdash; это подходит не для всех борд. На ычане (и на всех стандартных вакабах-кусабах) ютуб-превью уедет на правый край поста.

![20150320_101026](https://cloud.githubusercontent.com/assets/1059874/25119605/87dbe144-2423-11e7-886a-37d74e3bf1ec.jpg)

**Comment by SthephanShinkufag** [comment]
Лучшего решения не нашёл.
Теперь, при включенной маскировке, ютуб в оп-постах переносится вниз, под картинку.
