### ISSUE TITLE
Ponyach.ru: некорректное раскрытие картинок по клику

### ISSUE THREAD

**Issue by HouyiTheArcher** [SthephanShinkufag/Dollchan-Extension-Tools#1054]
При раскрытии картинок (по центру) некоторые изображения раскрываются некорректно, с какими-то серыми полями. При повторной попытке раскрытия всё уже работает нормально. Примеры прикреплены.

Версия скрипта крайняя, проблема воспроизводится как в Firefox'е, так и Chromium'е.

![layoutbug0](https://cloud.githubusercontent.com/assets/13876697/25055174/f1358af8-2169-11e7-91b2-cb3b1f106169.jpg)
![layoutbug1](https://cloud.githubusercontent.com/assets/13876697/25055181/f55f6cb6-2169-11e7-9f95-929c8ab0f4d2.jpg)
![layoutbug2](https://cloud.githubusercontent.com/assets/13876697/25055185/f78765fc-2169-11e7-85a0-f7b1e263827f.jpg)

**Comment by OpenA** [comment]
И еще просьба добавить какой нибудь
```javascript
form.dispatchEvent(new Event('deSuccessFormSend'));
```
После того как форма удачно прошла.

**Comment by OpenA** [comment]
Короче что бы это починить нужно добавлять костыль галактического масштаба.
Либо отказаться от идеи автоматического исправления ориентации изображения,  вместо этого сделать кнопку "повернуть"

Пусть пользователь сам решает как ему надо смотреть
![5431321](https://cloud.githubusercontent.com/assets/265758/25176246/f193dd32-2516-11e7-9214-53fc428e20f2.png)

**Comment by SthephanShinkufag** [comment]
> При раскрытии картинок (по центру) некоторые изображения раскрываются некорректно, с какими-то серыми полями

Исправлено.

Ребята, куклоскрипт берет параметры картинок (ширину, высоту, размер) из элементов на борде.
То есть,
`Файл 149095327656.jpg - (56.05KB , 604x604 , Слоупок.jpg ) `
Все это парсится, и используется скриптом.
В вашем случае, скрипт эти данные не находил вообще, так как не знал где их брать. Размеры вычислялись только после полной загрузки картинок, в скрипте есть и такой костыль, на самый крайний случай. Я теперь явно указал, где на вашей борде брать эти данные:

```js
this.qImgInfo = '.filesize[style="display: inline;"]';
```

Как видите, проблема осложняется тем, что если картинок в посте много, то их параметры у вас хранятся тупо в куче, в общем контейнере со всеми картинками.
На нормальных бордах, каждая картинка имеет свой контейнер, в котором содержатся ее данные.

Вот, к примеру, доброчан:
```html
	<div id="file_84439_2259963" class="file">
		<div class="fileinfo limited">
			Файл: <a href="/src/jpg/1704/138630334319.jpg" target="_blank">138630334319.jpg</a><br>
			<em>Jpg, 491.09 KB, 1131×800</em><br>
			<a class="edit_ icon" href="/utils/image/edit/2259963/9144650">
				<img src="/images/blank.png" title="edit" alt="edit">
			</a>
		</div>
  		<a href="/src/jpg/1704/138630334319.jpg" target="_blank">
			<img src="/thumb/jpg/1704/149187648362258s.png" class="thumb" alt="138630334319.jpg" onclick="expand_image(event, 1131, 800)" height="141" width="200">
			</a>
	</div>

	<div id="file_84439_1998190" class="file">
		<div class="fileinfo limited">
			Файл: <a href="/src/png/1609/1-8.png" target="_blank">1.png</a><br>
			<em>Png, 2390.58 KB, 1440×1440</em><br>
			<a class="edit_ icon" href="/utils/image/edit/1998190/9144650">
				<img src="/images/blank.png" title="edit" alt="edit">
			</a>
		</div>
  		<a href="/src/png/1609/1-8.png" target="_blank">
			<img src="/thumb/png/1609/147343391162576s.png" class="thumb" alt="1.png" onclick="expand_image(event, 1440, 1440)" height="200" width="200">
		</a>
	</div>
```

Я поступил по-хитрому. Селектор `this.qImgInfo = '.filesize[style="display: inline;"]` ориентируется на тот параметр картинки, который в данный момент отображается, так как пользователь навел мышь на текущую картинку.
К сожалению, при автоматическом просмотре, например, по стрелкам, это работать не будет. И скрипт будет брать первые попавшиеся размеры. Что чревато неправильным определением размеров картинок в постах, где их несколько.

**Comment by SthephanShinkufag** [comment]
Хм. Можно придумать костыль получше для гарантированного соотношения картинки и её информации.
Например, смотреть на цифры в конце id элементов, у вас там есть нумерация.

**Comment by SthephanShinkufag** [comment]
Нет. Не получится. В скрипте все настроено на то, что каждая картинка и ее инфа должны лежать в отдельном контейнере, а не в общем.

**Comment by SthephanShinkufag** [comment]
Кстати, у вас  сохранение треда и сохранение картинок до сих пор не рабротало. Ой вей.
Сейчас сохранение всех картинок работает.

**Comment by Y0ba** [comment]
> Размеры вычислялись только после полной загрузки картинок, в скрипте есть и такой костыль, на самый крайний случай.

Интересно, а почему этот костыль некорректно работает?

**Comment by SthephanShinkufag** [comment]
Почему, все корректно работало. Просто у них там есть какая-то кнопка по переворачиванию картинок. Пост OpenA выше. Я эту кнопку на странице не нашел, хех.

**Comment by Y0ba** [comment]
Не, он про костыль в скрипте, который переворачивает изображения, если в них есть соответствующий тег exif.

**Comment by SthephanShinkufag** [comment]
А, ліл. Дошло наконец.

**Comment by OpenA** [comment]
Нету там кнопки, это я (у себя) просто припилил ручное разворачивание вместо
```javascript
const isExifRotated = target.scrollHeight / target.scrollWidth > 1 ? ar < 1 : ar > 1;
```
из за которой он думает что превьюшки закрытые спойлером это перевернутые картинки через флаг в exif

**Comment by SthephanShinkufag** [comment]
@OpenA, а с b1b032833be77e7bb9226840b3779f65057547cf сейчас все нормально?

**Comment by SthephanShinkufag** [comment]
Или вы не по теме этого issue сюда напейсали? Чому не создадите отдельный issue?
Вы сбиваете меня с толку.

**Comment by SthephanShinkufag** [comment]
Я имею в виду серые поля.

**Comment by OpenA** [comment]
Да, вроде работает только значки поиска непойми куда вставляются.
![758767654](https://cloud.githubusercontent.com/assets/265758/25180862/ffcfe834-2528-11e7-85d0-33a66922f1ac.png)
> Или вы не по теме этого issue сюда напейсали?
И по теме и не по теме, не по теме:
```javascript
if(Cfg.favOnReply && tNum && !$q('.de-btn-fav-sel', pByNum.get(tNum).el)) {
		pByNum.get(tNum).thr.setFavorState(true, 'onreply');
	}
	pr.clearForm();
	pr.form.dispatchEvent(new Event('deSuccessUpload')); //<- прошу вот такую штуку dcnfdbnm
	Cfg.stats[tNum ? 'reply' : 'op']++;
	saveCfgObj(aib.dm, Cfg);
	if(!tNum) {
		if(postNum) {
```

**Comment by SthephanShinkufag** [comment]
> значки поиска непойми куда вставляются

Исправлено.

> pr.form.dispatchEvent(new Event('deSuccessUpload'));

Может, добавить событие в [dollchanAPI](https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/wiki/dollchan-api)?

**Comment by OpenA** [comment]
> Исправлено.
Теперь все хорошо, спасибо.
Ну или почти все хорошо (при ответе с нулевой всегда новый тред создает), пикрил:
![5643523](https://cloud.githubusercontent.com/assets/265758/25197350/3b4f1df6-255d-11e7-849d-2c40d5f5bd59.png)
> Может, добавить событие в dollchanAPI?
А так у вас есть API, добавьте тогда на success и на dismiss пожалуйста.

**Comment by SthephanShinkufag** [comment]
> при ответе с нулевой всегда новый тред создает

Исправлено.

> у вас есть API, добавьте тогда на success и на dismiss пожалуйста

Добавил. Смотрите коммит, там есть пример. Собственно, ссылка на скрипт с тестом АПИ:

https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/raw/master/DollchanAPI_Test.user.js

**Comment by SthephanShinkufag** [comment]
Щас обновлю статью на вики.

**Comment by SthephanShinkufag** [comment]
Готово! Вот [ссылка](https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/wiki/Dollchan-API#3-submitform--%D0%BF%D0%BE%D0%BF%D1%8B%D1%82%D0%BA%D0%B0-%D0%BE%D1%82%D0%BF%D1%80%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-%D0%BF%D0%BE%D1%81%D1%82-%D0%B8%D0%BB%D0%B8-%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D1%82%D1%8C-%D1%82%D1%80%D0%B5%D0%B4).

**Comment by OpenA** [comment]
> Исправлено.
Спасибо, теперь все хорошо
> Добавил. Смотрите коммит, там есть пример. Собственно, ссылка на скрипт с тестом АПИ:
Я тут на ясную проспавшуюся голову вспомнил что API  все таки подразумевает модель "запрос" <-> "ответ", например объекты картинок запросить с их кукловыми свойствами, или тред который кукла в невидимую загрузила.
А у нас все таки цель просто повешать сценарий который будет запускаться по событию.
Ну да ладно, пару строчек можно и в ручную добавлять.
Благодарю, обращение можно закрывать.
