### ISSUE TITLE
Поддержка фильтрования постов по флажкам

### ISSUE THREAD

**Issue by puyebu** [SthephanShinkufag/Dollchan-Extension-Tools#1055]
Хотелось бы иметь эту возможность в качестве спелла.

**Comment by SthephanShinkufag** [comment]
Сосач? Всё просто:
Россия
`#exph(/<img src="/flags/ru.png"/ig)`
Украина:
`#exph(/<img src="/flags/ua.png"/ig)`
Польша:
`#exph(/<img src="/flags/pl.png"/ig)`

**Comment by puyebu** [comment]
Сосач, но /gsg.
Тег флага:
<img hspace="3" src="/icons/gsg/Франция  (республика).png" title="Франция  (республика)" border="0" />
Попытка сделать выражение по примеру выше:
 #exph(/<img src="/icons/gsg/Франция  (республика).png"/ig) 
не скрыла сообщения.

**Comment by SthephanShinkufag** [comment]
Экранируйте скобки и спецсимволы:
`(` ==> `\(`
`)` ==> `\)`
`\` ==> `\\`
`/` ==> `\/`

**Comment by SthephanShinkufag** [comment]
#exph(/<img src="\/icons\/gsg\/Франция \(республика\).png"/ig)

**Comment by SthephanShinkufag** [comment]
А еще у аас там `hspace="3"`, что стоит между img  и src.
Попробуйте

`#exph(/<img[^>]+src="\/icons\/gsg\/Франция \(республика\).png"/ig)`

**Comment by SthephanShinkufag** [comment]
Вот более короткий рабочий вариант;

`#exph(/<img[^>]+src="\/icons\/gsg\/Франция/ig)`

**Comment by puyebu** [comment]
Да, это работает.
Спасибо.
