### ISSUE TITLE
Настройки для картинок распространяются на WEBM

### ISSUE THREAD

**Issue by bushig** [SthephanShinkufag/Dollchan-Extension-Tools#1057]
В настройках пункты **"Ability to post same images"** и **"Remove EXIF from JPEG"**, несмотря на названия, действуют не только на картинки, но и на WEBM файлы.
Проблема в том что эти настройки меняют содержимое файла и, соответственно, меняется хэш md5. Если для других борд это может быть полезным, то для мейлача уже нет, так как они больше не ограничивают возможность грузить одни и те же файлы. Или есть еще какие то причины?
Было бы неплохо если по дефолту эти пункты были отключены на мейлаче, так как мое расширение использует эти хэши для идентификации webm. И из-за того что хэш меняется при каждой загрузке, мне приходится анализировать по сути одни и те же вебм.

**Comment by Y0ba** [comment]
> мое расширение использует эти хэши для идентификации webm

Не проще ли при рассчёте хэша игнорировать элементы void (с id ранвым `0xEC`) нулевого уровня? Тогда кукла уже не будет мешать работе расширения, поскольку содержимое самого webm она не трогает.

**Comment by bushig** [comment]
> Не проще ли при рассчёте хэша игнорировать элементы void
В таком случае придется каждый раз скачивать вебм на сервере + не получится использовать md5 для того чтобы нормально отслеживать просмотренные вебмки на стороне расширения.
Думаю мне в любом случае придется чистить метаданные перед анализом на сервере,  но я все равно не вижу смысла использовать первую опцию на харкаче. И спасибо за наводку.

**Comment by SthephanShinkufag** [comment]
> Было бы неплохо если по дефолту эти пункты были отключены на мейлаче

Не все обновляют куклоскрипт, часть пользователей будет все равно слать измененные вебмки.

**Comment by izac1** [comment]
@Y0ba чтоб отсечь void всё равно нужно перекодировать webm без учёта void нулевого уровня

**Comment by Y0ba** [comment]
Что значит "перекодировать"? Видеопоток вообще трогать не надо, кодирование тут совсем не при чём.
