### ISSUE TITLE
Периодически не иницилизируется скрипт в открываемых тредах

### ISSUE THREAD

**Issue by Reisenfag** [SthephanShinkufag/Dollchan-Extension-Tools#1058]
FF53, es6 версия. В консоль вываливается такое:
```
Generator throw:  Exception { message: "Component returned failure code: 0x…", result: 2147549183, name: "NS_ERROR_UNEXPECTED", filename: "chrome://greasemonkey-modules/conte…", lineNumber: 59, columnNumber: 0, data: null, stack: "GM_ScriptStorageFront.prototype.get…", location: XPCWrappedNative_NoHelper }  Dollchan_Extension_Tools.es6.user.js:917:5
```

**Comment by SthephanShinkufag** [comment]
Прям на всех имейджбордах такое? Или на какой-то конкретной?
Покажите полный `stack`, а не сокращенный. И номер коммита скрипта, желательно.

**Comment by Y0ba** [comment]
Это что-то не так в гризманки. Попробуй обновить расширение.

**Comment by Reisenfag** [comment]
@Y0ba Да вроде самый свежий.
@SthephanShinkufag v17.2.13.0.3a65251.es6, На Ычане.
http://storage4.static.itmages.com/i/17/0423/h_1492914353_5997128_3dbbf69715.png
Что показать?

**Comment by Y0ba** [comment]
Версия 3.10?

**Comment by Y0ba** [comment]
Если версия гризманки последняя попробуй отключить E10S в настройках Firefox. Может быть дело ещё в этом.

**Comment by Reisenfag** [comment]
@Y0ba Да отключено всё. Но дело в макаке, ага. Поставил Tampermonkey, там такой проблемы нет. Но он сам по себе кривой.

**Comment by SthephanShinkufag** [comment]
Скопируйте и покажите полное содержимое поля `stack`.

**Comment by SthephanShinkufag** [comment]
И да, обновитесь по последнего коммита:

https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/raw/master/src/Dollchan_Extension_Tools.es6.user.js

**Comment by Reisenfag** [comment]
У меня гарантированно воспроизводится, если открыть одновременно несколько тредов, например в архиве

А как раз при включённой мультипроцессорности бага нет.

**Comment by SthephanShinkufag** [comment]
Каком еще архиве?

**Comment by Reisenfag** [comment]
iichan.hk/b/arch/ суть не важно, просто там легче кучу тредов одновременно пооткрывать.

**Comment by SthephanShinkufag** [comment]
Эта фигня ещё наблюдается?
