### ISSUE TITLE
Огромная ширина поля набора текста

### ISSUE THREAD

**Issue by OskarZeta** [SthephanShinkufag/Dollchan-Extension-Tools#1059]
Привет, такой вопрос - зачем полю поста задана настолько огроменная ширина? Это вроде недавно появилось, очень неудобно стало набирать пост, потому что текст не переносится и улетает за пределы экрана.
![doll_textarea](https://cloud.githubusercontent.com/assets/20010735/25327895/9098ec5e-28de-11e7-994d-58e5f722b6ec.jpg)

**Comment by SthephanShinkufag** [comment]
Макака что-то поменял на своей борде, и ширина поля ввода теперь вычисляется некорректно.

**Comment by SthephanShinkufag** [comment]
Ставите последний билд скрипта, на сосаче заходите в окно настроек куклоскрипта > кнопка `"Правка"` > найдите в тексте `textaWidth` и выставьте `"textaWidth": 400,` > нажимте кнопку `"Сохранить"`.

**Comment by OskarZeta** [comment]
Спасибо, помогло.

**Comment by elenmerbau** [comment]
А мне нет. Ширина плавающей формы всегда одинаково широкая, не подстраивается под поле ввода. Тестил в хромоопере последней и в эдж.
https://imgur.com/a/Vxf4c

**Comment by OskarZeta** [comment]
Да, у меня тоже не подстраивается, только поле ввода меняет ширину (всё с тем же вылетом за пределы экраны, как правило). Ну хоть дефолтный размер поля теперь нормально выглядит, и то хорошо.

**Comment by SthephanShinkufag** [comment]
Ребята, вы точно не забыли установить скрипт с последнего коммита?

> Ставите последний билд скрипта

https://raw.github.com/SthephanShinkufag/Dollchan-Extension-Tools/master/Dollchan_Extension_Tools.user.js

**Comment by OskarZeta** [comment]
Точно, забыл про это. Теперь ширина поля нормально изменяется, спасибо.

**Comment by SthephanShinkufag** [comment]
![5793056722](https://cloud.githubusercontent.com/assets/1059874/25385717/9ff171b8-29cd-11e7-9c82-2b2458ad855b.jpg)

**Comment by elenmerbau** [comment]
Да, заработало, прими мой пардон :>
