### ISSUE TITLE
При получении новых постов на абучане, превьюшки не прогружаются.

### ISSUE THREAD

**Issue by UberMenko** [SthephanShinkufag/Dollchan-Extension-Tools#1060]
![ss 2017-04-30 at 12 09 13](https://cloud.githubusercontent.com/assets/28218386/25563196/8a2b55e4-2d9f-11e7-88ae-3826dfeef5b2.png)
Доброго дня всем. При обновлении треда через браузер или кукулу, все превью снова отображаются, но постоянно обновлять тред неудобно. С другими бордами всё в порядке. 
В чём может быть причина проблемы?

**Comment by SthephanShinkufag** [comment]
Браузер какой?

**Comment by UberMenko** [comment]
Огненная Лиса, обновляется по мере поступления апдейтов.

**Comment by Dezaimasu** [comment]
Ловлю такое иногда на форчанях, особенно если пик под спойлером. Нажаль не знаю как воспроизвести. Последний воднолис.
