### ISSUE TITLE
Дублирование постов при обновлении треджа.

### ISSUE THREAD

**Issue by Autism-Corporation** [SthephanShinkufag/Dollchan-Extension-Tools#1062]
Но огненной фури дублируются посты (на хромоге не проверял), танцы с бубном не помогают, стоит последняя версия.

**Comment by UberMenko** [comment]
Выключи куклу, и отключи автообновление на обычной вакабе, после чего опять включи куклу.

**Comment by SthephanShinkufag** [comment]
Сначала попробуйте скрипт с последним исправлением. Если не получится &mdash; сообщите.

https://raw.github.com/SthephanShinkufag/Dollchan-Extension-Tools/master/Dollchan_Extension_Tools.user.js

**Comment by Autism-Corporation** [comment]
Обновление не помогло, помогло отключение авто обновления от макаки ибо адблок порезал строку с этой фичей.
![1](https://cloud.githubusercontent.com/assets/21297066/25951825/8c94f5bc-3667-11e7-8229-36e9ab67091e.PNG)

**Comment by SthephanShinkufag** [comment]
Не понял. А с отключением адблоком скрипт блокирует автообновление?

**Comment by Autism-Corporation** [comment]
Кукла при включении режет эту строчку, и adblock тоже, по этому работало 2 обновления постов и выключить версию макаки не удавалось.
![2](https://cloud.githubusercontent.com/assets/21297066/25953285/9146de32-366b-11e7-97b2-8d51cde88822.PNG)

**Comment by SthephanShinkufag** [comment]
В последнем коммите была опечатка. Теперь точно должно работать.
