### ISSUE TITLE
Коррекция времени выглядит странно в настройках, если использовать HTML в шаблоне замены

### ISSUE THREAD

**Issue by UserNaem** [SthephanShinkufag/Dollchan-Extension-Tools#1064]
Формат поиска:
`w+yyyy+m+dd+hh+ii+ss`
Формат замены:
`<span class="time">_d._n._y _h:_i:_s</span>`

![image](https://cloud.githubusercontent.com/assets/21028464/25934480/868ff8e0-3637-11e7-9760-9f0448aacd09.png)

**Comment by SthephanShinkufag** [comment]
Это на всех имиджбордах, или на каком-то конкретном?

**Comment by UserNaem** [comment]
Воспроизводится на всех бордах, использую только на одной.

**Comment by SthephanShinkufag** [comment]
Проверяйте, однако.

**Comment by SthephanShinkufag** [comment]
Ой вей, ліл, до сих пор думал, что у вас на аве герб СССР. Старею, савсэм слепой становлюсь.
А тама у вас лисичка-тян.
Респект, друже! Firefox сила, хромог могила!

**Comment by UserNaem** [comment]
Спасибо, работает.
![image](https://cloud.githubusercontent.com/assets/21028464/25956598/9e38fef8-3685-11e7-8168-21324fe3b746.png)
Да, хромог - могила, даже жесты мыши работают через жопу. Надеюсь, Mozilla передумают отказываться от имеющихся расширений, а то и в браузере жесты мыши будут работать только через ту же жопу.
