### ISSUE TITLE
Баг. Куклоскрипт не обрабатывает исходящие посты.

### ISSUE THREAD

**Issue by UberMenko** [SthephanShinkufag/Dollchan-Extension-Tools#1065]
В любом случае пишет "Капча невалидна", но при обновлении треда, пост появляется. При этом он появляется с названием файла, хоть в настройках и указано, что его надо очищать. Всё та же мозила и пристанище макака. 
Кстати. При этом проблема с превьюшками исправилась, да.

**Comment by UberMenko** [comment]
Прошло минут 10. Превью снова не грузятся нормально, а посты отправляются хорошо.

**Comment by SthephanShinkufag** [comment]
Укажите борду.

**Comment by SthephanShinkufag** [comment]
2ch.hk?

**Comment by UberMenko** [comment]
Да. Ради интереса проверил доброчан, там наблюдается схожая ошибка, хоть и в более не очевидном виде. (Так и не понял, что там происходит. При автообновлении превью были, а при постинге - нет.) Ычан работает как часы.

**Comment by SthephanShinkufag** [comment]
Если честно, я не понял, что за проблема с превьюшками. Превьюшками чего? Постов? Файлов в форме? Картинок в посте? В чем заключается проблема? Можно картинку.

**Comment by UserNaem** [comment]
Попробовал воспроизвести в /test/. 
https://qt.vidyagam.es/vUgsEEP.webm

**Comment by Y0ba** [comment]
@SthephanShinkufag алсо я нашёл ещё один баг с превью. Попробуй отключить удаление файлов и запостить в 2ch.hk файл с именем `200x100500.jpg` например. Кукла берёт размер файла из его имени и только после полной загрузки берёт правильный размер файла из метаданных.

**Comment by UberMenko** [comment]
@SthephanShinkufag 
Ну я уже же делал скрин... Превьюшками картинок в посте, но вместе с ними не погружаются превью ВБЕМ и вложений (Твитер и Ютаб). Всё вместе, выходит. 
![ss 2017-05-11 at 08 09 30](https://cloud.githubusercontent.com/assets/28218386/25962295/cdfda058-3685-11e7-8561-1c6b416648ed.png)

И да. Ещё если не постить в тред - то проблемы с превью нету.

**Comment by Y0ba** [comment]
А браузер какой?

**Comment by UberMenko** [comment]
@Y0ba
![](http://puu.sh/vMQmX/2533b2ef48.jpg)

**Comment by UberMenko** [comment]
Зато всё работает на Опере! Можно сидеть на ней.

Я даже снёс целиком Мозилу, поставил 64-битную версию, очистил настройки и всё равно работает не так. Либо сообщения посылаются неккоректно, либо нет никаких превью. Помимо меня мало кто жалуется, но видно не только у меня проблема со скриптом сейчас, если судить по постам на бордах.

**Comment by SthephanShinkufag** [comment]
@UserNaem, Абу в /test/ переименовал все классы элементов везде где можно. Понятное дело, скрипт там не будет работать. Не знаю, зойчем это там сделано, и какой профит.

**Comment by SthephanShinkufag** [comment]
@UberMenko проблема осталась?
Как пошагово добиться бага?

**Comment by UberMenko** [comment]
@SthephanShinkufag Постарался проверить наиболее разнообразно. Никаких ошибок не замечено, пока. Скорее всего проблема решена. Благодарю за внимание, если ещё что-то будет, то сообщу. (Хотя, я уже предпочитаю Оперу для скроллинга по причине скорости. Так что, скорее всего, этот пост - последний.)

**Comment by SthephanShinkufag** [comment]
Спасибо за ответ!
