### ISSUE TITLE
(2ch.hk) При наведении на >>ссылку на ОП другого треда показывается весь тред, а не только ОП

### ISSUE THREAD

**Issue by UserNaem** [SthephanShinkufag/Dollchan-Extension-Tools#1066]
Firefox 54.0a2, dE v17.2.13.0.4f6c5cd.es6

![image](https://cloud.githubusercontent.com/assets/21028464/25962233/6210277e-3696-11e7-8b50-e3d36bb1e8ad.png)

**Comment by SthephanShinkufag** [comment]
Будет хорошо, если вы проследите закономерность, как этого гарантировать добиться.. Наблюдал такое пару раз, но повторить не мог.

**Comment by UserNaem** [comment]
Воспроизводится на чистом профиле Firefox с последней версией Greasemonkey и dE.
https://2ch.hk/s/res/2040035.html
![image](https://cloud.githubusercontent.com/assets/21028464/25963450/c6dd93cc-369a-11e7-991a-c1a009c45396.png)
