### ISSUE TITLE
Возможность добавления картинки к посту посредством ссылки

### ISSUE THREAD

**Issue by apan65** [SthephanShinkufag/Dollchan-Extension-Tools#1069]
Возможно ли реализовать такую фичу, чтобы не нужно было картинку вначале скачивать, а сразу посредством ссылки её вставлять в пост.

**Comment by zm3y** [comment]
Вроде же можно в диалоговом окне вместо выбора файла вставить ссылку на картинку и нажать открыть.

**Comment by apan65** [comment]
**zm3y** Реально работает, спасибо, буду знать.

**Comment by SthephanShinkufag** [comment]
Работает, но при этом картинка скачивается во временные файлы.
Я щас пытаюсь все-таки это реализовать, с заделом на давнюю хотелку #550.
Перековырял уже весь `FormFile.js`.

**Comment by SthephanShinkufag** [comment]
![gfd](https://cloud.githubusercontent.com/assets/1059874/26423823/c5f6e0f2-40d7-11e7-828e-b0eae39c129b.gif)

**Comment by apan65** [comment]
Возбудился и накатил апдейт, спасибо.
