### ISSUE TITLE
Куклачёв ломается при спелле #rep(/thread/ig,нить).

### ISSUE THREAD

**Issue by Autism-Corporation** [SthephanShinkufag/Dollchan-Extension-Tools#1071]
Спелл `#rep(/thread/ig,нить)`.
после применения данного спелла и перезагрузке страницы куклоскрипт не получается открыть и сам он перестаёт работать, решается только сбросом данных куклы.
Интересует есть в принципе возможность починить данное, ибо даже макакин поиск не умеет в данное слово искать?

**Comment by SthephanShinkufag** [comment]
#rep заменяет ВСЁ содержимое страницы, включая html: теги, классы, атрибуты, небо, аллаха. Не удивительно, что у вас всё ломается. `thread` - частый префикс классов на имейджбордах.

Нужно заменять только то, что находится внутри контейнеров.

`#rep(/(>[^<]*?)thread/ig,$1нить)`
