### ISSUE TITLE
[BRCHAN] Правила скрытия не срабатывают на одном треде

### ISSUE THREAD

**Issue by Lourens-Rich** [SthephanShinkufag/Dollchan-Extension-Tools#1072]
https://brchan.org/rus/res/903041.html

Данный тред не скрывается по изображенным ниже способам:

```
(#op & #subj(/шлюхотред/i)) |
#words(хентайным) |
```
Browser: Chrome 58.0.3029.110 (64-bit)
Usercript manager: Tampermonkey 4.3.6 | Tampermonkey BETA 4.3.5447

Dollchan Extension Tools 17.2.13.1 так же подвержен.

Данная проблема не проявляется в Firefox / Greasemonkey

**Comment by Lourens-Rich** [comment]
В кастомной сборке Chromium всё работает!

![1493746983037-0](https://cloud.githubusercontent.com/assets/22860367/26284985/36de2374-3e4f-11e7-96d2-d11eb951abd8.jpg)

**Comment by SthephanShinkufag** [comment]
В хроме всё скрывается. Видимо, вы какой-то момент упустили из виду.
