### ISSUE TITLE
Allow multi-file selection

### ISSUE THREAD

**Issue by ganego** [SthephanShinkufag/Dollchan-Extension-Tools#1073]
On KC you can add up to four images/webms to one post. It's kinda annoying that you have to select each one separately. Could you change it so that you can select more than one file please?
HTML5 allows for `input type="file"` to have `multiple="multiple"`.

I don't really know much about js so I couldn't really solve it, seems `var FileInput = function () {` is the function for each of those four file buttons below a post that add the image then, so I guess it needs some form of wrapper outside that then will call the onchange event for each file when multiple files were selected?

**Comment by Y0ba** [comment]
@SthephanShinkufag может полностью убрать возможность отправки `IFrame`'ом? Тогда вся работа с формой становится тривиальной и не необходимости городить костыли.

Вроде html5 везде работает нормально и никто не жаловался.

**Comment by SthephanShinkufag** [comment]
![multi-file-drop](https://cloud.githubusercontent.com/assets/1059874/26700790/66c71830-4727-11e7-8798-a343bf13d22d.gif)

**Comment by Smugl** [comment]
Тогда может еще добавите CTRL+V для вставки файлов? Как на оригинальной макабе.

**Comment by vanya1996** [comment]
> Тогда может еще добавите CTRL+V для вставки файлов? Как на оригинальной макабе.
Два.чую, очень неудобно без этого

**Comment by SthephanShinkufag** [comment]
@vanya1996, уже сделано #1121

**Comment by ganego** [comment]
Any plan to support this too please?:

[![dckc.png](https://s18.postimg.org/o2z0aqwgp/dckc.png)](https://postimg.org/image/qkari0gd1/)

**Comment by SthephanShinkufag** [comment]
@ganego 

Install the newest version. This has already been implemented.

![multiselect](https://user-images.githubusercontent.com/1059874/34679764-9eeba886-f49f-11e7-9594-8fd84c279625.gif)

**Comment by ganego** [comment]
Since you gave it a "Done" tag, I guess my proposal/question from the previous post will not be taken?
I have updated the picture if it was not clear enough: https://imgur.com/a/v6LD5
Thank you.

**Comment by SthephanShinkufag** [comment]
@ganego 

Implemented! Please check out.

![multiple_files](https://user-images.githubusercontent.com/1059874/34905269-d3bbafb8-f85d-11e7-9c88-f46aaa093aa8.gif)

**Comment by SthephanShinkufag** [comment]
Должны быть включены опции `Отправка постов без перезагрузки* ` и `Улучшенное поле добавления файлов`.

**Comment by ganego** [comment]
It works. Makes posting images a lot simpler. Thank you so much <3
