### ISSUE TITLE
Обновление на Ычане

### ISSUE THREAD

**Issue by Reisenfag** [SthephanShinkufag/Dollchan-Extension-Tools#1074]
Там появилось нативное скрытие и разворот картинок. С последним, кажется проблемы — при включённой подзагрузке картинок/гифок их разворачивает по умолчанию.

**Comment by SthephanShinkufag** [comment]
Фичи на ычане? Щось у лісі здохло, невже?
No way.

**Comment by SthephanShinkufag** [comment]
Таки действительно.

**Comment by SthephanShinkufag** [comment]
> при включённой подзагрузке картинок/гифок их разворачивает по умолчанию

Не наблюдаю подобного. Возможно, вы имели в виду не подгрузку картинок, а `Заменять картинки на оригиналы*`

**Comment by Reisenfag** [comment]
Да, у меня срабатывает у гифок.

http://storage5.static.itmages.com/i/17/0531/h_1496269593_9800226_41440a1bdb.png

**Comment by SthephanShinkufag** [comment]
В новых скриптах ычана есть код

```js
    let thumbs = document.querySelectorAll('.thumb');
    for (let img of thumbs) {
      let a = img.parentNode;
      if (!a) continue;
      let imageExt = a.href.match(/\w*$/).toString();
      if (!EXTENSIONS.includes(imageExt)) continue;
      img.removeAttribute('width');
      img.removeAttribute('height');
      img.thumbSrc = img.src;
      a.addEventListener('click', onThumbnailClick);
    }
```

То есть, удаляются ширина и высота у картинок.
Придется как-то бороться со скриптами ычана =\

**Comment by SthephanShinkufag** [comment]
Задавить встроенную функцию `addListeners` не выйдет - она обёрнута.
Пришлось городить жуткий костыль, заменяя классы у всех картинок =\
Проверяйте.

**Comment by WagonOfDoubt** [comment]
Минутку. Может чем городить костыль, лучше пофиксить скрипт на самом Ычане?

**Comment by WagonOfDoubt** [comment]
Так оно мешать не будет?
```javascript
function onThumbnailClick(e) {
      if (!window.matchMedia(HANDHELD_MEDIA_QUERY).matches) return;
      const thumb = e.currentTarget.querySelector('.thumb');
      const isExpanded = !thumb.classList.toggle(EXPANDED_THUMB_CLASSNAME);
      if (isExpanded) {
        thumb.removeAttribute('width');
        thumb.removeAttribute('height');
      } else {
        thumb.setAttribute('width', thumb.thumbWidth);
        thumb.setAttribute('height', thumb.thumbHeight);
      }
      thumb.src = isExpanded ? thumb.thumbSrc : e.currentTarget.href;
      e.preventDefault();
    }

    const thumbs = document.querySelectorAll('.thumb');
    for (let img of thumbs) {
      let a = img.parentNode;
      if (!a) continue;
      let imageExt = a.href.match(/\w*$/).toString();
      if (!EXTENSIONS.includes(imageExt)) continue;
      img.thumbWidth = img.getAttribute('width');
      img.thumbHeight = img.getAttribute('height');
      img.thumbSrc = img.src;
      a.addEventListener('click', onThumbnailClick);
    }
  }
```

**Comment by SthephanShinkufag** [comment]
Откатил последний коммит.

**Comment by SthephanShinkufag** [comment]
Вроде бы, всё норм.

@WagonOfDoubt, спасибо вам большое, что уделяете внимание совместимости с куклоскриптом!

**Comment by WagonOfDoubt** [comment]
Изредка при загрузке страницы нарушается порядок выполнения скриптов, и кнопка `[-]` остается видимой.
Хорошо бы в Кукле в css Ычана добавить:
```css
.iichan-hide-thread-btn {
  display: none;
}
```

**Comment by SthephanShinkufag** [comment]
@WagonOfDoubt 

> в css Ычана добавить

2d558ffb864297ce73ac0d4ec6a6ccbfd149e35f
