### ISSUE TITLE
Доброчан -> отправка поста -> автообновление -> TypeError: pBuilder.getPostHTML is not a function

### ISSUE THREAD

**Issue by Al-faqun** [SthephanShinkufag/Dollchan-Extension-Tools#1076]
![default](https://cloud.githubusercontent.com/assets/23034680/26735020/e511d68e-47c8-11e7-88c4-5abbf6104576.PNG)

> Ошибка скрипта:
> TypeError: pBuilder.getPostHTML is not a function
>     at Thread._importPosts (chrome-extension://ipnoalfffblkaodfmipjjgkfbgcfadad/Dollchan_Extension_Tools.user.js:16730:26)
>     at Thread._parsePosts (chrome-extension://ipnoalfffblkaodfmipjjgkfbgcfadad/Dollchan_Extension_Tools.user.js:16963:22)
>     at Thread._loadNewFromBuilder (chrome-extension://ipnoalfffblkaodfmipjjgkfbgcfadad/Dollchan_Extension_Tools.user.js:16881:29)
>     at chrome-extension://ipnoalfffblkaodfmipjjgkfbgcfadad/Dollchan_Extension_Tools.user.js:16583:32
>     at chrome-extension://ipnoalfffblkaodfmipjjgkfbgcfadad/Dollchan_Extension_Tools.user.js:3856:22
>     at 

Сразу после отправки поста на доброчане выскакивает это сообщение об ошибке, после этого автообновление не работает, в заголовке вкладки показываются числа типа {0}0.

**Comment by SthephanShinkufag** [comment]
Хром + хроморасширение?
Откуда постите? Со страницы или из треда? На какой доске?
Попробовал в /mad - вроде всё постится.

**Comment by SthephanShinkufag** [comment]
И да. опция `Посты` > `dobrochan: использовать JSON API` включена или выключена?

**Comment by SthephanShinkufag** [comment]
Разобрался. Щас выкачу коммит.

**Comment by Al-faqun** [comment]
На все вопросы - да.
Спасибо.
