### ISSUE TITLE
Постинг картинок 2ch.rip/dva-ch.com

### ISSUE THREAD

**Issue by kiraseki** [SthephanShinkufag/Dollchan-Extension-Tools#1077]
не работает, посты проходят без них.

**Comment by SthephanShinkufag** [comment]
Этой борде не нравится, что в форме есть лишние инпуты. Ойлоло, с чего бы.
Починю конечно.

**Comment by kiraseki** [comment]
Спасибо!

**Comment by SthephanShinkufag** [comment]
Проверяйте.
Обновил также и хроморасширение, через некоторое время прилетит.

**Comment by kiraseki** [comment]
Проверил, все работает. Отдельное спасибо за вставку ссылок, теперь можно таскать пикчи прямо с rm.booru.org
