### ISSUE TITLE
syn-ch.ru -> отправка поста -> Превышен порог прохождения хэша. Обновите страницу.

### ISSUE THREAD

**Issue by Al-faqun** [SthephanShinkufag/Dollchan-Extension-Tools#1078]
Что забавно, когда загрузил вчерашний тред из спящего режима, всё было нормально. Когда загрузил новый тред, попробовал оставить в нём пост, получил ошибку:
x Превышен порог прохождения хэша. Обновите страницу.
Хромо-дополнение.
![image](https://cloud.githubusercontent.com/assets/23034680/26752035/664774da-484f-11e7-9298-b2178ff143df.png)

**Comment by tails11** [comment]
Удвою. Попробовал сбросить настройки куклы - не помогло.
