### ISSUE TITLE
Multiple Issues using the script in PaleMoon 27 on Krautchan

### ISSUE THREAD

**Issue by Berndion** [SthephanShinkufag/Dollchan-Extension-Tools#1079]
Sup

1. When I try to post an image I get the following error
`Script error: Error: Accessing TypedArray data over Xrays is slow, and forbidden in order to encourage performant code. To copy TypedArrays across origin boundaries, consider using Components.utils.cloneInto(). at cleanFile (Dollchan_Extension_Tools.user.js:11914:1) at html5Submit$ (Dollchan_Extension_Tools.user.js:11832:16) at tryCatch (Dollchan_Extension_Tools.user.js:2410:37) at invoke (Dollchan_Extension_Tools.user.js:2616:22) at defineIteratorMethods/`

2. Furthermore it is not possible to auto-clear the favourites.

3. The saved settings also reset after a couple of days in intervals that seem rather random.

**Comment by SthephanShinkufag** [comment]
Probably you installed the incorrect version of greasemonkey.
Go to [installation wiki](https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/wiki/installation#pale-moon) page and follow the steps.
Write here about the result, bitte.

**Comment by SthephanShinkufag** [comment]
<h3 id="PaleMoon">Pale Moon</h3>

1. Install the [Greasemonkey](https://addons.mozilla.org/firefox/downloads/file/477129/greasemonkey-3.9beta2-fx.xpi) add-on. Install from this link, not from the official site!

2. Install the [script](https://raw.github.com/SthephanShinkufag/Dollchan-Extension-Tools/master/Dollchan_Extension_Tools.user.js).
<hr>

**Comment by Berndion** [comment]
Oh man now I feel like a big idiot. Yeah I had the wrong greasemonkey version installed.

Thanks a lot and sorry for the inconvenience.

**Comment by SthephanShinkufag** [comment]
It's ok, bro.
