### ISSUE TITLE
Неправильное расширение файла при аттаче картинки по ссылке

### ISSUE THREAD

**Issue by WagonOfDoubt** [SthephanShinkufag/Dollchan-Extension-Tools#1082]
Иногда ссылки на изображения не содержат имя файла и расширение. Сервер может выдавать картинки по url'ам, заканчивающимся на *.php, *.aspx, а то и просто /
Например, берем ссылку вида https://410chan.org/faptcha.php?board=b и передаскиваем в поле добавления файла. Картинка прикрепляется корректно, появляется превью. Однако, имя файла - "faptcha.php?board=b", и при отправке имиджборда выдаст ошибку "Данный тип файлов не разрешено прикреплять на данной доске".
Чекбокс "Удалять имя файлов" роли не играет.
Нужно каким-то образом детектировать расширение файла и постить его с соответствующим именем.

**Comment by SthephanShinkufag** [comment]
Попробуйте и с другими источниками, может еще где чего.
