### ISSUE TITLE
Полноценная поддержка скрипта в Adguard

### ISSUE THREAD

**Issue by Darktrader** [SthephanShinkufag/Dollchan-Extension-Tools#1083]
Разработчики програмы Adguard добавили в последних версиях установку пользовательских джаваскриптов. Я попытался установить куклоскрипт туда.  Он поставился и вроде как выполняет более-менее нормально свои функции, но при попытке отправки поста, мне куклоскрипт выдает такую ошибку:
`TypeError: FormData is not a constructor
    at html5Submit$ (http://local.adguard.com/adguard-ajax-api/injections/userscripts/Dollchan%20Extension%20Tools?ts=63633440387508:12067:18)
    at tryCatch (http://local.adguard.com/adguard-ajax-api/injections/userscripts/Dollchan%20Extension%20Tools?ts=63633440387508:2724:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (http://local.adguard.com/adguard-ajax-api/injections/userscripts/Dollchan%20Extension%20Tools?ts=63633440387508:2930:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (http://local.adguard.com/adguard-ajax-api/injections/userscripts/Dollchan%20Extension%20Tools?ts=63633440387508:2749:21)
    at continuer (http://local.adguard.com/adguard-ajax-api/injections/userscripts/Dollchan%20Extension%20Tools?ts=63633440387508:4076:30)
    at onFulfilled (http://local.adguard.com/adguard-ajax-api/injections/userscripts/Dollchan%20Extension%20Tools?ts=63633440387508:4090:12)
    at http://local.adguard.com/adguard-ajax-api/injections/userscripts/Dollchan%20Extension%20Tools?ts=63633440387508:4095:11
    at spawn (http://local.adguard.com/adguard-ajax-api/injections/userscripts/Dollchan%20Extension%20Tools?ts=63633440387508:4104:47)
    at HTMLFormElement.PostForm.form.onsubmit (http://local.adguard.com/adguard-ajax-api/injections/userscripts/Dollchan%20Extension%20Tools?ts=63633440387508:11476:5)`

Поэтому, можно пожалуйста пофиксить этот недочет.

**Comment by Y0ba** [comment]
Выключи `Отправка постов без перезагрузки*` в Настройки -> Форма.

**Comment by SthephanShinkufag** [comment]
@Y0ba, возможно, нужно убрать `if(firefox || safari) {`, чтобы костыль проверялся везде.

```js
	let needFileHack = false;
	try {
		new File([''], '');
		if(firefox || safari) {
			needFileHack = !FormData.prototype.get;
		}
	} catch(e) {
		needFileHack = true;
	}
```

**Comment by Y0ba** [comment]
Судя по всему там `FormData` вообще нет. А учитывая, что `IFrame`-отправку из куклы не так давно удалили, то остаётся только совсем отключить эту фичу.

**Comment by SthephanShinkufag** [comment]
@Darktrader что-то до меня не совсем дошло. На ПК Adguard это всего-лишь набор расширений для браузеров.
Где его можно установить как самостоятельный браузер? Есть какое-то приложение для андроида, или что?

**Comment by SthephanShinkufag** [comment]
Расскажите подробнее, как именно вы установили Adguard, и куклоскрипт в него.

**Comment by Darktrader** [comment]
@SthephanShinkufag ну как там заходишь на официальный сайт, устанавливаешь как обычную программу.
> Где его можно установить как самостоятельный браузер? Есть какое-то приложение для андроида, или что?
Нет, я наверное не очень корректно выразился. Оно лишь как набор расширений для браузера. И одна из недавних возможностей - установка практически любого стороннего скрипта туда.
Куклоскрипт туда в принципе тоже устанавливать не сложно. Я просто взял и открыл [ссылку](https://raw.github.com/SthephanShinkufag/Dollchan-Extension-Tools/master/Dollchan_Extension_Tools.user.js) на скачивание и установку этого скрипта, который ты в гитхабе выложил. А дальше AdGuard уже сам подхватил ее и установил.

**Comment by Darktrader** [comment]
Еще конечно же можно через настройки в "расширениях" указать прямой URL или путь к файлу, но мне кажется, сути вопроса это не меняет.

**Comment by SthephanShinkufag** [comment]
А, просто у меня не уложилось в голове, при чем тут аддон-адблокер к установке юзерскриптов. Может, это какой-то полноценный браузер со встроенной блокировкой.
Оказывается, это уже какой-то комбайн со свистелками и перделками, куда до кучи можно и юзерскрипты ставить.
Буду посмотреть.

**Comment by SthephanShinkufag** [comment]
`window.FormData is undefined`, увы
Принудительно отключил html5-отправку постов.
Теперь только что выяснил, что `window.URL` тоже недоступно. О полноценной поддерже говорить не приходится, увы.

**Comment by SthephanShinkufag** [comment]
Так что, я не рекомендую использовать Adguard в качестве установщика куклоскрипта.

**Comment by Y0ba** [comment]
А что там внутри за браузер такой? На каком движке? Или они эти API сознательно выключили?

**Comment by SthephanShinkufag** [comment]
Это не браузер. Adguard это самостоятельная прога, которая внедряет свои агенты-расширения и прочие анальные зонды во все браузеры в системе. До кучи еще и яндекс-свиствелки предлагает поставить. Но не суть.
В общем, поначалу я не совсем понял - в браузере зонды Adguard'a вообще нкак не видны - в меню Инструменты - Дополнения ничего нет. Все взаимодействие происходит в материнской программе-агенте - там в последнем пункте "Расширения" можно вставить ссылку на скрипт, и добавить его в браузер.

**Comment by SthephanShinkufag** [comment]
Короче, это такая внедрялка расширений. Adguard позволяет помимо своих зондов внедрять и юзерскрипты.

**Comment by Y0ba** [comment]
И зачем это надо? :confused: Это когда уже расширение-блокировщик не вставляет и хочется больше приключений?

**Comment by SthephanShinkufag** [comment]
Наверно :D 

@Darktrader в общем, из-за `window.URL` не будут работать предзагрузка картинок, изменение и мигание фавикона, скачивание тредов и картинок целиком, асинхронные спеллы (#ihash и #video). Может, еще что-то.

**Comment by SthephanShinkufag** [comment]
Ага, и экспорт настроек через файл.

**Comment by SthephanShinkufag** [comment]
https://www.youtube.com/watch?v=uXrKiuG-ybI

**Comment by Efirion** [comment]
> И зачем это надо?

Вероятно для https://github.com/reek/anti-adblock-killer и форков.
![aak ce4gzeawsaasydo jpg orig](https://user-images.githubusercontent.com/11760479/27465943-3f341730-57f0-11e7-83e6-dd35ef0f835f.jpg)
