### ISSUE TITLE
На 2ch.hk в тематике (в разделе /po/) не работает куклоскрипт 

### ISSUE THREAD

**Issue by StirItUp** [SthephanShinkufag/Dollchan-Extension-Tools#1084]
Макака что то накрутил и теперь расширение просто не отображается. Причем если зайти в любой тред оно снова появляется, а на самой доске нет.

**Comment by Y0ba** [comment]
Уже исправлено в 825a89ee8f249cabc5fe78df19eacad6854893a0.

**Comment by Y0ba** [comment]
Если у тебя хроморасширение, надо подождать пока оно обновится в хромсторе. Иначе можешь просто обновить скрипт.

**Comment by SthephanShinkufag** [comment]
Расширение в хромосторе уже обновилось.

**Comment by StirItUp** [comment]
Найс! Все работает! Добра вам и вашему делу!
