### ISSUE TITLE
Как вернуть цвет новых постов на тот, который был в 2016.12.28?

### ISSUE THREAD

**Issue by ltyfdrjh** [SthephanShinkufag/Dollchan-Extension-Tools#1086]
В какой строке искать?

**Comment by SthephanShinkufag** [comment]
https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/wiki/css-tricks#2chhk

> Как сделать, чтобы новые посты подкрашивались оранжевым?

```css
.de-new-post { box-shadow: 6px 0px 2px -2px #F60, -6px 0px 2px -2px #F60 !important; }
```

Подставляете вместо `#F60` нужный вам цвет.

**Comment by ltyfdrjh** [comment]
Я про плюсик возле favicon. Это оно?

**Comment by SthephanShinkufag** [comment]
https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/blob/master/src/modules/ThreadUpdater.js#L210

Новые посты:
```js
			drawLines(ctx, [6, 11, 16, 11], [11, 6, 11, 16], '#1c5f23', 4, scale);
			drawLines(ctx, [7, 11, 15, 11], [11, 7, 11, 15], '#00f51b', 2, scale);
			this._iconNew = canvas.toDataURL('image/png');
```

Есть ответ на ваш пост:

```js
			drawLines(ctx, [6, 11, 16, 11], [11, 6, 11, 16], '#122091', 4, scale);
			drawLines(ctx, [7, 11, 15, 11], [11, 7, 11, 15], '#1b6df5', 2, scale);
			this._iconYou = canvas.toDataURL('image/png');
```

Первая строка drawLines &mdash; граница крестика, вторая строка &mdash; середина.

**Comment by ltyfdrjh** [comment]
Я подставил цвета из версии 2016.12.28 и сохранил скрипт - пропали все настройки, около 1000 строчек скрытия тредов. Больше ничего не менял. Что за бред?

**Comment by ltyfdrjh** [comment]
Просто пиздец, из-за кривого скрипта слетела тысяча строк скрытия. Зачем нужен такой скрипт, когда из-за банального редактирования цвета слетают все настройки? Я блядь просто в шоке! Нахуй я донатил на это говно. сука, чтобы ты сдох, мразина.

**Comment by SthephanShinkufag** [comment]
Выпрямляйте руки.

**Comment by SthephanShinkufag** [comment]
Не буду гадать, что вы там могли сделать не так, попробуйте снова поставить скрипт по ссылке
https://raw.github.com/SthephanShinkufag/Dollchan-Extension-Tools/master/Dollchan_Extension_Tools.user.js

**Comment by ltyfdrjh** [comment]
Слыш, ублюдок. Я только цвета поменял. Нихуя не помогает переустановка, ВСЕ НАСТРОЙКИ СЛЕТЕЛИ. Иди нахуй со своей новой формой прикрепления файлов. Какой же ты пидорас, сука, без вкуса. Меняешь стиль - оставь настройки для тех, кто не поддерживает твои уебанские идеи, гной ебаный. От тебя требовалось только вернуть работоспособность на главной странице - все остальное было настраиваемо под любой вкус. Нет, блядь, мы будем делать уебанские нововведения, НАХУЙ НИКОМУ НЕ НУЖНЫЕ, кроме тебя, хуила. Ты небось еще и анимацию в своем скрипте не отключаешь, ты же конченый долбоеб, блядь.

**Comment by VisualKei** [comment]
Лол, вот это бомбануло. Хотя для криворукого аутиста, который вместо бекапов делает тысячу скрытых тредов, это конечно совсем неудивительно.

**Comment by ltyfdrjh** [comment]
Ой блядь, ты наверно и не скрываешь, сидишь в помойке и радуешься, рулетки крутишь, хуй сосешь, да?

**Comment by Y0ba** [comment]
Попробуй поставь версию 2016.12.28. Может она подхватит настройки?

**Comment by Y0ba** [comment]
Вот она, кстати: https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/raw/3a05f45e9c5fdc1fcf51c590672ac13889001e85/Dollchan_Extension_Tools.user.js

**Comment by ltyfdrjh** [comment]
Не подхватывает... сразу пробовал так сделать. НАСТРОЙКИ ИСПАРИЛИСЬ!

**Comment by SthephanShinkufag** [comment]
Может он зашел на сосач под другим адресом, 2ch.pm, например. Или вообще через анонимайзер, который меняет целевой адрес.

**Comment by VisualKei** [comment]
Не, я в такие помойки, где надо скрывать тысячи тредов и выбирать из говна орешки, вообще не хожу, лол.

**Comment by ltyfdrjh** [comment]
Адрес тот же, страницу обновил просто. Где настройки хранятся?  Нашел только Dollchan_Extension_Tools.db, но там нет моих правил автоскрытия.

**Comment by Y0ba** [comment]
Браузер какой?

**Comment by ltyfdrjh** [comment]
Firefox 47.

**Comment by Y0ba** [comment]
> Dollchan_Extension_Tools.db, но там нет моих правил автоскрытия.

А что там? Это база данных sqlite, там и должны быть все настройки.

**Comment by Y0ba** [comment]
Попробуй открыть [этой программой](http://sqlitebrowser.org) db-файл и найти там `DESU_Config`. Пик релейтед. Если и там нет, то значит настройки действительно удалились.

![screenshot_20170621015038](https://user-images.githubusercontent.com/1163958/27359436-641bc692-5624-11e7-97e4-356e199ab310.png)

**Comment by ltyfdrjh** [comment]
Пусто. Пиздец короче. Месяцы добавления правил вскрытия на всякое говно. Пойду плакать.

**Comment by SthephanShinkufag** [comment]
Настройки пропали не сразу после обновления на новую версию, а именно после правки.
Даже не могу предположить, что такого могло произойти, чтобы слетел конфиг.
Конечно, следует всегда иметь при себе бэкап, тем более что скрипт позволяет экспортировать настройки в файл. У меня кукла стоит и дома, и на работе, иногда приходится их синхронизировать.

Вообще любые важные для вас данные всегда нужно бэкапить. И хорошо, что это всего-лишь куклоскрипт, а не винт с фотографиями и домашними видео.

Насчет формы прикрепления файлов, если хотите убрать кнопку добавления по ссылке (которая круглая с плюсом), зайдите в `"Настройки"` > вкладка `"Общее"` > `"Пользовательский CSS"` > добавьте правило

```css
.de-file-off > .de-file-utils {
    opacity: 0;
}
```
