### ISSUE TITLE
Socket server?

### ISSUE THREAD

**Issue by sliterok** [SthephanShinkufag/Dollchan-Extension-Tools#1087]
Доброе утро/день/вечер, предлагаю сделать сокет-сервер.
Благодаря этому могут стать реальностью такие штуки:
- Обновление треда прямо в момент отправки поста другим человеком.
- Скрипт, для отправки постов с красивыми числами (даблы, триплы, етц)

Тащемто идея очень зеленая и бесполезная, но может выйти интересная штука.

**Comment by Y0ba** [comment]
Только причём тут куклоскрипт? Это всё реализуется владельцем борды, а кукла может только подхватить, если будет публичный API например с использованием `WebSocket`s.

**Comment by sliterok** [comment]
Так, как я понимаю, сейчас ни одна крупная борда не юзает websockets или хотя бы long poll.
Куклоскрипт может являться клевым костылем для современного web'а.

**Comment by Y0ba** [comment]
Ну так куклоскрипт клиентское приложение. Откуда скрипту брать эти сокеты? Они должны быть именно на сервере, куда отправляются посты.

Создать кеширующий прокси с этими самыми сокетами имело бы смысл, если бы 100% клиентов борды пользовались куклой.

**Comment by SthephanShinkufag** [comment]
Можно самому поднять сервер, но только для какой цели, полет фантазии с ним не велик. Можно разве что реализовать какое-нибудь общее для всех избранное например. Или снимать статистику и прочие печеньки на радость параноикам.

**Comment by sliterok** [comment]
Сокет сервер можно вешать хоть куда, лишь бы позволяла политика CORS на домене.

Да, конечно, не 100% юзеров борд юзает куклу, но нельзя отрицать факт того, что их достаточно много.

Сейчас посмотрел на сайт куклы и понял, что Backend туда не сунуть. Что ж, это не очень хорошо.

**Comment by sliterok** [comment]
Думайте, решайте, целей мало, но моё мнение выражено примерно где-то вот в этих всех сообщениях.
