### ISSUE TITLE
[4chan][uBlock][Tampermonkey]: Не отображается превью файла в форме ответа

### ISSUE THREAD

**Issue by lordtenma** [SthephanShinkufag/Dollchan-Extension-Tools#1093]
Не отображается превью выбраной пикчи:
https://puu.sh/wKclH.png

После перехода в избранный тред панель становится прозрачной.
До: https://puu.sh/wKc6G.png
После: https://puu.sh/wKcc5.png

На ычане оба бага отсутствуют.

Greasemonkey 3.11
Firefox Nightly 56.0a1 
Windows 10 64

**Comment by Dezaimasu** [comment]
Превью не отображается из-за фильтров рекламорезки, uBlock или что там у тебя. В EasyList есть правило, блочащее все blob ресурсы на форчанях. 
Можешь вырубить подписку, но проще тупо добавить 4chan.org в вайтлист, не то чтобы там было что блокировать.

**Comment by lordtenma** [comment]
Я на uBlock сразу грешить начал но нет, превью отсутствует даже с выключеными аддонами.

**Comment by RosinSmoke** [comment]
Подтверждаю, без рекламорезок тоже отсутствует превью. Кукла свежая.

Заодно, это я бака, или на форчане пока не поддерживается галка, которая постит изображение под спойлером?

**Comment by SthephanShinkufag** [comment]
> После перехода в избранный тред панель становится прозрачной.

Исправлено.

> Не отображается превью выбраной пикчи

Не могу добиться бага.

**Comment by SthephanShinkufag** [comment]
> Не отображается превью выбраной пикчи:

![](https://puu.sh/wKclH.png)

Ежели кто знает, как этого бага добиться - пишите.

**Comment by Remu-rin** [comment]
> Ежели кто знает, как этого бага добиться - пишите.

[uBlock Origin](https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/) или любой блокировщик с EasyList. Там есть CSP-фильтр `*$csp=default-src 'self' * data: 'unsafe-inline' 'unsafe-eval'` (второй фильтр `||4chan.org^$csp=connect-src https: http:` из собственных фильтров юблока невиновен):
![image](https://user-images.githubusercontent.com/28995228/34646104-703a5a6a-f381-11e7-8964-882aca722448.png)
Из-за которого в консоли:
`Content Security Policy: The page’s settings blocked the loading of a resource at blob:https://boards.4chan.org/755212d8-3b0b-4baf-8db1-df337e8fd3bf (“default-src https://boards.4chan.org * data: 'unsafe-inline' 'unsafe-eval'”). `
А превью не грузится.

**Comment by Remu-rin** [comment]
> Можешь вырубить подписку, но проще тупо добавить 4chan.org в вайтлист, не то чтобы там было что блокировать.

Уже есть что блокировать. Хиро поднасрал недавно запросами на малварные домены и поломкой css, в случае если скрипты сайта увидят, что запросы заблочены (например, юматриксом). Так что вайтлистить форчан крайне нежелательно. Рефы:
https://github.com/uBlockOrigin/uAssets/commit/43eb4648ba1126a58c933177da00154d469536dd (проблема с Violentmonkey в комментах исправлена правкой фильтра в другом коммите)
https://gitlab.com/N3X15/argon-dissection

**Comment by lordnoobw** [comment]
Сейчас превью и вправду исчезает только с включеным юблоком. Можно это правило как-то завайтлистить?

**Comment by Y0ba** [comment]
В Firefox 59 и выше всё работает (после исправления [1415352](https://bugzilla.mozilla.org/show_bug.cgi?id=1415352)). Так что тут только ждать обновление браузера.

**Comment by Y0ba** [comment]
Хотя на самом деле всё должно работать даже в 58 лисе. Правильный баг [1407056](https://bugzilla.mozilla.org/show_bug.cgi?id=1407056).

**Comment by Remu-rin** [comment]
> Можно это правило как-то завайтлистить?

В My filters: `@@*$csp=default-src 'self' * data: 'unsafe-inline' 'unsafe-eval',domain=4chan.org`

@Y0ba 
Что-то у меня и на найтли аналогично. Или должны юблок/Violentmonkey обновиться под эти фиксы?

**Comment by Y0ba** [comment]
Видимо работает только в гризманки. Разные способы инжекции скрипта. Надо переходить на аддон и забить на юзерскрипты. С аддоном все эти ограничения можно обойти.

**Comment by SthephanShinkufag** [comment]
@Y0ba, у меня возникли вопросы по регистрации аддона: #1163

**Comment by lordnoobw** [comment]
> В My filters: `@@*$csp=default-src 'self' * data: 'unsafe-inline' 'unsafe-eval',domain=4chan.org`
Спасибо, помогло.

**Comment by SthephanShinkufag** [comment]
Этот баг теперь остался только в Firefox + Tampermonkey.
