### ISSUE TITLE
Скрыть все треды?

### ISSUE THREAD

**Issue by sooqua** [SthephanShinkufag/Dollchan-Extension-Tools#1094]
Вместо того, чтобы скрывать треды по одному, возможно ли автоматически скрыть все треды на доске?
Пробовал так, но почему-то не работает:
`$('div.thread:visible').find('.oppost').find('svg.de-btn-hide').click()`

**Comment by UserNaem** [comment]
Можно спеллом `#op`, например.

**Comment by sooqua** [comment]
Я имел ввиду скрыть все видимые треды. Что бы можно было проскроллить до конца и скрыть всё сразу, а не по одному.
