### ISSUE TITLE
2ch.hk При отправке жалобы не передаётся номер поста, на который жалуешься

### ISSUE THREAD

**Issue by VictorDragonslayer** [SthephanShinkufag/Dollchan-Extension-Tools#1096]
Процитирую мой разговор с модератором в /d/ (состоялся в https://2ch.hk/d/res/469466.html):

>[ None ] [dsg] шитпостинг

>[ None ] [dsg] шитпостинг

>[ None ] [dsg] шитпостинг

>[ None ] [dsg] шитпостинг

>[ None ] [ #23141384 ]	[dsg] Владикодебил

>[ None ] [dsg] шитпостинг

> У меня для тебя плохие новости.

> Ты не репортил никаких посты, просто писал "шитпостинг" и отсылал жалобу. 

> https://2ch.hk/d/res/379434.html Делаю, как написано там, ибо кукла. Хочешь сказать, эта отметка не срабатывает?

> Вот сейчас выделил свой предыдущий пост(>>469543) и отправил репорт с текстом "тест галочки". Можешь глянуть, содержит ли репорт номер поста?

> № 469466 [ d ] [ None ] [Консольщик в /vg/] тест галочки

> Нет.

> Зарепортил таким же образом тот же пост, но с выключенной куклой. Номер поста прошёл?

> № 469466 [ d ]\t[ #469543 ]\t[Консольщик в /vg/] тест галочки (без куклы)

Иными словами, чекбоксы в постах не выполняют свою функцию - их включение не крепит номера постов к жалобе.

Версия скрипта: v17.6.20.0.dd3c76e

**Comment by SthephanShinkufag** [comment]
Теперь Dollchan добавляет свою кнопку репорта к постам.
Насчёт поля жалобы внизу страницы на досках со старым движком, я посмотрю потом.
