### ISSUE TITLE
[2ch.hk]: Упорядочить по двачую и рейджам на /po и /news

### ISSUE THREAD

**Issue by apan65** [SthephanShinkufag/Dollchan-Extension-Tools#1098]
Возможно ли добавить такую функцию скрипт, чтобы сообщения переставлялись по количеству этих приблуд?

**Comment by vanya1996** [comment]
В /news двачую и рейдж вообще нельзя поставить, кнопки есть, но они не нажимаются

**Comment by apan65** [comment]
Не, это проблема то ли файрфокса, то ли адблока\носкрипта и прочих плагинов.
