### ISSUE TITLE
Избранные: отображать число постов адресованных конкретно тебе

### ISSUE THREAD

**Issue by Aquinary** [SthephanShinkufag/Dollchan-Extension-Tools#1101]
Доброго времени суток!
Имеется ли возможность добавить опцию, после применения которой в избранных показывалось бы число постов, адресованных конкретно мне?

**Comment by UserNaem** [comment]
Уже есть счётчик непрочитанных ответов на свои посты.

**Comment by Aquinary** [comment]
Его надо как-то включать в опциях?

**Comment by UserNaem** [comment]
Нет, только обновить список избранных тредов.
