### ISSUE TITLE
В свежей лисе съедаются картинки по прямым линкам

### ISSUE THREAD

**Issue by Reisenfag** [SthephanShinkufag/Dollchan-Extension-Tools#1103]
На любых сайтах. Похоже скрипт убивает всю страницу, которую генерирует лиса для показа пикчи. Но закешированные картинки показываются.
FF 55.0.2, e10s выключен, GreaseMonkey.

**Comment by Dezaimasu** [comment]
Та же история. Может не на любых, но с борд точно. В консоли:


ReferenceError: vAPI is not defined[Learn More] 
contentscript.js:90:1

[Exception... "Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIDOMWindowUtils.addSheet]"  nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame :: resource://gre/modules/ExtensionUtils.jsm :: runSafeSyncWithoutClone :: line 52"  data: no]
(unknown)

runSafeSyncWithoutClone resource://gre/modules/ExtensionUtils.jsm:52:14
inject/cssPromise< resource://gre/modules/ExtensionContent.jsm:306:13

**Comment by Y0ba** [comment]
Это проблема гризманки, а не куклы. В кукле тут ничего не сделаешь. Впрочем, можно попробовать добавить в начало правила:
```
// @exclude     *.jpg
// @exclude     *.jpeg
// @exclude     *.gif
// @exclude     *.png
// @exclude     *.svg
```

**Comment by Dezaimasu** [comment]
@Y0ba не только картинки, цуиьки в отдельных вкладках тоже сломались, то не грузятся, то частично грузятся. Уже было такое когда он только выкатил 3.11, из-за конфликта с NoScript, перекатился тогда с него на uMatrix, судя по всему не то что надо перекатил, надо было сразу обезьяну менять.
https://github.com/greasemonkey/greasemonkey/issues/2500

**Comment by Y0ba** [comment]
Правила выше не помогли?

**Comment by Dezaimasu** [comment]
Да я не стал пробовать, потом обнова они слетят, сразу откатился на предыдущий greasemonkey, всё заработало, сейчас webext-аналоги ковыряю, всё равно перекатываться.

**Comment by Y0ba** [comment]
Просто если сработают, то могу добавить в куклу.

**Comment by Dezaimasu** [comment]
Неа, не сработали. Так же случайные картинки не открываются. Да и фиг с ними.

**Comment by SthephanShinkufag** [comment]
Шалом, товарищи.
Firefawx 55.0.3 (64-бит)
Greezemonkey 3.11

![whatiamdoingwrong](https://user-images.githubusercontent.com/1059874/29909655-99c739fa-8e2f-11e7-9f4e-488ae5d4822a.gif)


ЧЯДНТ?

**Comment by SthephanShinkufag** [comment]
У вас какие-то аддоны конфликтуют, инфа 100%.

**Comment by UserNaem** [comment]
Когда-то у меня было что-то похожее: под пикчами с некоторых борд была панель dE. Вылечилось включением e10s и\или обновлением Greasemonkey.

**Comment by Remu-rin** [comment]
> Firefawx 55.0.3 (64-бит)
> Greezemonkey 3.11

Тоже не могу воспроизвести, даже отключив e10s.
Алсо заметил, что без e10s вызов настроек/избранного куклы через альт+S/F не выводит меню лисы, которое на просто альте. С e10s оно вылезает постоянно.

**Comment by Reisenfag** [comment]
Так и не нашёл, что мешало. Вылечил переходом на Tampermonkey, что давно думал сделать.

**Comment by Remu-rin** [comment]
> Tampermonkey

Нашёл на что переходить. Проприетарщина, обфускация кода, телеметрия. Есть ведь чистый Violentmonley.

**Comment by HYBRID-BEING** [comment]
У меня конфликтует с uBlock Origin. Когда отключаю его (в аддонах, не ⏻) или куклоскрипт, ссылки робят нормально.

**Comment by Rolfeg** [comment]
Конфликтует с uBlock Origin. 
C violentmonkey помогает отключение "предварительно загружать кратинки". С greasemonkey это помогает лишь частично - часть картинок в новой вкладке не прогружается совсем.

**Comment by Dezaimasu** [comment]
Greasemonkey 3.10 замечательно работает. Алсо WebExt версия пилится, ранняя альфа уже на гитхабе:
https://github.com/arantius/greasemonkey/releases/tag/4.0alpha1

Violentmonkey не умеет инжектить скрипты на сайтах с огроженной CSP, это гитхаб, тумблер, твиттер, и бог весть что ещё. 
https://github.com/violentmonkey/violentmonkey/issues/173
Это вроде бы как баг лисы, потому что вообще расширения должны инжектить скрипты без проблем. Проприетарный Tampermonkey это делает какими-то грязными(??) трюками https://github.com/Tampermonkey/tampermonkey/issues/418

**Comment by VictorDragonslayer** [comment]
https://github.com/gorhill/uBlock/releases/tag/1.14.10

> Firefox

> There are many reports of people experiencing issues with some web sites, or images not loading, etc. Turns out many of these are a result of using some legacy extensions along uBO/webext. For instance, Reek's AAK in GreaseMonkey has been causing issues with images not loading.

> If you experience such issue, you will have to disable all your legacy extensions and see if this fixes your issue. If so, then you will have to re-enable your legacy extension one by one to find the one(s) causing the problem.

Сам пользуюсь следующим трюком: открываю пикчу по прямой ссылке, кликаю на обезьянью морду, F5, снова кликаю по морде.

**Comment by HYBRID-BEING** [comment]
Waterfox 56.0.3, Greasemonkey 3.17, скрипт свежий. Всё ещё конфликтует с uBlock. ~~Перелезать на WebExtensions не вариант.~~

**Comment by Remu-rin** [comment]
> Перелезать на WebExtensions не вариант.

Ну так и не перелезай. Верни legacy uBlock (1.13.8 с AMO, либо любой .xpi с гитхаба на вкус, пока Горхил не дропнул легаси). Это же проблема конфликта webext uBlock и легаси-расширений (в данном случае Greasemonkey). https://github.com/gorhill/uBlock/wiki/Firefox-WebExtensions#read-carefully-if-using-ubowebext
Либо сиди чисто на легасях, либо заменяй всё на вебэксты. Смешиваешь - твои проблемы.

**Comment by HYBRID-BEING** [comment]
Спасибо за совет. Попробую побольше разузнать про поддержку GM в Waterfox (GM4 в текущий момент с Waterfox'ом криво работает).
