### ISSUE TITLE
Поддержка lolifox.org

### ISSUE THREAD

**Issue by Remu-rin** [SthephanShinkufag/Dollchan-Extension-Tools#1105]
Что-то никто из лисичек так и не написал.
Перекат брчана, движок тот же. Кажется нужна лишь одна строка с присваиванием настроек домену.

**Comment by SthephanShinkufag** [comment]
А що, брчан почил? Стори?
Какие за лето глобальные изменения в рубордосфере?
Я просто с джвухмесячной разморозки.

**Comment by Remu-rin** [comment]
Почил. Стори: https://lolifox.org/br/src/1499175533216-0.jpg
Если коротко, то можно обойтись одним постом над картинкой майора с 10 пунктами.

**Comment by SBVAVVTQ** [comment]
Враньё. Брчан жив и здоров. 
ru.brchan.org

**Comment by SthephanShinkufag** [comment]
@SBVAVVTQ, пофиксил.
