### ISSUE TITLE
[Баг] Коррекция времени в постах с некоторыми шаблонами может рушить верстку

### ISSUE THREAD

**Issue by WagonOfDoubt** [SthephanShinkufag/Dollchan-Extension-Tools#1106]
На примере [nowere.net](https://nowere.net):

Шаблон поиска: `nn+dd+yy+w+hh+ii+?s?s?`
Шаблон замены: `_w _d _M _Y _h:_i:_s`

В результате удаляется `<` из закрывающего тега `</label>`, верстка рушатся, скрипт не инициализурется (Delform parsing error: No threads detected!) и не дает открыть настройки.

Скорее всего там почему-то меняется `outerHTML` вместо `innerHTML`.

Помимо этого, классу `DateTime` не помешал бы небольшой рефакторинг, в [этом](https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/blob/93d02002f40de3bc87c63818e5b267b3f324e83a/src/modules/TimeCorrection.js#L97) месте месяца захардкожены, неплохо бы это дело вынести в Localization.js, как-то так:
```javascript
const LngMonths = [
  ['янв', 'сiч', 'jan'],
  ['фев', 'лют', 'feb'],
  ['мар', 'бер', 'mar'],
  ['апр', 'квi', 'apr'],
  ['май', 'мая', 'тра', 'may'],
  ['июн', 'чер', 'jun'],
  ['июл', 'лип', 'jul'],
  ['авг', 'сер', 'aug'],
  ['сен', 'вер', 'sep'],
  ['окт', 'жов', 'oct'],
  ['ноя', 'лис', 'nov'],
  ['дек', 'гру', 'dec']
];
```

**Comment by Y0ba** [comment]
> `nn+dd+yy+w+hh+ii+?s?s?`

Вообще по идее вместо последнего плюса должен стоят минус, ну да ладно. Сделал так, чтобы плюс не включал в себя символ `<`.
