### ISSUE TITLE
410chan.org: некорректно сохраняются спеллы в настройках

### ISSUE THREAD

**Issue by WagonOfDoubt** [SthephanShinkufag/Dollchan-Extension-Tools#1107]
По какой-то причине при правке спеллов в конфиге они сохраняются с лишними кавычками, в результате чего спеллы не парсятся, и при следующем заходе скрипт падает.

Как воспроизвести:

- Для чистоты эксперимента, идем в Правку и редактируем JSON настроек: `"spells": "",`
- Проведем с окном спеллов любую манипуляцию, например нажмем "Очистить"
- Снова жмем "Правка" чтобы обновить настройки и видим: `"spells": "\"[1504648343459, null, null, null]\"",`
- Вот это `\"` не появляется на других бордах. Результатом является то, что JSON.parse вместо массива возвращает строку, индексы указывают на буквы, гроб гроб кладбище.

**Comment by WagonOfDoubt** [comment]
Кстати, зачем вообще массив `spells` должен оборачиваться в строку? Получается JSON в JSON'е.

**Comment by SthephanShinkufag** [comment]
Баг не воспроизводится.

```
"spells": "[1505110282870,null,null,null]"
```

**Comment by WagonOfDoubt** [comment]
Воспроизводится в Firefox 55.0.2 в Ubuntu 16.04 Widnows 10 с последней куклой и Tampermonkey v4.4.5484. В Chrome работает нормально, как и в Firefox на любой другой борде.
Скорее всего это Non-script bug, но по крайней мере [здесь](https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/blob/6a24977f6c39e62dfb9f861ef49e9f8851b25f46/src/modules/Spells.js#L35) стоит добавить валидацию, что возвращается массив, а не строка.

**Comment by SthephanShinkufag** [comment]
Таки добился бага.
Забавно, с тамперманки на автобусе выполняю в консоли

```js
JSON.stringify([])
```

результат:

```
""[]""
```

На любых других ресурсах, как и должно быть,

```
"[]"
```

wtf

А гризманки умная, там свой JSON.stringify с блекжэеком и девками, поэтому там тоже

```
"[]"
```

**Comment by SthephanShinkufag** [comment]
> зачем вообще массив spells должен оборачиваться в строку

Зойпелил, чтобы не оборчаивались.
Спеллы теперь хранятся в json как массив, а не строка, всё красиво.

```diff
@@ -2693,11 +2693,11 @@ function initStorageEvent() {
 				temp.checked = data.hide;
 			}
 			$hide(docBody);
 			if(data.data) {
 				Spells.setSpells(data.data, false);
-				Cfg.spells = JSON.stringify(data.data);
+				Cfg.spells = data.data;
 				temp = $id('de-spell-txt');
 				if(temp) {
 					temp.value = Spells.list;
 				}
 			} else {
@@ -6771,15 +6771,18 @@ var Spells = Object.create({
 		this._init();
 		return this.outreps;
 	},
 	get list() {
 		var str, reps, oreps, data;
+		if(typeof Cfg.spells === 'string') {
+			Cfg.spells = JSON.parse(Cfg.spells);
+		}
 		if(Cfg.spells === null) {
 			return '#wipe(samelines,samewords,longwords,symbols,numbers,whitespace)';
 		}
 		try {
-			data = JSON.parse(Cfg.spells);
+			data = Cfg.spells;
 		} catch(e) {
 			return '';
 		}
 		str = data[1] ? this._decompileScope(data[1], '')[0].join('\n') : '';
 		reps = data[2];
@@ -6808,11 +6811,11 @@ var Spells = Object.create({
 			chk = $q('input[info="hideBySpell"]'),
 			spells = val && this.parseText(val);
 		if(!val || spells) {
 			if(!spells) {
 				try {
-					spells = JSON.parse(Cfg.spells);
+					spells = Cfg.spells;
 				} catch(e) {}
 				spells = spells || [Date.now(), [], null, null];
 			}
 			var idx, scope = aib.t ? [aib.b, aib.t] : null,
 				sScope = String(scope),
@@ -6862,11 +6865,11 @@ var Spells = Object.create({
 				saveCfg('hideBySpell', 0);
 				if(chk) {
 					chk.checked = false;
 				}
 			}
-			saveCfg('spells', JSON.stringify(spells));
+			saveCfg('spells', spells);
 			this.setSpells(spells, true);
 			if(fld) {
 				fld.value = this.list;
 			}
 			Pview.updatePosition(true);
@@ -6993,18 +6996,18 @@ var Spells = Object.create({
 		var spells, fld = $id('de-spell-txt'),
 			val = fld.value;
 		if(val && (spells = this.parseText(val))) {
 			closePopup('err-spell');
 			this.setSpells(spells, true);
-			saveCfg('spells', JSON.stringify(spells));
+			saveCfg('spells', spells);
 			fld.value = this.list;
 		} else {
 			if(!val) {
 				closePopup('err-spell');
 				SpellsRunner.unhideAll();
 				this.disable();
-				saveCfg('spells', JSON.stringify([Date.now(), null, null, null]));
+				saveCfg('spells', [Date.now(), null, null, null]);
 				locStorage['__de-spells'] = '{"hide": false, "data": null}';
 				locStorage.removeItem('__de-spells');
 			}
 			$q('input[info="hideBySpell"]').checked = false;
 		}
@@ -7054,12 +7057,15 @@ var Spells = Object.create({
 			});
 			return;
 		}
 		var spells, data;
 		try {
-			spells = JSON.parse(Cfg.spells);
-			data = JSON.parse(sesStorage['de-spells-' + aib.b + (aib.t || '')]);
+			if(typeof Cfg.spells === 'string') {
+				Cfg.spells = JSON.parse(Cfg.spells);
+			}
+			spells = Cfg.spells;
+			data = sesStorage['de-spells-' + aib.b + (aib.t || '')];
 		} catch(e) {}
 		if(data && spells && data[0] === spells[0]) {
 			this.hash = data[0];
 			this._setData(data[1], data[2], data[3]);
 			return;
```

Но! Теперь, если вдруг захочется поставить старые версии скрипта, они не распознают спеллы, тому що будут требовать строку.
Поэтому применять это в коммит я не буду.

**Comment by SthephanShinkufag** [comment]
Так и не разобрался, чому `JSON.stringify` так ведёт себя с массивами на `410chan.org`.
Где-то он переопределяется, может быть, не нашёл.
Костыли-костылики.

**Comment by Y0ba** [comment]
> Где-то он переопределяется

Такое было в некроопере. Однако в современных браузерах юзерскрипты выполняются с отдельным глобальным объектом (из-за чего есть костыль в виде `$script` чтобы модифицировать глобальный объект страницы) и на него скрипты иб влиять не могут.

**Comment by Y0ba** [comment]
На самом деле страница определяет `Array.prototype.toJSON`. Достаточно сделать `delete Array.prototype.toJSON` где-то в начале скрипта и всё будет работать нормально (кроме, возможно, сохранения данных самой страницы). Странно что на `JSON.stringify` юзерскрипта это влияет. Это баг браузера.

**Comment by SthephanShinkufag** [comment]
![jsonstringify_corrupted](https://user-images.githubusercontent.com/1059874/32099609-9998ac40-bb19-11e7-9491-7139740f32c6.png)

> `Array.prototype.toJSON`.
Ах вот оно что... На автобусе этот метод добавляет какая-то библиотека `protoaculous-compressed.js`.
Спасибо, однако.
