### ISSUE TITLE
Косяк с загрузкой/сохранением настроек скрипта

### ISSUE THREAD

**Issue by sanscriptum** [SthephanShinkufag/Dollchan-Extension-Tools#1109]
Здравия всем в этом тредике.

Тут короче трабла - то ли у меня что-то с настройками уже не то (я переношу те же настройки уже долгое время), то ли у скрипта проблема - когда сейвишь настройки и потом пытаешься их загрузить, кукла жалуется мол incorrect data format.
Я долго думал в чем косяк, может в версии проблема, но это не так. К тому же кукла отлично сейвит и грузит свежие настройки сразу после установки.
Вот я и выяснил в чем загвоздка была - в двух последних настройках в дамп файле: ``"hotkeys":undefined,"exclude":4chan.org``.
Походу то что их значения не были в кавычках заставлял скрипт, как говорится, shit itself. Проверьте чтоль, че там как.

**Comment by SthephanShinkufag** [comment]
Спасибо за багрепорт.
С `"exclude":4chan.org` порешал, теперь файл будет генерироваться с кавычками для exclude.

А с hotkeys сейчас всё норм:

'"hotkeys":' + (cfgData[1] || '""'),

ведь

```js
undefined || '' === ''
```

Откуда у вас там взялось `"hotkeys":undefined`, пока не понятно.
