### ISSUE TITLE
Greasemonkey 4 support

### ISSUE THREAD

**Issue by SthephanShinkufag** [SthephanShinkufag/Dollchan-Extension-Tools#1110]
http://www.greasespot.net/2017/09/greasemonkey-4-for-script-authors.html
https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/versions/beta

GM.getValue теперь асинхронная шняга.

Попытаюсь зойпелить.

**Comment by Y0ba** [comment]
Мда уж. Результат не впечатляет. Инициализация скрипта заметно замедлилась. Причём замедлилась в двух местах: (1) при чтении конфига во время инициализации и (2) при скрытии постов.

Даже в хроме из-за асинхронщины такого замедления нет, поскольку скрипт загружается ещё до создания DOM-дерева и параллельно загружает конфиг. Webextension API лисы такого не позволяют и поэтом гризманки все скрипты запускает после создания DOM-дерева.

Второй случай интересней. В хроме тоже из-за этого есть замедление. Как решение нужно загружать список избранного вместе с конфигом, а всю функцию скрытия постов сделать синхронной.

**Comment by Y0ba** [comment]
> Инициализация скрипта заметно замедлилась.

Более-менее удалось решить проблему. Теперь у меня загрузка идёт 25 - 50мс, что нормально (в первой версии было 280 - 1200мс).

Теперь осталось только дождаться пока в `GM.xhr` добавят функцию отмены запроса и поддержку можно считать полноценной.

**Comment by Y0ba** [comment]
> Теперь у меня загрузка данных из хранилища идёт 25 - 50мс

С 8996c913435bedca24c764a1d1aa6120fa045559 теперь 5-7мс. Даже быстрее чем было со старой версией.

**Comment by SthephanShinkufag** [comment]
Спасибо!
Только что-то сам 4 Greasemonkey не ставится на Nightly 58.0a1 (2017-10-09) (64-бит).
А на стабильной лисе (56) я не могу установить в него куклу, в списке скриптов пусто.
wtf

**Comment by Y0ba** [comment]
Ставится (у меня стоит). Просто автор его не пометил совместимым.
![screenshot_20171010102153](https://user-images.githubusercontent.com/1163958/31373996-d7719edc-ada4-11e7-8139-57342530f399.png)

Алсо, список скриптов и у меня не переносится. Впрочем, это не наша проблема.

**Comment by Y0ba** [comment]
Ах да, с локального файла срипты почему-то не ставятся, только с гитхаба. Ну и ещё скрипт отлаживать невозможно от слова совсем. Даже выкинутые ошибки нормально не отображаются.

**Comment by SthephanShinkufag** [comment]
В том-то и прикол, что пикрелейтед.
![1507540429871044](https://user-images.githubusercontent.com/1059874/31374147-72d2ea70-ada5-11e7-8be3-611569ef96b3.jpg)

Система свежая, ночнушку поставил только что.

**Comment by Y0ba** [comment]
Теперь просто перетащи скачанный файл в браузер, он и поставится.

**Comment by SthephanShinkufag** [comment]
>перетащи скачанный файл в браузер

Не, ни хрена :(

**Comment by Y0ba** [comment]
Поставь в `about:config` `extensions.legacy.enabled;true`.

Гризманки ещё не совсем webextension-дополнение.

**Comment by SthephanShinkufag** [comment]
> Гризманки ещё не совсем webextension-дополнение

Ах вот оно что..
Заработало, danke.

**Comment by Incurious** [comment]
Наверно зря сюда пишу, ну ладно.
Не устанавливается esnext версия с гитхаба. Такая же фигня со скриптом против рекламы была, только там были зеркала скрипты на ещё 3-х сайтах, и только с гитхаба он не устанавливался.

**Comment by SthephanShinkufag** [comment]
Greasemonkey 4 сырая, как решето. У меня не получается установить туда скрипт на свежий профиль. Ни с гитхаба, ни перетягиванием в браузер локального файла. Получилось установить скрипт в гризмонки 3.17, а потом обновить до гризмонки 4. По-другому скрипт не устанавливается.

**Comment by Incurious** [comment]
@SthephanShinkufag Проблема только со скриптами с гитхаба.
Алсо открыл тему у грисманки в гитхабе, там выяснили что этот баг задевает лису 56+, на 55 и ниже бага нет. Так что именно эту проблему можно закрывать.

**Comment by SthephanShinkufag** [comment]
Обновилась Лиса, вместе с ней обновилась гризманки до 4 версии.
Теперь скрипт нельзя установить по ссылке, или перетягиванием файла скрипта в браузер.

RIP greasemonkey...
2005-2017

**Comment by Y0ba** [comment]
Починят же, наверное. Можно вручную установить: создать новый скрипт и скопипастить содержимое.

**Comment by SthephanShinkufag** [comment]
Где кнопка создать новый скрипт? Пункт меню? Хоть что-нибудь? Или я в глаза долблюсь?
Нельзя новый скрипт создать.

**Comment by SthephanShinkufag** [comment]
![15100899983030](https://user-images.githubusercontent.com/1059874/32802122-c82ddc66-c987-11e7-9a32-fef13889448c.png)

**Comment by Y0ba** [comment]
А ведь точно, её ещё нет. А установку с гитхаба починят не раньше 59 версии лисы: https://bugzilla.mozilla.org/show_bug.cgi?id=1415352

Про установку с локального файла, видимо, можно вообще не заикаться.

Ждём и надеемся. :zzz:

**Comment by SthephanShinkufag** [comment]
Как так вышло, чому разраб прослоупочил? Я не понимаю. неужели всем пофиг до сих пор было, и не видели надвигающегося пиздеца.

На какой скрипт-органайзер теперь перекатываться, интересно.

**Comment by Y0ba** [comment]
Ну с гитхабом прослоупочили разрабы лисы. При этом даже в свежей ночнушке нет АПИ для полноценной реализации гризманки. Остальные работают с жуткими костылями, которые автор гризманки видимо добавлять не хочет. Например для нормальной работы `@run-at document-start` тамперманки удаляет скаченную браузером страницу, скачивает её заново и заново рендерит, предварительно запустив юзерскрипт  :scream:

**Comment by SthephanShinkufag** [comment]
Может, заняться разработкой Dollchan дополнения к Firefox?
https://developer.mozilla.org/ru/Add-ons/WebExtensions

**Comment by Y0ba** [comment]
Можно. Будет единое дополнение как для хрома, так и для лисы. Удобно.

**Comment by SthephanShinkufag** [comment]
Тогда буду усиленно изучать этот вопрос. Видимо, время юзерскриптов в наступающем 2k!8 подходит к концу.

**Comment by SthephanShinkufag** [comment]
Кстати, есть ещё
https://addons.mozilla.org/en-US/firefox/addon/violentmonkey/

Щас добавлю в вики.

**Comment by Incurious** [comment]
Ставите любой другой скрипт и вставляете в него сам код. Пришлось самому так делать.

**Comment by Incurious** [comment]
Ну и в новой бете Greasemonkey 4.1beta5 появилась кнопка создания нового скрипта.

**Comment by SthephanShinkufag** [comment]
Greasemonkey теперь нормально умеет в добавление и правку скриптов можно юзать.
Но всё ещё существует баг с отсутствием реферера при аякс-запросах на vichan-досках.
