### ISSUE TITLE
Разные настройки на разных бордах.

### ISSUE THREAD

**Issue by Incurious** [SthephanShinkufag/Dollchan-Extension-Tools#1111]
Greasemonkey 4.0 alpha 3 + Dollchan script ESNext
На каждом сайте свой доллчан со своим списком избранных, своими настройками и т.д. Не знаю почему. По крайней мере избранные должны синхронизироваться?

**Comment by SthephanShinkufag** [comment]
> Greasemonkey 4.0 alpha 3

Not so fast, dude.
Там теперь новое хранилище, его поддержка еще не зойпилена, скрипт вынужден использовать localStorage, ун7икальное для каждого домена.

Redirected to >> https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/issues/1110
