### ISSUE TITLE
Сброс скрытых тредов после отчистки кеша браузера

### ISSUE THREAD

**Issue by nowes** [SthephanShinkufag/Dollchan-Extension-Tools#1112]
v17.6.20.0.9cf3f06 Iron Chrome Версия 56.0.2950.1
На https://2ch.hk/ избранные треды остаются, но всё скрытие слетает после чистки Ccleaner. Для скрытия использую кнопку в оп-посте без доп. настроек.

**Comment by Y0ba** [comment]
Потому что скрытие хранится в localStorage (ради ускорения скрипта), который ccleaner и очищает.

**Comment by SthephanShinkufag** [comment]
Отключите очистку данных браузера при чистке.
