### ISSUE TITLE
Не пашет на брчан

### ISSUE THREAD

**Issue by SBVAVVTQ** [SthephanShinkufag/Dollchan-Extension-Tools#1113]
Впилите поддержку brchan.org и ru.brchan.org.  Кукла на них не запускается.

**Comment by SBVAVVTQ** [comment]
Капча отвалилась. 
![photo_2017-10-10_19-19-32](https://user-images.githubusercontent.com/32332750/31398007-3f2050fa-adf0-11e7-8b06-ed9ab6a526ae.jpg)

**Comment by SBVAVVTQ** [comment]
При постинге пишет "You look a bot"

**Comment by SthephanShinkufag** [comment]
@SBVAVVTQ Пусть удалят встроенный куклоскрипт, а то кина не будет.

**Comment by SthephanShinkufag** [comment]
Когда удалят встроенную куклу, сообщите здесь.
Сейчас она мешает выявить причину.

**Comment by SthephanShinkufag** [comment]
Проблема стандартная для vichan: изменение полей и кнопок в форме ответа приводит к тому, что движок борды считает запрос автоматизированным.
Коммит это вроде бы должен исправить, но сейчас по факту пост отправляется только один раз.
После первого поста запросы опять считаются как automated.
%банный тиниборд.

**Comment by SthephanShinkufag** [comment]
Вроде бы, постинг на брчане исправлен.

Ой вей, совсем забыл про капчу.
И де на брчане можно найти её? Не вижу.

**Comment by vanya1996** [comment]
![default](https://user-images.githubusercontent.com/26493956/32700180-3a4833d8-c7ca-11e7-9c48-82dc82557c7f.png)
![default](https://user-images.githubusercontent.com/26493956/32700189-4f29f2c8-c7ca-11e7-8b4c-b3fa682192db.png)
А я думал что я единственный у кого не отображается капча (в /rus/ она таки есть, про остальные борды не знаю, сидел только там и в /bb/, но бб перекатился на лолифокс, остался только rus)

**Comment by SthephanShinkufag** [comment]
> /rus/

@vanya1996, нет там капчи.
Может она есть только у анонов из России? Покажите скриншот.
