### ISSUE TITLE
ichan.net loads post twice at first auto-refresh

### ISSUE THREAD

**Issue by ihmena** [SthephanShinkufag/Dollchan-Extension-Tools#1114]
Example link (SFW):
http://ichan.net/tech/res/741.html

Now it will at first appear normal, but when the auto-refresh ("Get new posts" link) happens, it will load a new copy of all posts and paste them below. It does this only once though on the first refresh. All others will work perfectly fine.

Tested in FF with GM and in Vivaldi with TM.
In one of my browsers I sometimes get "Connection failed" and it will not update, no idea what causes this, but it goes away some time or I just use a different browser - just in case you test it and encounter that.

Thank you

**Comment by Y0ba** [comment]
Well, I think administrators should fix layout issues on their side. All posts except first one placed outside of thread's `div` element. And also all threads except first one placed outside of `form` element.

![screenshot_20171005014755](https://user-images.githubusercontent.com/1163958/31203408-93d7088a-a96f-11e7-9834-e309884205e8.png)
![screenshot_20171005014818](https://user-images.githubusercontent.com/1163958/31203414-9a53bad2-a96f-11e7-92a5-eb7a4c15f150.png)

**Comment by ihmena** [comment]
Well, don't know about that, but your fix for the double-loading seems to have worked. Thank you. Although I could not verify yet that a real new post shows up (they have moderation for posts).

**Comment by ihmena** [comment]
Ok, auto-updating seems to work fine.

**Comment by undershoe** [comment]
Wait, what? What fix? How to fix it?
