### ISSUE TITLE
2ch.hk: Вебмемы сломались

### ISSUE THREAD

**Issue by CherryPerry** [SthephanShinkufag/Dollchan-Extension-Tools#1118]
1. Зайти в webm тред
2. Открыть webm для просмотра (настройка - открывать плеер в посте)
3. Закрыть webm

В итоге остается висеть черный плеер вместо возвращения превьюхи.

![default](https://user-images.githubusercontent.com/9081555/31908418-7cfa52f0-b83f-11e7-8a64-85d4d4921f6f.PNG)

С настройкой открытия файлов в окне тоже остается черный незакрываемый плеер.

![default](https://user-images.githubusercontent.com/9081555/31908506-cbac950c-b83f-11e7-8856-3b9f6fd794ec.PNG)

Кукла: 17.10.23.0
Хромоног: 62.0.3202.62

**Comment by CherryPerry** [comment]
А вот с картинками и mp4 такой проблемы нет.

**Comment by SthephanShinkufag** [comment]
Баг не воспроизводится.
Покажите скриншот Настройки > Картинки.

**Comment by SthephanShinkufag** [comment]
И да, скрипт через что установлен - через тамперманки или как расширение?

**Comment by CherryPerry** [comment]
Тампер, отвалилось после обновления куклы.

![default](https://user-images.githubusercontent.com/9081555/31909401-aacf72fc-b842-11e7-994d-5d1d4b64e844.PNG)

**Comment by CherryPerry** [comment]
Factory reset из tampermonkey с загрузкой бэкапа настроек скрипта не помог.

**Comment by SthephanShinkufag** [comment]
Спасибо, друже, проблема оказалась в настройке "Получать названия WebM из метаданных ".
Будем посмотреть, однако.

**Comment by SthephanShinkufag** [comment]
Предварительно: проблема началась после коммита ca7a73544f69af8ee3c950434e7c3f07c07ce351

Uncaught TypeError: this._webmTitleLoad.cancel is not a function

в строке https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/blob/master/src/modules/PostImages.js#L347

Пока что не вдуплился, в чём соль, и чому так.

**Comment by SthephanShinkufag** [comment]
Какого то фига я `downloadImgData` сделал асинхронной. Хотя она и так возвращает промис `$ajax`.

https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/commit/ca7a73544f69af8ee3c950434e7c3f07c07ce351#diff-54aec029510567217a68e063a6dbafa8R134

**Comment by SthephanShinkufag** [comment]
Исправлено.
Апнул версию еще раз, от греха подальше.
