### ISSUE TITLE
Не работает постинг на 8ch.net

### ISSUE THREAD

**Issue by Incurious** [SthephanShinkufag/Dollchan-Extension-Tools#1119]
С куклой не работает постинг, выдаёт следующее
Your browser sent an invalid or no HTTP referer.
Чтобы запостить приходится отключать куклу.

Greasemonkey 4.0Alpha8
Кукла последняя.

Самое главное забыл добавить, сижу на 8ch.net через frigate.

**Comment by SthephanShinkufag** [comment]
А без впнки нормально поститься?

**Comment by SthephanShinkufag** [comment]
На большинстве борд запрещено постить из открытых прокси, впн и анонимайзеров.

**Comment by Incurious** [comment]
Без впн я не могу даже зайти, лол.
С впн без доллчана постится нормально.

**Comment by SthephanShinkufag** [comment]
Выяснилось, что это из-за Greasemonkey. Анонимайзеры тут не при чём.
Снесите его, установите Violentmonkey или Tampermonkey.
