### ISSUE TITLE
А можно опцию для скрытия имени файла под открытой по центру пикчей?

### ISSUE THREAD

**Issue by UserNaem** [SthephanShinkufag/Dollchan-Extension-Tools#1120]
Ещё желательно исправить английский текст на "Open the original image in new tab".

![firefox_2017-10-26_19-07-51](https://user-images.githubusercontent.com/21028464/32057598-22f3a42a-ba81-11e7-841f-c5565d3079b7.png)

**Comment by SthephanShinkufag** [comment]
Используйте css

**Comment by SthephanShinkufag** [comment]
```css
.de-img-full-info {
    display: none;
}
```

**Comment by SthephanShinkufag** [comment]
Нет, картинки масштабируются с учетом места под имя файла.

**Comment by UserNaem** [comment]
А жаль. Ладно, когда стану веб-разработчиком (никогда), подкручу.

**Comment by SthephanShinkufag** [comment]
Что-нибудь придумаю.

**Comment by Satorisan** [comment]
Без имени файла под пикчей было лучше. Сейчас отвлекается внимание на надпись.

**Comment by WagonOfDoubt** [comment]
> Используйте css

Пользуясь случаем, напомню о https://wagonofdoubt.github.io/Dollchan-Extension-Tools/ru/css-tricks

**Comment by SthephanShinkufag** [comment]
@WagonOfDoubt, danke, друже. Вчера вечером стянул `gh-pages`, ознакамливаюсь.
Спасибо за проделанную работу!
Надо только придумать, как малой кровью автоматизировать синхронизацию с `wiki`. Видимо, есть только два стула, либо придётся править и там и там всегда, либо полностью перейти на `gh-pages` и забросить (удалить) вики-материал,
