### ISSUE TITLE
Изображения из буфера обмена

### ISSUE THREAD

**Issue by Klaster1** [SthephanShinkufag/Dollchan-Extension-Tools#1121]
Сейчас очень неудобно вставлять скриншоты нитей или иного в форму отправки сообщений. Я имею в виду, зачем создавать промежуточный файл, если в браузере уже имеются все подходящие API? Мой небольшой эксперимент[ подтверждает жизнеспособность](https://i.imgur.com/WC6rLCl.png) в Firefox и Chrome на Windows 10, использовались снимки экрана от Win+Shift+S и Alt+PrtScrn.

Вот разница:
```
diff --git a/src/modules/Form.js b/src/modules/Form.js
index 39e7354..1ec5048 100644
--- a/src/modules/Form.js
+++ b/src/modules/Form.js
@@ -36,6 +36,16 @@ function PostForm(form, oeForm = null, ignoreForm = false) {
 			}
 		}, 0));
 	}
+	this.txta.addEventListener('paste', (e) => {
+		for (let item of e.clipboardData.items) {
+			if (item.kind === 'file') {
+				const file = item.getAsFile()
+				const url = URL.createObjectURL(file)
+				const lastFileInput = this.files._inputs[this.files.filesCount]
+				lastFileInput._addUrlFile(url)
+			}
+		}	
+	})
 	this.name = $q(aib.qFormName, form);
 	this.mail = $q(aib.qFormMail, form);
 	this.subj = $q(aib.qFormSubj, form);
```
Как видно, используется внутренний метод FileInpupt.prototype._addUrlFile в связке с URL.createObjectURL. Если подобный подход будет останется и в будущем, то как минимум потребуется чистить ресурсы через URL.revokeObjectURL при успешной отправке формы. Уверен, что существуют детали, связанные с устройство куклоскрипта, про которые я могу лишь догадываться.

**Comment by Y0ba** [comment]
> потребуется чистить ресурсы через URL.revokeObjectURL

Можно чистить сразу после вызова `FileInput.p._addUrlFile` (либо добавить небольшой таймаут). Всё равно сейчас функция полностью считывает содержимое файла в память. Хоть всё изменится когда я все эти функции переведу на `streams`.

**Comment by Y0ba** [comment]
> Хоть всё изменится когда я все эти функции переведу на streams.

Впрочем к `_addUrlFile` это не имеет отношения. Полностью загружать файл всё равно придётся.

**Comment by Klaster1** [comment]
>Можно чистить сразу после вызова FileInput.p._addUrlFile (либо добавить небольшой таймаут)
Было бы логично возвращать Promise из _addUrlFile и очищать в finally, но это справедило только если идти по пути допиливания прототипа. Опять же, встаёт вопрос поддежки finally, я не нашёл ни единого вызова в кодовой базе – видимо, вы его не используете пока.

**Comment by Y0ba** [comment]
>  видимо, вы его не используете пока.

Потому что не все браузеры его ещё поддерживают. Вместо `.finally(foo)` можешь писать `.then(foo, e => { foo(); throw e; })`. Последний `throw` нужен, чтобы увидеть ошибку в консоли ошибок.

**Comment by Y0ba** [comment]
И, кстати, в `_addUrlFile` есть такие строки:
```js
let name = url.split('/').pop();
let ext = name.split('.').pop();
```
Надо бы их (и последующие проверки на тип файла) исправить, чтобы скрипт правильно определял имя и тип файла. Вроде в объекте [`File`](https://developer.mozilla.org/en-US/docs/Web/API/File), который возвращает событие `paste` всё это уже есть.

**Comment by Klaster1** [comment]
>Вроде в объекте File, который возвращает событие paste всё это уже есть.

Его name является read only и зависит от браузера. Имеет ли смысл заморачиваться, чтобы вместо guid получить абстрактное "изображение"?

**Comment by Y0ba** [comment]
Можно ведь вставлять и реально существующие файлы, так? Может добавить проверку например на точку и если её нет писать вместо имени `clipboard`, например.

**Comment by Y0ba** [comment]
И, кстати, можно в функцию `_addUrlFile` сразу передавать [MIME-type](https://developer.mozilla.org/en-US/docs/Web/API/File/type).

Можно переписать функцию как-то так:
```js
_addUrlFile(url, uData = null) {
	if(!url) {
		return Promise.reject(new Error("url is null"));
	}
	$popup('file-loading', Lng.loading[lang], true);
	return downloadImgData(url, false).then(data => {
		if(!data) {
			$popup('file-loading', Lng.cantLoad[lang] + ' URL: ' + url);
			return;
		}
		closePopup('file-loading');
		this._isTxtEditable = false;
		let imgName;
		let MIME;
		if(uData == null) {
			let name = url.split('/').pop();
			let ext = name.split('.').pop();
			if(!/^(jpe?g|png|gif|webm)$/.test(ext)) {
				switch((data[0] << 8) | data[1]) {
				case 0xFFD8: ext = 'jpg'; break;
				case 0x8950: ext = 'png'; break;
				case 0x4749: ext = 'gif'; break;
				case 0x1A45: ext = 'webm'; break;
				default: ext = '';
				}
				if(ext) {
					url = name = name.split('?').shift() + '.' + ext;
				}
			}
			imgName = name;
			MIME = getFileType(url);
		} else {
			imgName = uData.name;
			MIME = uData.MIME;
		}
		this.imgFile = [data.buffer, imgName, MIME];
		if(this._isThumb) {
			$hide(this._txtWrap);
		}
		this._onFileChange(true);
	});
}
```

**Comment by Y0ba** [comment]
Или если `MIME` в событии `paste` может прийти неправильным, можно сделать так:
```js
_addUrlFile(url, uData = null) {
	if(!url) {
		return Promise.reject(new Error("url is null"));
	}
	$popup('file-loading', Lng.loading[lang], true);
	return downloadImgData(url, false).then(data => {
		if(!data) {
			$popup('file-loading', Lng.cantLoad[lang] + ' URL: ' + url);
			return;
		}
		closePopup('file-loading');
		this._isTxtEditable = false;
		let name = uData ? uData.name : url.split('/').pop();
		if(uData ? !uData.MIME : !/^(jpe?g|png|gif|webm)$/.test(name.split('.').pop())) {
			let ext;
			switch((data[0] << 8) | data[1]) {
			case 0xFFD8: ext = 'jpg'; break;
			case 0x8950: ext = 'png'; break;
			case 0x4749: ext = 'gif'; break;
			case 0x1A45: ext = 'webm'; break;
			default: ext = '';
			}
			if(ext) {
				name = name.split('?').shift() + '.' + ext;
			}
		}
		let MIME = (uData && uData.MIME) || getFileType(name);
		this.imgFile = [data.buffer, name, MIME];
		if(this._isThumb) {
			$hide(this._txtWrap);
		}
		this._onFileChange(true);
	});
}
```

**Comment by SthephanShinkufag** [comment]
![pasteclipboardimage](https://user-images.githubusercontent.com/1059874/32227652-a8cf73fe-be54-11e7-9d92-39ce486feaeb.gif)
