### ISSUE TITLE
Неправильно определяются домены второго уровня

### ISSUE THREAD

**Issue by lisanyan** [SthephanShinkufag/Dollchan-Extension-Tools#1125]
Например
https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/blob/a324b35c9363e6b95624aa3b30425e6365091617/src/modules/BoardDetector.js#L1607
Вернет `pp.ua` при `window.location.hostname == 'buttflaps.pp.ua'` и не сдетектит доску

**Comment by Y0ba** [comment]
Потому что код для правильного определения доменов второго уровня будет занимать столько же места, сколько куклоскрипт в целом и должен будет периодически обновляться. А веб-апи для подобного не завезли. Но костыль всё равно как-то исправить надо.

**Comment by lisanyan** [comment]
Це понятно. Also мне показалось что это intended behavior чтобы выпиливать `www` из dm.

**Comment by Y0ba** [comment]
Можно попробовать инициализацию сделать вот так:
```js
var prot = window.location.protocol;
var dm = localData ? localData.dm : null;
if(checkDomains) {
	if(!dm) {
		let r = new RegExp(`(?:${Object.keys(ibDomains).map(_ => quoteReg(_)).join('|')})$`, 'i');
		let arr = window.location.hostname.match(r);
		if(arr) {
			dm = arr[0];
			return new ibDomains[dm](prot, dm);
		}
		
	} else if(dm in ibDomains) {
		return new ibDomains[dm](prot, dm);
	}
}
dm = window.location.hostname.match(/(?:(?:[^.]+\.)(?=org\.|net\.|com\.))?[^.]+\.[^.]+$|^\d+\.\d+\.\d+\.\d+$|localhost/)[0];
if(checkEngines) {
	for(var i = ibEngines.length - 1; i >= 0; --i) {
		var [path, Ctor] = ibEngines[i];
		if($q(path, doc)) {
			return new Ctor(prot, dm);
		}
	}
	return new BaseBoard(prot, dm);
}
return null;
```
Правда при совпадении домена код замедляется в ~3.5 раза на моей машине (`getImageBoard` замедляется c 0.37мс до 1.25мс), однако тогда такой ошибки как эта уже совсем не будет, какой бы плохой функция извлечения домена из хоста не была.

**Comment by Y0ba** [comment]
> `quoteReg(_)`

Правда насчёт этой функции я не уверен. Скорее всего её можно убрать. Тогда замедляется меньше чем в два раза (до 0.7мс).

**Comment by Y0ba** [comment]
Убрал из предыдущего поста `.map(_ => queteReg(_))` и заменил на `.replace(/\./g, '\\.')` после `join`а. Вряд ли в доменах будут встречаться спец-символы регексов, кроме точки. Как я и говорил получилось примерно в 1.5 - 2 раза медленней (от 0.58мс для 0.74мс).

**Comment by lisanyan** [comment]
В доменах еще `-` часто встречается

**Comment by Y0ba** [comment]
За пределами квадратных скобок он за спецсимвол не считается.

**Comment by lisanyan** [comment]
```javascript
var prot = window.location.protocol;
var dm = localData ? localData.dm : null;
if(checkDomains) {
	if(!dm) {
		let ibKeys = Object.keys(ibDomains);
		let i = ibKeys.length;
		while (i--) {
			if (ibKeys[i] === window.location.hostname.toLowerCase()) {
				dm = ibKeys[i];
				return new ibDomains[dm](prot, dm);
			}
		}
	} else if(dm in ibDomains) {
		return new ibDomains[dm](prot, dm);
	}
}
dm = window.location.hostname.match(/(?:(?:[^.]+\.)(?=org\.|net\.|com\.))?[^.]+\.[^.]+$|^\d+\.\d+\.\d+\.\d+$|localhost/)[0];
if(checkEngines) {
	for(var i = ibEngines.length - 1; i >= 0; --i) {
		var [path, Ctor] = ibEngines[i];
		if($q(path, doc)) {
			return new Ctor(prot, dm);
		}
	}
	return new BaseBoard(prot, dm);
}
return null;
```
Такой код не быстрее будет?

**Comment by Y0ba** [comment]
1) `window.location.hostname.toLowerCase()` - вот это надо вынести за пределы цикла.
2) Не `ibKeys[i] === window.location.hostname.toLowerCase()`, а `window.location.hostname.toLowerCase().endsWith(ibKeys[i])`

Сейчас проверю скорость.

**Comment by Y0ba** [comment]
Использовал такой код:
```js
if(checkDomains) {
	if(!dm) {
		let ibKeys = Object.keys(ibDomains);
		let i = ibKeys.length;
		let host = window.location.hostname.toLowerCase();
		while(i--) {
			if(host.endsWith(ibKeys[i])) {
				dm = ibKeys[i];
				return new ibDomains[dm](prot, dm);
			}
		}
	} else if(dm in ibDomains) {
		return new ibDomains[dm](prot, dm);
	}
}
```
Выходи 0.78мс - 0.85мс. В целом немного медленней, чем вариант с регексом.

Можешь протестировать на своей машине? Я просто в начало функции добавляю `var a = performance.now();`, а перед `return new ibDomains[dm](prot, dm);` добавляю `console.log(performance.now() - a);`

**Comment by lisanyan** [comment]
0.27мс - 0.45мс примерно получается после нескольких рефрешей.

**Comment by Y0ba** [comment]
А с мой вариант с регексами сколько? А оригинальный код сколько тратил?

**Comment by lisanyan** [comment]
С регексом ~0.45мс, оригинальный код - ~0.33мс,

**Comment by Y0ba** [comment]
Я тестировал на `2ch.hk`. Он первый в массиве, а значит проверяется последним. Наверное отсюда такая разница.

**Comment by SthephanShinkufag** [comment]
`if(host.endsWith(ibKeys[i])) {` использовать нельзя.
Тогда с `2ch.hk` будут совпадать `foo2ch.hk`, `blablabla2ch.hk`...

**Comment by Y0ba** [comment]
Тогда и в версии с регексом его надо исправить на
```js
let r = new RegExp(`[^.](${Object.keys(ibDomains).join('|').replace(/\./g, '\\.')})$`, 'i');
```
И вместо `dm = arr[0];` писать `dm = arr[1];`.

**Comment by SthephanShinkufag** [comment]
Можно так:

```js
			while(i--) {
				const key = ibKeys[i];
				if(host === key || host.endsWith('.' + key)) {
					dm = ibKeys[i];
					console.log(dm, performance.now() - a);
					return new ibDomains[dm](prot, dm);
				}
			}
```

**Comment by Y0ba** [comment]
Да, так будет лучше всего. Алсо в файл `es5-polyfills.js` надо будет добавить строку `require('core-js/fn/object/keys');` чтоб некробраузеры не сломались.

**Comment by Y0ba** [comment]
И ещё `require('core-js/fn/string/ends-with');`

**Comment by SthephanShinkufag** [comment]
У нас `Object.keys` уже встречается 4 раза. Как иогда оно работает?

**Comment by Y0ba** [comment]
Ах, он из es5, потому и везде поддерживается. Тогда только `ends-with`.
