### ISSUE TITLE
Разворачиваемые в посте картинки не вмещаются в экран #Баг

### ISSUE THREAD

**Issue by Dezaimasu** [SthephanShinkufag/Dollchan-Extension-Tools#1126]
Собственно. Пропустил момент когда именно это началось, но вроде вот недавно. Отдельная опция под это есть, а она не работает.

Ночнушка 58.0a1(2017-10-24) с Violentmonkey и только что поставленным ESNext куклоскриптом, или ESR 52.4.0 с Greasemonkey и ES5 куклоскриптом. Ычан, мейлач, форчани, везде такое. 

Создаю новый профиль, ставлю манки и куклоскрипт, захожу на любую борду, меняю одну опцию "раскрывать картинки" с дефолтного "по центру" на "в посте", опция "Умещать большие картинки в экран" и так включена. Открываю любую большую картинку, и она открывается как есть, во всю ивановскую, не сжимаясь чтобы втиснуться в экран, а уезжая за пределы.

**Comment by Dezaimasu** [comment]
:3 совсем другое дело

**Comment by Remu-rin** [comment]
А у меня, наоборот, проблемы с раскрытием по центру появились. Пропорции искажаются.
Не могу пока добиться 100% воспроизведения, в одних и тех же местах то происходит, то нет. Чаще на бордах с несколькими файлами в посте, но и на классических с одним тоже бывает. Может разница стилей что-то скажет.
С доски:
![dollchan-img3](https://user-images.githubusercontent.com/28995228/32492096-e7664ae4-c3da-11e7-91b7-cb2f50f6dc3e.png)
Внутри треда:
![dollchan-img4](https://user-images.githubusercontent.com/28995228/32492161-2db8e5ce-c3db-11e7-84bd-c6a3cee116ea.png)
Потом обновил доску и та пикча стала уже нормально отображаться.
