### ISSUE TITLE
Графический баг(?) в навигации постов.

### ISSUE THREAD

**Issue by lordnoobw** [SthephanShinkufag/Dollchan-Extension-Tools#1127]
Видеорилейтед: https://puu.sh/ydPRG.mp4
Пробовал с дефолтным userchrome.css
Пробовал с выключенными аддонами
Пробовал с выключенными скриптами кроме собственно куклы

Tampermonkey® 4.5.5570 Windows 10 Firefox Nightly 58.0a1 (2017-10-29) (64-bit)

**Comment by Y0ba** [comment]
Найтлипроблемы.
> Nightly 58.0a1 (2017-10-29)

Попробуй обновиться. [Баг](https://bugzilla.mozilla.org/show_bug.cgi?id=1412150) должен быть исправлен в ночнушке от первого числа.

**Comment by lordnoobw** [comment]
Спасибо, помогло.
