### ISSUE TITLE
Добавь возможность скрыть имя файла под раскрытой картинкой

### ISSUE THREAD

**Issue by anon1223231** [SthephanShinkufag/Dollchan-Extension-Tools#1129]
Недавно ты добавил имя файла под раскрытой картинкой. И его можно убрать только редакритуруя КСС. Можно сделать проще, кнопку там добавить не?

**Comment by anon1223231** [comment]
Кому интересно. Пишите в пользовательский КСС.
.de-img-full-src {display: none;} 

Сохраняете, всё.

**Comment by SthephanShinkufag** [comment]
1246dbf38882fd24f049dfd5026fcff13ba9dc76
