### ISSUE TITLE
Громкость webm NaN

### ISSUE THREAD

**Issue by anon1223231** [SthephanShinkufag/Dollchan-Extension-Tools#1130]
Открываю вебмку на 2ch.hk. В настройках указанная громкость (допустим, 20%) меняется на NaN. В итоге, больше вебмки открывать нельзя - плеер глючит.
Не очень шарю, что нужно предоставить и как повторить баг.
56 фаерфокс у меня.

**Comment by Dezaimasu** [comment]
Фуф, а я думал у меня уже крыша едет, то робить, то не робить, не мог понять кто виноват. В общем да, такая же картина, если поставить любое отличное от дефолтного 100 значение в громкость вебмок, то там оказывается NaN, и воспроизведение вебм начинает жутко глючить, как минимум если в посте разворачивать. На форчане так же.

Причём первая вебм вроде бы всегда открывается нормально, а вот вторая либо разворачивается но уже не сворачивается по клику, либо вместо разворачивания вообще открывается в новой вкладке, либо разворачивается но видео не проигрывается и застыло на первом кадре а звук на максимальной громкости играет отдельно и его никак не остановить кроме как перезагружать вкладку.

Проверено на новых профилях на последних версиях воднолиса, ночнушки и дев.версии лисы с ESNext скриптом.

**Comment by SthephanShinkufag** [comment]
Дико извиняюсь за косяки, ребята.
И спасибо, что помогаете их вылавливать.

**Comment by Rthre3** [comment]
Star!
