### ISSUE TITLE
2ch.hk: Хромог кушает мою память

### ISSUE THREAD

**Issue by CherryPerry** [SthephanShinkufag/Dollchan-Extension-Tools#1132]
Начал замечать иногда Опаньки... в своем хромом, когда тред долго открыт. Дошедший до бамплимита тред скушал около 2ГБ памяти под конец, что конечно же не очень.
Казалось бы, все можно спихнуть на хромого, но!

![default](https://user-images.githubusercontent.com/9081555/32460974-7e5c5dda-c345-11e7-9bfa-d7b9f7910f60.PNG)

Насколько я понимаю, вот эти штуки с шестеренкой это Workers, но я не разбираюсь в веб разработке. Я так глянул, у вас в коде они используются. И их в том треде было около 400 штук, при этом они имели разные названия (blob:https://2ch.hk/87f065bf-12b8-47ef-a04b-5980c238744e, blob:https://2ch.hk/63426191-f6c8-4f52-9cc6-ad001e861625 и т.д.). А контент у них внутри абсолютно одинаковый.

Сейчас открытый тред на 84 постов без удалений постов имеет уже 110 таких воркеров за час времени. Изображений в треде 34, код похож на подсчет хэшей изображений для скрытия постов. Одно правило ihash в спеллах есть.

Если не воспроизводится, могу помочь подебажить, если скажешь что смотреть и куда ставить брейкпоинты.

Хромой 62.0.3202.75
Кукла через тампер 4b68f0d

**Comment by SthephanShinkufag** [comment]
Скиньте одержимое `Настройки > Инфо > Отладка`.

**Comment by SthephanShinkufag** [comment]
И да, попробуйте удалить спеллы `#ihash`, и капчевать без них.
Поменяется ли поедание памяти.

**Comment by Y0ba** [comment]
По идее скрипт не должен создавать столько воркеров. Скорее всего `WorkerPool.p.clear` не очищает воркеров. Надо посмотреть почему.

**Comment by Y0ba** [comment]
В скрипте есть код
```js
clear() {
	window.URL.revokeObjectURL(this._url);
	this._freeWorkers = [];
}
```
Если его заменить на код ниже, то всё становится нормально?
```js
clear() {
	window.URL.revokeObjectURL(this._url);
	this._freeWorkers.forEach(w => w.terminate());
	this._freeWorkers = [];
}
```

**Comment by CherryPerry** [comment]
Обновил до версии e838d08 и добавил `w.terminate()`. Стало все ок, больше мертвые воркеры не плодятся.
