### ISSUE TITLE
Минимальная ширина для вебм при разворачивании в посте #Баг

### ISSUE THREAD

**Issue by Dezaimasu** [SthephanShinkufag/Dollchan-Extension-Tools#1133]
- [x] Не работает. Опция ничего не меняет, видео всегда разворачивается в оригинальную ширину. Рилейтед: https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/issues/1010

----------------

- [ ] Вдогонку ещё один баг с вебмками, разворачиваемыми в посте, чтобы не плодить тикеты. Касается только ночнушки 2017-10-26 и выше, если интереса ковырятся в этом нету, то и чёрт бы с ним, в 57 стабильной версии этого изменения ещё не будет.
Развёрнутые вебмки при клике на них не закрываются. И закрыть их соответственно вообще никак нельзя. Оказалось, что на видео элементах не срабатывает click событие. Причина как я понял - правка вот этого "бага": https://bugzilla.mozilla.org/show_bug.cgi?id=1402877
Чейнджлог, где они это изменение добавили в ночнушку, билд от 26 или 27 октября, чёрт их разберёт с их нумерацией: https://hg.mozilla.org/mozilla-central/pushloghtml?startdate=2017-10-25&enddate=2017-10-27

---------------

При разворачивании по центру ни одной, ни другой проблемы не наблюдается. Всё на последней версии куклоскрипта, ночнушки и вайлентманки.

**Comment by SthephanShinkufag** [comment]
> Минимальная ширина для вебм при разворачивании в посте
> Опция ничего не меняет, видео всегда разворачивается в оригинальную ширину.

Исправлено.

**Comment by SthephanShinkufag** [comment]
Подтверждаю проблемму в ночнушке - на элементахъ `<video>` не работаетъ событие `onclick`.
Вообще никак не отрабатываетъ.

**Comment by Dezaimasu** [comment]
Как временный вариант может сделать отдельную кнопку "закрыть"? Например как на форчанивском встроенном расширении, в конце div.fileText блока кликабельное "Close" при развёрнутых вебмках.

Потому что жуть, ночнушку обновлять вообще нельзя было, совершенно неюзабельно становится, развернул вебм и всё, только страницу перезагуржать. 

Накостылил вот себе:
https://github.com/Dezaimasu/Dollchan-Extension-Tools/commit/f534a5c742985b5040ddf1875a802c61019249ec

Хотел её перед video элементом добавить, чтобы мышью далеко не тянуться, но там где-то походу закрался firstElementChild от wrapEl или _fullEl, и первым элементом во wrapEl именно видео нужно. Один такой селектор там сразу парой строк ниже, его заменял, но судя по всему где-то ещё один, и оно где-то дальше крашится.

![screenshot-2018-1-10 v - jap games are popular now](https://user-images.githubusercontent.com/1636242/34786628-5dfe3646-f63d-11e7-9139-741d938dacf4.png)

**Comment by SthephanShinkufag** [comment]
Можно попробовать создать `<div>` и растянуть его над всем пространством видео, кроме контрольной панели. И пусть этот див ловит события.
Костыли-костылики.

**Comment by Dezaimasu** [comment]
Поверх всего видео неудобно, а как схоронять тогда? Контекстное меню будет у дивки вызываться же, только перехватывать и прокидывать событие вебмке, это уж точно костыли.

Можно совсем просто, добавить одну строчку в стили с псевдо-селектором ::before, там нарисовать кнопку, и поскольку она будет висеть поверх video-элемента, то по ней клик срабатывает нормально.

ea68fae11529d0793000d54694c7dda5e931a099

![image1](https://user-images.githubusercontent.com/1636242/34982302-b585c644-fab2-11e7-9372-7840e56f2675.jpg)

**Comment by SthephanShinkufag** [comment]
Слил ваши коммиты и сломал репозиторий.

![broken_repo](https://user-images.githubusercontent.com/1059874/34996916-b865ca4a-fae3-11e7-91c0-d3866aa8e4c7.png)

У вас какие-то конфликты, пока не могу разобраться. Приеду домой, там всё целое, сделаю `reset --hard` и `push --force`

**Comment by Dezaimasu** [comment]
Сорян. Я с гитхабом ещё только разбираюсь.

**Comment by SthephanShinkufag** [comment]
1. Кнопка появляется только в Лисе 57+
2. Кнопка появляется только для видео (webm/mp4/ogv)
3. Кнопка появляется еще и в раскрытии по центру, ведь событие не срабатывает независимо от типа раскрытия.

**Comment by Dezaimasu** [comment]
Спасибо, и извини за бардак.

**Comment by SthephanShinkufag** [comment]
Да всё норм, мне самому надо быть внимательным, прежде чем отправлять что-либо прямо в мастер.
