### ISSUE TITLE
Не работает в Firefox 57

### ISSUE THREAD

**Issue by vanya1996** [SthephanShinkufag/Dollchan-Extension-Tools#1134]
Зависает в бесконечной загрузке при попытке запостить в тред, Firefox 57, Greasemonkey 4

**Comment by SthephanShinkufag** [comment]
Номер коммита в студию.
Если он не последний, то скачайте последнюю версию https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/raw/master/src/Dollchan_Extension_Tools.es6.user.js.

**Comment by SthephanShinkufag** [comment]
В Greasemonkey нельзя устанавливать скрипты по ссылке.
Даже если я починю что-то, вы не сможете это применить.
Попробуйте пока другой скрипт-органайзер, или браузер.

https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/wiki/installation

**Comment by DeadNumbers** [comment]
А в найтли (59 на данный момент) работает установка по ссылке?

**Comment by Y0ba** [comment]
Нигде не работает. В найтли может и починят, но неизвестно когда: https://bugzilla.mozilla.org/show_bug.cgi?id=1267027#c28

**Comment by vanya1996** [comment]
> Попробуйте пока другой скрипт-органайзер, или браузер.
Попробую поставить Violentmonkey, или Tampermonkey, но Tampermonkey – проприетарный зонд, так что попробую Violent

**Comment by Hectus** [comment]
Ставите Denwer, закидываете в папку localhost скрипт https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/raw/master/src/Dollchan_Extension_Tools.es6.user.js , запускаете сервер, идете по ссылке http://localhost/Dollchan_Extension_Tools.es6.user.js , радуетесь
