### ISSUE TITLE
Неправильно экспортируется файл настроек в хроме

### ISSUE THREAD

**Issue by lkarmelo** [SthephanShinkufag/Dollchan-Extension-Tools#1135]
В самом конце добавляются лишние кавычки, получается "exclude":""""}
Скрипт v17.10.24.0.4b68f0d 
Хром 62.0.3202.94

**Comment by WagonOfDoubt** [comment]
Кажется #1138, #1107 и это является следствием одного и того же бага с Array.prototype.toJSON
