### ISSUE TITLE
(#op[] & #words()) не скрывает треды

### ISSUE THREAD

**Issue by Raucev** [SthephanShinkufag/Dollchan-Extension-Tools#1140]
Тестил на 2ch.hk и фоче. К примеру:
> (#op[vg] & #words(overwatch))

Firefox 57.0(64)
script ver 17.10.24.0

**Comment by SthephanShinkufag** [comment]
Всё работает.
Попробуйте удалить все спеллы, кроме `(#op[vg] & #words(overwatch))`.
Если это выражение отдельно работает, добавляйте остальные спеллы по одному, так выявите конфликт.

**Comment by Raucev** [comment]
Помогла чистка спеллов/переход на violentmonkey, спасибо .
