### ISSUE TITLE
Не работает обновление страницы/треда по f5

### ISSUE THREAD

**Issue by SomebodyStalin** [SthephanShinkufag/Dollchan-Extension-Tools#1142]
Firefox 56.0.2, кукла v17.10.24.0.b06bdb0
При попытке обновить страницу по f5 куклоскрипт падает. (Не) работает как минимум на Ычане, Краутчане и Форче, а значит, скорее всего, везде. Скриншот прилагаю.
![default](https://user-images.githubusercontent.com/34474974/33878868-b677913a-df3d-11e7-81aa-e41dd4fea2c0.png)

**Comment by SthephanShinkufag** [comment]
Обновите скрипт
https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/raw/master/src/Dollchan_Extension_Tools.es6.user.js

**Comment by SthephanShinkufag** [comment]
Проблема сохранилась?

**Comment by SomebodyStalin** [comment]
Все починилось, спасибо.

**Comment by SomebodyStalin** [comment]
О, еще и бесконечная прокрутка заработала.
