### ISSUE TITLE
Перешаманин дизигн на 2ch.hk

### ISSUE THREAD

**Issue by Smugl** [SthephanShinkufag/Dollchan-Extension-Tools#1143]
В одном из инновационийшех обновлений макака сломала двач так, что кукла теперь там не работает. Сделайте что-нибудь.

**Comment by Y0ba** [comment]
Последняя версия вроде работает: https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/raw/master/src/Dollchan_Extension_Tools.es6.user.js

Может какие-то определённые доски не работают?

**Comment by Rolfeg** [comment]
Он почти сразу прошатал назад, это было временно.
