### ISSUE TITLE
Потребление памяти

### ISSUE THREAD

**Issue by perdolka** [SthephanShinkufag/Dollchan-Extension-Tools#1144]
С недавних пор вкладки с тредами 2chhk стали почему-то "подтекать" - вплоть до **500**+мб на одну вкладку - **независимо** от количества постов и "тяжести" контента.
Проблема исчезла только когда выключил куклу.

ФФ - 55.0.3 (x64)
кукла - 17.10.24.0
скрипт-менеджер - Violentmonkey v2.8.22

Утечки памяти детектил аддоном Tab Memory Usage 2.0.7 (с about:memory не успевал поймать момент)

**Comment by Y0ba** [comment]
Настройки какие?
> кукла - 17.10.24.0

Без хэша коммита это ни о чём не говорит. Полная версия выглядит например так: v17.10.24.0.**e047d69**.es6

**Comment by perdolka** [comment]
3ff9979

**Comment by Rolfeg** [comment]
Кстати да. Без куклы на 500мб меньше. FF 56.0.2 (64-бит) Violenmonkey v17.10.24.0.76099bc.es6
Плюс иногда в ней что-то багает и кукла перестает запоминать просмотренные посты до перезапуска браузера.

**Comment by SthephanShinkufag** [comment]
Referenced to #1148

**Comment by SthephanShinkufag** [comment]
Firefox 57.0.3 (64-бит) + ViolentMonkey

10 активных тредов по 250-400постов.
Настройки брал у товарища из #1148, там огромное количество спеллов.

Без куклоскрипта 800-900Mb
С куклоскриптом 1300-1500Mb

В среднем таки да, на куклу 500Mb где-то выделяется, а то и больше.

**Comment by SthephanShinkufag** [comment]
С чистыми настройками 1100-1200Mb
То бишь, 300Mb выделяется на куклу с чистым конфигом.

**Comment by SthephanShinkufag** [comment]
Попробовал Tampermonkey - абсолютно те же цифры.
Та же картина и на других бордах, не только на 2ch.hk

**Comment by SthephanShinkufag** [comment]
Chrome + Tampermonkey - те же 300-500Mb на куклоскрипт с 10 тяжёлыми тредами.

**Comment by SthephanShinkufag** [comment]
> 300-500Mb на куклоскрипт с 10 тяжёлыми тредами

Это на все вкладки вместе. Я считаю, это вполне нормальные цифры.
Измерял потребление браузера в целом, 
О 500Мб на одну вкладку речи не идёт, подобного поведения не заметил.

**Comment by perdolka** [comment]
Прикрою, т.к. это дублирует #1148
