### ISSUE TITLE
только мои доски

### ISSUE THREAD

**Issue by perdolka** [SthephanShinkufag/Dollchan-Extension-Tools#1145]
Была когда-то хорошая фича в макако-опциях "**показывать только мои доски**" 
(т.е. только мои избранные звёздочкой, остальные скрыты)

Но она давно не работает.
Поэтому очень хотелось бы увидеть эту фичу в кукле.

**Comment by SthephanShinkufag** [comment]
Issue устарел, Абу запилил вам кнопку "Настроить".
>  [ b / vg / po / news ] [ Прочие доски / Настроить ]
