### ISSUE TITLE
Вечная отправка созданного треда

### ISSUE THREAD

**Issue by perdolka** [SthephanShinkufag/Dollchan-Extension-Tools#1147]
Псевдо-вечная отправка созданного треда.
Плашка об аплоаде бесконечно (на самом деле нет) отправляет тред, страница с тредом не появляется.
На самом деле, если перейти на нулевую доски - тред там **уже** будет.

ФФ - 55.0.3 (x64)
кукла - 17.10.24.0, 3ff9979
скрипт-менеджер - Violentmonkey v2.8.22

**Comment by SthephanShinkufag** [comment]
https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/raw/master/src/Dollchan_Extension_Tools.es6.user.js

Баг сохранился?

**Comment by perdolka** [comment]
> Баг сохранился?
Да, на e2b6bea 
<a href="http://piccy.info/view3/11913778/199810dc43abd143d71b5a2edec2ea22/" target="_blank"><img src="http://i.piccy.info/i9/f7ce8375e20b1f48655e105589601de6/1514367129/2663/1207467/48322f1b_3fb8_4748_936b_5c7cfd479fa3_1_.png" alt="Piccy.info - Free Image Hosting" border="0" /></a><a href="http://i.piccy.info/a3c/2017-12-27-09-32/i9-11913778/240x69-r" target="_blank"><img src="http://i.piccy.info/a3/2017-12-27-09-32/i9-11913778/240x69-r/i.gif" alt="" border="0" /></a>

**Comment by SthephanShinkufag** [comment]
Что в консоли ошибок `(Ctrl+Shift+J)`?
Нигде не постится, или только на ёбаном сосаче?
И покажите содержимое `Настройка > Инфо > Отладка`.

**Comment by SthephanShinkufag** [comment]
А, всё, отбой, добился бага.

**Comment by perdolka** [comment]
ок, кстати на 4chan попробовал - то же самое.
