### ISSUE TITLE
2ch.hk: Капча

### ISSUE THREAD

**Issue by CherryPerry** [SthephanShinkufag/Dollchan-Extension-Tools#1149]
Снова поменяли на гуглокапчу, и она отвалилась. Пока вроде бы только /b/, на других досках просто старая и не работает.

Думаю большого смысла фиксить быстро пока нет, а то снова начнет шатать. Если сутки продержится, то уже думаю можно править.

```
const version = '17.10.24.0';
const commit = '3ff9979';
```

**Comment by SthephanShinkufag** [comment]
https://www.youtube.com/watch?v=NkYU-a-1eOs

**Comment by Atabrabaneva** [comment]
Поменяли везде. Это из-за утреннего конфопетуха, засравшего всю главную. Обезьяна всё только ломает, блядь.

**Comment by SthephanShinkufag** [comment]
Завтра гляну, что там.

**Comment by SthephanShinkufag** [comment]
00:36
Вот и завтра наступило, лiл. Что-то не спится.
Вроде бы не так всё сложно оказалось.
Пробуйте, господа.
Ежели всё ок, то я апну циферки версии и выкачу всем апдейт.

**Comment by SthephanShinkufag** [comment]
На мейлаче аноны с некролисами < 53 версии пишут, что фикс не работает.
Надобно проверить.

**Comment by Y0ba** [comment]
У меня с 59 тоже не работает. Может опять абу что-то сделал? Я в разметке следов рекапчи вообще не вижу.

**Comment by SthephanShinkufag** [comment]
57.0.2 (64-бит)
Только что проверрил в /b, рекапча есть, кукла отрабатывает.

**Comment by SthephanShinkufag** [comment]
Ах, я же виолентманки пользуюсь.
 У тебя гризманки 4?

**Comment by Y0ba** [comment]
Да. Гризманки.

**Comment by SthephanShinkufag** [comment]
Возможно, там не так работает песочница. Посмотри в коммите, я работаю напрямую с глобальной переменной страницы.

**Comment by SthephanShinkufag** [comment]
grecaptcha

**Comment by Y0ba** [comment]
> Посмотри в коммите, я работаю напрямую с глобальной переменной страницы.

Так нельзя. Странно, что это в хроме работает.

**Comment by SthephanShinkufag** [comment]
Знаю, знаю, я вообще изначально сделал

```js
if(!$id('captcha-widget-main').hasChildNodes()) {
    $script(`_2chWidget = grecaptcha.render('captcha-widget-main', { sitekey: ${ data.id } });`);
} else {
    $script('grecaptcha.reset(cap._2chWidget);');
}
```

Но оно не работало почему-то.

**Comment by Y0ba** [comment]
Может надо чтобы синхронно было? Т.е. чтобы скрипт ожидал, пока эта строка отработает? А вообще жаль, что отовсюду поубирали `unsafeWindow`. Тут он был бы очень удобен.

**Comment by SthephanShinkufag** [comment]
Короче вся проблема в доступе к глобальной внешней переменной `grecaptcha`, зуб даю.

**Comment by Nattpyre** [comment]
Потестил через виолентманки в хроме 63.0.3239.84. Не работает. Причем без куклы капча есть.

**Comment by SthephanShinkufag** [comment]
Вот теперь должно быть alles gut.

**Comment by SthephanShinkufag** [comment]
Ребята, отпишитесь по последнему коммиту.

**Comment by Nattpyre** [comment]
Теперь работает, спасибо. Нужно текстовое поле в фокус взять, тогда гугл капча появляется.

**Comment by SthephanShinkufag** [comment]
> Нужно текстовое поле в фокус взять

Так и задумано же. Это специально сделано, на всех имиджбордах не зависимо от типа капчи.

**Comment by MrBudda108** [comment]
![default](https://user-images.githubusercontent.com/34883583/34377140-adb08272-eb00-11e7-9693-93739c80d175.png)
Firefox esr 52.5.2 v17.10.24.0.e2b6bea greasemonkey 3.17 вот такая ебола, в предыдущей версии всё норм было.

**Comment by SthephanShinkufag** [comment]
@MrBudda108 попробуйте ещё раз.
Фикс для лойсов/rage пришлось откатить.

**Comment by oti88279** [comment]
Почините для хрома, молю.

**Comment by MrBudda108** [comment]
Спасибо. Всё работает. Капча тоже.

**Comment by SthephanShinkufag** [comment]
@oti88279
Хроморасширение? Или что для хрома.
Скрипт отсюда ставили?
https://raw.github.com/SthephanShinkufag/Dollchan-Extension-Tools/master/Dollchan_Extension_Tools.user.js

**Comment by oti88279** [comment]
Да, именно оттуда ставил. Когда нажимаю ответить капча просто не отображается. 
https://puu.sh/yOGCe/5239b7635d.png

**Comment by Remu-rin** [comment]
> Ребята, отпишитесь по последнему коммиту.

FF 57.0.2, Violentmonkey 2.8.23, v17.10.24.0.131cec7.es6, работает. Спасибо.

@oti88279 
Поле комментария тыкни. Старая капча тоже только тогда появлялась же вроде.

**Comment by SthephanShinkufag** [comment]
@oti88279 
А в поле ввода текста вы не додумались тыкать?
Капча в основноё форме не появляется, пока не тыкнешь на поле ввода текста.
В быстром ответе она сразу появляется.

**Comment by oti88279** [comment]
@SthephanShinkufag Было бы все так легко, я бы сюда не писал. 
https://puu.sh/yOGSc/c1a3c14dc9.png

**Comment by UberMenko** [comment]
В копилку. 
На опере куклоскрипт тоже не отображает капчу. Изначально опера вообще не показывала гуглкапчу, но после чистки куки всё стало нормально, за исключением работы скрипта, разумеется.

**Comment by SthephanShinkufag** [comment]
Опера ничем не отличается от хрома.
Или у вас некроопера 12?

Скрипт отсюда ставили?
https://raw.github.com/SthephanShinkufag/Dollchan-Extension-Tools/master/Dollchan_Extension_Tools.user.js

**Comment by UberMenko** [comment]
Отсюда, да. Но просто так решил переустановить скрипт по ссылке, и он заработал, так что спасибо.

**Comment by CherryPerry** [comment]
У меня хром и тампер работает.

**Comment by nowes** [comment]
А обновление через магазин хрома фсе?

**Comment by streamach** [comment]
Так и не работает.

**Comment by SthephanShinkufag** [comment]
@streamach 

Браузер, способ установки скрипта.
Ставьте скрипт по ссылке https://raw.github.com/SthephanShinkufag/Dollchan-Extension-Tools/master/Dollchan_Extension_Tools.user.js

@nowes 
Хроморасширение завезу потом.

**Comment by enterobius** [comment]
Не работает на Waterfox'е 56.0.1 ни с Violentmonkey, ни с Greasemonkey.

**Comment by SthephanShinkufag** [comment]
@enterobius 
Ставите скрипт по ссылке выше?

**Comment by enterobius** [comment]
@SthephanShinkufag 
Рекапчи. Ставил по ссылке - всё равно не появляется.

**Comment by SthephanShinkufag** [comment]
@enterobius

А вы кликаете в поле ввода текста? В основной форме капча появляется только после клика в поле текста.

**Comment by Y0ba** [comment]
Ещё должна после выбора файла.

**Comment by enterobius** [comment]
@SthephanShinkufag 
Да, кликаю. После выбора файла тоже картина, как на пикрелейтед.
![untitled](https://user-images.githubusercontent.com/34897983/34395257-7570dfd0-eb67-11e7-99b3-680aec1cb54d.png)

**Comment by SthephanShinkufag** [comment]
@enterobius 
Специально скачал Waterfox, накатил Violentmonkey, зашёл в /b &mdash; рекапча есть.

**Comment by enterobius** [comment]
@SthephanShinkufag 
Да, прошу прощения, забыл потестить с выключенными аддонами. Privacy Badger блочил www.gstatic.com.
