### ISSUE TITLE
Не восстанавливает настройки из бекапа

### ISSUE THREAD

**Issue by funkyshity** [SthephanShinkufag/Dollchan-Extension-Tools#1152]
После обновления фиксящего капчу, я не могу загрузить настройки из файла, пишет некорректный формат данных.
![opera _2017-12-27_135420_2ch hk](https://user-images.githubusercontent.com/11163036/34379872-93274ef0-eb0e-11e7-9900-818215df030e.png)
v17.10.24.0.131cec7

**Comment by SthephanShinkufag** [comment]
1. Когда был создан файл с настройками?
2. Раньше этот файл применялся?

**Comment by SthephanShinkufag** [comment]
Ответьте на эти два вопроса.
Откройте в редакторе этот файл, и найдите

> "exclude":

и

> "hotkeys":

Какое содержимое после них в кавычках?

Что-то вроде `"exclude":""""`?

**Comment by funkyshity** [comment]
Пробовал бекапы от 17 декабря и 11 ноября.
Я сейчас сделал полный откат оперы на вчерашний день, чтобы вернуть все настройки куклы до обновления капчи. Сейчас у меня стоит версия v17.10.24.0.4b68f0d, я сделал на ней бекап настроек и попробовал загрузиться, но тоже не смог. Смог загрузиться только на ноябрьскую версию.
exclude":"""",
hotkeys":"",

**Comment by SthephanShinkufag** [comment]
Исправьте `exclude":""""` на `exclude":""`, бекап должен примениться. Этот баг должен был быть исправлен, просто вы создавали бекап, имея старый скрипт, он лепил четыре кавычки.
И да, попробуйте создать и применить новый бекап с новым куклоскриптом, сообщите о результате.

**Comment by funkyshity** [comment]
Полностью снес скрипт и установил новый v17.10.24.0.bcda236, и смог загрузиться с бекапа после правок, спасибо.

**Comment by SthephanShinkufag** [comment]
А если покликать каких-нибудь пару опций в настройках, создать новый бекап, он применится?

**Comment by funkyshity** [comment]
Изменил пару настроек и сделал сброс, после загрузился, все работает.

**Comment by SthephanShinkufag** [comment]
Спасибо, успокоили.
#1135 тогда можно закрывать.
