### ISSUE TITLE
Не поддерживается гуглокапча

### ISSUE THREAD

**Issue by proftwist** [SthephanShinkufag/Dollchan-Extension-Tools#1153]
Бесноватое обезьянище добавило на мейлач гуглокапчу. С текущей версией куклоскрипта она не отображается. Использовать же мейлач без автоскрытия тредов решительно невозможно. 

Поправьте, а?

**Comment by SthephanShinkufag** [comment]
#1149 duplicated issue

https://raw.github.com/SthephanShinkufag/Dollchan-Extension-Tools/master/Dollchan_Extension_Tools.user.js

**Comment by SthephanShinkufag** [comment]
Всё исправлено, ставьте скрипт по ссылке.

**Comment by proftwist** [comment]
А это точно скрипт для хрома? Хром пишет, что расширение повреждено.

**Comment by SthephanShinkufag** [comment]
Ой вей. А у вас хроморасширение стояло?

**Comment by SthephanShinkufag** [comment]
У вас как скрипт стоял, через тамперманки, или как расширение (extension)?

**Comment by proftwist** [comment]
Стоял как хроморасширение.

**Comment by proftwist** [comment]
Сейчас через тамперманки попробую.

**Comment by SthephanShinkufag** [comment]
Да, надо расширение обновить. не удаляйте ваше расширение, вечером апну. Спасибо за напоминание.

**Comment by proftwist** [comment]
О, теперь всё работает, спасибо. Правда, пролюбил список спеллов, но это дело наживное.

**Comment by SthephanShinkufag** [comment]
Надеюсь, вы не удалили расширение, а только отключили его. Иначе потеряете все ваши настройки.
