### ISSUE TITLE
Расширение для хромогов не обновлялось

### ISSUE THREAD

**Issue by fpcompany** [SthephanShinkufag/Dollchan-Extension-Tools#1154]
Удалил, попробовал поставить снова, хроуми выдал ошибку:

Недопустимый пакет. Подробные сведения: "Не удалось декодировать изображение: logo-128.svg". 

(использую теперь вмешивающуюся обезьяну)

**Comment by SthephanShinkufag** [comment]
Хм. А в черновой версии всё работало.
Переконвертировал все занчки в png, залил в гугломагазин, через часик должно прилететь.

**Comment by SthephanShinkufag** [comment]
Всё, обновление доступно. Гомен насай за неудобства.

**Comment by fpcompany** [comment]
Теперь работает, спасибо
