### ISSUE TITLE
dollchan works on every site except kc

### ISSUE THREAD

**Issue by uohuo** [SthephanShinkufag/Dollchan-Extension-Tools#1155]
I clicked on the thing that asked me if i give dollchan every information and now it stopped working but on kc only PLS FIX

**Comment by uohuo** [comment]
also please give option to frontpage redirect like on kc normally

**Comment by uohuo** [comment]
also some times when I click on Nr. it goes to 404 page and some times clicking on report button does the same

**Comment by SthephanShinkufag** [comment]
> thing that asked me if i give dollchan every information
> option to frontpage redirect like on kc normally
> when I click on Nr

Wut.

I did not get anything. Can you write more in detail, what is your problem? You can even explain with screenshots.

**Comment by SthephanShinkufag** [comment]
> I clicked on the thing that asked me if i give dollchan every information and now it stopped working but on kc only PLS FIX
> dollchan works on every site except kc

May be it's the same problem as #1138?

* Go to any other imageboard
* Click `Settings window` > `Reset...` button and clear all settings (check all checkboxes).
* Install the [latest build of the script](https://raw.github.com/SthephanShinkufag/Dollchan-Extension-Tools/master/Dollchan_Extension_Tools.user.js)
