### ISSUE TITLE
[4chan][uBlock]: Error: Failed to construct 'Worker': Access to the script at 'blob:...

### ISSUE THREAD

**Issue by DarKotE** [SthephanShinkufag/Dollchan-Extension-Tools#1156]
Как воспроизвести. 
Зайти в любой тред на 4chan'e. Дождаться появления нового поста (без разницы по нажатию кнопки или при автообновлении), одновременно с этим появится сообщение об ошибке.
Работает и в скрипте, и в аддоне. В ошибке будет что-нибудь вроде: 

> Error: Failed to construct 'Worker': Access to the script at 'blob:https://boards.4chan.org/d291bfd3-9624-4add-bde9-93afcc30f740' is denied by the document's Content Security Policy.
>     at new WorkerPool (eval at E_c (:3:92), :4842:28)
>     at Object.get _workers [as _workers] (eval at E_c (:3:92), :16254:16)
>     at Object.endFn (eval at E_c (:3:92), :16230:10)
>     at SpellsRunner._savePostsHelper (eval at E_c (:3:92), :11136:23)
>     at SpellsRunner.end (eval at E_c (:3:92), :11071:11)
>     at Maybe.end (eval at E_c (:3:92), :4641:17)
>     at Thread._parsePosts (eval at E_c (:3:92), :17894:17)
>     at Thread._loadNewFromBuilder (eval at E_c (:3:92), :17782:29)
>     at eval (eval at E_c (:3:92), :17481:32)
>     at eval (eval at E_c (:3:92), :4581:22)

**Comment by SthephanShinkufag** [comment]
Это ошибка спелла #ihash 
Он не работает.

**Comment by DarKotE** [comment]
Хм, да, спасибо, занесение форча в вайтлист ublock'a вроде бы решило проблему

**Comment by Redricks** [comment]
Лучше сиди с ошибками, чем с майнером, японский мут совсем поехал.

**Comment by SthephanShinkufag** [comment]
Удалите все спеллы #ihash, #video и #vauthor

**Comment by sotaj** [comment]
Похожая ошибка на 4чане с хрома, при автообновлении треда если появляются новые посты (без новых постов нормально). Без у-блока работает нормально. C выключенными (или удалёнными) спеллами + включённым ублоком также выдаёт ошибку.
`
(№Thread is unavailable200303604): 
Internal error:
Error: Failed to construct 'Worker': Access to the script at 'blob:https://boards.4chan.org/db8fca17-6a32-440d-82fd-863b3d303a70' is denied by the document's Content Security Policy.
    at new WorkerPool Dollchan_Extension_Tools.es6.user.js:2001:27)
    at Object.get _workers [as _workers] Dollchan_Extension_Tools.es6.user.js:12065:17)
    at Object.endFn Dollchan_Extension_Tools.es6.user.js:12042:9)
    at SpellsRunner._savePostsHelper Dollchan_Extension_Tools.es6.user.js:7821:21)
    at SpellsRunner.end Dollchan_Extension_Tools.es6.user.js:7763:9)
    at Maybe.end Dollchan_Extension_Tools.es6.user.js:1856:15)
    at Thread._parsePosts Dollchan_Extension_Tools.es6.user.js:13437:15)
    at Thread._loadNewFromBuilder Dollchan_Extension_Tools.es6.user.js:13327:35)
    at ajaxPostsLoad.then.pBuilder Dollchan_Extension_Tools.es6.user.js:13072:32)
    at Dollchan_Extension_Tools.es6.user.js:1824:18
`

**Comment by UserNaem** [comment]
У меня в консоли то же самое, только dE не ругается и всё работает. uBlock режет всю новую рекламу. Попробуйте починить uBlock, что ли.
Firefox 56.0b3, dE v17.10.24.0.d7d835f, uBlock Origin 1.13.8
![image](https://user-images.githubusercontent.com/21028464/34461866-4114e454-ee58-11e7-92e9-e6cd08d4ddd8.png)

**Comment by SthephanShinkufag** [comment]
Кстати, ниогда не пользовался блокировщиками. Есть ли с них реальый толк безопасности?? Или это фишка для параноиков с диагнозом? Пару раз ставил чисто проверить совместимость со скриптом, и тут же удолял эту дичь. Ежели завтра буду трезвый, то гляну чего там.

**Comment by UserNaem** [comment]
Теоретически, если появится новый эксплойт JavaScript и будет распространяться через рекламные сети, он его заблокирует. Фактически вероятность такого события близка к 0%. Блокировщики рекламы обычно используют для удобства, а не для безопасности.

**Comment by sotaj** [comment]
> Кстати, ниогда не пользовался блокировщиками. Есть ли с них реальый толк безопасности?? Или это фишка для параноиков с диагнозом? Пару раз ставил чисто проверить совместимость со скриптом, и тут же удолял эту дичь. Ежели завтра буду трезвый, то гляну чего там.

В ублоке  также можно за пару кликов скрыть что угодно: пустые места на страницах или заголовки в бордах. Особенно надоедали кликабельные борта страниц которые вывозили наверх страниц (например на хабре).

**Comment by Remu-rin** [comment]
> Блокировщики рекламы обычно используют для удобства, а не для безопасности.

Теперь и для приватности. 3rd-party exposure жуткий нынче на сайтах. Если ещё рефереры не спуфить/блочить, то вообще ужас.

**Comment by SthephanShinkufag** [comment]
Починилъ работу #ihash, ежели чего.

**Comment by SthephanShinkufag** [comment]
Не наблюдаю этот баг, пробовал все скриптменеджеры с uBlock.
