### ISSUE TITLE
2ch.hk: Опять капча

### ISSUE THREAD

**Issue by CherryPerry** [SthephanShinkufag/Dollchan-Extension-Tools#1158]
Теперь у нас новая капча с типом `invisible_recaptcha`. Без куклы ее изначально нет. При отправке поста она может появиться в отдельном окне, а может и не появиться.

**Comment by MrBudda108** [comment]
Почему этот хуесос просто не может перестать шатать. Хуею с Абу просто.

**Comment by SthephanShinkufag** [comment]
Ein моментъ, ща гляну.

**Comment by proftwist** [comment]
Бесноватая обезьяна опять поменяла механизм капчи. Ждём ссылку на обновлённый скрипт.

**Comment by SthephanShinkufag** [comment]
https://raw.github.com/SthephanShinkufag/Dollchan-Extension-Tools/master/Dollchan_Extension_Tools.user.js

**Comment by MrBudda108** [comment]
Спасибо. Работает. Только заёбывает, что ебучие знаки появляются после того, как сообщение отправил.

**Comment by SthephanShinkufag** [comment]
Так работает рекапча. Вы отправляете соощение - невидимая рекапча обновляется, и требует знаки.

**Comment by SthephanShinkufag** [comment]
Если хотите, я могу сдалеть рекапчу видимой, и всё будет как по старому. Только вам придётся как обычно тыкать на галочку перед отправкой.

**Comment by MrBudda108** [comment]
Мне привычнее тыкать. За остальных говорить не буду.

**Comment by CherryPerry** [comment]
Показывать ее сразу такое себе, ведь есть некоторый лимит сообщений, которых можно отправить вообще без капчи.

**Comment by MrBudda108** [comment]
У меня такого лимита нет - капча вылазит сразу и требует выполнить несколько заданий - хотя в гугле я залогинен.

**Comment by CherryPerry** [comment]
Это может зависеть от айпишника, скорости постинга и т.д.

А еще бывает странное поведение при постинге. Я прокликиваю форму перед отправкой, чтобы капча прогрузилась, а мне сервер возвращает, что "Капча невалидна". Но когда я пытаюсь отправить тот же пост снова сразу же, то он уже отправляется.
Еще один раз капча показалась, я ее не прокликивал, а мисскликнул вне ее окна, и она закрылась. После этого я отправил другой пост, но тоже через двойную отправку, сначала словив "Капча невалидна", потом уже успешно.

**Comment by proftwist** [comment]
Опять постинг с куклой не работет. Пишет, что капча невалидна.

**Comment by SthephanShinkufag** [comment]
@proftwist, такое бывает, даже без куклы. Просто повторно нажмите "отправить".

**Comment by proftwist** [comment]
Неа. Попробовал нажать десять раз. Каждый раз пишет, что капча невалидна. Отключил куклу — запостилось с первого раза. 

Похоже, Абу опять что-то нашатал и снова нужно править скрипт.

**Comment by SthephanShinkufag** [comment]
На /b в `swag.js` ничего не поменялось со вчерашнего дня. либо я не замечаю изменения. Всё постится.

**Comment by CherryPerry** [comment]
У меня в /a тоже все работает.

**Comment by proftwist** [comment]
Да, вроде постинг заработал. Видимо, какие-то временные глюки.

**Comment by SthephanShinkufag** [comment]
Скорее всего программер Наримана тестировал что-нибудь, а потом откатил назад.

**Comment by streamach** [comment]
Таки при включенной кукле появляется гугл капча, которая галочку ставить, но даже так пишет ошибка постинга и не отправляет пост вообще. Плюс дублируются посты, раньше такое бывало, потом починили как-то. Такая фигня на двух браузерах на разных ос.  Без куклы все постится и не двоится.

**Comment by SthephanShinkufag** [comment]
@streamach
Ставьте скрипт по ссылке
https://raw.github.com/SthephanShinkufag/Dollchan-Extension-Tools/master/Dollchan_Extension_Tools.user.js

**Comment by streamach** [comment]
@SthephanShinkufag 
Хром пишет "Это расширение могло быть повреждено"

**Comment by SthephanShinkufag** [comment]
А, так вы используете расширение. Так бы и написали. Я его пока не обновлял.

**Comment by streamach** [comment]
@SthephanShinkufag печально. А когда в планах?

**Comment by SthephanShinkufag** [comment]
А чтобы посты не дублировались, отключите в макабе встроенный апдейтер тредов.

**Comment by streamach** [comment]
Поставил через tapermonkey, вроде работает. А вставку изображений по ctrl+v так и не прикрутили?

**Comment by SthephanShinkufag** [comment]
Апнул версию, обновил хроморасширение. Через часик прилетит в гугломагазин.
