### ISSUE TITLE
iichan.hk Нововведения.

### ISSUE THREAD

**Issue by MrBudda108** [SthephanShinkufag/Dollchan-Extension-Tools#1162]
"В некоторых разделах доступна загрузка видео-файлов (MP4, OGV, WEBM). Также в движок добавлены функции закрепления и закрытия тредов. "
Видео в формате OVG не открываются на странице.

**Comment by SthephanShinkufag** [comment]
Я там уже более полугода как забанен.
Может, Йоба починит.

**Comment by Reisenfag** [comment]
Родной разворот работает лучше чем скриптовый (ну, или скорее всего они конфликтуют):
http://storage7.static.itmages.com/i/18/0106/h_1515272638_4435061_67573102cc.png
http://storage8.static.itmages.com/i/18/0106/h_1515272667_6179289_ca63520b70.png

**Comment by SthephanShinkufag** [comment]
Ой вей, оказывается, разбанен. Давно из дому не заходил просто, сегодня домой приехал.

@Reisenfag 

А в чём ещё разница, кроме того, что вебмка выходит за пределы поста?

**Comment by Reisenfag** [comment]
@SthephanShinkufag ни в чём, но я так понял кукла всегда пытается растянуть на максимум, если возможно, а скрипт ычана оптимизирует по размеру экрана и подбирает размер поста под своё значение.

**Comment by SthephanShinkufag** [comment]
@MrBudda108
> добавлены функции закрепления и закрытия тредов

Покажите, где эти кнопки. Не могу найти.

> Видео в формате OVG не открываются на странице

Дайте ссылку на пост с ogv-файлом.

**Comment by Remu-rin** [comment]
> Дайте ссылку на пост с ogv-файлом.

https://iichan.hk/b/res/4639007.html#4639022

**Comment by SthephanShinkufag** [comment]
Починено.
Также, починил перетягивание mp4 и ogv на странице мышью в область файла, а также их предзагрузку в blob.

**Comment by SthephanShinkufag** [comment]
Алсо,

> добавлены функции закрепления и закрытия тредов
> Покажите, где эти кнопки. Не могу найти

Или их таки не запилили, и issue можно закрывать?

**Comment by Reisenfag** [comment]
@SthephanShinkufag это модераторские функции. С прикреплёнными тредами проблем нет. А вот с закрытыми — они внешне никак не отличаются от обычных, а при постинге возникает одинаковая ошибка с удалённым «Тред не существует или закрыт». Если он не 404, то очевидно, что закрыт.

**Comment by Y0ba** [comment]
Пример закрытого треда можно?

**Comment by Reisenfag** [comment]
@Y0ba для примера сделал https://iichan.hk/to/res/160876.html

**Comment by SthephanShinkufag** [comment]
Он и без куклы ничем не отличается от обычного.

**Comment by Reisenfag** [comment]
Ну, я это вроде и имел ввиду. Тут вроде как не ошибка, а скорее особенность работы.

**Comment by SthephanShinkufag** [comment]
@Reisenfag

> Родной разворот работает лучше чем скриптовый (ну, или скорее всего они конфликтуют):
http://storage7.static.itmages.com/i/18/0106/h_1515272638_4435061_67573102cc.png
http://storage8.static.itmages.com/i/18/0106/h_1515272667_6179289_ca63520b70.png

Вроде бы, починил. Теперь вебмки и картинки не вылазят за пределы постов.
