### ISSUE TITLE
Firefox Add-on is available!

### ISSUE THREAD

**Issue by SthephanShinkufag** [SthephanShinkufag/Dollchan-Extension-Tools#1163]
Хочу залить расширение на addons.mozilla.org.
Скрипт проходит валидацию, но получает 57 warning'ов:

![addons_mozilla_validation](https://user-images.githubusercontent.com/1059874/34651803-f96a3538-f3dd-11e7-9497-1cf26febe2d5.png)

56 из них `Unsafe call to insertAdjacentHTML`
и одно `The Function constructor is eval`

Поробнее:

![addons_mozilla_validation2](https://user-images.githubusercontent.com/1059874/34651807-154e6c38-f3de-11e7-9f8c-2ff91ce5e24c.png)

Дальнейшим шагом стаёт отправка расширения на рассмотрение модераторами из Mozilla.
И я боюсь, они наш аддон завернут из-за этих предупреждений.
Никак не решаюсь. Или я зря мандражирую?

Ну и вопрос вдогонку:
Отмечать галочкой Android или нет? Какого рода должно быть расширение, чтобы поддерживалось на этой платформе? Наш аддон только для браузеров, вроде бы. Андроидный Firefox поддерживает расширения?

**Comment by SthephanShinkufag** [comment]
То бишь, insertAdjacentHTML по их стандартам может применяться только со статическими строками, а не с переменными. =\

**Comment by RosinSmoke** [comment]
Конечно поддерживает. 
https://addons.mozilla.org/ru/android/
uBlock Origin как хороший пример, даже такая монструозная хренота на свежем апи нормально на мобилки взгромоздилась.

**Comment by SthephanShinkufag** [comment]
Я щас покурю вот эту хрень

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Developing_WebExtensions_for_Firefox_for_Android

Добьюсь вменяемой работы в Android Firefox. А потом отправлю расширение на рассмотрение мозилловцами как есть, с этими варнингами. Укажу в примечании ссылки на гитхаб, на страницу **хроморасширения**, мол не хуй с горы. Авось и проканает.

**Comment by alersrt** [comment]
@SthephanShinkufag 

Не пропустили расширение?

**Comment by XakepSDK** [comment]
bump

**Comment by SthephanShinkufag** [comment]
Теперь нужно адаптировать расширение под Android Firefox

**Comment by SthephanShinkufag** [comment]
Никакой не отсутствует. Это костыль для старых Greasemonkey, он не нужен, и ломал работу аддона.

**Comment by Bfgeshka** [comment]
Это вебэкстеншны, а для xul уже не будет?

**Comment by SthephanShinkufag** [comment]
Я чэлавэк недалёкий, поясните, что значит
> для xul уже не будет

И что вы вообще хотели спросить или имели в виду.

**Comment by Klaster1** [comment]
@SthephanShinkufag скорее всего имелась в виду предыдущая модель расширений, это может быть актуально для старых версий FF и форков (Palemoon?).

**Comment by Y0ba** [comment]
Вроде palemoon может работать с webextension'ами, нет? Только ограничение на API будет.

Впрочем куклу в виде юзерскрипта пока никто убирать не собирается.

**Comment by XakepSDK** [comment]
Браузер под android поддерживает расширения. Можно ublock поставить, к примеру.
Насчёт xul - кому-то пора обновиться.

**Comment by Bfgeshka** [comment]
> Вроде palemoon может работать с webextension'ами, нет? Только ограничение на API будет.

Не, ограниченно это на джетпаке. Вебэкстеншн вообще швах.

> Впрочем куклу в виде юзерскрипта пока никто убирать не собирается.

Да это понятно. Я не требую - так, спросил.

**Comment by SthephanShinkufag** [comment]
Ну уж нет, у меня ни сил, ни времени не хватит разрабатывать аддон старой модели. Ради кого? Ради полутора некроюзеров? Тут и у текущего даже 15 пользоваетей нет пока, и вряд ли будет много, аудитория Firefox специфична, что уж тут говорить.
Мало тго, при попытке уменьшить требуемую версию до Firefox 52 (минимальная, которая поддерживает асинхронные функции и async/await), я получаю следующие warnings:

manifest.json
Permission not supported by the specified minimum Firefox version
Предупреждение: "strict_min_version" requires Firefox 52.0, which was released before version 56 introduced support for "permissions:unlimitedStorage".

manifest.json
Manifest key not supported by the specified minimum Firefox version
Предупреждение: "strict_min_version" requires Firefox 52.0, which was released before version 55 introduced support for "optional_permissions".

menu/menu.js строка 10 столбец 4
storage.sync is not supported in Firefox version 52.0
Предупреждение: This API is not implemented by the given minimum Firefox version

settings/settings.js строка 13 столбец 4
storage.sync is not supported in Firefox version 52.0
Предупреждение: This API is not implemented by the given minimum Firefox version

settings/settings.js строка 22 столбец 2
storage.sync is not supported in Firefox version 52.0
Предупреждение: This API is not implemented by the given minimum Firefox version

settings/settings.js строка 26 столбец 4
storage.sync is not supported in Firefox version 52.0
Предупреждение: This API is not implemented by the given minimum Firefox version

background.js строка 13 столбец 4
storage.sync is not supported in Firefox version 52.0
Предупреждение: This API is not implemented by the given minimum Firefox version

background.js строка 22 столбец 2
storage.sync is not supported in Firefox version 52.0
Предупреждение: This API is not implemented by the given minimum Firefox version

background.js строка 26 столбец 4
storage.sync is not supported in Firefox version 52.0
Предупреждение: This API is not implemented by the given minimum Firefox version

<hr>
Помимо этого, попытка зарелизить аддон для Firefox for Android выдаёт предупреждения:

manifest.json
Permission not supported by the specified minimum Firefox for Android version
Предупреждение: "strict_min_version" requires Firefox for Android 52.0, which was released before version 54 introduced support for "permissions:tabs".

manifest.json
Permission not supported by the specified minimum Firefox for Android version
Предупреждение: "strict_min_version" requires Firefox for Android 52.0, which was released before version 56 introduced support for "permissions:unlimitedStorage".

manifest.json
Manifest key not supported by the specified minimum Firefox for Android version
Предупреждение: "strict_min_version" requires Firefox for Android 52.0, which was released before version 55 introduced support for "browser_action".

manifest.json
Manifest key not supported by the specified minimum Firefox for Android version
Предупреждение: "strict_min_version" requires Firefox for Android 52.0, which was released before version 57 introduced support for "browser_action.default_popup".

manifest.json
Manifest key not supported by the specified minimum Firefox for Android version
Предупреждение: "strict_min_version" requires Firefox for Android 52.0, which was released before version 55 introduced support for "browser_action.default_title".

manifest.json
Manifest key not supported by the specified minimum Firefox for Android version
Предупреждение: "strict_min_version" requires Firefox for Android 52.0, which was released before version 55 introduced support for "optional_permissions".

menu/menu.js строка 31 столбец 3
tabs.create is not supported in Firefox for Android version 52.0
Предупреждение: This API is not implemented by the given minimum Firefox for Android version

background.js строка 62 столбец 4
tabs.executeScript is not supported in Firefox for Android version 52.0
Предупреждение: This API is not implemented by the given minimum Firefox for Android version

background.js строка 103 столбец 4
tabs.query is not supported in Firefox for Android version 52.0
Предупреждение: This API is not implemented by the given minimum Firefox for Android version


**То есть, Firefox for Android требует 57 версию, Firefox for Desctop 56 версию.**

**Comment by SthephanShinkufag** [comment]
@XakepSDK 

> Браузер под android поддерживает расширения

Нужно найти время, чтобы протестировать аддон на мобильном устройстве. Как протестирую и исправлю возможные проблемы, так и поставлю галочку своместимости, тогда аддон будет доступен для мобильной лисы.

**Comment by SthephanShinkufag** [comment]
По поводу доступа к истории посещения в браузере, в следующем релизе выпилю.

https://dscript.me/de/1.html#596

**Comment by SthephanShinkufag** [comment]
В общем, посоны:

https://dscript.me/de/res/1.html#598

`"history"` permission на запись в историю я таки потом выпилю, но без `"webNavigation"` permission (чтение истории) никуда теперь.
Такие дела.

**Comment by XakepSDK** [comment]
Как часто обновляться будет?

**Comment by SthephanShinkufag** [comment]
Если буду что-то пилить, то раз в неделю-полторы, вместе с повышением версии.
Посмотрите даты [обновлений версий скрипта](https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/wiki/versions) за декабрь, где-то вот так.
Если хотите обновляться с каждого коммита, используйте юзерскрипт. У аддона преимуществ нет, кроме синхронизируемых настроек на всех ПК с аккаунтом Firefox, а также отсутствия необходимости в менеджере скриптов. Но то ли ещё будет :)

**Comment by RosinSmoke** [comment]
> синхронизируемых настроек/избранного на всех ПК с аккаунтом Firefox
Вот с этого и надо было начинать, джва года ждал. Хотя ежекоммитных обновлений и правда будет не хватать, да и выбора стабильной версии, мозилломагазин оставил хотя бы историю версий, или и это отломали?
