### ISSUE TITLE
Скрытая капча — опять не работает постинг

### ISSUE THREAD

**Issue by proftwist** [SthephanShinkufag/Dollchan-Extension-Tools#1164]
Не иначе, как опять что-то поменяли. Отправляю пост — пишет, что капча невалидна. Повторяю десяток раз — результат тот же. Пробую в другой тред — результат тот же. 

Можете посмотреть?

**Comment by SthephanShinkufag** [comment]
Всё постится.

**Comment by proftwist** [comment]
Вот видяшка. https://youtu.be/CaZ-vK1x2D8

**Comment by perdolka** [comment]
На видео видно оранжевую полосу загрузки, которая не дошла до конца.
По идее, капча появилась бы, если дождаться полной загрузки - у меня так.

**Comment by proftwist** [comment]
Вроде заработало, спасибо.
