### ISSUE TITLE
Расширение работает только в топ фрейме

### ISSUE THREAD

**Issue by hurrdurrderrp** [SthephanShinkufag/Dollchan-Extension-Tools#1165]
Но автоматически включается при открытии треда в новой вкладке.
Кукла последняя, переустановка не помогла.

**Comment by SthephanShinkufag** [comment]
Браузер? Тип установки скрипта (хроморасширение/Tampermonkey/Violentmonkey)? Содержимое консоли (Ctrl+Shift+J) на странице с ошибкой?

**Comment by hurrdurrderrp** [comment]
Хром, версия 63.0.3239.132 , хроморасширение.
В консоли только This page includes a password or credit card input in a non-secure context. A warning has been added to the URL bar.

**Comment by SthephanShinkufag** [comment]
Окно `"Настройки"` - вкладка `"Инфо"` - кнопка `Отладка`.
Запостите содержимое.

**Comment by hurrdurrderrp** [comment]
{
	"version": "18.1.4.0.1dabb01",
	"location": "http://iichan.hk/b/res/4629611.html",
	"nav": {
		"ua": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36",
		"isFirefox": false,
		"isWebkit": true,
		"isChrome": true,
		"isSafari": false,
		"isGM": false,
		"isNewGM": false,
		"isChromeStorage": true,
		"isScriptStorage": false,
		"Presto": false,
		"MsEdge": false,
		"isGlobal": true,
		"hasGMXHR": false,
		"isESNext": true,
		"scriptInstall": "WebExtension",
		"hasTemplate": true,
		"hasWorker": true,
		"canPlayMP3": true
	},
	"Cfg": {
		"timePattern": "w+dd+m+yyyy+hh+ii+ss",
		"updScript": 0,
		"hideBySpell": 0,
		"cfgTab": "info",
		"addMP3": 0,
		"addVocaroo": 0,
		"addYouTube": 0,
		"scrAfterRep": 1,
		"favOnReply": 0,
		"expandImgs": 1,
		"markNewPosts": 0,
		"addPostForm": 1,
		"turnOff": 1
	},
	"sSpells": [
		"#wipe(samelines,samewords,longwords,symbols,numbers,whitespace)"
	],
	"perf": [
		[
			"Imageboard check",
			5
		],
		[
			"Data loading",
			74
		],
		[
			"Init",
			7
		],
		[
			"Read my posts",
			0
		],
		[
			"Replace delform",
			1
		],
		[
			"Parse delform",
			60
		],
		[
			"Parse postform",
			183
		],
		[
			"Init keybinds",
			1
		],
		[
			"Init page",
			4
		],
		[
			"Add panel",
			4
		],
		[
			"Init AJAX",
			1
		],
		[
			"Preload images",
			0
		],
		[
			"Audio links",
			0
		],
		[
			"Image names",
			17
		],
		[
			"Reflinks map",
			17
		],
		[
			"Apply CSS",
			6
		],
		[
			"Display page",
			0
		],
		[
			"Infinity scroll",
			0
		],
		[
			"Hide posts",
			2
		],
		[
			"Scroll page",
			0
		],
		[
			"Всего",
			382
		]
	]
}

**Comment by SthephanShinkufag** [comment]
У меня с вашими настройками хроморасширение работает.

1. Попробуйте отключить все расширения (кроме Dollchan, конечно).
2. Мод-тян в последнее время шатает вакабу. Если вы модератор, у вас скорее всего появились какие-нибудь дополнительные кнопки интерфейса, вроде "закрыть тред", "влепить нанобан", они могут конфликтовать с Dollchan. Выйдите из аккаунта модератора.

**Comment by SthephanShinkufag** [comment]
Кажется, я таки добился вашего бага.
Вы используете боковой фрейм со списком досок?

**Comment by hurrdurrderrp** [comment]
Да, и с ним и перестала кукла работать. Раньше всё нарм было.

**Comment by SthephanShinkufag** [comment]
Исправил, отправил в гугломагазин. Через часик заапрувится и прилетит обнова.

**Comment by hurrdurrderrp** [comment]
Оки, спасибки.
