### ISSUE TITLE
[Lolifox] Не работают спойлеры и предзагрузка

### ISSUE THREAD

**Issue by XakepSDK** [SthephanShinkufag/Dollchan-Extension-Tools#1166]
На lolifox не работает предзагрузка изображений/webm.
Спойлеры всегда скрытые.(там какой-то скрипт на блюр стоит, нужен фикс)
Встроенный куклоскрипт отключен через ublock.
А еще там есть 2 кнопки справа, по середине. Когда листаешь через кнопки от скрипта, можно промахнуться и нажать на одну из этих кнопок, неприятно.(вырезал через ublock, но может есть решение из коробки?)
Настройки:
https://puu.sh/yXqaj/980b389c62.png

**Comment by SthephanShinkufag** [comment]
> На lolifox не работает предзагрузка изображений/webm.

Скорее всего это из-за того же uBlock. 
Со стандартными настройками и `https://lolifox.org/js/dollchan.js` в "моих фильтрах" предзагрузка работает, только что проверил. Копайте настройки блокировщика.

**Comment by XakepSDK** [comment]
В фильтрах с лолифоксом связанно только вот это:
```
||lolifox.org/js/dollchan.js$script,first-party
lolifox.org##div#thread-interactions
```

Со стандартным dollchan предзагрузка тоже не работает.(выключил ublock для проверки, предзагрузку включил)
p.s. не знаю, как правильно протестить. С выключенным adblock и включенной предзагрузкой на стандартном скрипте полоска загрузки почти моментально доходит до конца, с адблоком и нестандартным скриптом, полоска не доходит до конца, но я могу перематывать без задержек.
На дваче предзагрузка работает.
Больше информации:
1. Firefox 57.0.4
2. Grasemonkey
3. `version = '17.12.28.0';`
4. `commit = '369052b';`

Еще на форчане картинки не отображаются при клике на них, может это как-то связанно?
Только что хотел проверить на 4chan без adblock, но не смог, bad gateway.

**Comment by SthephanShinkufag** [comment]
uBlock и кукла очень не дружат.
Могут не работать спеллы, раскрытие картинок,  предзагрузка, загрузка титлов к ютуб-ссылкам, небо, аллах.
Я даже не пытаюсь что-то предпринимать, тому що это сизифов труд. Да и не хочу, честно, лень.
Наверное, я просто пропишу в wiki, что нормальная работа с блокировщиками не гарантирована, да и всё.

**Comment by XakepSDK** [comment]
Можете показать свой список включенных фильтров?
Хочу отсеять потенциально рабочие фильтры.

**Comment by SthephanShinkufag** [comment]
Исправил спойлеры.

@XakepSDK

Начисто установленный `uBlock`, и одна строчка

![9397998](https://user-images.githubusercontent.com/1059874/34709729-19489784-f521-11e7-9f57-3319884275ab.png)

Всё. Предзагрузка работает.

**Comment by SthephanShinkufag** [comment]
Никакие параметры в uBlock не менял, всё из коробки.

**Comment by XakepSDK** [comment]
Так и не нашел списка включенных фильтров по-умолчанию.
+ они вроде разнятся между локалями, у меня например RUAdList не был включен по-умолчанию.

**Comment by SthephanShinkufag** [comment]
Убрал лишние кнопки.

@XakepSDK

![93979986](https://user-images.githubusercontent.com/1059874/34710243-2b20cb5a-f523-11e7-9e9c-30d1fdfd2e97.png)

**Comment by XakepSDK** [comment]
Вот прикол. У меня точно такой же список фильтров.(Только adguard'овский список не включен)
А предзагрузка всё равно не работает.
Может мне какой-нибудь кеш надо сбросить? LocalStorage там, не знаю.

**Comment by SthephanShinkufag** [comment]
А если *выключить предзагрузку*, перезагрузить страницу, открыть консоль браузера `Ctrl+Shift+J`, очистить консоль, и нажать на панели скрипта "Предзагрузить картинки" (иконка со стрелочкой вниз в рамке), что-то появляется в консоли?

**Comment by SthephanShinkufag** [comment]
И вообще предзагрузка по этой кнопке работает?

**Comment by SthephanShinkufag** [comment]
И да, обновите скрипт до последнего коммита.

https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/raw/master/src/Dollchan_Extension_Tools.es6.user.js

**Comment by XakepSDK** [comment]
Выключил предзагрузку, обновил страницу(ctrl+f5), вот в консоли вот это:
https://puu.sh/yXrYv/08cdd7e918.png
И оно сработало!
Сейчас обновлю.

**Comment by SthephanShinkufag** [comment]
> on-user-script-xhr.js

Это что у вас за хрень. На странице таких скриптов нет.

**Comment by SthephanShinkufag** [comment]
Ещё посмотрите другие расширения и дополнения к вашему браузеру. Отключите все аддоны, может какой-то из них конфликтует.

**Comment by XakepSDK** [comment]
Это greasemonkey скорее всего.
https://puu.sh/yXs8a/73ffe18c1f.png

Обновил скрипт.

Смотрю активность сети - по нажатию на кнопку ничего не происходит. Ни с включенным ublock, ни с выключенным.

Сейчас попробую в другом браузере(safemode в ff57 сломали, проверял экспериментально)

Потом попробую поменять greasemonkey. Что посоветуете на замену?

**Comment by SthephanShinkufag** [comment]
Я пользуюсь [Violentmonkey](https://addons.mozilla.org/en-US/firefox/addon/violentmonkey/). Многие говорят, что Tampermonkey это анальный зонд.

**Comment by XakepSDK** [comment]
Поменял на violentmonkey. Предзагрузка всё равно не работает.
Мониторинг сети показывает то, что нагрузки вообще нет.

Только что зашел на мейлач в webm-thread и нажал на кнопку предзагрузки - загрузка сети 80%, причем уже минуту так держится.
(+ violentmonkey на firefox лагучий какой-то, умудрился подвесить соседнюю вкладку, лучше останусь на greasemonkey)
Провел тот же тест с greasemonkey:
Мейлач:
https://puu.sh/yXsu8/a28306b4f1.png
Лолифокс:
https://puu.sh/yXsvo/a822e3b20d.png

С violentmonkey всё так же, но ко всему этому добавляются фризы самого браузера.

Сейчас попробую на чистом браузере со скриптом с лолифокса.

**Comment by SthephanShinkufag** [comment]
Значит, вам просто не везёт.
Я представления даже не имею, что у вас там может быть. У меня предзагрузка работает.
Мне [один буржуй](https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/issues/1138) тоже месяц полоскал мозги и нервы, выяснилось, что у него какой-то ебучий аддон блокирует клик.

**Comment by XakepSDK** [comment]
Я тестировал на чистых браузерах с чистыми профилями. Нагрузки на сеть нет на лолифоксе, после нажатия на кнопку предзагрузки.

**Comment by SthephanShinkufag** [comment]
Кстати, да. Для чистоты эксперимента.
Скачатйе портабельную лису

https://portableapps.com/apps/internet/firefox_portable

накатите uBlock, Violentmonkey, и ничего более.

**Comment by SthephanShinkufag** [comment]
Ну тогда я не знаю. Судьба  такая значит.

**Comment by SthephanShinkufag** [comment]
Надеюсь, вы тестили с чистыми настройками куклоскрипта, ничего не экспортируя?

**Comment by XakepSDK** [comment]
Всё чистое, никаких импортов. Я выше расписал порядок тестирования и условия тестирования.

**Comment by SthephanShinkufag** [comment]
Кстати, я только что в коммите 86c16545f7d223d740149a3868016e3963e79247 исправил поиск контейнеров картинок на более корректный.
Попробуйте поставить ещё раз последний билд скрипта.

https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/raw/master/src/Dollchan_Extension_Tools.es6.user.js

**Comment by XakepSDK** [comment]
Не работает. Может версию с дебагом дадите? У меня есть еще где-то 35-40 свободных минут.

**Comment by SthephanShinkufag** [comment]
Ну вы блин нашли где тестить - на страницу с вебмками, где 2 гига данных.
Зайдите на страницу попроще.
Вот:
https://lolifox.org/b/res/32895.html
Тут работает?

**Comment by XakepSDK** [comment]
Нет, не работает.
Но я вот что заметил:
После первого нажатия на кнопку предзагрузки, нагрузка на сеть возрастает на 0.5-1 секунду, после этого на нажатия не реагирует.

**Comment by SthephanShinkufag** [comment]
Как вы определяете, что не работает?
Включите предзагрузку в этом маленьком треде (через галочку в настройках + обновление страницы, или однократно по кнопке на панели).
Наведите курсор на картинку - какую ссылку показывает? https: или blob:?

**Comment by SthephanShinkufag** [comment]
Монитор активности сети может не реагировать на сетевую активность гризманки-аддонов!

**Comment by XakepSDK** [comment]
Я через систему смотрю.
Теперь работает подгрузка картинок, webm не грузит.

**Comment by SthephanShinkufag** [comment]
Пиздец. Ну вот, теперь оказывается, что вы полоскали мне мозг.
Вебм не грузит, потому что они весят дохера.
Нашли где теститть, в анимублядском треде.
Подождите минут  15 - и загрузит.
У меня бомбит.

**Comment by XakepSDK** [comment]
Он блядь не грузит их. Мне тебе дапм пакетов скинуть или что?

**Comment by SthephanShinkufag** [comment]
Картинки грузит?

**Comment by SthephanShinkufag** [comment]
Зайдите в любой тред с одними картинками без вебмок, предзагрузка работает?
Запостите теда вебмку, обновите страницу, включите предзагрузку. Грузит?

**Comment by XakepSDK** [comment]
Картинки грузит. Ссылки на картинки заменяются на `blob:id`.

**Comment by SthephanShinkufag** [comment]
Ну а вы мне говорили что вообще ничего не работает, а я сижу и чешу репу, тому що у меня картоинки грузятся. Я не додумался тратить свой трафик на вебмки.

**Comment by XakepSDK** [comment]
До фиксов он ничего не подгружал.

**Comment by SthephanShinkufag** [comment]
Да ну.

**Comment by SthephanShinkufag** [comment]
А чому у меня подгружал?

**Comment by XakepSDK** [comment]
По крайней мере с моими расширениями.

**Comment by SthephanShinkufag** [comment]
Вот тут https://lolifox.org/b/res/32895.html чётко видно, что предзагрузка на вебмки не действует.
Я даже  уже могу сказать чому - если навести на превьюху вебмки курсор, там будет ссылка https://lolifox.org/player.php?v=/b/src/1515490205542-0.webm&t=1515347890888-0.webm&loop=1
нужно её преобразовывать в https://lolifox.org/b/src/1515490205542-0.webm

**Comment by XakepSDK** [comment]
А еще кнопка, которая над webm сломалась.

**Comment by SthephanShinkufag** [comment]
Кнопки `[один раз] [по кругу]` надо скрыть, кстати, они не нужны. Или вы другое имеете в виду?

**Comment by XakepSDK** [comment]
Эти кнопки.

**Comment by XakepSDK** [comment]
И еще ошибка: не могу постить.
Ошибка:
>Ваш браузер послал ошибочный HTTP реферрер. Ну или совсем его не отправил.

Без куклоскрипта работает нормально.

**Comment by SthephanShinkufag** [comment]
У вапсв прокси/анонимайзер?
Скрипт [не дружит с friGate](#1119)

**Comment by XakepSDK** [comment]
У меня openvpn.

**Comment by SthephanShinkufag** [comment]
> openvpn
Я пока не разбирался с этим багом, но мне известно, что с vpn-ками куклоскрипт не постит, и ругается на реферер.

**Comment by SthephanShinkufag** [comment]
Кстати, если отключить опцию `Форма` > `Отправка постов без перезагрузки* ` то даст постить?

**Comment by XakepSDK** [comment]
Постит, но не редиректит назад:
```json
{"redirect":"\/b\/res\/32895.html#32954","noko":true,"id":"32954"}
```

**Comment by SthephanShinkufag** [comment]
Починено. Такая же проблема была на 8ch.net и других vichan-имиджбордах. Теперь ссылки на webm/mp4 везде корректные.
Теоретически, предзагрузке ничего не должно мешать. В тестовом треде на 1-2 вебмки они грузятся. Сижу сегодня с тостера в глухом лесу, не могу себе позволить большой трафик.
Пробуйте.

**Comment by XakepSDK** [comment]
Предзагрузка webm работает.
Постинг не работает.

**Comment by SthephanShinkufag** [comment]
Я не чинил постинг с vpn. В ближайшем поставлю openvpn и посмотрю.

**Comment by XakepSDK** [comment]
OpenVPN подключен на уровне роутера, это не мусороподелие в виде расширений для браузера.
Ошибка в кукле, как и во всех остальных случаях и VPN тут не причём.
(твоё сообщение вызвало у меня глубочайший facepalm)

**Comment by SthephanShinkufag** [comment]
Я уже постил issue #1119. Человек с аддоном-анонимайзеров имеет проблему с реферером, как и у вас. Вы тогда уточняйте сразу, а а не умничайте.

**Comment by XakepSDK** [comment]
Я важные места буду отмечать **жирным**, хорошо?
https://puu.sh/yYfKz/78aec6c748.png

**Comment by SthephanShinkufag** [comment]
Я не увидел. Боюсь, я не смогу исправить этот баг, пока не воспроизведу эту ошибку у себя.

**Comment by XakepSDK** [comment]
Просто попробуй запостить на лолифоксе.

**Comment by SthephanShinkufag** [comment]
Я вчера там штук 5 постов отправил.

**Comment by SthephanShinkufag** [comment]
Вот мой пост, например.
https://lolifox.org/b/res/32895.html#32922

Попробуйте получить доступ к другому ПК, у друзей-знакомых-родственников и отправить пост с куклой.

**Comment by XakepSDK** [comment]
Вот тебе крутой профиль для Firefox: http://rgho.st/6QR9zVPhj
Чистый профиль с твоей куклой и блокировкой встроенной куклы.
Похоже, что твои расширения что-то там у тебя фиксят, поэтому у тебя и работает постинг.

**Comment by SthephanShinkufag** [comment]
У меня нет никаких расширений, кроме violentmonkey и uBlock. Постил вчера с двух разных пк.

**Comment by XakepSDK** [comment]
Делай что хочешь. Не забудь сюда отписать, если пофиксишь.

У тебя в коде где-то есть такая конструкция `rel="noreferrer"`, может из JS добавляется тег, может из-за замены формы. У меня нет желания искать место с этой ошибкой.

**Comment by XakepSDK** [comment]
Собственно, быстрый поиск вот что показал: https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/blob/master/src/Dollchan_Extension_Tools.es6.user.js#L14645

Наиболее вероятное место с ошибкой.

**Comment by SthephanShinkufag** [comment]
Этот атрибут в кукле добавляется только для ссылок в окне "Избранное". На `iichan.hk` например запрещён переход с `2ch.hk`. Когда кликаешьт по такой ссылке, ычан не будет знать, что на него зашли с мейлача.

**Comment by SthephanShinkufag** [comment]
> отправляешь запрос без нужного header'а

Скорее всего, нужно будет добавить что-то вроде

```js
xhr.setRequestHeader('referer', 'http://www.lolifox.org');
```

**Comment by SthephanShinkufag** [comment]
Кстати, а на `http://8ch.net/test/` вам даёт постить?

**Comment by SthephanShinkufag** [comment]
Всё, выяснено.
Загрузил я ваш профиль, и действительно, ругается на реферер на всех vichan-досках: lolifox, 8ch, и т.д.

Пробовал подставлять в POST-запросы свой Referer - браузер его вообще игнорирует.

```js
		ajaxParams.headers = {'Referer': aib.prot + '//' + aib.host};
		const xhr = await $ajax(form.action, ajaxParams, true);
```

Скорее всего, кастомный реферер в заголовках запроса нельзя устанавливать из соображений безопасности.

Установил под вашим профилем Violentmonkey - всё постится! И Tampermonkey тоже даёт постить.
Так что это баг Greasemonkey, а не куклы.

**Comment by SthephanShinkufag** [comment]
У меня, соответственно, всё прекрасно постилось, тому що я тоже использую Violentmonkey.
И я теперь уверен, что у #1119 та же самая проблема из-за гризманки.

**Comment by SthephanShinkufag** [comment]
e7b6a231294a4b5b5e7e712e77f83c7336749bd2

С данным коммитом теперь не нужен uBlock. Если встроенный в борду Dollchan отключить кнопкой "Включить/выключить Dollchan", то будет запускаться обычный.
