### ISSUE TITLE
проблема с "Избранное"

### ISSUE THREAD

**Issue by perdolka** [SthephanShinkufag/Dollchan-Extension-Tools#1168]
Опишу все шаги для точности.

1 На панели "Избранное" нажимаю  "Обновить"
2 Перехожу по адресам тех тредов, у которых появилась/обновилась цифра, обозначающая количество новых постов. Треды открываю на новых вкладках.
3 Читаю эти треды, тапаю на их страницах. Пишу/ридонли - результат одинаковый.
4 Возвращаюсь на ту страницу, где изначально открыта панель "Избранное" (п1), даже обновляю её (F5)
Теперь о проблемах после этого.
5 На панели "Избранное" нажимаю  "Обновить" - цифры, обозначающие количество новых постов у посещённых тредов не обнуляются. Или обнуляются но со временем (на новых вкладках или после обновления страницы) появляются опять. Эти цифры, естественно, обозначают уже прочитанные посты (п3). 
6 Некоторые треды (добавленные автоматически или вручную) исчезают с панели "Избранное".
Или НЕ исчезают, но со временем (на новых вкладках или после обновления страницы) исчезают опять. Эти треды, естественно, не удалены.

Возможно это как-то связано с использованием ВПН ? 
Я использую Browsec VPN

борда - сосач (харкач)
FF - 56.0.2 (x64)
Browsec VPN - 3.19.2
Violentmonkey - 2.8.24
кукла -  18.1.4.0 / e7b6a23

**Comment by SthephanShinkufag** [comment]
Теперь открытое окно `"Избранное"` синхронизируется со всеми вкладками, где работает апдейтер тредов.
