### ISSUE TITLE
Капча на форчане

### ISSUE THREAD

**Issue by RosinSmoke** [SthephanShinkufag/Dollchan-Extension-Tools#1169]
v1 отвалилась, теперь просто пустой фрейм. Переключателя версии капчи в настройках куклоскрипта вроде нет, а на самом форчане эта опция теперь выпилена, но скрипт-то старую запрашивает.
http://puu.sh/z7XAW/cb0c398993.png

**Comment by SthephanShinkufag** [comment]
> Переключателя версии капчи в настройках куклоскрипта вроде нет

Есть.

`"Настройки"` - `"Форма"` - `"4chan: альтернативная капча*"`

**Comment by RosinSmoke** [comment]
Ксо. Мои вам пардоны, проглядел.
Ну а в целом, наверное галка теперь бесполезная, может добавите в список что убрать при следующей чистке.
