### ISSUE TITLE
4chan: альтернативная капча - NoScript Captcha

### ISSUE THREAD

**Issue by anomalos** [SthephanShinkufag/Dollchan-Extension-Tools#1170]
Альтернативные текстовые капчи теперь не существуют на 4chan. Можно ли изменить опцию альтернативной капчи на использование капчи, не использующей JavaScript? Дело в том, что капча с включённым JS требует часто несколько кругов проверки, а без JS - только один раз.

**Comment by pwf63158cdnqacom** [comment]
В 4chanX это уже реализовано, но и работает он только там, да и непривычно. 
Выключать скрипт чтобы запостить что-нибудь конечно тоже неудобно.

**Comment by SthephanShinkufag** [comment]
> Выключать скрипт чтобы запостить что-нибудь

"Настройки" - "Форма" - "4chan: альтернативная капча*", отключите опцию, всё постится.

**Comment by SthephanShinkufag** [comment]
> Можно ли изменить опцию альтернативной капчи на использование капчи, не использующей JavaScript?

Готово! Благодарю за отличную идею!
Старая опци убрана, теперь доступна новая опция: "Настройки" - "Форма" - "Использовать альтернативную капчу".
В качестве альтернативной будет использоваться NoScript-рекапча.

**Comment by SthephanShinkufag** [comment]
Алсо, эту же опцию я планирую использовать, когда реализую цифровую капчу на мейлаче #1171.

**Comment by Dezaimasu** [comment]
Не совсем баг, скорее сам себе буратино. Перед этим переключался обратно на стандартную капчу, но не вынес, и вернул noscript версию обратно. При постинге с noscript капчи получаю "Error: You seem to have mistyped the CAPTCHA. Please try again.4chan Pass users can bypass this CAPTCHA." Хотя капчу разгадываю, текст копирую, всё как обычно. На голом профиле не воспроизвёл, т.е. проблема локальная. Вот буквально недавно, уже на втором компьютере такое началось. Может есть идеи, что может быть? Куки форчановские вычищал, разницы нет.

**Comment by SthephanShinkufag** [comment]
Обновляйте страницу после изменения опции!

**Comment by Dezaimasu** [comment]
Да уже даже браузер перезагрузил.
Алсо в дебаг инфе
>"cap4chanAlt": 0,
>"altCaptcha": 1
cap4chanAlt это рудимент?

**Comment by SthephanShinkufag** [comment]
@Dezaimasu да, надо бы запилить в скрипте удалялку устаревших настроек.

**Comment by Dezaimasu** [comment]
Всё, нашел виновника. Уже глаз дёргался от этих бесконечных дорожных знаков. Как обычно сам себе колено прострелил.
>network.http.referer.spoofSource _true_
network.http.referer.trimmingPolicy _2_
network.http.enablePerElementReferrer _false_
network.http.referer.userControlPolicy _3_

Вот этими настройками старая гуглокапча ломается. Лень вычленять какая именно из этих четырёх. 
Если не против пусть лежат тут в назидание потомкам, может гугел кого сюда приведёт.
