### ISSUE TITLE
2ch.hk - цифрофая капча 2chDigitGayCaptcha + Dollchan

### ISSUE THREAD

**Issue by NEONZARIN** [SthephanShinkufag/Dollchan-Extension-Tools#1171]
Собственно очень хотелось бы эту капчу работающую вместе с Dollchan. Сама по себе эта капча работает, только без куклы. С куклой выбивает ошибку ввода капчи.
[https://greasyfork.org/en/scripts/37655-2chdigitgaycaptcha](url)
![default](https://user-images.githubusercontent.com/16442992/35453996-40f0c0e4-02dd-11e8-9473-72b71762628a.PNG)

**Comment by SthephanShinkufag** [comment]
Надо своровать этот скрипт в наш Dollchan.
И тогда будет опция "Использовать альтернативную капчу".

**Comment by NEONZARIN** [comment]
Там часто новые версии выходят, если что.
![default](https://user-images.githubusercontent.com/16442992/35638086-3b001ce6-06c7-11e8-974f-7141b437cbb1.png)

**Comment by NEONZARIN** [comment]
![default](https://user-images.githubusercontent.com/16442992/35745409-44660442-0854-11e8-9428-bb7b6aa8bc79.png)
![default](https://user-images.githubusercontent.com/16442992/35745488-7d9ecb4a-0854-11e8-9e37-84ae269c42ce.png)
