### ISSUE TITLE
Поддержка archived.moe + др.

### ISSUE THREAD

**Issue by zbczyvgy** [SthephanShinkufag/Dollchan-Extension-Tools#1172]
Добавить поддержку Archived.Moe и борд, указанных как сорсы ( https://archived.moe/_/articles/faq/ ).
Еще было бы хорошо добавить warosu.org

**Comment by SthephanShinkufag** [comment]
Related to #952.

**Comment by SthephanShinkufag** [comment]
Готово. Проверка:
https://archived.moe/b/
https://rbt.asia/mu/
https://thebarchive.com/b/
https://archiveofsins.com/h/
https://boards.fireden.net/a/
https://desuarchive.org/a/
https://archive.4plebs.org/pol/
http://archive.nyafuu.org/c/

Для https://archived.moe/b/ реализовано отслеживание редиректа картинок.
