### ISSUE TITLE
[Feature Request] Последовательное воспроизведение webm/mp4 в треде

### ISSUE THREAD

**Issue by mytischi359** [SthephanShinkufag/Dollchan-Extension-Tools#1173]
Навеяно муз вебм тредами. Нечто подобное уже есть для ютуб ссылок по Alt+V. Дополните это окошко всеми вебмками в треде и пусть воспроизводятся друг за другом. В идеале вебмки в новых псотах на автомате запускать. Такое бордо радио получится.

**Comment by SthephanShinkufag** [comment]
Дублировать вебмки в отдельном списке нет смысла.
Добавил новую кнопку:
![autoplay_video](https://user-images.githubusercontent.com/1059874/36074527-9c6b0b50-0f49-11e8-91af-791601a56371.png)

Когда кнопка активирована - по окончанию проигрывания текущего видео автоматически стартует следующее видео на странице, игнорируя картинки.
