### ISSUE TITLE
2ch.hk Не отправляется пост с прикрепленными изображениями в разделе /b/

### ISSUE THREAD

**Issue by NEONZARIN** [SthephanShinkufag/Dollchan-Extension-Tools#1175]
При отключении куклы посты с прилепленными изображениями отправляются как положено. Например в /a/ все работает. Откат на прошлые версии не помог. Видать макака что то специально сделала. Подтвердите баг у кого тоже так. Как на скрине бесконечная отправка.
![default](https://user-images.githubusercontent.com/16442992/36080811-43f7face-0fa7-11e8-93b0-b9cf55826d8b.png)

**Comment by SthephanShinkufag** [comment]
Настройки - Инфо - Отладка.
Запостите сюда результат.

**Comment by NEONZARIN** [comment]
{
	"version": "18.2.8.0.4d7a593",
	"location": "https://2ch.hk/b/res/170552699.html",
	"nav": {
		"ua": "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0 [20180206200532]",
		"firefoxVer": "58",
		"isChrome": false,
		"isChromeStorage": false,
		"isFirefox": true,
		"isGM": true,
		"isNewGM": false,
		"isSafari": false,
		"isScriptStorage": false,
		"isWebkit": false,
		"hasGMXHR": true,
		"isMsEdge": false,
		"isGlobal": true,
		"isPresto": false,
		"isESNext": false,
		"scriptInstall": "Violentmonkey",
		"hasTemplate": true,
		"hasWorker": true,
		"canPlayMP3": true
	},
	"Cfg": {
		"timePattern": "dd+nn+yy+w+hh+ii+ss",
		"addVocaroo": 0,
		"hideBySpell": 0,
		"cfgTab": "info",
		"captchaLang": 2,
		"altCaptcha": 1,
		"findImgFile": 1,
		"webmTitles": 1,
		"delImgNames": 1,
		"crossLinks": 1,
		"decodeLinks": 1,
		"removeFName": 1,
		"warnSubjTrip": 1,
		"inftyScroll": 0,
		"scrUpdIntrv": 0,
		"addOPLink": 1,
		"noSpoilers": 0,
		"favIcoBlink": 1,
		"updThrDelay": "10",
		"animation": 0,
		"scrollToTop": 1,
		"scriptStyle": 2,
		"imgInfoLink": 0,
		"linksOut": 1000,
		"addPostForm": 1,
		"spacedQuote": 0,
		"markViewed": 1,
		"postSameImg": 0,
		"sageReply": 1
	},
	"sSpells": [
		"#wipe(samelines,samewords,longwords,symbols,numbers,whitespace)"
	],
	"perf": [
		[
			"Imageboard check",
			1
		],
		[
			"Data loading",
			0
		],
		[
			"Init",
			13
		],
		[
			"Read my posts",
			2
		],
		[
			"Replace delform",
			36
		],
		[
			"Parse delform",
			22
		],
		[
			"Parse postform",
			19
		],
		[
			"Init keybinds",
			1
		],
		[
			"Init page",
			8
		],
		[
			"Add panel",
			2
		],
		[
			"Init AJAX",
			1
		],
		[
			"Preload images",
			0
		],
		[
			"Audio links",
			1
		],
		[
			"Video links",
			2
		],
		[
			"Image names",
			2
		],
		[
			"Reflinks map",
			13
		],
		[
			"Apply CSS",
			8
		],
		[
			"Display page",
			0
		],
		[
			"Infinity scroll",
			0
		],
		[
			"Hide posts",
			4
		],
		[
			"Scroll page",
			1
		],
		[
			"Всего",
			136
		]
	]
}

**Comment by SthephanShinkufag** [comment]
Firefox 58 + Violentmonkey
Применил ваши настройки, в /b и /a картинки постятся.

Что-нибудь пишет в консоли ошибок (`Ctrl+Shift+J`) после момента нажатия на `Отправить`?

**Comment by NEONZARIN** [comment]
Можно закрывать. Это несовместимость куклы и этого расширения IDM Integration Module.
