### ISSUE TITLE
[Tampermonkey]: Не открывается instagram со скриптом

### ISSUE THREAD

**Issue by apan65** [SthephanShinkufag/Dollchan-Extension-Tools#1176]
Обновил лису, там greasemonkey тупит дичайше, поэтому перекатился в tampermonkey, теперь инстаграм не открывается, вроде вписываю в excludes сайт и все-равно не работает, только отключая скрипт сайт грузится.

**Comment by SthephanShinkufag** [comment]
Greasemonkey умер.
Инстаграмом не пользуюсь, аккаунта нет. Зарегал пустой аккаунт - вроде сайт работает.
Попробуйте Violentmonkey, уже полгода пользуюсь, брат жив, зависимости нет.

**Comment by apan65** [comment]
Ага, с этой обезьяной нормально работает.

**Comment by SthephanShinkufag** [comment]
Я проверял инстаграм с виолентманки. Значит, надо ставить проверять совместимость тамперманки и инстаграма.

**Comment by SthephanShinkufag** [comment]
@apan65 

Хм, с тамперманки тоже работает. Фиг его знает тогда.

**Comment by apan65** [comment]
Лол, ну и хрен с ним. Буду на насильственной обезьяне сидеть.

**Comment by artemsmikh** [comment]
Сейм. Не скажу, что испытываю неудобства, т.к. инстаграмом не пользуюсь, но для статистики отпишусь.
FF 58.0.2, Tampermonkey v4.6.5703, куклоскрипт v. 18.2.19.0

**Comment by apan65** [comment]
На violentmonkey избранное не сохранялось, перекатился снова на temper

**Comment by SthephanShinkufag** [comment]
@apan65

Как не сохранялись? Как это выглядело, как добиться?

**Comment by apan65** [comment]
Я импортировал скрипты через зип файл, когда добавляешь тред в избранное, он сохраняется только в этой вкладке, когда открываешь новую вкладку(или обновляешь текущую) список избранного тот же что и был при импортировании скриптов.

**Comment by SthephanShinkufag** [comment]
Что за импорт через зип файл такой?
Мне кажется, это проблема с  вашим импортом.
Можете попробовать просто проинсталлировать скрипт начисто обычным способом, всё будет ок.

**Comment by apan65** [comment]
Выбираю экспорт в одном плагине, импортирую через другой.
Я по-моему делал чистую установку с импортом файла настроек куклы.

**Comment by SthephanShinkufag** [comment]
Я не гарантирую корректную работу с импортом через плагины, так как никогда этого не делал.
Если вы делали чистую установку и импортировали через файл настроек, то это другое дело. Можете прислать ваш файл с настройками на sthephan.shi@gmail.com, я попробую загрузить его у себя.

**Comment by SthephanShinkufag** [comment]
@artemsmikh @apan65 

Опять решил проверить, поставил Tampermonkey на лису, зашел в инстаграм, всё работает.
ЧЯДНТ?
Что пишет в консоли ошибок (`Ctrl+Shift+J`) при заходе в инстаграм?

**Comment by artemsmikh** [comment]
@SthephanShinkufag  К сожалению, теперь и я не могу воспроизвести этот баг.

**Comment by ImoutoChan** [comment]
Воспроизвелось.

В консоли ничего нет.

С выключеным скриптом:
![image](https://user-images.githubusercontent.com/14975965/42382076-d994002c-813b-11e8-842c-81e4cd04624b.png)
С включеным:
![image](https://user-images.githubusercontent.com/14975965/42382085-e03e06c0-813b-11e8-9589-badada90e679.png)

Похоже реакт ломается (или отключается специально?) и не заполняет контент.
Это самая первая страничка логина.

**Comment by apan65** [comment]
Лол, а у меня наоборот перестала воспроизводиться.

**Comment by SthephanShinkufag** [comment]
Ребята, я оптимизировал работу Dollchan на НЕ-имиджбордах. Проверьте, у кого не работал инстаграм, гугль, и прочая лабуда с Tampermonkey+Dollchan. Исправилось? Должно.

**Comment by artemsmikh** [comment]
Версия 19.1.5.0, Tampermonkey, Safari. Проблем с открытием Instagram не наблюдаю. Хорошая работа, брат!
