### ISSUE TITLE
Проблема постинга на rfch.rocks

### ISSUE THREAD

**Issue by Darktrader** [SthephanShinkufag/Dollchan-Extension-Tools#1177]
Совсем не хочет постить на данной имиджборде. Пишет: 

> Your browser sent an invalid or no HTTP referer.

Похожая ситуация возникает на многих бордах, где стоит движок Tinyboard/Vichan или любой из его форков. Я даже когда установил на локалхост вичан и попробовал запостить из-под куклоскрипта, то мне выдалу ту же ошибку.

**Comment by SthephanShinkufag** [comment]
Greasemonkey.
Удалите.
[Violentmonkey](https://addons.mozilla.org/ru/firefox/addon/violentmonkey/)
[Tampermonkey](https://addons.mozilla.org/ru/firefox/addon/tampermonkey/versions/beta)

*Related to #1119*

**Comment by SthephanShinkufag** [comment]
Гризманки не отправляет реферер при запросах.

**Comment by Darktrader** [comment]
Вот как. Понял, буду знать.
