### ISSUE TITLE
"Быстрый ответ" на vichan-подобных имиджбордах

### ISSUE THREAD

**Issue by Darktrader** [SthephanShinkufag/Dollchan-Extension-Tools#1179]
Степан привет, это снова я. Хотел спросить и зареквестировать фичу очень важную и недостающую. Суть в том, что на всех АИБах, которые были подняты на движке Tinyboard/Vichan или их форках - отсутствует возможность отвечать в тред, не заходя в него. Знаю, что сам движок "из-под коробки" не поддерживает эту фичу, в отличии от той же kusaba. С другой стороны, насколько я знаю, wakaba и ее форки тоже не поддерживают быстрый ответ. Но тем не менее, с помощью куклоскрипта это все  легко исправляется. Можешь ли ты также запилить подобное для вичанодвижков, учитывая то, что каждая вторая борда поднята на нем.

**Comment by SthephanShinkufag** [comment]
Не так. Скриптом предусмотрен быстрый ответ из списка тредов на любой борде, в том числе и на vichan. Скрипту не важно, что за движок и откуда происходит запрос. Но на tinyboard и его форках, к которым относится vichan, существует пресловутая ЗАЩИТА ОТ СПАМА. Она режет попытку запостить из списка тредов, выдавая ошибку `You look like a bot`. И победить это не получилось. Поэтому я взял и просто скрыл кнопки быстрого ответа. Их легко вернуть, но защиту от спама не победить. На днях еще раз гляну, может придет идея в голову, как её обойти.

**Comment by SthephanShinkufag** [comment]
Мне удалось победить антибот-защиту при ответе из списка досок на Tinyboard и Vichan.
Правда, есть особенность. При клике по кнопке быстрого ответа из списка досок в память каждый раз загружается весь тред, чтобы получить скрытые поля и хеш  для формы.

**Comment by SthephanShinkufag** [comment]
Проблема реально была древняя, идея загружать нужную форму из треда была давно, но это очень костыльно, поэтому не реализовывал. Что же, другого выхода пока не вижу.

**Comment by Darktrader** [comment]
Что ж мне кажется учитывая распространения борд на тинибордах/вичане даже любой костыль лучше чем отсутствие его.

**Comment by SthephanShinkufag** [comment]
Сейчас ещё надо как-то обыграть ситуацию, в случае если загрузить из треда форму с правильными полями не получится. Например, долгий ответ от сервера, либо какая-нибудь ещё ошибка при загрузке.
В этом случае сейчас выдается сообщение `Error while loading form`.
Но этого недостаточно. Нужно вообще скрывать форму, чтобы пользователь даже не пытался отправить ответ с некорректными полями, получая `"You like a bot"`.
