### ISSUE TITLE
Реквест: noscrip каптча на форчане

### ISSUE THREAD

**Issue by lordnoobw** [SthephanShinkufag/Dollchan-Extension-Tools#1180]
В связи с тем что v1 рекаптча сдохла реквестирую опцию хотя бы на носкрипт v2 каптчу как в 4chanX что бы бесконечных лупов небыло.

**Comment by SthephanShinkufag** [comment]
Уже реализовано.
#1170
Обновите скрипт до последней версии.

**Comment by lordnoobw** [comment]
Упс, опция выключена была с момента смерти v1. Не заметил.
