### ISSUE TITLE
[Feature request] Скрытие только ответов на пост

### ISSUE THREAD

**Issue by Darktrader** [SthephanShinkufag/Dollchan-Extension-Tools#1181]
Я тут подумал, что было бы неплохо, если бы ты добавил возможность скрывать только ответы на пост, не скрывая самого поста.  Т.е. наводишь на крестик, а там выпадает список тот, и можно выбрать скрыть только ответы все. Это очень полезно, так как иногда вроде хороший пост идет, только вот беда, что ответы на него сплошной щитпостинг.

**Comment by SthephanShinkufag** [comment]
В меню скрытия постов добавлен пункт `Скрыть только ответы`. Скрывает рекурсивно все ответы на пост, ответы на ответы и т.д.

**Comment by Darktrader** [comment]
Збс. Спасибо Степан. Только я хотел ещё возможность, чтобы скрывать ответы на пост можно было ещё до того, как кто-то ответит на пост. Это получается как автоскрытие новых постов, только вместо классических спелов к строкам, тут у нас идёт по ссылкам на пост внутри треда.

**Comment by SthephanShinkufag** [comment]
Можно попробовать добавить новый спелл `#ref(num)`, где `num` - номер поста. Только это не будет рекурсивное скрытие, скрываться будут только ответы на конкретный пост.

**Comment by SthephanShinkufag** [comment]
Хотя, нет, такой спелл не нужен.
Погорячился.
Достаточно использовать спелл `#words(>>171388349)`

**Comment by SthephanShinkufag** [comment]
Могу сделать, чтобы по клику на `"Скрыть только ответы"` добавлялся спелл  `#words(>>1234567)`.

**Comment by Darktrader** [comment]
Ну давай тогда так, раз ты говоришь, что они дублировать будут друг друга.

**Comment by SthephanShinkufag** [comment]
В меню скрытия постов "Скрыть только ответы" теперь скрывает только ответы на данный пост, добавляя спелл `#words[борда,номерТреда](>>номерПоста)`. Также убудут скрываться новые подгруженные ответы на данный пост.

**Comment by SthephanShinkufag** [comment]
Теперь опция отображается всегда, даже если ответов на пост ещё нет.

**Comment by SthephanShinkufag** [comment]
Блджад, я совсем забыл про опцию `"Скрывать ответы на скрытые посты"`.
Таким образом, со включённой этой опцией, "Скрывать ответы" будет действовать рекурсивно и скрывать ответы на ответы.
