### ISSUE TITLE
[2ch.hk] Счётчик новых постов на вкладке считает скрытые посты

### ISSUE THREAD

**Issue by succade** [SthephanShinkufag/Dollchan-Extension-Tools#1182]
Не знаю, задумано ли так или нет, но это сильно напрягает.

**Comment by SthephanShinkufag** [comment]
> скрытые посты

Ах, СКРЫТЫЕ. А я прочитал как удалённые.
Скрытые посты учитываются, так и должно быть! !

**Comment by succade** [comment]
Скрытые удаленные, прости, надо было уточнить.
Там визуально удаленные посты проскакивают при обновление треда.

**Comment by SthephanShinkufag** [comment]
Ага, *удаление скрытых постов*. То есть, включена опция `"Фильтры"` > `"Удалять скрытое"`.
Так бы сразу и написали.
Тогда гляну, можно ли как-то реализовать игнорирование скрытых постов в счётчике с этой опцией.

**Comment by succade** [comment]
Протестировал с нового профиля хрома переустановив tampermonkey + скрипт. Всё работало как надо. То есть не считало удаленные скрытые посты, значит проблема на моей стороне. Прости за беспокойство.
