### ISSUE TITLE
2ch.hk: Превью постов по mouseover'у

### ISSUE THREAD

**Issue by CherryPerry** [SthephanShinkufag/Dollchan-Extension-Tools#1183]
Сломалось превью постов по mouseover'у, оно как-будто выходит куда-то за экран вниз, т.к. появляется огромный отступ снизу. Воспроизводится пока только в /a.

Ну и макакакодинг в действии:
![default](https://user-images.githubusercontent.com/9081555/36441335-5b237f06-1683-11e8-8e33-401ec9fdcbb2.PNG)
В начале страницы появился текст оп-поста, возможно это вызвало поломку. На других бордах вроде этого нет.

```
const version = '18.2.19.0';
const commit = '7d74ff9';
```

Хромог последний.

**Comment by Garitos** [comment]
В vg та же история. Первый до наведения. Второй после.
![1](https://user-images.githubusercontent.com/20102977/36442842-1d23208a-1688-11e8-81be-97e70a1e741b.png)
![2](https://user-images.githubusercontent.com/20102977/36442843-1d4386fe-1688-11e8-82ab-d904bb8450a2.png)

**Comment by Rolfeg** [comment]
/hw/ тоже затронут.
Firefox 56.0.2 (64-бит) v18.2.19.0.7d74ff9

**Comment by SthephanShinkufag** [comment]
Чому никто никогда не пишет тип установки скрипта? Как хроморасширение, или через тамперманки в хроме, через гризманки/виолентманки/тамперманки в Firefox...

**Comment by CherryPerry** [comment]
Не серчай, забыл. Tamper Chrome.
А вообще заведи уже ISSUE_TEMPLATE.md для удобства.

**Comment by SthephanShinkufag** [comment]
Не могу добиться бага. Firefox 58.0.2 (64-бит) + ViolentMonkey, Chrome 64.0.3282.167 (64 бит) + Violentmonkey.
https://2ch.hk/hw/a, https://2ch.hk/hw/vg, https://2ch.hk/hw/hw

Навожу на ссылки, превью постов ведет себя нормально.

> ISSUE_TEMPLATE.md

Благодарю за идею.

**Comment by Rolfeg** [comment]
Само починилось. Видимо были временные шатания от добавления части оп-поста в стиль (скрин 1го поста) - оно тоже пропало.
