### ISSUE TITLE
Не работает spell #rep на rfch.rocks

### ISSUE THREAD

**Issue by Darktrader** [SthephanShinkufag/Dollchan-Extension-Tools#1184]
В общем, когда добавляешь данный спелл и применяешь, скрипт его вроде применяет, но: никакие изменения не происходят и перезагрузке странице, он исчезает. На других бордах еще не смотрел пока его работоспособность.

**Comment by SthephanShinkufag** [comment]
Всё работает.
Покажите ваш спелл, может он некорректный.

**Comment by Darktrader** [comment]
Да без проблем: 
`#rep(/добропараша/ig, Доброчан)`

**Comment by SthephanShinkufag** [comment]
* Другие спеллы на `rfch.rocks` применяются?
* На других имиджбордах `#rep` работает?

**Comment by Darktrader** [comment]
> Другие спеллы на rfch.rocks применяются?

Да, вполне.

> На других имиджбордах #rep работает?

Да, работает.

**Comment by SthephanShinkufag** [comment]
Можете показать весь список спеллов на `rfch.rocks`?
Или киньте сюда, или можете прислать мне на sthephan.shi@gmail.com, если не хотите палить на весь гитхаб.

**Comment by Darktrader** [comment]
А все, отбой. Вроде проблема сама собой разрешилась. Я просто перезапустил в очередной раз браузер и оно исчезло, лол.
