### ISSUE TITLE
капча на харкаче

### ISSUE THREAD

**Issue by perdolka** [SthephanShinkufag/Dollchan-Extension-Tools#1185]
Макак уже добавил (вернул?) опцию выбора между 2chcapcha и гуглокапча 
(настройка - другое - капча)
С выключенной куклой работает, с включённой - появляется только гуглокапча.

FF 59.0b12 (x64)
5a16226

**Comment by SthephanShinkufag** [comment]
Уже давно реализовано #1171 

Опция "Настройки" > "Форма" > "Использовать альтернативную капчу".
Можно переключать опцию на лету, капча автоматически перестраивается.

**Comment by perdolka** [comment]
упс
