### ISSUE TITLE
[2ch.hk]: Adblock/Adguard блокирует открытие файла в новой вкладке.

### ISSUE THREAD

**Issue by LikiPra** [SthephanShinkufag/Dollchan-Extension-Tools#1186]
При включенных Dollchan и Adblock/Adguard не открывает файлы (будь то png, gif, webm и т.д.) в новой вкладке.
![default](https://user-images.githubusercontent.com/36929982/36802184-51fe0fd4-1cc5-11e8-9b10-32e90417896f.png)
При этом если кликать по названию файла или открывать через копипасту url, то все работает.
Так же, при выборочном включении плагинов (либо Dollchan, либо Adblock), все тоже работает.

Браузер: Google Chrome 64.0.3282.167
Dollchan стоит как расширение.

P.S. Вопрос, как выключить замену названия webm при его сохранении на его url?

**Comment by SthephanShinkufag** [comment]
Отключите предзагрузку картинок.

**Comment by LikiPra** [comment]
Спасибо.

**Comment by LikiPra** [comment]
Спасибо.

**Comment by LikiPra** [comment]
Буду благодарен, если добавите приписку к этой функции или что проще, описание здесь на Wiki. Т.к. гугл нужной информации не выдавал, да и на wiki я ее не нашел. Для таких "не умных" пользователей это многое упростит.

**Comment by SthephanShinkufag** [comment]
Пердзагрузка подразумевает, что картинка/webm скачивается, и хранится в памяти в виде массива двоичных данных `blob`. Блоб не хранит оригинальное имя файла. А адблокеры могут блокировать такие данные.
