### ISSUE TITLE
4chan Не проигрывается музыка в треде.

### ISSUE THREAD

**Issue by lordnoobw** [SthephanShinkufag/Dollchan-Extension-Tools#1188]
https://boards.4chan.org/v/thread/408619304/rest-in-peace-ankin
С куклой музыка не играет, без куклы играет. Проверил на чистом браузере.

**Comment by SthephanShinkufag** [comment]
В смысле музыка? Что вы имеете в виду?

**Comment by lordnoobw** [comment]
Моды прикрепили тред и врубили музыку. Бида, уже отключили.

**Comment by SthephanShinkufag** [comment]
Fixed: add1c2f5eadc9147090d494790849087d2571b3e
