### ISSUE TITLE
Функция постинга в тред с главной страницы

### ISSUE THREAD

**Issue by imasuridondai** [SthephanShinkufag/Dollchan-Extension-Tools#1190]
А можно сделать так, чтобы на главной странице внизу каждого треда кроме [Получить новые посты] была бы функция [Запостить в тред]? Сейчас мне для того, чтоб мимоходом закинуть в тред картинку, например, надо или зайти в тред с главной страницы, или щёлкнуть по кнопке ответа на чей-нибудь пост и потом из поля ввода убрать ссылку на этот пост, а хочется, чтоб можно было постить сразу с главной страницы без лишних манипуляций.

**Comment by SthephanShinkufag** [comment]
![no_link_reply](https://user-images.githubusercontent.com/1059874/36995815-d38da626-20bd-11e8-9812-82d9c2c4cabf.png)

**Comment by imasuridondai** [comment]
Знаю я эту опцию, это совсем не то. Во-первых, когда просматриваешь список тредов и хочешь ответить в один из них, кнопку для ответа удобнее иметь после последних постов, чтобы не скроллить сначала вверх до кнопок ОП-поста, а потом вниз; по крайней мере, лично мне удобнее использовать кнопку ответа последнего поста и потом удалить ссылку на этот пост, чем скроллить. Во-вторых, а что делать, если из списка треда хочешь, например, не просто бампануть тред, а именно ответить ОПу, со ссылкой на ОП-пост в своём посте? в тред заходить или руками ссылку ставить? Опять-таки неудобно.

**Comment by SthephanShinkufag** [comment]
Не хотет.

**Comment by SthephanShinkufag** [comment]
Зачем дублировать существующий функционал.
Скрипт и так уже bloated as hell.

**Comment by SthephanShinkufag** [comment]
> а что делать, если из списка тредов хочешь, например, не просто бампануть тред, а именно ответить ОПу, со ссылкой на ОП-пост в своём посте?

Нажимайте на **№**

![no_link_reply2](https://user-images.githubusercontent.com/1059874/37000111-fca8f6c0-20ca-11e8-83cf-96e651ed2d49.png)

**Comment by SthephanShinkufag** [comment]
Всё-таки реализовал.
Проверяйте.

**Comment by NEONZARIN** [comment]
А как выключить теперь в уже открытом треде это? Лучше было бы сделать кнопочки _ответить на ОП пост_ и оставить _добавить в избранное_ ну и эти сами знаки убрать _>>_.
![image](https://user-images.githubusercontent.com/16442992/37820676-75dc0346-2e92-11e8-9553-843781a00773.png)

**Comment by NEONZARIN** [comment]
Ну в самом открытом треде в конце думаю оно вообще не нужно. В начале треда все это есть есть, избранное, ответить на оп пост.

**Comment by NEONZARIN** [comment]
Но опционально бы эту менюшка, в настройках что-бы вкл/выкл.

**Comment by SthephanShinkufag** [comment]
Опция `"Кнопки "Получить новые посты" в списке тредов"` устарела, её и переделаю.

**Comment by SthephanShinkufag** [comment]
Опция `"Настройки"` > `"Посты"` > `"Дополнительные кнопки под тредами"`. Варианты выбора: 'Откл.', 'Все', 'Новые посты'.

**Comment by NEONZARIN** [comment]
Опять же нет возможности выключить эти кнопки только в треде, и при этом оставить их включенными в доске.

**Comment by SthephanShinkufag** [comment]
А чем вам они мешают в треде?

**Comment by NEONZARIN** [comment]
Они там лишние лично для меня. А в самой доске удобно с ними.

**Comment by SthephanShinkufag** [comment]
Добавляйте свои user-css.

**Comment by NEONZARIN** [comment]
Но как?

**Comment by NEONZARIN** [comment]
Первая кнопка не скрывается вообще.
![image](https://user-images.githubusercontent.com/16442992/37825547-4c69956e-2ea1-11e8-978e-926eea4f2378.png)

**Comment by SthephanShinkufag** [comment]
Опция `"Настройки"` > `"Посты"` > `"Дополнительные кнопки под тредами"`.
Варианты выбора:
`[Откл.]`
`[Все]`
`[Все (на доске)]'`
`["Новые посты" на доске]`

**Comment by NEONZARIN** [comment]
Вот теперь норм.
