### ISSUE TITLE
2ch.hk реквест фичи *добавить в избранное*

### ISSUE THREAD

**Issue by NEONZARIN** [SthephanShinkufag/Dollchan-Extension-Tools#1192]
![default](https://user-images.githubusercontent.com/16442992/37386037-b299ba1c-2767-11e8-8f22-2817126d481b.png)
Как на скрине что бы была возможность добавить тред в избранное при предпросмотре  выделенного поста.

**Comment by SthephanShinkufag** [comment]
Готово. Теперь добавлять в избранное можно даже по ссылкам "из глубины треда".
