### ISSUE TITLE
[Vichan][8ch.net][lolifox.org]: Отсутствие чекбоксов в постах

### ISSUE THREAD

**Issue by Darktrader** [SthephanShinkufag/Dollchan-Extension-Tools#1193]
В общем суть проблемы вот в чем: на вичанах, а также их многочисленных форках, существует, как известно, множество джаваскриптов из-под коробки, которые легко можно включать и отключать со стороны сервера. И один из этих джаваскриптов, заменяет чекбоксы в постах на "стрелочку-треугольник" с выпадающим меню с многочисленными функциями, в том числе и функцией пользовательского удаления постов. Все это конечно может и замечательно, но оно приводит к тому, что куклоскрипт просто теряется при виде того, что вытворил тот другой скрипт. Одним словом он удаляет эти "треугольнички", но не генерирует при этом вместо них чекбоксы и в футере страницы - форму для удаления. Нужно чтобы он либо не трогал того, что сделал тот скрипт, либо принудительно генерировал чекбоксы с формой для удаления. В общем, чтобы лучше ты понял, зайди на перечисленные сайты выше и сам удостоверся в том, что я сказал тут.

**Comment by SthephanShinkufag** [comment]
Duplicated issue #844
