### ISSUE TITLE
[Firefox Quantum]: Не срабатывают события на <video>

### ISSUE THREAD

**Issue by XakepSDK** [SthephanShinkufag/Dollchan-Extension-Tools#1194]
1. Раньше webm запускались сразу после нажатия на `preview`, теперь просто открывается окно с видео.
2. Чтобы запустить / остановить webm, достаточно нажать на окно с видео, раньше же окно закрывалось. Теперь для закрытия окна нужно использовать кнопку справа сверху.

**Comment by Remu-rin** [comment]
Второе из-за изменения в Firefox 59. При обнове со старой куклой на 59 вообще невозможно закрыть видео. Степан добавил кнопку в угол в тот день. Надо бы версию апнуть, наверное.

**Comment by SthephanShinkufag** [comment]
1. Не понял. Покажите на скриншоте, либо снимите видеоролик.
2. Проблемы 59 лисы, не лечится. Есть специальная кнопка с крестиком вверху, чтобы можно было хоть как-то закрыть.

**Comment by perdolka** [comment]
Ещё можно кликом по превью в посте закрыть.
И просто нажатием Esc

**Comment by XakepSDK** [comment]
@SthephanShinkufag в посте могут быть картинки / вебм, по нажатию на `preview` выбранной картинки / webm - открывается большое, плавающее окно, в нем находится картинка в большем размере, либо проигрывается вебм. Можно менять размер окошка с помощью скролла по нему.
Раньше, после нажатия на `preview` с webm, открывалось окно и webm проигрывалась сразу, теперь же после нажатия на `preview` - открывается окно с webm, но webm не проигрывается, нужно нажать на play.
Сразу после нажатия на `preview`:
https://puu.sh/zJzTC/c1b3ce6384.png
Нужно нажать на кнопку play, чтобы webm начала проигрываться.

Еще нельзя перетаскивать окно, вместо перетаскивания webm останавливается / воспроизводится, будто кнопка play находится над всем окном.

**Comment by XakepSDK** [comment]
https://puu.sh/zJA4c/298f797447.png
Вот еще кнопка какая-то справа появилась, когда нажимаю - белая часть становится золотой.

**Comment by perdolka** [comment]
@XakepSDK
> Еще нельзя перетаскивать окно, 

Можно, но только за самый-самый верхний край. Прям нужно в пиксель рамки попасть курсором.

**Comment by SthephanShinkufag** [comment]
Как уже было сказано - все события наб webm/mp4 в Firefox 59 и выше не работают. Либо откатитесь до 58 лисы, либо используйте другой браузер.
Единственное, что можно (наверное) исправить - это автовоспроизведение вебм. Но этот баг я не могу повторить - всё работает. 

> кнопка какая-то

https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/wiki/versions

> * Новая фича: кнопка `"Автоматически воспроизводить следующее видео"` ([скриншот](https://user-images.githubusercontent.com/1059874/36074527-9c6b0b50-0f49-11e8-91af-791601a56371.png)). Когда кнопка активирована &mdash; по окончанию проигрывания текущего видео автоматически стартует следующее видео на странице, игнорируя картинки.

**Comment by XakepSDK** [comment]
Выключил ublock - автовоспроизведение заработало. Какая-то несовместимость =(
Фича классная, давно хотел такую.

**Comment by SthephanShinkufag** [comment]
> ublock

Из-за него в кукле много проблем, полно issue уже было написано про совместимость с этой дичью.

**Comment by SthephanShinkufag** [comment]
@XakepSDK 

Можно увеличить рамку вокруг, чтобы тягать за неё.
Скачиваете *разрабатываемую* версию с https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/wiki/versions

Открываете `"Настройки"` > `"Общее"` > Включаете галочку `"Пользовательский CSS"`, нажимаете кнопку `"Правка"`. В окно редактирования вводите 

```css
.de-fullimg-center {
    border: 10px solid #444 !important;
}
```

нажимаете `"Сохранить"`.

**Comment by SthephanShinkufag** [comment]
Если рамка в 10 пикселей слишком узкая, можно убрать по бокам и снизу, чтобы не мешали, а сделать шапку сверху потолще, как в окошке `"Настроек"` или `"Избранного"` например:

Вот css-код

```css
.de-fullimg-center {
    border-top: 20px solid #444 !important;
    border-radius: 10px 10px 0 0;
}
```

Алсо, добавил на страничку с CSS-трюкми https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/wiki/CSS-tricks

**Comment by XakepSDK** [comment]
https://puu.sh/zJClh/32d3b04e63.png
Нужно исправить еще вот это

**Comment by SthephanShinkufag** [comment]
@XakepSDK 

Теперь окно `"Настройки"`, если оно не откреплено, показывается всегда над всеми элементами.

**Comment by NEONZARIN** [comment]
Я конечно извиняюсь. раз уж в 59 лисе СДЕЛОЛИ такое сраное управление HTML5 видосами,  нельзя ли сделать управление видео средствами куклы? Горячими клавишами. Перемотка видео вперед/назад, Стоп/пауза. Ну или наэкранными кнопками как то эти же функции.

**Comment by Y0ba** [comment]
Можно. Если убрать встроенные контролы и заменить своими собственными, то перемещение и закрытие видео возвращается в норму (как было до 59 лисы).

**Comment by NEONZARIN** [comment]
А как это сделать?

**Comment by Y0ba** [comment]
Написать логику для контролов в кукле как минимум. А вообще контролы можно полностью выключить в настройках.
![_](https://user-images.githubusercontent.com/1163958/37561607-c72d390a-2a63-11e8-815a-a1be3528c25f.PNG)

**Comment by NEONZARIN** [comment]
Ага, это то же *Скрыть пульт управления*. Ясно, да.

**Comment by artemsmikh** [comment]
Люблю Лису, никогда не было проблем, и вот опять.
@SthephanShinkufag можно ли для варианта [отсюда](https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/issues/1194#issuecomment-373930677) перенести кнопку закрытия на саму верхнюю рамку, направо? Чтобы было как в окне настроек куклы.

**Comment by Malomalsky** [comment]
Подписываюсь под проблемой.

**Comment by SthephanShinkufag** [comment]
@artemsmikh 

```css
.de-fullimg-center {
    border-top: 20px solid #444 !important;
    border-radius: 10px 10px 0 0;
    cursor: pointer;
}

.de-fullimg-video::before {
    content: "✖";
    right: 6px;
    top: -20px;
}
```

**Comment by SthephanShinkufag** [comment]
CSS выше добавлял перетаскиваемый хедер ко всему, в том числе и к обычным картинкам, которым он не нужен.
Короче, я реализовал идею с хедером в самом скрипте. 
Теперь с последним коммитом для Firefox > 59 над вебмками, раскрытыми по центру появляется шапка, за которую можно тягать.

**Comment by XakepSDK** [comment]
А это ошибка или так и должно быть? А то не нашёл в багтрекере мозиллы бага на эту тему. Плохо искал, скорее всего.

**Comment by SthephanShinkufag** [comment]
@XakepSDK 

Если элемент `<video>` имеет атрибут `controls` (отображение контрол-бара), то начиная с Firefox 59 , на таких элементах не отрабатывают события `onclick`. Что там в багртекере, хуй его знает.

**Comment by SthephanShinkufag** [comment]
Хотя, так было раньше. по карйней мере. Сейчас посмотрю, может действительно в скрипте что-то, мало ли.

**Comment by XakepSDK** [comment]
Я когда смотрел в багтрекере, там было несколько проблем, связанных с этими самыми элементами управления. Например, на каком-то сайте, при нажатии ПКМ на видео, оно останавливалась.
Наверное снова залили какую-то хуйню в релиз, нормально не протестировав.

**Comment by anon1223231** [comment]
Степан, приделай тогда кнопку закрытия видоса, что ли.

**Comment by ImoutoChan** [comment]
Если честно, не самое удобное решение. Можно ли к middle button приделать toggle опции отображения контролов? 

А то сейчас приходится сначала двигать/ресайзить, а потом кликать правой кнопкой и включать контролы, чтоб длительно посмотреть или перемотать. За заголовок совсем неудобно.

**Comment by ganego** [comment]
I just tried FF Quantum and this is very annoying - I switched back to old FF.  
So Dollchan cannot do anything here?  
Is there a bugreport regarding this on Bugzilla? Because Vivaldi for example behaves differently.

**Comment by Y0ba** [comment]
@ganego 
Such behavior conforms standard; it's actually vivaldi does wrong thing here.

We should make our own controls for videos to reintroduce this feature.

**Comment by SthephanShinkufag** [comment]
My congratulations! This bug is fixed!
Now the player works as before.

**Comment by XakepSDK** [comment]
Кайф! Наконец-то.

Меню с кнопками появляется только если переместить мышь в его зону. Так и должно быть?
Т.е. оно появляется если переместить мышь в зону, где должно отображаться это меню.

**Comment by SthephanShinkufag** [comment]
@XakepSDK 
Да. Хорошо, что хоть так. Могу вернуть как было)))))))

**Comment by SthephanShinkufag** [comment]
Могу сделать опцию, чтобы в Quantum'е можно было выбрать между
а) предыдущей баго-фичей с перетягиванием за шапку с паузой по клику на видео, контролы появляются по наведению на любую область видео.
б) теперешним перетягиванием за видео с закрытием по клику на видео, контролы появляются по наведению на область контрола внизу.

**Comment by XakepSDK** [comment]
Мне и так норм. Спасибо за фикс.

**Comment by XakepSDK** [comment]
Поворот видео всё ломает

**Comment by SthephanShinkufag** [comment]
Исправил поворот видео в Firefox Quantum.
