### ISSUE TITLE
Картинки размазывает шопиздец

### ISSUE THREAD

**Issue by Turbolalka9000** [SthephanShinkufag/Dollchan-Extension-Tools#1196]
Было уже вроде, да не могу найти. По проблеме: есть шанс на любой борде словить сплюснутую по вертикали пикчу, просто перезагрузка страницы не помогает, только с отключением куклы, появляется при включенной опции "Умещать большие картинки в экран" и вроде даже без неё.
Вроде чаще всего появляется при быстром переключении на следующую и вангую что-то связанное с подгоном всех картинок под первую загрузившуюся или типа того.
v18.2.19.0.7d74ff9.es6 хромоаддон

**Comment by SthephanShinkufag** [comment]
Если найдёте такую картинку, покажите мне скриншот развёрнутой картинки и поста, в котором она содержится, и укажите здесь ссылку на пост в треде.

**Comment by Rolfeg** [comment]
Такое в основном на фото проявляется, но пару раз попадалось и у скриншотов.
Пример - https://2ch.hk/hw/res/2752655.html#2774277 - 2 вертикальные картинки шакалит в квадрат с переворотом.
![default](https://user-images.githubusercontent.com/31603013/37561191-964b4dae-2a59-11e8-94c1-a2c57caa06fe.jpg)

**Comment by SthephanShinkufag** [comment]
Это фича, Dollchan автоматически переворачивает фотки, если они повёрнуты.
Баг в тому, що при этом не меняются ширина и высота местами, видимо, я недавно где-то сломал.

**Comment by SthephanShinkufag** [comment]
Проблема в коммите 82ff8e3e6217e0b5000f20f334f5a5b6f0d0006b, буду завтра посмотреть.

**Comment by Remu-rin** [comment]
> Было уже вроде, да не могу найти.

Тут писал: https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/issues/1126#issuecomment-342459866

> просто перезагрузка страницы не помогает

Мне помогает.

> Если найдёте такую картинку, покажите мне скриншот развёрнутой картинки и поста, в котором она содержится, и укажите здесь ссылку на пост в треде.

Я наконец нашёл, что провоцирует. Например http://410chan.org/b/res/127845.html
В ОП-посте картинка 2.66MB, и далее несколько подобных. Если открыть пикчу и закрыть её до полного скачивания, а потом открыть после завершения, то она будет сплющенной. Поэтому человек выше пишет, что чаще с фотками, они нередко больше обычных пикч весят. Если у вас слишком быстрый интернет, поищите пожирнее пикчи. Пример выше с мышью у меня тоже работает.
![-1](https://user-images.githubusercontent.com/28995228/37561285-a788a09a-2a6c-11e8-887a-1a03a43ea7c3.png)

**Comment by Remu-rin** [comment]
> Проблема в коммите 82ff8e3, буду завтра посмотреть.

Да, подтверждаю. Но кое-что выяснилось. До этого коммита тоже была проблема с закрытием до скачивания и раскрытием после, но проявлялась она менее проблемно: пропорции не искажались, просто пикча раскрывалась вылезая за пределы экрана, несмотря на опцию "Умещать большие картинки в экран". И тогда было достаточно уменьшить пикчу вручную. Хоть она и не достигала ровно размера экрана (шаг масшабирования большеват), но терпимо.
![-2](https://user-images.githubusercontent.com/28995228/37561425-069c07ae-2a70-11e8-8502-72e018e6a3d2.png)
А после того коммита стала вмещаться в экран ценой искажения пропорций.

**Comment by SthephanShinkufag** [comment]
Не спится, однако. Починил, вроде.
Проверяйте по-всякому, может ещё где чего.

**Comment by NEONZARIN** [comment]
Эта проблема уже давненько так. месяц так точно.

**Comment by Remu-rin** [comment]
Спасибо, вернулось к прежнему поведению с вылезанием за экран, которое описал выше. Не идеально, но так всяко лучше.

**Comment by Rolfeg** [comment]
Спасибо, вроде нормально.

**Comment by SthephanShinkufag** [comment]
> вернулось к прежнему поведению с вылезанием за экран

Тому що картинки масштабируются в экран ДО переворачивания. Надо делать после.

**Comment by SthephanShinkufag** [comment]
@Remu-rin 

Сейчас вылезают за экран только картинки, которые *загружаются в первый раз* и переворачиваются . Если второй раз открыть эту же картинку, то она уже отображается перевёрнутой и умещённой в экран.

**Comment by Remu-rin** [comment]
@SthephanShinkufag 
Нет, я же говорю, что при закрытии до завершения скачивания и раскрытии после завершения вылезают и обычные пикчи, если они больше окна (а точнее высота, вроде). И второе открытие не спасает, она и дальше так раскрывается из кеша, пока не перезагрузить страницу. Вот после перезагрузки уже норм. Или если при первом открытии и скачивании не закрывать пикчу, а дождаться завершения скачивания, она тоже будет нормальной.
Повторяю шаги.
1. Загружаем страницу без кеша.
2. Открываем пикчу и закрываем её до того как она догрузится.
3. Ждём окончания загрузки, потом снова открываем её.

С моим черепашьим инетом я могу воспроизвести даже с ОП-пиком этого треда https://2ch.hk/s/res/2240583.html (83Кб, 539x960). При условии, что уменьшу высоту окна лисы до размера меньше высоты пикчи.
![-2](https://user-images.githubusercontent.com/28995228/37561968-669dc10c-2a7e-11e8-9141-387b8ba26392.png)

С большими пикчами горизонтального/квадратного соотношения сторон не выходит. Нужна вертикальная.
Попробуй с этими пикчами https://iichan.hk/hr/res/4447.html#5192, 5083, 5381.
Как вариант, забей входящий канал скоростной закачкой, если слишком быстрый инет.

**Comment by SthephanShinkufag** [comment]
@Remu-rin 

В скрипте было условие, определяющее повёрнута ли картинка или нет:

```js
const isRotated = img.scrollHeight / img.scrollWidth > 1 ? ar < 1 : ar > 1;
```

Фишка в том, что если закрыть картинку раньше, чем она загрузится - она загружалась в фоне и имела нулевой scroll размер `img.scrollHeight === img.scrollWidth === 0`.
Я отключил определение повёрнутых картинок, если они были закрыты раньше чем загружены.
Обычно расположенные картинки теперь будут в дальнейшем разворачиваться корректно, если их рано закрыть.

Проверяйте.

**Comment by Remu-rin** [comment]
Спасибо! Теперь всё нормально.
