### ISSUE TITLE
Кукла в хроме не тянет *большие треды*

### ISSUE THREAD

**Issue by NEONZARIN** [SthephanShinkufag/Dollchan-Extension-Tools#1197]
Не знаю как правильно сформулировать. Напишу как есть.
Беру чистый хром устанавливаю куклу и захожу в тред с 2500 постами. Видно что страница загружается примерно до 2300 постов и вкладка виснет наглухо. Выгдят так как вроде кукла не переваривает жирные треды. И так постоянно при открытии перезагрузке таких вот больших тредов. С обычными тредами до 1к - 2к постов которые такого не наблюдается.

С чистой лисой таких проблем с зависанием нет начиная с 58 версии. Страничка загружается в течении ~28 секунд, без зависаний без таких проблем как в хроме.

**Comment by Y0ba** [comment]
Интересно было бы посмотреть выхлоп профайлера. Можешь сделать? Гугли "chrome javascript cpu profiler" там будет написано как это сделать.

**Comment by SthephanShinkufag** [comment]
А у вас предзагрузка картинок в настройках случайно не включена? Она очень прожорлива.
С дефолтными настройками пробовали загружать?

**Comment by NEONZARIN** [comment]
Настройки дефолтные, кукла и маркета хрома, пробовал последнюю версию при помощи виолентманкей все равно зависает. Предзагрузка картинок не включена. Выхлоп профайлера сегодня сделаю.

**Comment by NEONZARIN** [comment]
![default](https://user-images.githubusercontent.com/16442992/37562222-32da9016-2a74-11e8-9fe1-4fdaefb634b8.png)
На графике внизу это без куклы. С куклой  постоянно висит вот так как на скрине. Или нужно сам файл выхлопа? Как его тогда получить если оно висит?

**Comment by NEONZARIN** [comment]
[Profile-20180318T062949.zip](https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/files/1822322/Profile-20180318T062949.zip)
Вот. 4 минуты висит. Рендерило чет собака.

**Comment by Y0ba** [comment]
Забавно. Проблема в CSS. Какой-то селектор куклы занимает кучу времени в крупных тредах. JS в профиле почти не видно.

**Comment by Y0ba** [comment]
Или не CSS. Больше всего времени занимает обновление стилей, которое триггерится при вызове функции `$script`. Странно это.

**Comment by NEONZARIN** [comment]
Собственно именно поэтому я и ушел с хрома на лису. Я вообще думал что это у меня **моя пекарня не тянет** большие треды. А в лисе  все норм оказалось.
Для сравнения загрузка такого вот треда 2500 постов **без куклы** что в лисе с 58 что  в хроме/его форках последних версий ~18 секунд. С куклой лиса 58 ~28 секунд, хром соответственно висит наглухо.

**Comment by NEONZARIN** [comment]
Хех, Violentmonkey + https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/raw/master/src/Dollchan_Extension_Tools.es6.user.js загрузка _быстрее_  3.4 min. Инструмент профилирования или как его там не зависал и показывал сколько времени оно там загружается.
[Profile-20180318T070126.zip](https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/files/1822340/Profile-20180318T070126.zip)

**Comment by NEONZARIN** [comment]
Это вот это типо?
![default](https://user-images.githubusercontent.com/16442992/37562503-23d3d90e-2a7b-11e8-8f48-1ec74a2ce3c8.png)

**Comment by Y0ba** [comment]
В лисе, кстати, тоже профайлер показывает около 50% времени инициализации тратится на обработку стилей. Просто лиса делает это быстрее.

**Comment by NEONZARIN** [comment]
28 секунд всего...

**Comment by Y0ba** [comment]
Как я и предполагал, всё это из-за CSS счётчиков постов. Видимо придётся переписать их на JS. Всяко быстрее будет.

**Comment by Y0ba** [comment]
Можешь попробовать найти в скрипте `.de-post-counter::after { counter-increment: de-cnt 1; content: counter(de-cnt); color: #4f7942; }` и заменить на `/* .de-post-counter::after { counter-increment: de-cnt 1; content: counter(de-cnt); color: #4f7942; } */`. Тогда скрипт срабатывает мгновенно с единственной потерей функционала: счётчика постов.

**Comment by NEONZARIN** [comment]
А как/чем правильно редактировать? Пробовал notepad/Editplus при любом изменении скрипта он потом не пашет.

**Comment by Y0ba** [comment]
Если установлено как расширение - то никак. А так можно в *манки встроенным редактором.

**Comment by NEONZARIN** [comment]
Ну нифига себе! **ПРЯМО КАК В ЛИСЕ 29 СЕКУНД СТАЛО.** Никаких фризов, ничего.
[Profile-20180318T074912.zip](https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/files/1822355/Profile-20180318T074912.zip)
Во, теперь и можно на хром обратно вернутся.

**Comment by NEONZARIN** [comment]
В лисе вот опять проверил секундомером на смарте (не разобрался в лисьем профайлере где так же в сендах глянуть) - 28 секунд.
Так а почему именно в хроме такой баг со счетчиком постов?

**Comment by Y0ba** [comment]
Просто правило `counter` недостаточно оптимизировано и в больших тредах начинает сильно глючить. В лисе там же недавно крутой многопоточный css-движок встроили написанный на расте, вот он эту фигню без проблем и переваривает.

**Comment by NEONZARIN** [comment]
Я бы даже сказал он ее игнорирует. Т.к я и в лисе закоментировал эту строчку счетчика. Изменений по времени загрузки не видно.

**Comment by Y0ba** [comment]
Не игнорирует, просто выполняется настолько быстро, что не заметно на глаз.

**Comment by SthephanShinkufag** [comment]
Круто! Я знал, что у хрома были проблемы с css-движком, но это вообще аллес.
А счётчик постов на JS не замедлит лису? Нужно будет делать ветвление - для хрома счётчик на JS, а для лисы оставить как есть.

**Comment by Y0ba** [comment]
Не замедлит (там всего-то подредактировать html, который и так вставляется в dom). Там самое сложное будет - обновление счётчика после удаления постов. С CSS это делается автоматом.

**Comment by SthephanShinkufag** [comment]
Готово. Счётчик постов теперь расставляется посредством JavaScript.
Учёт при удалении постов и при автоподгрузке тредов с удалёнными постами, отображение в превью, всё работает.

**Comment by NEONZARIN** [comment]
Очень интересно теперь стало!
Хром - тред 2630 постов полная загрузка страницы до ~50 секунд.  Без полных зависаний как раньше.
Лиса - тред 2630 постов полная загрузка страницы ~42 секунды.
В общем кукла на лисе в больших тредах работает быстрее на ~5 секунд. 
Да, и ещё у меня при этом включен ublock который снижает загрузку тредов на 4 секунды в обоих браузерах одинаково. Без него соответственно загрузка на 4 секунды быстрее.
