### ISSUE TITLE
Навигация постов по ссылкам не сохраняются настройки.

### ISSUE THREAD

**Issue by NEONZARIN** [SthephanShinkufag/Dollchan-Extension-Tools#1198]
![image](https://user-images.githubusercontent.com/16442992/37573880-6e8f2d42-2b2d-11e8-8963-ad48a7b584b5.png)
Выставляю 80 через некоторые время после открытия новых тредов визуально видно что настройка стала по умолчанию 100. И собственно оно в настройках так и отображается как на скрине. Версия куклы последняя, хром.
При каких условиях кукла в дефолт эту настройку делает пока не заметил.
Или оно так делает из за закоментирования мной этой строки? _.de-post-counter::after { counter-increment: de-cnt 1; content: counter(de-cnt); color: #4f7942; }_ Так вроде пока сегодня куклу не обновил и не было такой проблемы.

**Comment by SthephanShinkufag** [comment]
Всё работает.

1. Я не знаю, какая у вас версия коммита, поставьте последний:

https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/raw/master/src/Dollchan_Extension_Tools.es6.user.js

2. Попробуйте проследить другие опции с текстовіми полями, например "Апдейтер тредов [ ] (сек)", они тоже сбрасываются?

**Comment by NEONZARIN** [comment]
Перепроверил. Сбрасывается при закоментировании этой строки .de-post-counter::after { counter-increment: de-cnt 1; content: counter(de-cnt); color: #4f7942; }. Так что это не баг.

**Comment by NEONZARIN** [comment]
Проблема имеет место быть. Какие бы значения не ставил хоть 80 хоть. Периодически эта настройка отваливается. Из-за чего это я не обнаружил. В лисе же такого не наблюдается вообще. Может возможно как то это отследить, почему так происходит?

**Comment by NEONZARIN** [comment]
Вот нашел таки когда отваливается. Открываю первый тред, по всему посту активно скролю по постам - ничего не отваливается. После открытия ещё 4 тредов в первом треде как раз и отваливается нахрен. В остальных 4 открытых ничего не отваливается.

**Comment by NEONZARIN** [comment]
[bandicam 2018-03-23 10-12-53-732.zip](https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/files/1840523/bandicam.2018-03-23.10-12-53-732.zip)

**Comment by NEONZARIN** [comment]
Такс. Выключил все расширения вообще. Включено только Violentmonkey и сам скрипт куклы.
Открываю первый тред, +4 и больше на остальных страницах. Скролю все треды, хожу по постам  посты создаю. Перехожу на первый открыйтый тред и там после  энного перехода по ссылкам постов отваливается все это дело. Это что опять дело в счетчике постов?
Как его в последней версии куклы отключить? Интересно без него эта проблема исчезнет?

**Comment by SthephanShinkufag** [comment]
Что отваливается? Вы про что вообще?

**Comment by NEONZARIN** [comment]
Вот именно эта настройка.
![image](https://user-images.githubusercontent.com/16442992/37818274-aaadfaf0-2e8a-11e8-8314-6d5f111ce3ce.png)

**Comment by SthephanShinkufag** [comment]
При чём тут вообще счётчик постов?

**Comment by NEONZARIN** [comment]
Может и не причем.

**Comment by Y0ba** [comment]
Это рассинхронизация настроек между вкладками. Известный баг. Если изменить настройки в одной вкладке, то они могут быть сброшены если сохранить настройки (или что-то другое) в другой вкладке.

Единственный способ это решить - сделать синхронизацию настроек при помощи localStorage. Некоторые настройки уже синхронизируются, можно просто добавить и эту.

**Comment by NEONZARIN** [comment]
Настройки я вообще не изменяю в кукле при этом. 
Можно поподробнее как запилить эту синхронизацию?

**Comment by NEONZARIN** [comment]
```
"permissions": [
"storage"
]
```
Оно?

**Comment by SthephanShinkufag** [comment]
@NEONZARIN 

Никуда не лезьте, синхронизацию нужно реализовывать в скрипте, писать код.
Посмотрите лучше, не сбрасываются ли другие опции. Измените, например, время апдейтера  тредов на другое. И проследите, будет ли сбрасываться.

**Comment by SthephanShinkufag** [comment]
Йоба починил гонку между вкладками, #1453
Думаю, issue можно закрыть.
