### ISSUE TITLE
Не работает при предпросмотре поста кнопка  *добавить тред в избранное*

### ISSUE THREAD

**Issue by NEONZARIN** [SthephanShinkufag/Dollchan-Extension-Tools#1199]
Хром, и в лисе тоже неправильно работает эта кнопка. На последней версии куклы.
![image](https://user-images.githubusercontent.com/16442992/37829026-832705de-2eae-11e8-9c35-4ae0ab545b40.png)

**Comment by SthephanShinkufag** [comment]
Всё работает.
Опишите, с какого поста/треда доски не добавляется.
Что пишет в косноли ошибок (Ctrl+Shift+J) при нажатии.

**Comment by NEONZARIN** [comment]
https://2ch.hk/a/res/4999830.html#5001725
Хром в консоли когда нажимаю ничего не пишет. В лисе специально перед обновлением до последней версии потыкал все работало, обновил и перестало.

**Comment by NEONZARIN** [comment]
А точнее при предпросмотре в избранное добавляется теперь, а при повторном клике не убирается из избранного.

**Comment by NEONZARIN** [comment]
И вот ещё не отображается курсор в поле ввода горячей клавиши.
![default](https://user-images.githubusercontent.com/16442992/37830082-7812ac80-2eb2-11e8-855e-dee9fdd2672d.png)
Опять же в хроме. В той же лисе все нормально с этим.
Какая то нездоровая хрень происходит с куклой в хроме.

**Comment by NEONZARIN** [comment]
![default](https://user-images.githubusercontent.com/16442992/37830210-cb953648-2eb2-11e8-82f8-82824937d379.png)
Вот например в лисе все работает.

**Comment by NEONZARIN** [comment]
Вот видео на всякий случай.
Хром
[bandicam 2018-03-23 15-58-10-911.zip](https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/files/1841552/bandicam.2018-03-23.15-58-10-911.zip)

Лиса
[bandicam 2018-03-23 16-00-25-562.zip](https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/files/1841553/bandicam.2018-03-23.16-00-25-562.zip)

**Comment by SthephanShinkufag** [comment]
Исправлена установка стороннего избранного треда из превью.

**Comment by SthephanShinkufag** [comment]
Насчёт курсора в хроме.
Чисто теоретически, хром ведёт себя логично, тому що поля эти имеют атрибут readonly и соответственно не имеют возможность ввода.
А лиса, из-за своей особенности, курсор отображает даже в readonly полях.
Нужно написать свою выделялку текущего поля, чтобы не зависеть от курсора.

**Comment by SthephanShinkufag** [comment]
Теперь выбранное поле в редакторе хоткеев помечается желтоватым фоном.

**Comment by NEONZARIN** [comment]
Так теперь даже лучше выглядит.
