### ISSUE TITLE
[2ch.hk]: /d/ и /test/ - не видно тредов, ошибка инициализации

### ISSUE THREAD

**Issue by anon1223231** [SthephanShinkufag/Dollchan-Extension-Tools#1202]
![screenshot-2018-3-25 d -](https://user-images.githubusercontent.com/33400229/37877746-3fcdcbcc-3068-11e8-94f7-40b978b1fbee.png)

Собственно, сабж. Если включить скрипт, всё работает.

**Comment by NEONZARIN** [comment]
Уже второй день подряд. Я не стал создать про это.

**Comment by NEONZARIN** [comment]
И в тестовом разделе тоже кукла не работает вроде.

**Comment by SthephanShinkufag** [comment]
/test не работает уже где-то год или больше.
Там очень многие классы отличаются от классов на других досках, в скрипте пололовину переменных инициализации для макабы придётся подгонять. А ради чего, ради какого-то /test
Про /d не знал, видимо из /test туда шаблон перенесли.

**Comment by Dezaimasu** [comment]
Клятая обезьяна кажется перетащила эту(?) чуму и в /b/.


![screenshot_2018-05-12 b -](https://user-images.githubusercontent.com/1636242/39956916-59b0b07c-55f2-11e8-8f2d-cc3a22ea2ba9.jpg)

**Comment by SthephanShinkufag** [comment]
@Dezaimasu

Предлагаю не спешить с фиксом.
https://dscript.me/de/res/1.html#27

**Comment by SthephanShinkufag** [comment]
Итак, учитывая, что Абу в любой момент может применить тестовый движок на постоянной основе &mdash; я зойпилил его поддержку.
