### ISSUE TITLE
[2ch.hk]: Отправка жалоб через ajax

### ISSUE THREAD

**Issue by XakepSDK** [SthephanShinkufag/Dollchan-Extension-Tools#1203]
Отправка жалобы обновляет всю страницу, это неудобно.

**Comment by Remu-rin** [comment]
Ещё модератор однажды говорил, что с куклой репорты приходят без указания конкретных постов, в то время как без куклы в репорте содержатся список постов, выделенных чекбоксом.

**Comment by SthephanShinkufag** [comment]
@Remu-rin 

Есть такой issue &mdash; #1096

**Comment by SthephanShinkufag** [comment]
Теперь Dollchan добавляет свою кнопку репорта к постам.
Насчёт поля жалобы внизу страницы на досках со старым движком, я посмотрю потом.

**Comment by SthephanShinkufag** [comment]
> Насчёт поля жалобы внизу страницы на досках со старым движком, я посмотрю потом.

Уже неактуально.
