### ISSUE TITLE
[TinyIB] Кнопки разметки

### ISSUE THREAD

**Issue by VVatashi** [SthephanShinkufag/Dollchan-Extension-Tools#1205]
В TinyIB из коробки отсутствует какая-либо разметка текста постов, но скрипт всё равно отображает соответствующий блок кнопок на форме постинга. Можно для TinyIB их как-то отключить совсем или хотя бы по-умолчанию?

**Comment by SthephanShinkufag** [comment]
Настройки - Форма - [Откл.] Кнопки разметки текста

**Comment by VVatashi** [comment]
@SthephanShinkufag 
Да, я знаю об этой настройке, но у меня есть доска на TinyIB, где для некоторых не слишком технически подкованных людей, вероятно, даже просто настроить скрипт может быть проблемой. Так что, если это не сложно, хотелось бы всё-таки видеть такую настройку скрипта для данного движка по-умолчанию.
Собственно, для своей доски я это уже исправила. Но данное поведение скрипта, с показом кнопок, которые вставляют разметку, которая не работает, мне всё же кажется недоработкой именно скрипта.

**Comment by SthephanShinkufag** [comment]
У меня есть своя тестовая борда на TinyIB, я не поленился, и реализовал там разметку.
На некоторых других TinyIB-форках я тоже её видел.

**Comment by SthephanShinkufag** [comment]
Я тут подумал. всё-таки обычный TinyIB искаробки не имеет разметки, будет таки правильно убрать кнопки по умолчанию. Только учтите, это будет дейстоввать только на вновь прибывших юзверей. у всех тех, кто уже посетил вашу борду и тем самым проинициализировал скрипт, кнопки придётся отключать вручную.
А для своей борды я в скрипте потом добавлю исключение, там bbCode, и его всё равно надо будет явно указывать в инициализации.

**Comment by VVatashi** [comment]
Ну, вот о чём я и толкую. Спасибо.
