### ISSUE TITLE
[2ch.hk]: Сделать окошко капчи большего масштаба

### ISSUE THREAD

**Issue by NEONZARIN** [SthephanShinkufag/Dollchan-Extension-Tools#1207]
Сделать окошко капчи большего масштаба для удобства, а то много времени уходит на ее разгадывание при таком нынешнем масштабе.
![image](https://user-images.githubusercontent.com/16442992/38131631-7f215572-3410-11e8-8475-82fb0cc94447.png)
Первый скриншот(из /d/) пример того как должно по моему выглядеть окно капчи. 

Или возможно сделать как я на этой картинке запилил увеличение картинки с капчей когда тянуть за уголок.
![image](https://user-images.githubusercontent.com/16442992/38131839-393a0e0e-3411-11e8-9a84-8fb08b87919b.png)

Но удобнее будет как мне кажется на первом скриншоте показано.

**Comment by NEONZARIN** [comment]
Еще один реквест.
Не отображать вообще скрытые посты. В постах. Как на скрине. Что бы там их вообще не было.
А еще лучше было бы сделать полное скрытие скрытых постов в треде. Зря место только занимают.
![image](https://user-images.githubusercontent.com/16442992/38792287-f1774946-4154-11e8-856d-dd255acb73ca.png)
И эту фичу в настройки сделать _вкл/выкл_.

**Comment by NEONZARIN** [comment]
Кстати спасибо. Теперь можно срать не снимая свитер.
![image](https://user-images.githubusercontent.com/16442992/38833401-1494b64c-41ce-11e8-9698-e67a7eed9e3e.png)

**Comment by SthephanShinkufag** [comment]
@NEONZARIN 

> Не отображать вообще скрытые посты. В постах. Как на скрине. Что бы там их вообще не было.
А еще лучше было бы сделать полное скрытие скрытых постов в треде.

`"Настройки"` - `"Ссылки"` - `"Не отображать превью для скрытых постов"`
`"Настройки"` - `"Фильтры"` - `"Скрывать ответы на скрытые посты"`

**Comment by SthephanShinkufag** [comment]
Сделал капчу больше. Для экономии места обрезал 45 пикселей картинки капчи сверху, и сместил поле ввода капчи вверх. Пикрелейтед:

![2chhk_bigger_captcha](https://user-images.githubusercontent.com/1059874/39450421-f64454f2-4cd3-11e8-970c-b3ebb5d59ec6.png)

**Comment by NEONZARIN** [comment]
Хорошо сделол! Можно было еще и справа обрезать немножко для экономии, Долго щелкал капчу, дальше чем на скрине циферки не вылазили вправо.
![image](https://user-images.githubusercontent.com/16442992/39455269-4335f3a6-4ce8-11e8-8d9b-47797f44c921.png)
Но и так уже вполне себе нормально.

**Comment by SthephanShinkufag** [comment]
Обрезал.

**Comment by Remu-rin** [comment]
Спасибо, но она всё ещё немного уменьшается. Если применить `.captcha-box > img { width: unset; }` или убрать в девтулзах правило ширины чекбоксом, то видно увеличение. Там пикчи шириной 364, а не 350.
Алсо, я один не вижу эффекта margin-right из коммита выше? С любым значением.

**Comment by NEONZARIN** [comment]
Тоже не вижу эффекта. Но и так норм.

**Comment by SthephanShinkufag** [comment]
Может, тому що вы хромоги? Я хром редко запускаю.

**Comment by SthephanShinkufag** [comment]
А, нет, и в хроме всё работает. Не вижу проблемы.

**Comment by SthephanShinkufag** [comment]
Вот теперече дольжно быть норм. Задал пикче явные 364px, корректно обрезал правый бок..
