### ISSUE TITLE
[Chrome]: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by Xowk** [SthephanShinkufag/Dollchan-Extension-Tools#1208]
Тут это, на сосаке постоянно какие-то ошибки вылазят и при отправлении постов, новые перестают подгружаться, пока страницу не обновишь. Свои посты после этого тоже перестают отправляться, пишет мол капча инвалидна, хотя набрать её не предлагают. Историю очищал, но что-то не помогло. Уже несколько дней такая байда, но судя по тому что никто на это не жалуется, видимо только у меня такое счастье. Как починить?
![2018-03-30_205347](https://user-images.githubusercontent.com/25745393/38148406-186b56d0-345f-11e8-8824-9461c4b9c0df.jpg)

**Comment by SthephanShinkufag** [comment]
Отключите abBlock, uBlock, или что там за блокироващик у вас.

**Comment by Xowk** [comment]
Отключил, но ничего не изменилось.

**Comment by SthephanShinkufag** [comment]
Что за браузер? Как установлен скрипт?

**Comment by SthephanShinkufag** [comment]
Попробуйте установить разрабатываемую версию скрипта по ссылке https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/wiki/versions

**Comment by Xowk** [comment]
Хром обычный. Версия 65.0.3325.181 (Официальная сборка), (64 бит). Разрабатываемая версия скрипта тоже не помогла. Так же как и отключение всех расширений кроме куклы. Настройки в макабе тоже ковырял, пробуя убирать всё в минимум, но так же безрезультатно. До недавнего времени таких проблем если что никогда не было. Годами сидел на хроме с куклой и всё было ок. Но потом макак что-то у себя докрутил и жизнь кончилась.

**Comment by Xowk** [comment]
Я сейчас сбросил настройки в самой кукле и всё чудесным образом заработало. Я видимо у мамы не слишком умный и мне это почему-то раньше в голову не приходило. Простите за отнятое время. Если это ещё имеет значение, до сброса отладка выглядела так:

{
	"version": "18.4.26.0.77a1f59",
	"location": "https://2ch.hk/a/res/5134862.html",
	"nav": {
		"ua": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36",
		"scriptHandler": "Violentmonkey 2.9.4",
		"isESNext": true,
		"isFirefox": false,
		"firefoxVer": 0,
		"isWebkit": true,
		"isChrome": true,
		"isSafari": false,
		"isPresto": false,
		"isMsEdge": false,
		"isGM": true,
		"isNewGM": false,
		"isChromeStorage": false,
		"isScriptStorage": false,
		"isGlobal": true,
		"hasGMXHR": true,
		"canPlayMP3": true,
		"hasTemplate": true,
		"hasWorker": false
	},
	"Cfg": {
		"timePattern": "dd+nn+yy+w+hh+ii+ss",
		"addVocaroo": 0,
		"hideBySpell": 0,
		"cfgTab": "info",
		"hideReplies": 1,
		"expandTrunc": 1,
		"widePosts": 1,
		"webmTitles": 1,
		"webmVolume": 86,
		"preLoadImgs": 1,
		"findImgFile": 1,
		"openImgs": 1,
		"linksOut": 150,
		"markViewed": 1,
		"decodeLinks": 1,
		"addImgs": 1,
		"YTubeTitles": 1,
		"removeFName": 1,
		"spacedQuote": 0,
		"saveSage": 0,
		"inftyScroll": 0,
		"scrUpdIntrv": 4,
		"textaWidth": 120,
		"textaHeight": 132,
		"updDollchan": 1
	},
	"sSpells": [
		"#wipe(samelines,samewords,longwords,symbols,numbers,whitespace)"
	],
	"perf": {
		"Imageboard check": 3,
		"Storage loading": 8,
		"Init": 4,
		"Read my posts": 0,
		"Replace delform": 7,
		"Parse delform": 9,
		"Parse postform": 73,
		"Init keybinds": 1,
		"Init page": 54,
		"Add panel": 2,
		"Init AJAX": 1,
		"Preload images": 6,
		"Audio links": 0,
		"Video links": 8,
		"Image names": 1,
		"Reflinks map": 3,
		"Apply CSS": 5,
		"Display page": 0,
		"Infinity scroll": 0,
		"Hide posts": 8,
		"Image-links": 0,
		"Scroll page": 0,
		"Всего": 193
	}
}

**Comment by SthephanShinkufag** [comment]
Спасибо вам за отладочную инфу, проблема оказалась в опциях "Предварительно загружать картинки*" и "Распознавать файлы, встроенные в картинках*".
Буду чинить.
