### ISSUE TITLE
[arhivach.org]: На /favs белая страница

### ISSUE THREAD

**Issue by perdolka** [SthephanShinkufag/Dollchan-Extension-Tools#1210]
Violentmonkey 2.9.0
FF 60.0b8 (x64)
Кукла 18.2.19.0.f588f8d

Не грузится страница https://arhivach.org/favs/
Точнее, загружается пустая белая страница.

Остальные страницы архивача грузятся нормально.

**Comment by SthephanShinkufag** [comment]
Азъ там не зарегистрирован. Зарегистрируюсь на фейкомыло, гляну.

**Comment by perdolka** [comment]
А архивач-то **ВСЁ** оказывается?
По адресу arhivach.org "сервер не найден".
Кто знает ситуацию?

**Comment by perdolka** [comment]
Новый адрес - arhivach.cf

**Comment by perdolka** [comment]
У меня такая идея, может просто запретить работу скрипта на страницах
http://arhivach.cf/my/
http://arhivach.cf/favs/
? 
Всё-равно на этих двух страницах кукла не нужна, это просто списки тредов.
