### ISSUE TITLE
please support chan.sankakucomplex.com it is a very good image gallery

### ISSUE THREAD

**Issue by cafrew** [SthephanShinkufag/Dollchan-Extension-Tools#1211]
thank you very much :+1:

**Comment by cafrew** [comment]
please consider make this plugin available at chan.sankakucomplex.com
:smiley:

**Comment by SthephanShinkufag** [comment]
Sorry, but Dollchan supports only 4chan-like imageboards type, with posts and threads.
Danbooru-like galleries are not related and not supported.
