### ISSUE TITLE
[2ch.hk]: Пост с пометкой "удален"

### ISSUE THREAD

**Issue by NEONZARIN** [SthephanShinkufag/Dollchan-Extension-Tools#1213]
Открыт постоянно один тред и там постоянно каждый день через энное количество постов появляется вот это:
![image](https://user-images.githubusercontent.com/16442992/38459707-f5b2d20a-3ab5-11e8-9722-98d645f348c1.png)
И это судя по всему не может быть именно по настоящему удалённый пост мочератором. Ибо он практически мгновенно становится с пометкой *удален*.

Наблюдается только в этом треде https://2ch.hk/a/res/5046409.html#5046409

**Comment by Y0ba** [comment]
@SthephanShinkufag такое бывает в прикреплённых "ПОСОВЕТУЙТЕ АНИМЕ ТРЕД" в https://2ch.hk/a/

Просто появляется довольно редко.
