### ISSUE TITLE
Плавающее окно с картинкой / видео

### ISSUE THREAD

**Issue by XakepSDK** [SthephanShinkufag/Dollchan-Extension-Tools#1215]
Пожалуйста, уменьши кликабельную зону до размеров коричневого прямоугольника с названием файла.
Скрин зоны: https://puu.sh/A4Frq/e5a5a89055.png (выделено синим)
Я постоянно промахиваюсь, когда закрываю картинку, из-за этого закрывается вкладка с тредом.
А еще было бы неплохо открывать картинку / видео в новом окне.

**Comment by lordnoobw** [comment]
Удваиваю. Алсо после последнего апдейта появилась полусекундная задержка перед открытием и закрытия пикчи. Это баг или фича? Очень раздражает.

**Comment by XakepSDK** [comment]
Чет за Степана беспокоюсь, давно не отвечал тут.

**Comment by SthephanShinkufag** [comment]
@XakepSDK 

> открывать картинку / видео в новом окне

Клик колесом мыши.

@lordnoobw 

Снимите видео, не вижу никаких задержек.

**Comment by lordnoobw** [comment]
Внезапно прошло само. てへ

**Comment by SthephanShinkufag** [comment]
@lordnoobw 

Вы случайно не это имели в виду? https://transfer.sh/Cf6te/2018_04_06_16_57_18_551.mp4
Этой проблемы уже нет, но я добавил исправление в последнем коммите.

**Comment by lordnoobw** [comment]
Таки нет, был именно полусекундный лаг перед открытием и закрытием.

**Comment by SthephanShinkufag** [comment]
Ладно, закрываю этот issue, создадите новый, если обнаружите эту проблему.

**Comment by SthephanShinkufag** [comment]
@XakepSDK 

С колесом картинка открывается в новой вкладке же.

**Comment by XakepSDK** [comment]
Так а если всё же случайно попал с ЛКМ?

**Comment by SthephanShinkufag** [comment]
@XakepSDK

Я вас не понимаю. Куда случайно попал?
Если вы имеете в виду основной issue, то он исправлен, есть [коммит](https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/issues/1215#ref-commit-f6f5fdf). Что вы имеете в виду?

**Comment by XakepSDK** [comment]
Я понял, что эта проблема решена, но всё же существует ненулевая вероятность того, что человек случайно нажмёт на плашку с названием и из-за этого закроется тред.
Раздражает не само закрытие треда, а закрытие дерева ответов из-за смены страницы, поэтому хотелось бы минимизировать эту случайность.

**Comment by SthephanShinkufag** [comment]
И что вы предлагаете?

**Comment by XakepSDK** [comment]
Открывать картинку / webm в новом окне.

**Comment by XakepSDK** [comment]
Прошу прощения.

**Comment by lordnoobw** [comment]
Опять появилась задержка при открытии/закрытии картинки. В видео курсор отвожу сразу после клика. https://puu.sh/AmEsJ.mp4

**Comment by lordnoobw** [comment]
Судя по всему возникает только в больших тредах. В видео тред с 700 постов, попробовал в треде с 80 постов, задержки нет.
