### ISSUE TITLE
Тред удаляется из Избранного при обновлении

### ISSUE THREAD

**Issue by Incurious** [SthephanShinkufag/Dollchan-Extension-Tools#1216]
Firefox59.0.2+violentmonkey+esnext версия Dollchan
Открыт тред, добавляю его в избранное по кнопке, дальше обновляю тред, и всё, треда в избранном нет
Ну и рилейтед проблемы с 8ch и не только, не всегда обновляются счётчики новых постов, и вообще эти 2 проблемы начались ещё вроде с того времени, как вы начали поддерживать greasemonkey 4.

**Comment by SthephanShinkufag** [comment]
У вас всегда открыто несколько вкладок с 8чаном? Всегда ли открыто окно с избранным в одной или нескольких вкладок? Какие вкладки с 8чаном открыты, и в каких открыты окна с избранным?
Закройте все вкладки, сохраните куда-нибудь ваше избранное. очистите его, и начистую напишите, как гарантированно добиться вашего бага.

**Comment by Incurious** [comment]
А фиг знает как повторить, несколько дней не мог поймать момент, вот прямо сейчас поймал.

(Сразу говорю, тут пропали не треды, а счётчик непрочитанных сообщений, и баг как мне кажется тот же)
Пошёл сразу на 8ch.net, пошёл потом на /v/ с главной, открыл список избранных тредов, из списка избранных тредов перешёл на доску /htg/, нажал кнопку обновления тредов, подождал пока всё обновится, перешёл в тред с новыми постами, открываю избранное, а там пропал счётчик новых постов. Обновил снова, перешёл уже в другой тред с непрочитанными постами, открыл избранное - та же картина, счётчик новых постов проебался. обновил, и он мне показал непрочитанные сообщения в том треде где я уже был, вернулся туда, а там те же сообщения.

Треды и доски открывались в одной вкладке.

**Comment by Rolfeg** [comment]
#1151

**Comment by Incurious** [comment]
До сих пор ловлю баг, и до сих пор не могу понять почему. Просто вот список избранных вот никак не меняется и всё.

**Comment by SthephanShinkufag** [comment]
Ни разу не ловил. Фиг знает.

**Comment by SthephanShinkufag** [comment]
Пока не получится воспроизвести баг - исправить его не выйдет.

**Comment by perdolka** [comment]
Не знаю, как это поможет, просто догадка - я уверен, что у всех, у кого возникал баг, было открыто **несколько** вкладок с бордой.

@Rolfeg
> Баг есть, как воспроизвести не знаю - появляется сам через 2-3 часа при любой открытой вкладке.
> #1151

Был и у меня такой запрос: #1168

**Comment by Incurious** [comment]
Короче, я там уже нарейджил в треде про то что баг пофикшен на грисманки, (во время введения поддержки которого этот баг и возник, ну по времени рядом), однако всё ещё присутствует на вайлент манки.

Есть подозрение, что баг возникает только после прошествия определённого количества времени, И самое главное, то что скрипт инициализируется на всех доменах делает ситуацию хуже.
Но это надо потестить с включением отключением вайлент манки. Или просто как нибудь ограничить работу скрипта до нужных мне доменов.

**Comment by SthephanShinkufag** [comment]
Duplicated issue => #1151
