### ISSUE TITLE
Опять поменяли капчу

### ISSUE THREAD

**Issue by proftwist** [SthephanShinkufag/Dollchan-Extension-Tools#1217]
Обезьяны из РКН испортили гуглокапчу и Абу опять поставил числовую. 
Обновление бы для Tapemonkey

**Comment by XakepSDK** [comment]
Настройки -> форма -> использовать альтернативную капчу.

Тикет сам закрой, Степан куда-то пропал.

**Comment by SthephanShinkufag** [comment]
![imback](https://user-images.githubusercontent.com/1059874/39270975-500b1a9a-48e0-11e8-8dc5-7b3efee2b117.jpg)

**Comment by SthephanShinkufag** [comment]
В больничке месяц лежал, не до скриптов было.

**Comment by XakepSDK** [comment]
Я как-то повалялся в больничке месяц, вышел правда оттуда уже не самым здоровым человеком. :cry:

**Comment by SthephanShinkufag** [comment]
@XakepSDK 

Та же фигня, друже... Полный аллес с этой медициной, чтоб её. Попадалово истиннное.

**Comment by XakepSDK** [comment]
Ну ты держись там. Что потерял-то? Я вот слух на одно ухо...

**Comment by SthephanShinkufag** [comment]
А я теперь на гормонах сижу. И чтобы не произошел *синдром отмены*, я должен их постоянно принимать. Снижение дозы до нуля займёт длительное время.

**Comment by NEONZARIN** [comment]
Эт самое. Ты няшный трапик чтоле?
![d3c6b26c-034b-4cbb-8f58-601e2c8c81de](https://user-images.githubusercontent.com/16442992/39275760-1c337a32-48ef-11e8-91d1-78238baedbf7.jpg)

**Comment by XakepSDK** [comment]
Ну ты там держись, даже не знаю, что хуже, слух на одно ухо или либидо.

**Comment by XakepSDK** [comment]
Да ладно, я сам чуть не помер из-за своей болезни, пол года ходил с жесточайшей болью в ухе. Теперь я одноухий бандит.

**Comment by SthephanShinkufag** [comment]
От моих гормонов наоборот волосатость на морде повышается. И постоянно жрать хочется.

**Comment by SthephanShinkufag** [comment]
Надо буде в бородо-тред на двощах заглянуть, борода реально растёт как на дрожжах.
Теперь Степан худощавый, и в зеркале себя не узнаёт.
Можно теперь покупать зауженные джинсы, вейп-машинку, и смело заявится в барбер-шоп.
