### ISSUE TITLE
[Chrome extension]: Не сохраняются изменения в настройках

### ISSUE THREAD

**Issue by DimoNline** [SthephanShinkufag/Dollchan-Extension-Tools#1220]
- Не сохраняются изменения в настройках после обновления страницы 

- Не меняются настройки при загрузки настроек из файла

**Comment by SthephanShinkufag** [comment]
Внезапно столкнулся сегодня.

`chrome.storage.sync.set` выполняется, но не сохраняет информацию. Может быть даже такое, что куклу забанил гугль за несоблюдение каких-либо новых политик. `chrome.runtime.lastError` никакую ошибку не выдаёт. Нужно разбираться.

**Comment by SthephanShinkufag** [comment]
Ага, откатился на пару десятков коммитов назад, загрузил распакованное расширение, всё работает.
Сейчас найду коммит с ошибкой, и исправлю.

**Comment by SthephanShinkufag** [comment]
Нашёл. Вот это я лоханулся! Не знаю, что я тогда курил.

```diff
-		const obj = {};
-		obj[id] = value;
+		const obj = { id: value };
```

https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/commit/255d984ff1ab74012fefa8746748d9aa3fee6136#diff-3ffdccae365c029e209bbfa4211be3e6R2397

**Comment by SthephanShinkufag** [comment]
Обновил хроморасширение, сейчас прилетит.
Извиняюсь за серьёзный косяк.

**Comment by perdolka** [comment]
> Не сохраняются изменения в настройках после обновления страницы

Это точно проблема **только** хроморасширения?
Потому что у меня куклоскрипт на ФФ и тоже что-то не сохраняет.

Я менял правила на вкладке "Фильтры" (спелы) и чекбоксы.
До перезагрузки страницы (открытый тред) правила работают, 
после перезагрузки страницы - возвращаются предыдущие значения.

v18.4.26.0 8d2a71e es6
Violentmonkey 2.9.4
FF 60.0b15 (x64)

**Comment by NEONZARIN** [comment]
Это то же самый баг? https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/issues/1198

**Comment by SthephanShinkufag** [comment]
Эта проблема касается только хроморасширения и ничего более, некорректный код в условии для хроморасширения стоит.

**Comment by SthephanShinkufag** [comment]
Для своих репортов создавайте отдельные issues.

**Comment by DimoNline** [comment]
`Это точно проблема только хроморасширения?` 
Похоже, что да. параллельно на firefox все работает.

**Comment by SthephanShinkufag** [comment]
@DimoNline 

Хроморасширение исправлено и обновлено, проблемы быть уже не должно.

**Comment by DimoNline** [comment]
@SthephanShinkufag да, уже все работает, благодарю.
