### ISSUE TITLE
Как это теперь лечить? 2ch.hk страница уезжает вправо при использовании стороннего скрипта на установку тредов по центру страницы.

### ISSUE THREAD

**Issue by NEONZARIN** [SthephanShinkufag/Dollchan-Extension-Tools#1222]
Пользуюсь этим скриптом https://userstyles.org/styles/103272/columnar-for-dvach-makaba-wakaba-2ch-hk в последней кукле теперь с ним как на скрине все вправо уезжает.
![image](https://user-images.githubusercontent.com/16442992/39384348-22dba4b8-4a75-11e8-919e-12fde2efbefe.png)
Хром.

**Comment by SthephanShinkufag** [comment]
Пожалуйта, делайте информативные заголовки для issues!

**Comment by SthephanShinkufag** [comment]
Применил этот css, всё по центру, ничего не уезжает.

Покажите `Настройки` - `Инфо` - `Отладка`.

**Comment by NEONZARIN** [comment]
Можно закрывать. Когда по закрывал все открытые вкладки двача и открыл по новой все опять стало по центру. Жаль так и не понял почему это произошло.
