### ISSUE TITLE
[410chan.org] Множесвенные баги в последней версии

### ISSUE THREAD

**Issue by WagonOfDoubt** [SthephanShinkufag/Dollchan-Extension-Tools#1223]
1. `.de-thr-buttons` стоит вне контейнера треда .`thrdcntnr`, из-за чего смещается ОП-пик в следующем треде. Скорее всего это не единственная борда, где для разделения тредов не используется `<hr>`
2. Форма быстрого ответа не инициализируется правильно. Вместо кнопок форматирования текстовая нода "**,*,__,^^,%%,`" и нет квадрата для прикрепления картинки.
3. Ошибка `inp.clearInp is not a function` при постинге.
Возможно что-то еще.

**Comment by Remu-rin** [comment]
Ещё новые посты в конце треда появляются после ссылок Назад, Вся нить, Первые 100/50 сообщений, в итоге они как разделитель.

**Comment by SthephanShinkufag** [comment]
410chan давно не поддерживаетсяиз-за того, что там встроен фреймворк `Prototype`, который портит многие стандартные функции и методы JS. И победить это никак нельзя, либо нужно много времени на нахождение решения. В какой-то момент у меня вообще была идея запретить там запуск куклы.
Увы.

**Comment by WagonOfDoubt** [comment]
Действительно. Как временное решение помогает запрет в адблоке скрипта `/lib/javascript/protoaculous-compressed.js`
Однако нарушение верстки остается проблемой, которая к тому же потенциально может возникать на других бордах. Нужно либо держать `.de-thr-buttons` внутри контейнера треда, либо добавить css:
```css
.de-thr-buttons::after {
    content: ' ';
    clear: both;
    display: block;
}
```

**Comment by Reisenfag** [comment]
Это имеет место на всех кусаба-бордах. На версии 2018.2.19 работает почти нормально, не считая всякой мелочи. А тут полный аллес.

**Comment by SthephanShinkufag** [comment]
@Reisenfag

Prototype есть только на 410чане.
Что именно имеет место? 
Уточняйте.

**Comment by SthephanShinkufag** [comment]
Sorry, I can't pass this gensokyo magic barrier.

![default](https://user-images.githubusercontent.com/1059874/39674390-d87015c2-5153-11e8-8127-08a3d9686d73.png)

**Comment by SthephanShinkufag** [comment]
Не разбираюсмь в тоходевках. Пришлось гуглить по картинке. Попозже гляну, что там.

**Comment by SthephanShinkufag** [comment]
Ага, так там тоже встроена эта ё%№#ая библиотка Prototype. Как и на 410chan, ничего с этим поделать нельзя, кроме как блокировать `protoaculous-compressed.js`.

**Comment by SthephanShinkufag** [comment]
Придётся пересмотреть в скрипте конфликтующие с Prototype функции и методы, тому що многие кусаба-доски содержат этот фреймворк. Может, как-то получится решить эту проблему.

**Comment by SthephanShinkufag** [comment]
> `.de-thr-buttons` стоит вне контейнера треда `.thrdcntnr`, из-за чего смещается ОП-пик в следующем треде. Скорее всего это не единственная борда, где для разделения тредов не используется <hr>. Нужно либо держать .de-thr-buttons внутри контейнера треда, либо убрать

```js
form > .de-thr-buttons {
    float: left;
}
```

Убрал.

> Форма быстрого ответа не инициализируется правильно. Вместо кнопок форматирования текстовая нода "**,*,__,^^,%%,`" и нет квадрата для прикрепления картинки.
> Ошибка inp.clearInp is not a function при постинге.

Отказался от использования `Array.prototype.reduce` и `Array.from` в скрипте, используя старый дедовский перебор в цикле. Конфликт с Prototype на этом пока исчерпан.

> Ещё новые посты в конце треда появляются после ссылок Назад, Вся нить, Первые 100/50 сообщений, в итоге они как разделитель.

Скрыл эти элементы. Кнопка `Назад` есть на панели скрипта.

**Comment by Reisenfag** [comment]
На 410 осталась кнопка [Mod].

**Comment by SthephanShinkufag** [comment]
А зачем её убирать? Она находится не в треде, а вне его.
