### ISSUE TITLE
[temp.lewd.ga] Сломалось скрытие постов

### ISSUE THREAD

**Issue by UserNaem** [SthephanShinkufag/Dollchan-Extension-Tools#1224]
https://temp.lewd.ga/dev/res/1.html

**Comment by SthephanShinkufag** [comment]
У вас html постов не характерный для TinyIB, основанный на div'ах, со своими классами. Скрипт кое-как задеткетил посты, но чтобы всё полностью корректно работало, нужно прописывать некоторые классы в скрипте. Так как ваша доска тестовая и никем не посещается, то не вижу в этом смысла.
