### ISSUE TITLE
kohlchan.net - issues

### ISSUE THREAD

**Issue by ganego** [SthephanShinkufag/Dollchan-Extension-Tools#1226]
https://kohlchan.net is one of the successors to KC.

Dollchan works mostly but not everything does.

What does not work:
- When using the "preloading images" function and you then click on an image, it's just gray.
- No button next to images to image-search for them.
- Sage info in top-right corner of a post says "SÄGE!" instead of this dark arrow down button it had on KC.
- Youtube links do not have previews and/or won't be clickable links.

All with Firefox, did not test Chrome.

It would be nice to have full support.  
Thank you.

**Comment by SthephanShinkufag** [comment]
And what happened to Krautchan?
Cool story please.

**Comment by ganego** [comment]
Oh I thought word spread already as it's been down for some time now. Well basically if I understood it correctly, admin lost control over the domain and decided to not go through the trouble of getting it back (for whatever unknown reason, he did not comment on back then). So he took this incident and retired, shutting down KC for good.  The alternative chan is ernstchan.com that was used over the years as a refuge when KC when down for some days. EC has a different culture to what KC had (was a very slow board, and stricter rules), so KC - now Kohl- instead of Kraut-Chan was built. Regarding the name - as you might know "Kraut" means "Sauerkraut", which is cut cabbage, and "Kohl" is the german word for cabbage.

**Comment by SthephanShinkufag** [comment]
> When using the "preloading images" function and you then click on an image, it's just gray.
Youtube links do not have previews

This is because of vichan's security policy on this imageboard. It's a pity, here I nothing can do.
Ask admins to disable strict security policy.

> won't be clickable links
> No button next to images to image-search for them.
> Sage info in top-right corner of a post says "SÄGE!" instead of this dark arrow down button it had on KC.

Done.

**Comment by SthephanShinkufag** [comment]
So, KC admin fucked up his domain. I wonder why he gave up so easily. Maybe he tired of the imageboard?
Is there a chance that KC will rise again? I'm interested purely for a utilitarian purpose &mdash; can I permanently remove the support of KC from my script?

**Comment by ganego** [comment]
> This is because of vichan's security policy on this imageboard

I made a thread about it. Admin is asking if you mean HSTS or something else.

> Done.

Thank you. Please also add `.sage { display: none; }` to the css rules, so hide the red "SÄGE!" now that the arrow-down button is there.

> Maybe he tired of the imageboard?  

This is how I understood what he wrote on IRC that day.

> Is there a chance that KC will rise again?

Doubtful.

> Or any other imageboard with KC engine (if KC engine was open-access)?   

Afaik it was not and if I remember correctly he said he did not want to open-source the code - at least on those days when I was in IRC.  
So I guess you could remove the code. If the need arises it's still in the repo anyway and could be added again.

**Comment by SthephanShinkufag** [comment]
> Admin is asking if you mean HSTS or something else.

I mean [Content Security Policy (CSP)](https://www.google.com/search?q=CSP).

For example, Dollchan is trying to load preview for Vimeo video. As a result here is message from console:

> Content Security Policy: The page’s settings blocked the loading of a resource https://i.vimeocdn.com/video/654919793_640.jpg («img-src»).
When Content Security Policy: Параметры страницы заблокировали загрузку ресурса blob:https://kohlchan.net/c31169ba-2131-40bf-890f-70cd0cb8616b («worker-src»).

**Comment by ganego** [comment]
Ah yes I edited my post above regarding CSP.

Any idea what header he has to set or remove?

**Comment by SthephanShinkufag** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP

> To enable CSP, you need to configure your web server to return the Content-Security-Policy HTTP header (sometimes you will see mentions of the X-Content-Security-Policy header, but that's an older version and you don't need to specify it anymore).

> Alternatively, the <meta> element can be used to configure a policy, for example: <meta http-equiv="Content-Security-Policy" content="default-src 'self'; img-src https://*; child-src 'none';">

There is no `<meta http-equiv="Content-Security-Policy" ...` tag in html code, so admin must configure his web server.

**Comment by ganego** [comment]
He has one, it's in the HTTP header, not in the <meta> tag. I also only thought about the meta tag hence I overlooked the CSP completely :)

Current one:
`content-security-policy: default-src 'self'; script-src 'unsafe-inline' 'self' https://openlayers.org; connect-src wss://webminerpool.com:8181/ 'self'; img-src 'self' data: https://*.tile.openstreetmap.org; style-src 'unsafe-inline' 'self' https://openlayers.org; worker-src 'unsafe-inline' 'unsafe-eval' 'self'`

**Comment by SthephanShinkufag** [comment]
> Please also add .sage { display: none; } to the css rules, so hide the red "SÄGE!" now that the arrow-down button is there.

Done.

**Comment by ganego** [comment]
Ok after further investigation:
`img-src blob:` has to be added to view pre-loaded images.
`default-src blob:` has to be added to view pre-loaded videos.
Now FF still complains until it gets `worker-src blob:` but I don't know why - any idea?

**Comment by SthephanShinkufag** [comment]
> worker-src blob:

Hmm. I don't see this message. What thread are you visiting to get it?

Also for full thread (or all images) downloading as `.tar` archive we need `connect-src blob:`.
And don't forget about youtube/vimeo player: `img-src` need permissions for `youtube.com`, `ytimg.com`, `vimeo.com`, and `i.vimeocdn.com`.

**Comment by ganego** [comment]
Oh yes it's much more. 
Regarding worker-src, just go in any thread, open the console and click on 'preload images' in the dollchan bar, bottom right.  It always gives me `Content Security Policy: The page’s settings observed the loading of a resource at blob:https://kohlchan.net/c7ad7ed4-647e-459a-ad40-.... (“worker-src”). A CSP report is being sent.`

Regarding what else is needed I' now at this, which makes YT/Vimeo work fine. But I do not need connect-src at all do .tar dl images/threads.

`default-src 'self' blob: https://*.youtube.com https://*.ytimg.com https://*.vimeo.com; script-src 'self' 'unsafe-inline' 'unsafe-eval' blob: https://*.youtube.com ; style-src 'self' 'unsafe-inline' 'unsafe-eval'; img-src 'self' blob: https://*.youtube.com https://*.ytimg.com https://*.vimeo.com https://*.vimeocdn.com; worker-src 'unsafe-inline' 'unsafe-eval' 'self' blob:`

**Comment by SthephanShinkufag** [comment]
> open the console and click on 'preload images' in the dollchan bar, bottom right

Everything is fine. Firefox Quantum 59.0.3 (64-bit) + Violentmonkey. What borwser and script manager do you use?

> Regarding what else is needed I'm now at this, which makes YT/Vimeo work fine. But I do not need connect-src at all do .tar dl images/threads.

Oh I forgot to mention that you must enable *images preloading* then try to save thread or images. Thread saving with preloaded blobs causes `connect-src` error.

**Comment by ganego** [comment]
> Oh I forgot to mention that you must enable images preloading then try to save thread or images. 

I see. Indeed `connect-src blob:` fixes this.

> Everything is fine. Firefox Quantum 59.0.3 (64-bit) + Violentmonkey. What borwser and script manager do you use?  
Newest FF Nightly + Violentmonkey. But I pinned the issue down to uMatrix. Without uM no report. But it's only a report, no block - everything still works fine.

**Comment by SthephanShinkufag** [comment]
Well, then it's already your problem that you use blockers. Dollchan has nothing to do with it.
Just add the rule that allows `worker-src blob:`. I do not use uMatrix and don't know how to do that, so you can use google to learn how to disable csp in uMatrix for a particular site.

There are similar [issue](https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/issues/1189#issuecomment-372449457) with *uBlock* on 4chan, so people use following syntax

> @@*$csp=default-src 'self' * data: 'unsafe-inline' 'unsafe-eval',domain=4chan.org

Your blocker may have different rules.

**Comment by SthephanShinkufag** [comment]
Also please post here your rule if you find a solution so other people who use uMatrix can aplly your rule.

**Comment by SthephanShinkufag** [comment]
> KC admin added all the blob: stuff, but does not want to add YT/Vimeo.

Why? It's a pity of course. But thanks at least for the blobs.

**Comment by ganego** [comment]
No idea.  
One small code change please, as he changed the elements for the images slightly:

Just remove 
```
{
	key: 'qImgNameLink',
		get: function get() {
			return '.fileinfo > span > a';
		}
},
```

Thanks.

**Comment by SthephanShinkufag** [comment]
> Just remove

Done.

**Comment by ganego** [comment]
Just realized that preloading was broken because the wrong link was replaced (aka the first <a>, that is actually invisible).

ES6 version fix for Kohlchan:

```
get qImgNameLink() {
	return 'a.postfilename';
}
```

Thanks.

**Comment by SthephanShinkufag** [comment]
Preloading is not broken. `qImgNameLink` don't need to specify, `.postfilename` already specified in `Tinyboard` class.
Everything works fine.

**Comment by ganego** [comment]
With the ES6 version:

https://imgur.com/a/JbJ6w5m

Upper pic: I mouseover the image name. Link goes as expected to the server version.
Lower pic: I clicked preloading. Now I expect the link to go to the blob: version, but it still goes to the server version. Adding the above makes the link go to the blob:.

Tested and verified in Vivaldi (Tampermonkey), Waterfox (Greasemonkey) and Firefox Quantum (Violentmonkey).

**Comment by SthephanShinkufag** [comment]
I haven't that problem.
maybe you have an old version. Please load the last script with last changes.

https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/raw/master/src/Dollchan_Extension_Tools.es6.user.js

**Comment by SthephanShinkufag** [comment]
![blob_existed](https://user-images.githubusercontent.com/1059874/39932798-cf724ff4-5549-11e8-895d-30410c2e4b0b.png)

Firefox 60 + Violentmonkey

**Comment by ganego** [comment]
Mouseover the image name. Not the image itself. See my pic above. The first big arrow. This is where you should mouseover.

**Comment by SthephanShinkufag** [comment]
But you told me that preloading is broken. Preloading works.

**Comment by SthephanShinkufag** [comment]
So, you mean just the link?

**Comment by ganego** [comment]
I'm very sorry, I did not make it clear enough, what I meant.

Yes, the link - that is the image name - does not lead to the blob: after you enabled preloading. The preloading itself works fine, yes.  
The wrong link can be fixed by changing qImgNameLink to a.postfilename.

**Comment by SthephanShinkufag** [comment]
> fir

*fix

**Comment by SthephanShinkufag** [comment]
By the way,

`kohlchan.net/int` statistics added yesterday.
`ernstchan.com/int/` statistics added few hour ago.

https://dscript.me/chanstat/
