### ISSUE TITLE
[2ch.hk + Chrome extension]: Дублирование постов при автообновлении

### ISSUE THREAD

**Issue by andreyelek** [SthephanShinkufag/Dollchan-Extension-Tools#1227]
1. **Браузер и его версия** - Google Chrome Версия 65.0.3325.181 (Официальная сборка), (64 бит)
2. **Используемая версия скрипта** -  18.4.28.0
3. **Имиджборд, на котором встретилась ошибка** - https://2ch.hk/
4. **Пошаговые действия для воспроизведения ошибки.** - дождаться автообновления и посты будут дублироваться, при обновлении самой страницы дублирование спадает
![image](https://user-images.githubusercontent.com/25351724/39662475-6f611250-506a-11e8-9c89-06d9cc81b1be.png)

**Comment by SthephanShinkufag** [comment]
У вас хроморасширение или скрипт?
Зайдите в настройки макабы, и отключите её автообновление.
У вас одновременно работает апдейтер куклы и апдейтер макакоподелия.

**Comment by andreyelek** [comment]
Все понел

**Comment by SthephanShinkufag** [comment]
Починил, обновил расширение. Ждите, сейчас прилетит.
Напишете потом, всё ли хорошо.

**Comment by andreyelek** [comment]
Все работает нормально, баг пофиксен, спасибо
