### ISSUE TITLE
[4chan.org] Не проигрывается музыка в треде.

### ISSUE THREAD

**Issue by Redricks** [SthephanShinkufag/Dollchan-Extension-Tools#1228]
Собственно, та же проблема, что и в https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/issues/1188
С куклой музыки нет, без нее есть. 
Тред: https://boards.4chan.org/a/thread/172452918/guys-hey-guys-its-cinco-de-maho

**Comment by SthephanShinkufag** [comment]
Пока что не могу определить источник звука, что его генерирует...

**Comment by SthephanShinkufag** [comment]
Ага, нашёл.

```html
<iframe src="https://www.youtube.com/embed/wztuzAkF0hw?version=3&amp;autoplay=1&amp;controls=0&amp;showinfo=0&amp;modestbranding=1&amp;rel=0&amp;iv_load_policy=3&amp;loop=1&amp;playlist=wztuzAkF0hw" allowfullscreen="" width="1" height="1" frameborder="0"></iframe>
```

https://www.youtube.com/embed/wztuzAkF0hw?version=3&autoplay=1&controls=0&showinfo=0&modestbranding=1&rel=0&iv_load_policy=3&loop=1&playlist=wztuzAkF0hw

**Comment by SthephanShinkufag** [comment]
То есть, это тупо скрытый ютуб-эмбеддер в одном из постов.
Dollchan удаляет встроенные ютуб-эмбеддеры, и добавляет свой плеер с блекджеком и превью-картинками.

**Comment by SthephanShinkufag** [comment]
Таки починилъ.
