### ISSUE TITLE
2ch.hk Реквест фичи по авто обновлению страницы каталога доски.

### ISSUE THREAD

**Issue by NEONZARIN** [SthephanShinkufag/Dollchan-Extension-Tools#1229]
По ссылкам типа https://2ch.hk/b/catalog.html
Удобно было бы сидя в каталоге и что бы кукла сама обновляла страничку, отображая новые треды и тд изменения.

**Comment by SthephanShinkufag** [comment]
Скрипт не поддерживает каталоги. Кукла парсит только посты и треды.
Проще новый скрипт написать специально для каталогов.

**Comment by NEONZARIN** [comment]
ok

**Comment by SthephanShinkufag** [comment]
К сожалению, у меня нет столько времени. Я даже issues на гитхабе не могу разгрести, а тут целый новый парсер пейсать.
