### ISSUE TITLE
[dscript.me]: Imageboard for Dollchan discussion

### ISSUE THREAD

**Issue by SthephanShinkufag** [SthephanShinkufag/Dollchan-Extension-Tools#1230]
http://dscript.me/

В последнее время приходит очень много писем на почту с вопросами, потому я решил более не тянуть кота в долгий ящик, и всё-таки выкатить своё поделие на основе TinyIB, дабы вопросы задавали там.
Итак, очередная мелкоборда на просторах интернетов.
Создан тред с обсуждением скрипта, как в старые добрые времена на Ычане:
http://dscript.me/de/res/1.html
Можете задавать там свои вопросы, если не хотите создавать issue, или например, вы не зарегистрированы на Github.

Также доступна доска для тестов и прочего непотребства:
http://dscript.me/test

Также на ресурсе доступен сервис по отслеживанию скорости постинга на имейджбордах:
http://dscript.me/chanstat
Сервис запущен вчера, поэтому "данные за неделю" и "за всё время" пока не актуальны.
По вашему желанию могу добавить и другие домены для отслеживания.

**Comment by XakepSDK** [comment]
Добавь пожалуйста lolifox в статистику

**Comment by SthephanShinkufag** [comment]
@XakepSDK 

Добавил. Сейчас 17:10 на моих часах, в 18:00 произойдёт первый запрос, и он отображаться не будет, так как сервис работает на разнице между постами, и нужно две выборки. Первый столбик на графике появится в 19:00.

**Comment by XakepSDK** [comment]
Баг с отображением цифр на шкале - они белого цвета, когда самой шкалы нет
https://puu.sh/AiqIG/e74bc0e345.png
