### ISSUE TITLE
Неправильная работа скрипта на kusabax  0.9.3

### ISSUE THREAD

**Issue by Satorisan** [SthephanShinkufag/Dollchan-Extension-Tools#1231]
При попытке оставить пост через форму быстрого ответа выдает:
 ✖ Внутренняя ошибка:
TypeError: inp.clearInp is not a function
    at clearInputs (:13203:7)
    at clearForm (:12271:6)
    at checkUpload (:12988:3)
    at run (:1832:22)
    at notify/< (:1845:30)
    at flush (:996:9)

Пост при этом уходит, однако сам скрипт работать перестает. 
Доски, на которых обнаруживалась проблема:
http://zenchan.hk/z/  - через форму быстрого ответа выходит ошибка;
http://gensokyo.4otaku.org/curr/b - ошибка появляется даже при ответе напрямую в треде.

**Comment by SthephanShinkufag** [comment]
Уже исправлено сегодня.

https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/issues/1223#ref-commit-126b2b5

Устанавливайте разрабатываемую версию скрипта
https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/wiki/versions
Либо обновляйте хроморасширение, если оно у вас стоит.

**Comment by Satorisan** [comment]
Спасибо!
