### ISSUE TITLE
Не сохраняются изменения

### ISSUE THREAD

**Issue by Fourest** [SthephanShinkufag/Dollchan-Extension-Tools#1233]
Изменения не сохраняются, вот допустим: я изменил настройки или добавил тред в избранные, но при перезагрузке страницы, переходе на новую страницу или открытии новой вкладки изменения пропадут

**Comment by SthephanShinkufag** [comment]
Если вы хромог и используете хроморасширение, обновите хроморасширнеие. Этот баг хроморасширения уже исправлен.
