### ISSUE TITLE
Download button for preloaded images that goes to server URL

### ISSUE THREAD

**Issue by ganego** [SthephanShinkufag/Dollchan-Extension-Tools#1234]
When you use preloading for images, you will get blobs that cannot be downloaded with the original file name.
I propose the idea of having an (optional) button in front of the file name when using preloading, that will serve as a link to the original file.  

Why?  
I sometimes want to download some of those preloaded images, but with the original name. This is obviously not possible with blob, so I had to set the name manually.
<br>
Example:
- Left: Original, without preloading
- Right: Preloading started. Button leads to URL on server, name leads to blob.

https://imgur.com/a/gP2QSQU

<br>
  
Example code:
https://github.com/ganego/Dollchan-Extension-Tools/commit/df8442e3a96719318553c06769d593278475b21a#diff-3ffdccae365c029e209bbfa4211be3e6

**Comment by SthephanShinkufag** [comment]
Links have the download attribute with the original name. When you save images on such links, they are saved with the original name.

Extra buttons are not needed.
