### ISSUE TITLE
Make "minWebmWidth" work as expected

### ISSUE THREAD

**Issue by ganego** [SthephanShinkufag/Dollchan-Extension-Tools#1235]
Config minWebmWidth is to set the minimum width of a video.  
This would be useful to make long videos easier to navigate, by giving them a larger navigation bar at the bottom.  
Right now this is not the case, because it will stop scaling once the height is maxed.  

I suggest changing:

```
const minSize = this.isVideo ? Math.max(Cfg.minImgSize, Cfg.minWebmWidth) : Cfg.minImgSize;
if(width < minSize && height < minSize) {
	const ar = width / height;
	if(width > height) {
		width = minSize;
		height = width / ar;
	} else {
		height = minSize;
		width = height * ar;
	}
}
```

to (width in else changed)

```
const minSize = this.isVideo ? Math.max(Cfg.minImgSize, Cfg.minWebmWidth) : Cfg.minImgSize;
if(width < minSize && height < minSize) {
	const ar = width / height;
	if(width > height) {
		width = minSize;
		height = width / ar;
	} else {
		height = minSize;
		width = minSize;
	}
}
```

Result:
https://imgur.com/a/xjxyYqq

**Comment by SthephanShinkufag** [comment]
But if it will be a picture, then its proportions will break...

**Comment by SthephanShinkufag** [comment]
There is another problem, an option "Images" > "Minimal width for WebM (px)" is broken.
Just need to fix it.

**Comment by ganego** [comment]
Seems you changed stuff. Problem exists again.  
In es6 script search for 

```
if(width < minSize || height < minSize) {
	return [width, height, Math.max(width, height)];
}
```

Now I fixed it by changing it to 
```
if(width < minSize) {
	return [minSize, height, Math.max(width, height)];
}
```

I honestly did not analyze the whole code if there is a better solution or if I overlooked something, but as far as I've tested it works now as I expect it to work.
