### ISSUE TITLE
Поле ввода капчи наползло на картинку капчи

### ISSUE THREAD

**Issue by funkyshity** [SthephanShinkufag/Dollchan-Extension-Tools#1237]
Так и задумано? Появилось после последней обновы, до этого поле было снизу.
v18.4.28.0.4d1582e
![image](https://user-images.githubusercontent.com/11163036/40417636-e05e2dcc-5e88-11e8-8809-7b3a18bf18c9.png)

**Comment by funkyshity** [comment]
Ок, сносите тему.

**Comment by perdolka** [comment]
Просто нажми кнопку Close issue
