### ISSUE TITLE
Не показывает ответы на твои посты в избранном.

### ISSUE THREAD

**Issue by funkyshity** [SthephanShinkufag/Dollchan-Extension-Tools#1239]
При ответе на твой пост в избранном не появляется выделенная цифра.  Сегодня заметил и затестил через два браузера.
![image](https://user-images.githubusercontent.com/11163036/40480977-ae8391c2-5f58-11e8-85f2-ec4bb3160c5c.png)
А в избранном показывает просто +1, а единичка должна быть выделена. 
![image](https://i.imgur.com/3AxdVmJ.png)
Может кто нибудь еще затестить?
Пробовал 2 раза и оба раза в избранном не отобразился ответ на мой пост.
Opera 52.0.2871.99
Кукла v18.4.28.0.4d1582e

**Comment by NEONZARIN** [comment]
так сам себе ответил чтоле?

**Comment by funkyshity** [comment]
Через другой браузер же.

**Comment by SthephanShinkufag** [comment]
Чому закрыли?

**Comment by SthephanShinkufag** [comment]
Исправлено.
