### ISSUE TITLE
Надоедающее окошко в Safari

### ISSUE THREAD

**Issue by artemsmikh** [SthephanShinkufag/Dollchan-Extension-Tools#1240]
Safari 11.1
Скрипт v18.4.28.0.8256b0d
Tampermonkey 4.6

Постоянно вылазит вот такое окошко при попытке перейти с текущей страницы на другую, а в некоторых случаях — при попытке закрыть вкладку с тредом:
<img width="532" alt="screen shot 2018-05-27 at 01 12 30" src="https://user-images.githubusercontent.com/5757193/40580636-2aca03da-614b-11e8-94a7-994fe0d644d4.png">
Такое происходит, например, при нажатии на кнопку "Reply", когда ты на какой-нибудь доске (не внутри треда). Проверено на 4chan, iichan.hk, 2ch.hk. Также на 2ch.hk то же самое происходит, если ты внутри треда и хочешь закрыть вкладку с ним. 

Пытался найти какую-нибудь настройку, отключающую это, но не нашёл. Без скрипта не воспроизводится.

**Comment by Y0ba** [comment]
Может дело в зарегистрированном событии `beforeunload`? Попробуй найти в крипте этот `if` и удалить его. https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/blob/c1c32bc43b27ff7efa0af3300e2cde5cf9f7c2c7/src/modules/Main.js#L53-L56

**Comment by artemsmikh** [comment]
@Y0ba да, если закомментировать этот кусок, то окошко не появляется. Что он делает?

**Comment by Y0ba** [comment]
Сохраняет насколько тред проскроллен перед закрытием, чтоб потом восстановить если его откроешь снова.

А если заменить тот `if` на
```js
 if(aib.t || !Cfg.scrollToTop) { 
 	doc.defaultView.addEventListener('beforeunload', 
 		() => { sesStorage['de-scroll-' + aib.b + (aib.t || '')] = window.pageYOffset; }); 
} 
```

**Comment by artemsmikh** [comment]
Было вот так:
```javascript
if (aib.t || !Cfg.scrollToTop) {
	doc.defaultView.addEventListener('beforeunload', function () {
		return sesStorage['de-scroll-' + aib.b + (aib.t || '')] = window.pageYOffset;
	});
}
```

Заменил на твой вариант, окошка нет. Хотя я не замечаю, чтобы треды скрошились до сохранённой позиции после переоткрытия. -_-

**Comment by Y0ba** [comment]
Проблема в `return` в коде выше. Вебкит возвращение чего-то из этого события не равное `undefined` вопринимает как просьбу к пользователю не покидать страницу. Для хрома, лисы и всех остальных для этого нужно ставить `e.returnValue = "сообщение";`, а возвращаемое значение они игнорируют. Учитывая, что на вебките скрипт тестируется редко, баг так и висел тут давно.

> Хотя я не замечаю, чтобы треды скрошились до сохранённой позиции после переоткрытия. -_-

Для этого `sessionStorage` нужно заменить на `localStorage` и периодически подчищать его. Сейчас оно работает разве что для кнопки "назад" (потому что `sessionStorage` уникален для каждой вкладки) и по большей части ненужно, поскольку браузеры делают это сами.

**Comment by artemsmikh** [comment]
Ну, собственно, тогда для меня проблема решена, спасибо. Было бы здорово, если бы фикс вошёл в один из следующих релизов скрипта, если это возможно, чтобы не нужно было подменять тот кусок кода каждый раз после обновления.
