### ISSUE TITLE
[2ch.hk] рамка у webm

### ISSUE THREAD

**Issue by perdolka** [SthephanShinkufag/Dollchan-Extension-Tools#1241]
она исчезла

**Comment by SthephanShinkufag** [comment]
Что за рамка?

**Comment by SthephanShinkufag** [comment]
https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/issues/1238#issuecomment-392452601

**Comment by perdolka** [comment]
Нет, я имел ввиду ту рамку (полоску над видео), 
которую ты делал для возобновления возможности перетаскивать открытое видео.
Она пропала на харкаче. Во всяком случае у меня, странно что больше никто не написал об этом.
version = 18.4.28.0
commit = 4d1582e

**Comment by SthephanShinkufag** [comment]
Ну так уточняйте же, ё-моё. Сколько всем говорю - пишите подробнее вашу проблему.
Я не могу вас с полуслова понимать.

Всё на месте. Скорее всего, вы используете посторонние css. Отключите их.

**Comment by perdolka** [comment]
Да, извини, тут я лажанул.
Проблема была на моей стороне, с css да.
