### ISSUE TITLE
Поиск по превью и по кадру webm/mp4

### ISSUE THREAD

**Issue by XakepSDK** [SthephanShinkufag/Dollchan-Extension-Tools#1242]
На данный момент есть поиск по картинке, возможно ли сделать поиск по кадру? А то приходится вручную сохранять кадр и искать.
(я про google images, whatanime.ga и др.)

**Comment by perdolka** [comment]
Был уже такой реквест:
https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/issues/923

**Comment by SthephanShinkufag** [comment]
Может, когда-нибудь, но не сейчас. Достаточно сложно.

**Comment by XakepSDK** [comment]
А можешь хотя бы по превью поиск сделать?

**Comment by SthephanShinkufag** [comment]
> А можешь хотя бы по превью поиск сделать?

Сделал. теперь кнопки поиска хотя бы по превью работают, раньше с них вообще толку для вебм не было.

**Comment by XakepSDK** [comment]
Вот это реально круто! Прямо killer-feature. Жду whatanime.ga

**Comment by SthephanShinkufag** [comment]
> whatanime.ga

Увы, не получится. Там в ответе нет ссылки на страницу с результатами поиска.

**Comment by XakepSDK** [comment]
А нельзя ли сделать какой-нибудь хак с использованием imgur или похожих сервисов?

**Comment by SthephanShinkufag** [comment]
Нет, таким пердолингом я заниматься не буду.

**Comment by SthephanShinkufag** [comment]
Нужен ресурс без регистрации.
Поисследовав тему, я таки обнаружил интересное приложение от создателей sauceNAO:
https://addons.mozilla.org/en-US/firefox/addon/image-search-options/

Приложение загружает картинки на временный картинкохостинг https://tmp.saucenao.com/, а оттуда картинка ищется по всем движкам. Не нужна ни регистрация, ничего.
Можно попробовать использовать этот ресурс.

**Comment by SthephanShinkufag** [comment]
Взлетело. Немного обкатаю и запилю коммит.

**Comment by SthephanShinkufag** [comment]
Готово. Проверяйте.

![webm_search_links](https://user-images.githubusercontent.com/1059874/41250317-3501f576-6dbf-11e8-8b03-93b5c1cc6956.png)
