### ISSUE TITLE
[bug] [2ch.hk] создание треда

### ISSUE THREAD

**Issue by perdolka** [SthephanShinkufag/Dollchan-Extension-Tools#1244]
Ошибка при попытке создать тред: 
> Ошибка:
> Вы постите слишком быстро.

На самом деле, перед попыткой создать тред никаких постов/тредов отправлено НЕ было.
Капча введена правильно.
Где-то с 3-4- раза отправка срабатывает (без перезагрузки страницы и т.д., просто с N-попытки).
Проблема возникает не всегда, закономерность пока не нашёл.

18.4.28.0. 4eb28c8

**Comment by perdolka** [comment]
Сейчас создал два треда **без куклы**, проблема не появилась.
Не знаю как ещё воспроизвести, я редко создаю треды, а шитпостить не очень хочется.

**Comment by SthephanShinkufag** [comment]
Просто у меня, как обычно, всё работает. Тоже шитпостить не хочется.
