### ISSUE TITLE
Реквест: Вернуть оригинальный размер капчи на 2ch.hk или сделать выбор размера в настройках

### ISSUE THREAD

**Issue by cndmn** [SthephanShinkufag/Dollchan-Extension-Tools#1247]
На большом зуме сайта огромная капча почти не воспринимается. Будет очень хорошо, если появится выбор в настройках оригинальная/большая или размер капчи в процентах.

**Comment by SthephanShinkufag** [comment]
Я не хочу плодить опции.
Используйте css:

```js
.captcha-box > img {
    width: 200px;
    margin: 0;
}
```

Подставляйте вместо 200px своё значение, которое вам нравится.

**Comment by SthephanShinkufag** [comment]
Могу вообще выпилить css увеличенния капчи из скрипта, пусть все делают то, что захотят сами.

**Comment by cndmn** [comment]
Все работает, спасибо.
