### ISSUE TITLE
[enhancement] выделять ответы в уведомлении...

### ISSUE THREAD

**Issue by perdolka** [SthephanShinkufag/Dollchan-Extension-Tools#1248]
...на рабочем столе. 
Те, которые адресованы "мне".
Пометкой "You", звуком, или каким-то другим способом.
<a href="http://piccy.info/view3/12393161/2bf1015b1ac39e75a46a4cdf82ee79bc/" target="_blank"><img src="http://i.piccy.info/i9/fc15a326ce9aeab494561a523f946d85/1528317983/18109/1246306/dfd.png" alt="Piccy.info - Free Image Hosting" border="0" /></a><a href="http://i.piccy.info/a3c/2018-06-06-20-46/i9-12393161/367x130-r" target="_blank"><img src="http://i.piccy.info/a3/2018-06-06-20-46/i9-12393161/367x130-r/i.gif" alt="" border="0" /></a>

**Comment by SthephanShinkufag** [comment]
Сделал вот так:

![notification_replies_to_you](https://user-images.githubusercontent.com/1059874/41482240-a4dead78-70dd-11e8-9f2f-c71b2d96a098.png)

В уведомлении теперь будет показываться уведомление вида
`kohlchan.net/int/123456: 5 новых постов. 2 ответа Вам`

**Comment by SthephanShinkufag** [comment]
Слова "Последний пост" снесены в тело уведомления, ибо не помещались в заголовке, и обрезались троеточием.
И да, выделять что-то цветом в теле уведомления нельзя, там можно размещать только текст, а не html-код.

**Comment by perdolka** [comment]
Спасибо.
