### ISSUE TITLE
[enhancement] Сделать возможным поиск пометок (You)...

### ISSUE THREAD

**Issue by perdolka** [SthephanShinkufag/Dollchan-Extension-Tools#1249]
...с помощью Ctrl+F, чтобы искать все ответы на свои посты.

**Comment by SthephanShinkufag** [comment]
В >>ссылках или в постах возле кнопок?
Если в >>ссылках, то это сильно замедлит выполнение скрипта, так как изменение их текста гораздо медленнее, чем добавление классов.

**Comment by perdolka** [comment]
Ну, тогда в постах возле кнопок.

**Comment by XakepSDK** [comment]
Разве сейчас нельзя?

**Comment by SthephanShinkufag** [comment]
Заодно сделал (you) синим цветом в тон с боковыми полосками:

![my_posts_marking](https://user-images.githubusercontent.com/1059874/41459537-8a5097b4-7092-11e8-9e79-6163b2e73d6f.png)

**Comment by perdolka** [comment]
Спасибо.
