### ISSUE TITLE
2 проблемы

### ISSUE THREAD

**Issue by trollsasha1** [SthephanShinkufag/Dollchan-Extension-Tools#1251]
1) Отктырыть вбмку(да и mp4 тоже) можно, а закрыть нельзя. Не кликом по ней, не кликом просто в рандомном месте вне плеера, как это делается если кукла не стоит. С пикчами всё норм работает. Закрывается исключительно если перезагрузить тред f5, из-за этого просто невозможно сидеть в вебм тредах.
2) Не как не помечается ответы на мои посты. Без куклы, твой пост помечается красной полоской, а ответы на него тоже послоской но из точек. В кукле же, есть только функция твоего поста. А ответы тупо не видно, да там есть слово You, но его практически не видно. Лучше сделать выделение цветом как на "Мой пост" только не синим цветом а другим.

**Comment by SthephanShinkufag** [comment]
> Отктырыть вбмку(да и mp4 тоже) можно, а закрыть нельзя. 

Похоже, у вас Firefox. Это проблема Лисы &mdash; обытия на video-объектах у неё не работают, и исправить это никак нельзя. Специально добавлен вверху крестик для закрытия.
Или вы не видите крестик?

**Comment by trollsasha1** [comment]
Нет у меня хром. А уже понял почему так. У меня стоит расширение для регулировки скорости html5 (https://chrome.google.com/webstore/detail/video-speed-controller/nffaoalbilbmmfgbnbgppjihopabppdk) он видимо конфликтует с твоей куклой, так как просто на дваче всё было норм. Нужно как то решить это, чтобы работало и то и то.
А по поводу выделения ответа, мне уже подсказали css для этого. Но всё равно странно что это делается так, а не галочкой в настройках. Ведь это всё же одна из основ борд, понимать кто тебе ответил и где твой пост.

**Comment by SthephanShinkufag** [comment]
> понимать кто тебе ответил и где твой пост.

Ваши посты выделяются цветом, ссылки на ваши посты выделяются как (you).
Что не так?

**Comment by trollsasha1** [comment]
> Ваши посты выделяются цветом, ссылки на ваши посты выделяются как (you).
Что не так?
То что("You) не так бросается в глаза, как цвет сбоку поста, и чтобы это (You) найти, нужно всматриваться, а хочется налегке скролить.

**Comment by SthephanShinkufag** [comment]
Покажите, как надо тогда, няшонька.
Ваш css, или даже покажите картинкой, например.
Тогда запилю, чтоб было модно-молодёжно.

**Comment by trollsasha1** [comment]
Будет [так](https://ibb.co/ec8kAJ). (так по дефолту на дваче без куклы выделяются посты/ответы) 

> .de-mypost{
border-left: 2px solid #991700 !important;
}
.de-reply-post{
border-left: 2px dashed #991700 !important;
}
.post.reply .post-message { max-height: 600px !important; }

**Comment by SthephanShinkufag** [comment]
Сделал выделение ответов на ваш пост с помощью пунктирных точек по бокам.

![answer_to_my_post](https://user-images.githubusercontent.com/1059874/41380564-05daf97c-6f6e-11e8-8e99-06c37b29b84a.png)

**Comment by SthephanShinkufag** [comment]
> Нет у меня хром. А уже понял почему так. У меня стоит расширение для регулировки скорости html5 (https://chrome.google.com/webstore/detail/video-speed-controller/nffaoalbilbmmfgbnbgppjihopabppdk) он видимо конфликтует с твоей куклой, так как просто на дваче всё было норм. Нужно как то решить это, чтобы работало и то и то.

Исправил совместимость.
Issue можно закрывать?

**Comment by trollsasha1** [comment]
Да, спасибо!

**Comment by SthephanShinkufag** [comment]
Сделал пометку только с одной стороны, чтобы не путать с "моими" постами.

![my_posts_replying](https://user-images.githubusercontent.com/1059874/41460738-52da1ebe-7096-11e8-9696-c3b680832984.png)
