### ISSUE TITLE
[4chan.org]: Conflict with uBlock

### ISSUE THREAD

**Issue by puyebu** [SthephanShinkufag/Dollchan-Extension-Tools#1252]
Обновил сегодня огнелис с очисткой профиля, захожу, а на форчане не работает. На абучане работает. На dscript.me/de/ тоже работает.
Версия скрипта: v18.6.3.0.4957fe6.es6 
Версия огнелиса: 61.0
Версия скрипт-менеджера: Violentmonkey v2.9.5
В настройках проверил, запрет запуска на форчонге не стоит.

**Comment by SthephanShinkufag** [comment]
Что пишет в консоли ошибок (`Ctrl+Shift+J`) если обновить страницу на форчане?
Используете ли вы uBlock либо другие блокировщики? Если отключить блокировщик, будет ли работать куклоскрипт?

**Comment by puyebu** [comment]
В консоли ошибок ничего не пишет связанного с куклоскриптом.
Использую уБлок Оригин и уМатрикс.
Оказалось, что блокирует ублок подпиской "uBlock filters" фильтром "4chan.org##script:inject(abort-current-inline-script.js, String.fromCharCode, /\/\*[0-9a-f]{40}\*\//)".
Как-то не подумал, что они могли подобное сделать, теперь бы ещё разобраться, как бы вырубить только это правило, не вырубая весь фильтр.
Спасибо за помощь, можно закрывать.

**Comment by SthephanShinkufag** [comment]
Странно то, что у меня тоже стоит uBlock о всеми подписками, но Dollchan нормально работает.

Все проблемы на `4chan.org` сейчас возникают из за малвара, котрый админ внедрят в сайт, чтобы в будущем следить и продавать информацию об аноне. Разработчики uBlock добавили блокировку этой гадости в подписку, и из-за этого ненароком ломается Dollchan. Лечится добавлением правила

```
@@||boards.4chan.org^$csp
```

Правда, это делает вас уязвимым к малварю, встроенному админом.

Вот такие два стула.

**Comment by SthephanShinkufag** [comment]
Алсо, у 4chanX тоже есть эта проблема:
https://github.com/ccd0/4chan-x/issues/1968

**Comment by puyebu** [comment]
Жаль. 
Учитывая сколько всякой пакости отображается ублоке/уматрикс после использования вышенаписанного правила, мне как-то не по себе.
Ублок имеет возможность блокировать отдельные скрипты через script:contains(...), но похоже правило выше имеет приоритет над остальными правилами или же его ломают остальные фильтры.

**Comment by SthephanShinkufag** [comment]
У меня от этого всего лётчик.jpg, извините. Я не могу добиться этого бага, у меня всё работает с uBlock + Firefox 60 + Tampermonkey.
Аноны с форчана советуют добавлять правило
```
@@||boards.4chan.org^$csp
```
Но с ним вы должны расслабить булки и пропускать весь малварь. Что, как, зачем и почему &mdhas; родной, я этот уебанский форчан не посещаю почти. Спрашивайте у буржуев оттуда, кто пользуется 4chanX, они должны больше знать. Там у них такая же ситуация.

**Comment by perdolka** [comment]
[SPOILER]форчан ни нужон[/SPOILER]

**Comment by SthephanShinkufag** [comment]
@puyebu 

Тут выплыл вот такой баг:
https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/issues/1254

Не пытались ли вы, кстати, использовать корректировку времени?

**Comment by puyebu** [comment]
Да, я использовал корректировку времени.
Билд выше пофиксил эту проблему и теперь работает без отключения чего-либо в ублоке.

**Comment by SthephanShinkufag** [comment]
Да вы что? Мама дорогая, вот это бинго!
Значит, всё дело действительно было только в этом.
Good, good.
