### ISSUE TITLE
[arhivach.cf] 2 бага

### ISSUE THREAD

**Issue by perdolka** [SthephanShinkufag/Dollchan-Extension-Tools#1255]
Ещё проблемы с архивачем.
1
Невозможно залогинить акк, если на странице входа включена кукла:
http://arhivach.cf/auth/
Думаю, эту страницу тоже добавить бы в исключения (как вы уже сделали с /favs), чтобы не тратить время на поиск проблемы.
На этой странице кукла не нужна.

2
Если открепить панель, например "Избранное", она залезает верхним краем под шапку страницы:
<a href="http://piccy.info/view3/12422153/455d04a82fc17741bd450e1d2f838833/" target="_blank"><img src="http://i.piccy.info/i9/9eda1412a1ffa5e98dcf77c89a581025/1529307202/8227/1252111/sshot_200.png" alt="Piccy.info - Free Image Hosting" border="0" /></a><a href="http://i.piccy.info/a3c/2018-06-18-07-33/i9-12422153/509x179-r" target="_blank"><img src="http://i.piccy.info/a3/2018-06-18-07-33/i9-12422153/509x179-r/i.gif" alt="" border="0" /></a>

**Comment by perdolka** [comment]
Спасибо.

**Comment by perdolka** [comment]
Видимо из-за фикса с прячущейся панелью появилась такая ерунда - контекстные меню шапки (аккаунт, стиль, информация)  прячутся под кнопки сортировки тредов.
<a href="http://piccy.info/view3/12422393/8c2597b31b63e8b1dcf23370bf9e25e4/" target="_blank"><img src="http://i.piccy.info/i9/d7b6ba8219733c4378c81c842eac4045/1529310895/6973/1252135/sshot_201.png" alt="Piccy.info - Free Image Hosting" border="0" /></a><a href="http://i.piccy.info/a3c/2018-06-18-08-34/i9-12422393/204x177-r" target="_blank"><img src="http://i.piccy.info/a3/2018-06-18-08-34/i9-12422393/204x177-r/i.gif" alt="" border="0" /></a>

**Comment by SthephanShinkufag** [comment]
У меня нет этих кнопок.

**Comment by perdolka** [comment]
Хм, думаю, они должны быть например на странице http://arhivach.cf/index/ даже без логина, только что проверил:
<a href="http://piccy.info/view3/12422427/57ce3217f57bc33b4379c15566373df7/" target="_blank"><img src="http://i.piccy.info/i9/ee5cbde31a93713dab9e9fc115ac9fe6/1529311537/12675/1252135/sshot_202_240.jpg" alt="Piccy.info - Free Image Hosting" border="0" /></a><a href="http://i.piccy.info/a3c/2018-06-18-08-45/i9-12422427/240x218-r" target="_blank"><img src="http://i.piccy.info/a3/2018-06-18-08-45/i9-12422427/240x218-r/i.gif" alt="" border="0" /></a>
С логином - ещё на странице http://arhivach.cf/my/

**Comment by SthephanShinkufag** [comment]
А, это на главной, нашёл.

**Comment by SthephanShinkufag** [comment]
Вот сейчас должно быть норм.
