### ISSUE TITLE
Resize large images to fit screen не работает

### ISSUE THREAD

**Issue by zbczyvgy** [SthephanShinkufag/Dollchan-Extension-Tools#1257]
В ишью #1034 стоит помеченным как сделанное
```[x] Опция Resize images по размеру экрана не работает с кнопкой Expand all images.```

Но ведь это до сих пор не работает, простейший пример - на любой борде создать тред с длиннокотом ( https://my.mixtape.moe/blacup.png ) в оп-посте, нажать `Expand all images` со включенным `Resize large images to fit screen`, картинка станет столь же огромной, сколь была и без этой галки, и улетит за пределы экрана.

**Comment by SthephanShinkufag** [comment]
Разворачивание в посте умещает картинки только по ширине.

**Comment by SthephanShinkufag** [comment]
Это нормальное поведение, так и задумано. Ресайз по высоте работает только для разворота по центру, для разворота в посте это не нужно.

**Comment by SthephanShinkufag** [comment]
Или у вас картинка все-таки вылезает по ширине?

**Comment by zbczyvgy** [comment]
Только по ширине, но я не уверен, что "так и задумано" - хорошо. Может, все-таки сделать и по высоте тоже? Или поменять галку на дропдаун с "Do not resize", "Fit to width", "Fit to height", "Fit to width and height"?

**Comment by zbczyvgy** [comment]
В смысле "зачем"? В смысле "глупость"? Затем, чтобы не обрезалась картинка и можно было сразу увидеть, что на ней. При чем тут "самый низ экрана"? Например, треды a la "оцени тян", если фотка больше моего вертикального разрешения, то я увижу личико только до переносицы, а дальше листать или жамкать на фотку два раза, чтобы она открылась по центру. Глупость - это то, как функция работает сейчас.

**Comment by SthephanShinkufag** [comment]
Если пост находится внизу экрана, и вы раскроете длинную картинку в нём, вам все равно придётся скроллить, чтобы картинка с постом достигла верха и уместилась в экран.

**Comment by SthephanShinkufag** [comment]
Опция `"Картинки"` > `"Умещать большие картинки в экран"` расширена до `"Картинки"` > `"[Откл.][По ширине][Шир.+выс.] Уменьшать при раскрытии в посте"`. Раскрытие в посте теперь подгоняет картинки только по ширине, либо по ширине и высоте, соответственно. При раскрытии по центру, картинки теперь всегда подгоняются по ширине и высоте.

**Comment by perdolka** [comment]
О, Дарья поправилась.

**Comment by SthephanShinkufag** [comment]
@zbczyvgy 

Хромог, небось? В Лисе всё нормально, в хроме не проверял.

**Comment by SthephanShinkufag** [comment]
Теперь должно быть нормально.

**Comment by zbczyvgy** [comment]
Хромоги тоже люди :point_up:
