### ISSUE TITLE
Create embedded Youtube player for all videos in a post

### ISSUE THREAD

**Issue by ganego** [SthephanShinkufag/Dollchan-Extension-Tools#1259]
Situation:  
- 10 Youtube links in a post.

What happens:  
- The first video will have the embedded player, the others are text links.

Suggestion:  
- Make embedded player for all Youtube links in a post.

Thank you :)

**Comment by SthephanShinkufag** [comment]
No, only one player per post. Click on a link that you need, and it will play.

**Comment by SthephanShinkufag** [comment]
The whole algorithm is set up that there is one player object in the post. Your wish need to completely rewrite the behavior of Dollchan.

**Comment by ganego** [comment]
Ok, no problem.

**Comment by SthephanShinkufag** [comment]
> I always use middleclick normally

=\
