### ISSUE TITLE
Баг во фрейме

### ISSUE THREAD

**Issue by Dollfriend** [SthephanShinkufag/Dollchan-Extension-Tools#1261]
Куклоскрипт версии 18.6.25.0.771d95d не запускается при просмотре досок на iichan.hk и owlchan.ru через фрейм. Без фрейма всё работает. До обновления такого не замечал. (Greasemonkey 4.5, Firefox 61.0)

**Comment by Gorjoda** [comment]
Версия v18.8.9.0.87fff30.es6 не работает версия с фреймом на 2ch.hk (https://2ch.hk/frame.html).

**Comment by SthephanShinkufag** [comment]
```js
for(let i = 0, frs = window.frames; i < frs.length; ++i) {
	frs[i].document.addEventListener('load', () => runMain(checkDomains, dataPromise));
}
```

Даже так не работает.

**Comment by Y0ba** [comment]
По идее можно встраивать во фреймы как простой скрипт, а с хранилищем общаться через `postMessage`, но будет это работать только если у `iframe` домен совпадает с доменом страницы.

**Comment by SthephanShinkufag** [comment]
На сосаче не ифреймы, там

```js
<frameset cols="15%,*" frameborder="1" border="1">
        <frame src="menu.html">
        <frame src="/b/" name="main">
        <noframes><a href="menu.html">Меню</a></noframes>
</frameset>
```

**Comment by SthephanShinkufag** [comment]
> contentDocument
> document

Без разницы. И так, и так работает, но при выполнении события

```
> console.log(doc.body.innerHTML)
> ''

> console.log(window.location)
> Location about:blank
```

**Comment by SthephanShinkufag** [comment]
> слегка переделать скрипт

Просвети, Йоба. Как именно.

**Comment by Y0ba** [comment]
> Без разницы. И так, и так работает, но при выполнении события

Потому что обновляется и `contentWindow` внутри фрейма на которое событие `load` зарегестрировано, если запустить код внутри setTimeout, то всё сработает. Т.е. таким способом отследить загрузку фрейма невозможно, остаётся только поллинг (т.е. проверка каждые n миллисекунд). Можно проверять так:

```js
var frame = doc.querySelector('frame[name="main"]');
const processFrame = doc => doc.body.style.backgroundColor = "blue";
const checkFrame = () => {
	var fDoc = frame.contentDocument
	if (String(fDoc.defaultView.location) === "about:blank") {
		setTimeout(checkFrame, 20);
	} else {
		if (fDoc.readyState === 'loading') {
			fDoc.addEventListener('DOMContentLoaded', () => processFrame(fDoc));
		} else {
			processFrame(fDoc);
		}
	}
};
checkFrame();
```

**Comment by Y0ba** [comment]
Хотя, можно и так:
```js
var frame = doc.querySelector('frame[name="main"]');
const processFrame = () => frame.contentDocument.body.style.backgroundColor = "blue";
if (String(frame.contentDocument.defaultView.location) === "about:blank") {
	frame.onload = processFrame;
} else {
	processFrame();
}
```

**Comment by SthephanShinkufag** [comment]
Круто, работает! Спасибо, буду прикручивать к кукле.

**Comment by SthephanShinkufag** [comment]
Кстати, есть еще `DOMFrameContentLoaded`, только я с ним не разбирался еще.

**Comment by Y0ba** [comment]
> Просвети, Йоба. Как именно.

По идее добавить в `deMainFuncInner` параметр `deWindow` и провести аудит скрипта, чтоб он использовал только его и не обращался неявно к параметрам `window`. Тогда скрипт можно будет рекурсивно запускать в любом фрейме, поскольку он будет работать только со своим `window`.

> `DOMFrameContentLoaded`

Пишут что он только для firefox и только для привелигерованных страниц, так что возможно в юзерскрипте работать не будет.

**Comment by Y0ba** [comment]
Второй вариант: инжектировать скрипт в виде простого `script` тега, а доступ к GM-функция давать ему через `postMessage`. Недостаток в том, что дуступ к ним так же получат и скрипты странцы.

**Comment by SthephanShinkufag** [comment]
Выяснил, что при `@run-at document-start` юзерскрипт выполняется во всех фреймах, но с `about:blank`. То есть, нужно ждать загрузки фреймов как ты описал выше.
Короче, всё сделал, куклоскрипт даже начинает исполняться, но на `GM.getValue` почему-то всё затыкается. 

Вот тестовый скрипт:

```js
// ==UserScript==
// @name     Unnamed Script 723591
// @version  10
// @run-at   document-start
// @grant    GM.getValue
// ==/UserScript==

var frame = window.frameElement;
const processFrame = async () => {
  if(frame) {
  	frame.contentDocument.body.style.backgroundColor = 'blue';
    console.log('frame: ' + String(frame.contentDocument.defaultView.location));
  } else {
	console.log('top: ' + String(window.location));
  }
  let value;
	try {
		value = await GM.getValue('Test');
	} catch(e) {
		console.log(e);
	}
  console.log('value: ', value);
};

if(frame && String(frame.contentDocument.defaultView.location) === 'about:blank') {
	frame.onload = processFrame;
} else {
	if(frame && frame.contentDocument.readyState === 'loading') {
		frame.contentDocument.addEventListener('DOMContentLoaded', () => processFrame());
	} else {
		processFrame();
	}
}
```

Запускаем на https://2ch.hk/frame.html и смотрим консоль:

```
top: https://2ch.hk/frame.html
value:  undefined
frame: https://2ch.hk/menu.html
frame: https://2ch.hk/b/
```
`try-catch` изначально не было, но и он молчит. Просто исполнение затыкается и всё.

**Comment by SthephanShinkufag** [comment]
Короче, `GM.getValue` недоступен во фреймах.
Лучше бросить эту затею, гризманки кивой, и всё тут.

**Comment by Y0ba** [comment]
У меня все три value отображаются. Странно.

**Comment by SthephanShinkufag** [comment]
Firefox 63.0 (64-bit)
Что у тебя?

Видимо, придется таки исполнять куклу только из топового окна, искать каждый фрейм. Как изначально и оговаривалось.

**Comment by SthephanShinkufag** [comment]
Да, проверил, в Nightly `GM.getValue` работает везде.
