### ISSUE TITLE
Make "minWebmWidth" work as expected v2

### ISSUE THREAD

**Issue by ganego** [SthephanShinkufag/Dollchan-Extension-Tools#1262]
See https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/issues/1235#issuecomment-402496900
Not sure if that is a proper fix, but I don't see a problem in the past days.

**Comment by SthephanShinkufag** [comment]
https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/commit/3d3d69306d0a783ebc3e9ddfae5706e03956df30#diff-e35c77c8a1b47e8a79a4822aa292a8df2b49e1b1d044af7a839f14b09077cc64R494
