### ISSUE TITLE
Чёрные кнопки.

### ISSUE THREAD

**Issue by solara322** [SthephanShinkufag/Dollchan-Extension-Tools#1264]
Кнопки на панельке почему то стали чёрные. Стиль не менял. 
https://image.ibb.co/k7EOmK/05_08_2018_130645.png

**Comment by SthephanShinkufag** [comment]
Что за браузер?
В каком скрипт-менеджере установлен Dollchan?
Что за имиджборд?

**Comment by solara322** [comment]
Chrome 
tampermonkey 
2ch
и на любых другие тоже. 2 месяца всё было норм изначально, потом просто так, то есть я никаких дополнений не ставил и скриптов тоже и кнопки сами по себе стали чёрные.
