### ISSUE TITLE
Отвалилась капча.

### ISSUE THREAD

**Issue by bugreporteur** [SthephanShinkufag/Dollchan-Extension-Tools#1265]
Сабж.
https://imgur.com/a/UAqvErw

**Comment by LLlOZAHAX** [comment]
Подтверждаю. 2chcaptcha теперь всегда невалидна. Еасколько помню - раньше была функция переключения в кукле на такие случаи шатания. Ныне выпилена? Не могу найти.

**Comment by KTheRD** [comment]
Да, отвалилась. Нужна гуглокапча.

**Comment by apan65** [comment]
Вроде же был выбор капчи в настройках, сейчас не нашел

**Comment by solara322** [comment]
сейм

**Comment by CherryPerry** [comment]
Откатился на https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/commit/a303c50d75c352582cea71a20ace3c10485bc418 версию. Гуглокапча работает, но избранное по понятным причинам отвалилось.

**Comment by proftwist** [comment]
А как на эту версию обновиться, если стоит версия с Tape Monkey? Автоматически обновлять не хочет.

**Comment by CherryPerry** [comment]
@proftwist https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/raw/a303c50d75c352582cea71a20ace3c10485bc418/src/Dollchan_Extension_Tools.es6.user.js

**Comment by proftwist** [comment]
Спасибо, обновился, заработало.

**Comment by SthephanShinkufag** [comment]
о_0
Зачем меня из потустороннего плана призвали? Ааргххх.

**Comment by reallyuniquename** [comment]
Спасибо. Только теперь в /d/ капчи нет.

**Comment by reallyuniquename** [comment]
Что-то все равно гуглокапчи нет в /d/. В остальных разделах нормально работает.

**Comment by SthephanShinkufag** [comment]
У меня всё работает. Гуглокапча есть.
Вы, скорее всего, не используете скрипт с последнего коммита.

**Comment by SthephanShinkufag** [comment]
https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/raw/master/src/Dollchan_Extension_Tools.es6.user.js

**Comment by bugreporteur** [comment]
Странно, но у меня ни на одном браузере с последней версией не заработало.
https://imgur.com/a/YZHgGZl

**Comment by reallyuniquename** [comment]
Вы правы, теперь все работает. Спасибо.

**Comment by SthephanShinkufag** [comment]
@bugreporteur

2chaptcha не работает даже без куклоскрипта.
Заходите в `Настройки` - `Форма` - `Использовать альтернативную капчу` и отключаете опцию!

**Comment by reallyuniquename** [comment]
В /d/ гуглокапча всегда оказывается неправильной, пробовал раз 10-20. В остальных разделах с первого раза решается. На моей стороне проблемы?

**Comment by SthephanShinkufag** [comment]
@reallyuniquename 

87fff309b032709d2329921a10271ab521be259a

https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/raw/master/src/Dollchan_Extension_Tools.es6.user.js

**Comment by reallyuniquename** [comment]
Сейчас все заработало, хотя у меня и так последняя версия вроде была.

@SthephanShinkufag Скажите, а можно что-то сделать с гуглокапчей, чтобы она не всплывала в произвольное время посередине страницы. Хотя бы на кнопку это повесить, а то сейчас приходится делать какую-то комбинацию: закрыть капчу, написать пост, отправить без капчи, потом ввести капчу.

**Comment by SthephanShinkufag** [comment]
@DimoNline , а без куклоскрипта всё работает?
