### ISSUE TITLE
Метадата WEBM

### ISSUE THREAD

**Issue by TELEUZI** [SthephanShinkufag/Dollchan-Extension-Tools#1266]
Если
>Получать названия WebM из метаданных 
То получается https://ibb.co/jAKCvp
Из-за точки в метадате воспринимает как расширение.

**Comment by SthephanShinkufag** [comment]
Глупый хром берёт название файла из атрибута `title` видео-элемента, в отличие от Лисы. Еще и криво обрабатывает символ точки. Этого чисто баг хрома, а не скрипта.

**Comment by SthephanShinkufag** [comment]
Сделал костыль, который убирает все точки из загруженных метаданных.
