### ISSUE TITLE
Неправильная работа Hide by selected text [?]

### ISSUE THREAD

**Issue by zbczyvgy** [SthephanShinkufag/Dollchan-Extension-Tools#1267]
Решил напердолить фаерфокс, до того все время пользовался хромом.
Вот добавил `bst`, руками. Ничего. Жму `Apply`. Ничего.
Прежде чем добавить руками, просто выделил текст и нажал `Hide by selected text`.
Вместо `#words(/bst) |` добавилось `#exph(//bst/) |`. Да, с этим все прекрасно скрывается и работает, но я более чем уверен, что в хроме работало и с `#words`, так как я часто это правил руками.
![screen](https://my.mixtape.moe/ycszcx.png)

**Comment by SthephanShinkufag** [comment]
Сейчас можете повторить баг?
Дайте ссылку на тред, покажите список спеллов, и укажите какой спелл хотите добавить
