### ISSUE TITLE
[Flash Video Downloader] Блокирует отправку постов с опцией "Отправка постов без перезагрузки*"

### ISSUE THREAD

**Issue by OskarZeta** [SthephanShinkufag/Dollchan-Extension-Tools#1268]
Добрый день, возникла проблема с картинками - при попытке отправить пост с прикреплённой пикчей вылезает "Ошибка подключения", при этом на дваче загрузочный спиннер сначала пару секунд висит на 100%, а затем начинает рисовать какую-то дичь (пикрилейтед)
![loading](https://user-images.githubusercontent.com/20010735/44399098-ebfc1b00-a54e-11e8-865d-1f757fbe7f6b.jpg)
Без куклы всё грузится нормально.

Кукла установлена в Tampermonkey
Версия куклы последняя (18.8.9.0.87fff30)
Браузер - лиса (тоже последняя на данный момент, 61.0.2)

**Comment by SthephanShinkufag** [comment]
Проблема до сих пор есть?

**Comment by SthephanShinkufag** [comment]
На странице с сосачем откройте `"Настройки" (Alt+S)` - вкладка `"Инфо"` - кнопка `"Отладка"`, и запостите сюда содержимое.

**Comment by OskarZeta** [comment]
Затёр инфу по спеллам (поля "spells" в "Cfg", "sSpells" и "oSpells"), если необходимо - пришлю.

{
	"version": "18.8.9.0.87fff30",
	"location": "https://2ch.hk/b/",
	"nav": {
		"ua": "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0 [20181018182531]",
		"scriptHandler": "Tampermonkey 4.8.5847",
		"isESNext": false,
		"isFirefox": true,
		"firefoxVer": 63,
		"isWebkit": false,
		"isChrome": false,
		"isSafari": false,
		"isPresto": false,
		"isMsEdge": false,
		"isGM": false,
		"isNewGM": true,
		"isChromeStorage": false,
		"isScriptStorage": false,
		"isGlobal": true,
		"hasGMXHR": true,
		"canPlayMP3": true,
		"hasTemplate": true,
		"hasWorker": true
	},
	"Cfg": {
		"timePattern": "dd+nn+yy+w+hh+ii+ss",
		"addVocaroo": 0,
		"expandPanel": 1,
		"cfgTab": "info",
		"noSpoilers": 0,
		"webmVolume": 12,
		"textaWidth": 766,
		"textaHeight": 236,
		"favOnReply": 0,
		"spacedQuote": 0,
		"altCaptcha": 1
	},
	"perf": {
		"Imageboard check": 1,
		"Storage loading": 1,
		"Init": 3,
		"Read my posts": 1,
		"Replace delform": 0,
		"Parse delform": 21,
		"Parse postform": 8,
		"Init keybinds": 2,
		"Init page": 0,
		"Add panel": 1,
		"Init AJAX": 0,
		"Preload images": 1,
		"Audio links": 0,
		"Video links": 1,
		"Image names": 12,
		"Reflinks map": 3,
		"Apply CSS": 5,
		"Display page": 0,
		"Infinity scroll": 0,
		"Hide posts": 46,
		"Image-links": 0,
		"Scroll page": 0,
		"Всего": 106
	}
}

**Comment by SthephanShinkufag** [comment]
Я до сих пор всё также не могу воспроизвести ваш баг. 
Firefox 64.0 (64-бит), Tampermonkey v4.8.5847, применены ваши настройки.

Попробуйте отключить временно ВСЕ расширения и дополнения, кроме Tampermonkey, а в Tampermonkey отключить все скрипты кроме Dollchan.

**Comment by SthephanShinkufag** [comment]
Какое именно дополнение, не скажете? Чтобы знать на будущее. Блокировщик какой-то?

**Comment by OskarZeta** [comment]
Нет, не блокировщик, приблуда для скачивания видео со всяких ютубов - Flash Video Downloader.

**Comment by SthephanShinkufag** [comment]
Благодарю за ответ, надо ознакомиться, как оно ломает.
И вы 4 месяца пользовались Dollchan без возможности отправлять картинки?

**Comment by OskarZeta** [comment]
Ага. Я всё равно 99% времени в ридонли, поэтому это не слишком напрягало, если честно.

**Comment by SthephanShinkufag** [comment]
Этот аддон блокирует POST-запросы, если используется `FormData` при отправке запросов.
Придётся что-то одно отключать на время пользования другим.
