### ISSUE TITLE
Настройки названий картинок

### ISSUE THREAD

**Issue by Turbolalka9000** [SthephanShinkufag/Dollchan-Extension-Tools#1276]
А можно рядом с настройкой отображения имён картинок добавить переключатель `Передавать имя файла/Не передавать имя файла/Передавать только длинные (сокращаемые троеточием) имена файла`? И откуда это имя файла будет браться, `Метаданные/Как загрузили на сайт`. Ну или отключаемую кнопку `Скачать` с настройкой как выше написал.
Бывает нужно скачать файл с оригинальным именем или с номером, выданным абучаном, а выбора нет (или я не заметил).

**Comment by solara322** [comment]
Тоже хочу. Я для себя называю вемб, и не хочу чтобы моё название видели другие.

**Comment by WagonOfDoubt** [comment]
Хотелось бы поле ввода для имени файла, чтобы не переименовывая локальный файл иметь возможность указать его название для конкретного поста.

**Comment by Remu-rin** [comment]
> Тоже хочу. Я для себя называю вемб, и не хочу чтобы моё название видели другие.

Была с древних времён настройка во вкладке Форма с урезанием до .ext. С некоторых пор и unixtime вариант есть.

> Хотелось бы поле ввода для имени файла, чтобы не переименовывая локальный файл иметь возможность указать его название для конкретного поста.

А вот эту фичу удваиваю. И в идеале ещё настройка к unixtime варианту для генерации рандомного момента за период в прошлом, например год или более. Будет неотличимо от варианта, когда человек когда-то сохранил файл с борды и потом запостил. Сейчас берется текущее время и это палевно даже визуально, очень близко к unixtime, который дала файлу сама борда.

**Comment by SthephanShinkufag** [comment]
![rename_files_button](https://user-images.githubusercontent.com/1059874/50059319-fe4d3500-018d-11e9-86aa-23231dcb3948.jpg)

Теперь появилась ещё одна кнопка управления прикреплённым файлом.
По нажатию открывается текстовое поле для редактирования имени файла. В это же поле можно по-прежнему, как и ранее вставлять ссылки, перетягивать картинки, et cetera.

Переименованный файл *имеет приоритет* над опцией `"[Удалять][Unixtime] имена файлов"`. Его эта опция не трогает. Так, если у вас будет выбрана опция `"[Unixtime] имена файлов"`, и например прикреплено три файла, и один вы переименуете, то он отправится с вашим именем, а два других будут иметь юникстайм.

**Comment by SthephanShinkufag** [comment]
> настройка к unixtime варианту для генерации рандомного момента за период в прошлом, например год или более

Слишком экзотическая фича. Из-за полутора параноиков захламлять и так забитое окно настроек не хочу.
Могу просто сделать фиксированное вычитание, 2 года, например.

**Comment by SthephanShinkufag** [comment]
> И в идеале ещё настройка к unixtime варианту для генерации рандомного момента за период в прошлом, например год или более.

Могу сделать вариант селектора:
"[Не изменять][Удалять][Unixtime][Unixtime-random] имена файлов"

`Unixtime-random` будет выбирать рандомный момент до 5 лет в прошлое, например.

**Comment by Remu-rin** [comment]
> Могу сделать вариант селектора

Было бы прекрасно. Спасибо.

**Comment by SthephanShinkufag** [comment]
@Remu-rin 
Сделано.

**Comment by SthephanShinkufag** [comment]
![Image_links_02](https://user-images.githubusercontent.com/1059874/113620510-11d48080-9663-11eb-9ff0-41738fc31d40.jpg)
![Image_links_01](https://user-images.githubusercontent.com/1059874/113620523-14cf7100-9663-11eb-9c8b-356da24ffd80.jpg)

Теперь кнопка поиска картинок выдаёт ссылку на скачивание картинки с именами:
1. С оригинальным именем
2. Для webm - с именем, полученным из метаданных (при включённой опции `"Картинки"` > `"Получать названия WebM из метаданных"`)
2. С номером, выданным доской.

Метаданные, загруженные из webm, теперь выделяются жёлтым цветом.
