### ISSUE TITLE
whatanime.ga has moved to trace.moe

### ISSUE THREAD

**Issue by soruly** [SthephanShinkufag/Dollchan-Extension-Tools#1278]
Hello, I'm (was) the owner of whatanime.ga
A few days ago, the .ga domain was taken down by freenom T_T,
so the site has moved to https://trace.moe
if you are still actively supporting this project, please update the URL, thank you m(_ _;)m

**Comment by SthephanShinkufag** [comment]
Thank you for letting me know!
˘◡˘
