### ISSUE TITLE
Показывать количество непрочитанных постов в названии или иконке таба

### ISSUE THREAD

**Issue by alexc363** [SthephanShinkufag/Dollchan-Extension-Tools#1279]
Реквестирую фичу, чтобы куклоскрипт показывал количество непрочитанных сообщений в названии вкладки, как это сейчас сделано на дваче. Браузер Vivaldi умеет делать бейджики, если название вкладки содержит число в скобках (пикрил). Значок плюса, который показывает куклоскрипт, занимает примерно столько же места, а особой информативности не несёт. Да и не очень красиво смотрится. Но плюсы можно оставить как одну из опций, вдруг они кому-то больше нравятся.

Третьей опцией можно сделать, чтобы куклоскрипт рисовал бэйджи с числами на фавиконах сам или при помощи favicon.js. Это решение хорошо тем, что будет работать во всех браузерах даже когда на вкладках не помещается текст или они прикреплены. И к тому-же можно сделать разные цвета бейджей. Оранжевый - если нет ответов на твои сообщения, синий - если есть. Т.е. как сейчас цвета значков плюса. 

Ссылки по favico.js:
https://github.com/ejci/favico.js
http://lab.ejci.net/favico.js/
https://webdesign.tutsplus.com/tutorials/how-to-display-update-notifications-in-the-browser-tab--cms-23458

Если нужно, могу помочь программированием, т.к. я программист. Но мне нужно тыкнуть куда что писать, т.к. код куклоскрипта немаленький и разбираться во всём нет особо времени

**Comment by Y0ba** [comment]
Дополнительные библиотеки не нужны. В скрипте уже есть всё необходимое. Плюсики рисуются через канву (чтобы работало на всех бордах). Можно дополнительно нарисовать с цифрами от 0 до 9 (в случае переполнения рисовать как и раньше плюсик). Вот код:
https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/blob/8ecf532a9e79d469a4cf8b730aa09bdea25440c9/src/modules/ThreadUpdater.js#L200-L220

**Comment by SthephanShinkufag** [comment]
Готово.

![favicons_newposts](https://user-images.githubusercontent.com/1059874/47621042-8aca6800-dafa-11e8-99b4-beee312672d2.png)

Отображается количество до 9. После этого отображается плюс, как и раньше.

**Comment by SthephanShinkufag** [comment]
Убрать дублирование в квадратных [ ] скобках? Чтобы отображались только от 10.

**Comment by alexc363** [comment]
Да, можно убрать для экономии места. Или сделать настройку - показывать бейдж / показывать в скобках / показывать и так и так

**Comment by SthephanShinkufag** [comment]
9+ не поместится в кружочке.
> Сам по себе плюс обычно обозначает добавление чего-то
Пять лет там был плюс, и всех всё устраивало.

**Comment by alexc363** [comment]
> 9+ не поместится в кружочке.
Можно сделать меньше шрифт, когда 2 символа. Не обязательно, чтобы легко читался текст, просто сразу будет видно, что два символа, значит много сообщений. Так сделано в некоторых мессенджерах.

> Пять лет там был плюс, и всех всё устраивало.
Ну это вкусовщина. Мне плюс никогда особо нравился, поэтому я и предложил улучшение. В любом случае спасибо за быструю доработку. Я только собирался вникать в код

**Comment by SthephanShinkufag** [comment]
Для соблюдения единообразия убрал плюсы, теперь в кружочках троеточие. Новые посты в скобках меньше [10] не отображаются, чтобы не дублировать информацию.

**Comment by perdolka** [comment]
Блин, от зелёного/белого вылезают глаза в попытке распознать цифру.
Синий норм.
Может контрастнее сделать (темнее зелёный)?

**Comment by perdolka** [comment]
![default](https://user-images.githubusercontent.com/24720263/47913228-02eeb000-dea4-11e8-8059-38c8353d99c4.png)
