### ISSUE TITLE
Скрипт несовместим с Gulp 4

### ISSUE THREAD

**Issue by Y0ba** [SthephanShinkufag/Dollchan-Extension-Tools#1281]
Недавно обновил `node.js` и gulp отказался парсить `gulpfile.js`, пришлось явно указывать версию gulp@3.9.1. Надо его исправить, поскольку есть несовметимости.

https://codeburst.io/switching-to-gulp-4-0-271ae63530c0

**Comment by SthephanShinkufag** [comment]
```
$ npm rm -g gulp
$ npm install -g gulp-cli
$ npm uninstall gulp --save-dev
$ npm install gulp@next --save-dev
```

**Comment by SthephanShinkufag** [comment]
Ой вей, не туда сослался.
