### ISSUE TITLE
[2ch] Прилипает сажа

### ISSUE THREAD

**Issue by XakepSDK** [SthephanShinkufag/Dollchan-Extension-Tools#1282]
Постоянно прилипает сажа, не могу уже. Пока не нажму на вкл/выкл сажу, то 100% сообщение будет с сажей.

**Comment by SthephanShinkufag** [comment]
Всё просто. Вы без куклы постили что-то с сажей, и сосач это запомнил. Сосачевские скрипты срабатывают позже куклоскрипта, и переопределяют кукловые настройки сажи. Сделал принудительную установку состояния сажи при отправке поста. Попробуйте скрипт с этим коммитом.
Скажите, помогло или нет. Если нет, тогда выключите Dollchan, обновите страницу и снимите галочку сажи в форме быстрго ответа.

**Comment by XakepSDK** [comment]
Вроде заработало как надо! Спасибо.
