### ISSUE TITLE
Реквест фичи. Менюшка скрытия поста.

### ISSUE THREAD

**Issue by NEONZARIN** [SthephanShinkufag/Dollchan-Extension-Tools#1283]
Собственно добавление всего функционал менюшки по скрытию поста для поста который в данный момент просматривается по ссылке поста (точно не знаю название). Думаю на картинке все понятно изобразил.
![image](https://user-images.githubusercontent.com/16442992/47936209-03ac3400-deee-11e8-8536-f8993ae9d00e.png)

**Comment by SthephanShinkufag** [comment]
Этот функционал был, просто не работал корректно для превью.
