### ISSUE TITLE
Не работает на lolifox

### ISSUE THREAD

**Issue by XakepSDK** [SthephanShinkufag/Dollchan-Extension-Tools#1284]
Не работает на lolifox.
https://puu.sh/BVCrw/eead01135b.png
Нажимаю на обе кнопки, ничего не происходит.

**Comment by SthephanShinkufag** [comment]
И не должен. Это ваша проблема. Там встроенный Dollchan, бороться со встраиваемыми копиями скрипта бесполезно, так как гарантированно добиться того, чтобы юзерскрипт грузился первее встроенных скриптов невозможно.
Отключайте встроенный Dollchan блокировщиками..
Установите uBlock, и добавьте в "Мои фильтры" строку:
```
||lolifox.org/js/dollchan2.js$script,first-party
```
В Firefox работает, в хроме не проверял.
