### ISSUE TITLE
[request] hide by ID - lolifox.org/polru

### ISSUE THREAD

**Issue by perdolka** [SthephanShinkufag/Dollchan-Extension-Tools#1285]

**Comment by SthephanShinkufag** [comment]
А описать подробнее как-то не судьба?

**Comment by perdolka** [comment]
На доске /polru/ лолифокса есть айдишники. 
Было бы неплохо добавить в список функций, которые спрятаны под кнопкой "Hide/Unhide post" возможность скрывать по этому айди.

**Comment by SthephanShinkufag** [comment]
Используйте спеллы. При чём тут я.

**Comment by XakepSDK** [comment]
А какой спелл использовать?

**Comment by SthephanShinkufag** [comment]
```
#exph(/<span class="poster_id">d6ffdc</span>/)
```

Например.
