### ISSUE TITLE
lolifox не могу запостить

### ISSUE THREAD

**Issue by XakepSDK** [SthephanShinkufag/Dollchan-Extension-Tools#1286]
Такая ошибка
Internal error: TypeError: txt.trim is not a function at $popup (Dollchan%20Extension%20Tools:5580:29) at checkUpload (Dollchan%20Extension%20Tools:9498:3)

v18.8.9.0.222665a.es6

**Comment by SthephanShinkufag** [comment]
Всё нормально постится. Firefox 63.0.1, Tampermonley 4.8.5847.

uBlock Origin 1.17.2:
```
||lolifox.org/js/dollchan2.js$script,first-party
```

Браузер, скрипт-менеджер, блокироващик, правила блокировщика?
Что не можете запостить, картинку, текст, или вообще ничего?
Больше данных, хуле вы как не родной.

**Comment by SthephanShinkufag** [comment]
Может, вы вообще с какого-то другого домена заходите?
Вот список зарегистрированных доменов:

lisach.pw
lolifox.org
lisach7joohmqk3a.onion
d4pdldleatdext7ejb45c3uxg67eddl2pwftnxpm4thwtjigci3rmrqd.onion

**Comment by XakepSDK** [comment]
Firefox 63.0.1, Greasemonkey, куклоскрипт самого сайта заблокирован.
lolifox.org
Не работает только тут, как я понял: https://lolifox.org/polru/

**Comment by SthephanShinkufag** [comment]
Всё постится с Greasemonkey.
Попробуйте с Violentmonkey. Поэкспериментируйте с фильтрами блокировщика.
Может, у вас не получается запостить конкретный текст или конкретную картинку?
Не хотет ещё один `can't reproduce` issue...

**Comment by XakepSDK** [comment]
1. Установил violentmonkey
2. Сбросил настройки ublock
3. Заново включил блок встроенной куклы
Всё равно не постит.

**Comment by SthephanShinkufag** [comment]
Кукла пытается вывести сообщение об ошибке отправки, но затыкается.

Найдите в скрипте строку `$popup('upload', error);`, и поместите перед ней `console.log(error);`:
```js
console.log(error);
$popup('upload', error);`
```
 Попробуйте запостить с этим скриптом. Что пишет в консоли?

**Comment by XakepSDK** [comment]
https://puu.sh/C08Mn/11967d6d71.png
https://puu.sh/C08N4/da83f02f1b.png

**Comment by XakepSDK** [comment]
Теперь могу постить. Мб что-то на самом лисаче было, либо ты как-то случайно зафиксил.
