### ISSUE TITLE
[харкач] не работает цифрокапча

### ISSUE THREAD

**Issue by perdolka** [SthephanShinkufag/Dollchan-Extension-Tools#1287]
кукла: 18.11.10.1.a7dfc86
ФФ: 60.3.0esr

Переключение на гуглокапчу в настройках харкака не работает.
Получаю сообщение об ошибке отправки поста: 
_Ошибка: Капча невалидна._

Временное решение - отключаю куклу на момент постинга, после отправки включаю обратно.

**Comment by bugreporteur** [comment]
Та же проблема.

**Comment by SthephanShinkufag** [comment]
> не работает цифрокапча
> Переключение на гуглокапчу в настройках харкака не работает

Так и не понял, какая какая не работает?

**Comment by perdolka** [comment]
2chaptcha
Извиняюсь, я забыл об этой галочке:
![default](https://user-images.githubusercontent.com/24720263/48433463-d4b08080-e77f-11e8-8c8a-c8304639a050.png)

**Comment by besteady** [comment]
> Так и не понял, какая капча не работает?

Цифровая, которая при галочке на "Использовать альтернативную капчу". Всегда выдает
> ✖   Ошибка: Капча невалидна.

Гуглокапча у меня работает.

**Comment by SthephanShinkufag** [comment]
Переключать капчу нужно не в настройках сосача, а в куклоскрипте:

`"Настройки"` > `"Форма"` > `"Использовать альтернативную капчу"`

**Comment by SthephanShinkufag** [comment]
Приехал домой, сел за пекарню проверил &mdash; 2chaptcha не работает даже без куклы, что-то там админ нашатал.

**Comment by SthephanShinkufag** [comment]
Короче, пинайте Абу, цифрокапча там сломана, кукла тут не при чём вообще.
