### ISSUE TITLE
Иконка счетчиков новых постов

### ISSUE THREAD

**Issue by RosinSmoke** [SthephanShinkufag/Dollchan-Extension-Tools#1289]
Недавно обновился, а вместо привычного плюса, который можно было с орбиты разглядеть, появился зелёный кружок, который сливается с большинством существующих иконок. Особенно на форчане напрягает, откроешь в лисе выпадающий вертикальный список вкладок, крутишь вверх-вниз и вчитываешься в каждую строку, когда раньше сразу видно было где новый пост. Ярко-жёлтый и синий цвет реально цеплялись за глаза, а количество новых постов гораздо нагляднее в заголовках текстом чем мелкой белой цифрой на светло-зелёном фоне, на ips это ещё как-то видно, но на тнфилмах вангую совсем ужас. Это можно как-то вернуть, хотя бы и локальной заменой куска кода? Я уже готов руками после каждого обновления его заново вставлять, настолько он удобнее.

**Comment by NEONZARIN** [comment]
Тоже согласен. Раньше было лучше.

**Comment by SthephanShinkufag** [comment]
Где вы видели ярко-жёлтый? Это было в версии трехлетней давности. Плюсы уже года три как были синие и зелёные, в точности как сейчас.

**Comment by RosinSmoke** [comment]
Полгода назад точно жёлтые помню. Энивей, нельзя ли хоть количество постов текстом в заголовках вернуть, раз мы теперь в принудительно-пастельных тонах?

**Comment by SthephanShinkufag** [comment]
Возможно, вы пользовались древней версией. Могу вернуть текст в квадратных скобках, пусть дублируются, ладно.

**Comment by RosinSmoke** [comment]
Мерси. Просто дело даже не в дублировании, а в том, что у плюса была довольно толстая рамка, делающая его заметной, а кружок пал жертвой антиалиасинга и на нём чёрной рамки даже не видно, пик релейтед [http://puu.sh/C3IT9/0ecbca126b.png](http://puu.sh/C3IT9/0ecbca126b.png)
На зелёном клевере зелёная иконка с белой цифрой, на цоцаче синий цвет сглаживанием наплыл на чёрную рамку. Ниже идёт как раз бесконечный лисотред который я 3 месяца не закрывал и там ещё старая версия, скобки сдвигают текст вправо и создают ещё один визуальный маркер среди слешей.
