### ISSUE TITLE
2ch.hk не работает нормально

### ISSUE THREAD

**Issue by aai2k** [SthephanShinkufag/Dollchan-Extension-Tools#1293]
Да когда твое говно начнет нормально работать? Какого хуя новые посты в б отображаются с какими-то кривыми двачую и рейдж, которые вообще непонятно откуда там могли взяться?
![image](https://user-images.githubusercontent.com/20245954/48741208-6a11b000-ec6b-11e8-8156-4a9d905fbc9b.png)

**Comment by Coloruts** [comment]
Не говорю, что и цвет и размер шрифта разные у старых постов и у постов, которые появились, когда ты зашел в тред(я про Аноним xx/xx/18 день время)

**Comment by SthephanShinkufag** [comment]
Потому что Абу применил новый тестовый движок в /b. Потому что нельзя предугадать, как поведет себя система при изменении внешних условий. Если вам вместо головы поместить жопу, то ничего ведь не должно измениться по вашей логике. Вы будете функционировать как обычно?

Лишние Двачую и RRRAGE исправлены были сразу. Вот ссылка на все последние исправления:
https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/raw/master/src/Dollchan_Extension_Tools.es6.user.js

**Comment by SthephanShinkufag** [comment]
Ставьте исправленный скрипт:

https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/raw/master/src/Dollchan_Extension_Tools.es6.user.js

Всё должно быть в порядке.

**Comment by perdolka** [comment]
> Да когда твое говно начнет нормально работать? 
Это нужно спрашивать у безумной макаки.
