### ISSUE TITLE
[Chrome extension]: Не работает на 2ch и 4chan

### ISSUE THREAD

**Issue by streamach** [SthephanShinkufag/Dollchan-Extension-Tools#1296]
Тащемта, в первом макака что-то переделал, и теперь скрипт не работает: рушится вёрстка, сломались кнопки ответа на пост (раньше можно было сразу ответить, нажав на кнопку, теперь вылезает стандартный макабовский ответ), съехало поле ответов. Плюс в тредах теперь, при обновлении, у новых постов пишется "ДВАЧУЮ RRRAGE!", даже не в разделах где можно рейтить. 
![image](https://user-images.githubusercontent.com/29983895/48979820-e3c0f800-f0c8-11e8-97f2-ac38ece1a18a.png)
Форчан же переехал на другой домен, и там скрипт вообще не активен.

**Comment by SthephanShinkufag** [comment]
https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/raw/master/src/Dollchan_Extension_Tools.es6.user.js

**Comment by SthephanShinkufag** [comment]
Прежде, чем создавать issue, убедитесь, что это уже не исправлено.

**Comment by SthephanShinkufag** [comment]
> съехало поле ответов

https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/issues/1295#issuecomment-441308722

**Comment by streamach** [comment]
А что делать, если стоит расширение для хрома, которое обновлено 10 ноября 2018 г.?

**Comment by SthephanShinkufag** [comment]
Почему вы не написали в оп-посте, что у вас расширение для хрома?
Я должен догадываться, или как?

Расширение обновлю потом.

**Comment by SthephanShinkufag** [comment]
Обновил хроморасширеие, ожидайте, скоро должно прилететь!
