### ISSUE TITLE
Капча невалидна 2ch.hk

### ISSUE THREAD

**Issue by DimoNline** [SthephanShinkufag/Dollchan-Extension-Tools#1300]
![image](https://user-images.githubusercontent.com/19239834/49698405-69b66600-fbd4-11e8-92e4-b36bd38e8289.png)

**Comment by SthephanShinkufag** [comment]
Какая капча?

**Comment by SthephanShinkufag** [comment]
Если вы про цифровую капчу, то она даже с отключенеым Dollchan не работает.

**Comment by SthephanShinkufag** [comment]
Сейчас на 2ch.hk есть только гугль-капча.
Dollchan по-прежнему может генерировать цифровую капчу, но она как видите не работает.
Заходите в `"Настройки"` (Alt+S) > `"Форма"` > отключаете опцию `"Использовать альтернативную капчу"`.
Я могу конечно запретить эту опцию, но Абу в любой момент может цифровую капчу включить опять.
