### ISSUE TITLE
[WebExtension][02ch.su]: Не отображает капчу

### ISSUE THREAD

**Issue by kiraseki** [SthephanShinkufag/Dollchan-Extension-Tools#1301]
Скрипт v18.11.25.0.b50a986.es6
Браузер 70.0.3538.77

В консоли браузера 
Uncaught TypeError: Cannot read property 'getAttribute' of null
    at Captcha.addCaptcha (Dollchan_Extension_Tools.es6.user.js:9781)
    at HTMLTextAreaElement.updCapFn (Dollchan_Extension_Tools.es6.user.js:8666)

В Firefox 60.3.0esr не воспроизводится.

**Comment by NEONZARIN** [comment]
Все работает. Полет нормальный.
![image](https://user-images.githubusercontent.com/16442992/49891900-b8743200-fe58-11e8-821b-e6528bd6032f.png)

**Comment by SthephanShinkufag** [comment]
Исправлено в скрипте. Сегодня вечером обновлю хроморасширение.
