### ISSUE TITLE
2ch - reCaptcha.

### ISSUE THREAD

**Issue by MrBudda108** [SthephanShinkufag/Dollchan-Extension-Tools#1302]
С нововведением очень долго отправляются посты. Можно это дело опциональным сделать или пофиксить?

**Comment by SthephanShinkufag** [comment]
А вы отключите Dollchan, и увидите, что она грузится ровно столько же на голой макабе. Рекапча всегда долго вызывалась, просто раньше в Dollchan это происходило при фокусе в поле ответа, и пока вы набирали текст, рекапча грузилась, и вы этого не замечали. Минус был в том, что она выскакивала потом внезапно после загрузки в любое время. Так что покупайте у Абу пасскод, а мне это сырьё по поводу рекапча уже надоело. Сейчас всё работает в точности как в макабе.

**Comment by MrBudda108** [comment]
После обновления всё работает нормально. Спасибо.
