### ISSUE TITLE
[2ch.hk]: Долго грузится reCaptcha

### ISSUE THREAD

**Issue by HouyiTheArcher** [SthephanShinkufag/Dollchan-Extension-Tools#1303]
После обновления на последнюю версию ( скрипт ES6, браузер Firefox 60) оче долго начала подгружаться рекапча, секунд этак 20 минимум.

**Comment by SthephanShinkufag** [comment]
#1302

**Comment by SthephanShinkufag** [comment]
Не буду ничего пояснять. Пройдите по ссылке и прочитайте.
Мне надоело. Пока не буду закрывать этот issue, чтобы все видели.

**Comment by SthephanShinkufag** [comment]
Сосачеры заебали.
Заплптите Абу пасскод и не ебите мне мозги.

**Comment by NEONZARIN** [comment]
**ШОК! абу лично разрабатывает куклу!**

**Comment by SthephanShinkufag** [comment]
Вначале все хором ныли, что рекапча в кукле видите ли выскакивает внезапно после фоновой загрузки, пока вы набираете текст, а после того как я по многочисленным просьбам запилил ее загрузку после наджатия на кнопку "ответ" как в голой макабе, так теперь видите ли вам западло ждать её загрузку. Вы отключите куклу, и увиддите что она точно так же грузится. Хотели как в макабе - вот вам как в макабе. Хуле вы доебались.

**Comment by HouyiTheArcher** [comment]
Что началось-то? Где-то на харкаче или в кукле есть примечание насчёт механизма загрузки рекапчи, или любой юзер должен по факту знать механизм и скорость работы этой херни? Обновился куклоскрипт - стало дольше для юзера грузиться. Что юзер должен решить? Было бы уведомление после обновления, а не плашка с адресом доната - вопросов бы не было.
Если по теме - так действительно лучше, чем внезапно выскакивающая капча.

**Comment by SthephanShinkufag** [comment]
О чем я вас должен уведомлять?
Список всех изменений доступен в вики:
https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/wiki/versions

Я не обязан знать всех возможных проблем, ибо не г-сподь бог.
Может я вам должен уведомлять о погоде на завтра?

**Comment by HouyiTheArcher** [comment]
О том, что капча теперь будет "дольше" грузится.
У тебя там ПМС начался или что за истерика? Ряя погода, ряя не бог...

**Comment by SthephanShinkufag** [comment]
Можно включить мозг, отключить куклу, и увидеть, что там рекапча тоже долго грузится. Нет, сосачерам надо идти на гитхаб, на dscript.me и срать репортами о долго загружающейся рекапче.

**Comment by HouyiTheArcher** [comment]
Если отключить куклу, то она будет грузиться по-старому, после загрузки страницы, и визуально ВНЕЗАПНО будет казаться так же, как и на старой версии скрипта, "быстро", не?

**Comment by SthephanShinkufag** [comment]
Отключайте куклоскрипт, ваша воля, никто никому ничего не должен.
Я не на фуллтайм работе, чтобы быть кому-то здесь чем-то обязанным.

**Comment by HouyiTheArcher** [comment]
О, то юзеры были тупые, а теперь уже "никто не обязан ряя". Юзеры так же не обязаны шарить в механизме работы рекапчи на отдельно взятом харкаче. Не надо истерить в ответ на возникающие вопросы.

**Comment by SthephanShinkufag** [comment]
Рекапча грузится точно также, как и с отключенной куклой.

**Comment by Y0ba** [comment]
Может можно сделать как на форчане при отключённых скриптах? Там рекапча вообще становится няшной и удобной.

**Comment by SthephanShinkufag** [comment]
Кажется, выпил лишнего. Я под градусом становлюсь агрессивным.
Но тут реально накипело уже
Надо попробюовать прикрутить как говорил товарищ https://dscript.me/de/res/1.html#455

**Comment by Y0ba** [comment]
Я попробую сделать как на форчане. Fallback-версию (в виде альтернативы в опциях). Единственный недостаток: код капчи надо самому копипастить (впрочем можно исправить скриптом, просто запускать скрипт надо будет и внутри гуглокапчесвой iframe). Зато капча становится гораздо проще.

**Comment by SthephanShinkufag** [comment]
Жаль...
Провёл серию отправок постов с отключенным Dollchan.
Рекапча иногда грузится быстро, а иногда медленно. Всё зависит от сервера.
Заметил закономреность. Если капча с отключенным Dollchan отправляется медленно, то сразу же отправленный следующий пост со включенном Dollchan будет отправляться медленно. А бывают моменты, егда капча отправляется быстро и там, и там подряд.
То есть, на лицо временные промежутки, где рекапча имеет плохок конект с сервером.
