### ISSUE TITLE
[2ch.hk]: Не могу отправить пост со включенным пасскодом

### ISSUE THREAD

**Issue by slavutich32** [SthephanShinkufag/Dollchan-Extension-Tools#1304]
Доброго дня. После последнего обновления, посты отправляются дико долго. Плашка "загружено" и вращающийся круг на ней. Пасскод куплен. Без куклы посты отправляются мгновенно.

**Comment by slavutich32** [comment]
Если выйти через https://2ch.hk/2ch/ , в форме ответа нет надписи про пасскодобоярина, посты отправляются мгновенно. Капчи нет вообще. Зашел обратно, ввел пасскод - опять посты виснут с плашкой "загружено".

**Comment by SthephanShinkufag** [comment]
Капча есть, просто она невидимая. Если вы отправите подряд штук десять постов, она появится.
Так как мне лень тратить 500р на сосач, мне нужно, чтобы вы показали мне HTML-код формы ответа, чтобы я мог исправить Dollchan, выяснив, как элементы пасскода ломают отправку. Я сейчас напишу вам шаги, как это посмотреть. Думаю, там не будет информации о ключе пасскода.

**Comment by slavutich32** [comment]
С удовольствием постараюсь помочь. Давно юзаю куклу и без нее как без рук.

**Comment by SthephanShinkufag** [comment]
1. Зайдите в любой тред на https://2ch.hk/b/
2. **Отключите Dollchan**, включите пасскод, обновите страницу.
3. Откройте форму ответа, которая сверху треда, по кнопке `Ответить в тред`. Не быстрый ответ!
4. Правой кнопкой мыши по текстовой области, выберите пункт контекстного меню `"Исследовать элемент"`. Если у вас хром, то `"Просмотреть код"`.

![form_html_steps_0](https://user-images.githubusercontent.com/1059874/50045833-ad144700-00a2-11e9-8aa0-7805cc60f792.jpg)

5. Откроется инспектор HTML с указанием на элемент `textarea`. Найдите выше элемент `form`:
```html
<form id="postform" class="postform" action="/makaba/posting.fcgi" method="post" enctype="multipart/form-data" style="">
```
как показано на картинке:
![form_html_steps_1](https://user-images.githubusercontent.com/1059874/50045786-c2d53c80-00a1-11e9-97f9-f698e552f418.jpg)

6. Правой кнопкой мыши по нему > `Копировать` > `Внешний HTML`. В хроме по-моему также &mdash; `Копировать` > `Копировать outerHTML`.

![form_html_steps_2](https://user-images.githubusercontent.com/1059874/50045847-ccab6f80-00a2-11e9-8428-5945f2c3eda7.jpg)

7. отправьте содержимое на https://pastebin.com/, а ссылку на пасту мне сюда.

**Comment by slavutich32** [comment]
https://pastebin.com/bMM8TN8c

**Comment by SthephanShinkufag** [comment]
Спасибо. Я удаляю ваш пост, во избежание лишних глаз, мало ли что.

**Comment by SthephanShinkufag** [comment]
Разобрался. Сейчас починю!

**Comment by slavutich32** [comment]
Отлично!

**Comment by SthephanShinkufag** [comment]
Скажите, у вас установлен скрипт, или хроморасширение?

**Comment by slavutich32** [comment]
Аддон из хромомагазина.

**Comment by slavutich32** [comment]
![screenshot00089](https://user-images.githubusercontent.com/17064588/50046732-d76d0100-00b0-11e9-94f1-48f5f2f837fa.png)
Не получается. Скачал вышеуказанные файлы.

**Comment by SthephanShinkufag** [comment]
Ох, я не все файлы указал. Щас.

**Comment by SthephanShinkufag** [comment]
Держите, тут всё сразу. Распакуйте архив, и укажите путь туда.
http://rgho.st/8zT6x7grM

А я сейчас буду исправлять [руководство по установке](https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/wiki/installation), а то там устаревшая инфа.

**Comment by slavutich32** [comment]
Попробывал отправить с десяток постов, работает. Ура и спасибо!

**Comment by SthephanShinkufag** [comment]
Тогда ждите, когда я обновлю расширение для всех.
Пока можете пользоваться этим тестовым, но тут у вас будут дефолтные настройки и пустое избраное/мои посты/сркытые посты/спеллы, не пугайтесь.

**Comment by slavutich32** [comment]
Ничего страшного, хорошо что исправили!

**Comment by SthephanShinkufag** [comment]
Хех, даже на ргхост не надо было заливать, весь репо можно скачать сразу с гитхаба.
Исправил вики:
https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/wiki/Installation#google-chrome

**Способ 3**:

1. Скачайте [архив с репозиторием](https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/archive/master.zip), распакуйте его.

2. Зайдите в браузере на страницу ваших расширений, набрав в адресной строке `chrome://extensions/`

3. Установите галочку `"Режим разработчика"`, нажмите кнопку `"Загрузить распакованное расширение"`, укажите путь к папке `extension` в распакованном архиве, подтвердите.

**Comment by SthephanShinkufag** [comment]
Обновил хроморасширение.
