### ISSUE TITLE
2ch.hk - некорректное отображение индикатора постов на вкладке

### ISSUE THREAD

**Issue by perdolka** [SthephanShinkufag/Dollchan-Extension-Tools#1305]
![default](https://user-images.githubusercontent.com/24720263/50229569-4f8a3e00-03b3-11e9-9a3b-b3f5fc03857f.png)
Вот эта синенькая кругляшка с цифрой висит на вкладках тредов постоянно, 
после прочтения новых постов не исчезает, после обновления страницы не исчезает.

[цифра в квадратных скобках] - работает нормально:
![default](https://user-images.githubusercontent.com/24720263/50229765-b871b600-03b3-11e9-8c59-89befc165c2e.png)

Иногда синенькая кругляшка становится зелёной, закономерность пока не уловил:
![default](https://user-images.githubusercontent.com/24720263/50229885-05558c80-03b4-11e9-9eec-8dd5e4b26c71.png)

FF 60.3.0esr (x64)
Кукла v18.12.13.0.50ab7e9.es6
Violentmonkey 2.10.0

**Comment by perdolka** [comment]
У меня так на всех досках.

**Comment by SthephanShinkufag** [comment]
Пока я не воспроизведу этот баг у себя, я не смогу его починить.

**Comment by SthephanShinkufag** [comment]
Дайте ещё какую-нибудь зацепку. Закономерности в поведении, примерные шаги воспроизведения...
issue так и останется висеть месяцами.

**Comment by perdolka** [comment]
Только что удалил favicons.sqlite, favicons.sqlite-wal и favicons.sqlite-shm, очистил кэш - починилось, зашёл сообщить об этом. 
Вроде пока полёт нормальный.
