### ISSUE TITLE
[Enhancement] Обход капчи со звуком[reCaptcha]

### ISSUE THREAD

**Issue by XakepSDK** [SthephanShinkufag/Dollchan-Extension-Tools#1307]
Есть такой проект на python:
https://github.com/ecthros/uncaptcha2

В 85% случаев обходит капчу от гугла самим же гуглом, причём бесплатно.
Выглядит просто:
1. Достать вариант капчи со звуком
2. Загрузить звук на какой-нибудь сервис по распознаванию звука
3. Ввести полученные данные

Вот сама библиотека, там же есть ссылки на различные сервисы по определению текста по звуку:
https://github.com/Uberi/speech_recognition

**Comment by XakepSDK** [comment]
Ох, вот что нашёл:
https://github.com/dessant/buster
Расширение для браузера, отгадывает капчу.

**Comment by SthephanShinkufag** [comment]
Никакие обходы / ломалки / разпознаватели капчи мне внедрять не хочется.
Ни на Ычан, ни на Сосач, ни на Форчан, ни куда либо ещё.
Dollchan это хоть и комбайн свистелок и перделок, но не подобного рода.
Можете создать репо со своим собственным скриптом, который будет интегрироваться в Dollchan, но он не будет ко мне иметь никакого отношения.
Извините.
