### ISSUE TITLE
Архивач. Новый домен. Опять

### ISSUE THREAD

**Issue by perdolka** [SthephanShinkufag/Dollchan-Extension-Tools#1312]
У Архивача в очередной раз отключили домены (arhivach.cf, arhivach.tk,  arhivach.org и прочая).
Сайт по-прежнему доступен через Tor.
Новый домен - https://arhivach.gq

**Comment by SthephanShinkufag** [comment]
А чому его блокируют?

**Comment by perdolka** [comment]
А ХЗ

**Comment by GrayFace** [comment]
https://arhivach.ng

**Comment by ruzzke** [comment]
add arhivach.ng

**Comment by Chrizt** [comment]
arhivach.ng отвалился

**Comment by Getlostmoron** [comment]
fuck you
