### ISSUE TITLE
[4chan] "Captcha Fixes"

### ISSUE THREAD

**Issue by o8216488** [SthephanShinkufag/Dollchan-Extension-Tools#1313]
https://github.com/ccd0/4chan-x/wiki/Captcha-FAQ#why-do-i-have-to-copy-a-code-when-force-noscript-captcha-is-turned-on-but-other-users-dont
Сделай.

**Comment by SthephanShinkufag** [comment]
https://dscript.me/de/res/1.html#222
> Реквестирую автоматический копипаст когда носкрипт рекаптчи в поле.

Ага, надо будет запилить. Спасибо, что создали issue. Будет висеть как напоминание.

**Comment by SthephanShinkufag** [comment]
Closed due to the new captcha mechanism. #1402
