### ISSUE TITLE
[maybe 4chan?] Broken crossthread links

### ISSUE THREAD

**Issue by o8216488** [SthephanShinkufag/Dollchan-Extension-Tools#1315]
Links to posts in a different threads display as ">>000000000 →" and show the OP of that thread on hover. Happens on both -chan and -channel.
По-привычке написал на английском, ну да ладно.
И ведь иногда работает нормально. Хуй знает, от чего зависит. Не от доски, не от бамплимита/архива.

**Comment by SthephanShinkufag** [comment]
Can't reproduce. Please show me a live (and not outaded) example of this bug.
I want to see it.

**Comment by o8216488** [comment]
https://boards.4channel.org/v/thread/447098902#447101735
https://boards.4channel.org/vg/thread/241122347#241122443
https://boards.4channel.org/g/thread/69387953#69389183
![brok](https://user-images.githubusercontent.com/46669853/51276943-34791100-19e7-11e9-93fb-a1e3c3567cb8.png)

**Comment by SthephanShinkufag** [comment]
Spasibo bolshoye for your help.
