### ISSUE TITLE
/2ch/capcha/google recaptcha 2.0

### ISSUE THREAD

**Issue by Autism-Corporation** [SthephanShinkufag/Dollchan-Extension-Tools#1318]
Степан можешь прикрутить к кукле дополнение https://chrome.google.com/webstore/detail/buster-captcha-solver-for/mpbjkejclgfgadiemmefgebjfooflfhl для обхода капчи, дабы лишний раз не кликать? При вызове капчи скрипт кликал бы на формочку антикапчи.

Ссылочка на гит:
https://github.com/dessant/buster

**Comment by SthephanShinkufag** [comment]
https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/issues/1307#issuecomment-451705361

**Comment by Autism-Corporation** [comment]
Я тебя понял, благодарствую.

**Comment by SthephanShinkufag** [comment]
Администраторы любого ресурса, не важно, имиджборда это или нет, очень не любят, когда пользователи обходят защиту, в данном случае капчу. Обход капчи это риск подставить под удар всех пользователей Dollchan, если кто-то из администрации решит бороться с куклоскриптом из-за этого.

**Comment by SthephanShinkufag** [comment]
Спасибо за понимание.
