### ISSUE TITLE
[Chrome] На https-бордах не грузит ссылки в форму по http

### ISSUE THREAD

**Issue by Chinpoko** [SthephanShinkufag/Dollchan-Extension-Tools#1321]
Собственно, всё в тайтле описано.

_Cent Browser Chromium 71.0.3578.98
Violentmonkey>Dollchan_Extension_Tools.meta.js_

![2019-02-18_102746](https://user-images.githubusercontent.com/47727202/52922117-31689c00-336a-11e9-9b35-76c374ce8c68.png)

**Comment by Bfgeshka** [comment]
А причём тут куклоскрипт, это же настройки hsts у тебя в браузере.

**Comment by Chinpoko** [comment]
> А причём тут куклоскрипт, это же настройки hsts у тебя в браузере.

Этож дефолтные настройки всех хромоногов, разве нет? Вот я и подумал, что кукла могла бы работать и с ними.

**Comment by SthephanShinkufag** [comment]
Chrome/Violentmonkey. Всё работает. При нажатии на "+" Violentmonkey спрашивает вас "Всегда разрешать домену", подтверждаю, и всё.
Видимол вы когда-то промахнулись, и не подтвердили запросы сос сторонних источников для Violentmonkey.

**Comment by SthephanShinkufag** [comment]
Я не знаю, как в Violentmonkey сбрасываются настройки, и где это настраивается.
Просто переустановите Vilolentmonkey, и при любом запросе выбирайте "Всегда доверять домену".
