### ISSUE TITLE
[Bug] [FF] [EXT] 8ch не показывает картинки

### ISSUE THREAD

**Issue by XakepSDK** [SthephanShinkufag/Dollchan-Extension-Tools#1323]
Не показывает картинки на 8ch.
1. Зайти на 8ch
2. Нажать на картинку
3. Серый popup

Firefox 66.0b10, установлено как расширение.
uBlock выключен.

**Comment by XakepSDK** [comment]
Если отключить предзагрузку, то всё работает.

**Comment by SthephanShinkufag** [comment]
Ничего сделать нельзя. На этом сайте применена директива CSP `default-src`, которая блокирует загрузку ресурсов `blob` на странице. Это разве что админа просить, чтобы убрал.

**Comment by XakepSDK** [comment]
Нельзя ли сделать список исключений, куда будут добавляться такие борды?
Возможно ли загружать картинки / webm не blob'ом, а невидимом img тегом, куда вставляется ссылка на картинку?

**Comment by SthephanShinkufag** [comment]
Вы не понимаете смысл и предназначение предзагрузки? Её предполагается включать, когда есть шанс, что тред в дальнейшем может быть недоступен. Соответственно, и ссылки на картинки будут недоступны. Для этого картинки закачиваются в память (в виде blob'ов), чтобы при недоступном треде извлекать из памяти полные версии картинок.

**Comment by SthephanShinkufag** [comment]
> список исключений, куда будут добавляться такие борды
Можно убрать из настроек опцию предзагрузки для 8ch.
А пока что выключите её, да и все дела. Имхо, одна из спорных фич Dollchan. зачем некоторые перманентно сидят со включенной предзагрузкой, генерируя бесполезный трафик, непонятно.

**Comment by SthephanShinkufag** [comment]
8ch is dead.
