### ISSUE TITLE
[Bug] Ошибка бесконечного скролла

### ISSUE THREAD

**Issue by DimoNline** [SthephanShinkufag/Dollchan-Extension-Tools#1324]
Уже несколько месяцев на 2ch.hk при включенной и выключенной опции "Infinite scrolling for pages" отображается только первая страница, отсутствует возможность перейти на другие страницы и нет бесконечного скролла.
![image](https://user-images.githubusercontent.com/19239834/53989427-0090b100-4137-11e9-949d-5547520dd6d1.png)
![image](https://user-images.githubusercontent.com/19239834/53989461-14d4ae00-4137-11e9-91b3-d591e1c5c968.png)

**Comment by Explaiz** [comment]
Сейм шыт, приходится ф5 постоянно нажимать

**Comment by SthephanShinkufag** [comment]
> при включенной и выключенной опции
Это как?

**Comment by SthephanShinkufag** [comment]
А с последними коммитами работает?
https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/raw/master/src/Dollchan_Extension_Tools.es6.user.js

**Comment by SthephanShinkufag** [comment]
Что за браузер и способ установки скрипта?

**Comment by Explaiz** [comment]
> Что за браузер и способ установки скрипта?

Хром, расширение. 
Работает через раз, иногда сколлит до последней, иногда не скроллит первую, иногда несколько скроллит, а потом всё - хватит. Хуй поймёшь от чего это зависит, мне кажется (с дивана), что проблема в функции "Показывать только ОР в списке тредов" или масштабировании (которое у меня 110)

**Comment by SthephanShinkufag** [comment]
Настройки - инфо - отладка.
Покажите содержимое.

**Comment by Explaiz** [comment]
{
	"version": "19.1.16.0.1c0195f",
	"location": "https://2ch.hk/v/",
	"nav": {
		"canUseFetch": true,
		"canUseFetchBlob": false,
		"canUseFetchCORS": true,
		"canUseNativeXHR": true,
		"firefoxVer": 0,
		"hasGlobalStorage": true,
		"hasGMXHR": false,
		"hasNewGM": false,
		"hasOldGM": false,
		"hasPrestoStorage": false,
		"hasWebStorage": true,
		"isChrome": true,
		"isESNext": true,
		"isFirefox": false,
		"isMsEdge": false,
		"isPresto": false,
		"isSafari": false,
		"isWebkit": true,
		"scriptHandler": "WebExtension",
		"ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36",
		"canPlayMP3": true,
		"hasTemplate": true,
		"hasWorker": true
	},
	"Cfg": {
		"timePattern": "dd+nn+yy+w+hh+ii+ss",
		"addVocaroo": 0,
		"updDollchan": 0,
		"cfgTab": "info",
		"postBtnsCSS": 0,
		"showHideBtn": 2,
		"noSpoilers": 2,
		"imgInfoLink": 0,
		"markViewed": 1,
		"linksOut": 650,
		"replyWinDrag": 1,
		"replyWinY": "top: 145.69601440429688px",
		"removeFName": 3,
		"favOnReply": 0,
		"scriptStyle": 4,
		"spells": "[1554232393484,[[255,[[522,\"\",null],[0,\"/owl/\",null]]],[255,[[522,\"\",null],[0,\"/mtga/\",null]]],[255,[[522,\"\",null],[0,\"/lolg/\",null]]],[255,[[522,\"\",null],[0,\"/fgoalter/\",null]]],[255,[[522,\"\",null],[0,\"/tf2/\",null]]],[255,[[522,\"\",null],[0,\"/hsg/\",null]]],[255,[[522,\"\",null],[0,\"/alg/\",null]]],[255,[[522,\"\",null],[0,\"/factory/\",null]]],[255,[[522,\"\",null],[0,\"/honkai/\",null]]],[255,[[522,\"\",null],[0,\"/dmc/\",null]]],[255,[[522,\"\",null],[0,\"/wowg/\",null]]],[255,[[522,\"\",null],[0,\"/dbd/\",null]]],[255,[[522,\"\",null],[0,\"/anthem/\",null]]],[255,[[522,\"\",null],[0,\"/bfg/\",null]]],[255,[[522,\"\",null],[0,\"/sandbox/\",null]]],[255,[[522,\"\",null],[0,\"/quake/\",null]]],[255,[[522,\"\",null],[0,\"/warframe/\",null]]],[255,[[522,\"\",null],[0,\"/wot/\",null]]],[255,[[522,\"\",null],[0,\"/sims/\",null]]],[255,[[522,\"\",null],[0,\"/gwent/\",null]]],[255,[[522,\"\",null],[0,\"/bns/\",null]]],[255,[[522,\"\",null],[0,\"/mhw/\",null]]],[255,[[522,\"\",null],[0,\"/truck/\",null]]],[255,[[522,\"\",null],[0,\"/epic7/\",null]]],[255,[[522,\"\",null],[0,\"/ovw/\",null]]],[255,[[522,\"\",null],[0,\"/fgog/\",null]]],[255,[[522,\"\",null],[0,\"/tw/\",null]]],[255,[[522,\"\",null],[0,\"/csgo/\",null]]],[255,[[522,\"\",null],[0,\"/sc/\",null]]],[255,[[522,\"\",null],[0,\"/gta/\",null]]],[255,[[522,\"\",null],[0,\"/diablo2/\",null]]],[255,[[522,\"\",null],[0,\"/forhonor/\",null]]],[255,[[522,\"\",null],[0,\"/autochess/\",null]]],[255,[[522,\"\",null],[0,\"/catadda/\",null]]],[255,[[522,\"\",null],[0,\"/destiny2/\",null]]],[255,[[522,\"\",null],[0,\"/lisg/\",null]]],[255,[[522,\"\",null],[0,\"/hots/\",null]]],[255,[[522,\"\",null],[0,\"/kancolle/\",null]]],[255,[[522,\"\",null],[0,\"/blg/\",null]]],[255,[[522,\"\",null],[0,\"/wows/\",null]]],[255,[[522,\"\",null],[0,\"/r6s/\",null]]],[255,[[522,\"\",null],[0,\"/dota2/\",null]]],[255,[[522,\"\",null],[0,\"/bdo/\",null]]],[255,[[522,\"\",null],[0,\"/longdark/\",null]]],[255,[[522,\"\",null],[0,\"/nier/\",null]]],[255,[[522,\"\",null],[0,\"/factorio/\",null]]],[255,[[522,\"\",null],[0,\"/cross/\",null]]],[255,[[522,\"\",null],[0,\"/gd/\",null]]],[255,[[522,\"\",null],[0,\"/simrace/\",null]]],[255,[[522,\"\",null],[0,\"/stalker/\",null]]],[255,[[522,\"\",null],[0,\"/nondnd/\",null]]],[255,[[522,\"\",null],[0,\"/elite/\",null]]],[255,[[522,\"\",null],[0,\"/eveo/\",null]]],[255,[[522,\"\",null],[0,\"/pala/\",null]]],[255,[[522,\"\",null],[0,\"/pubg/\",null]]],[255,[[522,\"\",null],[0,\"/utg/\",null]]],[255,[[522,\"\",null],[0,\"/assassin/\",null]]],[255,[[522,\"\",null],[0,\"/gw2g/\",null]]],[255,[[522,\"\",null],[0,\"/fallout/\",null]]],[255,[[522,\"\",null],[0,\"/wtg/\",null]]],[255,[[522,\"\",null],[0,\"/apex/\",null]]],[255,[[522,\"\",null],[0,\"/dsg/\",null]]],[255,[[522,\"\",null],[0,\"/gerk/\",null]]]],false,false]",
		"favWinWidth": 400,
		"hideReplies": 1,
		"expandPanel": 1,
		"YTubeWidth": "400",
		"YTubeHeigh": "250",
		"cfgWinY": "top: 0px",
		"webmVolume": 15,
		"textaWidth": 633,
		"textaHeight": 241,
		"loadPages": "7",
		"spacedQuote": 0,
		"preLoadImgs": 2,
		"updThrDelay": "60",
		"strikeHidd": 1,
		"zoomFactor": 10
	},
	"sSpells": [
		"(#op & #words(/owl/)) |",
		"(#op & #words(/mtga/)) |",
		"(#op & #words(/lolg/)) |",
		"(#op & #words(/fgoalter/)) |",
		"(#op & #words(/tf2/)) |",
		"(#op & #words(/hsg/)) |",
		"(#op & #words(/alg/)) |",
		"(#op & #words(/factory/)) |",
		"(#op & #words(/honkai/)) |",
		"(#op & #words(/dmc/)) |",
		"(#op & #words(/wowg/)) |",
		"(#op & #words(/dbd/)) |",
		"(#op & #words(/anthem/)) |",
		"(#op & #words(/bfg/)) |",
		"(#op & #words(/sandbox/)) |",
		"(#op & #words(/quake/)) |",
		"(#op & #words(/warframe/)) |",
		"(#op & #words(/wot/)) |",
		"(#op & #words(/sims/)) |",
		"(#op & #words(/gwent/)) |",
		"(#op & #words(/bns/)) |",
		"(#op & #words(/mhw/)) |",
		"(#op & #words(/truck/)) |",
		"(#op & #words(/epic7/)) |",
		"(#op & #words(/ovw/)) |",
		"(#op & #words(/fgog/)) |",
		"(#op & #words(/tw/)) |",
		"(#op & #words(/csgo/)) |",
		"(#op & #words(/sc/)) |",
		"(#op & #words(/gta/)) |",
		"(#op & #words(/diablo2/)) |",
		"(#op & #words(/forhonor/)) |",
		"(#op & #words(/autochess/)) |",
		"(#op & #words(/catadda/)) |",
		"(#op & #words(/destiny2/)) |",
		"(#op & #words(/lisg/)) |",
		"(#op & #words(/hots/)) |",
		"(#op & #words(/kancolle/)) |",
		"(#op & #words(/blg/)) |",
		"(#op & #words(/wows/)) |",
		"(#op & #words(/r6s/)) |",
		"(#op & #words(/dota2/)) |",
		"(#op & #words(/bdo/)) |",
		"(#op & #words(/longdark/)) |",
		"(#op & #words(/nier/)) |",
		"(#op & #words(/factorio/)) |",
		"(#op & #words(/cross/)) |",
		"(#op & #words(/gd/)) |",
		"(#op & #words(/simrace/)) |",
		"(#op & #words(/stalker/)) |",
		"(#op & #words(/nondnd/)) |",
		"(#op & #words(/elite/)) |",
		"(#op & #words(/eveo/)) |",
		"(#op & #words(/pala/)) |",
		"(#op & #words(/pubg/)) |",
		"(#op & #words(/utg/)) |",
		"(#op & #words(/assassin/)) |",
		"(#op & #words(/gw2g/)) |",
		"(#op & #words(/fallout/)) |",
		"(#op & #words(/wtg/)) |",
		"(#op & #words(/apex/)) |",
		"(#op & #words(/dsg/)) |",
		"(#op & #words(/gerk/))"
	],
	"oSpells": "[1554232393484,[[255,[[522,\"\"],[0,\"/owl/\"]]],[255,[[522,\"\"],[0,\"/mtga/\"]]],[255,[[522,\"\"],[0,\"/lolg/\"]]],[255,[[522,\"\"],[0,\"/fgoalter/\"]]],[255,[[522,\"\"],[0,\"/tf2/\"]]],[255,[[522,\"\"],[0,\"/hsg/\"]]],[255,[[522,\"\"],[0,\"/alg/\"]]],[255,[[522,\"\"],[0,\"/factory/\"]]],[255,[[522,\"\"],[0,\"/honkai/\"]]],[255,[[522,\"\"],[0,\"/dmc/\"]]],[255,[[522,\"\"],[0,\"/wowg/\"]]],[255,[[522,\"\"],[0,\"/dbd/\"]]],[255,[[522,\"\"],[0,\"/anthem/\"]]],[255,[[522,\"\"],[0,\"/bfg/\"]]],[255,[[522,\"\"],[0,\"/sandbox/\"]]],[255,[[522,\"\"],[0,\"/quake/\"]]],[255,[[522,\"\"],[0,\"/warframe/\"]]],[255,[[522,\"\"],[0,\"/wot/\"]]],[255,[[522,\"\"],[0,\"/sims/\"]]],[255,[[522,\"\"],[0,\"/gwent/\"]]],[255,[[522,\"\"],[0,\"/bns/\"]]],[255,[[522,\"\"],[0,\"/mhw/\"]]],[255,[[522,\"\"],[0,\"/truck/\"]]],[255,[[522,\"\"],[0,\"/epic7/\"]]],[255,[[522,\"\"],[0,\"/ovw/\"]]],[255,[[522,\"\"],[0,\"/fgog/\"]]],[255,[[522,\"\"],[0,\"/tw/\"]]],[255,[[522,\"\"],[0,\"/csgo/\"]]],[255,[[522,\"\"],[0,\"/sc/\"]]],[255,[[522,\"\"],[0,\"/gta/\"]]],[255,[[522,\"\"],[0,\"/diablo2/\"]]],[255,[[522,\"\"],[0,\"/forhonor/\"]]],[255,[[522,\"\"],[0,\"/autochess/\"]]],[255,[[522,\"\"],[0,\"/catadda/\"]]],[255,[[522,\"\"],[0,\"/destiny2/\"]]],[255,[[522,\"\"],[0,\"/lisg/\"]]],[255,[[522,\"\"],[0,\"/hots/\"]]],[255,[[522,\"\"],[0,\"/kancolle/\"]]],[255,[[522,\"\"],[0,\"/blg/\"]]],[255,[[522,\"\"],[0,\"/wows/\"]]],[255,[[522,\"\"],[0,\"/r6s/\"]]],[255,[[522,\"\"],[0,\"/dota2/\"]]],[255,[[522,\"\"],[0,\"/bdo/\"]]],[255,[[522,\"\"],[0,\"/longdark/\"]]],[255,[[522,\"\"],[0,\"/nier/\"]]],[255,[[522,\"\"],[0,\"/factorio/\"]]],[255,[[522,\"\"],[0,\"/cross/\"]]],[255,[[522,\"\"],[0,\"/gd/\"]]],[255,[[522,\"\"],[0,\"/simrace/\"]]],[255,[[522,\"\"],[0,\"/stalker/\"]]],[255,[[522,\"\"],[0,\"/nondnd/\"]]],[255,[[522,\"\"],[0,\"/elite/\"]]],[255,[[522,\"\"],[0,\"/eveo/\"]]],[255,[[522,\"\"],[0,\"/pala/\"]]],[255,[[522,\"\"],[0,\"/pubg/\"]]],[255,[[522,\"\"],[0,\"/utg/\"]]],[255,[[522,\"\"],[0,\"/assassin/\"]]],[255,[[522,\"\"],[0,\"/gw2g/\"]]],[255,[[522,\"\"],[0,\"/fallout/\"]]],[255,[[522,\"\"],[0,\"/wtg/\"]]],[255,[[522,\"\"],[0,\"/apex/\"]]],[255,[[522,\"\"],[0,\"/dsg/\"]]],[255,[[522,\"\"],[0,\"/gerk/\"]]]],null,null]",
	"perf": {
		"Imageboard check": 1,
		"Storage loading": 1,
		"Init": 6,
		"Read my posts": 1,
		"Replace delform": 1,
		"Parse delform": 23,
		"Parse postform": 11,
		"Init keybinds": 0,
		"Init page": 1,
		"Add panel": 1,
		"Init AJAX": 0,
		"Preload images": 4,
		"Audio links": 1,
		"Video links": 3,
		"Image names": 6,
		"Reflinks map": 2,
		"Apply CSS": 3,
		"Display page": 0,
		"Infinity scroll": 0,
		"Hide posts": 35,
		"Image-links": 0,
		"Scroll page": 0,
		"Всего": 100
	}
}

**Comment by SthephanShinkufag** [comment]
Исправлено в скрипте.

**Comment by Explaiz** [comment]
> Исправлено в скрипте, позже обновлю расширение.

Спасибо, буду ждать

**Comment by SthephanShinkufag** [comment]
Обновил хроморасширение на серверен гугля. Сейчас прилетит.

**Comment by LightGameStudio42** [comment]
Проблема вернулась. И на chrome, и на firefox.
Версия скрипта: 24.9.16.0
Просто не показываются страницы, а бесконечный скроллинг не рабоатет.
![image](https://github.com/user-attachments/assets/44d831d5-e74e-49aa-8d06-6a992850cb62)
