### ISSUE TITLE
Скрытие боевых картинок и гринтекста

### ISSUE THREAD

**Issue by Autism-Corporation** [SthephanShinkufag/Dollchan-Extension-Tools#1326]
Есть ли возможность скрывать подобные пикрилу творчества бота? Через спеллы не получается, через #img бред т.к эти пикчи клепают шизики каждую минуту?
![image](https://user-images.githubusercontent.com/21297066/54522836-3d527880-497f-11e9-9c39-044db5060175.png)

**Comment by SthephanShinkufag** [comment]
Данный конкретный пост можно скрыть спеллом

```
#exp(/>>\d+\n+>[^>][^\n]+\n+>[^>][^\n]+$/)
```

Если строка с цитатой только одна, то 

```
#exp(/>>\d+\n+>[^>][^\n]+$/)
```

**Comment by Autism-Corporation** [comment]
С пикчей спелл не работает почему то, без него работает, как починить?
![image](https://user-images.githubusercontent.com/21297066/55071448-b2b5fb80-5099-11e9-9e2d-e4be304627e6.png)

**Comment by SthephanShinkufag** [comment]
У вас там три строки с цитатами. Я привёл пример для двух и одной строк. Разбирайтесь далее сами.

**Comment by Autism-Corporation** [comment]
И правда, чёт я туплю, спасибо.
![image](https://user-images.githubusercontent.com/21297066/55072453-340e8d80-509c-11e9-944f-735f1df99de7.png)

**Comment by SthephanShinkufag** [comment]
Универсальное выражение для любого количества цитируемых строк:

```
#exp(/>>\d+(\n+>[^>][^\n]+)+$/)
```
