### ISSUE TITLE
[2chan.net]: Ошибка кодировки при бесконечном скролле

### ISSUE THREAD

**Issue by roman-software** [SthephanShinkufag/Dollchan-Extension-Tools#1330]
Chrome 73, Windows 7
На 2chan.net при использовании бесконечного скролла или нажатии F5 текст превращается в крякозябры.
https://imgur.com/a/A2JQOku

**Comment by SthephanShinkufag** [comment]
Пробовал хром, лису - всё работает...

**Comment by SthephanShinkufag** [comment]
2chan.net is not supported now.
