### ISSUE TITLE
[Bug] 2ch.hk. Перестали раскрываться пички и вебмки - опять Абу что-то сломал.

### ISSUE THREAD

**Issue by MrBudda108** [SthephanShinkufag/Dollchan-Extension-Tools#1338]
2ch.hk. Перестали раскрываться пички и вебмки - опять Абу что-то сломал.

**Comment by MrBudda108** [comment]
Спасибо за оперативность и простите за оформление.

**Comment by Turbolalka9000** [comment]
@SthephanShinkufag А когда на хромоаддоне обнову ждать?

**Comment by SthephanShinkufag** [comment]
Когда починю там кроссдоменные запросы.

**Comment by sucud** [comment]
У меня на версии v18.11.25.0 картинки открываются, но только по центру, хотя я выбрал открывать в посте.

**Comment by SthephanShinkufag** [comment]
@sucud 
https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/raw/master/src/Dollchan_Extension_Tools.es6.user.js
!!!

**Comment by XakepSDK** [comment]
Можешь обновить аддон для FF?

**Comment by sucud** [comment]
Слава Украине!

**Comment by klaiksa** [comment]
![image](https://user-images.githubusercontent.com/51678279/59220874-a4727880-8bce-11e9-9814-40f0c5fb71d1.png)
и куда тыкать

**Comment by SthephanShinkufag** [comment]
@klaiksa 
https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/wiki/installation

**Comment by sucud** [comment]
Обновился с v18.11.25.0 до последней версии и возникла проблема. Как сделать так, чтобы при нажатии на номер поста не раскрывалась форма под постом, а кидало сразу в форму снизу треда?

**Comment by sucud** [comment]
Так, разобрался. Нужно параметр reply to post thread menu вместо disabled поставить no menu.

**Comment by SthephanShinkufag** [comment]
Обновил хроморасширение и лисоаддон. Ждите, сейчас прилетит.
