### ISSUE TITLE
[Enhancement] Как насчет того, чтобы скрытые треды вообще не показывать в выдаче?

### ISSUE THREAD

**Issue by user55** [SthephanShinkufag/Dollchan-Extension-Tools#1339]
Логично же, что треды которые ты скрываешь, ты вообще не хочешь видеть. А так они болтаются в общей выдаче. Если скрыл случайно, то можно через кнопку "крестик" на панели управления открыть обратно.

**Comment by hauau** [comment]
![firefox_F8wo9FIUq9](https://user-images.githubusercontent.com/8182054/59284200-0e098a00-8c96-11e9-945c-3b01eb153c9e.png)

**Comment by user55** [comment]
Хм, даже не подумал проверить, только появилась потребность пользоваться. Небольшой баг все равно есть, обычные посты отделяются одной линией, скрытые после себя оставляют двойную.

**Comment by SthephanShinkufag** [comment]
@user55 

> скрытые после себя оставляют двойную

Исправлено.
