### ISSUE TITLE
[Enhancement] Полные имена файлов

### ISSUE THREAD

**Issue by solara322** [SthephanShinkufag/Dollchan-Extension-Tools#1340]
Добавить функцию для возможности отключения укорачивания имени файла в постах. То есть к посту прикреплена, допустим, пикча и её имя длинное, в итоге оно урезано и невозможно целиком скопировать. 
При открытии полноразмерной пикчи по центру экрана тоже нельзя скопировать имя, так как клик приводит к закрытию пикчи. Открытая в новой вкладке пикча имеет в адресной строке уже другое имя, соответственно там тоже нельзя скопировать.

Ну или хотя бы скажите где в коде что подправить, чтобы убрать это укорачивание. Если не захотите делать отдельную функцию для этого.

**Comment by SthephanShinkufag** [comment]
1. Обновите юзерскрипт.
2. `"Настройки"` > `"Картинки"` > выставьте `"[Настоящие] имена картинок"`.

**Comment by hm2xsi** [comment]
A bit of a problem here.
![cut](https://user-images.githubusercontent.com/49578934/59883607-46a81280-93be-11e9-9096-f0b22ed553ee.png)

**Comment by SthephanShinkufag** [comment]
I'm so sick of this shit.
