### ISSUE TITLE
[Bug] Поддержка animach.pw

### ISSUE THREAD

**Issue by shn10032** [SthephanShinkufag/Dollchan-Extension-Tools#1342]
**Опишите вашу ошибку**
1. Четкое описание ошибки. Что произошло?
Не работает постинг и автообновление треда на animach.pw
2. Какого поведения вы ожидали?
Работает постинг и автообновление треда на animach.pw
3. Ошибка происходит на конкретном имиджборде, или везде?
Только на animach.pw
4. Что пишет в консоли в момент наблюдения ошибки?
Ошибок нет.

**Описание браузера и Dollchan**
1. Firefox Beta; 64-bit; 68.0b9
2. v19.6.16.0.bf6a991.es6
3. Юзерскрипт
4. Greasemonkey

**Шаги для воспроизведения поведения ошибки**
1. Открыть тред на animach.pw
2. Попробовать запостить
3. Попробовать получить новые посты

**Скриншоты**
![image](https://user-images.githubusercontent.com/51961752/59695078-4bb86680-91f2-11e9-9ea5-6edea3ef638f.png)

**Comment by SthephanShinkufag** [comment]
Всё работает. Вы используете какие-то блокировщики?
Отключите.

**Comment by shn10032** [comment]
Проверял с отключенным uBlock, аналогично. Кстати, проверил в хромом tampermonkey, там все работает.

**Comment by SthephanShinkufag** [comment]
Проблемы не в greasemonkey. Всё работает.
Скорее, проблемы в ваших настройках.
Покажите содержимое Настройки > Инфо > Отладка.

**Comment by shn10032** [comment]
Вот.
{
	"version": "19.6.16.0.bf6a991",
	"location": "https://animach.pw/mod/res/52.html",
	"nav": {
		"canUseFetch": true,
		"canUseFetchBlob": true,
		"canUseNativeXHR": true,
		"firefoxVer": 68,
		"hasGlobalStorage": true,
		"hasGMXHR": true,
		"hasNewGM": true,
		"hasOldGM": false,
		"hasPrestoStorage": false,
		"hasWebStorage": false,
		"isChrome": false,
		"isESNext": true,
		"isFirefox": true,
		"isMsEdge": false,
		"isPresto": false,
		"isSafari": false,
		"isWebkit": false,
		"scriptHandler": "Greasemonkey 4.9",
		"ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0 [20181001000000]",
		"canPlayMP3": true,
		"hasTemplate": true,
		"hasWorker": true
	},
	"Cfg": {
		"addVocaroo": 0,
		"hideBySpell": 0,
		"updDollchan": 0,
		"expandPanel": 1,
		"cfgTab": "info",
		"timeOffset": "3",
		"textaWidth": 267,
		"textaHeight": 196,
		"closePopups": 1,
		"warnSubjTrip": 1,
		"saveSage": 0,
		"decodeLinks": 1,
		"postSameImg": 0,
		"webmTitles": 1,
		"noSpoilers": 0,
		"timePattern": "nn+dd+yy++w++hh+ii+ss"
	},
	"sSpells": [
		"#wipe(samelines,samewords,longwords,symbols,numbers,whitespace)"
	],
	"perf": {
		"Imageboard check": 5,
		"Storage loading": 634,
		"Init": 6,
		"Read my posts": 0,
		"Replace delform": 44,
		"Parse delform": 21,
		"Parse postform": 11,
		"Init keybinds": 1,
		"Init page": 8,
		"Add panel": 2,
		"Image-links": 0,
		"Init AJAX": 0,
		"Preload images": 1,
		"Audio links": 1,
		"Video links": 2,
		"Image names": 10,
		"Reflinks map": 6,
		"Apply CSS": 7,
		"Display page": 0,
		"Infinity scroll": 0,
		"Hide posts": 3,
		"Scroll page": 0,
		"Total": 762
	}
}

**Comment by SthephanShinkufag** [comment]
Всё работает.
Ищите проблему у себя.

**Comment by SthephanShinkufag** [comment]
Возможно, вы используете и другие блокироващики, кроме uBlock.

**Comment by shn10032** [comment]
Нет, ничего кроме uBlock нет. Без него уже пробовал. Это очень странно, что везде кроме той борды работает. Проблема определенно в greasemonkey, возможно у него есть конфиг, который поломался?

**Comment by shn10032** [comment]
Было бы интересно посмотреть, куда он стучит, но в консоле ничего нет.

**Comment by SthephanShinkufag** [comment]
Убрал использование fetch для animach.pw
Обновите скрипт до последнего коммита, проверяйте.

**Comment by shn10032** [comment]
![изображение](https://user-images.githubusercontent.com/51961752/61953986-700d1d00-afc0-11e9-9512-2ee74a145e27.png)
Обновил скрипт (https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/raw/master/src/Dollchan_Extension_Tools.es6.user.js).
Теперь connection failed. Думаю, проблема на моей стороне. Поломанный профиль лисы, возможно. Не уверен. На violentmonkey/tampermonkey все так же работает.
