### ISSUE TITLE
[Enhancement] панелька оппоста

### ISSUE THREAD

**Issue by trollsasha1** [SthephanShinkufag/Dollchan-Extension-Tools#1343]
Борда 4chan
Возможно ли при включённом дашчане оставить эту панельку?
Я установил расширение, а оно юзает эту панель для расположения своих кнопок и получается при включённом дашчане я не могу их нажимать никак.
Возможно есть какое-то решение через пользовательский css?
![Скриншот 19-06-2019 225232](https://user-images.githubusercontent.com/30331570/59796133-83eca180-92e5-11e9-96b9-bcf53e0309f8.png)

**Comment by SthephanShinkufag** [comment]
`"Настройки"` (Alt+S) > `"Общее"` > `"Пользовательский CSS"` - поставить галочку, нажать кнопку `"Правка"`, добавить строки

```css
.navLinks {
    display: initial !important;
}
```

Нажать кнопку `"Сохранить"`.
