### ISSUE TITLE
[Bug] SyntaxError

### ISSUE THREAD

**Issue by hk0kizu** [SthephanShinkufag/Dollchan-Extension-Tools#1345]
При попытке вставить некоторые файлы %%ибо некоторые проходят, некоторые нет, независимо от расширения и размера%% выскакивает popup со следующим содержанием:
**SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data at checkUpload (userscript.html?id=9e7c3217-00eb-4e13-bf70-b5ff3c9c24d9:9093:17)**
При отключении куклы постится успешно.
Замечено было на syn-ch.ru
В консоли не пишет ничего. Проходят 2 запроса с 200 кодом и больше ничего.
Пытался вставить банально try-catch, чем поломал скрипт, но на 9093 строчке не особо видно место парсинга данных, а идти по веткам функций не стал.

Лисобраузер 67.0.4 (64-бит), но было и на прошлых версиях.
Кукла v19.6.16.0.7eb624f.es6
Tampermonkey 4.9.5941

**Шаги для воспроизведения поведения ошибки**
Конкретный файл: https://cdn.syn-ch.ru/src/156/20/04/1562004383-52912.mp4
С текстом или без - без разницы.

![изображение](https://user-images.githubusercontent.com/30866467/60457529-eed29c80-9c44-11e9-803b-e361fad5240d.png)

**Comment by SthephanShinkufag** [comment]
Не могу добиться бага.
Firefox 68.0 / Tampermonkey 4.9.5921 / Dollchan v19.6.16.0.7eb624f.es6 / тред https://syn-ch.ru/b/res/4986111.html#q5051014

Дайте другую вебмку, например. И ссылку на тред, где пытаетесь постить и появляется ошибка.

**Comment by SthephanShinkufag** [comment]
Запилил отображение содержимого некорректного ответа, если он не является JSON.
Обновитесь до последнего коммита и покажите, на что теперь будет ругаться.
