### ISSUE TITLE
[Bug] Неотключаемый NSFW в архиве двача (https://2ch.hk/b/arch)

### ISSUE THREAD

**Issue by sucud** [SthephanShinkufag/Dollchan-Extension-Tools#1346]
Проблема только в архиве, на обычных досках все норм. Настройка видимости NSFW (0-100) не помогает. Если отключить скрипт, то NSFW отключается.

**Comment by SthephanShinkufag** [comment]
Баг не подтверждён.
Браузер, способ установки скрипта?
Чем включаете/отключаете NSFW - через горячую клавишу `"B"`, или кнопку на панели скрипта?
