### ISSUE TITLE
[Bug] Ajax bugs

### ISSUE THREAD

**Issue by Delian0** [SthephanShinkufag/Dollchan-Extension-Tools#1348]
![xhr](https://user-images.githubusercontent.com/40333853/62833565-36374a00-bc41-11e9-90dd-50167c2cb30e.png)
Here is a screenshot of what happens in the network if I hover mouse cursor over a simple >>link

Problems:
1. Two xhr's are sent.
5142074.json
5142074.json?nocache=X
Only one request should be sent to retrieve the thread data.

2. Breaking browser cache by using the nocache parameter.
5142074.json?nocache=X
Please don't do this. This eats up all my network data. This also affects the threads updater, which keeps downloading the same thread over and over, even when there's no changes. Please use browser's built-in cache handling. If some people need to force no cache, then add a setting for them.

3. Downloading all the images
As seen on the screenshot, all the thread's image thumbnails are downloaded, even when I'm only hovering over a link.
Only the necessary 1 thumbnail should be downloaded.
Here is an example of code which parses xhr data without downloading img src links:
`var doc = document.implementation.createHTMLDocument();`
`doc.documentElement.innerHTML = xhr.data;`

I'm using the latest version of dollchan in Tampermonkey in latest Firefox
As far as I can tell, the problems are in kusaba boards. The example screenshot shows .json files for the thread data, but the problem are the same with .html files.

**Comment by Y0ba** [comment]
1 & 2: could you test #1349?
3: That's exactly what script is doing:
https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/blob/df38c56909130f3093be793e6b32883b167cc29d/src/modules/Utils.js#L114-L118

**Comment by Delian0** [comment]
1 & 2:
Internal error: TypeError: header[0] is undefined at saveData 
Fixed by changing for..in into for..of

3: The trigger for the loading of images is in 
11584:36
https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/blob/df38c56909130f3093be793e6b32883b167cc29d/src/modules/PostPreviews.js#L322-L337

**Comment by Delian0** [comment]
`doc.adoptNode(form)` specifically

**Comment by Delian0** [comment]
![image](https://user-images.githubusercontent.com/40333853/62973127-c62ded00-be15-11e9-98d5-d43dfb86ea6d.png)

`for(let header of headers) {` was good
`for(const idx in headers) {` broke it again

**Comment by SthephanShinkufag** [comment]
Browser and its version? Script manager? Board?

**Comment by Delian0** [comment]
Firefox 69.0b13 (64-bit)
Tampermonkey 4.9.5941
Board is kusabaX

#1349 was supposed to fix it, but it did not.

https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/blob/a4c5ce06418151114de4889d598cb7de2e378a5f/src/modules/Ajax.js#L229-L231

`headers` is an Array.
However, the board uses Prototype+aculous (protoaculous.js) library. This library extends Array to have extra functions.
`Object.keys(headers)` will result in:
`[ "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "each", "eachSlice", "all", "any", ... ` ]
So you cannot use `for(let header in headers)` (for..in) to traverse the array because it contains these extra property names.
Either use a normal `for` loop, or use for..of, that is, `for (let header of headers)`.

**Comment by SthephanShinkufag** [comment]
Oh, that shitty Prototype library on kusaba boards spoiled my nerves once many times... And again now. It overrides many methods in arrays with its functions.
Thank you for your comment.

**Comment by SthephanShinkufag** [comment]
Fixed.
As for repeated `?nocache=X` request, it used when response of usual request does not contain `cache-control` header.

If usual request does not contain `cache-control` header then the browser will constantly display outdated information about the thread and the user will not see new posts. This used to be a big problem, and it is solved with such `?nocache=X` request, which shows the actual data.

**Comment by Delian0** [comment]
The last fix works and the ticket can be closed.

As for the `nocache` parameter, can you give me an example where using that is necessary?

**Comment by Y0ba** [comment]
> As for the nocache parameter, can you give me an example where using that is necessary?

It's used when there is no Cache-Control header and no Expires header, but there is a Last-Modified header (script check only presence of Cache-Control). Basically if administrator misconfigured server.

**Comment by Delian0** [comment]
If there is a `Last-Modified` response header, then you don't need the `nocache` parameter either. The browser correctly handles caching on its own even if there's only this response header present.

Of course, if you leave it to the browser, then you will always get a `200 OK` response status in your xhr requests. If you want to find out if a page changed, then you simply need to correctly set `If-Modified-Since` request header and you should get a response status of either `200 OK`, or `304 Not Modified`.
I can see that the script already does this. But if it does this, then I don't understand why it would ever need the `nocache` parameter. That's my opinion. Maybe I'm wrong? Do you have an example of a board where you use this parameter?

**Comment by Y0ba** [comment]
Well, if there is no `Cache-Control` header and you set `If-Modified-Since` in request browser will use his own heuristics of caching and might return `304 Not Modified` even if original document was changed.

**Comment by Y0ba** [comment]
https://tools.ietf.org/html/rfc7234#section-4.2.2
> Since origin servers do not always provide explicit expiration times,
   a cache MAY assign a heuristic expiration time when an explicit time
   is not specified, employing algorithms that use other header field
   values (such as the Last-Modified time) to estimate a plausible
   expiration time.  This specification does not provide specific
   algorithms, but does impose worst-case constraints on their results.

**Comment by SthephanShinkufag** [comment]
Try to replace

```js
return $ajax(ajaxURL, useCache && params || { useTimeout: true }, aib._4chan).then(xhr =>
			this.saveData(url, xhr) ? xhr : $ajax(this.fixURL(url), useCache && params, aib._4chan));
```

with

```js
return $ajax(ajaxURL, useCache && params || { useTimeout: true }, aib._4chan);
```

to disable `nocache` mechanism,
Go for example, to https://syn-ch.ru/b/
Expand random thread +10posts from the threads list
Then try to post in that thread.
Your post will not shown without `nocache` mechanism.

But! On some boards without cache-control everything is ok...  On lynxchan boards (kohlchan.net), for example...

**Comment by SthephanShinkufag** [comment]
Maybe it will be better to implement some kind of counter of usual+`nocache` double calls?
And after 3..4 usual+`nocache` requests to use only `nocache`?

**Comment by Delian0** [comment]
![image](https://user-images.githubusercontent.com/40333853/63011844-6d983780-be89-11e9-97c8-aee02761b380.png)

As far as I can tell, when not using the script, caching and refreshing on the site works just fine.
On the screenshot you can see that xhr requests are cached. But when the `Last-Modified` date no longer matches the `If-Modified-Since` date (when the document changes), the server returns a new version, and updates the cache.

It works exactly as I said.
- If I don't set `If-Modified-Since` header, then I always get a `200 OK` response
- If I set `If-Modified-Since` header, then I get `304 Not Modified` if there was no change, or I get `200 OK` if there was change to the file on the server.

So I think it's most likely that there's a bug in the script. But I don't have the time to look at it to see exactly where it is.
