### ISSUE TITLE
!!!Chrome extension is deleted by Google!!!

### ISSUE THREAD

**Issue by SthephanShinkufag** [SthephanShinkufag/Dollchan-Extension-Tools#1352]
Today I received an email from Google:

> Dear Developer,
We routinely review items in the Chrome Web Store for compliance with our Program policies to ensure a safe and trusted experience for our users. We recently found that your item, "Dollchan Extension Tools," with ID: ipnoalfffblkaodfmipjjgkfbgcfadad did not comply with our policies. Your item did not comply with the following section of our policy: Do not use irrelevant, misleading, or excessive keywords in app descriptions, titles, or metadata. Please ensure that your item has a description that clearly and directly relates the functionality of your extension.Your item is still published, but is at risk of being removed from the Web Store.
Please make the above changes within 7 days in order to avoid removal: Once you have made these changes you may submit and publish a new draft in the developer dashboard. Your draft will be reviewed for policy compliance which typically takes a few business days. If the outcome of the review is successful, your store listing will remain published. If we find additional issues with your item, we will send you another email with details. If you have any questions about this email, please respond and the Chrome Web Store developer support team will follow up with you.
Important Note:
Your item will still be subject to review and may be removed from the store within the warning period. Repeated or egregious policy violations in the Chrome Web Store may result in your developer account being suspended or could lead to a ban from using the Chrome Web Store platform. This may also result in the suspension of related Google services associated with your Google account.
Thank you for your cooperation,
Google Chrome Web Store team
Developer Terms of Service: https://developers.google.com/chrome/web-store/terms
Program Policies: https://developers.google.com/chrome/web-store/program_policies
Branding Guidelines: https://developers.google.com/chrome/web-store/branding

Here is an extension's page:
https://chrome.google.com/webstore/detail/dollchan-extension-tools/ipnoalfffblkaodfmipjjgkfbgcfadad

I don't know what they don't like about the application...
It will be deleted in 7 days.
What to do?
Maybe you have some ideas?

**Comment by SthephanShinkufag** [comment]
Wrote a new text, sent the extension for review:

This extension improves the functionality of anonymous imageboard sites you visit, which allows you to spend your time there more easily and conveniently.
Supports imageboard engines as Wakaba, Kusaba, Tinyboard, Vichan, TinyIB, LynxChan, FoolFuuka and their derivatives.

Features this extension provides are:
- Sending posts without rebooting (reply in thread or from the index page).
- Thread updater with different types of alerts (for example, the blinking favicon or the desktop notification when new posts appeared).
- Hiding posts and threads using the wide choice of expressions and rules.
- Saving threads entirely with original quality images.
- Expanding threads directly on the index page.
- Adding interesting threads to your Favorites to track new posts or responses to your posts.
- "Endless scrolling" of index pages with threads.
- Easy navigation through >>links as a posts tree.
- Easy navigation through attached images/videos in posts.
- Easy navigation through posts and threads.
- Embedding player to YouTube and Vimeo links.
- Search for source of images, search for source of .webm/.mp4 video frames.
- Adding images to the reply form with convenient preview thumbnails.
- Markup buttons in the repy form.
- Embedding preview thumbnails to .jpg/.png/.gif links.
- Adding your CSS rules.
- Hotkeys.

**Comment by Delian0** [comment]
The description looks good to me. Might also want to mention the supported languages.

Is this still a problem?

**Comment by SthephanShinkufag** [comment]
Well, Google removed my extension now!  I don’t understand what they don’t like...

> Dear Developer, Your Google Chrome item, "Dollchan Extension Tools," with ID: ipnoalfffblkaodfmipjjgkfbgcfadad did not comply with our policies and was removed from the Google Chrome Web Store. Your item did not comply with the following section of our policy: Do not use irrelevant, misleading, or excessive keywords in app descriptions, titles, or metadata. Please ensure that your item has a description that clearly and directly relates the functionality of your extension.If you'd like to re-submit your item, please make the appropriate changes to the item so that it complies with our policies, then re-publish it in your developer dashboard. Please reply to this email for issues regarding this item removal. *Please keep in mind that your re-submitted item will not be immediately published live in the store. All re-submitted items undergo a strict compliance review and will be re-published if the item passes review. *Important Note Repeated or egregious violations in the store may result in your developer account being banned from the store. This may also result in the suspension of related Google services associated with your Google account. All re-submitted items will continue to be subject to Chrome Web Store policies and terms of service. Thank you for your cooperation, Google Chrome Web Store team --------------------------- Developer Terms of Service: https://developers.google.com/chrome/web-store/terms Program Policies: https://developers.google.com/chrome/web-store/program_policies Branding Guidelines: https://developers.google.com/chrome/web-store/branding

**Comment by SthephanShinkufag** [comment]
About policies:

https://developer.chrome.com/webstore/program_policies
https://play.google.com/intl/en_us/about/storelisting-promotional/metadata/

> We don't allow apps with misleading, irrelevant, excessive, or inappropriate metadata, including but not limited to the app's description, developer name, title, icon, screenshots, and promotional images. We also don't allow user testimonials in the app's description.
Here are some examples of common violations:
① User testimonials
② Excessive details
③ ④ Misleading references to other apps or products
⑤ Repetitive, excessive, or irrelevant keywords
Here are some examples of inappropriate text, images, or videos within your listing:
> - Imagery or videos with sexually suggestive content. Avoid suggestive imagery containing breasts, buttocks, genitalia, or other fetishized anatomy or content, whether illustrated or real.
>  - Language inappropriate for a general audience. Avoid profane and vulgar language in your app listing. If it is a critical element of your app, you must censor its presentation within the store listing.
> - Graphic violence prominently depicted in app icons, promotional images, or videos.
> - Depictions of the illicit usage of drugs. Even EDSA (Educational, Documentary, Scientific, or Artistic) content must be suitable for all audiences within the store listing.

> Here are a few best practices:
> - Highlight what's great about your app. Share interesting and exciting facts about your app to help users understand what makes your app special.
> - Make sure that your app’s title and description accurately describe your app’s functionality.
> - Avoid using repetitive or unrelated keywords or references.
> - Keep your app’s description succinct and straightforward. Shorter descriptions tend to result in a better user experience, especially on devices with smaller displays. Excessive length, detail, or repetition can result in a violation of this policy.
> - Remember that your listing should be suitable for a general audience. Avoid using inappropriate text, images or videos in your listing.

**I was used these text and screenshots:**

This extension improves the functionality of anonymous imageboard sites you visit, which allows you to spend your time there more easily and conveniently.
Supports imageboard engines as Wakaba, Kusaba, Tinyboard, Vichan, TinyIB, LynxChan, FoolFuuka and their derivatives.

Features this extension provides are:

- Sending posts without rebooting (reply in thread or from the index page).
- Thread updater with different types of alerts (for example, the blinking favicon or the desktop notification when new posts appeared).
- Hiding posts and threads using the wide choice of expressions and rules.
- Saving threads entirely with original quality images.
- Expanding threads directly on the index page.
- Adding interesting threads to your Favorites to track new posts or responses to your posts.
- "Endless scrolling" of index pages with threads.
- Easy navigation through >>links as a posts tree.
- Easy navigation through attached images/videos in posts.
- Easy navigation through posts and threads.
- Embedding player to YouTube and Vimeo links.
- Search for source of images, search for source of .webm/.mp4 video frames.
- Adding images to the reply form with convenient preview thumbnails.
- Markup buttons in the repy form.
- Embedding preview thumbnails to .jpg/.png/.gif links.
- Adding your CSS rules.
- Hotkeys.

![Dollchan_Extension_screenshot05](https://user-images.githubusercontent.com/1059874/65329631-8cdd5f80-dbc1-11e9-9e51-e89ec5c08235.jpg)
![Dollchan_Extension_screenshot06](https://user-images.githubusercontent.com/1059874/65329632-8cdd5f80-dbc1-11e9-9d85-cd74e18eb44f.jpg)
![Dollchan_Extension_screenshot07](https://user-images.githubusercontent.com/1059874/65329634-8cdd5f80-dbc1-11e9-8866-0744172d7236.jpg)
![Dollchan_Extension_screenshot08](https://user-images.githubusercontent.com/1059874/65329635-8cdd5f80-dbc1-11e9-8d04-f3ddf0ab2f5a.jpg)

As I assume,
1. The first screenshot contains an unacceptable anime picture of a sexual nature.
2. The second screenshot contains registered trademarks - Google, Yandex, TinEye.
3. The text in description contains registered trademarks - YouTube, Vimeo. ("- Embedding player to YouTube and Vimeo links.")

**Comment by Delian0** [comment]
I think the most likely cause were the images containing thumbnails of risque nature. Thus, the rule of "excessive details" was violated. I don't think the board names were a problem. Well, maybe "FoolFuuka" could be misunderstood.

**Comment by Vomitlord** [comment]
Why do you even care? Fuck all this Chromium-based madness.

**Comment by lewisje** [comment]
Is there anything that can be done with the extension that could not be done with the UserScript?

**Comment by SthephanShinkufag** [comment]
> Уважаемый разработчик!
> Ваш недавний запрос на публикацию продукта "Dollchan Extension Tools" (идентификатор: ipnoalfffblkaodfmipjjgkfbgcfadad) для Google Chrome был отклонен, поскольку этот продукт нарушает наши правила.
Если его предыдущая версия уже опубликована в сервисе "Интернет-магазин Chrome", она не будет удалена оттуда и останется доступна.
> 
> Ваш продукт нарушает следующий раздел документа "[правила программы](https://developer.chrome.com/webstore/program_policies)":
> 
> "Конфиденциальность пользовательских данных"
> Ваш продукт нарушает требования раздела "Использование разрешений" данных правил, поэтому Вы обязаны:
> •	Запросить доступ к минимальным разрешениям, необходимым для реализации функций или служб Вашего продукта.
> •	Если для реализации функции можно использовать более одного разрешения, запросите эти разрешения с минимальным доступом к данным или функциональным возможностям.
> •	Не запрашивайте доступ к разрешениям, необходимым для служб и функций, которые ещё не реализованы в Вашем продукте.
> 
> Когда Ваш объект перестанет нарушать правила сервиса "Интернет-магазин Chrome", Вы сможете отправить запрос о повторной публикации. Сделать это можно на сайте панели инструментов разработчика продуктов для Интернет-магазина Chrome. Перед повторной публикацией Ваш объект будет проверен на соответствие правилам.
> 
> Если у Вас возникли вопросы по поводу этого электронного письма, ответьте на него, и с Вами свяжется Интернет-магазин Chrome команда поддержки разработчиков.
> 
> Важно!
> Неоднократные или грубые нарушения правил в сервисе "Интернет-магазин Chrome" могут привести к блокировке Вашего аккаунта разработчика или полному запрету на использование платформы "Интернет-магазин Chrome".
> Кроме того, Вам может быть закрыт доступ к сервисам Google, связанным с Вашим аккаунтом.
> 
> С уважением,
> Интернет-магазин Chrome команда поддержки разработчиков

**Comment by SthephanShinkufag** [comment]
Google Translate:
> Dear developer!
> Your recent request to publish "Dollchan Extension Tools" (ID: ipnoalfffblkaodfmipjjgkfbgcfadad) for Google Chrome was rejected because this product violates our policies.
If its previous version is already published in the Chrome Web Store service, it will not be deleted from there and will remain available.
>
> Your product violates the following section of the document "[program rules](https://developer.chrome.com/webstore/program_policies)":
>
> "User Data Privacy"
> Your product violates the requirements of the "Using Permissions" section of these rules, so you must:
> • Request access to the minimum permissions required to implement the functions or services of your product.
> • If you can use more than one permission to implement a function, request these permissions with minimal access to data or functionality.
> • Do not request access to the permissions required for services and functions that are not yet implemented in your product.
>
> When your site ceases to violate the rules of the Chrome Web Store service, you can send a request for re-publication. You can do this on the Chrome Web Store product developer toolbar site. Before republishing your object will be checked for compliance with the rules.
>
> If you have questions about this email, please reply to it and you will be contacted by the Chrome Web Store by the developer support team.
>
> Important!
> Repeated or flagrant violations of the rules in the Chrome Web Store service may lead to the suspension of your developer account or a complete ban on the use of the Chrome Web Store platform.
> In addition, you may be denied access to the Google services associated with your account.
>
> Regards,
> Chrome Web Store Developer Support Team

**Comment by SthephanShinkufag** [comment]
The extension uses permissions:
chrome.tabs
My explainations to Google Team when applying the package:

> Need while loading the page contents to find the anonymous imageboard and to apply features to it. Needs to create an application settings page.

chrome.webNavigation
> Need to run the application in all frames of the page, as the anonymous imageboard can be found in one of the frames.

Host Access Permission
> It is necessary to run the application on all possible anonymous imageboards regardless of domain. The application analyzes whether the page content contains anonymous imageboard and applies its features to it.

Apparently, this is not enough.

**Comment by SthephanShinkufag** [comment]
Apparently, I have to stop supporting the Chrome extension.

**Comment by Delian0** [comment]
Try comparing your permissions with permissions that Greasemonkey and Tampermonkey use. And see their descriptions for why they need the permissions.

**Comment by SthephanShinkufag** [comment]
I'm fed up with this shit already. There is no desire to even engage.

**Comment by SthephanShinkufag** [comment]
Another attempt, and they will block my access to Google services.

**Comment by liaten** [comment]
А никак не сделать обход через юзерскрипт? Tampermonkey, например

**Comment by liaten** [comment]
А, нашёл, тупо сделай вот эту [ссылку](https://raw.github.com/SthephanShinkufag/Dollchan-Extension-Tools/master/Dollchan_Extension_Tools.user.js), мол так и так, и не ворчи

**Comment by liaten** [comment]
Жалко, конечно, что гугл банит

**Comment by WagonOfDoubt** [comment]
There are non-google alternative to Chrome Web Store and Google Chrome is not the only Chromium-based browser, so dropping support for an extension because Google Support are brainless drones is a bit unnecessary.
Maybe you can upload extension to addons.opera.com, addoncrop.com or other places. But IMHO, hosting extension here and on your site is more than enough already.

**Comment by SthephanShinkufag** [comment]
Packed extension is just a `.zip` archieved folder https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/tree/master/extension, renamed to `.crx`
Only you need is delete
```
	"applications": {
		"gecko": {
			"id": "dollchan_extension@dscript.me",
			"strict_min_version": "56.0"
		}
	},
```
from manifest.json
Do I need to upload `.crx` file here?

**Comment by lewisje** [comment]
If you did, we'd need to unpack the folder anyway to side-load it, so it might be better to just put those instructions into the repository; what I'm wondering, however, is what benefit the extension has over the UserScript.

**Comment by SthephanShinkufag** [comment]
@lewisje no benefits except you will have common settings/favorites/hidden on all devices with enabled synchronization in your Chrome.
Also you will have the ability to limit the launch scope:
![settings_screenshot01](https://user-images.githubusercontent.com/1059874/79889733-234b5b00-8407-11ea-9b2d-35ddfb8d66c3.jpg)
(however, script managers also can).
