### ISSUE TITLE
[Enhancement] Disable automatic scrolling

### ISSUE THREAD

**Issue by Delian0** [SthephanShinkufag/Dollchan-Extension-Tools#1354]
The extension currently stores the scroll position inside a thread and restores the position when the thread is opened again.

I don't like this behavior and would like to turn it off. However, I didn't find any settings which would allow me to do that.

So, I would like to request that a new setting is added which would disable the automatic position restoration.
The setting could be called "Remember scroll position" with a default value "true".

**Comment by SthephanShinkufag** [comment]
Hmm. But the browser remembers the scroll position too.

**Comment by SthephanShinkufag** [comment]
But the browser remembers the scroll position too.
This option is even useless now, with modern browsers.

**Comment by Delian0** [comment]
Yes, I'd prefer to use browser's built-in scroll position restoration.

**Comment by SthephanShinkufag** [comment]
And what's the difference?

**Comment by SthephanShinkufag** [comment]
Ok, I will make an option.

**Comment by Delian0** [comment]
Browser only restores position when using the browsers Back or Forward buttons. If you enter the thread normally (by clicking Reply), then the browser does not restore the scroll position.

**Comment by SthephanShinkufag** [comment]
> If you enter the thread normally (by clicking Reply), then the browser, by itself, does not restore the scroll position.

Oh. Then an option is make a sense.

**Comment by SthephanShinkufag** [comment]
* `Common` > `Remember the scroll position in threads`.
