### ISSUE TITLE
Нет звука в webm'ах

### ISSUE THREAD

**Issue by chsnt** [SthephanShinkufag/Dollchan-Extension-Tools#1355]
1. Chrome Версия 76.0.3809.132 (Официальная сборка), (64 бит)
2. v19.8.28.0.5d0bb84.es6 
3. хроморасширение

Нет звука в webm'ах.
С выключенной куклой все ок.

**Comment by SthephanShinkufag** [comment]
Чому закрыли? Баг оказался не в кукле или сам собой пропал?
Если вы насчёт того, что гугль забанил хроморасширение, то я попытаюсь с ними связаться, и исправить спорные моменты, чтобы вернули.
