### ISSUE TITLE
[Bug][410chan] Картинки-спойлеры не обрабатываются куклой

### ISSUE THREAD

**Issue by WagonOfDoubt** [SthephanShinkufag/Dollchan-Extension-Tools#1357]
**Describe your bug**
1. A clear description of the bug. What happened?
В недавнем обновлении на 410чан запилили картинки-спойлеры. В отличие от классической реализации, где вместо сгенерированного превью в `img.thumb` подставляли url картинки-заглушки, тут спойлеры реализованы путем добавления контейнеру `a.imglink` класса `spoiler-image`. Заглушка реализована через псевдоэлемент a.spoiler-image::after, который закрывает собой исходное изображение и исчезает по наведению.
Кукла почему-то не воспринимает такие картинки как картинки, и их раскрытие при включенной кукле выполняется встроенным скриптом сайта, а не куклой.
2. What behavior did you expect?
Кукла должна обрабатывать картинки-спойлеры так же как и остальные, например, раскрывать их по центру.
3. Does the error occur on a specific imageboard, or everywhere?
Только https://410chan.org/a
4. What is written in the console at the time of seeing the bug?
Если раскрыть и закрыть картинку-спойлер штатным скриптом, затем раскрыть по центру любую картинку-не-спойлер, и стрелками долистать до спойлера, то большое изображение не отобразится и в консоли будет ошибка
```
TypeError: aib.getImgSrcLink(...) is null line 1 > scriptElement:12590:14
    _getImageSrc moz-extension://d96866aa-da82-442a-b9c1-e8569c4da43a/options/index.html#scripts/7:12590
    getFullImg moz-extension://d96866aa-da82-442a-b9c1-e8569c4da43a/options/index.html#scripts/7:12310
    _showFullImg moz-extension://d96866aa-da82-442a-b9c1-e8569c4da43a/options/index.html#scripts/7:12066
    updateImgViewer moz-extension://d96866aa-da82-442a-b9c1-e8569c4da43a/options/index.html#scripts/7:11966
    navigate moz-extension://d96866aa-da82-442a-b9c1-e8569c4da43a/options/index.html#scripts/7:11934
    handleEvent moz-extension://d96866aa-da82-442a-b9c1-e8569c4da43a/options/index.html#scripts/7:11805
```

**Browser and Dollchan Description**
1. Specify your browser and its version
Firefox 69.0.2 (64-bit)
2. Specify the version of your Dollchan
19.8.28.0.308148b.es6
3. What do you use: chrome extension or userscript?
Userscript
4. If you are using a userscript, specify your script manager
Violentmonkey v2.11.2

**Steps to reproduce the bug behavior**
1. Go to https://410chan.org/a/res/7628.html#15321
2. Scroll down to post >>15321 
3. Press on картинку-спойлер
4. There bug appears
5. То же самое применимо к webm https://410chan.org/a/res/7628.html#15330

P.S. Эти строки https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/blob/604ad98be14a0c262a5f3d69463fa76312bc2dc6/src/modules/BoardDetector.js#L1169
Можно удалять, так как код, вызывающий #921 выпилен пару лет назад.

**Comment by SthephanShinkufag** [comment]
Dollchan слушает события на элементах <img>, а :after-псевдоэлемент спойлера прикреплён к контейнеру-ссылке `<a>`. Соответственно, клик по спойлеру срабатывает на контейнере, и не вызывает событие клика по <img>.

**Comment by SthephanShinkufag** [comment]
> код, вызывающий #921 выпилен пару лет назад

Благодарю, друже.
