### ISSUE TITLE
[Bug] Как скрывать картинки без имени?

### ISSUE THREAD

**Issue by solara322** [SthephanShinkufag/Dollchan-Extension-Tools#1359]
Если написать
#imgn(/\.jpg/i) |
#imgn(/\.png/i) |
то будут скрываться ВСЕ картинки с любым именем, а нужно чтобы скрывало картинки которые не имеют никаких символов перед расширением. .png/.jpg

**Comment by WagonOfDoubt** [comment]
Вот так:
```
#imgn(/^.jpg/i) |
#imgn(/^.png/i) |
```
должно работать.
Подробнее: https://www.w3schools.com/jsref/jsref_regexp_ncaret.asp
