### ISSUE TITLE
[Enhancement] Поддержка YouTube

### ISSUE THREAD

**Issue by Philosoph228** [SthephanShinkufag/Dollchan-Extension-Tools#1361]
Знаю что доллчан для борд, однако, может добавить скрытие комментариев на ютубе? Или сделать отдельный форк скрипта для ютуба, который скрывал бы комментарии ровно точно так же, как скрывает посты кукла на бордах. Или может, посоветуете готовые решения? Уже нет сил видеть комментарии дегенератов - "Nobody: Absolutely nobody: Me:", "2019?" и прочий кал.

**Comment by SthephanShinkufag** [comment]
Нет, скрипт заточен под движки борд, и не предназначен для прочих ресурсов.

**Comment by SthephanShinkufag** [comment]
Решений не знаю, ибо не ставил перед собой таких задач (скрытие коментов на ютубе).
Гуглите, няшонька.
