### ISSUE TITLE
[Bug] Некорректная работа скрипта на доске архива ычановских РПГ

### ISSUE THREAD

**Issue by Satorides** [SthephanShinkufag/Dollchan-Extension-Tools#1362]
Скрипт некорректно работает на доске архива РПГ https://gensokyo.4otaku.org/curr/b/
Не работает автоподгрузка и отправка постов. Выдает «Ошибка. Сервер отправил поврежденные данные.»
Судя по всему, проблема в том, что скрипт не отправляет реферер. Из-за этого возникают проблемы с местной капчей. Кроме того, в логах замечены попытки захода под другим юзерагентом. 
Юзерагент клиента: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0

Однако на сервер в момент запроса скрипта пришло: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36 

Пришло именно с этого IP, никаких других устройств в этот момент активно не было. 

Ранее (ну, наверное еще с пол года назад) скрипт работал без проблем.

**Comment by Satorides** [comment]
Еще по-видимому кукла меняет HTTP_ACCEPT
С куклой:
   [HTTP_ACCEPT_ENCODING] => gzip, deflate
   [HTTP_ACCEPT_LANGUAGE] => ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3
   [HTTP_ACCEPT] => */*
   [HTTP_USER_AGENT] => Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0
Без куклы:
   [HTTP_ACCEPT_ENCODING] => gzip, deflate
   [HTTP_ACCEPT_LANGUAGE] => ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3
   [HTTP_ACCEPT] => text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
   [HTTP_USER_AGENT] => Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0

**Comment by SthephanShinkufag** [comment]
Да, проблема была в реферере. Исправлено.
