### ISSUE TITLE
[Bug] Не появляется список страниц

### ISSUE THREAD

**Issue by DimoNline** [SthephanShinkufag/Dollchan-Extension-Tools#1363]
1. Бесконечный скролл отключен, нет списка страниц.
![image](https://user-images.githubusercontent.com/19239834/71751630-3dc7eb80-2e8d-11ea-9c85-722dcbd38460.png)
Ошибка только на 2ch.hk
>Что пишет в консоли в момент наблюдения ошибки?
![image](https://user-images.githubusercontent.com/19239834/71751733-95feed80-2e8d-11ea-934f-27c4e50ec030.png)

Нажмите `Ctrl+Shift+K` в Firefox, или `Ctrl+Shift+J` в Chrome, чтобы открыть консоль ошибок.

**Описание браузера и Dollchan**
1. Chrome 79.0.3945.88 64 бит
2. v19.8.28.0.be594d4
3. Использую скрипт
4. Violentmonkey v2.12.4

**Шаги для воспроизведения поведения ошибки**
1. Перейти к любой доске 2ch.hk
2. Прокрутить вниз список тредов
3. Не отображается нумерация страниц

**Comment by SthephanShinkufag** [comment]
А без куклоскрипта (с отключенным Violentmonkey) нумерация страниц есть?
Может она у вас в настройках сосача отключена? Сосачевская бесконечная прокрутка удаляет нумерацию.
Настройки сосача > Другое > Бесконечная прокрутка > выставьте [Отключено].
