### ISSUE TITLE
Не получается настроить автоскрытие

### ISSUE THREAD

**Issue by MuuNU** [SthephanShinkufag/Dollchan-Extension-Tools#1364]
Все спеллы брал буквально из руководства по спеллам (Которые новый формат)
Вот что получилось

`#wipe(samelines,samewords,longwords,symbols,numbers,whitespace)
#exp(/[^a-zа-я](?:re|ре)?(?:roll|ролл)/i)
#exp(/[ -]тян[-.,?!ые ]|тян$|[ -]тн[яе]|[ -]тянк[еаиу]|[ -]тян[оy]чк[еаиу]|тянучек|[ -]тяночкой|тянам|тнн|кнн/i)  
#exp(/вр[её]+ти+/i)
#exp(/ламповая||отношашки|отношашек| ебл[яюие]|[её]б[ыа]р|альфач|омеган/i)
#exp(/кекнул|сереньк| ору[! ]|орнул|проорал| ч[её]т |за щ[её]ку|защеку|ман[яь]/i)
#exp(/хуйл|укроп|рашк|пидора[хш]|ватник|\+15|с[тр]алин|совки|совках|совковы|совкобляд|русн[яюие]/i)
(#op & #exp(/fap|фап|милф|milf|рулетка|хуетред/i))
(#exp(/оцени|анона/i) & #exp(/член|ху[йя]|глаза?/i))
(#exp(/рулетк[ао]|roll|ролл|дабл|трипл|сакральный олень/i)& #op)
(#op & #exph(/\/sticky\.png/i))
#exph(/(?:<br>\s*){4}/i)
#rep(/(№(?:<\/a><a[^>]+>)?\d*)(\d)(\2+)</g,$1<font color="red">$2$3</font><)`

При нажатии применить вылезает
`Ошибка: пропущен оператор (строка 2, столбец 5)`

**Comment by WagonOfDoubt** [comment]
Из руководства по спеллам:

> Если спеллов несколько, то все они должны быть объединены в одно логическое выражение, которое для каждого из постов также будет возвращать true или false. Для этого доступны следующие логические операции:
>   - `&` — логическое "И", `#spell_1 & #spell_2`
>   -  `|` — логическое "ИЛИ", `#spell_1 | #spell_2`
>   - `!` — логическое "НЕ", `!#spell_1`
>   -  `)` и `(` — скобки для логической группировки, `(#spell_1 & #spell_2) | #spell_3`

> **Важно!** Все спеллы скрытия должны быть связаны между собой логическими операторами. Спеллы замены должны писаться отдельно, без связующих логических операторов. Пример корректной записи:

И далее образец. В твоем случае корректная запись будет:

```
#wipe(samelines,samewords,longwords,symbols,numbers,whitespace) |
#exp(/[^a-zа-я](?:re|ре)?(?:roll|ролл)/i) |
#exp(/[ -]тян[-.,?!ые ]|тян$|[ -]тн[яе]|[ -]тянк[еаиу]|[ -]тян[оy]чк[еаиу]|тянучек|[ -]тяночкой|тянам|тнн|кнн/i) |
#exp(/вр[её]+ти+/i) |
#exp(/ламповая|отношашки|отношашек| ебл[яюие]|[её]б[ыа]р|альфач|омеган/i) |
#exp(/кекнул|сереньк| ору[! ]|орнул|проорал| ч[её]т |за щ[её]ку|защеку|ман[яь]/i) |
#exp(/хуйл|укроп|рашк|пидора[хш]|ватник|\+15|с[тр]алин|совки|совках|совковы|совкобляд|русн[яюие]/i) |
(#op & #exp(/fap|фап|милф|milf|рулетка|хуетред/i)) |
(#exp(/оцени|анона/i) & #exp(/член|ху[йя]|глаза?/i)) |
(#exp(/рулетк[ао]|roll|ролл|дабл|трипл|сакральный олень/i) & #op) |
(#op & #exph(/\/sticky\.png/i)) |
#exph(/(?:<br>\s*){4}/i)

#rep(/(№(?:<\/a><a[^>]+>)?\d*)(\d)(\2+)</g,$1<font color="red">$2$3</font></)
```

Кроме того в регулярке  `/ламповая||отношашки|отношашек|...` ошибка: двойной `||` матчит вообще все. В примере выше это исправил.

**Comment by MuuNU** [comment]
Спасибо
