### ISSUE TITLE
[Enhancement] Make "Preload Images" button change color when active

### ISSUE THREAD

**Issue by ganego** [SthephanShinkufag/Dollchan-Extension-Tools#1366]
Dollchan has a button to "Preload Images". It seems to be a toggle switch(?). But it's not possible to know if it's enabled or not.

Solution: Make button change background/white color when active. Similar to how "Thread Updater" button can be green or red.

Thank you

**Comment by SthephanShinkufag** [comment]
"Expand images", "Mask images", "Preload images" buttons now change color to green.
Check it out.

**Comment by ganego** [comment]
Seems to work.
Thanks <3
