### ISSUE TITLE
[Bug] Дублирование постов

### ISSUE THREAD

**Issue by googleitffs** [SthephanShinkufag/Dollchan-Extension-Tools#1369]
При открытии нового треда сначала все нормально, но после обновления постов весь тред целиком дублируется и вставляется вниз треда - получается дубль. 
![image](https://user-images.githubusercontent.com/53625091/76141189-e142a180-6072-11ea-9e3f-537141704b93.png)

**Comment by SthephanShinkufag** [comment]
Баг не подтверждён.

**Comment by SthephanShinkufag** [comment]
Это в каждом треде, или только в некоторых?
Настройки - инфо - отладка, покажите содержимое.

**Comment by undershoe** [comment]
> Это в каждом треде, или только в некоторых?
> Настройки - инфо - отладка, покажите содержимое.

Information for debugging:
>  {
> 	"version": "19.8.28.0.05747c3",
> 	"location": "http://boards.4channel.org/a/thread/200023084",
> 	"nav": {
> 		"canUseFetch": true,
> 		"canUseFetchBlob": true,
> 		"canUseNativeXHR": true,
> 		"firefoxVer": 0,
> 		"hasGlobalStorage": true,
> 		"hasGMXHR": true,
> 		"hasNewGM": true,
> 		"hasOldGM": false,
> 		"hasPrestoStorage": false,
> 		"hasWebStorage": false,
> 		"isChrome": true,
> 		"isESNext": true,
> 		"isFirefox": false,
> 		"isMsEdge": false,
> 		"isPresto": false,
> 		"isSafari": false,
> 		"isWebkit": true,
> 		"scriptHandler": "Tampermonkey 4.9",
> 		"ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36",
> 		"canPlayMP3": true,
> 		"hasTemplate": true,
> 		"hasWorker": true
> 	},
> 	"Cfg": {
> 		"timePattern": "nn+dd+yy+w+hh+ii-?s?s?",
> 		"txtBtnsLoc": 0,
> 		"hideBySpell": 0,
> 		"expandPanel": 1,
> 		"cfgTab": "info",
> 		"scriptStyle": 4,
> 		"addVocaroo": 0,
> 		"userCSS": 1,
> 		"userCSSTxt": "body { margin: auto; width: 1300px; }",
> 		"removeFName": 3,
> 		"linksOver": 40,
> 		"linksOut": 400,
> 		"updThrDelay": 10,
> 		"crossLinks": 1,
> 		"noSpoilers": 2,
> 		"timeRPattern": "_n/_d/_y(_w)_h:_i:_s",
> 		"spells": "[1581357145046,null,null,null]",
> 		"sendErrNotif": 0
> 	},
> 	"sSpells": [
> 		""
> 	],
> 	"perf": {
> 		"Imageboard check": 0,
> 		"Storage loading": 6,
> 		"Init": 4,
> 		"Read my posts": 0,
> 		"Replace delform": 21,
> 		"Parse delform": 17,
> 		"Parse postform": 162,
> 		"Init keybinds": 0,
> 		"Init page": 9,
> 		"Add panel": 302,
> 		"Image-links": 0,
> 		"Init AJAX": 0,
> 		"Preload images": 1,
> 		"Audio links": 2,
> 		"Video links": 1,
> 		"Image names": 4,
> 		"Reflinks map": 3,
> 		"Apply CSS": 4,
> 		"Display page": 0,
> 		"Infinity scroll": 0,
> 		"Hide posts": 2,
> 		"Scroll page": 0,
> 		"Total": 538
> 	}
> }

Я не совсем уверен, в какие моменты это появляется. Когда я создаю новый тред, несколько раз такое было. Сейчас вот почему-то тот же самый тред вернулся к норме, хотя я ничего не делал, разве что страницу обновил.

**Comment by SthephanShinkufag** [comment]
Сообщите сюда, если отследите закономерность.

**Comment by mkefa** [comment]
тоже такое **рандомно** случается

**Comment by SthephanShinkufag** [comment]
Такое случается, если нажать на макабовскую кнопку "Обновить". Скрыл кнопку.
