### ISSUE TITLE
[Enhancement] опция спрятать лайк/дислайк на /по/раше харкача

### ISSUE THREAD

**Issue by perdolka** [SthephanShinkufag/Dollchan-Extension-Tools#1370]
Скриптоклоуны с диаметрально противоположными полит.взглядами, накручивают лайк/дислайк по ключевым словам, поэтому циферки становятся абсолютно бесполезными и только отвлекают внимание.

**Comment by perdolka** [comment]
Пример: коммунистов раздражает слово "котлета". 
Поэтому когда коммунистический скрипт натыкается на пост с котлетами он его беспощадно дислойсит.

**Comment by SthephanShinkufag** [comment]
Настроки - Общее - Пользовательский CSS:

```css
.post__rate {
    display: none;
}
```
