### ISSUE TITLE
[Bug] /statcount don't work

### ISSUE THREAD

**Issue by Nimond** [SthephanShinkufag/Dollchan-Extension-Tools#1373]
1. Четкое описание ошибки. Что произошло?
Я ввел команду `/statcount` и она не заменилась на статистику
2. Какого поведения вы ожидали?
```2ch
Тредов создано: 87
Тредов посещено: 7928
Тредов скрыто: 0
Всего сообщений: 11726 
```
3. Ошибка происходит на конкретном имиджборде, или везде?
везде
4. Что пишет в консоли в момент наблюдения ошибки?
ничего

**Описание браузера и Dollchan**
1. firefox 75.0, archlinux
2. v20.3.17.0.d4bfe2e.es6
3. addon

**Шаги для воспроизведения поведения ошибки**
1. Перейти к двочу
2. Прокрутить вниз до треда
3. Нажать «ответить в тред»
4. Ввести `/statcount`
5. Не появляется статистика

**Comment by SthephanShinkufag** [comment]
Dollchan никогда не заменял `/statcount` на статистику.
Или `2ch.hk` делает замену без Dollchan, а с ним эта замена не происходит?

**Comment by ancap-kun** [comment]
Надо /postcount писать, нуфажина
