### ISSUE TITLE
[Bug] Ernstchan.xyz - Can't post files with "Posting without page refresh" active

### ISSUE THREAD

**Issue by Ernstian** [SthephanShinkufag/Dollchan-Extension-Tools#1375]
Firefox 76.0.1 (64-Bit)
Dollchan 20.3.17.0
Tampermonkey 4.10.6112

If I try to post a file to ernstchan.xyz with "Posting without page refresh" active, I'll get a "403 Request Timeout" response from the server. If I turn it off, the file posts normally.

**Comment by SthephanShinkufag** [comment]
Ernstchan is dead.
