### ISSUE TITLE
kohlchan.net

### ISSUE THREAD

**Issue by pdftk** [SthephanShinkufag/Dollchan-Extension-Tools#1376]
Firefox 77.0.1
Dollchan 20.3.17.0
Tampermonkey 4.10.6112
The script stopped working on krautchan.net at all.

**Comment by SthephanShinkufag** [comment]
> krautchan.net

lol what
krautchan.net is down two years ago...

**Comment by pdftk** [comment]
D'oh! Sorry, of course it's kohlchan.net

**Comment by pdftk** [comment]
Works now. Thanks for fixing it.
