### ISSUE TITLE
[Enhancement] Генерировать название для загружаемого файла

### ISSUE THREAD

**Issue by perdolka** [SthephanShinkufag/Dollchan-Extension-Tools#1381]
Опция - во время отправки поста переименовывать файлы, 
загружаемые с диска или из буфера обмена, 
на набор случайных знаков например, или что-то типа "1.png"

Иногда в названии может быть нежелательная информация.

Имеющаяся опция "прятать имена изображений" не совсем походит, 
потому что при наведении курсора оригинальное название всё равно можно посмотреть.

**Comment by Y0ba** [comment]
Уже есть же. Форма -> имена файлов.

**Comment by perdolka** [comment]
Упс, звиняйте.
