### ISSUE TITLE
[Bug] При отправке сообщения не прогружается капча на 2ch.hk

### ISSUE THREAD

**Issue by VictorDragonslayer** [SthephanShinkufag/Dollchan-Extension-Tools#1387]
**Прежде, чем отправлять баг репорт**
- Удостоверьтесь, что вы пользуетесь последней версией. **Удостоверился.**
  Если вы используете юзерскрипт, попробуйте обновиться по ссылке:
  https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/raw/master/src/Dollchan_Extension_Tools.es6.user.js
- Наблюдается ли данная ошибка, если выключить Dollchan? **Нет.**
- Поищите упоминание об этом баге, возможно, отчёт о нём уже был раньше. **Пусто.**

**Опишите вашу ошибку**
_1. Четкое описание ошибки. Что произошло?_
При отправке сообщения в правом верхнем углу экрана бесконечно крутится "reCaptcha...", капча не приходит.
_2. Какого поведения вы ожидали?_
Ожидалась отправка сообщения.
_3. Ошибка происходит на конкретном имиджборде, или везде?_
Тестировалось только на 2ch.hk.
_4. Что пишет в консоли в момент наблюдения ошибки?
Нажмите `Ctrl+Shift+K` в Firefox, или `Ctrl+Shift+J` в Chrome, чтобы открыть консоль ошибок._
Uncaught ReferenceError: deCapWidget is not defined
    <anonymous> https://2ch.hk/test/res/31814.html#171505 line 1792 > injectedScript:1
    $script moz-extension://b687a2ce-0102-491d-bd03-3686cbaf43c1/Dollchan Extension Tools.user.js#1:1792
    updateCaptcha moz-extension://b687a2ce-0102-491d-bd03-3686cbaf43c1/Dollchan Extension Tools.user.js#1:16438
    _capUpdPromise moz-extension://b687a2ce-0102-491d-bd03-3686cbaf43c1/Dollchan Extension Tools.user.js#1:10226
    wrap moz-extension://b687a2ce-0102-491d-bd03-3686cbaf43c1/Dollchan Extension Tools.user.js#1:1993

**Описание браузера и Dollchan**
1. Firefox 84.0 (64-бит)
2. v20.3.17.0.dd8a83a.es6
3. Юзерскрипт
4. Скриптменежер - Violentmonkey 2.12.7

**Шаги для воспроизведения поведения ошибки**:
1. Выключить пасскод.
2. Зайти в /test/, в ответе на ОП-пост написать "тест".
3. Нажать на кнопку "Ответ".
4. В правом верхнем углу экрана бесконечно крутится "reCaptcha...", капча не приходит.

**Скриншоты**
![изображение](https://user-images.githubusercontent.com/20127025/102719174-96da9a80-42fd-11eb-94a4-28fcb9c50ba1.png)

**Comment by VictorDragonslayer** [comment]
Ошибка перестала воспроизводиться. Повторится - открою заново.

**Comment by imasuridondai** [comment]
Ну вот, повторилась. Уже не первый день как повторяется
