### ISSUE TITLE
Не работает замена в #rep, если в регулярке есть якоря (^$)

### ISSUE THREAD

**Issue by altwarg** [SthephanShinkufag/Dollchan-Extension-Tools#1388]
**Опишите вашу ошибку**
1. Спелл замены `#rep()` не работает, если в регулярке указаны якоря (anchors). Например, спелл `#rep(/^сап$/ig,привет)` не работает (не зависит от набора флагов regexp). Если же применять без якорей, то, очевидно, что спелл `#rep(/сап/ig,привет)` заменит все сочетания `сап` в всех словах и получается в результате, что заменяются слова `сап, сапоги, сапфир, ватсап` на `привет, приветоги, приветфир, ватпривет`.
2. Ожидалось, что при применении якорей, обозначающих начало-конец строки, будут заменяться конкретные слова, но замены не происходит
3. Имиджборда -- харкач
4. Ошибок в консоли нет

**Описание браузера и Dollchan**
1. Хромоног ungoogled (87.0.4280.67)
2. Собственно, последняя версия куклоча для хромонога (20.3.17.0)
3. Используется расширение

**Шаги для воспроизведения поведения ошибки**
1. Добавить спелл в настройки
2. Открыть харкач
3. ?????????
4. BUG

**Скриншоты**
Поведение с заменой всех сочетаний:
![image](https://user-images.githubusercontent.com/34391398/106403468-f28d5d00-643f-11eb-9c80-15c66f101038.png)

Если ставим якоря, то, в этом треде все нормально:
![image](https://user-images.githubusercontent.com/34391398/106403644-c2928980-6440-11eb-91d7-b390e2a2fb5a.png)

Но стоит зайти в соседний и выставить, допустим, флаг i (без флагов тоже не работает):
![image](https://user-images.githubusercontent.com/34391398/106403500-1b155700-6440-11eb-8297-11fc6f9cb69f.png)

**Comment by SthephanShinkufag** [comment]
`#rep` применяется не к тексту постов, а к HTML-содержимому контейнера с тредами.

**Comment by altwarg** [comment]
@SthephanShinkufag, issue не по поводу того, как работает `#rep`, но по поводу того, что первым параметром спелла, как я понял, выступает регулярка, и такая обыденная для регулярок вещь как якоря в ней не работают

**Comment by SthephanShinkufag** [comment]
Поиск идёт по контейнеру с тредами. Начало строки - это начало HTML текста первого треда. Конец строки - конец HTML последнего треда.

**Comment by altwarg** [comment]
@SthephanShinkufag, какие есть варианты, чтобы заменить так, как мне необходимо, содержимое тредов? В wiki упоминается для этого только `#rep`, и мне необходимо заменить в ней целиком слово, а не подстроку -- не важно насколько короткой строка для того притом должна быть.

**Comment by SthephanShinkufag** [comment]
#rep(/([^а-я])сап([^а-я])/ig, $1привет$2)

**Comment by altwarg** [comment]
@SthephanShinkufag, жутчайший костыль, конечно. Но ладно, хоть такой вариант есть. Закрываю issue

**Comment by SthephanShinkufag** [comment]
Слово в строке выделяется ограничителями, в данном случае не буквенными символами. Придумайте регулярку лучше, я за вас регекспы что-ли должен придумывать.

`#rep(/(\W))сап(\W)/ig, $1привет$2)`

**Comment by SthephanShinkufag** [comment]
Есть ещё такой вариант:

`#rep(/(?:\W)хрюююю(?:\W)/ig, привет)`

Чтобы исключить замену ограничительных символов.
