### ISSUE TITLE
[Bug] italics formatting on kohlchan.net

### ISSUE THREAD

**Issue by gruzefix** [SthephanShinkufag/Dollchan-Extension-Tools#1390]
The formatting options for italics is off on kohlchan.net.

Using
`''italics''`
yields
`"italics"`
instead of
_italics_ .

The rest works fine though.

**Comment by ganego** [comment]
See https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/issues/1332#issuecomment-803452530

**Comment by SthephanShinkufag** [comment]
https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/commit/3d3d69306d0a783ebc3e9ddfae5706e03956df30
