### ISSUE TITLE
[Bug] не скачиваются thumbs в архиве треда с 4chan

### ISSUE THREAD

**Issue by aleksejrs** [SthephanShinkufag/Dollchan-Extension-Tools#1392]
**Опишите вашу ошибку**
1. Файлы в каталоге thumbs/ имеют размер 0 байт.
2. Превьюшки на скачанной странице должны быть.
3. 4chan
4. Что пишет в консоли в момент наблюдения ошибки?

```
GEThttps://boards.4channel.org/wsr/thread/data/50.png
[HTTP/2 404 Not Found 37ms]

GEThttps://boards.4channel.org/wsr/thread/data/a9c97dc2b0bc556e972204452bc55332c846e85b.gif
[HTTP/2 404 Not Found 30ms]

GEThttps://boards.4channel.org/wsr/thread/data/partyhat.gif
[HTTP/2 404 Not Found 31ms]

GEThttps://boards.4channel.org/wsr/thread/data/modicon.gif
[HTTP/2 404 Not Found 32ms]

GEThttps://boards.4channel.org/wsr/thread/data/sticky.gif
[HTTP/2 404 Not Found 32ms]

GEThttps://boards.4channel.org/wsr/thread/data/closed.gif
[HTTP/2 404 Not Found 31ms]
```

**Описание браузера и Dollchan**
1. Firefox 86.0.1 (64-bit)
2. Расширение v20.3.17.0
3, 4. юзерскрипт v20.3.17.0.dd8a83a.es6 на Violentmonkey v2.12.11.

**Шаги для воспроизведения поведения ошибки**
1. Перейти к https://boards.4channel.org/wsr/thread/1
2. Нажать «Download thread»
3. В скачанном архиве файл(ы) в каталоге thumbs/ имеют размер 0 байт.

**Comment by SthephanShinkufag** [comment]
Исправлено. Пробуйте.

**Comment by aleksejrs** [comment]
Работает, но [здесь](https://boards.4channel.org/mlp/thread/36754433), если скачать сразу после загрузки, несколько файлов среди первых пустые.

**Comment by SthephanShinkufag** [comment]
А теперь?

**Comment by aleksejrs** [comment]
Вроде работает, спасибо.
