### ISSUE TITLE
[Bug] харкач - не отправляются посты

### ISSUE THREAD

**Issue by perdolka** [SthephanShinkufag/Dollchan-Extension-Tools#1393]
Не отправляются посты, если включён куклоскрипт.
Крутящийся кружок символизирует вечную загрузку гуглокапчи.
Кукла:
const version = '20.3.17.0';
const commit = 'dd8a83a';

Firefox 78.8.0esr

**Comment by nikitaivantsov** [comment]
Не работает через Greasemonkey и в виде аддона
Через Violentmonkey/Tampermonkey работает, только отправляется со второго раза (первый раз можно нажать Ответ без решения капчи, потом решить её и нажать Ответ второй раз).

**Comment by perdolka** [comment]
О, кстати забыл уточнить.
У меня Violentmonkey (v2.12.11)

**Comment by nikitaivantsov** [comment]
У меня Firefox Developer 87, работает. Версия Violentmonkey та же.
У других анонов судя по треду в /d тоже начинает работать при установке Violentmonkey/Tampermonkey
Попробуй с более новой версией Firefox'а

**Comment by perdolka** [comment]
Альтернативная капча работает. Галка почему-то слетела, а я и не заметил.

**Comment by theanonym** [comment]
Со стандартной капчей бесконечно пишет "reCaptcha..."
С альтернативной пишет "Ошибка: Капча невалидна."
Не знаю что делать, сброс настроек куклоскрипта+удаление кук сосача не помогает
