### ISSUE TITLE
[Enhancement] Добавлять в имя файла при скачивании треда тему или начало первого поста.

### ISSUE THREAD

**Issue by aleksejrs** [SthephanShinkufag/Dollchan-Extension-Tools#1396]
**Ваш запрос на улучшение функционала связан с проблемой?**
В куче .tar-файлов не видно, какие из них с чем.

**Опишите ваше решение, которое вы хотели бы увидеть в реализации**
Было бы удобно, если бы в именах файлов сразу были отфильтрованные до допустимых символов начала названия тем (если есть) или первых постов.

in English: when downloading a thread, put the subject or the beginning of the first post into the file name.

**Comment by SthephanShinkufag** [comment]
Сделано. Отображается тема поста, либо первые слова из текста, если темы нет.

**Comment by konacha** [comment]
Bug: it [doesn't ignore double quotes](https://files.catbox.moe/1djts1.png) in the subject (at least on windows)
Try downloading this [thread ](https://nocsp.kohlchan.net/m/res/133340.html)

Also, this is just my opinion, but isn't that functinality better left as an optional setting?
