### ISSUE TITLE
How do you decrease the time of a selected post?

### ISSUE THREAD

**Issue by darlopvil** [SthephanShinkufag/Dollchan-Extension-Tools#1397]
Hi,

Perhaps my question is kinda confusing but I don't know if there is even a way to do it or not, or it is what it is. Once you are in a determined post and let's suppose it has some replies you can move the cursor over the replies and the reply will appear  immediately, right? Just by hovering it. But if you want to return to the original post or go to other in the thread (the cursor has obviously moved), the previous reply-post is still popped-up until it vanishes. 

So, Is there some secret configuration in the settings that i haven`t seen yet that able you to decrease that time in seconds or even instantaneously and so by that, once you move your cursor, the reply-post disappears?

I've attached a video in case I haven't been understood:

https://user-images.githubusercontent.com/60988792/119242918-57410480-bb62-11eb-9532-729e3c292741.mp4

**Comment by Remu-rin** [comment]
![image](https://user-images.githubusercontent.com/28995228/119356612-10692100-bcc0-11eb-8d39-39c8e305edf9.png)

**Comment by darlopvil** [comment]
Thank you so much! I didn't even notice
