### ISSUE TITLE
2ch[captcha]

### ISSUE THREAD

**Issue by tuxarch** [SthephanShinkufag/Dollchan-Extension-Tools#1400]
Абу опять играется с капчей. Почини плиз.
![photo_2021-07-01_01-19-15](https://user-images.githubusercontent.com/17531010/124052699-a0208e80-da27-11eb-84dd-59f9f608c7a7.jpg)

**Comment by childrenofwater** [comment]
Алсо, почему-то даже с выключением куклы через скрипт, то есть без ее отключения как скрипта, вообще не дает постить с ошибкой Bad Gateway.

**Comment by SthephanShinkufag** [comment]
Заменил инвизибл рекапчу на 2chcaptcha. Оставил опцию `Форма` > `"Использовать альтернативную капчу"` на случай, если рекапчу включат назад. Пока эта опция должна быть отключена.
