### ISSUE TITLE
[4chan] New captcha

### ISSUE THREAD

**Issue by pilaco** [SthephanShinkufag/Dollchan-Extension-Tools#1402]
![image](https://user-images.githubusercontent.com/22872431/124503925-df8b0a00-dd9c-11eb-8a39-b9a5194e26bc.png)

**Comment by SthephanShinkufag** [comment]
![изображение](https://user-images.githubusercontent.com/1059874/124512896-336c1200-dde2-11eb-90eb-23349a67c548.png)

What the f

**Comment by SthephanShinkufag** [comment]
As I understand, Google introduced a fee for using recaptcha. Everyone is abandoning recaptcha now, coming up with all sorts of crap. Focking shiet.

**Comment by SthephanShinkufag** [comment]
Done. Please check.
