### ISSUE TITLE
[Bug?] Dollchan in Firemonkey

### ISSUE THREAD

**Issue by kr4ssi** [SthephanShinkufag/Dollchan-Extension-Tools#1404]
Just tried to load the newest version of Dollchan into [Firemonkey](https://addons.mozilla.org/de/firefox/addon/firemonkey/) using Firefox 91. Firemonkey uses the [Official Userscripts-API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/userScripts).
It worked so far until I tried to post, then I get this Error on several tested imageboards:
```
✖ Internal error:
Error: Accessing TypedArray data over Xrays is slow, and forbidden in order to encourage performant code. To copy TypedArrays across origin boundaries, consider using Components.utils.cloneInto().
    at cleanFile (Dollchan%20Extension%20Tools.user.js:16919:9)
    at _callee23$ (Dollchan%20Extension%20Tools.user.js:16836:45)
    at tryCatch (Dollchan%20Extension%20Tools.user.js:4882:40)
    at invoke (Dollchan%20Extension%20Tools.user.js:5066:30)
    at [244]
```
There isn't anything else in the console besides of:
`Error: An unexpected apiScript error occurred`

Is this a bug in Dollchan, Firemonkey, or Firefox?

**Comment by SthephanShinkufag** [comment]
FireMonkey have many problems. It cannot use arraybuffer and blob requests in both GM.xmlHttpRequest and GM_xmlhttpRequest. It has Xray error when accessing TypedArray.... A lot of bugs.

**Comment by SthephanShinkufag** [comment]
Tried to fix all of that, but may be another problems.

**Comment by kr4ssi** [comment]
That was quick, thanks man.

**Comment by kr4ssi** [comment]
I get "can't load url" when I drag and drop an imagelink into the fileupload. There isn't anything else in the console.

**Comment by SthephanShinkufag** [comment]
It's easier to drop this shit, seriously.

**Comment by SthephanShinkufag** [comment]
`Load titles for YouTube links*` also. FireMonkey is raw, and doesn't work as expected.

**Comment by SthephanShinkufag** [comment]
Seems Firemonkey works fine now.
