### ISSUE TITLE
[Bug] Настоящее имя файла не устанавливается

### ISSUE THREAD

**Issue by aleksejrs** [SthephanShinkufag/Dollchan-Extension-Tools#1405]
**Опишите вашу ошибку**
При выборе в меню «🔍» пункта для сохранения с настоящим именем (#1045) картинка открывается в новой вкладке с числовым именем, и настоящему имени там  быть уже негде.

3. Ошибка происходит на конкретном имиджборде, или везде?
4chan. На 2ch работает.

4. Что пишет в консоли в момент наблюдения ошибки?
Ничего.

**Описание браузера и Dollchan**
1. Firefox 91.0.2 (64-bit)
2. v21.7.6.0
3. и с расширением, и с юзерскриптом.

**Comment by SthephanShinkufag** [comment]
Dollchan задаёт аттрибут download, который позволяет сохранять изображения с кастомными именами. Проблема в том, что на форчане картинки хранятся на другом домене, i.4cdn.org. Пример: https://i.4cdn.org/int/1630868801791.jpg
Атрибут download не работает для кроссдоменных ссылок, из соображений безопасности.

**Comment by SthephanShinkufag** [comment]
Теперь детектируется совпадение домена страницы и домена файла. Если они не совпадают, то скрипт по клику считывает картинку в blob и отдаёт его с кастомным именем.

**Comment by aleksejrs** [comment]
Работает, спасибо.
