### ISSUE TITLE
Не работает загрузка файлов из буфера обмена

### ISSUE THREAD

**Issue by wololowins** [SthephanShinkufag/Dollchan-Extension-Tools#1406]
Chrome 94.0.4606.61
Версия - 21.7.6.0 
Tampermonkey 4.13

На дваче, при вставке через Ctrl+v из проводника windows нескольких фалов, добавляется только один(в хроме). В фаерфоксе 92.0 тоже пробовал, используя расширение и tampermonkey - вообще ни один не добавляется.

**Comment by SthephanShinkufag** [comment]
Исправлена вставка в Хроме.
Очень жаль, но в Firefox недоступна вставка файлов из проводника через буфер обмена. Но зато работает с изображениями в буфере обмена, полученными другим путём, например скриншоты по кнопке PrintScreen, скопированные изображения из редакторов (выделить и скопировать область в пейнте), либо через контекстное меню "копировать изображение" в браузере.
