### ISSUE TITLE
[2ch.life] Не подхватывается скрипт.

### ISSUE THREAD

**Issue by Nodenes** [SthephanShinkufag/Dollchan-Extension-Tools#1412]
Собственно, на зеркале харкача не запускается кукла. В загрузках Violentmonkey активен, но панельки на страничке нет.

**Comment by Dimki100** [comment]
Подтверждаю. Пользуюсь через Tampermonkey, но панельки нет. Когда стоит ждать какое-нибудь обновление, зеркало появилось около месяца назад

**Comment by perdolka** [comment]
Дваждую проблему.

кукла:
const version = '21.7.6.0';
const commit = 'a265892';

Аддон: Violentmonkey 2.13.0

ФФ: 91.4.0esr
