### ISSUE TITLE
[Bug] не работает ihash

### ISSUE THREAD

**Issue by solara322** [SthephanShinkufag/Dollchan-Extension-Tools#1423]
Скрипт не может скрыть файл по ihash.
Сам файл, https://2ch.life/vg/res/42490979.html#42499752
когда его скрываешь - в списке появляется "#ihash[vg,42490979] |". То есть без хэша.
![image](https://user-images.githubusercontent.com/40701744/159081577-e16f20a4-abaf-44ba-823d-9d00b786c031.png)

**Comment by SthephanShinkufag** [comment]
Исправлено. Только теперь все прошлые `#ihash` недействительны, так как теперь хеши будут генерироваться другие.
