### ISSUE TITLE
[2ch]Плавающая форма

### ISSUE THREAD

**Issue by justUjin** [SthephanShinkufag/Dollchan-Extension-Tools#1426]
Читая в серии раскрытых постов хочется на какой-то из них ответить и тебя кидает к этому посту с гиганской уродливой формой, встраиваемой под постом и потом надо долго искать то место, откуда же ты начал. Можно сделать как без куклоскрипа, когда форма плавающая в том месте, где ты кликнул, без скролла треда?

Спасибо

**Comment by SthephanShinkufag** [comment]
Плавающую форму можно уменьшить, потянув за её край.
Форму можно переключить в режим "под постом", нажав на кнопку со стрелкой в шапке плавающей формы.

![Floating_form_toggle](https://user-images.githubusercontent.com/1059874/173934394-a5bccb1c-58aa-41ad-9592-73c3a2b2b8fe.jpg)
