### ISSUE TITLE
[2ch]Выделенный текст в посте, на который открываешь форму ответа кидать автоматом в цитату (как в нативе)

### ISSUE THREAD

**Issue by justUjin** [SthephanShinkufag/Dollchan-Extension-Tools#1427]
Собственно, без куклоскрипта очень круто, когда выделяешь текст, нажимаешь ответить на посте и сразу в форме идет ссылка на пост и цитата того, что выделил. Чому бы не добавить такую фичу сюда?

**Comment by SthephanShinkufag** [comment]
Это уже много лет как есть. Нажимайте на кнопку с треугольником, а не на номер поста.
Нажатие на кнопку "Ответить на пост" открывает форму ответа и вставляет ссылку на пост с цитатой, если текст выделен.
Нажатие на номер поста:
- в треде - открывает форм ответа и в вставляет ссылку на пост, без цитат.
- в списке тредов - перемещает вас в тред к этому поста.
