### ISSUE TITLE
[Enhancement][2ch][Spells] Иметь перманентные спеллы и спеллы на тред раздельно

### ISSUE THREAD

**Issue by justUjin** [SthephanShinkufag/Dollchan-Extension-Tools#1428]
Есть спеллы общие, есть скрытия на треды. Они все в одной куче и накапливаются, хотя треды уже давно покинуты или удалены и приходится их чистить.

Можно разделить спеллы на глобальные и на локальные, плесс?

**Comment by SthephanShinkufag** [comment]
Теперь опция `"Фильтры"` > `"Сортировать спеллы и удалять дубликаты"` сортирует спеллы по доскам и тредам. Включите эту опцию, чтобы задействовать сортировку.
