### ISSUE TITLE
[Bug] Не работает форма постинга на новом движке сосаки

### ISSUE THREAD

**Issue by arkeyaallods** [SthephanShinkufag/Dollchan-Extension-Tools#1433]
Версия [v21.7.6.0.44a4c26.es6]
Там на сосаке всё передрочено в щи, новый говнодвижок и всё такое. Скрипт запускается, скрывает посты, разворачивает картинки и делает всё, что положено, но нет окошка для ввода текста при ответе. Вот как сейчас выглядит это дерьмо.
![Screenshot 2022-08-06 155804](https://user-images.githubusercontent.com/110594899/183234685-3ec58f38-59c5-4534-ae2b-c83d1a3796dc.png)

**Comment by kontolxd** [comment]
А как ты вообще куклу запустил под новый говнодвижок? У меня что на винде, что на ляниксах кукла просто исчезла.

**Comment by berbunda** [comment]
кукла запускается в бреде, но форма ответа куцая и ущербная

**Comment by arkeyaallods** [comment]
> А как ты вообще куклу запустил под новый говнодвижок? У меня что на винде, что на ляниксах кукла просто исчезла.
Аяхуйзнает, она просто работала в таком виде сегодня, когда я запустил браузер. Естественно, это всё в бредаче, другие-то разделы вообще не работают.

**Comment by SimWolfschebnickoff** [comment]
У меня вовсе не работает "Куклоскрипт" на этом сайте. Браузер Firefox ESR, скрипт для Greasemonkey.

**Comment by Malomalsky** [comment]
Они убили куклу...

**Comment by RichardSimple** [comment]
У меня в FF 88 + Violentmonkey 2.13.0 скрипт 21.7.6.0 (44a4c26), как и у ОПа, +- работает. И поля для ввода текста поста тоже нет.

В качестве временного решения проблемы с полем можно в пользовательский CSS добавить:
`#postform .postarea {
	display: block !important;
}`

Сразу после постинга, правда, рапортуется "Ошибка: undefined" и пост не выделяется как "мой", хотя и отправляется успешно.

**Comment by devbased** [comment]
Они поменяли апи постинга. Теперь приходит
```json
{"num":12345678,"result":1}
```
вместо
```json
{"Num":12345678,"Status":'OK'}
```
т.е. надо поправить парсинг в `getSubmitData(json)` ну и не скрывать postarea, как @RichardSimple посоветовал
Также файлы необходимо отправлять под именем `file[]` вместо `formimages[]`

**Comment by SimWolfschebnickoff** [comment]
А как тогда решить проблему, что "Кукла" на новом beta.2ch.hk не работает вовсе, если установлено, чтобы она работала только на определённых сайтах?

**Comment by kontolxd** [comment]
Заметил, что кукла пропала только на фурифоксах. На едже и хромиуме все ок.

**Comment by imasuridondai** [comment]
Firefox 103.0.1 (64-bit). Greasymonkey 4.11, кукла v21.7.6.0.44a4c26 никуда не пропала

**Comment by SimWolfschebnickoff** [comment]
> Firefox 103.0.1 (64-bit). Greasymonkey 4.11, кукла v21.7.6.0.44a4c26 никуда не пропала

А вы попробуйте в параметрах скрипта поставить, чтобы он работал только на определённых сайтах.

**Comment by hiigara123** [comment]
Хотфикс
https://github.com/hiigara123/Dollchan-Extension-Tools/blob/master/src/Dollchan_Extension_Tools.es6.user.js

**Comment by arkeyaallods** [comment]
> Хотфикс https://github.com/hiigara123/Dollchan-Extension-Tools/blob/master/src/Dollchan_Extension_Tools.es6.user.js

У меня в нём не сохраняются изменения настроек, вроде стиля панельки или таймингов появления/пропадания всплывающих ответов. Меняю, обновляю страницу и нихуя. Edge 103, violentmonkey 2.13.0. В оригинальном куклоскрипте всё применялось и сохранялось.

**Comment by apan65** [comment]
Cтепан, ну уже и хотфиксы всякие васяны запилили, что трудно что ли скрипт обновить? Там пару строчек поправить.

**Comment by PeteBurns6** [comment]
Усовершенствованный хотфикс
https://github.com/PeteBurns6/Dollchan-Extension-Tools/blob/fix-2ch.hk/src/Dollchan_Extension_Tools.es6.user.js

**Comment by tsunamaru** [comment]
> Cтепан, ну уже и хотфиксы всякие васяны запилили, что трудно что ли скрипт обновить? Там пару строчек поправить.

@apan65 у Степана в стране война идёт. Ему _немного_ не до этих ваших куклоскриптов сейчас.

**Comment by Y0ba** [comment]
Думаю всё было исправлено в #1437? Если нет, то лучше будет открыть новый issue.
