### ISSUE TITLE
[Bug] Не работает скрипт для Greasemonkey на новом beta.2ch.hk

### ISSUE THREAD

**Issue by SimWolfschebnickoff** [SthephanShinkufag/Dollchan-Extension-Tools#1434]
Здравствуйте, на новом сайте "Двач" скрипт для Greasemonkey (браузер Firefox ESR) не работает вовсе, хотя в параметрах скрипта, в разделе "Пользовательские включения" (и стоит галочка на "Использовать только эти"), добавлены https://beta.2ch.hk/* и https://2ch.life/*.

**Comment by Y0ba** [comment]
Проблемы нового движка 2ch.hk/2ch.life должны быть исправлены после #1437. Обновитесь и проверьте снова.

**Comment by SimWolfschebnickoff** [comment]
> Проблемы нового движка 2ch.hk/2ch.life должны быть исправлены после #1437. Обновитесь и проверьте снова.

Да, теперь работает правильно.
