### ISSUE TITLE
Перестал работать скрипт на Доброчане [Bug]

### ISSUE THREAD

**Issue by SimWolfschebnickoff** [SthephanShinkufag/Dollchan-Extension-Tools#1445]
На Доброчане перестал работать скрипт. Да, в параметрах скрипта Greasemonkey стоит галочка "Использовать только эти", где и прописаны борды, чтобы Кукла работала только на них. Браузер Firefox ESR.

На других имиджбордах работает нормально.

**Comment by SimWolfschebnickoff** [comment]
Баг с "Два Си Эйч" исправили быстро, а на Доброчан всем всё равно, пооже.

**Comment by SimWolfschebnickoff** [comment]
> Только что проверил и вроде всё работает. Можешь адрес дать с которого заходишь? Кто-то в треде адрес на `.net` упомянул. Может в этом дело?

Да, .net.

**Comment by Y0ba** [comment]
Тогда проверь с последней версией. Я добавил этот адрес в скрипт.

**Comment by SimWolfschebnickoff** [comment]
> Тогда проверь с последней версией. Я добавил этот адрес в скрипт.

Да, теперь работает. Спасибо.
