### ISSUE TITLE
[Enhancement] Обновите расширение для FF

### ISSUE THREAD

**Issue by XakepSDK** [SthephanShinkufag/Dollchan-Extension-Tools#1449]
**Ваш запрос на улучшение функционала связан с проблемой?**
Расширение давно не обновляли на Firefox.

https://addons.mozilla.org/en-US/firefox/addon/dollchan-extension/

**Опишите ваше решение, которое вы хотели бы увидеть в реализаци**
Новую версию расширения со всеми фиксами

**Comment by SthephanShinkufag** [comment]
Если никуда не пропаду, постараюсь апать версию и собирать билды расширения раз в пару недель.
