### ISSUE TITLE
[Bug] 4chan infinite scrolling not working

### ISSUE THREAD

**Issue by roworu** [SthephanShinkufag/Dollchan-Extension-Tools#1455]
**Describe your bug**
1. A clear description of the bug. What happened?
Open 4chan board and scroll to the end, getting dollchan error
2. What behavior did you expect?
infinite scrolling
3. Does the error occur on a specific imageboard, or everywhere?
I only can see this issue on 4chan
4. What is written in the console at the time of seeing the bug?
`InstallTrigger is deprecated and will be removed in the future. constants.js:50:14
Loading failed for the <script> with source “https://platform.bidgear.com/async.php?domainid=176&sizeid=1&zoneid=5050&k=1665755988623”. g:1:1
Loading failed for the <script> with source “https://platform.bidgear.com/async.php?domainid=176&sizeid=1&zoneid=5078&k=1665755988623”.`

**Browser and Dollchan Description**
1. Specify your browser and its version
Firefox 105.0.3 (64-bit)
2. Specify the version of your Dollchan [for example, v18.12.29.0.e7e44f7.es6]
21.7.6.0
3. What do you use: chrome extension or userscript?
userscript
4. If you are using a userscript, specify your script manager
Violentmonkey 2.13.2

Dollchan error:
Internal error:
TypeError: text is undefined
    at getAjaxResponseEl (%20Dollchan%20Extension%20Tools.user.js#1:7030:2)
    at ajaxLoad/< (%20Dollchan%20Extension%20Tools.user.js#1:7039:31)
    at wrap/< (%20Dollchan%20Extension%20Tools.user.js#1:2049:20)
Screenshot: 
![image](https://user-images.githubusercontent.com/36964755/195866298-713bc598-b89f-451d-8a3d-30eacaf9fe8c.png)

**Comment by SthephanShinkufag** [comment]
Please check the last commit version.

**Comment by roworu** [comment]
Working good now, thank you!
