### ISSUE TITLE
На endchan.gg пропадает пост если ввести неправильную капчу

### ISSUE THREAD

**Issue by sisyphussend** [SthephanShinkufag/Dollchan-Extension-Tools#1464]
**Прежде, чем отправлять баг репорт**
- Удостоверьтесь, что вы пользуетесь последней версией.
  Если вы используете юзерскрипт, попробуйте обновиться по ссылке:
  https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/raw/master/src/Dollchan_Extension_Tools.es6.user.js
- Наблюдается ли данная ошибка, если выключить Dollchan?
- Поищите упоминание об этом баге, возможно, отчёт о нём уже был раньше.

**Опишите вашу ошибку**
1. Четкое описание ошибки. Что произошло? **После отправления поста с неправильно введенной капчей, пост пропадает из поля ввода.**
2. Какого поведения вы ожидали? **Пост остается в поле и в углу экрана появляется сообщение об ошибке.**
3. Ошибка происходит на конкретном имиджборде, или везде? **https://endchan.gg**
4. Что пишет в консоли в момент наблюдения ошибки? Нажмите `Ctrl+Shift+K` в Firefox, или `Ctrl+Shift+J` в Chrome, чтобы открыть консоль ошибок.
![image](https://user-images.githubusercontent.com/124622775/217072186-d97215ef-9707-44e1-a286-a408adf91688.png)

**Описание браузера и Dollchan**
1. Укажите ваш браузер и его версию [например, Firefox 64.0 (64-бит)] **Google Chrome Version 109.0.5414.119 (Official Build) (64-bit)**
2. Укажите версию вашего Dollchan [например, v18.12.29.0.e7e44f7.es6] **v22.12.5.0.9d0f7f0.es6**
3. Чем вы пользуетесь: хроморасширением или юзерскриптом? **Violentmonkey 2.13.9**
4. Если вы используете юзерскрипт, укажите ваш скриптменежер [например, Violentmonkey 2.10.0] **Violentmonkey 2.13.9**

**Шаги для воспроизведения поведения ошибки**
1. Зайти на борду с включенной капчей, например: https://endchan.gg/polru/res/50978.html.
2. Открыть форму постинга, написать уникальный пост (на борде включен r9k, который не пропускает одинаковые посты).
3. Ввести неправильную капчу.
4. Нажать `Reply`.

**Скриншоты**
Если возможно, добавьте скриншоты, чтобы объяснить вашу проблему. Это улучшит понимание и ускорит исправление ошибки.

**Comment by SthephanShinkufag** [comment]
Fixed: https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/commit/0fbfb91816d2f00f14fb300aed44255d97412aac
