### ISSUE TITLE
[Bug] Куклоскрипт не блокирует посты с пустым именем / именем нулевой длины

### ISSUE THREAD

**Issue by Shaber05** [SthephanShinkufag/Dollchan-Extension-Tools#1471]
**Опишите вашу ошибку**
1. Куклоскрипт не скрывает неймфага с пустым именем. Неймфаг пишет в поле имени 1 пробел, rf.dobrochan.net создаёт пост с отсутствующим именем юзера.
2. Ожидал скрытия всех постов с пустым именем.
3. Ошибка происходит на конкретном имиджборде rf.dobrochan.net
4. При попытке создать правило #name() пишет Error: missing argument of spell: #name (row 1, column 6). Правила типа #name( ) c одним пробелом или символами аналогичными пробелу или пустому месту - не приносят ожидаемого результата. Пытался использовать вложение #name(#tlen(0)) для блокировки постов с именем нулевой длины, но также получил ошибку.

**Описание браузера и Dollchan**
Firefox 114.0 (64-бит)
Dollchan v22.12.5.0.51864e1.es6
Пользуюсь юзерскриптом
Скриптменежер Tampermonkey 4.18.1

**Шаги для воспроизведения поведения ошибки**
1. перейти на rf.dobrochan.net
2. создать в настройках куклоскрипта правило #name()
3. Нажать Apply
4. Появляется Error: missing argument of spell: #name (row 1, column 6)

**Comment by SthephanShinkufag** [comment]
Куклоскрипт обрезает пробелы в имени.
Теперь `#name` или `#name()` скрывают пост, если в нём есть имя, а `!#name` или `!#name()` - если нет имени, или оно состоит лишь из пробелов.
