### ISSUE TITLE
[Bug] Сбивается счётчик постов всех тредов в избранном при постинге в тред / получении новых постов

### ISSUE THREAD

**Issue by PukPukov** [SthephanShinkufag/Dollchan-Extension-Tools#1477]
**Описание браузера и Dollchan**
1. Хром 118.0.5993.71 (Официальная сборка), (64 бит)
2. Dollchan [v23.9.19.0.5f0b6f7.es6]
3. Юзерскриптом
4. Violentmonkey v2.15.0
5. Сосач

**Шаги для воспроизведения поведения ошибки**
1. Зайти в тред
2. Запостить чё-нибудь
3. Посмотреть в избранное
4. Все счётчики постов у всех тредов сбиты, там показывается количество постов текущего треда

**Скриншоты**
![2023-10-16_07-01-14](https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/assets/90708073/9b536383-3b79-4427-b022-4090d28e6d5e)

**Comment by SthephanShinkufag** [comment]
Баг воспроизвдоится, да. Надо будет глянуть.

**Comment by SthephanShinkufag** [comment]
А вот теперь опять не могу воспроизвести.

**Comment by PukPukov** [comment]
У меня на самой новой версии (v24.9.16.0.7bdd555) всё ещё воспроизводится, причём я сменил браузер на файрфокс и виолент манки обновился до 2.26 за это время и оно никуда не делось. Устанавливал я с этой ссылки: https://raw.github.com/SthephanShinkufag/Dollchan-Extension-Tools/master/Dollchan_Extension_Tools.user.js
