### ISSUE TITLE
[Enhancement] Возможность скачивать файлы с сохранением имени отдельной кнопкой

### ISSUE THREAD

**Issue by ancap-kun** [SthephanShinkufag/Dollchan-Extension-Tools#1478]
На оригинальном фронте сосача есть кнопка скачки возле кнопки поиска у файлов, если её нажать, файл тут же начнёт скачиваться, с сохранением названия. Хотелось бы и в кукле иметь это. 
![2023-10-16_08-05-48](https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/assets/90708073/9698f678-9aa2-4e68-941c-96868645b598) ![2023-10-16_08-05-15](https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/assets/90708073/cfd607df-e65e-4c75-b287-12e9e279fabc)

**Comment by SthephanShinkufag** [comment]
На кнопке с лупой есть меню по наведению, там вы можете выбрать, с каким именем скачивать картинку. Идея была в том, чтобы не плодить лишние кнопки.
