### ISSUE TITLE
[Enhancement] Save flags

### ISSUE THREAD

**Issue by aleksejrs** [SthephanShinkufag/Dollchan-Extension-Tools#1482]
4chan posts have small pictures called flags after the poster's name.

`<span title="flag description" class="bfl bfl-[identifier]"></span>` makes a segment of the image containing all the flags of the board appear after "Anonymous".

They are currently not being saved when Downloading a thread.

**Comment by SthephanShinkufag** [comment]
Fixed now.

**Comment by aleksejrs** [comment]
Works for /int/, but /mlp/ uses a different image specified in https://s.4cdn.org/image/flags/mlp/flags.2.css — https://s.4cdn.org/image/flags/mlp/flags.png?2
