### ISSUE TITLE
[Enhancement] Антикаптча 

### ISSUE THREAD

**Issue by ancap-kun** [SthephanShinkufag/Dollchan-Extension-Tools#1483]
Почему бы не добавить авторешалку каптч через произвольный сторонний сервис?

**Comment by SthephanShinkufag** [comment]
Любой админ будет бороться с обходом капчи, тем более массовым.
Вы хотите, чтобы куклоскрипт на сосаче запретили, или что?

**Comment by ancap-kun** [comment]
На том же сосаче в /s/ есть официальные треды дашчана и айчана, в обоих есть антикаптча, и никто не трёт их.
