### ISSUE TITLE
[Bug] Существующие треды удаляются при нажатии кнопки "очистить" если к ним нет доступа из-за отсутствующего интернета

### ISSUE THREAD

**Issue by PukPukov** [SthephanShinkufag/Dollchan-Extension-Tools#1488]
Лучше бы удалялись только те что с явным 404.

**Comment by SthephanShinkufag** [comment]
Исправил. Теперь при нажатии на кнопку удаляются только 404 треды. А при ошибке подключения ничего не удаляется и выскакивает предупреждающий попап.

P.S. Классный номер коммита :D

**Comment by PukPukov** [comment]
Наверное, эту иссую с таким красивым номером можно закрыть.
