### ISSUE TITLE
Нету кнопки скачивания треда

### ISSUE THREAD

**Issue by ASNDROID** [SthephanShinkufag/Dollchan-Extension-Tools#1489]
**Опишите вашу ошибку**
Не нашел кнопки скачивания всего треда в кукле, ее просто нет. Я скачивал и юзерскрипт и хроморасширение и все равно нету кнопки. 

**Описание браузера и Dollchan**
Google Chrome 120.0.6099.225 (64 бит); Firefox 121.0.1 (64-бит)
Dollchan v23.9.19.0.d7adc77
Юзерскрипт
Tampermonkey 5.0.1

**Скриншоты**
![image](https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/assets/132222807/e176c4d7-6a66-4f86-a737-c913b67d5e51)

**Comment by SthephanShinkufag** [comment]
Судя по всему, вы находитесь не в треде, а на доске. Зайдите в тред, кнопка появится.

**Comment by ASNDROID** [comment]
Разобрался. Спасибо.
