### ISSUE TITLE
[Enhancement] Копирование с форматированием

### ISSUE THREAD

**Issue by PukPukov** [SthephanShinkufag/Dollchan-Extension-Tools#1495]
Чтобы текст "**залупа**" копировался как "[B]залупа[/B]".

**Comment by PukPukov** [comment]
Очень удобно было бы.

**Comment by SthephanShinkufag** [comment]
Повторный issue #1005

**Comment by PukPukov** [comment]
Ну не совсем, там про цитирование, а у меня про копирование. Хотя можно добавить там пункт про копирование.
