### ISSUE TITLE
[Bug] [2ch.hk] Новая капча на 2ch.hk

### ISSUE THREAD

**Issue by theanonym** [SthephanShinkufag/Dollchan-Extension-Tools#1498]
Появилась новая капча, невозможно отправить пост.

**Comment by SthephanShinkufag** [comment]
У меня 2ch.hk не открывается. Он жив ещё?

**Comment by xobgoblin** [comment]
К сожалению, жив. Тоже прошу о фиксе.

**Comment by SthephanShinkufag** [comment]
Видимо, он у меня заблокирован провайдером. С нидерландского прокси тоже не заходит, странно.

**Comment by xobgoblin** [comment]
Могу прислать сохраненную страницу с открытым окном реплая. Уж не знаю, поможет ли это.

**Comment by RosinSmoke** [comment]
Через 2ch.life открывай

**Comment by apan65** [comment]
> Видимо, он у меня заблокирован провайдером. С нидерландского прокси тоже не заходит, странно.

Скорее обезьянья кодла заблочила доступ с прояксяков и впнов.

**Comment by Rolfeg** [comment]
`_initCaptcha() {
      if (aib.makaba && !aib.isArchived) {
              loadCaptchaFn();
      } else {
          const capEl =
              $q('input[type="text"][name*="aptcha"], *[id*="captcha"], *[class*="captcha"]', this.form);
          if (!capEl) {
              this.cap = null;
              return;
          }
          this.cap = new Captcha(capEl, this.tNum);
          const updCapFn = () => {
              this.cap.addCaptcha();
              this.cap.updateOutdated();
          };
          this.txta.addEventListener('focus', updCapFn);
          if (this.files) {
              this.files.onchange = updCapFn;
          }
          this.form.addEventListener('click', () => this.cap.addCaptcha(), true);
      }
  }`
  Временный фикс из /s

**Comment by Rolfeg** [comment]
Временный фикс из /s - слегка подправить initCaptcha под макабу. Вроде не задевает другие доски.
https://pastebin.com/HPbDngNS

**Comment by imasuridondai** [comment]
1. "Пофикшенный" скрипт глючит под Greasemonkey - вместо содержимого страницы отображатеся только фон, или вообще белый экран. С Violentmonkey работает нормально
2. Даже с Violentmonkey ломается 2channel.moe, симптомы те же, что и выше

**Comment by Rolfeg** [comment]
Есть второй фикс для формы постинга, попробуйте с ним. С tampermonkey работает и без него.
https://pastebin.com/dJW0cDgH

**Comment by imasuridondai** [comment]
Бесполезно. Всё ломает loadCaptchaFn в _initCaptcha первого фикса, без вызова loadCaptchaFn страницы (и на 2channel.moe, и с Greasemonkey) отображаются нормально, но зато капча не показывается

**Comment by SthephanShinkufag** [comment]
Исправил капчу, сделал её более компактной.
