### ISSUE TITLE
[Реквест] Перелистывание картинок стрелочками

### ISSUE THREAD

**Issue by PekaGucci** [SthephanShinkufag/Dollchan-Extension-Tools#586]
При открытии картинки - по бокам есть стрелочки, при клике на которые картинки листаются, так вот, почему бы не сделать листание этих картинок стрелочками клавиатуры (←, →), а не только кликами мышки?

Пробовал это делать с включенной навигацией с клавиатуры - не работает.

**Comment by Mayurifag** [comment]
Cделайте, пожалуйста, опцию убрать эти стрелочки по бокам каким-нибудь флагом в разделе «Картинки», на навигацию с клавиатуры наплевать, устроит даже костыль со скрытием, лишь бы искаропки это было.
