### ISSUE TITLE
Сохранение всех картинок из треда (Webm)

### ISSUE THREAD

**Issue by dfgjdfsa** [SthephanShinkufag/Dollchan-Extension-Tools#623]
Не работает с вебмками.

2ch.hk-b-t68926748-images.tar Этот файл отсутствует на сервере.
blob:http%3A//2ch.hk/5080f1a1-09e0-4377-8e2d-f37e011db9b6

И архив не сохраняет.

**Comment by kukulza** [comment]
Выпадает в ошибку на странице **"Нехватает памяти"** при поптыке скакачать все webm на странице их около 500, ошибка на ~250. Может разбивку какаю сделать по 100 шт за раз?

**Comment by SthephanShinkufag** [comment]
Предлагаю запретить предзагрузку webm вообще. пусть будет только для картинок. Надо иметь отсутствие здравого смысла, чтобы запускать предзагрузку в вебм-тредах. это же гигабайты данных.
Либо сделать опцию "Предзагрузка для webm"

**Comment by UserNaem** [comment]
Да, это воспроиозводится с любым очень тяжелым тредом, расход памяти переваливает за несколько ГБ, и обычно не получается сохранить.

Но все равно, ящитаю, "проверки на здравый смысл" всегда должны быть отключаемы, на те единичные случаи, когда они только мешают.

**Comment by SthephanShinkufag** [comment]
Количество вебмок в каком-нибудь цуиь- или анимублядском- треде. Скажем, 2 вебмки на пост в треде с 400постами это 800 вебмок, и умножьте на средний вес - 6Мб.
Это 5гб данных. И все это должно храниться в памяти... Тут не кукла виновата, а сами треды и их посетители. Есть фича, она работает. Но она не предполагает таких тяжелых условий.

**Comment by SthephanShinkufag** [comment]
Опция `"Картинки"` >`"Предварительно загружать картинки*"` теперь имеет три варианта:
```
[Откл.]
[Все]
[Без WebM]
```

Вариант [Без WebM] применяет предварительную загрузку ко всем, кроме .webm, .mp4 и .ogv
