### ISSUE TITLE
@include *

### ISSUE THREAD

**Issue by dluciv** [SthephanShinkufag/Dollchan-Extension-Tools#641]
Может быть туплю, тогда сорри и прошу пояснить.

Не даёт покоя `@include *`. У GreaseMonkey она лишает возможности ограичить скрипт несколькими чанами. Пользовательский инклюд добавляется к авторским, а пользовательский `@exclude *` пользовательским инклюдом не исправить. На GreaseMonkey уже [баг накатал](https://github.com/greasemonkey/greasemonkey/issues/1946), может они мне сами что пояснят... А если нет, то может быть стоит сделать инклюды на несколько популярных чанов, а остальные пользователь сам добавит?..

У Scriptish другая политика пользовательских инклюдов, они целиком отменяют авторские, замещая их собой, и всё ок.

**Comment by Remu-rin** [comment]
> У GreaseMonkey она лишает возможности ограичить скрипт несколькими чанами.

Слава Violentmonkey, недавно выяснил, что она этой проблемы не имеет. Спокойно может переопределить правила юзерскрипта.
Снимаем галку keep original у include и прописываем свои правила в match (или в include, но они хуже в плане безопасности вайлдкардов в домене).
![image](https://user-images.githubusercontent.com/28995228/34594777-efabf454-f1f4-11e7-8a75-2b48ebfb01f7.png)

**Comment by dluciv** [comment]
Ну сейчас, после того, как Firefox стал не таким, как прежде, Tampermonkey стал мейнстримом. Он вроде тоже позволяет.
