### ISSUE TITLE
А поддержку архивача не планируете?

### ISSUE THREAD

**Issue by YellowSM** [SthephanShinkufag/Dollchan-Extension-Tools#713]
Собсно, там только вьювер картинок нужен, превью для вебм/ютуб, ну и возможность сохранить тред, картинки.
Может, еще избранное.

**Comment by YellowSM** [comment]
В копилку реквестов: хорошо бы чтобы плеер для ютуб ссылок был развернут (сейчас там нужно кликать, чтобы его открыть)

**Comment by YellowSM** [comment]
В копилку: стили менюшек куклы

![11 07 15 18-41-20](https://cloud.githubusercontent.com/assets/5058386/8634311/e0fbd6a0-27fc-11e5-87b0-1e30e1130337.png)

**Comment by SthephanShinkufag** [comment]
Куклоскрипт на архиваче работает отлично с последним коммитом:

f557447e65cea2dd240f6f906bda431b476e8a0f

> *arhivach.org* &mdash; Исправлено раскрытие картинок, определение удалённых постов, дублирование (OP) в ссылках.
