### ISSUE TITLE
Фоновое обновление тредов

### ISSUE THREAD

**Issue by YellowSM** [SthephanShinkufag/Dollchan-Extension-Tools#728]
(Лиса+гризманки)
Че-то не пойму почему тред перестает обновляться в фоне?
Открыта вкладка с тредом в фоне. Серфишь в других вкладках (или сворачиваешь лису). Сначала  посты обновляет - счетчик на вкладке тикает, но потом в какой-то момент останавливается. Стоит развернуть вкладку, сразу догружается пол-треда.
Чому такая беда?

**Comment by YellowSM** [comment]
С введением отображения таймера до обновления, заметил, что при переходе на вкладку, после некоторой работы вне браузера, счетчик на секунду показывает значения значительно большие, чем время обновления.
Например, у меня стоит 30 секунд, при переключении замечал значения 100+ сек, 80+ сек.
Может, проблема где-то тут?

Во, успел заскринить:
![timer-bug](https://cloud.githubusercontent.com/assets/5058386/5787172/1b12c44c-9e06-11e4-849d-e9e04718ce58.png)

**Comment by Y0ba** [comment]
Там таймер может увеличивать значение времени обновления (если нет новых постов с последнего обновления) вплоть до 120 секунд. Если появится новый пост или ты переключишься на вкладку, то таймер сбросится на заданное значение. Сделано это для уменьшения нагрузки на сервер в неактивных тредах.

**Comment by Y0ba** [comment]
Если у тебя лиса, проблема могла быть в том, что там иногда `currentXHR.abort` вылетал с ошибкой и выключал автообновление. Попробуй последнюю версию.

**Comment by YellowSM** [comment]
Ok, понаблюдаю.
А какой алгоритм увеличения времени обновления?

Я, кстати, наблюдал и отрицательные значения у счетчика. Это не критично?

**Comment by Y0ba** [comment]
> А какой алгоритм увеличения времени обновления?

Например у тебя стоит время обновления 10 секунд. Если новых постов нет и пользователь не смотрит на тред, то каждое обновление будет увеличиваться на 10 секунд пока не дойтёт до 120.

> Я, кстати, наблюдал и отрицательные значения у счетчика. Это не критично?

В последней версии тоже исправлено.

**Comment by YellowSM** [comment]
Для любых значений увеличение на 10 сек или увеличение на значение счетчика?

**Comment by Y0ba** [comment]
На начальное значение, да. Поставишь 20 - будет увеличиваться на 20. Сам алгоритм я писал от балды, спиздив идею с форчановского аддона. Если есть идеи по-лучше - валяй.

**Comment by YellowSM** [comment]
Да фик знает, вроде нормально. Может, конечно какую-то прогрессивную шкалу увеличения - для 10 секунд увеличение на 10 нормально, а для 60 сразу до 2х минут. Впрочем, не так важно.

У меня тут еще вопрос. Насколько я понял, при переключении на неактивную вкладку происходит принудительное обновление треда. Может, не стоит так делать, если текущее значение таймера меньше заданного в конфиге? А то так можно спамить - тупо по вкладкам переключаться. Например, если переключаешься, а там осталось 20 сек до обновления (при заданных 30), то пусть себе дальше тикает, а если таймер был увеличен скриптом, то форсировать обновление.

**Comment by desudesutalk** [comment]
Мне нравится как это реализовано на окточане (а туда, видимо, утащено с форчана): время обновления изначально равно 5 секундам. Если новых постов при обновлении не обнаружено таймер увеличивается в два раза. И так пока не станет равным 600 секундам.

Таймер сбрасывается обратно на 5 секунд если сделать ручное обновление треда или если при обновлении появился новый пост.

При этом на форчане ещё есть такая фишка - если переключиться обратно на тред, то таймер выставляется на 10 секунд (независимо от того сколько было до переключения, хоть одна. Получается что если быстро переключаться между двумя вкладками они никогда не будут обновляться).

Мне кажется это самый лучший вариант. Реализации таймера.

**ОДНАКО!** Обязательно должна быть опция которая такое поведение отключает и делает обновление железно раз в указанное количество секунд. (охотники за удалёнными постами любят держать кучу вкладок с автоапдейтом в пять секунд, думаю они расстроятся если их лишить такого *"спорта"*)

**Comment by Y0ba** [comment]
> При этом на форчане ещё есть такая фишка - если переключиться обратно на тред, то таймер выставляется на 10 секунд

Добавил. 8ca652ac16c164fbe4ad636cb441876a53365c5d
