### ISSUE TITLE
Панель видео

### ISSUE THREAD

**Issue by VisualKei** [SthephanShinkufag/Dollchan-Extension-Tools#732]
Воспользовался тут, и обнаружил, что плюс рядом с плеером (для увеличения его размера) поломал симметричность полей панели.

Алсо, по плюсу похоже вообще нужно делать динамическую перерисовку списка видео.
Во-первых, чтобы его ширина (т.е. фон и разбивка длинных названий) реагировала на расширение/сужение панели после плюса.
Во-вторых, если список достаточно длинный, то после увеличения плеера появляется вертикальная полоса прокрутки у всей панели, а плюс съезжает на новую строку. После обратного уменьшения эта полоса может сохраняться (если у списка была своя полоса прокрутки?).
Стоит сделать и добавление в список новых видео из подгруженных постов без переоткрытия панели - это явно было бы удобно. Наверное, кумулятивное по переходу на проигрывание следующего видео, чтобы текущему не мешать перерисовкой панели.

Тестовые треды: [много видео](http://iichan.hk/a/res/980157.html), [мало видео](http://iichan.hk/a/res/1003495.html).

**Comment by SthephanShinkufag** [comment]
Теперь кнопка разворота не нарушает симметрию, и не съезжает вниз. А список ссылок адаптируется по ширине.

**Comment by SthephanShinkufag** [comment]
Теперь список в окне `"Видео"` обновляется с появлением новых постов, и загрузке названий.
