### ISSUE TITLE
Капча во встроенной форме (макаба)

### ISSUE THREAD

**Issue by YellowSM** [SthephanShinkufag/Dollchan-Extension-Tools#734]
После загрузки треда если постить через встроенную форму (та, которая на странице внизу), капча не грузится. Капча начинает грузиться только после использования кнопки ответа на постах.

В голой макабе (без куклы) капча грузится сразу.

**Comment by SthephanShinkufag** [comment]
Вы должны кликнуть в поле ответа, либо на выбор картинки.
Тогда капча появится. Это сделано специально, и уже достаточно давно.
В быстрых ответах она появляется сразу.

**Comment by SthephanShinkufag** [comment]
Протухание капчи вещь достаточно изменчивая, и может меняться по желанию левой пятки администрации. Подстраиваться еще и под это - nein...
