### ISSUE TITLE
Пикчи на форчане

### ISSUE THREAD

**Issue by mr-rak** [SthephanShinkufag/Dollchan-Extension-Tools#735]
Есть один баг и он меня уже утомил. Некоторые пикчи, неверно растягиваются по ширине, это не зависит от браузера или разрешения окна/пикчи (хотя на мелких пикчах такого не видел) часто проявляется в десктоптредах  /g, на тред около десятка таких пикчь, зависимости между ними я не нашел, проявляется даже если изображение вписывается по ширине окна. Наблюдаю давно, фикс плиз.
![screenshot](https://cloud.githubusercontent.com/assets/6695875/5237401/0a566bd2-788a-11e4-99bf-c9f162fa31ae.png)

**Comment by SthephanShinkufag** [comment]
Если бы можно было самому увидеть такой тред...

**Comment by mr-rak** [comment]
Обычно в десктоп тредах, вот пост с такой пикчей http://boards.4chan.org/g/thread/45979421/desktop-thread#p45981247
