### ISSUE TITLE
Оповещение об ошибке миганием фавикона

### ISSUE THREAD

**Issue by VisualKei** [SthephanShinkufag/Dollchan-Extension-Tools#736]
Сабж не отменяется даже когда ошибки больше нет, пока не переключишься на такую вкладку или там не появятся новые посты, и мигание не сменится на соответствующее.

**Comment by SthephanShinkufag** [comment]
Вроде бы все работает..

**Comment by SthephanShinkufag** [comment]
Можно как-то добиться данного бага?
