### ISSUE TITLE
Ссылки на удалённые сообщения в отключенном состоянии, даже если удалённое сообщение видно

### ISSUE THREAD

**Issue by Klaster1** [SthephanShinkufag/Dollchan-Extension-Tools#743]
![clipboard01](https://cloud.githubusercontent.com/assets/2667662/5514492/b8ea8b24-886b-11e4-9e05-266cd76d118e.png)
Собственно, на скриншоте видно. В данной ситуации ссылка вполне может работать.

**Comment by SthephanShinkufag** [comment]
Сделал пометку `[del]` возле ссылки на удаленные посты.
