### ISSUE TITLE
KC /int/: куклоскрипт отваливается при входе в тред

### ISSUE THREAD

**Issue by deterenkelt** [SthephanShinkufag/Dollchan-Extension-Tools#748]
Если смотреть доску целиком, кнопки и иконка в уголке на месте, а при входе в тред ни кнопок, ни иконки нет.

В JS консоли ошибка 

    [15:38:56.487] NS_ERROR_DOM_QUOTA_REACHED: Persistent storage maximum size reached @ chrome://scriptish/content/scriptish.js -> file:///home/dtr/…@httpwwwfreedollchanorgscripts.user.js:4673

Есть тред, который был открыт два дня назад, вот в нём всё по-прежнему хорошо даже после F5, там есть такая же ошибка, но она ссылается уже на другую строчку
  
     [15:49:26.964] NS_ERROR_DOM_QUOTA_REACHED: Persistent storage maximum size reached @ chrome://scriptish/content/scriptish.js -> file:///home/dtr/…@httpwwwfreedollchanorgscripts.user.js:1200

В /b/ кстати, тоже не работает.

Бледномун 24.6.1, скрепыш 0.1.11, кукла 14.12.31.0.

**Comment by deterenkelt** [comment]
Хм, не понимаю, почему, но если в той вкладке, где у меня обычно открыт /int/ перейти в /b/, а потом обратно в /int/ (через ссылки в шапке доски) то кнопки на месте. Если открыть /int/ из адресбара, то он в чём мать родила, без скрипта. При этом скриптиш показывает 1 активный скрипт и это кукла.

**Comment by SthephanShinkufag** [comment]
Palemoon вместо браузера, Scriptish вместо юзерскрипт-аддона. Что я могу сказать..
Меня настораживает, что у вас имеется ограничение на размер хранилища. Вы не localStorage используете часом?
Запостите `Настройка` - `Инфо` - `Отладка` - содержимое объекта `"nav": {}`

**Comment by SthephanShinkufag** [comment]
По-умолчанию ограничение на localStorage равно 5Мб.
Скрипт пытается туда записать инфу о постах, и происходит сбой.

**Comment by SthephanShinkufag** [comment]
Вообще, у гризманки-юзеров localStorage использоваться не должен. Видимо, ваш браузер со скриптишем настолько суровы...

**Comment by deterenkelt** [comment]
> Что я могу сказать.
Что надо найти источник проблемы же.
> Меня настораживает, что у вас имеется ограничение на размер хранилища.
Это не dom.storage.default_quota? У меня стоит 5120.
> Вы не localStorage используете часом?
А как я могу уэто узнать?
> Запостите Настройка - Инфо - Отладка - содержимое объекта "nav": {}
Во-первых, у меня англоязычный интерфейс. Во-вторых, смысл, наверно, уже пропал, так как когда очистка кеша не помогла, я перезапустил браузер и всё стало хорошо. Но то, что такие шняги будут случаться, меня конечно, не радует,  и хотелось бы разобраться. Раньше у меня FF месяцами висел в памяти и ничего.

**Comment by SthephanShinkufag** [comment]
> у меня англоязычный интерфейс

`Settings` > `Info` > `Debug` > `"nav" `

Мне не нужен "смысл". Мне нужно узнать, использует ли у вас скрипт localStorage, и все.
С вероятностью 95%, это так. И с вероятностью в 95% я могу заявить, что задав в `dom.storage.default_quota` число побольше, у вас в дальнейшем будет все хорошо.

> Раньше у меня FF месяцами висел в памяти и ничего.

Это ваше ничего накапливалось-накапливалось, вот и накопилось 5Мб данных о видимости постов, скрытых тредах, избранном, и прочее.

Сообщите содержимое отладки, и можно быть до конца уверенным.

**Comment by SthephanShinkufag** [comment]
Раньше скрипт хранил все в GM-хранилище, егда вы пользовали Файерфокс, там ограничений нема.

**Comment by SthephanShinkufag** [comment]
Может быть, скрипт не видит Palemoon как файерфокс. Если это исправить, то проблема лимита вообще не будет вас волновать.

**Comment by deterenkelt** [comment]
> Settings > Info > Debug > "nav"

А, в скрипте, я тогда подумал, что в браузере, и надо посмотреть что-то из DOM на тех страницах. http://pastie.org/pastes/9819488/text
У скриптиша есть настройка ‘Cache user scripts’, она может как-то на это влиять?

> что задав в dom.storage.default_quota число побольше, у вас в дальнейшем будет все хорошо.

М, и сколько будет адекватно? 10, 15, 20, 50?

> Это ваше ничего накапливалось-накапливалось, вот и накопилось 5Мб данных о видимости постов, скрытых тредах, избранном, и прочее.

Да нет, это раньше FF работал, сейчас мне приходится браузер рестартовать чаще (не из-за него самого), судя по аптайму, конкретно этот инстанс не мог проработать больше двух недель.

**Comment by SthephanShinkufag** [comment]
Ой вей. У вас все-таки испольтзуется GM-хранилище, как и должно быть.
Скрипт конечно использует localStorage для синхронизации между вкладками, но эта информация сразу же удаляется.
Хм.
Тогда, может, у вас как-то переполняется sessionStorage. Скрипт его активно использует.
Кажись, до меня дошло..
У вас постоянно открыты вкладки с тредами, и вы их никогда не закрываете, а ПК вы просто отправляете в спящий режим?
Теоретически возможно, что при длительной сессии с большим потоком данных (много больших тредов с множеством постов) будет происходить перполнение.
В общем, выставьте ограничение побольше, добавьте нолик.
dom.storage.default_quota = 51200, например.

**Comment by SthephanShinkufag** [comment]
Аще я бы хотел, чтобы вы показали, как у вас выглядят строки `4673` и `1200` в коде скрипта.
А то у нас скрипты разные...

**Comment by deterenkelt** [comment]
> У вас постоянно открыты вкладки с тредами, и вы их никогда не закрываете,

Ну, пока они не умирают. Обычно их не больше трёх-пяти, несчитая самого /int/.

> а ПК вы просто отправляете в спящий режим, не закрывая браузер?

А ПК просто работает :D Его обязанность — держать домашнюю локалку.

> В общем, выставьте ограничение побольше, добавьте нолик.

М-мкей.

> Аще я бы хотел, чтобы вы показали, как у вас выглядят строки `#4673` и `#1200` в коде скрипта.

4673:

    sesStorage['de-spells-' + brd + TNum] = JSON.stringify([data[0], spells, reps, outreps]);

1200:

    	',' + lPost.num + ',' + lPost.count + ',' + sVis.join('');

**Comment by SthephanShinkufag** [comment]
```
sesStorage['de-hidden-' + brd + TNum] = (Cfg.hideBySpell ? spells.hash : '0') +
    ',' + lPost.num + ',' + lPost.count + ',' + sVis.join('');
...
sesStorage['de-spells-' + brd + TNum] = JSON.stringify([data[0], spells, reps, outreps]);
```

Ну, теперь все ясно. Большинство пользователей закрывают браузер, и сессия завершается.
На то, что кто-то будет всегда держать браузер открытым, рассчитано не было.
Закрывайте иногда браузер. Раз в неделю, хотя бы. И подобных казусов не будет.

**Comment by deterenkelt** [comment]
> Закрывайте иногда браузер. Раз в неделю, хотя бы.

[А это что, никак не почистить?](http://images.netbynet.ru/imgs/7a4cc83ce6e7ba2826f1ce7f2a7e4345.png)

**Comment by SthephanShinkufag** [comment]
sessionStorage можно очистить, закрыв сессию - т.е. закрыв барузер.
Сессия сохраняется по принципу одна-страница-одно-окно и ограничивается жизнью данного окна, то есть для каждого открытого окна создается новая сессия, которая прекращает свое существование при закрытии окна и не зависит от домена, открывшего ее.

Можно извратиться и выполнить строку на `js`

```js
sessionStorage.clear();
```

Но проще закрыть браузер, и открыть заново.

**Comment by deterenkelt** [comment]
Vimperator выдаёт [ошибку](http://images.netbynet.ru/img.php?6aa586275f99ae404296fc57e5e054f0.png) при попытке выполнить такой код. В чём может быть дело? sessionStorage он предлагает дополнить, с dom.* тоже ен фурычит…

**Comment by SthephanShinkufag** [comment]
`window.sessionStorage.clear();`

**Comment by deterenkelt** [comment]
Выдаёт похожую лабуду. Ладно, пойду дёргать за фартук девелопера на этот счёт.
