### ISSUE TITLE
webm corrupt

### ISSUE THREAD

**Issue by ganego** [SthephanShinkufag/Dollchan-Extension-Tools#749]
When uploading a certain webm I created the upload will stop with the message, that the webm is corrupt. Is there a way to disable this check, because it gets it simply wrong. Without dollchan uploading the video works and the video plays perfectly fine, so it is not corrupt.
Please give an option to disable this check.
Thank you.

**Comment by SthephanShinkufag** [comment]
Show me a sample of your webms that couldn't upload.

**Comment by SthephanShinkufag** [comment]
And a name of your imageboard.

**Comment by ganego** [comment]
Hey, all info here:
http://pastebin.com/ZggksKch
Thanks.

**Comment by SthephanShinkufag** [comment]
> THAT WEBM

<img src='http://rghost.ru/60296727/image.png' />

Man, I am disappointed...

Btw, iichan.hk does not support webms.
Mkay, I will look what I can do.

**Comment by ganego** [comment]
Sorry :/
But at least they cuddle at the end...
