### ISSUE TITLE
Прикрепленное изображение + iframe видео не помещаются в одном посте

### ISSUE THREAD

**Issue by faucct** [SthephanShinkufag/Dollchan-Extension-Tools#750]
Firefox 34.0, Ubuntu
![2015-01-11 19-01-14](https://cloud.githubusercontent.com/assets/5202503/5695295/587b86b4-99bc-11e4-936f-5edcadde59ea.png)

**Comment by SthephanShinkufag** [comment]
Исправлено в последних коммитах.
