### ISSUE TITLE
Постинг на макабе скролит тред вверх

### ISSUE THREAD

**Issue by YellowSM** [SthephanShinkufag/Dollchan-Extension-Tools#752]
После поста переходит к первому сообщению треда. Шоза?

**Comment by SthephanShinkufag** [comment]
Как добиться данного бага? Какой браузер, настройки?

**Comment by SthephanShinkufag** [comment]
Какая борда, из какой формы постите, наконец? Что за репорт...

**Comment by Y0ba** [comment]
Мб срабатывает родной постинг макабы и страница обновляется. У меня такое было, когда я чинил капчу и проверял работоспособность.

Алсо, какая капча: яндекс или гугл?

**Comment by SthephanShinkufag** [comment]
Все, увидел. Если постить из основной формы внизу на сосаче. Капча яндекс.

**Comment by YellowSM** [comment]
Макаба, /по/, постинг из встроенной форме (нижней) стабильно скролит вверх

**Comment by SthephanShinkufag** [comment]
с любой капчей бросает обновляет страницу. Если постить из быстрой формы, то все ок.
Хмм.

**Comment by SthephanShinkufag** [comment]
Пока не выяснил причину.

**Comment by SthephanShinkufag** [comment]
Все. Понял. Ядурак, как всегда.

**Comment by SthephanShinkufag** [comment]
ac02be2771f252cc0a3e81b4aaca318258a3de1c
