### ISSUE TITLE
Rarjpg detector error

### ISSUE THREAD

**Issue by SthephanShinkufag** [SthephanShinkufag/Dollchan-Extension-Tools#753]
Не работает детектор рарджпегов.
Запрещен доступ к ArrayBuffer, получаемом в `detectImgFile`:

> XrayWrapper denied access to property **data** (reason: value not Xrayable). See https://developer.mozilla.org/en-US/docs/Xray_vision for more information. Note that only the first denied property access from a given global object will be reported.

```js
new Blob([new Uint8Array(info.data).subarray(info.idx)], {'type': app})
```

Соответственно, `new Uint8Array` валится с ошибкой:

> Error: invalid arguments

Лиса 35.

**Comment by SthephanShinkufag** [comment]
> Components.utils.waiveXrays

```js
new Blob([new Uint8Array(
    (nav.Firefox ? Components.utils.waiveXrays(info) : info).data
).subarray(info.idx)], {'type': app})
```

> Components.utils is undefined

Wtf?

**Comment by SthephanShinkufag** [comment]
```js
console.log(Components)
```

```
nsXPCComponents {
    interfaces: nsXPCComponents_Interfaces,
    interfacesByID: nsXPCComponents_InterfacesByID,
    results: nsXPCComponents_Results
}
```

Нифига не понимаю. `utils` не доступен из юзерскрипта, только для расширений?

**Comment by desudesutalk** [comment]
Из скрипта недоступен вроде.

Вообще это разве не то же самое? https://github.com/greasemonkey/greasemonkey/issues/2034

**Comment by SthephanShinkufag** [comment]
o_0
Я и не знал.
