### ISSUE TITLE
Реквест: подсветка линков открытых превью-постов

### ISSUE THREAD

**Issue by YellowSM** [SthephanShinkufag/Dollchan-Extension-Tools#755]
Ну т.е. щас по `:hover` подсвечивается, а хорошо бы, чтобы линк подсвечивался постоянно, пока открыто связанное с ним превью. 

Просто когда ответов на пост много, просматриваешь их по очереди, из открытых превьюшек бывает дальше по дереву уходишь и, когда возвращаешься к исходному посту, - не понятно какой следующий ответ смотреть.
Ну или просто бывает превьюшка на весь экран растягивается с линка фокус ушел - и не понятно какой это ответ.

**Comment by YellowSM** [comment]
О, спасибо, то, что надо.
А можно их синенькими сделать? Ну в смысле оставить стиль от hover?

**Comment by YellowSM** [comment]
Ну или доттед обводку синенькую - так лучше выделяется имхо

**Comment by SthephanShinkufag** [comment]
На сосаче синенькие, на ычане красненькие. А у кого-то своя цсс и там серо-буро-малиновые с тенями и заливкой.
Вы уж как-нибудь сами.

**Comment by SthephanShinkufag** [comment]
Предвижу бесконечное нытье про ОНО НЕ СООТНОСИТСЯ С МОИМИ ЦЭЭСЭСИКАМИ.

**Comment by YellowSM** [comment]
Ладно, ладно, понял. Я прост думал, это в кукле.
Пропишу юзерстайл.
А так - спасибо

**Comment by SthephanShinkufag** [comment]
Да и имхо, штука полезная, сам часто теряюсь в ссылках, егда их в ответах много. Но егда оно бросается в глаза, становится *дискомфортно*.
Пусть уж будет различимым, но *малозаметным*.

**Comment by SthephanShinkufag** [comment]
Добавлен класс `de-link-parent`, ежели чего.
Он отвечает за выделение.
