### ISSUE TITLE
Шрифты с обновлением Tampermonkey.

### ISSUE THREAD

**Issue by ninefineninja** [SthephanShinkufag/Dollchan-Extension-Tools#756]
Chrome, 41.0.2272.16 beta-m, обновился Tampermonkey до v.3.9.202 и рендер шрифтов решил ебануться. Похоже на траблы с ClearType. Это баг или фича?
![vape 11](https://cloud.githubusercontent.com/assets/8942754/5881419/b32970f2-a30e-11e4-8832-d3088ba1102b.png)

**Comment by YellowSM** [comment]
В лисе были проблемы с рендером из-за виндового бага на относительно старых видюхах.
Лечилось отключением аппаратного ускорения.
Может и тут в этом направлении?

**Comment by ninefineninja** [comment]
@YellowSM потыкал аппаратное ускорение, ничего не изменилось. 
Алсо, Windows 8.1, Intel HD4000.
UPD: выключил DirectWrite, пофиксилось. Шо за хуйня?

**Comment by ninefineninja** [comment]
Короче, это опять хромодебилы что-то сделали, так как на других сайтах тоже бывает такая херня.

**Comment by SthephanShinkufag** [comment]
Так это случается только в скриптовых превью?

**Comment by Y0ba** [comment]
Во всём виновата анимация, хром её ускоряет отключая улучшалки текста, но включить их обратно забывает.

**Comment by SthephanShinkufag** [comment]
Пусть отключит в настройках скрипта `Общее` > `CSS3 анимация в скрипте` и посмотрит.

**Comment by ninefineninja** [comment]
@SthephanShinkufag , @Y0ba , отключил, все стало нормально. Может в багтрекер Chromium запилить issue?

**Comment by Y0ba** [comment]
@ninefineninja Этот баг то появляется, то исчезает с тех пор как анимации были добавлены в хром (потому они там до сих пор идут с префиксом). Уже была куча багов и всем похуй.

**Comment by SthephanShinkufag** [comment]
У гуглоидов вообще проблемы с CSS-взаимодействием. Это их слабое место.
Уже сколько костылей в куклоскрипте из-за них, все не перечислишь.

**Comment by SthephanShinkufag** [comment]
**Если в хроме тормоза при анимации превью / новых постов**

1. Зайдите в `chrome://flags`.

2. Нажмите `ctrl+F`.

3. Введите в поиск `#ignore-gpu-blacklist`.

4. Нажмите `Enable/Включить`.

https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/wiki/installation
