### ISSUE TITLE
2ch

### ISSUE THREAD

**Issue by stupidlamo** [SthephanShinkufag/Dollchan-Extension-Tools#758]
Некорректно работает на дваче.
Всплывающий пост при наведении на ссылку на пост - совсем по пизде пошел.
Навожу на ссылку - не открывается. Навожу на следующую - открывается предыдущий, на который наводил.
Потом убираю курсор - остается открытым и не пропадает.
Пропадает когда навожу на очередную ссылку на пост.

При выключении куклы всё нормально.
Настройки куклы сбрасывал, переустанавливал - всё тлен.

Ниже прикладываю отладку

{
	"version": "15.1.18.2",
	"location": "https://2ch.hk/b/res/84855772.html#84870665",
	"nav": {
		"ua": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.91 Safari/537.36",
		"Firefox": false,
		"Opera11": false,
		"Presto": 0,
		"WebKit": true,
		"Chrome": true,
		"Safari": false,
		"isGM": false,
		"isChromeStorage": true,
		"isScriptStorage": false,
		"isGlobal": true,
		"scriptInstall": "Chrome extension",
		"cssFix": "-webkit-",
		"Anim": true,
		"animName": "webkitAnimationName",
		"animEnd": "webkitAnimationEnd",
		"hasWorker": true,
		"canPlayMP3": true,
		"canPlayWebm": true
	},
	"cfg": {
		"timePattern": "dd+nn+yy+w+hh+ii+ss",
		"addVocaroo": 0,
		"updScript": 0,
		"spells": "[1422208927576,[[14,103,null]],false,false]",
		"addOPLink": 1,
		"webmVolume": 8
	},
	"sSpells": [
		"#wipe(samelines,samewords,longwords,numbers,whitespace)"
	],
	"oSpells": "[1422208927576,[[14,103]],false,false]",
	"perf": [
		"Init: 106ms",
		"Config loading: 1758ms",
		"Replace delform: 2ms",
		"Parse delform: 1223ms",
		"Parse postform: 80ms",
		"Init keybinds: 2ms",
		"Init page: 16ms",
		"Add panel: 5ms",
		"YouTube links: 15ms",
		"Sauce buttons: 134ms",
		"Reflinks map: 625ms",
		"Apply CSS: 36ms",
		"Apply spells: 2ms",
		"Всего: 4005ms"
	]
}

**Comment by SthephanShinkufag** [comment]
> 15.1.18.2

Ой вей. Я не опубликовал изменения три дня назад, что-ли..
Щас перезалью сегодняшнюю версию (15.1.18.3), попробуете.

**Comment by stupidlamo** [comment]
Вкратце - не помогло.

Что делал - удалил расширение из хрома, удалил все данные о работе в браузере, поставил снова.
При этом обращаю внимание, что на странице chrome://extensions/ рядом с куклой написано "15.1.18.3", когда же захожу в настройки куклы со страницы двача (нажимая на шестеренку внизу в углу) - во вкладке "Инфо" написано v15.1.18.1
Сделал сброс настроек куклы.
Обновил яву и флешплеер до последней версии.
Выключил AdBlock на дваче.
Выключил антивирус.

Отладка ниже (повторюсь - версия в "расширениях" - *.3 , я проверил)
{
	"version": "15.1.18.1",
	"location": "https://2ch.hk/b/",
	"nav": {
		"ua": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.93 Safari/537.36",
		"Firefox": false,
		"Opera11": false,
		"Presto": 0,
		"WebKit": true,
		"Chrome": true,
		"Safari": false,
		"isGM": false,
		"isChromeStorage": true,
		"isScriptStorage": false,
		"isGlobal": true,
		"scriptInstall": "Chrome extension",
		"cssFix": "-webkit-",
		"Anim": true,
		"animName": "webkitAnimationName",
		"animEnd": "webkitAnimationEnd",
		"hasWorker": true,
		"canPlayMP3": true,
		"canPlayWebm": true
	},
	"cfg": {
		"timePattern": "dd+nn+yy+w+hh+ii+ss",
		"addVocaroo": 0,
		"updScript": 0,
		"spells": "[1422375975238,[[14,111,null]],false,false]",
		"expandPanel": 1
	},
	"sSpells": [
		"#wipe(samelines,samewords,longwords,symbols,numbers,whitespace)"
	],
	"oSpells": "[1422375975238,[[14,111]],false,false]",
	"perf": [
		"Init: 58ms",
		"Config loading: 508ms",
		"Parse delform: 154ms",
		"Parse postform: 39ms",
		"Init keybinds: 3ms",
		"Add panel: 5ms",
		"YouTube links: 15ms",
		"Sauce buttons: 42ms",
		"Reflinks map: 20ms",
		"Apply CSS: 23ms",
		"Apply spells: 2ms",
		"Scroll page: 91ms",
		"Всего: 960ms"
	]
}

**Comment by SthephanShinkufag** [comment]
У меня все работает. По-всякому пробовал.
У вас появляется что-нибудь в консоли ошибок (`Ctrl+Shift+J`) при наведении на ссылки?

> 15.1.18.3
Это номер для гуглемагазина. Там с каждым новым билдом необходимо апать версию.
В самом скрипте версия остается прежней

**Comment by SthephanShinkufag** [comment]
Отключите опцию `Общее` > `CSS3 анимация в скрипте`.

проблема в анимации
#756

**Comment by stupidlamo** [comment]
И правда, снял галку - заработало.
Кстати говоря, когда вернул галку - всё работает нормально и анимация вернулась.

Спасибо.

**Comment by SthephanShinkufag** [comment]
**Если в хроме тормоза при анимации превью / новых постов**

1. Зайдите в `chrome://flags`.

2. Нажмите `ctrl+F`.

3. Введите в поиск `#ignore-gpu-blacklist`.

4. Нажмите `Enable/Включить`.

https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/wiki/installation
