### ISSUE TITLE
Поддержка каталога

### ISSUE THREAD

**Issue by Klaster1** [SthephanShinkufag/Dollchan-Extension-Tools#760]
Скрипт вообще никак не работает в каталогах (по крайней мере, на 2ch и Krautchan), хотя ничто не мешает реализовать тот же самый функционал, что и в корне доски.

Я бы сам сделал, но непонятно, откуда начать.

**Comment by Y0ba** [comment]
А какой именно функционал там нужен? Вот я смотрю https://2ch.hk/makaba/makaba.fcgi?task=catalog&board=b и не знаю, что и куда можно впихнуть из скрипта.

**Comment by Klaster1** [comment]
1. Проверка постов из меню favorites.
2. Фильтр NSFW не прячет тамбнейлы в каталоге.
3. Скрытие тредов.

**Comment by SthephanShinkufag** [comment]
Нереально.
