### ISSUE TITLE
Не подгружаются посты

### ISSUE THREAD

**Issue by linux111** [SthephanShinkufag/Dollchan-Extension-Tools#762]
Абу изменил макабу и теперь вместо страниц в /b/ безконечный скроллинг. Только на куклоскрипте в виде плагина для Chrome страницы не грузятся. Доходишь до конца страницы, на 1 секунду появляется надпись "Загрузка...", потом исчезает и ничего не происходит, новые посты не подгружаются. Посмотреть содержимое остальных вообще невозможно. Запускал в анонимном режиме без других плагинов - все равно не работает. Очень критичный баг.

**Comment by SthephanShinkufag** [comment]
Настройки **макабы** - Другое - Бесконечная прокрутка [Отключено]

**Comment by linux111** [comment]
Да, помогло. Но! Бесконечная прокуртка это лютый win, я хочу поддержку этого в куклоскрипте. Можно оставить реквест?

**Comment by SthephanShinkufag** [comment]
Мне не нравится. Я привык к списку досок. К тому же это ломает концепцию "глубины треда". В избранном ее не проверишь, если доски не отображаются.

**Comment by SthephanShinkufag** [comment]
Хотя идея, в принципе, неплохая. Можно будет реализовать, егда с остальными проблемами разберемся.
