### ISSUE TITLE
Подгрузка постов на сосаче.

### ISSUE THREAD

**Issue by KAMKillJoy** [SthephanShinkufag/Dollchan-Extension-Tools#763]
![2015-02-23 18 12 52](https://cloud.githubusercontent.com/assets/8235528/6330269/d90fffe8-bb87-11e4-980e-e12abe8b1a7f.png)
Бесконечно грузит и ничего.

**Comment by KAMKillJoy** [comment]
Ах, ну да. Хром Версия 40.0.2214.115 m.

**Comment by xDShot** [comment]
Тоже самое и у меня на Firefox 35.0.1, когда прикрепляю WebM или картинки к посту.

**Comment by KAMKillJoy** [comment]
> Ах да, еще "зависает" когда нажимаю на [получить новые посты]
Так я это и имею ввиду. Наверное я плохо описал :(

**Comment by KAMKillJoy** [comment]
![2015-02-28 00 30 36](https://cloud.githubusercontent.com/assets/8235528/6421564/40f1d17a-bee1-11e4-95b1-a670f93950ef.png)
Вот теперь что выдало.

**Comment by SthephanShinkufag** [comment]
Обновите скрипт.
https://raw.github.com/SthephanShinkufag/Dollchan-Extension-Tools/master/Dollchan_Extension_Tools.user.js

**Comment by KAMKillJoy** [comment]
Теперь при наведении на номер поста нет всплывашек. Ответы на пост не показывает, другими словами.

**Comment by SthephanShinkufag** [comment]
Где полная инфа? Настройки - Инфо - Отладка.
Что в консоли?

**Comment by xDShot** [comment]
Таки снёс Scriptish и поставил Greasemonkey. Проблема исчезла.

**Comment by KAMKillJoy** [comment]
Если навожу на номер поста на который отвечают- его показывает, а вот если на сам ответ, то нет. Подгрузка не зависает теперь.
{
	"version": "15.1.28.0",
	"location": "https://2ch.hk/mmo/res/4961102.html",
	"nav": {
		"Firefox": false,
		"Opera11": false,
		"Presto": 0,
		"WebKit": true,
		"Chrome": true,
		"Safari": false,
		"isGM": true,
		"isChromeStorage": false,
		"isScriptStorage": false,
		"isGlobal": true,
		"scriptInstall": "Monkey",
		"cssFix": "-webkit-",
		"Anim": true,
		"animName": "webkitAnimationName",
		"animEnd": "webkitAnimationEnd",
		"ua": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36",
		"hasWorker": true,
		"canPlayMP3": true,
		"canPlayWebm": true,
		"hasModernFormData": false
	},
	"cfg": {
		"timePattern": "w+dd+m+yyyy+hh+ii+ss",
		"spells": "[1413117051694,[[6,\"Omegа\",[\"mmo\",\"4842872\"]],[8,[0,[\"253\",\"253\"],[\"1201\",\"1201\",\"750\",\"750\"]],[\"mmo\",\"4686474\"]],[7,\"!khuiokDOKY\",[\"mmo\",\"4621639\"]],[6,\"Omeha\",[\"mmo\",\"4604562\"]],[8,[0,[27,27],[250,250,334,334]],[\"mmo\",false]],[7,\"!L708B4KK6A\",[\"mmo\",false]],[7,\"!uV3Mo4R2c2\",[\"mmo\",false]],[6,\"Omega\",[\"mmo\",false]],[14,103,null]],false,false]",
		"favIcoBlink": 1,
		"expandImgs": 1,
		"preLoadImgs": 1,
		"openImgs": 1,
		"markViewed": 1,
		"strikeHidd": 1,
		"addYouTube": 4,
		"addPostForm": 1,
		"scriptStyle": 2,
		"expandPanel": 1,
		"addImgs": 1,
		"hideBySpell": true,
		"expandPosts": 1,
		"linksOut": 500,
		"textaWidth": 1118,
		"textaHeight": 458,
		"scrUpdIntrv": 0,
		"removeFName": 1,
		"noBoardRule": 0,
		"warnSubjTrip": 1,
		"qReplyX": "left: 749px",
		"qReplyY": "top: 189px",
		"addVocaroo": 0
	},
	"sSpells": [
		"#name[mmo,4842872](Omegа) |",
		"#img[mmo,4686474](=253@1201x750) |",
		"#trip[mmo,4621639](!khuiokDOKY) |",
		"#name[mmo,4604562](Omeha) |",
		"#img[mmo](=27@250x334) |",
		"#trip[mmo](!L708B4KK6A) |",
		"#trip[mmo](!uV3Mo4R2c2) |",
		"#name[mmo](Omega) |",
		"#wipe(samelines,samewords,longwords,numbers,whitespace)"
	],
	"oSpells": "[1413117051694,[[8,[0,[27,27],[250,250,334,334]]],[7,\"!L708B4KK6A\"],[7,\"!uV3Mo4R2c2\"],[6,\"Omega\"],[14,103]],false,false]",
	"perf": [
		[
			"Init",
			6
		],
		[
			"Config loading",
			3
		],
		[
			"Parsing spells",
			1
		],
		[
			"Replace delform",
			0
		],
		[
			"Parse delform",
			24
		],
		[
			"Parse postform",
			34
		],
		[
			"Init keybinds",
			1
		],
		[
			"Init page",
			5
		],
		[
			"Add panel",
			2
		],
		[
			"Preload images",
			3
		],
		[
			"Audio links",
			0
		],
		[
			"Video links",
			1
		],
		[
			"Image links",
			0
		],
		[
			"Sauce buttons",
			6
		],
		[
			"Reflinks map",
			12
		],
		[
			"Apply CSS",
			20
		],
		[
			"Всего",
			118
		]
	]
}



![2015-02-28 12 29 49](https://cloud.githubusercontent.com/assets/8235528/6425660/b85b8328-bf45-11e4-99a8-126e05f457bf.png)

**Comment by KAMKillJoy** [comment]
![2015-02-28 13 02 01](https://cloud.githubusercontent.com/assets/8235528/6425740/0bb730b8-bf4a-11e4-81a6-87bb3c8b819c.png)
Теперь ещё и наверху выдаёт. Превью постов тоже не выдаёт теперь нигде. Скрипт своей жизнью живёт.

**Comment by KAMKillJoy** [comment]
Степан, ну ты куда пропадаешь? Я без куклы не могу, в абулиной макабе даже кнопок форматирования нет (ну или их искать надо в настройках). Всё неудобно и отвратительно. Даже непонятно- у одного у меня проблема или нет.

**Comment by SthephanShinkufag** [comment]
https://raw.github.com/SthephanShinkufag/Dollchan-Extension-Tools/master/Dollchan_Extension_Tools.user.js

!!!!

**Comment by KAMKillJoy** [comment]
Бесконечная подгрузка постов.
В консоли:
Tampermonkey started
swag.js:1210 Uncaught TypeError: Cannot read property 'thread' of undefined

Отладка:
{
	"version": "15.1.28.0",
	"location": "https://2ch.hk/mmo/res/4961102.html",
	"nav": {
		"ua": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36",
		"Firefox": false,
		"Opera11": false,
		"Presto": 0,
		"WebKit": true,
		"Chrome": true,
		"Safari": false,
		"isGM": true,
		"isChromeStorage": false,
		"isScriptStorage": false,
		"isGlobal": true,
		"scriptInstall": "Monkey",
		"cssFix": "-webkit-",
		"Anim": true,
		"animName": "webkitAnimationName",
		"animEnd": "webkitAnimationEnd",
		"hasWorker": true,
		"canPlayMP3": true,
		"canPlayWebm": true
	},
	"cfg": {
		"timePattern": "w+dd+m+yyyy+hh+ii+ss",
		"spells": "[1413117051694,[[6,\"Omegа\",[\"mmo\",\"4842872\"]],[8,[0,[\"253\",\"253\"],[\"1201\",\"1201\",\"750\",\"750\"]],[\"mmo\",\"4686474\"]],[7,\"!khuiokDOKY\",[\"mmo\",\"4621639\"]],[6,\"Omeha\",[\"mmo\",\"4604562\"]],[8,[0,[27,27],[250,250,334,334]],[\"mmo\",false]],[7,\"!L708B4KK6A\",[\"mmo\",false]],[7,\"!uV3Mo4R2c2\",[\"mmo\",false]],[6,\"Omega\",[\"mmo\",false]],[14,103,null]],false,false]",
		"favIcoBlink": 1,
		"expandImgs": 1,
		"preLoadImgs": 1,
		"openImgs": 1,
		"markViewed": 1,
		"strikeHidd": 1,
		"addYouTube": 4,
		"addPostForm": 1,
		"scriptStyle": 2,
		"expandPanel": 1,
		"addImgs": 1,
		"hideBySpell": true,
		"expandPosts": 1,
		"linksOut": 500,
		"textaWidth": 1118,
		"textaHeight": 458,
		"scrUpdIntrv": 0,
		"removeFName": 1,
		"noBoardRule": 0,
		"warnSubjTrip": 1,
		"qReplyX": "left: 749px",
		"qReplyY": "top: 189px",
		"addVocaroo": 0
	},
	"sSpells": [
		"#name[mmo,4842872](Omegа) |",
		"#img[mmo,4686474](=253@1201x750) |",
		"#trip[mmo,4621639](!khuiokDOKY) |",
		"#name[mmo,4604562](Omeha) |",
		"#img[mmo](=27@250x334) |",
		"#trip[mmo](!L708B4KK6A) |",
		"#trip[mmo](!uV3Mo4R2c2) |",
		"#name[mmo](Omega) |",
		"#wipe(samelines,samewords,longwords,numbers,whitespace)"
	],
	"oSpells": "[1413117051694,[[8,[0,[27,27],[250,250,334,334]]],[7,\"!L708B4KK6A\"],[7,\"!uV3Mo4R2c2\"],[6,\"Omega\"],[14,103]],false,false]",
	"perf": [
		[
			"Init",
			54
		],
		[
			"Config loading",
			14
		],
		[
			"Parsing spells",
			0
		],
		[
			"Replace delform",
			1
		],
		[
			"Parse delform",
			784
		],
		[
			"Parse postform",
			96
		],
		[
			"Init keybinds",
			1
		],
		[
			"Init page",
			13
		],
		[
			"Add panel",
			4
		],
		[
			"Preload images",
			3
		],
		[
			"Audio links",
			1
		],
		[
			"Video links",
			11
		],
		[
			"Image links",
			3
		],
		[
			"Sauce buttons",
			204
		],
		[
			"Reflinks map",
			442
		],
		[
			"Apply CSS",
			29
		],
		[
			"Scroll page",
			0
		],
		[
			"Apply spells",
			294
		],
		[
			"Всего",
			1955
		]
	]
}

**Comment by SthephanShinkufag** [comment]
У меня все работает.
Вы переустановили скрипт по ссылке?

**Comment by KAMKillJoy** [comment]
Я переустановил и обновил страницу. Я бы на Вашем месте давно бы решил, что это троллинг, но честное слово- не работает. Видео записать?

**Comment by SthephanShinkufag** [comment]
Да я вам верю же. Щас подумаю.

**Comment by SthephanShinkufag** [comment]
Прошлые ошибки с промисами были из-за экспериментов с ES6.
Сейчас я откатил все назад.

**Comment by SthephanShinkufag** [comment]
У вас стоят какие-нибудь дополнения кроме тамперманки?

**Comment by KAMKillJoy** [comment]
Я не знаю откуда выдрать человеческий текстовый список.
![2015-03-02 17 00 51](https://cloud.githubusercontent.com/assets/8235528/6442070/fc3901ec-c0fd-11e4-8a58-e8118fa7b403.png)
![2015-03-02 17 00 57](https://cloud.githubusercontent.com/assets/8235528/6442069/fc377c78-c0fd-11e4-972f-39d4f75b3c51.png)
![2015-03-02 17 01 06](https://cloud.githubusercontent.com/assets/8235528/6442071/fc3a37f6-c0fd-11e4-8eb7-643240f1503c.png)
![2015-03-02 17 01 13](https://cloud.githubusercontent.com/assets/8235528/6442068/fc3761b6-c0fd-11e4-949d-da4209c46c98.png)

**Comment by SthephanShinkufag** [comment]
о_0

**Comment by SthephanShinkufag** [comment]
Попробуйте ради прикола отключить временно все ваши аддоны.

**Comment by KAMKillJoy** [comment]
Что, много что ли? Отключил всё, кроме обезьяны, конечно. Никаких изменений. Бесканечная подгрузка, та же строчка в консоли.

**Comment by SthephanShinkufag** [comment]
Та строчка не относится к скрипту.
swag.js это макаба-костыли Абу.

**Comment by SthephanShinkufag** [comment]
А на ычане подгрузка работает?

**Comment by KAMKillJoy** [comment]
Но никто же не жалуется? Я в abu заходил, там нет ничего.
Uncaught TypeError: Cannot read property 'thread' of undefined, про сваг не пишет сейчас.
Сейчас проверю на ычане.

**Comment by KAMKillJoy** [comment]
Ошибку не выдаёт, но та же бесконечная загрузка.
![2015-03-02 17 35 55](https://cloud.githubusercontent.com/assets/8235528/6442688/a2c7c86e-c102-11e4-8e5e-460915f348c1.png)

**Comment by KAMKillJoy** [comment]
Кстати, на сосаче удалял куки, что бы настройки абушные слетели на стандарт, на случай, если там какие экзотические настройки конфликтуют.

**Comment by SthephanShinkufag** [comment]
А треды с нулевой раскрываются?

**Comment by KAMKillJoy** [comment]
А ещё я уже обращался с бесконечной подгрузкой. Там ошибка была с предварительной загрузкой картинок, но я отключал- не помогло.
Нет, нажал "раскрыть" -> "5 постов". И бесконечно вертится загрузка.

**Comment by SthephanShinkufag** [comment]
Все. Переустановил тамперманки, и получил вашу проблему.
Видимо, новая версия тамперманки конфликтует с нашими аякс-запросами.

**Comment by KAMKillJoy** [comment]
Теперь только ждать? :(

**Comment by SthephanShinkufag** [comment]
Хм. А вот со скриптом из ES6-ветки все работает.

**Comment by Y0ba** [comment]
Попробуй заменить `window.addEventListener` и `window.removeEventListener` на `doc.defaultView.[add|remove]EventListener`. В ES6-версии я подобную замену уже делал.

**Comment by SthephanShinkufag** [comment]
Неа. Хотя исправило другую ошибку, связанную с разворотом картинок.
Надо смотреть, как ты сделал `$ajax`.

**Comment by Y0ba** [comment]
Я его сделал с помощью промисов. Ты можешь составить список всех ошибок, связанных с ES6? Я уже частично починил его, может замержим обратно сегодня-завтра.

**Comment by SthephanShinkufag** [comment]
ОК.

**Comment by SthephanShinkufag** [comment]
Я могу потом откатить мастер до состояния es6-ветки, и смержить твой пулл-реквест, не содержащий 7830c9034c1a00014eee60d90dd1ba445bac914d

**Comment by Y0ba** [comment]
Пока что я буду просто отправлять коммиты в es6-ветку, а потом просто её смержишь и всё. Какая разница, одним коммитом больше или меньше.

**Comment by SthephanShinkufag** [comment]
Можешь обновить изменения в `es6.user.js` выше этого коммита, типа исправленного 8chan'а и пр.

**Comment by Y0ba** [comment]
Ага.

**Comment by xStiven** [comment]
Ну темерманки обновился, появилась проблема такая же. Вроде скрипт последней версии.

**Comment by SthephanShinkufag** [comment]
https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/raw/es6/Dollchan_Extension_Tools.user.js

**Comment by KAMKillJoy** [comment]
Спасибо.

**Comment by xStiven** [comment]
Спасибо, тоже.

**Comment by KAMKillJoy** [comment]
Степан, открывай!
{
	"version": "15.1.28.0",
	"location": "https://2ch.hk/mmo/res/4995479.html",
	"nav": {
		"Firefox": false,
		"Opera11": false,
		"Presto": 0,
		"WebKit": true,
		"Chrome": true,
		"Safari": false,
		"isGM": true,
		"isChromeStorage": false,
		"isScriptStorage": false,
		"isGlobal": true,
		"scriptInstall": "Monkey",
		"cssFix": "-webkit-",
		"Anim": true,
		"animName": "webkitAnimationName",
		"animEnd": "webkitAnimationEnd",
		"ua": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36",
		"hasWorker": true,
		"canPlayMP3": true,
		"canPlayWebm": true,
		"hasModernFormData": false
	},
	"cfg": {
		"timePattern": "w+dd+m+yyyy+hh+ii+ss",
		"spells": "[1413117051694,[[6,\"Omegа\",[\"mmo\",\"4842872\"]],[8,[0,[\"253\",\"253\"],[\"1201\",\"1201\",\"750\",\"750\"]],[\"mmo\",\"4686474\"]],[7,\"!khuiokDOKY\",[\"mmo\",\"4621639\"]],[6,\"Omeha\",[\"mmo\",\"4604562\"]],[8,[0,[27,27],[250,250,334,334]],[\"mmo\",false]],[7,\"!L708B4KK6A\",[\"mmo\",false]],[7,\"!uV3Mo4R2c2\",[\"mmo\",false]],[6,\"Omega\",[\"mmo\",false]],[14,103,null]],false,false]",
		"favIcoBlink": 1,
		"expandImgs": 1,
		"preLoadImgs": 1,
		"openImgs": 1,
		"markViewed": 1,
		"strikeHidd": 1,
		"addYouTube": 4,
		"addPostForm": 1,
		"scriptStyle": 2,
		"expandPanel": 1,
		"addImgs": 1,
		"hideBySpell": true,
		"expandPosts": 1,
		"linksOut": 500,
		"textaWidth": 1118,
		"textaHeight": 458,
		"scrUpdIntrv": 0,
		"removeFName": 1,
		"noBoardRule": 0,
		"warnSubjTrip": 1,
		"qReplyX": "left: 749px",
		"qReplyY": "top: 189px",
		"addVocaroo": 0
	},
	"sSpells": [
		"#name[mmo,4842872](Omegа) |",
		"#img[mmo,4686474](=253@1201x750) |",
		"#trip[mmo,4621639](!khuiokDOKY) |",
		"#name[mmo,4604562](Omeha) |",
		"#img[mmo](=27@250x334) |",
		"#trip[mmo](!L708B4KK6A) |",
		"#trip[mmo](!uV3Mo4R2c2) |",
		"#name[mmo](Omega) |",
		"#wipe(samelines,samewords,longwords,numbers,whitespace)"
	],
	"oSpells": "[1413117051694,[[8,[0,[27,27],[250,250,334,334]]],[7,\"!L708B4KK6A\"],[7,\"!uV3Mo4R2c2\"],[6,\"Omega\"],[14,103]],false,false]",
	"perf": [
		[
			"Init",
			42
		],
		[
			"Config loading",
			2
		],
		[
			"Parsing spells",
			0
		],
		[
			"Replace delform",
			0
		],
		[
			"Parse delform",
			446
		],
		[
			"Parse postform",
			88
		],
		[
			"Init keybinds",
			1
		],
		[
			"Init page",
			9
		],
		[
			"Add panel",
			2
		],
		[
			"Preload images",
			4
		],
		[
			"Audio links",
			1
		],
		[
			"Video links",
			13
		],
		[
			"Image links",
			1
		],
		[
			"Sauce buttons",
			55
		],
		[
			"Reflinks map",
			248
		],
		[
			"Apply CSS",
			24
		],
		[
			"Display page",
			0
		],
		[
			"Всего",
			937
		]
	]
}

![2015-03-06 21 30 16](https://cloud.githubusercontent.com/assets/8235528/6531166/132c1a04-c448-11e4-9e37-1df505609e78.png)

**Comment by SthephanShinkufag** [comment]
Эта ошибка уже была исправлена.

https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/raw/es6/Dollchan_Extension_Tools.user.js

**Comment by KAMKillJoy** [comment]
Ок, спасибо.

**Comment by SthephanShinkufag** [comment]
=\

**Comment by Y0ba** [comment]
У него в пику другая ошибка. Связано со спеллом `img`.

**Comment by KAMKillJoy** [comment]
Ну лол. Что-то совсем у вас скрипт отлетает в каждой версии. Спешите с добавлением фич?

**Comment by SthephanShinkufag** [comment]
Это не я. Это все Йоба :P

**Comment by Y0ba** [comment]
Нет. Просто много кода было переписано при миграции на es6, потому и всплывает куча ошибок. Потому ветка es6 и не замержена в основную `master`-ветку.

**Comment by SthephanShinkufag** [comment]
Практически весь скрипт был изменен.

**Comment by KAMKillJoy** [comment]
Ну я спелл убрал ибо он протух давно.

**Comment by Y0ba** [comment]
А что за спеллы у тебя были?

**Comment by KAMKillJoy** [comment]
Скрывал аватаркофага по пикче, но это было нужно полчаса, да так и осталось висеть. Вон же в отладке всё.
"spells": "[1413117051694,[[6,\"Omegа\",[\"mmo\",\"4842872\"]],[8,[0,[\"253\",\"253\"],[\"1201\",\"1201\",\"750\",\"750\"]],[\"mmo\",\"4686474\"]],[7,\"!khuiokDOKY\",[\"mmo\",\"4621639\"]],[6,\"Omeha\",[\"mmo\",\"4604562\"]],[8,[0,[27,27],[250,250,334,334]],[\"mmo\",false]],[7,\"!L708B4KK6A\",[\"mmo\",false]],[7,\"!uV3Mo4R2c2\",[\"mmo\",false]],[6,\"Omega\",[\"mmo\",false]],[14,103,null]],false,false]",

**Comment by KAMKillJoy** [comment]
А чё клосед то? Вот завтра снова придёт аватаркофаг, а у меня скрипт отвалится.

**Comment by Y0ba** [comment]
Обнови по ссылке: https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/raw/es6/Dollchan_Extension_Tools.user.js

И да, создавай новые багрепорты, если найдёшь чего. Этот уже протух.

**Comment by KAMKillJoy** [comment]
Ок.

**Comment by KAMKillJoy** [comment]
Просто началось с одной проблемы, вытекло в другую, а потом вылезла третья и всё в течении исправления предыдущих проблем. Так что вдруг проблемы связаны? Вот и писал сюда.
