### ISSUE TITLE
Обновление до последнего коммита убило спеллы

### ISSUE THREAD

**Issue by YellowSM** [SthephanShinkufag/Dollchan-Extension-Tools#767]
Собсно, решил обновиться - а спелы все сгинули. Абидно.
Или пока не стОит обновляться?

**Comment by Y0ba** [comment]
Что в консоли ошибок? Спеллы оно не убило, просто может возникает ошибка при попытке их отобразить.

**Comment by YellowSM** [comment]
>консоль ошибок
Это которая Консоль браузера?
Тогда вот:

![27 02 15 16-31-15](https://cloud.githubusercontent.com/assets/5058386/6413230/5849d7c0-be9e-11e4-8299-827d30dadde8.png)

фф 36.0, гризманки 2.3, сосач

**Comment by Y0ba** [comment]
При открытии настроек новые ошибки возникают?

**Comment by YellowSM** [comment]
> TypeError: oreps.forEach is not a function Dollchan_Extension_Tools.user.js:6718:5

**Comment by Y0ba** [comment]
Ох. Я выкачу сегодня фикс. Но если не терпится, можешь поискать в коде `oreps.forEach` и строкой выше исправить `if (reps) {` на `if (oreps) {`. Должно помочь.

**Comment by YellowSM** [comment]
О, заработало. сенькс

**Comment by YellowSM** [comment]
Напишу сюда, чтоб не плодить.
Ошибка при отправке файла (вебм):

"Generator throw: " TypeError: Value can't be converted to a dictionary. Dollchan_Extension_Tools.user.js:2882:5

**Comment by SthephanShinkufag** [comment]
https://raw.github.com/SthephanShinkufag/Dollchan-Extension-Tools/master/Dollchan_Extension_Tools.user.js

**Comment by Y0ba** [comment]
@YellowSM можешь првоерить свой баг с `webm` с этой версией: https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/raw/es6/Dollchan_Extension_Tools.user.js
?

Если всё ещё выскакивает ошибка скинь информацию для отладки.

**Comment by YellowSM** [comment]
Выскакивает.

> "Generator throw: " TypeError: Value can't be converted to a dictionary.  Dollchan_Extension_Tools.user.js:3169:5

**Comment by Y0ba** [comment]
Что находится на той строчке в коде? Инфу для отладки скинешь? Сам пост отправляется или нет?

**Comment by Y0ba** [comment]
Хм, у меня на той строчке находится `console.log("Generator throw: ", err);`. А если убрать этот `console.log`?

**Comment by YellowSM** [comment]
"Generator throw: " TypeError: Value can't be converted to a dictionary.

Стек-трейс:
html5Submit$@file:///..../gm_scripts/Dollchan_Extension_Tools/Dollchan_Extension_Tools.user.js:2244:14
tryCatch@file:///..../gm_scripts/Dollchan_Extension_Tools/Dollchan_Extension_Tools.user.js:1244:37
invoke@file:///..../gm_scripts/Dollchan_Extension_Tools/Dollchan_Extension_Tools.user.js:1400:22
continuer@file:///..../gm_scripts/Dollchan_Extension_Tools/Dollchan_Extension_Tools.user.js:3167:15
async/<@file:///..../gm_scripts/Dollchan_Extension_Tools/Dollchan_Extension_Tools.user.js:3181:13
spawn@file:///..../gm_scripts/Dollchan_Extension_Tools/Dollchan_Extension_Tools.user.js:3191:26
_init/</_this.form.onsubmit@file:///..../gm_scripts/Dollchan_Extension_Tools/Dollchan_Extension_Tools.user.js:8792:7
 Dollchan_Extension_Tools.user.js:3169:5

**Comment by YellowSM** [comment]
Пост не отправляется, постоянная отправка.
В коде тоже, что и у тебя
