### ISSUE TITLE
Кукла съёживает посты по ширине

### ISSUE THREAD

**Issue by deterenkelt** [SthephanShinkufag/Dollchan-Extension-Tools#770]
![untitled](https://cloud.githubusercontent.com/assets/2245254/6478668/dcace8ba-c248-11e4-9bb4-37aa6c82cda0.png)

http://nowere.net/b/res/114040.html#i114059
PM 25.2, GM 1.15, DE v15.1.28.0.

**Comment by SthephanShinkufag** [comment]
> Thumbnail displayed, click image for full size

Не нужно.

Можно задать

```css
.thumbnailmsg { opacity: 0 !important; }
```

вместо `display: none`, но тогда некрасиво будут смотреться посты без текста или с коротким текстом.

**Comment by deterenkelt** [comment]
«Некрасиво»?

**Comment by SthephanShinkufag** [comment]
<a href='http://rghost.ru/private/6gZBzCvSg/129d0d663651d972ebc6fa7ce5765b84.view'><img src='http://rghost.ru/private/6gZBzCvSg/129d0d663651d972ebc6fa7ce5765b84/image.png' /></a>

**Comment by SthephanShinkufag** [comment]
Альзо, с оригинальной надписью та же елдырьма

<a href='http://rghost.ru/private/6dTKz6VT2/dfb2591a7647a0d7422717402480397b.view'><img src='http://rghost.ru/private/6dTKz6VT2/dfb2591a7647a0d7422717402480397b/image.png' /></a>

**Comment by SthephanShinkufag** [comment]
Нужно придумать какое-то компромиссное решение.

**Comment by deterenkelt** [comment]
М-м. А если просто на всю ширину экрана растянуть? Как я понимаю, динамически под текст ширина поста не подстраивается и всё равно будет бить строки, словно у меня нищеквадрат 800×600.

**Comment by SthephanShinkufag** [comment]
> на всю ширину экрана растянуть

Слишком кардинально. Пусть это останется уделом пользовательских css. Будут массовые жалобы.

**Comment by SthephanShinkufag** [comment]
Пустое место в постах раздражает гораздо сильнее, чем нынешняя ситуация..

**Comment by deterenkelt** [comment]
Это я уже знаю как сделать, но было бы хорошо, если бы кукла сама про это знала, а мне не надо было прописывать кучу `@moz-document domain` в userContent.css.

**Comment by Y0ba** [comment]
Используй `stylish`.

**Comment by SthephanShinkufag** [comment]
Йоба, вся проблема в наличии картинки. Так как текст постов не блочный, а float-картинка занимет свои 250 пикселей, то текст пытается ее обтекать. Применение `display: inline-block` к тексту может решить проблемму, но много где чего ломает.

**Comment by SthephanShinkufag** [comment]
`aib.qMsg + ' { display: inline-block !important; }`

**Comment by deterenkelt** [comment]
> Будут массовые жалобы.
Ну зделай галочку? Её ж не обязательно включать по умолчанию.

**Comment by SthephanShinkufag** [comment]
Хочется без галочек. И чтобы всех устраивало.

**Comment by deterenkelt** [comment]
> Хочется без галочек.

С шестью табами в настройках, уже забитыми ими, об этом как-то поздно говорить.

**Comment by SthephanShinkufag** [comment]
Никто до вас не жаловался.

**Comment by deterenkelt** [comment]
~~Могу пожаловаться с другого аккаунта, если надо~~Буду первым же :D
Вообще меня это давно уже беспокоит, просто, если раньше я довольствовался

    @-moz-document domain("iichan.hk") {
        .reply {width: 100%}
    }

в userContent.css, сейчас я там давно уже не сижу и часто меняю борды. В общем, «хватит это терпеть» во все поля.

**Comment by YellowSM** [comment]
> Никто до вас не жаловался.

На самом деле, тоже такое замечал. С картинкой текст столбиками выглядит херово.
Я думал, это не кукла. Но если можно пофиксить, то присоединяюсь к реквесту

**Comment by SthephanShinkufag** [comment]
Добавил опцию:
Посты > Растягивать посты по ширине экрана

**Comment by deterenkelt** [comment]
http://webmup.com/Evyjh/

**Comment by YellowSM** [comment]
А можно превьюшки постов не растягивать на весь экран, если растягивание включено?
Растянутые посты на борде мне нравятся, а вот в превьюшках это ужос (особенно если в посте 1-2 строки всего)

**Comment by deterenkelt** [comment]
Как-то странно оно понимает `width: 100%`…
![1429974141.jpg](http://images.netbynet.ru/imgs/daaaa0fcc52930b37a012af0f6f8bb26.jpg).

**Comment by deterenkelt** [comment]
На Краутчане отвалилось:
![](http://i.imgur.com/UWevYq0.png)
А на форчке работает.

FF 38.0.1, GM 3.2, DE 15.6.10.0.

**Comment by deterenkelt** [comment]
В версии 15.7.4 ширина постов увеличивается на 2 пикселя вместо расширения на весь экран.

**Comment by SthephanShinkufag** [comment]
У меня все работает.
Отключите все свои стили и проверьте.

**Comment by SthephanShinkufag** [comment]
Вы используете какие-то свои стили.
Отключите их.
У меня все работает.

**Comment by SthephanShinkufag** [comment]
А. Вы про краутчан.. Таки да. щас посмотрю.

**Comment by SthephanShinkufag** [comment]
Починил расширене на весь экран на краутчане.

**Comment by deterenkelt** [comment]
У меня скрипт откатился до 15.7.2, так и надо? Кстати, оно продолжает неработать, хотя у меня userContent.css пролюблен, а стайлиш вообще не стоит.

**Comment by SthephanShinkufag** [comment]
Wut? Последние коммиты не содержат инкремент версии, она остается 15.7.2. Это последняя версия на сегодняшний момент. 

> продолжает неработать

Ну это уже пушка.

Отсюда качали?

https://raw.github.com/SthephanShinkufag/Dollchan-Extension-Tools/master/Dollchan_Extension_Tools.user.js

**Comment by SthephanShinkufag** [comment]
Проблема на краутчане была, да. И заключалась в `float: left`.
И исправил на `float: none`. Все теперь растягивается.
Смотрите у себя в инспекторе стилей, может у вас аще что-нибудь влияет.

**Comment by SthephanShinkufag** [comment]
Попробуйте строку

```js
		x += '.' + aib.cReply.replace(/\s/, '.') + ':not(.de-pview) { float: none; width: 100%; }';
```

заменить на

```js
		x += '.' + aib.cReply.replace(/\s/, '.') + ':not(.de-pview) { float: none !important; width: 100%; }';
```

**Comment by deterenkelt** [comment]
> Wut? Последние коммиты не содержат инкремент версии, она остается 15.7.2.

![](http://i.imgur.com/Wrw5Lsm.jpg)

Я точно помню, что в кукле видел 15.7.4.0, я эту версию в нескольких багрепортах указывал (хотя и копипастил из одного в другой пару раз).

> Отсюда качали?

Хмм, вот теперь работает. Я просто ткнул в куклу правой кнопкой мыши, где обновить, обновлений не вылезло, зашёл на гитхаб, там предложило установить то же самое, поэтому я нажал cancel, но установив по ссылке сейчас, понимаю, что у меня стояло что-то старое.
