### ISSUE TITLE
Непонятная бага со счетчиком обновления треда

### ISSUE THREAD

**Issue by YellowSM** [SthephanShinkufag/Dollchan-Extension-Tools#771]
Уже несколько раз проявлялось (сосач). В какой-то момент счетчик проглючивает и он уходит в минус и продолжает уходить, пока вручную не обновишь линком "получить новые посты".
Но после ручного обновления он начинает убывать с завышенной скоростью (в 2-3 раза быстрее крутится).

Сижу через прокси, канал не такой большой. Повторить баг не могу, т.к. не понимаю из-за чего это происходит.
Есть подозрение, что в момент просмотра картинок/вебмок канал забит и в этот момент происходит обновление треда, там что-то проглючивает. И после этого бывает выскакивает такая бага. (но это предположение)

Когда счетчик мотается быстро - в консоли ошибок нет. А до этого момента я консоль не включал.

фф 36, гризманки, коммит последний https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/commit/bcdabfaa1a46be56393b7e59a1efa3a1af6aa85c

**Comment by YellowSM** [comment]
Во, запостил вебм (долго тупило), потом началось.
Таймер выставлен на 15 сек. В принципе они срабатывают, но счетчик уменьшается в 2 раза быстрее. Как-будто два потока работают.

![doll-timer](https://cloud.githubusercontent.com/assets/5058386/6526196/0ff1ab9c-c420-11e4-893e-a8fcf0dd79e4.gif)

**Comment by SthephanShinkufag** [comment]
Наблюдал такую хрень не раз, но не знаю, как гарантированно добиться.

**Comment by Y0ba** [comment]
А с последним скриптом как? Там для остановки загрузки используется специальный токен (идея спижжена со встроенной в .NET винрарной штуковины https://msdn.microsoft.com/en-us/library/dd997364%28v=vs.110%29.aspx ).

**Comment by SthephanShinkufag** [comment]
Буквально сегодня с коммитом 2be214a1020b0318c181dab4dee075345bbd0f28

Причем как-то интересно считало, будто бы два разных счетчика что-то типо вот такого, точно не помню:

20
8
19
7
18
6
17
5
16
4
...

**Comment by SthephanShinkufag** [comment]
Стало так считать, егда пост отправил. Потом этого добиться не мог.

**Comment by Y0ba** [comment]
Хм. Сейчас попробую исправить.

**Comment by Y0ba** [comment]
Вроде теперь всё: 1138363391010dbad6cce56ba860990620bec107

**Comment by SthephanShinkufag** [comment]
Полет нормальный пока. Посмотрим.

**Comment by YellowSM** [comment]
Не, не помогло. Теперь и я такую багу словил - два счетчика друг друга перебивают (45... 15... 44... 14)
Опять вылезло после постинга вебмки. До этого счетчик уже успел увеличиться (т.к. тред полумертвый).

**Comment by Y0ba** [comment]
Ошибки в консоли есть какие?

**Comment by YellowSM** [comment]
Не, ошибок нет. Вроде бы добился стабильного появления бага.
Гружу вебмку (скорость небольшая), счетчик обновления за время загрузки успевает несколько раз обновлять тред (важно или нет хз). 
Пока грузится хожу по другим вкладкам. После загрузки начинается двоение счетчика. Причем обновление треда после этого будет два раза - каждый счетчик работает сам по себе и обновляет тред когда доходит до нуля.

Ты, помнится, отключал обновление счетчика на неактивных вкладках. Может, в этом направлении копать? Пробовал загружать без перехода по вкладкам во время загрузки - тогда вроде бага не проявляется.

ЗЫ. Индикатор загрузки няшный. А можно еще прикрутить скорость аплоада?

**Comment by YellowSM** [comment]
Ну да, еще раз попробовал. Вроде стабильно бага проявляется. Причем бывает, что счетчики считают синхронно - кажется, что один, а обновления запрашивает два раза.
А если жамкнуть "получить новые посты", тогда уже раздвоение будет видно - один обнулится, а второй продолжит считать дальше.

**Comment by Y0ba** [comment]
Пробуй: https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/raw/master/Dollchan_Extension_Tools.user.js

**Comment by Y0ba** [comment]
И ещё, @YellowSM нужно ли останавливать обновление треда, когда отправляется пост? Кто-то просил в куклотреде и сейчас скрипт приостанавливает (тут и была ошибка), но если пост отправляется долго, можно много чего пропустить.

**Comment by YellowSM** [comment]
> и сейчас скрипт приостанавливает

Сейчас в смысле по ссылке выше? Или в старом?
На мой взгляд лучше приостанавливать. Т.к. если инет медленный, то обновление треда только тормозит загрузку. А после загрузки можно форсировать обновление.
Либо засекать сколько по времени идет отправка поста и если он не успевает отправится до обновления треда, то таймер обновления замораживать и обновлять уже после отправки.

Ща потестю.

**Comment by Y0ba** [comment]
> Сейчас в смысле по ссылке выше? Или в старом?

Уже давно так. Просто при переходе на es6 немного сломал его.

**Comment by YellowSM** [comment]
Вроде всё нормально работает.

Алсо, спасибо за скорость аплоада. Может ее лучше на прогрессбар прилепить? Шрифтом поменьше. Окно по ширине тогда гулять не будет.

**Comment by SthephanShinkufag** [comment]
>скорость аплоада
Шрифтом поменьше. Окно по ширине тогда гулять не будет.

594971244557529cf838b12cd912c37a356611a3

**Comment by YellowSM** [comment]
Теперь вообще индикатор загрузки пропал )

**Comment by YellowSM** [comment]
А не, вроде работает. На одной вебмке не показывает

**Comment by SthephanShinkufag** [comment]
Пишет "Файл поврежден"? Бывают вебм-ки, сделанные некорректным способом.

УМВР.

**Comment by YellowSM** [comment]
Ничего не пишет. Бесконечная загрузка со стандартным "Отправка...". В консоли чисто.
Самое интересное, качал я эту вебку с борды.

**Comment by YellowSM** [comment]
Кстати, мельком один раз при отправке поста заметил в индикаторе аплоада (то ли в трафике, то ли в скорости) кучу цифр после запятой. Разглядеть не успел. Пока не повторялось
