### ISSUE TITLE
Перестала работаеть капча со скриптом на дваче.

### ISSUE THREAD

**Issue by xStiven** [SthephanShinkufag/Dollchan-Extension-Tools#772]
Внезапно перестала работать капча, как гугловская так и яндоксовская. Без скрипта пашет. Стоит Хромоопера Opera 27, скрипт пашет через темперманки.

**Comment by SthephanShinkufag** [comment]
А если кликнуть в поле ввода текста? Или выбрать картинку?

**Comment by xStiven** [comment]
Хм, однако жи, да появляется. Странно, до того как куки почистил не появлялась, но после этого печать не пробовал, сразу сюда пошел. Прошу прошения.

**Comment by YellowSM** [comment]
Кстати, Степан, сделай плиз, чтобы капча загружалась при добавлении картинки (в нижней форме), т.е. когда текстовое поле пустое. А то чтобы запостить только картинку нужно тыкать в текстареа чтобы капча загрузилась - не очень удобно

**Comment by SthephanShinkufag** [comment]
Пробуйте.

https://raw.github.com/SthephanShinkufag/Dollchan-Extension-Tools/es6/Dollchan_Extension_Tools.user.js

**Comment by YellowSM** [comment]
Во, спасибо. Работает
