### ISSUE TITLE
Странно скрывает посты и треды

### ISSUE THREAD

**Issue by xStiven** [SthephanShinkufag/Dollchan-Extension-Tools#774]
Очень странно скрывает треды. Т.е. после того как скрыл тред он все равно виден после того как обновить страницу, НО, если в панели скрипта из списка скрытых тредов удалить "скрытый" тред - он внезапно скрывается когда обновляешь страничку.Не уверен что это баг скрипта, скорее всего это у меня что то с настройками, но началось внезапно, хотя ничего не менял.

**Comment by xStiven** [comment]
Ой лол, то ли у скрипта, то ли у Абу то ли у оперы синдром полярности, так же как для того что бы скрыть тред - его нужно удалить из скрытого, так же само что бы переключить капчу на гугловскую - нужно выбрать яндексовую, и наоборот, что бы врубить на дваче яндекс капчу - нужно врубить гугло капку в настройках.

**Comment by SthephanShinkufag** [comment]
> после того как скрыл тред он все равно виден после того как обновить страницу
Да, есть такое. Надо починить.

**Comment by SthephanShinkufag** [comment]
Пробуйте.

https://raw.github.com/SthephanShinkufag/Dollchan-Extension-Tools/master/Dollchan_Extension_Tools.user.js
