### ISSUE TITLE
Сломанное автоскрытие

### ISSUE THREAD

**Issue by Bfgeshka** [SthephanShinkufag/Dollchan-Extension-Tools#776]
При включенной опции CSS3 анимации всплывшие окна постов не закрываются, то же относится к окнам настроек - вплоть до перезагрузки страницы.

FF 36.0.1, версия скрипта с поддержкой ES6.

**Comment by SthephanShinkufag** [comment]
А при чем тут автоскрытие? Что вы имеете в виду под автоскрытием?
Что пишет в консоли ошибок?

**Comment by Bfgeshka** [comment]
Не то скрытие постов, которое по кнопке, нет. Наводишь курсор на ссылку - всплывает окно с постом, но при удалении курсора окно не исчезает, а продолжает висеть.

В консоли ни ошибок, ни warning'ов - только GET-запросы при наведении.
