### ISSUE TITLE
Проблемы со скрытием постов

### ISSUE THREAD

**Issue by DCPtime** [SthephanShinkufag/Dollchan-Extension-Tools#777]
Их 2: Во-первых, посты почему-то не скрываются до того, как я зашел в тред. Т.е если я скроллю нулевую, то я буду видеть в "последних постах тредов"  посты, которые я обозначил как  #words(что-нибудь) |;
Вторая проблема: даже находясь в треде, я почему-то вижу посты, которые  которые обозначил как #words(что-нибудь). Например, в вемб тред кидают вембку, и в ответах к ней я начинаю видеть посты, обозначенные в  #words. Иногда бывает, что слово с ненавистным мне тегом сначала вижу, а потом, через пару секунд, проскроллив страницу до низу и нажав ctrl+f и введя в строку это слово, оно внезапно исчезает. Во мне ли проблема?

**Comment by SthephanShinkufag** [comment]
Ничего не понял, скачайте последний скрипт:

https://raw.github.com/SthephanShinkufag/Dollchan-Extension-Tools/master/Dollchan_Extension_Tools.user.js
