### ISSUE TITLE
Threads added to favs even if you're banned

### ISSUE THREAD

**Issue by CherryPill** [SthephanShinkufag/Dollchan-Extension-Tools#782]
If you're banned from 4chan and try to reply to a thread, the thread appears in the favorite's list either way.

**Comment by SthephanShinkufag** [comment]
But if you're trying to answer into a thread, even if you are banned, it means that you are interested in it and want to watch him in the future, isn't it?

**Comment by CherryPill** [comment]
Then 'Add threads to favorites on reply' doesn't make sense here, because no actual reply was submitted.

**Comment by SthephanShinkufag** [comment]
Done. If you're using chrome extension then let me know, I will update it.

**Comment by SthephanShinkufag** [comment]
Fixed script: https://raw.github.com/SthephanShinkufag/Dollchan-Extension-Tools/master/Dollchan_Extension_Tools.user.js
