### ISSUE TITLE
"Banned" Overlay is too big

### ISSUE THREAD

**Issue by ganego** [SthephanShinkufag/Dollchan-Extension-Tools#784]
So I sometimes have to deal with the banned overlay thanks to some people in my IP range but the problem is, that I cannot read the message.
See this screenshot: http://postimg.org/image/ksi2v8nkv/

As you can see it's missing the important parts and you cannot use the scrollbar because it will only scroll the page but not the overlay. I'm using a 'default' zoom of 145%. 
This is what I get when using 45% zoom: http://postimg.org/image/kfctf4vzp/

**Comment by YellowSM** [comment]
Видимо, мой коммент не заметили в коммите https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/commit/7c81f8b5b01a980a8085364819eb99a95215e90a#commitcomment-10979587
Теперича при выдаче окна с баном горизонтальный скролл то появляется, то исчезает, пока окно "анимирует"

**Comment by YellowSM** [comment]
thnx
