### ISSUE TITLE
Обновление YouTube API

### ISSUE THREAD

**Issue by Y0ba** [SthephanShinkufag/Dollchan-Extension-Tools#785]
Гугл сегодня преподнёс небольшой сюрприз: https://support.google.com/youtube/answer/6098135?p=yt_devicesupport&hl=en&rd=1
Кратко: были обновлены API для доступа к метаданным. Однако портировать просто так скрипт не получится, поскольку теперь любой запрос должен быть авторизирован с приватным ключом у которого есть ограничение на 50000000 запросов в день.

Пока что отключил функцию загрузки заголовков: e8428184135dff415a37f967bbdd0d45147896fc

**Comment by Y0ba** [comment]
И да, если даже в скрипт и воткнуть ключ, который будет сгенерирован для тебя или меня, то ты (или я) сможем просматривать все метаданные, загруженные пользователями куклы и с какой страницы они были сделаны. Т.е. тут ещё встаёт вопрос о приватности.

**Comment by Y0ba** [comment]
@SthephanShinkufag Ммм, насчёт статистики соврал. Она там не такая подробная. Но всё же. Может предоставить пользователю поле для ввода своего ключа?

**Comment by VisualKei** [comment]
@Y0ba, можешь отписать небольшой FAQ по гуглоключам - как получать, где про них почитать, какие подводные камни? В одной проге нужно аналогичную операцию провести, хочется дать автору ссылку на инфу, чтоб он не морочился лишнего.

**Comment by Y0ba** [comment]
@VisualKei https://developers.google.com/youtube/registering_an_application
Чуть позже запилю в FAQ на русском и со скриншотами.

**Comment by VisualKei** [comment]
Там говорится про server key и browser key - я так понимаю, нужен второй, или это без разницы?

**Comment by Y0ba** [comment]
Второй, да.

**Comment by VisualKei** [comment]
А для обычной виндовой проги, которая будет такие запросы слать, тоже он? В чём разница вообще?

**Comment by Y0ba** [comment]
Да. Разница в том, в какую таблицу идёт статистика.

**Comment by etnl** [comment]
We don't need API keys to get basic stuff, just use [oembed](http://www.oembed.com/) like this: http://www.youtube.com/oembed?url=http%3A//youtube.com/watch%3Fv%3DdQw4w9WgXcQ&format=json

**Comment by Y0ba** [comment]
@etnl действительно. Добавил в скрипт. Оставил возможность yt-api, поскольку там загружается чуть больше инфы (дата загрузки и количество просмотров). Но если ключ отсутствует, либо при загрузке с ключём произойдёт ошибка скрипт автоматом перейдёт на oembed.
