### ISSUE TITLE
Раскрытие треда на доске некорректно

### ISSUE THREAD

**Issue by VisualKei** [SthephanShinkufag/Dollchan-Extension-Tools#787]
Например, на доске показанный хвост треда - 10 постов. Выбираем в меню раскрыть 15 - выводится 15 ранее скрытых, а раньше было бы раскрыто только 5. При этом в счётчике скрытых постов внизу ОПпоста считается по-старому (как будто раскрыли только 5), и кроме того все номера постов получают +10 к правильным значениям.

Алсо, если в меню теперь выбрать этот пункт второй раз, то будет показано уже именно всего 15 постов, но +10 у номеров постов останется. Дальнейший выбор этого же пункта больше ничего не меняет. Но если после этого выбрать раскрыть например 30 постов, то цикл повторится - первое нажатие раскрывает +30 постов, второе оставляет всего 30, следующие не влияют. Номера у постов при этом прирастают ещё на 15.

Возможно стоит переделать всю логику на "пункт меню всегда означает показать столько ранее скрытых постов", если это не слишком геморрой, не знаю.

**Comment by VisualKei** [comment]
@Y0ba обновил багрепорт, читай не из почты.

**Comment by Y0ba** [comment]
> Возможно стоит переделать всю логику на "пункт меню всегда означает показать столько ранее скрытых постов", если это не слишком геморрой, не знаю.

Не знаю. Это не сложно, но пока вернул как надо. 5/15/... всего постов и новые, и видимые.

**Comment by VisualKei** [comment]
Ещё при постинге с доски надо поправить - номера постов в хвосте получают +1 к правильным, всё остальное при этом вроде нормально (пока проверил только простой случай добавки одного своего свежедобавленного поста, без появления новых постов с момента прошлого рефреша страницы).

**Comment by VisualKei** [comment]
А если предварительно раскрыть тред например на 50 и запостить ответ, то номера получают +41.
@Y0ba,  пофикси же.

**Comment by VisualKei** [comment]
А если запостил 1 свой пост и за это время в треде добавился 1 чужой, то хвосты получают +2.
Всё остальное при этом работает правильно.

**Comment by SthephanShinkufag** [comment]
Куклочую. Что-то там все накручено, раскрытие треда как попало работает. Какие-то невидимые посты, которые не удаляются, хрен поймешь, что там Йоба имел в виду. Из-за них счетчик и сбивается.

**Comment by VisualKei** [comment]
Я вот думаю таки стоит добавить в конец меню отдельный пункт `+10 постов` с вышеописанным смыслом. Иногда даже 100 раскрытых постов оказывается мало (или наоборот много), а открывать тред в отдельной вкладке и скроллить там влом, раз уж начал на доске его хвост читать.

**Comment by SthephanShinkufag** [comment]
Хорошая идея.

**Comment by VisualKei** [comment]
@SthephanShinkufag, сделай же плиз пункт меню "+10 постов".
