### ISSUE TITLE
Проблемы с предзагрузкой картинок и сохранением всех картинок/треда

### ISSUE THREAD

**Issue by VisualKei** [SthephanShinkufag/Dollchan-Extension-Tools#788]
@Y0ba, у меня от коммита 1457b0511f5584cdd94380bca4e322392b3055e7 на Лисе 28 сабж.
Предзагрузка картинок не работает. В случае сохранения треда в тарболе оказывается только сама html-страничка и скрипт, в случае сохранения картинок тарбол - килобайт нулей. При запуске сохранения в алерте прогресс не идёт дальше 1/N, но через некоторое время таки предлагается сохранить тарбол. В консоли ничего. Видимо некролисопроблемы, но пофикси пожалуйста.

Алсо, у меня и до этой правки в сохранённых тредах нет карты ответов внизу постов, а в их попап-превью - есть. А если навести мышь на ссылку-имя прикреплённой к посту картинки (указывающую на сохранённый файл), то всплывает превью `Загрузка...` как для ссылки на пост в другом треде, которое потом превращается в `Ошибка подключения`. Проверял на ичане, если что.

**Comment by Y0ba** [comment]
Проблема скорее не со старым фоксом, а со старым гризманки. Какая у тебя версия обезъяны?

**Comment by VisualKei** [comment]
Стояла 1.15. Поставил 2.0 с поддержкой `responseType` и бэкпортнул туда последующий фикс на эту тему - нет эффекта. 2.1 и выше уже не пашут даже с правкой минверсии. Алсо, сами картинки при этом с сервера скачиваются.

А по второй части подтверждаешь у себя?

**Comment by YellowSM** [comment]
Хракач.
При сохранении треда для вебмок не сохраняются превьюшки. Зато для тех вебмок, которые загрузить не удалось (кукла ошибку загрузки выдает), превьюшки сохраняются.

Кстати, а ошибки загрузки можно как-то пофиксить? Ну там несколько раз пытаться сохранять или еще как? А то руками приходится докачивать.

**Comment by VisualKei** [comment]
@Y0ba, плиз пофикси же карту ответов в сохранённых тредах.

**Comment by SthephanShinkufag** [comment]
> пофикси же карту ответов в сохранённых тредах

Баг актуален? У меня все работает. Сохраняю тред - есть карта ответов.

**Comment by YellowSM** [comment]
А сохранение превьюшек для вебмок сделаешь?

**Comment by VisualKei** [comment]
@SthephanShinkufag 
Да. Сейчас покрутил подробнее - на вышеупомянутом некроконфиге нашёл ещё проблемы.
С текущей версией скрипта на 4чане предзагрузка картинок (и сохранение треда) не работает с теми же симптомами как в оппосте, на ичане и крауте предзагрузка норм. Версия перед упомянутой в оппосте правкой на 4чане картинки предзагружает и сохраняет, но треды сохраняет без css и интерфейса скрипта нет.
Сохранённые с краута треды  (что той старой версией, что текущей) - css и картинки в архиве есть, но интерфейса скрипта нет.
Сохранённые с ичана - кроме вышеописанного всё вроде норм.

Наверное проще мне забить на это всё, чем вам обоим в этом разбираться.

**Comment by VisualKei** [comment]
@Y0ba 
Ещё кстати заметил, что после коммита 4a082e20d65f384b2f1950bbf577a80d281dea45 при каждом обновлении треда скриптом, если в треде нет изменений, то в консоли стала появляться ошибка `no element found` в html-странице треда (не знаю где именно - пишет в строке 1, но там весь html-файл в одну строку). Вроде ничему не мешает, но может важно.

**Comment by SthephanShinkufag** [comment]
@VisualKei 

> на вышеупомянутом некроконфиге

Ой вееей, только сейчас дошло. Смотел в обычной лисе.
Может, доберусь до некролисы егда-нибудь.

@YellowSM 

> А сохранение превьюшек для вебмок сделаешь? 

Done.

**Comment by SthephanShinkufag** [comment]
На 28 лисе недопустима гризманки 2, по-моему.

**Comment by VisualKei** [comment]
Если грузить из аддонов то да, но я подробно смотрел коммиты и как автор менял совместимость бет, пробовал до какого работает и кое-что добавил (выше тоже описано). То есть в итоге у меня не чистая 2.0, могу выложить если будешь копаться.

**Comment by SthephanShinkufag** [comment]
Официальная инфа, родной.

https://addons.mozilla.org/ru/firefox/addon/greasemonkey/versions/

> Версия 2.0beta1
Выпущено June 5, 2014 293.6 kB
Работает с Firefox 29.0 и выше

**Comment by SthephanShinkufag** [comment]
> и кое-что добавил (выше тоже описано). То есть в итоге у меня не чистая 2.0

Э, не, родной, за ваши солянки точно никто браться не будет.

**Comment by VisualKei** [comment]
Ну сейчас проверю с официальной 1.15 тогда.

**Comment by SthephanShinkufag** [comment]
Я тоже проверю вечером 28 с 1.15

**Comment by VisualKei** [comment]
Да, чего-то в моей солянке не совсем правильно работает. Но единственное что изменилось - предзагрузка картинок на 4чане заработала, этот вопрос снимается. Всё остальное вышеописанное без изменений.

**Comment by VisualKei** [comment]
Ещё чуть поковырялся - не в моей солянке дело, первая же бетка 1.16b2 с аддонов, которая какбе совместима с лисой 27 и выше, уже даёт те же проблемы с предзагрузкой картинок на 4чане (захожу по несекурному http, если важно).
Я в принципе изначально стал с этим ковыряться так как подумал, что стали нужны фичи из манкикоммитов ba9e9eae9f22c9afcdb9dc3d31a91ecd2909ca70 и 59f07764b8c975cc3cef451743e3f2754fc95f45. Видимо они сразу и дают этот глюк, потому что другие изменения с 1.15 до 1.16b2 вроде про другое и никак не должны влиять, то есть дело не в несовместимости обезьяны с лисой.
@Y0ba плиз глянь если не в лом и скажи, нужно оно для скрипта или нет, и если да, то поправь его под это.

**Comment by YellowSM** [comment]
Спасибо за превьюхи. А для ютуба в оффлайне плеер теперь не грузится?

Алсо, чтоб не плодить , напишу тут. Попробовал сохранить этот тред: https://2ch.hk/po/res/9654738.html
так в оффлайновой версии у body какого-то хрена display:none прописался.

**Comment by SthephanShinkufag** [comment]
> для ютуб-ссылок в оффлайне плеер теперь не грузится

У меня все работает. Попробуйте треды из /mu, например.

> у body какого-то хрена display:none прописался

Done.

**Comment by YellowSM** [comment]
Теперь все заработало.

**Comment by KonataIzumi** [comment]
Не могу скачать большие треды размером ~700 файлов. Загрузка проходит, но окно сохранения архива не появляется. 2ch.hk, Iceweasel 40.0.3, Greasemonkey 3.4, Dollchan Extension Tools 15.8.27.0.

**Comment by SthephanShinkufag** [comment]
Refs to #623
