### ISSUE TITLE
2chan.net разворачивание картинок

### ISSUE THREAD

**Issue by Dezaimasu** [SthephanShinkufag/Dollchan-Extension-Tools#791]
По клику всегда скукоживаются/растягиваются до размера, указанного в "Минимальный размер картинок (px)". Вне зависимости от собственно разрешения картинки. И в посте, и по центру.
На опцию "Уменьшать в экран большие картинки" не реагируют.
Хотя на деле они открываются и загружаются, но визуально выглядит дико.

**Comment by SthephanShinkufag** [comment]
Это проблема всех борд, где размеры картинок в посте **не указываются**.
Скрипту неоткуда взять размер картинки, вот он и лепит значение по умолчанию.

**Comment by Y0ba** [comment]
Починено в последней версии.
