### ISSUE TITLE
Постинг на 2ch.hk

### ISSUE THREAD

**Issue by The-OP** [SthephanShinkufag/Dollchan-Extension-Tools#793]
Макабу опять шатают. Теперь в случае успешного поста она возвращает не 3xx с Location = новый пост, а 200 с таким JSON: {"Error": null, "Status": "OK", "Num": номер нового поста}. Или таким для нового треда: {"Error": null,"Status": "Redirect", "Target": номер нового треда}. Кукла, соответственно, выдает error: undefined. Поправьте, пожалуйста.

**Comment by YellowSM** [comment]
Присоединяюсь. Плюс ко всему после такого постинга треды в избранное не добавляются, как раньше.

**Comment by Nosorog312** [comment]
Тащемта да.
У меня много времени ушло на локализацию проблемы на моей Мозилле, так что с этим тредом меня опередили.
Кароч, всё как ОП сказал.

**Comment by The-OP** [comment]
Вот фикс короче: SthephanShinkufag/Dollchan-Extension-Tools#794

**Comment by Nosorog312** [comment]
Теперь появилась бесконечнаязагрузка страницы.
