### ISSUE TITLE
Обновление chrome extension

### ISSUE THREAD

**Issue by CherryPerry** [SthephanShinkufag/Dollchan-Extension-Tools#795]
Chrome/manifest.json
```
"version": "15.4.20.0"
```

Версия не обновлена, в хромстор не залита (хотя я не знаю, как там происходит процедура публикации расширений).

**Comment by Y0ba** [comment]
Это к степану. У меня доступа к хромстору нет.

@SthephanShinkufag

**Comment by linux111** [comment]
В тамперманки не работают настройки, а по старинке хром уже не дает поставить. В целом нету возможности пользоваться скриптом. Пофиксите макаку хотя бы.

**Comment by linux111** [comment]
Алсо установил предыдущую ревизию и все заработало, в последней поламали.

**Comment by Y0ba** [comment]
Именно этим коммитом сломал https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/commit/c19da2734e58c37fd24e6cd818c9715b2deefcff ?
А ошибки какие-нибудь возникают?

**Comment by Y0ba** [comment]
Проверил. У меня всё работает. Какая версия хрома/тампермонки? Какая борда? Любые настьройки не сохраняются или какие-то особенные? В консоли ошибок что-нибудь есть?
