### ISSUE TITLE
Вы что, предопределили ⌘R в Chrome?

### ISSUE THREAD

**Issue by yurikoles** [SthephanShinkufag/Dollchan-Extension-Tools#797]
Сочетание ⌘R должно обновлять страницу, об этом все знают, но вы сделали по этому сочетанию создание ответа.

**Comment by Y0ba** [comment]
Не. Ответ по-умолчанию просто `R` безо всяких модификаторов. Скрипт проверяет модификаторы `Ctrl`, `Alt` и `Shift`, но вот mac command key не проверяется. Надо бы пилить возможноть создания горячих клавиш с ⌘ или просто игнорировать все нажатия с ней?

**Comment by yurikoles** [comment]
Я думаю лучше пока игнорировать, т.к. это простое исправление бага, но если будет FR, то можно и запилить.
