### ISSUE TITLE
Небольшая бага в отображении правила скрытия поста

### ISSUE THREAD

**Issue by YellowSM** [SthephanShinkufag/Dollchan-Extension-Tools#799]
Есть спелл: `#name(Heaven) & !#op`
А посты, скрытые по нему отмечаются как:`autohide: !#op`
Т.е. первая часть спелла не отображается. Это так и задумано? Похоже на проблему со знаком &

**Comment by Y0ba** [comment]
Это не проблема со знаком `&` просто отображается последний сработавший спелл в наборе правил.

**Comment by YellowSM** [comment]
Но оно у меня в скобках, т.е. так: 
```
...
(#name(Heaven) & !#op) |
...
```
Может, лучше всё выражение выводить? А то ведь сути не отображает

**Comment by Y0ba** [comment]
Ммм. Пришлось пол интерпретатора спеллов переписывать. Есть вопрос насчёт `#wipe`. Сайчас он при скрытии отображается примерно так: `#wipe(symbols,capslock)<CAPSLOCK: 50%>`, т.е. сначала идёт полное описание спелла, а затем в треугольных скобках причина скрытия. Так пойдёт или реальную причину скрытия стоит отображать по-другому?

**Comment by VisualKei** [comment]
Я думаю, проще и одновременно наглядней будет `#wipe(symbols,capslock: 50%)`.

**Comment by VisualKei** [comment]
Хотя если бывает, что причина без дополнительной информации, тогда её ещё капсом выделять.

**Comment by Y0ba** [comment]
Лучше жирным шрифтом. Или обеими сразу.

**Comment by VisualKei** [comment]
Да, болдом пожалуй лучше будет, но обеими это уже перебор.

**Comment by Y0ba** [comment]
Сделал всё таки КАПСОМ. А то там защита от XSS, которую ломать уж очень не хотелось.

**Comment by YellowSM** [comment]
Спасибо!
