### ISSUE TITLE
Всплывает сообщение Error: undefined при успешном ответе

### ISSUE THREAD

**Issue by yurikoles** [SthephanShinkufag/Dollchan-Extension-Tools#801]
В двачике, Chrome beta, капча при этом остаётся старая, хотя она конечно же уже не работает.

**Comment by Y0ba** [comment]
Скрипт стоит в виде расширения?

**Comment by yurikoles** [comment]
Да

**Comment by Y0ba** [comment]
Расширением заведует степан, а он сейчас в оффлайне. У меня нет доступа к гугл-стору. Поставь скрипт через тамперманки, либо собери расширение сам.

**Comment by yurikoles** [comment]
Т.е. это уже починили в master?

**Comment by Y0ba** [comment]
Ага. 26252c99999ee77aee665af65a881ffc82a28f58
