### ISSUE TITLE
Цитата сообщения не появляется если окно ответа уже открыто

### ISSUE THREAD

**Issue by yurikoles** [SthephanShinkufag/Dollchan-Extension-Tools#802]
Т.е. нужно сначала закрыть окно, потом ещё раз выделить текст и нажать на номер сообщения, и вот тогда цитата появляется.

**Comment by Y0ba** [comment]
На панели тегов есть кнопка специальная `>`. При нажатии цитируется выделенный текст.

**Comment by yurikoles** [comment]
Ок, нашёл, тогда предложу такую фичу: возможность включить автоматическое цитирование в настройках, выделять каждый раз напрягает.

**Comment by Y0ba** [comment]
Автоматическое цитирование всего поста? Обычно цитирование используют для обращения внимания на определённый участок текста, а для ответа в обзем достаточно просто ссылки с номером поста.
