### ISSUE TITLE
Иногда появляется ненужный прогрессбар под постом.

### ISSUE THREAD

**Issue by yurikoles** [SthephanShinkufag/Dollchan-Extension-Tools#803]
Если его прокрутить, то такая херня: ![херня](http://i.imgur.com/eNq7ush.png)
Chrome beta.

**Comment by Y0ba** [comment]
А без куклы он есть? Да и ссылку бы на пост не мешало.

**Comment by SthephanShinkufag** [comment]
Таки да, ссылочку на тред бы.

**Comment by pwf63158cdnqacom** [comment]
Тоже такое есть, какое-то время не было, сейчас вот опять появилось. При "растягивать посты по ширине экрана" исправляется, и это есть и без скрипта, да. У всех ли?
