### ISSUE TITLE
Drag-and-drop файла для прикрепления не работает

### ISSUE THREAD

**Issue by yurikoles** [SthephanShinkufag/Dollchan-Extension-Tools#805]
Вместо этого происходит открытие файла в этой же вкладке.
Кукла: последний master.
Browser: Chrome 44.0.2403.39 beta (64-bit)/OSX

**Comment by SthephanShinkufag** [comment]
Хм. В моем хроме все работает.
Макопроблемы?
Надо будет вечером проверить на виртуалке.

**Comment by yurikoles** [comment]
В Linux тоже не работает.

**Comment by yurikoles** [comment]
В FSB-уке, и на прочих сайта норм.

**Comment by Y0ba** [comment]
Проблема скорее всего была в отсутствующем `preventDefault` для событий `dragover` и `dragenter` без которого событие `drop` могло не сработать.
