### ISSUE TITLE
А можно ли как-то замутить автообновление из git master?

### ISSUE THREAD

**Issue by yurikoles** [SthephanShinkufag/Dollchan-Extension-Tools#806]
Ну вот допустим у меня Хром, а Степан куда-то пропал, мне теперь вручную обновляться?

**Comment by Y0ba** [comment]
Только если через тамперманки.

**Comment by yurikoles** [comment]
А может скриптик наваять, который расширение собирает и обновляет?

**Comment by Y0ba** [comment]
Лол, я бы и сам обновлял, но скрипт в сторе зареган на степана, а его нету. Тут только если мне самому зарегистрировать аккаунт и выложить в стор копию скрипта.

**Comment by yurikoles** [comment]
Я имею ввиду какой-то CI, я думаю если не корпорация бобра, то кто-нибудь уже точно замутил.
А по поводу тамперманки: это просто пиздец, такой-то UX. Я пользуюсь компьютером уже 12 лет, 4 года пишу софт, но я нихуя не понял как заставить его работать с куклой.

**Comment by yurikoles** [comment]
Хотя нет, это *es6* версия не работает просто в хроме.
