### ISSUE TITLE
Избранное на arhivach.org

### ISSUE THREAD

**Issue by VisualKei** [SthephanShinkufag/Dollchan-Extension-Tools#807]
Ссылка на тред имеет вид `http://arhivach.org/thread/XXX`, ссылка на оппост - `http://arhivach.org/thread/XXX/#YYY`, где `YYY` - оригинальный номер поста на исходной борде. При добавлении треда в избранное скрипта сохраняется некорректная ссылка `http://arhivach.org/thread/YYY`.

Ну и автообновление по дефолту там наверное стоит выключать.

**Comment by YellowSM** [comment]
Да архивач, как я понял, в зачатке. Степан как запилил набросок для него, так им и не занимались

**Comment by VisualKei** [comment]
Сейчас ещё ткнулся - не до конца пофикшено.
Название закладки берётся из тела поста, даже если у поста есть тема (а на оригинальной борде название берётся правильно, из поля темы).
Алсо, хотя ссылка теперь адресуется правильно, полю номера треда в Избранном всё равно присваивается YYY.

**Comment by VisualKei** [comment]
Степан, таки пофикси это тоже, раз за Архивач взялся.
