### ISSUE TITLE
А как импортировать/экспортировать настройки?

### ISSUE THREAD

**Issue by deterenkelt** [SthephanShinkufag/Dollchan-Extension-Tools#810]
Вроде раньше внизу справа была кнопка, а сейчас нет. Заходишь так на какую-нибудь новую борду и правишь опять посты/форму/изображеия. Хочу импортировать из шаблона в один клик!

**Comment by SthephanShinkufag** [comment]
Каков браузер и способ установки скрипта?

**Comment by deterenkelt** [comment]
А, пардон, забыл. FF38 через greasemonkey.

**Comment by SthephanShinkufag** [comment]
И що, у вас нет этих кнопок?

<a href='http://rghost.ru/7mvlNSkgW.view'><img src='http://rghost.ru/7mvlNSkgW/image.png' /></a>

Если нет, запостите содержимое "Инфо" > "Отладка".

**Comment by deterenkelt** [comment]
Вот с последним апдейтом появились. Что это было? (обновлялся с 15.6.10).
А ещё все настройки опять слетели, арргх…

**Comment by SthephanShinkufag** [comment]
Слетели они, тому що, как я подозреваю, ваш скрипт чому-то работал с localStorage. Который как раз и не подразумевает глобальных настроек. Теперь ваш скрипт работает с конфигами GM, естественно, что старые настройки для каждого сайта остались у вас в localStorage.

**Comment by deterenkelt** [comment]
Хм, если я праивльно понимаю, то local storage это dom.storage, тогда #748 ещё актуально?

**Comment by SthephanShinkufag** [comment]
Там у вас были проблемы с sessionStorage, из-за переполнения.
А тут я понятия не имею, чому.
```js
isGM = typeof GM_setValue === "function" && (!chrome || !GM_setValue.toString().includes("not supported"));.
```
Это проверка на поддержку хранилища гризманки. Оно глобальное. Без него не будет и кнопок глобального хранилища.
Видимо, ви хорошенько поковырялись в настройках лисы.

**Comment by deterenkelt** [comment]
Копался, да, но я их как минимум полмесяца не трогал, мамой клянусь.

    $ ls -la ~/.ff/user.js
    -rw-r--r-- 1 dtr dtr 14701 июн 15 20:52 /home/dtr/.ff/user.js

Сам файл вот: http://sprunge.us/CcMK А кнопки пропали не месяц и не два назад.

**Comment by Bfgeshka** [comment]
А что насчёт бэкапа в файл?

**Comment by SthephanShinkufag** [comment]
Хм. Спасибо, что напомнили.
