### ISSUE TITLE
Скрипт не работает в последнем TorBrowser 4.5.2

### ISSUE THREAD

**Issue by YellowSM** [SthephanShinkufag/Dollchan-Extension-Tools#811]
Кукла не запускается ни на одной борде.
TB 4.5.2 (based on Mozilla Firefox 31.7.0)
GM 2.3.1

Консоль:
regeneratorRuntime is undefined Dollchan_Extension_Tools.user.js:1754

**Comment by SthephanShinkufag** [comment]
Баг, видимо, устарел.

TB 6.5, GM 3.9
Кукла работает.
