### ISSUE TITLE
На KC отвалилась корректировака времени

### ISSUE THREAD

**Issue by deterenkelt** [SthephanShinkufag/Dollchan-Extension-Tools#812]
Ставлю галку, сдвиг на -2, Find и Replace паттерны в соответствии с /wiki/Settings-time-en. Дробные доли секунды добавляются, но время не корректируется. После перезапуска браузера галка слетет.
FF 38, DE 15.7.4, GM 3.2.

**Comment by SthephanShinkufag** [comment]
Может, +2, а не -2?
Вы же из Москвы, вестимо.
Может, я вас не правильно понял, но у меня все работает.
Ставлю +1, киевское время, все получается.

**Comment by deterenkelt** [comment]
Да, да, это я не от гринвича, а от ДС часы считал, как и полагается москвичу, ага.
