### ISSUE TITLE
АНОНЧИК, МОЛЮ.

### ISSUE THREAD

**Issue by apan65** [SthephanShinkufag/Dollchan-Extension-Tools#813]
Добавь уже запомнание скролла в избранных тредах при открытии нового окна. Самый простой вариант - при открытии треда из избранного, страница пролистывается до номера последнего запомненного поста(к ссылке добавлять #xxxxxxxx)

**Comment by SthephanShinkufag** [comment]
Зойпилил.

**Comment by apan65** [comment]
НУ НАКАНЕЦТА!

**Comment by SthephanShinkufag** [comment]
Ога.

**Comment by apan65** [comment]
Последний пост не обновляется, то есть, как висел вначале #aaaaaaaa, так и висит вконце после закрытия треда  #aaaaaaaa.  Это баг?

**Comment by SthephanShinkufag** [comment]
Пробуйте.

**Comment by apan65** [comment]
Теперь идеально. Спасибо за фичу!

**Comment by apan65** [comment]
Хотя иногда не запоминает почему-то.

**Comment by SthephanShinkufag** [comment]
Теперь точно всё.

**Comment by apan65** [comment]
Супер. Кстати, можешь добавить пункт в настройки, чтобы загружались автоматом страницы, а не только по нажатию F5(в опциях "Количество страниц, загружаемых по F5")

**Comment by SthephanShinkufag** [comment]
> загружались автоматом страницы

Подробнее, не совсем понимаю. Автоматическое обновление нулевой по таймеру? Как тогда серфить треды нулевой, если она вас будет постоянно кидать?

Можете оформить новый issue.
Этот реквест закрыт.

**Comment by apan65** [comment]
Да ладно, f5 нажимать не лень, еще раз спасибо. Укатился.
