### ISSUE TITLE
Реквест: Авторефреш капчи

### ISSUE THREAD

**Issue by YellowSM** [SthephanShinkufag/Dollchan-Extension-Tools#815]
Уже где-то просил, но так и не реализовали.
Суть: капча, после некоторого прибывания в ридонли, протухает. И, соответственно, после отправки поста с протухшей капчей выдается ошибка, что она не валидна. Ладно еще когда просто пост отправляешь, а когда аттач загружается минуту, а потом такой облом - мягко говоря негодуешь.
 Просить криворуких обезьян, чтобы проверяли капчу до отправки - бесполезно.
Предлагаю ввести в настройках куклы опцию - Автообновление капчи (чекбокс + время до протухания).
Принцип работы вижу такой: запускается таймер с прошлого поста и при каждом вызове формы поста (или при активации фокуса в полях ввода - так стабильнее), проверять этот таймер. Если он превышает заданное в настройках значение, принудительно рефрешить капчу.
По умолчанию эту фичу можно выключить. Остальные настроят сами под каждую борду.

**Comment by SthephanShinkufag** [comment]
Реализовано в последних коммитах. Таймер равен 5 мин.
