### ISSUE TITLE
[FR]Возможность выключить звук

### ISSUE THREAD

**Issue by yurikoles** [SthephanShinkufag/Dollchan-Extension-Tools#816]
Глобально по борде и/или по треду. Бывает слушаешь ты музыку, а в соседней вкладке двачуешь в webm-thread, а там кареянки что-то кукарекают или ещё что.

**Comment by yurikoles** [comment]
Было бы ещё лучше, если бы можно было отрегулировать громкость. Технически я это вижу как устанавку громкости перед стартом воспроизведения web-m.

**Comment by Y0ba** [comment]
Так и сейчас можно же. В настройках. Только надо синхронизацию между вкладками сделать.

**Comment by yurikoles** [comment]
Что-то я не нашёл, пруф?

**Comment by Y0ba** [comment]
![screenshot_20150714153551](https://cloud.githubusercontent.com/assets/1163958/8673309/109dafbc-2a3e-11e5-9aea-67a20f7a5981.png)

**Comment by Y0ba** [comment]
Наверное надо картинки переименовать во что-то другое.

**Comment by yurikoles** [comment]
А синхронизация?

**Comment by Y0ba** [comment]
Сегодня сделаю.

**Comment by yurikoles** [comment]
И ещё: страницу перезагружать нужно чтобы настройки громкости применить.

**Comment by Y0ba** [comment]
Не. Достаточно закрыть и открыть webm-файл. Это тоже исправлю.

**Comment by yurikoles** [comment]
Иншааллах, бро.

**Comment by Y0ba** [comment]
Во всех webm он уже есть (справа внизу) если включены контролы. Скрипт их тоже сохраняет и синхронихирует (в пределах борды).
