### ISSUE TITLE
8chan no captcha showing up

### ISSUE THREAD

**Issue by b4n4n4** [SthephanShinkufag/Dollchan-Extension-Tools#825]
In boards such as http://8ch.net/furry/ there is no captcha showing up while replying to a thread, and because of that you can't post. Firefox 36.0.4 and latest dollchan installed.
![dollchan](https://cloud.githubusercontent.com/assets/7440318/8914478/e4876a64-349f-11e5-8e4b-811360d751f7.png)
![no dollchan](https://cloud.githubusercontent.com/assets/7440318/8914479/e695aabe-349f-11e5-9e01-5409696a3399.png)

**Comment by b4n4n4** [comment]
I just tested it on clean firefox 36.0.4 and it has the same problem. In Chrome the captcha works.

**Comment by SthephanShinkufag** [comment]
Solved in last commits.
