### ISSUE TITLE
Бесконечная прокрутка на макабе.

### ISSUE THREAD

**Issue by xzyxzy** [SthephanShinkufag/Dollchan-Extension-Tools#827]
Как в феврале об этом ты думал, так ничего и не поменялось.
Почини пожалуйста.

**Comment by SthephanShinkufag** [comment]
Бесконечная прокрутка макаки не совместима со скриптом.
Установите последний билд скрипта, там принудительно отключается эта опция.

https://raw.github.com/SthephanShinkufag/Dollchan-Extension-Tools/master/Dollchan_Extension_Tools.user.js

**Comment by xzyxzy** [comment]
Я об этом:
https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/issues/762
Просьба именно приделать её обратно.

**Comment by Y0ba** [comment]
9a6065a23a74437efbf3e0dce1ada26d67f4ce9a
