### ISSUE TITLE
Баги с редактированием постов на ponychan.ru

### ISSUE THREAD

**Issue by insciq** [SthephanShinkufag/Dollchan-Extension-Tools#828]
После удачного редактирования поста (нажать на треугольник в посте -> редактировать) появляются такие проблемы:
1. С поста который был отредактирован сбрасывается рефмап (в том случае если нет ошибки при постинге, которая описывается ниже)
2. Посты которые были выше приходят как новые (неизвестно как точно воспроизвести, обычно проявляется в активном треде спустя несколько минут после редактирования)
3. Если был отредактирован ОП пост, то в тред нельзя запостить без ошибки спустя некоторое время (которую отдаёт куклоскрипт) [Ссылка на тред](https://ponyach.ru/dollchan/res/1.html)
Как это выглядит: 
Встроенный доллчан 
![e31090e4b9e59958fb857873e0f8a7bb1](https://cloud.githubusercontent.com/assets/7069863/9026217/df8df20a-392f-11e5-9e97-1f564e8812dd.png)
Внешний (юзерскрипт)
![7cf342138e1a433f0bcfe9df3897e2ef](https://cloud.githubusercontent.com/assets/7069863/9026270/f1020d1c-3931-11e5-9784-0cbb0bfebeb1.png)

3.1. Все приходящие посты приходят в 1 строку и липнут друг к другу как на картинке (если был отредактирован ОП пост. Очень редкое такое случалось и во время редактирования обычных постов)
![b67e0b71f8db62949a690d1292c7d5e33](https://cloud.githubusercontent.com/assets/7069863/9026200/7e7fc5e2-392f-11e5-8577-1d094bd74daa.png)

Всё тестировалось на встроенном и на внешнем скриптах последних версий.

**Comment by ninja-pirate** [comment]
> 2. Посты которые были выше приходят как новые (неизвестно как точно воспроизвести, обычно проявляется в активном треде спустя несколько минут после редактирования)

в том смысле, что посты приходят по второму разу. мы видели такое в активных тредах, где много постов, но как воспроизводить не понятно.
