### ISSUE TITLE
Карта ответов под оп постами исчезла на сосаче

### ISSUE THREAD

**Issue by liderzisd** [SthephanShinkufag/Dollchan-Extension-Tools#829]
Исчезла после блокировочки, то есть совсем недавно. Такое происходит в независимости от раздела/домена. Куклоскрипт последний: v15.7.2.0. Браузер обычный огнелис: 39. На хроме та же фигня, причём заметно что она порой отображается пол секунды и исчезает. Это у меня одного что то сломалось?

**Comment by Y0ba** [comment]
Уже давно исправил в da8d5f9e56ed51bfc5ed5fe7e2dcd8e139599a3c

Обнови по ссылке: https://raw.github.com/SthephanShinkufag/Dollchan-Extension-Tools/master/Dollchan_Extension_Tools.user.js
