### ISSUE TITLE
Formatting rules on 4chan

### ISSUE THREAD

**Issue by dicksdicks** [SthephanShinkufag/Dollchan-Extension-Tools#832]
Можно как-нибудь прикрутить возможность спрятать кнопку спойлера на досках, на которых спойлеры не работают?

**Comment by SthephanShinkufag** [comment]
Как узнать, есть ли на доске спойлеры?

**Comment by dicksdicks2** [comment]
Проверить наличие чекбокса для спойлера изображений, что скрипт уже делать умеет. Нет чекбокса — какие-либо спойлеры не работают вовсе.
