### ISSUE TITLE
Ресайз раскрываемых по месту картинок

### ISSUE THREAD

**Issue by VisualKei** [SthephanShinkufag/Dollchan-Extension-Tools#833]
После 3c3f0079018ae3bb7af50433658040feb09acf87 требующие уменьшения картинки стали справа вылезать за границы контейнера.
Например, в [попапах](http://rghost.net/private/6cXcybzKM/df7f5cd02808dbf74332fabce2f47675), в постах аналогично.

Алсо, это стало происходить как-то странно в два этапа - сначала границы контейнера увеличиваются до размера какого-то непонятного плейсхолдера, а потом после загрузки картинки увеличиваются ещё раз до итогового размера.

**Comment by Y0ba** [comment]
Вроде как проблема не в этом коммите. Проблема с реализацией кэша отступов постов, который использовался и в попапах, хотя для каждого попапа он должен высчитываться каждый раз заного. Пробуй.

**Comment by VisualKei** [comment]
Нет изменений по обоим пунктам. По второму пункту заметил, что так бывает только при необходимости даунскейла раскрываемой картинки.

**Comment by VisualKei** [comment]
Похоже понял, откуда размер этого пустого плейсхолдера берётся. Далее пишу только про то, что происходит на страницах, в попап-превью так подробно не вникал.

На однокартиночных досках (ичан, 4чан, nowere.net) плейсхолдер соответствует размеру, до которого бы уменьшилась картинка в исходную ширину поста. Потом пост расширяется вправо до упора, и только тогда уменьшенная уже "по-новому" картинка начинает грузиться. Если посты изначально имеют ширину во весь вьюпорт, как на вакачане или же оппосты, то ресайзится сразу, без отображения плейсхолдера.

На многокартиночных досках (краут, сосач, добрач) плейсхолдер соответствует размеру,  до которого бы уменьшилась картинка в ширину контейнера тамбнейла, но как если бы самого тамбнейла не было. Иначе говоря это та ширина контейнера, которая задавалась бы только находящимися в нём же инфой о файле, кнопками и т.п. (потому на добраче плейсхолдер вообще в самый минимум уходит). То есть размер плейсхолдера получается даже меньше исходного тамбнейла.

Ну и из всех вышеупомянутых досок правые края итоговых уменьшенных картинок кривые на однокартиночных и нормальные на многокартиночных. С этой точки зрения плейсхолдеры ведут себя аналогично.

@Y0ba, разберись плиз с этим поскорее. Края ещё ладно, но постоянная дерготня с плейсхолдерами уже заманала. Но что хорошо в новом алгоритме - в попап-превью исчезли странные нестабильные ресайзы картинок за пределы вьюпорта, о которых я как-то говорил в треде (когда одна и та же картинка сначала ресайзилась нормально, а через некоторое время рефрешей треда/доски скриптом начинала распидорашиваться).

**Comment by SthephanShinkufag** [comment]
Что вы имеете в виду под плейсхолдером? Ничего не понял из текста.

**Comment by VisualKei** [comment]
![snap1](https://cloud.githubusercontent.com/assets/1483359/9836577/6505e614-5a27-11e5-8ff7-f38fbeb24ba9.png)

**Comment by VisualKei** [comment]
@Y0ba, займись же этой хренью пожалуйста.

**Comment by Y0ba** [comment]
Просто я немножко дурак и не понимаю о чём речь. Можешь снять видео с экрана с багом? И если используешь кастомный CSS, тоже выложи.

Просто я наблюдал подобное с Youtube-видео (и это действительно надо починить), но с изображениями - никогда.

**Comment by VisualKei** [comment]
Возможно у тебя быстрый комп и потому не успеваешь увидеть. Попробуй отрубить инет и нажать на картинку - у меня тогда этот плейсхолдер дольше виден. Но суть такова же: после клика на картинку сначала отображается вышеаттаченная хренота, и только потом конечный результат.

Кастомного CSS никакого нет. Видео с экрана никогда раньше не делал, это надо будет заморочиться, тогда позже. Чем его сделать проще всего?

**Comment by VisualKei** [comment]
Класс, спасибо, эта проблема наконец решена!

Но есть косметическая мелочь - на однокартиночных досках картинки раскрываются не на всю возможную ширину вьюпорта, справа остаётся некоторое пустое место и результат выглядит несимметрично. Можно это пофиксить?

**Comment by Y0ba** [comment]
На таких бордах как `2ch.hk` - нет. Тогда будет появляться скролл. На остальных детектить довольно сложно, потому не знаю.

**Comment by Y0ba** [comment]
А нет, тут даже на `2ch.hk` может быть проблема. Всё дело в `>>` перед постами. Если их скрыть CSS, то картинки разворачиваются нормально.

**Comment by VisualKei** [comment]
На сосаче как раз норм (и на крауте), а вот на ичане и 4чане - нет.

**Comment by VisualKei** [comment]
Раньше же как-то детектилось? Вот то что было до упомянутой в оппосте правки выглядело идеально. Посмотри плиз что можно сделать.

**Comment by Y0ba** [comment]
Раньше никак не детектилось. Просто изображения переносились на новую строку в некоторых бордах. Сейчас захотел исправить это и вылезло другое.

**Comment by VisualKei** [comment]
На мультикартиночных есть другая проблема. Я так понимаю что ширина, до которой ресайзить, определяется от левого края контейнера до конца, и если раскрывать не первую картинку из нескольких, то она переносится на новую строку, но её ширина получается как если бы она оставалась на том же месте, то есть меньше возможной.

**Comment by VisualKei** [comment]
Кстати попробовал на ичане скрыть `.doubledash` - чё-то нихрена, всё равно справа много пустоты.

**Comment by Y0ba** [comment]
Проблема в том, что у превью на ычане (може ещё где) есть маргины. У развёрнутых картинок их нет и при этом они не учитываюся.

**Comment by VisualKei** [comment]
Кстати не совсем понял про что это
>Просто изображения переносились на новую строку в некоторых бордах

Это разве плохо? Вроде так и должно быть, чтобы картинки были максимальны по ширине, но без распидорашивания вьюпорта. Имхо не в попап-превью надо отталкиваться только от ширины вьюпорта с учётом паддинга `<body>` и границ/паддинга у постов (плюс >>) если они есть, но тут я конечно слабо представляю, как это всё на многих бордах устроено.

**Comment by Y0ba** [comment]
Это не плохо. Плохо то, что даже после переноса картинка не разворачивалась на весь вьюпорт  и это я и исправил тем коммитом. А так, можно добавить и принудительный перенос картинок на новую строку.

Алсо скрипт теперь учитывает маргины (только если они указаны в пикселях, что вроде так везде) и расстояние от поста до левого края.

**Comment by VisualKei** [comment]
На ичане теперь хорошо, на 4чане - всё ещё нет. Алсо на крауте крайняя левая картинка теперь распидорашивает вьюпорт. Ну и наверное на мультикартиночных всё же надо устроить принудительный перенос картинок начиная со второй, если они шире оставшегося справа места.

**Comment by VisualKei** [comment]
Кстати на ичане на доске если у второго поста поле оппоста (который из-за этого сдвинут вправо) есть большая картинка, теперь тот же эффект, как на мультикартиночных - пост переносится, но ширина как была бы на старом месте. Ну это в принципе мелочь, если попутно удастся починить - хорошо, а так ладно.

**Comment by VisualKei** [comment]
Хотя так не только на доске же, в тредах тоже может быть. Наверное в этих случаях тоже надо принудительно переносить и считать уже так.
