### ISSUE TITLE
Автохайд главной панели

### ISSUE THREAD

**Issue by VisualKei** [SthephanShinkufag/Dollchan-Extension-Tools#834]
Сабж не происходит, если закрывать окна по кнопке в заголовке.

Алсо, если открыть окно хоткеем, навести мышь на открытую главную панель и потом увести - панель сворачивается, хотя не должна, пока  окно остаётся открытым. Такого не происходит, если открывать окна мышью. Если первое окно открыть мышью, а потом переключиться хоткеем на другое - тоже всё нормально.

**Comment by SthephanShinkufag** [comment]
1d0878de6c500e0719988d9c749692642da64b30
