### ISSUE TITLE
Выбор капчи на форчане

### ISSUE THREAD

**Issue by e6opoteh** [SthephanShinkufag/Dollchan-Extension-Tools#839]
На форчане не работает его родная форма быстрого ответа.
Со включенным скриптом ее вызвать вообще никак нереально, ни по клавише R (когда включены горячие клавиши в самом скрипте), ни по клавише Q (когда они включены в настройках форчана).
В стандартной форме (не в быстром ответе) гребаная гуглокапча с бургерами, поэтому хотелось бы использовать квикреплай (в котором капча человеческая, с цифрами).

**Comment by SthephanShinkufag** [comment]
> родная форма быстрого ответа

Сожалею, но это невозможно. Куклоскрипт глушит родные скрипты форчана.
А вот возможность выбора капчи я посмотрю.

**Comment by SthephanShinkufag** [comment]
0532140ba35cf48e2abfd786f7e49c645ead2849
