### ISSUE TITLE
Даблпост

### ISSUE THREAD

**Issue by deterenkelt** [SthephanShinkufag/Dollchan-Extension-Tools#843]
Можно как-то убрать «досылатель» сообщения, если оно не отправилось? А то срабатывает через раз, а когда срабатывает, я уже отправил этот пост руками две минуты назад, получился даблпост.

**Comment by Y0ba** [comment]
Это не досылатель, а глюки сервера. Т.е. сервер принял сообщение, но ответил ошибкой. Скрипт тебе показывает ошибку и тебе кажется, что сообщение не отправилось и ты отправляешь его повторно. Потом сервер приходит в себя и обрабатывает оба сообщения. Вот и все.

**Comment by deterenkelt** [comment]
Так нарисуйте пост призрачным или ещё как, чтоб я видел, что не надо отправлять его ещё раз.

**Comment by Y0ba** [comment]
Так невозможно же отличить глюки сервера от реальной ошибки. Просто если увидишь ошибку 5XX при отправке подожди немного перед второй попыткой.

**Comment by deterenkelt** [comment]
Тайхен.
