### ISSUE TITLE
[8ch.net]: Удаление постов, фильтр по ID

### ISSUE THREAD

**Issue by Vesper-** [SthephanShinkufag/Dollchan-Extension-Tools#844]
На 8чане по дефолту слева от имени треугольник с выползающим меню, где можно удалить пост и отфильтровать по ID:
http://a.pomf.cat/ycdjhe.png
Куклоскрипт заменяет это на чекбокс, но в отличие от ычана, на 8чане нет опции удалить пост внизу страницы.
http://a.pomf.cat/drmntm.png
Можно ли убрать убрать замену на чекбокс и оставить дефолтный треугольник? Или где-то на хейтчане есть/спрятана опция удаления поста?

p.s. спасибо за скрипт :3

**Comment by SthephanShinkufag** [comment]
8ch.net is dead
