### ISSUE TITLE
Новая капча на харкаче

### ISSUE THREAD

**Issue by YellowSM** [SthephanShinkufag/Dollchan-Extension-Tools#846]
Макака опять капчу поменяла. В кукле не отображается.

**Comment by SthephanShinkufag** [comment]
Так им и надо.

**Comment by SthephanShinkufag** [comment]
Ліл. И без капчи все отправляется. *Только выиграли.*

**Comment by YellowSM** [comment]
А у меня пишет капча невалидна.
А макакиной формой если отправлять, грузится его капчоуебище на пол-формы, а после отправки вываливается страница с json ответом.
Трындец короче

**Comment by Y0ba** [comment]
Пока что капча нужна только для создания тредов. Кукла её пережёвывала нормально, только почему-то новую капчу скрывала.

**Comment by Y0ba** [comment]
Посмотрим надолго ли хватит. Если нет капчи, значит вводить её не нужно.
