### ISSUE TITLE
Капча на 2ch.hk

### ISSUE THREAD

**Issue by pwf63158cdnqacom** [SthephanShinkufag/Dollchan-Extension-Tools#847]
Обезьяна снова включила капчу, теперь она не отображается в форме постинга.

%%Да еще и мои любимые апельсины выключил.%%

**Comment by Y0ba** [comment]
Какая версия скрипта и способ установки (расширение gs)? Капча уже исправлена в master-ветке и, кстати, требуется только для создания тредов.

**Comment by pwf63158cdnqacom** [comment]
Скрипт через темперманки в хроме, самая последняя версия 15.8.27.0, и нет, для отправки обычных постов уже тоже требуется.

**Comment by Y0ba** [comment]
Попробуй обновить отсюда: https://raw.github.com/SthephanShinkufag/Dollchan-Extension-Tools/master/Dollchan_Extension_Tools.user.js

**Comment by pwf63158cdnqacom** [comment]
Ну там же версия точно такая. Вот только сейчас заметил включенный зенмейт, и это он внезапно был причиной включенной капчи. 
Но все равно настроить её отображение нужно же.

**Comment by Y0ba** [comment]
Версия обновляется редко и зачастую по желанию левой пятки степана. Ты на номер коммита смотри, откуда скрипт взят
