### ISSUE TITLE
"Ошибка подключения" и состояние автообновления

### ISSUE THREAD

**Issue by VisualKei** [SthephanShinkufag/Dollchan-Extension-Tools#849]
Если происходит сабж при постинге и он не проходит, то состояние обновления начинает крутиться без конца, а глаз в панели становится красным и на нажатия не реагирует. Раньше это можно было пофиксить кликом на глаз два раза и вновь включить автообновление, а теперь приходится страницу рефрешить. @Y0ba, пофикси плиз - это после каких-то недавних изменений так стало, сейчас точнее не могу найти.

**Comment by VisualKei** [comment]
А, вроде после [этого](https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/commit/d4fe2de30f1be04dc739c20af41da73491987fe9#diff-3ffdccae365c029e209bbfa4211be3e6L1737) стал замечать.

**Comment by SthephanShinkufag** [comment]
Тоже заметил, что кнопка с глазом на панели стала вести себя странно. Пока закономерностей не уловил. Я часто отключаю апдейтер в тредах, и стал замечать, что кнопка иногда перестает реагировать на клик. В консоли ошибок пусто.

**Comment by Y0ba** [comment]
@SthephanShinkufag можешь добавить `console.log(focusLoadTime, paused, enabled, disabledByUser, lastECode, sendError, newPosts);` в методы `enable` и `disable` возвращаемого объекта из `initThreadUpdater` и посмотреть что они пишут когда кнопка с глазом не работает?

**Comment by Y0ba** [comment]
> `console.log(focusLoadTime, paused, enabled, disabledByUser, lastECode, sendError, newPosts);`

Лучше даже `console.log(focusLoadTime, paused, enabled, disabledByUser, lastECode, sendError, newPosts, audio, counter, favicon, notification, updMachine);`

Правда последние объекты надо развернуть, чтобы увидеть их содержимое.

**Comment by SthephanShinkufag** [comment]
Добился гарантированного бага. Вставленный код (ES6):

```js
function initThreadUpdater(title, enableUpdate) {
	...
	return {
		enable() {
			console.log(focusLoadTime, paused, enabled, disabledByUser, lastECode, sendError, newPosts, audio, counter, favicon, notification, updMachine);
			if(!enabled) {
				enableUpdater();
				updMachine.start();
			}
		},
		disable() {
			console.log(focusLoadTime, paused, enabled, disabledByUser, lastECode, sendError, newPosts, audio, counter, favicon, notification, updMachine);
			disabledByUser = true;
			disableUpdater()
		},
		forceLoad(e) {
```

1. Firefox Nightly. Ычан. Твой последний коммит. Апдейтер в настройках включен. Открываю любой тред. 
2. Отключаю глаз. Он становится красным. Консоль:

```
0 false true false 200 false 0 Object { enabled: false, repeatMS: 0, disable: disable(), play: play(), stop: stop(), _el: _el() } Object { enable: enable(), disable: disable(), count: count(), setWait: setWait(), _countingIV: 4, _countingTO: null, _enabled: true, _el: <span#de-updater-count>, _set: _set(), _stop: _stop() } Object { canBlink: Getter, originalIcon: Getter, startBlinkEmpty: startBlinkEmpty(), startBlinkError: startBlinkError(), stopBlink: stopBlink(), _blinkInterval: null, _blinkMS: 800, _currentIcon: null, _emptyIcon: "data:image/x-icon;base64,iVBORw0KGg…", _errorIcon: "data:image/x-icon;base64,iVBORw0KGg…", 4 more… } Object { canShow: Getter, checkPermission: checkPermission(), show: show(), close: close(), _granted: true, _closeTO: null, _notifEl: null, _requestPermission: _requestPermission() } Object { start: start(), stop: stop(), _delay: 180000, _initDelay: 180000, _loadPromise: null, _loadOnce: false, _seconds: 0, _state: 1, _panelButton: Getter, _handleNewPosts: _handleNewPosts(), 2 more… }
```
3. Кликаю по кнопке `[Получить новые посты]`. Апдейтер включается, глаз становится зеленым.
4. Кликаю по глазу, он так остается зеленым, хотя должен отключиться. Консоль:

```
0 false false true 200 false 0 Object { enabled: false, repeatMS: 0, disable: disable(), play: play(), stop: stop(), _el: _el() } Object { enable: enable(), disable: disable(), count: count(), setWait: setWait(), _countingIV: null, _countingTO: null, _enabled: false, _el: <span#de-updater-count>, _set: _set(), _stop: _stop() } Object { canBlink: Getter, originalIcon: Getter, startBlinkEmpty: startBlinkEmpty(), startBlinkError: startBlinkError(), stopBlink: stopBlink(), _blinkInterval: null, _blinkMS: 800, _currentIcon: null, _emptyIcon: "data:image/x-icon;base64,iVBORw0KGg…", _errorIcon: "data:image/x-icon;base64,iVBORw0KGg…", 4 more… } Object { canShow: Getter, checkPermission: checkPermission(), show: show(), close: close(), _granted: true, _closeTO: null, _notifEl: null, _requestPermission: _requestPermission() } Object { start: start(), stop: stop(), _delay: 180000, _initDelay: 180000, _loadPromise: null, _loadOnce: true, _seconds: 0, _state: -1, _panelButton: <a#de-panel-upd-on.de-abtn.de-panel-button>, _handleNewPosts: _handleNewPosts(), 2 more… }
```

**Comment by SthephanShinkufag** [comment]
>2 more…
4 more...

Не дает скопировать. Если надо, могу дать скриншоты.

**Comment by Y0ba** [comment]
Не. Я уже понял в чём дело.

**Comment by SthephanShinkufag** [comment]
Да, я забыл сказать, что при клике на `[Получить новые посты]` апдейтер не должен включаться. Ты догадался.

**Comment by SthephanShinkufag** [comment]
Вроде все норм. Посмотрим, что скажет *VisualKei*.

**Comment by Y0ba** [comment]
@SthephanShinkufag можно, кстати, поставить таймаут на загрузку постов. Если по прошествии определённого времени посты не загрузятся, скрипт будет пытаться загрузить ещё раз но сбросив соединение. Можно сделать таймаут динамическим, например изначально ставить значение равное времени последней успешной загрузки умноженное на два (чтобы избежать сброса загрузки при нормальном, но медленном соединении).

**Comment by VisualKei** [comment]
Да, теперь глаз работает как раньше, можно передёргивать зависоны. Таймаут для этого - хорошая идея. У меня это всё в основном когда через прокси постишь, с ними часто всякая хрень с соединениями происходит.
