### ISSUE TITLE
4chan: отсутствует поле в форме

### ISSUE THREAD

**Issue by deterenkelt** [SthephanShinkufag/Dollchan-Extension-Tools#851]
Для скрытия изображений под спойлер.

![1445563685](https://cloud.githubusercontent.com/assets/2245254/10682443/91e6e99a-793e-11e5-859b-a2fc5646c5a1.png)

**Comment by SthephanShinkufag** [comment]
<a href='http://rghost.ru/8mXgW64Wf.view'><img src='http://rghost.ru/8mXgW64Wf/image.png' /></a>

**Comment by deterenkelt** [comment]
Что-то я его там не заметил. Зачем вообще прятать эти кнопки, когда есть изображение? Дальше же условий нет, есть картинка — должны быть кнопки.

**Comment by SthephanShinkufag** [comment]
Некоторым они мешают, был реквест в Issues.

**Comment by deterenkelt** [comment]
А можно поле анчекать после отправки? Нафиг оно остаётся?
