### ISSUE TITLE
Раскрытие картинок в новом окне при настройке "раскрытие в посте" на 8ch.net

### ISSUE THREAD

**Issue by Colesad** [SthephanShinkufag/Dollchan-Extension-Tools#855]
Раскрытие картинок на 8ch.net всегда происходит в новом окне, не смотря на указанные настройки, т.е. "раскрытие в посте".

**Comment by SthephanShinkufag** [comment]
У меня все работает.
Скачали последнй скрипт по ссылке?
https://raw.github.com/SthephanShinkufag/Dollchan-Extension-Tools/master/Dollchan_Extension_Tools.user.js

Что за браузер? Что за настройки? Что пишет в консоли ошибок при клике на картинку?
