### ISSUE TITLE
Кнопки панели (косметика)

### ISSUE THREAD

**Issue by VisualKei** [SthephanShinkufag/Dollchan-Extension-Tools#856]
У кнопки настроек стоит сделать внутреннее кольцо чуть потолще.
У зрачка глаза слева вверху возле белой линии есть какой-то непрокрашиваемый участок цвета фона - он там явно не нужен.

Ну и думаю то, что svg- и gif-кнопки выровнены по вертикали чуть по-разному это временно до перерисовки остальных кнопок, но пока наверное всё же стоит сместить svg-кнопки на 1px вниз.

**Comment by Y0ba** [comment]
> У зрачка глаза слева вверху возле белой линии есть какой-то непрокрашиваемый участок цвета 

Это типа блик. Был в оригинальной иконке и я его оставил.

**Comment by VisualKei** [comment]
Не знаю, в оригинальной я его что-то вообще не разгляжу, но по-моему теперь это очень криво смотрится, тем более какой блик, если он прозрачный.

**Comment by VisualKei** [comment]
Если уж оригинальную повторять, то тогда стоит сделать глаз поменьше и нарисовать реснички, а то сейчас оно как-то криповато выглядит, особенно пустота между "зрачком" и "нижним веком".

**Comment by Y0ba** [comment]
Под *оригинальным* я имел в виду вот это: https://commons.wikimedia.org/wiki/File:Eye_open_font_awesome.svg

Честно говоря, мне так даже нравится. Такой-то взгляд, лол.

**Comment by VisualKei** [comment]
А. Однако там чисто монохром и большой размер, так оно вполне ничего смотрится. А когда добавляется второй (причём яркий) цвет и это сжимается до такого размера, вся задумка теряется и начинает восприниматься просто как косяк рисовщика.

**Comment by Y0ba** [comment]
Такой-то косяк на чистом круге сложно будет сделать не нарочно :grinning:

**Comment by VisualKei** [comment]
Умом-то это понятно, я естественно так и не думал, но впечатление создаётся именно такое. И дело тут именно в цвете зрачка - та монохромная иконка как фавикон смотрится вполне нормально.

**Comment by Y0ba** [comment]
Щас дорисую брови и обновлю.

**Comment by Y0ba** [comment]
Ой, ресницы, то есть.

**Comment by VisualKei** [comment]
А чего вы кнопку Избранного в вектор не переводите, векторная звёздочка уже есть же в кнопках постов и рисовать не надо? А то сейчас такая хрень с растровыми кнопками есть: закрываешь Избранное кликом по панели, она автохайдится, и если её опять раскрыть хоткеем, чтобы мышь на неё не попадала, то можно увидеть неубранный хайлайт кнопки Избранного с прошлого раза. Почему-то так происходит только с растровыми кнопками (например Видео), а с векторными (Скрытое) всё нормально.

**Comment by SthephanShinkufag** [comment]
Йобе лень.
А мне эта затея с векторами что-то все меньше нравится, например.

**Comment by VisualKei** [comment]
Ну в общем да, как-то странно это всё. Например ещё такую проблему обнаружил - если навести мышь на кнопку, у которой есть меню (Обновить на доске, Скачать, Звуковое оповещение), чтобы оно появилось, а потом перевести мышь на любую соседнюю кнопку, то вся панель скрывается. А если просто елозить мышью в пределах кнопки Звук, то меню появляется/исчезает, а иногда панель тоже скрывается. С растровой кнопкой Обновить на доске такого не происходит.

**Comment by Y0ba** [comment]
> Например ещё такую проблему обнаружил

Исправил.

**Comment by SthephanShinkufag** [comment]
Бля. Тоже не до конца. Показалось, что работает.

**Comment by Y0ba** [comment]
Я уже почти исправил.

**Comment by SthephanShinkufag** [comment]
А, ну заливай.

**Comment by Y0ba** [comment]
@SthephanShinkufag сделал.

**Comment by VisualKei** [comment]
Предложения по поводу стрелок:

1. В тултипах к "горизонтальным" имхо стоит навести порядок: сейчас там "Назад" и "Следующая" - неединообразно и неоднозначно. Лучше "Предыдущая/Следующая страница", как у стрелок для картинок, а в тредах - "На доску". Ну или хотя бы "Назад/Вперёд", если отдельно обрабатывать влом. А высший пилотаж - на доске сделать "Страница N" и соответственно динамически менять N. Особо полезно для случаев загрузки >1 страницы - можно увидеть, на какую страницу будет переход.

2. В тултипах к "вертикальным" аналогично "Наверх/В конец" неединообразно. Алсо, сейчас особой пользы от этих кнопок нет, с клавиатуры явно быстрее и привычнее, потому предлагаю расширить их функционал. На доске в случаях, когда загружено >1 страницы, переходить ими в пределах именно этих страниц, а не всего вьюпорта,  чтобы можно было жать их несколько раз до упора. А то визуальное выделение отдельных загруженных страниц есть, а способа быстрой прокрутки именно между ними нет. В тредах при желании тоже можно что-нибудь сделать - например "промежуточный" переход к выделенному красным посту, а потом уже в начало/конец.

**Comment by SthephanShinkufag** [comment]
@VisualKei 

> В тултипах к "горизонтальным" имхо стоит навести порядок

8054149368a33829c2f2f7a15f3fc94da5b33e7e

**Comment by VisualKei** [comment]
>закрываешь Избранное кликом по его кнопке на панели, не двигая мышь, панель автохайдится, потом её раскрываешь - иногда можно увидеть неубранный хайлайт

Оказалось, это не связано с растром или вектором - до сих пор есть. Не пойму от чего зависит: на Избранном бывает практически всегда, несколько раз встречалось на Настройках, на Скрытом получить не удалось. Возможно, с размером окна и его анимацией? Предполагаю, на мощном компе может и вообще не быть, но можно как-то попробовать пофиксить?

**Comment by Y0ba** [comment]
Это проблема в лисе. Проблема в том, что лиса не посылает `mouseout` там где нужно, потому `:hover`-эффект не убирается. В скрипте даже есть костыль для превью, который синтезирует и посылает `mouseout` сам, лол: https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/blob/8ddfc365179eae76bdde9c788d6ec6d4617cd318/src/Dollchan_Extension_Tools.es6.user.js#L8454

Правда сейчас он используется уже и не как костыль, а как часть нормального функционала, в том числе для хрома и оперы, но создавался как лисокостыль.
