### ISSUE TITLE
Красная рамка у постов

### ISSUE THREAD

**Issue by pwf63158cdnqacom** [SthephanShinkufag/Dollchan-Extension-Tools#857]
При клике на ссылку поста (http://puu.sh/l85r8/2e3de42ea5.png) он выделяется затемнением фона (это можно отключить, кликнув на имя), а также, с недавних пор, появляется красная рамка, и способов отключить её я не нашел нигде. Очень мешает это все, есть ли способы отключения?

**Comment by SthephanShinkufag** [comment]
@pwf63158cdnqacom, красная рамка отключается нажатием на `Esc`.
