### ISSUE TITLE
Отключение загрузки картинок по ссылкам в скрытых постах

### ISSUE THREAD

**Issue by VisualKei** [SthephanShinkufag/Dollchan-Extension-Tools#858]
Сабжи не скрываются в загруженных через бесконечную прокрутку страницах.

**Comment by VisualKei** [comment]
Алсо вопрос: если включена загрузка картинок по внешним ссылкам и пост с такой ссылкой скрыт, картинка будет грузиться или нет?

**Comment by Y0ba** [comment]
Будет, но можно легко исправить, за исключением асинхронных спеллов, таких как `#ihash`, `#video` и `#vauthor`. Все три асинхронны только при первой проверке, дальше результат кешируется.

**Comment by VisualKei** [comment]
Да, стоит исправить, именно чтобы не отключая весь функционал, можно было вручную скрыть пост со ссылкой на особо толстую картинку или ip-логгер и не грузить именно её.
Ну и тогда естественно надо предусмотреть подгрузку при раскрытии поста.

**Comment by Y0ba** [comment]
К слову, именно из-за таких логгеров загрузка картинок из внешних URL была выключена по-умолчанию.

**Comment by Y0ba** [comment]
@VisualKei теперь треды скрываются и помечаются как добавленные в избранное. Issue оставлю для отключения загрузки картинок по URL в скрытых постах.

**Comment by VisualKei** [comment]
Заодно надо поправить парсер ссылок, чтобы не реагировал на [такие](http://iichan.hk/a/res/1141660.html#1147888) ссылки вида `http://tineye.com/search/?url=http://iichan.hk/a/src/1447530955413.jpg`.

**Comment by Y0ba** [comment]
Разве что игнорировать URL'ы c `?` и `#` внутри.

**Comment by VisualKei** [comment]
Наверное лучше по наличию протокола больше одного раза. С `#` тоже наверное можно, а вот насчёт `?` не уверен.

**Comment by Y0ba** [comment]
`?` - означает запрос к серверу. Разве много таких сайтов, к которым можно хотлинкаться вот так: `http://azaza.lol?getimage=image.jpg`

**Comment by VisualKei** [comment]
Ну вот этого я как раз и не знаю, зато иногда запросы и без `?` бывают. А вот протокол два раза - однозначный флаг.

**Comment by VisualKei** [comment]
Но в принципе если так проще, то можно и не заморачиваться, и по ссылке сходить можно если что.

**Comment by SthephanShinkufag** [comment]
Я считаю, что эту фичу надо выпилить.
Неоднократно видел, как на сосаче умники кидали ссылки на картинки на сотни мегабайт, и писали "владельцы куклы соснулей".

**Comment by Y0ba** [comment]
По умолчанию они и так выключена.

**Comment by SthephanShinkufag** [comment]
А я продолжу выискивать баги. Хочу сегодня-завтра апнуть версию.

**Comment by VisualKei** [comment]
Не, совсем выпиливать не стоит, фича полезная. Можно прикрутить настраиваемое ограничение по размеру, и тогда даже с неподгрузкой в скрытых постах можно не морочиться.

**Comment by Y0ba** [comment]
Тут проблема в том, что в отличии от `<audio>` и `<video>` у `<images>` нет события `onmetadataloaded`, а потому определить размер изображения невозможно, пока его полностью не загрузишь.

**Comment by SthephanShinkufag** [comment]
Хех. Тогда можно было бы и картинки адекватно разворачивать даже если не указан размер. Но мы не в сказке.

**Comment by VisualKei** [comment]
Я имею в виду по размеру файла в байтах из хедера `Content-Length:`.

**Comment by Y0ba** [comment]
В js нет прямого доступа к http-протоколу, только убогий костыль под названием `XMLHttpRequest`, и в какой-то степени чуть менее убогий `fetch`, хотя в последнем даже нельзя отменить загрузку, потому что `Cancelable-promises` не завезли, лол.

**Comment by SthephanShinkufag** [comment]
> fetch

А я все думал, чому ты его не используешь. Ты же любишь всякую йобу.

**Comment by Y0ba** [comment]
Впрочем в `xhr` можно использовать `xhr.getResponseHeader('Content-Length');`, правда я не в курсе можно ли этот код использовать при `readyState` меньше четырёх (читай не при полной загрузке).

**Comment by Y0ba** [comment]
@SthephanShinkufag в кукле есть собсвенный аналог под названием `$ajax`. Да и дополнительные плюшки, которые даёт `fetch` не нужны-то.

**Comment by VisualKei** [comment]
@Y0ba попробуй тогда, если взлетит - так ведь и ип-логгеры можно будет отсекать по минимальному размеру.

**Comment by Y0ba** [comment]
IP-логгеры так не остечёшь. Запрос-то всё равно есть, хоть и отменённый.

**Comment by VisualKei** [comment]
А, да, что-то я торможу.

**Comment by Y0ba** [comment]
В принципе можно, но затратно.
1. Вызывать надо будет не XHR, а GM_xhr, что увеличивает накладные расходы.
2. Будет два запроса, один с XHR (отменённый) и второй с `Image`.

Вопрос: нужно ли оно?

**Comment by VisualKei** [comment]
В принципе внешние картинки не так часто встречаются, так что накладные расходы особо и не играют роли. Но ты смотри что тебе проще сделать, мне кажется неподгрузка скрытых всё же лучше - один раз посмотрел, если слишком большое - скрыл, и не паришься. Можно дополнительно предусмотреть отмену текущего запроса по факту скрытия, чтобы до конца не ждать если что.

**Comment by Y0ba** [comment]
У изображений нет метода `cancel`, чтобы браузер перестал загружать его. Можно конечно удалить элемент из DOM, но не факт, что браузер остановит загрузку.

**Comment by SthephanShinkufag** [comment]
Теперь картинки не добавляются к ссылкам в сообщении, если пост скрыт.
Работает с инфинитискроллом, автоподгрузкой, и всеми синхронными спеллами.
Не работает с асинхронными спеллами `#ihash`, `#video` и `#vauthor`. В таких постах картинки будут загружаться. Лень ковырять машину спеллов.
