### ISSUE TITLE
Palemoon

### ISSUE THREAD

**Issue by Mayurifag** [SthephanShinkufag/Dollchan-Extension-Tools#859]
Не могу запустить по инструкции по установке, просто фрейм вместо борд на сайтах, где скрипт должен работать. Пробовал на новом профиле, а так же новую версию гризиманки и скриптиша. Или совсем не работает, или как выше. Что я делаю не так?

**Comment by Y0ba** [comment]
`Ctrl+Shift+J` нажми, очисть консоль ошибок и попробуй открыть борду со скриптом. Ошибки скопипасть сюда.

**Comment by Mayurifag** [comment]
Как-то вот так. На новом профиле все так же, так что нет здесь конфликтов с другими расширениями. 
![pbxbtfp](https://cloud.githubusercontent.com/assets/12841309/10964787/458ef386-83ba-11e5-9e2d-50ed9f0b4457.png)

**Comment by Y0ba** [comment]
Разверни же ошибку. Только заголовка недостаточно.

**Comment by Y0ba** [comment]
Ах, стоп. Она не разворачивается.

**Comment by Mayurifag** [comment]
Да, так точно, хотел уж было по глупости спрашивать где мне найти искомую кнопку.

**Comment by Y0ba** [comment]
Попробуй в исходном коде заменить `console.log('Generator throw: ', err);` на `console.log('Generator throw: ' + getPrettyErrorMessage(err));`.

**Comment by Mayurifag** [comment]
Что-то мне подсказывает, что очень много работы сейчас предстоит над скриптом, за что я очень сильно извиняюсь.
![vgmclzj](https://cloud.githubusercontent.com/assets/12841309/10965168/3bac0e06-83bc-11e5-86ed-8db7d46e0aee.png)

**Comment by Mayurifag** [comment]
Дико извиняюсь, забыл упомянуть, что у меня не работает на арче, в винде у меня работает с гризманки 1.15.1 все.

**Comment by SthephanShinkufag** [comment]
Скажи версию своего Palemoon, я его дома накачу под вируталкой.

**Comment by Y0ba** [comment]
Судя по стек-трейсу проблема в бабеле. Я хочу перевести скрипт на шестую версию (прошлый раз когда я её пробовал неделю назад бабел не смог скомпилировать скрипт, свалившись от ошибки). Может уже починили, надо будет взглянуть.

**Comment by Y0ba** [comment]
Хотя может баг уже починен. Проблемный код был в генераторе реф-карты, а в последнии дни я его сильно изменил. @Mayurifag можешь попробовать последнюю версию: https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/raw/master/Dollchan_Extension_Tools.user.js

**Comment by Mayurifag** [comment]
@Y0ba  @SthephanShinkufag Последние версии у меня.
![hkcofwx](https://cloud.githubusercontent.com/assets/12841309/10996663/336fa8ce-8498-11e5-93b6-f8de4f9e3ab6.png)
