### ISSUE TITLE
Баг на форчане: рекапча зависает

### ISSUE THREAD

**Issue by deterenkelt** [SthephanShinkufag/Dollchan-Extension-Tools#860]
Если я какое-то время не постил в тред (приблизительно от 15 минут и дальше), при повторном вызове капчи она зависает на обновлении и помогает только рефреш страницы. Если отправлять посты практически сразу один за одним, или повторно запросить капчу к тому же посту, если она была введена ошибочно, бага не наблюдается.
![boards 4chan org_2015-11-08_12-52-32](https://cloud.githubusercontent.com/assets/2245254/11019748/4b34c03a-8618-11e5-8030-cbea1c0c76ad.png)

**Comment by Y0ba** [comment]
Тоже такое было, если открыто много вкладок. Наверное, надо полностью удалять капчу в неактивных вкладках по таймауту.

**Comment by deterenkelt** [comment]
А, нет, вот сейчас попробовал ещё пост отправить (после того, как на мой первый ответили) — снова виснет.

**Comment by deterenkelt** [comment]
А, забыл детали.

DE 15.10.20.1, FF 39, GM 3.5. Вкладок открыто всего три, но давно.

**Comment by VisualKei** [comment]
@Y0ba 
>Наверное, надо полностью удалять капчу в неактивных вкладках по таймауту.

Лучше сделать проще, я давно уже это предлагал - удалять из постформы капчу сразу после отправки поста, до состояния как в свежеоткрытом треде с нескрытой постформой.

Заодно ещё надо поправить, чтобы постформа оставалась открытой после ошибки постинга из-за проблем с соединением, а то сейчас она скрывается и приходится лишний раз тыкать в [Ответ], чтобы повторить попытку.

И ресет автообновления по таймауту при зависании соединения, о чём мы недавно говорили, таки стоит запилить.

**Comment by SthephanShinkufag** [comment]
> чтобы постформа оставалась открытой после ошибки постинга из-за проблем с соединением

49e17df2f40c0320cc00052b6047cd3d86703db3

**Comment by Y0ba** [comment]
@deterenkelt Проблема может быть в noScript'е:
```
x Fixed incompatibility with importScript() from workers
breaking new reCaptcha implementation (thanks Mr_KrzYch00
for reporting)
```
У тебя он вообще стоит? Попробуй обновить версию. Недавно вышла с исправлением.

**Comment by deterenkelt** [comment]
У меня в настоящее время не наблюдается (с DE v15.10.20.1.6b20023, GM 3.4.1 и NoScript 2.6.9.39). Зато появился другой баг, сейчас отрепорчу.

**Comment by Y0ba** [comment]
> NoScript 2.6.9

Обнови до 2.7.

**Comment by deterenkelt** [comment]
> Обнови до 2.7.
Обновил же.
