### ISSUE TITLE
Спам "mutating the [[Prototype]] of an object will блаблабла"

### ISSUE THREAD

**Issue by Dezaimasu** [SthephanShinkufag/Dollchan-Extension-Tools#864]
Подспамливает браузерную консоль лисы вот этим:

mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create
 Dollchan_Extension_Tools.user.js:1421:5

При переходе на новую страницу. Довольно часто, на разных сайтах.
Так надо, или это баг? 42 лиса обычная, обезьяна и скрипт последние. Пробовал чистый профиль, только со скриптом, такая же картина.

**Comment by Y0ba** [comment]
Это особенность babela (компилятора из es6 в es5). На скорость скрипта влиять не должно. По сути означает, что в с объектами, в которых изменён `__proto__` не будет работать предсказыватель типов, например в коде
```js
var a = { foo: 5 };
var b = {
    __proto__: Object.prototype,
    foo: 5
};
```
в случае `a.foo` компилятор заранее будет знать, что `foo` - это число и сможет убрать проверки типов или даже сразу подставить в код нужную цифру, вместо обращения к объекту, заодно ещё убрав код типа `if(a.foo > 6) { ... }` так как он и так не будет выполняться. А вот в случае с `b.foo` компилятору о `foo` ничего не известно, потому и будут ВСЕГДА выполняться все проверки типов и код будет универсальным, а значит довольно медленным.

Ну и особенность самого вывода ошибки в том, что первая подстановка `__proro__` будет выполняться медленно из-за времни, который лиса затратит на вывод самого предупреждения, лол. Из-за этого пришлось использовать другие методы (функцию `Object.assign`) при инициализации конфига.
