### ISSUE TITLE
Баг на 4chan — форма зависает при отправке

### ISSUE THREAD

**Issue by deterenkelt** [SthephanShinkufag/Dollchan-Extension-Tools#867]
При нажатии на кнопку Post появляется див с уведомлением «  ҉    Checking…», в нём же крутящееся колесо, и внизу такое же, там где [Get new posts    ҉   ] Через пару секунд на вкладке что-то мелькает, вроде то, что она обновилась, и пост в большинстве случаев проходит. Но тред дальше не обновляется, и если зайти в меню DE, то там красный глаз, как будто автообновление снято.

FF 39
DE v15.10.20.1.6b20023
GM 3.4.1
NoScript 2.7

**Comment by Y0ba** [comment]
1. Попробуй последнюю версию: https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/raw/master/Dollchan_Extension_Tools.user.js
2. Посмотри, что у тебя стоит в  Настройки -> Форма -> AJAX отправка постов*. Попробуй варианты `html5` и `Iframe`.

В консоли ошибок `Ctrl+Shift+J` после отправки что-нибудь появляется?

**Comment by deterenkelt** [comment]
> Попробуй последнюю версию

С последней всё вроде окей.

> Настройки -> Форма -> AJAX отправка постов*

Iframe. А что лучше — iframe или html5?

> В консоли ошибок Ctrl+Shift+J после отправки что-нибудь появляется?

Там что-то дохрена всего появляется…
![1448336674](https://cloud.githubusercontent.com/assets/2245254/11357391/eed87054-9277-11e5-9125-5c2080ca7edf.png)

**Comment by Y0ba** [comment]
Ммм, это ошибки самой консоли ошибок, лол. А вот ошибка вверху с `XrayWrapper` уже выглядит подозрительно. У меня подобное было, правда с `html5`.

**Comment by SthephanShinkufag** [comment]
>  Попробуй последнюю версию

>  С последней всё вроде окей

Issue можно закрывать?

**Comment by Y0ba** [comment]
Хрен его знает. Эти ошибки с лисовской песочницей (XrayWrapper) чаще всего связаны либо с типизированными массивами, либо промисами (особенно после фикса https://bugzilla.mozilla.org/show_bug.cgi?id=1170760 ). Ни то, ни другое не используется при iframe-отправке.

**Comment by deterenkelt** [comment]
> Issue можно закрывать?

Если никто больше ничего выуживать не собирается, то это issue я закрываю. Потом, если надо, сами откроете.
