### ISSUE TITLE
Просьба: Сделать поддержку midorichan.ru

### ISSUE THREAD

**Issue by malamut2014** [SthephanShinkufag/Dollchan-Extension-Tools#868]
Движок сам по выхлопному коду похож на вакабу, но не поддерживается. Запилите поддержу, пожалуйста.

**Comment by SthephanShinkufag** [comment]
Щито это за бред?
У вас по всей странице рандомные куски обернуты в <font></font>

<a href='http://rghost.net/8FMpNpzBx.view'><img src='http://rghost.net/8FMpNpzBx/image.png' /></a>

**Comment by malamut2014** [comment]
Причину я так и не нашел. Странно. Это единственный такой тред?

**Comment by Y0ba** [comment]
Причина вот она: 
https://github.com/malamut2014/Midori/blob/4dbfb173ab4d473d04febdb7b9d8c2fd1a819bcf/engine.php#L139
> `"$1</font><a href=\"$threadurl#$3\" onclick=\"\" onclick=\"highlightReply('$3');\">$2$3</a>$4<font>", $com);`

Судя по всему перепутаны местами теги `<font>` и `</font>`.

И вообще там ещё куча других подобных багов (например два раза присутствует `</head>`). Не помешало бы исправить как минимум половину ошибок из https://validator.w3.org/ ну и переключить борду на труЪ `html5`, а то сейчас там `<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">` да ещё и с несколькими пустыми комментариями до него. Кто ж так делает.

**Comment by SthephanShinkufag** [comment]
И добавьте `/res`  в адрес тредов. Как вы собираетесь различать url треда с постом №1 и урл первой страницы? Для скрипта это тоже важно.

**Comment by malamut2014** [comment]
Исправил рандомный фонты по странице. Они действительно были перепутаны.
Сейчас добавлю `/res/` в адрес тредов.

**Comment by SthephanShinkufag** [comment]
Я еще несколько дней назад почти запилил. Но вот эти моменты всю картину портят.

**Comment by malamut2014** [comment]
Мдемс. Слишком много переделывать. 
Вообще тред №1 будет отличаться от первой страницы ссылкой. Например:
`http://midorichan.ru/test/1.html` и `http://midorichan.ru/test/1`
Никак вообще без `/res/` в ссылке?

**Comment by SthephanShinkufag** [comment]
Проект помер, что-ли.
