### ISSUE TITLE
Firefox crash

### ISSUE THREAD

**Issue by XakepSDK** [SthephanShinkufag/Dollchan-Extension-Tools#869]
Крашает firefox, если ответить в тред.
{
	"version": "15.10.20.1",
	"location": "https://2ch.hk/azazazaz",
	"nav": {
		"ua": "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0 [20151029151421]",
		"Firefox": true,
		"Presto": 0,
		"WebKit": false,
		"Chrome": false,
		"Safari": false,
		"isGM": true,
		"isES6": false,
		"isScriptStorage": false,
		"isGlobal": true,
		"scriptInstall": "Greasemonkey",
		"cssFix": "",
		"animName": "animationName",
		"animEnd": "animationend",
		"hasWorker": true,
		"canPlayMP3": true,
		"canPlayWebm": true
	},
	"cfg": {
		"timePattern": "dd+nn+yy+w+hh+ii+ss",
		"addVocaroo": 0,
		"hideBySpell": null,
		"webmVolume": 29,
		"preLoadImgs": 1,
		"findImgFile": 1,
		"timeOffset": "+1",
		"removeFName": 1,
		"turnOff": 1,
		"openImgs": 1,
		"spells": "[1448552781181,null,null,null]",
		"expandPanel": 1
	},
	"sSpells": [
		"#wipe(samelines,samewords,longwords,symbols,numbers,whitespace)"
	],
	"oSpells": "[1448552781181,null,null,null]",
	"perf": [
		[
			"Init",
			1
		],
		[
			"Replace delform",
			4
		],
		[
			"Parse delform",
			5
		],
		[
			"Parse postform",
			3
		],
		[
			"Init keybinds",
			0
		],
		[
			"Init page",
			2
		],
		[
			"Add panel",
			0
		],
		[
			"Init AJAX",
			0
		],
		[
			"Preload images",
			13
		],
		[
			"Audio links",
			1
		],
		[
			"Video links",
			0
		],
		[
			"Image names",
			0
		],
		[
			"Reflinks map",
			2
		],
		[
			"Apply CSS",
			3
		],
		[
			"Display page",
			1
		],
		[
			"Infinity scroll",
			0
		],
		[
			"Hide posts",
			2
		],
		[
			"Scroll page",
			0
		],
		[
			"Всего",
			37
		]
	]
}

**Comment by SthephanShinkufag** [comment]
Блядь, ну началось.

**Comment by XakepSDK** [comment]
Ну это мой косяк или как?

**Comment by SthephanShinkufag** [comment]
> 15.10.20.1

Ох! Я уж подумал, что это с новой версией.
Обновитесь же!

**Comment by XakepSDK** [comment]
Щас тестировать буду. Обновился.

**Comment by XakepSDK** [comment]
Всё, не крашает, загрываю.

**Comment by SthephanShinkufag** [comment]
Я просто только что выкатил обнову, и тут сразу такой критический Issue, хех.

**Comment by XakepSDK** [comment]
Сам с собой крашается. Пока не нашёл каких либо корреляций.
{
	"version": "15.11.26.0",
	"location": "https://2ch.hk/po/res/12076972.html",
	"nav": {
		"ua": "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0 [20151029151421]",
		"Firefox": true,
		"Presto": 0,
		"WebKit": false,
		"Chrome": false,
		"Safari": false,
		"isGM": true,
		"isES6": false,
		"isScriptStorage": false,
		"isGlobal": true,
		"scriptInstall": "Greasemonkey",
		"cssFix": "",
		"animName": "animationName",
		"animEnd": "animationend",
		"hasWorker": true,
		"canPlayMP3": true,
		"canPlayWebm": true
	},
	"cfg": {
		"timePattern": "dd+nn+yy+w+hh+ii+ss",
		"addVocaroo": 0,
		"hideBySpell": null,
		"webmVolume": 29,
		"preLoadImgs": 1,
		"findImgFile": 1,
		"timeOffset": "+1",
		"removeFName": 1,
		"turnOff": 1,
		"openImgs": 1,
		"spells": "[1448552781181,null,null,null]"
	},
	"sSpells": [
		"#wipe(samelines,samewords,longwords,symbols,numbers,whitespace)"
	],
	"perf": [
		[
			"Init",
			2
		],
		[
			"Replace delform",
			3
		],
		[
			"Parse delform",
			4
		],
		[
			"Parse postform",
			3
		],
		[
			"Init keybinds",
			0
		],
		[
			"Init page",
			1
		],
		[
			"Add panel",
			1
		],
		[
			"Read my posts",
			0
		],
		[
			"Init AJAX",
			1
		],
		[
			"Preload images",
			12
		],
		[
			"Audio links",
			1
		],
		[
			"Video links",
			3
		],
		[
			"Image names",
			1
		],
		[
			"Reflinks map",
			2
		],
		[
			"Apply CSS",
			3
		],
		[
			"Display page",
			0
		],
		[
			"Infinity scroll",
			0
		],
		[
			"Hide posts",
			2
		],
		[
			"Scroll page",
			0
		],
		[
			"Всего",
			39
		]
	]
}

**Comment by SthephanShinkufag** [comment]
Как добиться краша? Как именно крашится? Пустая страница? Или просто висит попап "Загрузка"?
Что в консоли ошибок (`Ctrl + Shift + J`)?

**Comment by XakepSDK** [comment]
Крашается во время обновления страницы или во время загрузки поста по номеру.(когда мышкой на цифры наводишь).

**Comment by SthephanShinkufag** [comment]
И часто крашится? Ни разу ничего не заметил. Может, у вас какие-то плагины стоят, которые конфликтуют с куклой?

**Comment by Y0ba** [comment]
Версия лисы 32-битная? Перед крэшем много памяти отъедает? Сколько всего памяти на компьютере? Просто может крашится из-за недостатка памяти. Этим же можно объяснить тормоза у некоторых в треде. Тогда это будет значить, что в скрипте (или в какой-то функции, который скрипт использует) есть утечка памяти.

**Comment by SthephanShinkufag** [comment]
У меня сегодня было что-то подобное.
Я прокрутил инфинитискроллом до 2 страницы, нормально все скроллилось, и в какой-то момент на экране все пропало. Просто фоновый цвет document.body. Я хотел уже было вызывать консоль, как случайно крутанул клесо опять вниз, и тред опять появился. Ни тромозов, ничего. Просто на время пропали все элементы. Сосач, найтли.

**Comment by Y0ba** [comment]
Не. Это проблема с лейаутом. А тут именно зависания, что браузер не реагирует на мышку и клавиатуру и возможно OOM (out of memory) крэш.

**Comment by Y0ba** [comment]
Зависания могут быть из-за кучи объектов, которые сборщик мусора не может по какой-то причине удалить, но каждый раз проверяет можно ли их уже удалить или нет. Объектов становится всё больше, зависания усиливаются. В конце концов может не хватить памяти и всё.

**Comment by SthephanShinkufag** [comment]
По любому должна быть утечка. Столько всего переделано, что такие вещи в таком сложном коде просто обязаны появляться.

**Comment by SthephanShinkufag** [comment]
Надо зайти в какие-нибудь вебм-треды и поставить апдейтер на 10сек.

**Comment by Y0ba** [comment]
Замутить утечку с язаком с GC это очень сильно постараться надо :\
Да ещё и попробуй найди её.

**Comment by SthephanShinkufag** [comment]
Меня сейчас беспокоит поведение скрипта в хроме. Там он очень странно применяется, будто релоадит всю страницу.

**Comment by Y0ba** [comment]
Это в стейбл версии?

**Comment by Y0ba** [comment]
Можно скрывать не `doc.body`, а только делформу во время выполнения. По идее время увеличиться не должно.

**Comment by SthephanShinkufag** [comment]
Это в хроморасширении. С тамперманки все норм.

**Comment by SthephanShinkufag** [comment]
Причем хроморасширение выполняется тоже по domcontentloaded, как и везде. Но выглядит это вырвиглазно.

**Comment by SthephanShinkufag** [comment]
Может, это из-за асинхронного конфига расширения, все выполняется растянуто во времени.

**Comment by XakepSDK** [comment]
Такс, только что крашнуло во время ответа в тред. 16гб озу, firefox 32 бит. Flash player, adblock, ghostery, noscript.

**Comment by Y0ba** [comment]
@SthephanShinkufag а версия хрома какая? У меня в `Version 46.0.2490.86 m` выглядит норм.

**Comment by Y0ba** [comment]
@SthephanShinkufag попробуй эту версию в хроме: https://gist.github.com/Y0ba/86a389c70b2c84657618/raw/1589849e07244194e80507188781044249e9006f/DET.user.js

**Comment by XakepSDK** [comment]
Только что краш во время обновления треда. Какой-то буфер наверное переполняется.

**Comment by Y0ba** [comment]
Гы-гы. В хроме "мелькание" объясняется дополнительной задержкой из-за `readMyPosts`. Нормальное исправление - сделать так, чтобы функция выполнялась сама по себе после отображения формы. Ммм...

**Comment by Y0ba** [comment]
В тампермонки такого нет, поскольку конфиги читаются синхронно и быстро.

**Comment by Y0ba** [comment]
`Read my posts 151ms`

**Comment by SthephanShinkufag** [comment]
За тампермонки речь не шла. Проблема в расширении из-за асинхронных вызовов.
Щас посмотрю, загружу как расширение.
Лиса в отношении загрузки конечно красава. Кеширует страницу, и при ее обновлении практически ничего не заметно, даже кнопки постов не пропадают.

**Comment by SthephanShinkufag** [comment]
У меня проблемы с лейаутом уже раза два сегодня были. Причем это только на сосаче, когда набегает узкая оранжевая сосачерская полоса вверху страницы.

**Comment by SthephanShinkufag** [comment]
Страница пропадает полностью, и появляется, если ее поскроллить.

**Comment by Y0ba** [comment]
У тебя e10s включён? А то я видел, что в куклотреде у тебя 45 версия, а в ночнушках e10s по-умолчанию включён и очень нестабилен.

**Comment by SthephanShinkufag** [comment]
Мм, а ведь таки да. Надо будет выключить и погонять.

**Comment by Y0ba** [comment]
@XakepSDK последнюю версию можешь проверить?

https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/raw/master/Dollchan_Extension_Tools.user.js

**Comment by SthephanShinkufag** [comment]
Я доделал расширение. Скрипт внедряется, если найдена делформа из query списка.
Блджад, столько подводных камней, полный пыц. Даже на костыли бабеля ругалось. Зато разобрался.

Прикрутить список использвуемых в скрипте доменов, чтобы скрипт там инжектировался без проверки делформ?

**Comment by SthephanShinkufag** [comment]
Или пусть везде тупо делформы чекает, меньше выполняемого кода.

**Comment by Y0ba** [comment]
Угу проверку доменов можно добавить.

Я, кстати, почти доделал разворот картинок если недоступен размер. Выглядит няшно: на заднем плане загружается полупрозрачная картинка с размером табнейла, пока на переднем вертится значок загрузки.

**Comment by SthephanShinkufag** [comment]
Круто.
А у расширения есть минус - недоступно greasemonkey хранилище. Используется localStorage. Ничего кроссдоменного для расширений не придумали?

**Comment by Y0ba** [comment]
Придумали, только там вручную надо запиливать. И, кстати, что хорошо: можно обойтись без `JSON.parse`/`stringify` и передавать копии объектов по запросу, а хранить их в памяти.

**Comment by Dezaimasu** [comment]
Пару раз лиса повесилась при нажатии кнопки "Ответ". Сегодня раз и вчера раз. Наверное это из этой же области. Воспроизвести не получается. Просто накатал ответ, нажал отправить, и всё повисло. Оба раза на сосаче. Лиса 42 штейбл, обезьяна-кукла последние.

**Comment by Y0ba** [comment]
@Dezaimasu так, открой в лисе `about:crashes`, выбери тот который произошёл из-за куклы и дай ссылку сюда.

**Comment by Dezaimasu** [comment]
Так она не крашнулась, она повисла намертво. Я её сам пристрелил, прождал минут пять вначале, а потом прибил процесс. Если вдруг ещё поймаю, подожду поболе.

**Comment by Y0ba** [comment]
Тогде тебе сюда: #873 Алсо, попробуй последнюю версию: https://raw.github.com/SthephanShinkufag/Dollchan-Extension-Tools/master/Dollchan_Extension_Tools.user.js

**Comment by XakepSDK** [comment]
Кстати, у меня тоже намертво 1 раз зависала вкладка, но потом весь браузер повис(

**Comment by Y0ba** [comment]
@XakepSDK а если выключить предзагрузку изображений тоже крэшится?
@Dezaimasu у тебя предзагрузка изображений включена?

**Comment by XakepSDK** [comment]
@Y0ba а вот фиг знает, всего 1 раз было. Алсо, еще сильно зависает во время загрузки треда/раздела.

**Comment by Y0ba** [comment]
Ну так попробуй отключи опцию и проверь. Алсо, если не сильно лень, можешь сделать профилирование скрипта (могу подсказать как) и тогда уже будет ясно видно откуда идут тормоза.

**Comment by XakepSDK** [comment]
Подсказывай, лаги надоели, иногда до 5-10 секунд зависает.

**Comment by Y0ba** [comment]
@XakepSDK ммм, для начала попробуй сделать так:

Открой редактор скрипта, найди функцию `function setStored(id, value) {` и добавь сразу после `{` - `return;`.

А то я нашёл, что некоторые жалуются, что `GM_setValue` меедленно работает и вешает браузер. Может у тебя та же проблема.

**Comment by Dezaimasu** [comment]
@Y0ba не, предзагрузкой пиков никогда не пользовался.

**Comment by XakepSDK** [comment]
Это скидывать?

Config loading 5ms
Init 2ms
Replace delform 2ms
Parse delform 11ms
Parse postform 3ms
Add panel 2ms
Preload images 18ms
Image names 3ms
Reflinks map 3ms
Apply CSS 3ms
Hide posts 34ms
Scroll page 134ms
Всего 220ms 

Это нужная статистика?

**Comment by Y0ba** [comment]
Не, ты просто скажи, если отключить функцию `setStored` как я указал выше, то зависания прекращаются? У тебя в избранном много тредов? Если их очистить быстрее становится?

**Comment by XakepSDK** [comment]
Вот без return, выше было с return:

Config loading 4ms
Init 3ms
Replace delform 2ms
Parse delform 11ms
Parse postform 3ms
Init page 2ms
Preload images 12ms
Image names 3ms
Reflinks map 2ms
Apply CSS 3ms
Hide posts 153ms
Scroll page 166ms
Всего 364ms

**Comment by Y0ba** [comment]
Зависания как?

**Comment by XakepSDK** [comment]
Общее зависание сокращается на 5-7мс, но сильных изменений нету, как лагало так и лагает.

**Comment by Y0ba** [comment]
@XakepSDK попробуй эту версию скрипта: https://gist.github.com/Y0ba/86a389c70b2c84657618/raw/6f0864c7d7c44cffa9276985b3a2295213a6d0c9/DET.user.js

Не забудь удалить старую версию скрипта.

Я туда встроил профилировщик (результат отображается в окошке справа вверху). Суть такова: открываешь с этой версией скрипта тред, доводишь скрипт до зависания и копипастишь результат сюда. Так я смогу увидеть в каком месте у тебя скрипт зависает.

**Comment by XakepSDK** [comment]
Там пусто.

**Comment by Y0ba** [comment]
@XakepSDK оно записывает только при ручном обновлении.

**Comment by XakepSDK** [comment]
[
	[
		[
			"$$Start",
			9142.960000000001
		],
		[
			"Prevent Default",
			9143.04
		],
		[
			"Clear Marks",
			9143.145
		],
		[
			"Show Popup",
			9143.960000000001
		],
		[
			"Stopping UpdMachine",
			9144.77
		],
		[
			"Set Update Status",
			9145.035
		],
		[
			"Updmachine: Step 1",
			9145.08
		],
		[
			"AJAX: Check Headers",
			10962.22
		],
		[
			"AJAX: Check Response",
			10962.44
		],
		[
			"AJAX: DOMify Response",
			10984.345
		],
		[
			"Load Form",
			10984.635
		],
		[
			"Check Bans",
			10984.925000000001
		],
		[
			"Check Form",
			10984.94
		],
		[
			"Parser: Init",
			10985.235
		],
		[
			"Parser: Check Deleted & Omitted",
			10985.255000000001
		],
		[
			"Parser: Import Posts",
			10993.91
		],
		[
			"Parsing Posts",
			10994.51
		],
		[
			"Scrolling",
			10994.550000000001
		],
		[
			"Update panel counters",
			10995.455
		],
		[
			"Updmachine: Handle New Posts",
			10995.915
		],
		[
			"Updmachine: Update Notifications",
			10996.175000000001
		],
		[
			"$$Finish",
			10996.205
		]
	]
]

Алсо, при обновлении не зависает. Зависает при 1 загрузке страницы/треда.
Кстати, только что крашнуло при обновлении треда, не успел скопировать текст дебага.

**Comment by Y0ba** [comment]
Ммм, тут всё быстро. Значит тормоза не в загрузке и анализе постов :<

**Comment by Y0ba** [comment]
@XakepSDK ссылку на креш-репорт из `about:crashes` можешь показать? Или ты сам завершил работу фокса?

**Comment by XakepSDK** [comment]
https://crash-stats.mozilla.com/report/index/5444b6d9-e4c3-461f-9f47-1f3bf2151205
Блин, я же запретил отправку!

**Comment by Y0ba** [comment]
Попробуй отключить `Flash`-плеер. Судя по всему крешится он.

**Comment by XakepSDK** [comment]
Получается это несовместимость?

**Comment by Y0ba** [comment]
Возможно, но эта проблема известна. Можешь попробовать последнюю бету флэша, но там вроде как ещё не исправили конкретно этот крэш: http://labs.adobe.com/downloads/flashplayer.html

Алсо, тормозит ли скрипт с выключенным флэшем?

**Comment by XakepSDK** [comment]
Крашей пока не заметил.

**Comment by Y0ba** [comment]
А тормоза есть?

**Comment by XakepSDK** [comment]
Есть, но во время загрузки страницы/треда ибо не оптимизирован.

**Comment by Y0ba** [comment]
В настройки -> инфо цифры большие? Или тормоза идут после начальной загрузки.

**Comment by XakepSDK** [comment]
Тормоза еще во время загрузки страницы, плагин еще не подгружен.

**Comment by Y0ba** [comment]
Так, речь идёт про куклу. Тормоза ещё до активации куклы? Или во время её работы?

**Comment by XakepSDK** [comment]
До активации куклы

**Comment by Y0ba** [comment]
А если куклу вообще выключить? Может проблема во встроенных скриптах?

**Comment by XakepSDK** [comment]
Без куклы тоже лагает.(всё время с куклой сидел, лол)

**Comment by Y0ba** [comment]
:\
Ну вот. Значит проверяй дополнения и плагины. Отключай по одному и смотри кто виноват. Потом отпишись сюда о результатах.

**Comment by XakepSDK** [comment]
Всё равно лагает, это из-за новомодного загрузчика двача(полоска сверху). Ёба-макаки говнокодят как могут.

**Comment by Y0ba** [comment]
Тогда ставь `NoScript` и блокируй `2ch.hk`. Кукла с заблокированными встроенными скриптами там работает нормально.

**Comment by Y0ba** [comment]
Только отключи в `NoScript` блокировку `<AUDIO> / <VIDEO>`. Кукла с ней не совсем дружит при просмотре `webm`.

**Comment by XakepSDK** [comment]
Не, всё равно лагает(бля), ну и пох, двач уже не тот, заебали биопроблемники.

**Comment by Y0ba** [comment]
А если создать новый профиль лисы? Может в старом мусора поднакопилось и теперь из-за него браузер лагает.

**Comment by XakepSDK** [comment]
А где это можно сделать?

**Comment by Y0ba** [comment]
https://www.google.ru/search?q=Firefox+новый+профиль
Только старый сразу не удаляй. А то удалятся и закладки.

**Comment by XakepSDK** [comment]
Да, что-то сам не погуглил)
Давай завтра сделаю? Просто сейчас занят, не могу бразуер перезапускать. (Может через час попробую)
