### ISSUE TITLE
Открытие картинок с помощью СКМ на 2ch.hk 

### ISSUE THREAD

**Issue by pwf63158cdnqacom** [SthephanShinkufag/Dollchan-Extension-Tools#870]
Раньше можно было открыть одновременно 2 картинки/вебмки и перетаскивать их, а теперь нельзя, и картинка, открытая средней кнопкой, закрывается только повторным кликом по превью этой картинки в посте опять же средней кнопкой, а раньше можно было тыкнуть ЛКМ в любое место, и она закрывалась (как при обычном просмотре картинок без скрипта).

**Comment by Y0ba** [comment]
1. Скрипт не поддерживает открытие по СКМ. Видимо срабатывал встроенный в борду скрипт, а в последней версии его сломали.
2. Скрипт не поддерживает открытие нескольких файлов (хотя сделать можно).

По всей видимости тебя интересует именно открытие нескольких файлов.

**Comment by Teasin** [comment]
Да,было удобно открывать картинки\вебмки СКМ и масштабировать их скроллом, теперь же они только открываются в центре экрана и всё.

**Comment by SthephanShinkufag** [comment]
Они не открываются в центре экрана по средней кнопке. Они открываются в новой вкладке.
Может быть, вы сидите на какой-то борде, где срабатывают встроенные скрипты раскрытия.

**Comment by SthephanShinkufag** [comment]
Я часто открываю картинки в новой вкладке средней кнопкой, например.

**Comment by Y0ba** [comment]
СКМ в элементах `<a>` в лисе перехватить вообще невозможно. Такое ограничение было сделано в целях совместимости с друвнючими сайтами.

Ты, кстати, версию обновлять будешь?

**Comment by SthephanShinkufag** [comment]
Я понял. Просто он хромог. В хроме по СКМ раскрываются в центре.

**Comment by SthephanShinkufag** [comment]
Причем раскрываются как он описал.

> Ты, кстати, версию обновлять будешь?

Да. Я сейчас просто везде все проверяю.

**Comment by SthephanShinkufag** [comment]
Нужно запретить СКМ по тамбнейлу. Ибо ванильное раскрытие не нужно. Надо чтобы было как в лисе.

**Comment by SthephanShinkufag** [comment]
Я про сосач на хроме, если что

**Comment by Y0ba** [comment]
Можно в `AbstractPost.p.handleEvent` заменить
```js
if(e.button !== 0) {
	return;
}
```
на
```js
switch(e.button) {
	case 0: break;
	case 1:
		e.stopPropagation();
		/* falls through */
	default: return;
}
```
Правда это отключит любые бордовские ивенты с СКМ.

**Comment by SthephanShinkufag** [comment]
А они и не нужны. Все равно они наполовину сломаны. Сосачевское раскрытие по СКМ в хроме работает, но странно.

**Comment by SthephanShinkufag** [comment]
Не пойму, в чем проблема открывать картинки ЛКМ.

**Comment by Y0ba** [comment]
Он хочет открывать две картинки одновременно.

**Comment by SthephanShinkufag** [comment]
Раньше это можно было сделать, убрав в одном месте проверку. Мало тог, изначально скрипт ее не миел, народ попросил. С тех пор многое поменялось. Щас гляну.

**Comment by Y0ba** [comment]
Сейчас есть `Attachment.viewer` который нужно как-то убрать.

**Comment by Y0ba** [comment]
Т.е. одной проверкой не обойтись.

**Comment by SthephanShinkufag** [comment]
И вообще, я не пойму, зачем открывать несколько картинок.
Если они разного размера, они будут закрывать друг друга.

**Comment by Teasin** [comment]
В общем такие дела, с отключенной куклой в виде расширения для хрома или скрипта Темперманки всё работает по старому, открывает в центре, масштабирует, можно таскать картинку\вебмку по странице, с обновлениями в скрипте стало открывать в новом окне

**Comment by SthephanShinkufag** [comment]
Я не пойму, почему вы не окрываете картинку ЛКМ. Средняя кнопка для этого не предназначена.

**Comment by Teasin** [comment]
Как-то случайно привык, можно её уменьщить\увелисить если она раздирает монитор

**Comment by SthephanShinkufag** [comment]
Приучайтесь, как все нормальные люди.

**Comment by SthephanShinkufag** [comment]
ВНЕЗАПНО, скрипт тоже масштабирует картинки. Уже года три как. Или четыре.

**Comment by SthephanShinkufag** [comment]
Только надо открывать по левой кнопке.

**Comment by Y0ba** [comment]
Тащем-то с куклы фичу и взяли же.

**Comment by SthephanShinkufag** [comment]
Я удивился, как мы раньше пропустили ванильное раскрытие по СКМ и не заблокировали его сразу.

**Comment by Y0ba** [comment]
Я хромом попросту не пользуюсь в качестве основного браузера, а протестировать СКМ на превьюшках как-то ума не хватило.

**Comment by SthephanShinkufag** [comment]
То, что по СКМ открывает в новом окне &mdash; это нормальное поведение. Так и должно быть.
Открытие нескольких картинок можно сделать, но это запортит всю логику навигации между ними.

**Comment by Teasin** [comment]
Воу, научился в открытие в центре по ЛКМ и масштабирование, спасибо.
Просто привык к СКМ когда случайно открыл картинку и она появилась в центре, а о такой же фиче по ЛКМ и не думал.
