### ISSUE TITLE
Bug: Возросшее потребление памяти

### ISSUE THREAD

**Issue by SaruhBaruh** [SthephanShinkufag/Dollchan-Extension-Tools#871]
Браузер: Firefox 42
OS: Windows 7 64bit
Dollchan Extension Tools // @version         15.11.26.0
Борда: https://2ch.hk
Обычное открытие страницы с более чем 30 постами потребляет до гига оперативной памяти, дальше больше доходит до 2 гигов, фризы прилагаются.

**Comment by SthephanShinkufag** [comment]
Настройки в студию. Настройки - Инфо - Отладка.

**Comment by SthephanShinkufag** [comment]
Можете в момент фризов ввести в адрес `about:memory`, создать репорт и запостить сюда?

**Comment by SthephanShinkufag** [comment]
Там нажмите кнопку `Measure` или `Measure & save`

**Comment by SaruhBaruh** [comment]
Что я не вижу такой вкладки. 
[memory-report.txt](https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/files/46379/memory-report.txt)
![2015-11-28 22-59-10](https://cloud.githubusercontent.com/assets/16060563/11452974/b6108de2-9623-11e5-8c06-9455dbd5c446.png)

**Comment by SthephanShinkufag** [comment]
> Настройки - Инфо - Отладка.

В кукле же.

**Comment by SthephanShinkufag** [comment]
Окно настроек на панели скрипта внизу. Кнопка шестеренки.

**Comment by SaruhBaruh** [comment]
Вот 
[debug.txt](https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/files/46380/debug.txt)

**Comment by Y0ba** [comment]
1. Попробуй последнюю версию: https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/raw/master/Dollchan_Extension_Tools.user.js (перезапусти браузер после обновления). Я изменил немного алгоритм `CancelablePromise`. Может в них дело было.
2. Если первое не поможет попробуй зайти в Настройки -> Посты и снять галку с Обратный счетчик секунд до обновления. После чего перезапусти браузер и снова проверь.

**Comment by SaruhBaruh** [comment]
Y0ba, спасибо, первый вариант помог, но проблема не только у меня. Еще раз спасибо, если что могу выложить еще что-нибудь если поможет.

**Comment by Y0ba** [comment]
Здорово. Пока issue пусть будет открытым. Если заметишь тормоза, скажи.

**Comment by SthephanShinkufag** [comment]
Будет повод апнуть вресию. Только с хромом разобраться.

**Comment by SthephanShinkufag** [comment]
Так что, неужели зависоны у народа были из-за неоптимизированных cancellable промисов?

**Comment by Y0ba** [comment]
Хрен их знает. Возможно была какая-то замудрённая циклическая ссылка. Я бы поверил в утечку при отмене загрузки (промис бы раньше оставался в состоянии ожидания, а сейчас реждектится), но не при нормальной заргузке.

**Comment by SaruhBaruh** [comment]
К сожалению похоже фикс на сработал и течет в процессе обновления треда, сейчас тред 500 постов, работает больше 30 минут и памяти съело уже 1 гиг с чем-то. Проблема началась после вчерашнего обновления, до этого всего было нормально.
[memory-report.txt](https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/files/46409/memory-report.txt)
[debug.txt](https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/files/46411/debug.txt)

**Comment by SthephanShinkufag** [comment]
961.59 MB (100.0%) -- explicit
├──607.31 MB (63.16%) ── heap-unclassified

=\

**Comment by SthephanShinkufag** [comment]
Возможно, есть какие-нибудь расширения к лисе, которые делают замер памяти более подробным? Эта "темная материя" мне не нравится.

**Comment by Y0ba** [comment]
Эта тёмная материя детектируется специальным средством под названием детектор тёмной материи: https://developer.mozilla.org/en-US/docs/Mozilla/Performance/DMD
Для этого нужно сконпелировать фокс со специальными флагами и после чего немного поебстить с консолечкой. Но я уже это сделал и вот результат. Большая часть этой тёмной материи, возникающей после запуска скрипта, - это результат работы `new DOMParser().parseFromString(html, 'text/html');`, который почему-то не очищается сборщиком мусора. Т.е. каждый раз когда скрипт получает и парсит документ, то он ПОЛНОСТЬЮ остаётся в памяти. Отсюда и фризы, и крэши. Промисы тут не при чём.

**Comment by Y0ba** [comment]
Утечка происходит из-за того, что мы импортируем из этого документа посты и вставляем их в страницу. Однако так делать нельзя, потому что каждый пост сохраняет сильную ссылку `ownerDocument`, которая ведёт на тот документ, который был создан при помощи `DOMParser`. Потому он и не удаляется. Решение проблемы простое: перед импортированием нод использовать `doc.importNode` или `doc.adoptNode` (первый копирует ноду, второй перемещает).

**Comment by Y0ba** [comment]
@SaruhBaruh пробуй: https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/raw/master/Dollchan_Extension_Tools.user.js

**Comment by Y0ba** [comment]
И да, теперь я понимаю чувства этого юзера: http://iichan.hk/b/res/3776131.html#3776205
Ждять в отладочной версии лисы да ещё и с детектором утечек пока загрузится страница и сработает скрипт дико раздражает.
<table>
<tbody>
<tr><td>Imageboard check</td><td>2ms</td></tr>
<tr><td>Config loading</td><td>116ms</td></tr>
<tr><td>Init</td><td>175ms</td></tr>
<tr><td>Read my posts</td><td>8ms</td></tr>
<tr><td>Replace delform</td><td>3ms</td></tr>
<tr><td>Parse delform</td><td>420ms</td></tr>
<tr><td>Parse postform</td><td>38ms</td></tr>
<tr><td>Init keybinds</td><td>20ms</td></tr>
<tr><td>Init page</td><td>21ms</td></tr>
<tr><td>Add panel</td><td>13ms</td></tr>
<tr><td>Init AJAX</td><td>3ms</td></tr>
<tr><td>Audio links</td><td>5ms</td></tr>
<tr><td>Video links</td><td>25ms</td></tr>
<tr><td>Image names</td><td>142ms</td></tr>
<tr><td>Reflinks map</td><td>149ms</td></tr>
<tr><td>Apply CSS</td><td>68ms</td></tr>
<tr><td>Display page</td><td>15ms</td></tr>
<tr><td>Hide posts</td><td>38ms</td></tr>
<tr><td>Всего</td><td>1262ms</td></tr> 
</tbody>
</table>

**Comment by SthephanShinkufag** [comment]
То есть, мои опасения оправдались.
Проблемы начались именно недавно, егда ты начал использовать `new DOMParser()`.

Чому бы не использовать

		var myDoc = doc.implementation.createHTMLDocument('');
		myDoc.documentElement.innerHTML = html;
		return myDoc;

как раньше?

**Comment by Y0ba** [comment]
Да, наверное стоит сделать так (но `adoptNode` оставить, а то мало ли). Вроде он и быстрее: https://jsperf.com/domparser-vs-innerhtml-vs-createhtmldocument/13

**Comment by Y0ba** [comment]
Щас сделаю. Заодно посмотрю из-за чего происходит 0166a8d83850535a16fc0f5b5b601b393a7dd4ba

**Comment by SaruhBaruh** [comment]
Спасибо, сижу с фиксом уже около 3 часов, пока все нормально, но не могу найти быстрый тред, чтобы протестировать.

**Comment by SthephanShinkufag** [comment]
Создай вебм-тред на сосаче. Быстро наберется.

**Comment by SaruhBaruh** [comment]
Похоже, что фикс работает, лиса работает уже более 4 часов, уже 2 треда ушли бамплимит, фризов от этого не прибавилось, памяти ест пока не более 850 метров. Спасибо.

**Comment by YellowSM** [comment]
Меня вообще лиса последнее время очень расстраивает. Памяти начинает отжирать по 1,5-2 гига спустя какое-то время, проц на 50% грузит. Не только с куклой. 
Делаю тут свой сайтик, скриптов там тоже хватает, отлаживаю, падения, релоады, вот это всё. Потом начинаются дичайшие тормоза и всё вышеописанное.
Сдается, мне сама лисичка течет на скриптах или хз где.

**Comment by SthephanShinkufag** [comment]
Same shit, родной. Лиса стала чутка прожорливее. До гига доходит безо всяких куклоскриптов. Я даже на Nightly перешел (заодно чтобы куклу легче отлаживать), но та же фигня.

**Comment by YellowSM** [comment]
Хм... После предыдущего своего поста обновил куклу до последнего коммита, сижу в треде 1800 постов - фризов нет. Памяти отожрал гиг, но все работает на удивление гладко.

А кукла же не может добавлять фризы на других сайтах, если не открыто ни одной борды? Она же типа в суспензед моде висит, да?

**Comment by Y0ba** [comment]
Мне это и не нравится в кукле, что она запускается на каждом сайте при этом будучи довольно тяжеловесной. Там около пары мегабайт на каждую страницу. Это очень дохрена.

**Comment by Y0ba** [comment]
Алсо, дохрена памяти в кукле уходит на парсинг в функции `$DOM`. Надо будет просмотреть борды, которые поддерживают JSON-api и хотя бы частично перейти на них. И памяти меньше и фризить не будет при обновлении на старых компах.

**Comment by Y0ba** [comment]
Один `$DOM` может сгенерировать до пяти-десяти мегабайт. При этом лиса особо не торопиться уго убирать и пока GC разберётся со всеми промисами и прочим говном потребление памяти может дойти до пары сотен мегабайт.

**Comment by Y0ba** [comment]
По крайней мере у меня с 32 гигами. У тех, у кого памяти меньше, возможно, GC более агрессивно удаляет.

**Comment by SthephanShinkufag** [comment]
Скажу сразу &mdash; я ни за что не уберу `*` из included pages.
Скрипт должен выполняться на максимальном количестве борд, которые мы не можем предугадать. Например, я вчера случайно зашел на `hispachan.org`, и с удивлением обнаружил, что кукла там работает. Хотя я про этот сайт слышу впервые.

**Comment by Y0ba** [comment]
Я хочу переписать скрипт в виде расширения (опционально, возможность установки в качестве юзерскрипта останется), которое просто будет проверять домен и DOM-ноды, и если борда обнаружена только тогда инжектировать куклу.

**Comment by SthephanShinkufag** [comment]
Форкай. Будет две куклы.

**Comment by Y0ba** [comment]
Лол. Зачем форкать? Хроморасширение же есть уже. Там-то суть в проверке наличия делформы и всё. Есть делформа - запускаем.

**Comment by SthephanShinkufag** [comment]
А сейчас разве не идет проверка на делформу, лол?

**Comment by Y0ba** [comment]
В том-то и дело. Что код самой куклы изменять почти и не нужно. Разница будет в том, что где делформы нет, кукла даже инжектироваться не будет.

**Comment by Y0ba** [comment]
То есть просто запускаем универсальный `document.querySelector('<все делформы которые поддерживаем>')` из расширения и если сработал инжектируем куклу. Большинство сайтов уже отфильтруются на этом этапе.

**Comment by SthephanShinkufag** [comment]
Щас попробую создать скелет будущего расширения, чисто самому разобраться.

**Comment by desudesutalk** [comment]
> Скажу сразу — я ни за что не уберу `*` из included pages.

Все пользователи Scriptish, которых встречал, пользовались им именно из-за этой звёздочки. В Гризманки её не отключить, а вот в скриптише эта опция есть - отключить скриптовые инклюды и оставить только свои. Ещё встречал пару человек с Гризманки которые редактировали скрипт чтоб эту звёздочку убрать.

Или как пример - [синч](http://syn-ch.com/). Они там впаяли свою версию куклоскрипта (вроде бы) прямо в борду. Так что если у человека стоял куклоскрипт и он заходил на синч, то всё ломалось и ничего не работало. Вот только если отключить куклоскрипт для этой борды, встроенная продолжала глючить (из-за разного формата настроек в локалсторадже). С новой версией куклоскрипта эта ботва починилась вроде бы.

Ну. это я так - просто чтоб ты знал что есть *два с половиной антонимуса* кому эта `*` портит настроение.

**Comment by SthephanShinkufag** [comment]
И есть *огромная толпа* анонимусов, которым она его улучшает.
Два нытика не стоят тысячи человек. Никто не будет подстраиваться под меньшинство.

Я недавно исправил отключение скрипта по кнопке "Отключить", и по "Списку доменов, запрещающих запуск". Скрипт, если это детектирует, не производит больше с настройками ничего.

**Comment by SthephanShinkufag** [comment]
Сейчас на синче все прекрасно работает.

**Comment by SthephanShinkufag** [comment]
Зарегался на https://addons.mozilla.org/, почитал пару гайдов, щас разбираюсь с 
https://developer.mozilla.org/ru/Add-ons/SDK и
https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/jpm#Installation.

**Comment by UdongeinChan** [comment]
Лол, одна из моих первых хотелок, кажется ещё из 2010.

Мозиловцы, если что, ещё и  https://wiki.mozilla.org/WebExtensions впиливают. С ним не придётся геморроиться с компиляцией расширений отдельно пдо ФФ/Хром.
