### ISSUE TITLE
Проблемы с постингом

### ISSUE THREAD

**Issue by VisualKei** [SthephanShinkufag/Dollchan-Extension-Tools#872]
После сегодняшних изменений на ичане при постинге возвращает "Изображение слишком большое или не существует", хотя постил просто текст. В формдате `filename="blob"`. В других местах пока не пробовал.

**Comment by Y0ba** [comment]
Уже исправлено же.
https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/raw/master/Dollchan_Extension_Tools.user.js

**Comment by VisualKei** [comment]
Именно после сегодняшних исправлений и появилось, я естественно проверил, что стоит последний. Некропроблемы?

**Comment by Y0ba** [comment]
А версия лисы какая?

**Comment by VisualKei** [comment]
28

**Comment by SthephanShinkufag** [comment]
Подозреваю, дело в коммите https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/commit/fe476ed80a46c97f31840267035b3dfe0bcdca9f

Проверь с этим скриптом:
https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/raw/65008e3cac7a1620bcf85a19d740bf7265a405ee/Dollchan_Extension_Tools.user.js

Это скрипт до этого коммита.

**Comment by Y0ba** [comment]
С чего бы? Для html5-постинга используется `$ajax`, а я его там вообще не трогал.

**Comment by VisualKei** [comment]
Сейчас все сегодняшние коммиты переберу.

**Comment by SthephanShinkufag** [comment]
А, точно.

**Comment by Y0ba** [comment]
Попробуй найди `window.File = function File(arr, name) {` и замени весь блок (и последующий `File.prototype = ...`) на
```js
window.File = function File(arr, name) {
	var rv = new Blob(arr);
	rv.name = name;
	return rv;
};
```
Ну и ещё перед `if (value instanceof Blob && 'name' in value && fileName === null) {` добавь `console.log(value, value.name)` и посмотри что пишет (и пишет ли вообще) при отправке.

**Comment by VisualKei** [comment]
Чёрт, походу это не в скрипте дело, даже со старыми версиями, с которыми точно норм всё было, та же хрень.

**Comment by SthephanShinkufag** [comment]
Скоро приеду домой, проверю на palemoon.

**Comment by Y0ba** [comment]
У меня на `palemoon` всё работает.

**Comment by SthephanShinkufag** [comment]
Проверь на palemoon https://lainchan.org/layer или https://legacy.ronery.me/b пост без картинки и с картинкой.
Они самые злобные в отношении запросов. Если там не будетошибки "некорректный файл" и "you like a bot", значит все замечательно.
Осторожно, на lainchan встроенный троянец.

**Comment by Y0ba** [comment]
Что за троянец? Я то я не под виртуалкой запускаю, а с устаревшей лисы заходить на такие сайты не очень хочется.

**Comment by SthephanShinkufag** [comment]
Тогда проверь legacy.ronery.me/b, этого достаточно

**Comment by Y0ba** [comment]
Ну он не выдаёт ничего про ботов. Стандартное `You must upload an image.`, а значит бот-проверка пройдена.

**Comment by SthephanShinkufag** [comment]
Там тиниборд. В треде пость.

**Comment by Y0ba** [comment]
Всё норм.

**Comment by VisualKei** [comment]
Чё-то хрень какая-то, ещё вчера же постил, в системе ничего не менял, а теперь только скрипт от 24.11 постит даже из бэкапа лисы.

**Comment by VisualKei** [comment]
Проверил ещё на крауте, 4чане и сосаче - там всё норм. А на ичане теперь вообще пиздец - после попыток определить последний работающий коммит за неудачной попыткой запостить сразу следует бан с HTTP 502. Походу там пошатали вакабу, других причин не вижу, раз ещё вчера проблем не было и у меня в системе никаких изменений.

**Comment by VisualKei** [comment]
Походу последний нормально работающий там у меня коммит - предыдущий до dbe39c8b183162c28125f7e791e688fd84150487.

**Comment by Y0ba** [comment]
noscript стоит?

**Comment by SthephanShinkufag** [comment]
Ты все подряд коммиты пробовал?
Попробуй это:

https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/raw/e32090453ae9442a0e9d838fa1be402017d5b230/Dollchan_Extension_Tools.user.js

**Comment by VisualKei** [comment]
Тот коммит точно постит, до следующего после него не дошёл из-за геморроя с прокси, но ещё следующий уже нет. Попробовал и этот коммит, и с отключённым носкриптом - похрен, постится с
```
Content-Disposition: form-data; name="file"; filename="blob" 
Content-Type: application/octet-stream 
```

**Comment by SthephanShinkufag** [comment]
> filename="blob"

В этом-то вся проблема. Самое интересное, у нас есть на это проверка, но у тебя она не происходит почему-то.

**Comment by VisualKei** [comment]
Главное, вчера же ещё все эти коммиты работали. А у вас на палемоон норм? Может на портабельной 28 проверить?

**Comment by Y0ba** [comment]
@VisualKei найди функцию `rv.append = function append(name, value) {` и добавь в начало `alert('WORKING!');`
При отправке алерт появляется?

**Comment by Y0ba** [comment]
Алсо. Просто попробуй выполнить в консоли (Ctrl+Shift+K) код: `new File([''], '').name === ''`

Что происходит?

**Comment by SthephanShinkufag** [comment]
Но ведь я же ему специально дал попробовать https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/commit/e32090453ae9442a0e9d838fa1be402017d5b230 ыше, там вообще этот костыль вырезается, и происходит проверка прямо на месте.

**Comment by SthephanShinkufag** [comment]
Я вообще не пойму.
Как у него не может выполняться

```js
if(!nav.hasFile && value instanceof Blob) {
```

**Comment by Y0ba** [comment]
У него началось после фикса тинибоардов, когда добавили непосредственно `new File([''], '');`. Там походу с самим `File` что-то не то. Может он не выкидывает ошибку и костыли не инициализируются.

**Comment by SthephanShinkufag** [comment]
надо ему проверить 

if(value instanceof Blob) {

**Comment by VisualKei** [comment]
>Просто попробуй выполнить в консоли (Ctrl+Shift+K) код

Возвращает true

**Comment by Y0ba** [comment]
Не. Я думаю так. В 26 лисе `new File([''], '')` выкидывает ошибку. В 28 ошибки нет (как уже подтвердили), но и `FormData` его правильно не обрабатывает (конкретно пустую версию), а в 30 версии уже и `FormData` починили.

**Comment by SthephanShinkufag** [comment]
Почему

if(value instanceof Blob) {

не выполняется у него?

загрузи

https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/commit/c3a7603a8bd0b5da5ff9ffdc6618d200ebd0eccf

https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/raw/c3a7603a8bd0b5da5ff9ffdc6618d200ebd0eccf/Dollchan_Extension_Tools.user.js

И добавь после

if(value instanceof Blob) {

alert(111);

**Comment by Y0ba** [comment]
У него сам костыль не применяется, потому что
```js
try {
	new File([''], '');
} catch(e) {
```
не выкидывает ошибку.

**Comment by Y0ba** [comment]
То есть у него такая версия браузера, где `File` починили, а `FormData` ещё нет.

**Comment by Y0ba** [comment]
А учитывая политику версий, никто подобные фиксы не бекпортировал.

**Comment by SthephanShinkufag** [comment]
Хм. Тогда надо чинить сам html5Submit

**Comment by VisualKei** [comment]
Алерт 111 есть.

**Comment by Y0ba** [comment]
Не хочу я его чинить ради одной версии браузера. Надо придумать детектор подобной ошибки или в крайнем случае банить родной файл по версии браузера из UA и похуй на тех, кто изменяет его.

**Comment by Y0ba** [comment]
Естественно будет. Родной `File` тоже наследуется от `Blob`, лол.

**Comment by SthephanShinkufag** [comment]
Добавь вместо алерта

`console.log(value);`

и запость развернутое значение сюда.

**Comment by SthephanShinkufag** [comment]
оповещение появится в консоли

**Comment by VisualKei** [comment]
Там [object File] и по клику на него справа список, так просто весь не копируется, что нужно?

**Comment by SthephanShinkufag** [comment]
скриншоть

**Comment by VisualKei** [comment]
Там дохрена узлов можно раскрыть, все до упора?

**Comment by SthephanShinkufag** [comment]
Попробуй, кстати, заменить

```js
formData.append(name, value, value.size === 0 ? '' : value.name);
```

на

```js
formData.append(name, value, value.name === 'blob' ? '' : value.name);
```

**Comment by Y0ba** [comment]
Не поможет. Там ошибка в самом алгоритме `append`. Все объекты работают нормально.

**Comment by SthephanShinkufag** [comment]
Ну а вдруг.

**Comment by Y0ba** [comment]
Он уже проверял выше. Возвращает `''` как положено.

**Comment by SthephanShinkufag** [comment]
Ну и скриншоты сюда если не поможет.

**Comment by SthephanShinkufag** [comment]
А, я не глянул.

**Comment by Y0ba** [comment]
Я уже поставил портабейл (условно, эта сука умудрилась снести мой локальный профиль) версию и могу подтвердить неработоспособность скрипта.

**Comment by SthephanShinkufag** [comment]
Тогда нужно детектить версию лисы и направлять его на костыль window.File

**Comment by Y0ba** [comment]
Да. Других вариантов не вижу. Проверить не привязываясь к UA судя по всему невозможно.

**Comment by SthephanShinkufag** [comment]
Странно, что он вчера говорил, будто все работало.

**Comment by VisualKei** [comment]
Вот этот момент я тоже не пойму. Перезапуск браузера разве может влиять (хотя вроде и перезапускал тоже)? Страницы я и с нуля за это время открывал.

**Comment by SthephanShinkufag** [comment]
Что-то ведь поменялось, что имя файла при FormData.append раньше было пустым, а сейчас вдруг стало `'blob'`.

**Comment by VisualKei** [comment]
А, стоп, я мог только с картинками постить, уже точно не помню. Тогда всё понятно.

**Comment by SthephanShinkufag** [comment]
Ліл.

**Comment by Y0ba** [comment]
@VisualKei пробуй свеженький костыль :hankey:: https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/raw/master/Dollchan_Extension_Tools.user.js

**Comment by VisualKei** [comment]
Да, теперь норм, большое спасибо.
Походу таки пришло время начинать насиловать австралису.

**Comment by SthephanShinkufag** [comment]
Да сиди уже.
Зря Йоба фикс пилил, что-ли :D
