### ISSUE TITLE
Зависание вкладок на 2ch.hk

### ISSUE THREAD

**Issue by pwf63158cdnqacom** [SthephanShinkufag/Dollchan-Extension-Tools#873]
На версии от 29.11 в хроме очень часто стали просто зависать вкладки с тредами при нажатии на кнопку "получить новые посты" с ошибкой "ошибка подключения" так, что даже вкладку закрыть нельзя. Часто это происходит при нажатии этой кнопки с открытой картинкой или вебм. 
Причём эта вкладка нагружает ЦП и оперативную память, пока с ней ничего не происходит.
Если даблкликнуть по этой кнопке, то зависает гарантированно.  
И такое не только на сосаче, да.

**Comment by SthephanShinkufag** [comment]
Какой скрипт? Хроморасширение, или установленный через Tampermonkey?

**Comment by AlsaAsksMiley** [comment]
Тоже с таким поведением сталкивался на крауте при попытке загрузить файлы.
v15.11.29.1.efbd0f7
GreaseMonkey 3.6 
FF38.4.0 ESR

**Comment by Y0ba** [comment]
@pwf63158cdnqacom версия хрома какая? Алсо, расскажи подробнее про свой конфиг, он быстрый или нет? За сколько кукла инициализируется? Сам интернет быстрый?

Ошибку "ошибка подключения" исправил: https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/raw/master/Dollchan_Extension_Tools.user.js
Проверь, может и твой баг тоже исправлен.

@AlsaAsksMiley Опции `Возможность отправки одинаковых картинок` и `Удалять EXIF из JPEG` на зависания влияют? Скрипт по ссылке выше тоже попробуй.

**Comment by AlsaAsksMiley** [comment]
@Y0ba Возможность отправки одинаковых картинок отключена, удаление EXIF активно. Буквально полчаса назад опять завис браузер, но уже просто при отправке ответа без каких-либо вложений.
Спасибо, попробую скрипт, отпишусь в случае чего.

**Comment by AlsaAsksMiley** [comment]
Небольшое уточнение, я невнимательно прочитал первый пост.
Зависание происходит без показа ошибки, возможно, она просто не успевает показаться, либо природа ошибки другая.

**Comment by Y0ba** [comment]
Природа ошибки может и одна. Собственно сам показ "ошибка подключения" на зависания влиять не должен.

**Comment by Y0ba** [comment]
@AlsaAsksMiley проверь последнюю версию скрипта: https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/raw/master/Dollchan_Extension_Tools.user.js

Я там исправил баг в функции проверки отправки формы. Хотя по идее даже из-за бага скрипт зависать не должен, а в крайнем случае некоторые посты могут появиться дважды (первый будет с пометкой *удалено*). Скорее всего баг ОПа всё ещё есть, но в твоём случае он уже срабатывать не должен.

**Comment by pwf63158cdnqacom** [comment]
>Скорее всего баг ОПа всё ещё есть
Да, всё так же зависает при даблклике на "получить новые посты".

Версия последняя, v15.11.29.1.a08d02d , установленная через темперманки.

**Comment by Y0ba** [comment]
@pwf63158cdnqacom попробуй эту версию скрипта: https://gist.github.com/Y0ba/86a389c70b2c84657618/raw/6f0864c7d7c44cffa9276985b3a2295213a6d0c9/DET.user.js

Не забудь удалить старую версию скрипта.

Я туда встроил профилировщик (результат отображается в окошке справа вверху). Суть такова: открываешь с этой версией скрипта тред, доводишь скрипт до зависания и копипастишь результат сюда. Так я смогу увидеть в каком месте у тебя скрипт зависает.

**Comment by Y0ba** [comment]
@AlsaAsksMiley @pwf63158cdnqacom проверьте последнюю версию скрипта: https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/raw/master/Dollchan_Extension_Tools.user.js

Алсо, ещё одна просьба: зависаний в любом случае теперь быть не должно, но можете повторить шаги из-за которых скрипт раньше зависал и поискать в консоли ошибок (`Ctrl+Shift+J`) ошибки начинающиеся с `Invalid State!` и скопипастить сюда их содержимое.

**Comment by AlsaAsksMiley** [comment]
У меня за прошедшие дни ни разу не зависло ничего после того, как поставил скрипт версии v15.11.29.1.677bb9d
