### ISSUE TITLE
post.text.length на Краутчане

### ISSUE THREAD

**Issue by VisualKei** [SthephanShinkufag/Dollchan-Extension-Tools#874]
Что-то он там какие-то нереально большие значения даёт, в результате не срабатывает правильно условие о времени до отметки поста прочитанным по его значению. Гляньте плиз.

**Comment by SthephanShinkufag** [comment]
Ничего не понял.

**Comment by VisualKei** [comment]
Я про опцию `markViewed` же. В строке 10239 есть условие `post.text.length > 100 ? 2e3 : 500`, по которому если пост короче 100 символов, то время показа превью до пометки поста прочитанным - 500 мс, иначе 2с. Я заметил, что на крауте для коротких постов это почему-то не работает, добавил в это место `console.log(post.text.length)` и увидел, что там какие-то странные значения, типа если вручную посчитать количество символов в тексте поста, то будет к примеру 20, а в консоли выводится 140. На других же чанах это меряется вроде нормально.
