### ISSUE TITLE
Обновление капчи по таймеру

### ISSUE THREAD

**Issue by YellowSM** [SthephanShinkufag/Dollchan-Extension-Tools#876]
Посоны, добавьте еще проверку обновления капчи и при фокусе в текстарии формы редактирования. Прост, сейчас капча обноляется при фокусе на поле ввода капчи и при медленном инете я там успеваю пару символов ввести, а она херак - и новая уже. Достает.
И еще хорошо бы значение таймера в настройки вынести. Так будет более гибко.

**Comment by VisualKei** [comment]
Вот я же говорю что нужно удалять капчу после успешного ответа и вновь показывать только при следующем фокусе на постформе - все подобные проблемы решатся автоматом и не надо ничего наворачивать. Зачем вообще тратить ресурсы на долбёжку по таймеру, вместо того чтобы посылать один запрос именно тогда, когда капча реально потребуется?

**Comment by YellowSM** [comment]
Да я условно говорю про таймер - не знаю как там реализовано. Можно вообще тупо время последней загрущки запомнить, а при фокусе отнять от его текущего - и никаких таймероф.
