### ISSUE TITLE
Deleted & hidden threads automatically gives place to unfiltered 'page 2' top

### ISSUE THREAD

**Issue by gazetorio** [SthephanShinkufag/Dollchan-Extension-Tools#877]
Another feature 4chan X has for quite some time, removes empty spaces from the front page caused by magicspells and replaces all with actual threads.

**Comment by Y0ba** [comment]
@SthephanShinkufag я сейчас работаю с этой фичей и возник такой вопрос: Что делать если кто-нибудь поставит спелл `#all` или его аналоги? Загружать все треды подряд пока не закончатся страницы или поставить какое-нибудь ограничение?

**Comment by SthephanShinkufag** [comment]
Можно вообще запретить в спелледиторе писать подобное, и выдавать $popup, мол данные спеллы скроют все ваши треды, как при ошибке.

**Comment by SthephanShinkufag** [comment]
хотя, если это большой вайп....

**Comment by Y0ba** [comment]
Да ну! Всё равно ведь даже если добавить все возможные анализы, то можно написать `#words( )`, что скроет 99% тредов.

**Comment by Y0ba** [comment]
А думаю ограничить двумя страницами, а дальше уже автоматом не загружать.

**Comment by SthephanShinkufag** [comment]
хороший вайп может несколько страниц занять.

**Comment by Y0ba** [comment]
Или даже одной страницей.

**Comment by Y0ba** [comment]
А так думаю, что это не против вайпов, а скорее против всяких оффициальных™ тредов.

**Comment by Y0ba** [comment]
Кароч, вот что я думаю: загружать новые посты ТОЛЬКО если загружена одна страница и загружать новые посты только вместо тех что скрыты на ней.

При этом не важна загружена ли она была при инициализации или бесконечным скроллом.

**Comment by SthephanShinkufag** [comment]
А как быть с надписями "Страница N"? Они будут терять актуальность, если дергать треды отовсюду.

**Comment by Y0ba** [comment]
С чего бы? Просто будут указывать откуда взят тред. Можно их просто сделать менее заметными.

**Comment by SthephanShinkufag** [comment]
Я вообще не вижу смысла в этой всей машинерии с подгрузкой тредов вместо скрытых.Что мешает подгрузить еще одну страницу?

**Comment by Y0ba** [comment]
Просто будет делать тоже самое но подгружать автоматом и не отображать все треды сразу.

**Comment by SthephanShinkufag** [comment]
Но по факту подгружаются те же две страницы. Мало того, подгруженная донорская страница будет не актуальна, пока проспроллишь вниз, и нужно будет подгружать ее еще раз.

**Comment by Y0ba** [comment]
> Но по факту подгружаются те же две страницы.

Ага. Просто отличие в том, что загружается она сразу и не нужно ждать. Может у кого интернет медленный. Хрен его знает.

**Comment by SthephanShinkufag** [comment]
> загружается она сразу и не нужно ждать

Так я раньше получал всегда актуальные страницы, а теперь меня будут кормить протухшими.

**Comment by Y0ba** [comment]
Фича по умолчанию будет выключена, может кому-то так нравится.

**Comment by SthephanShinkufag** [comment]
Неправильно назвал опцию.
На самом деле, треды берутся не со второй, а со следующих страниц, вплоть до четвёртой.
