### ISSUE TITLE
[Bug] [KC] Crash upon sending post

### ISSUE THREAD

**Issue by SpedePasanen** [SthephanShinkufag/Dollchan-Extension-Tools#879]
Privet,

There is an issue with Dollchan that at least two Krautchan users reported.

Sometimes when we write a reply (which may include a picture or not) using the rapid reply floating box, just when we press the "Send" button, the whole page begins to freeze.

We can't even edit or save the text we have written, it's just entirely frozen and the page is barely responsive. The problem goes away when the thread is reloaded, but of course when we do this what was written is lost.

Thanks for any help that could alleviate the issue.

P.-S. : these are our configurations:

User #1 :
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36
v15.11.29.1.9ca4199 [Chrome extension]

User #2 :
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2579.0 Safari/537.36
v15.11.29.1.9ca4199 [Chrome extension]

**Comment by SthephanShinkufag** [comment]
Try last build please.

https://raw.github.com/SthephanShinkufag/Dollchan-Extension-Tools/master/Dollchan_Extension_Tools.user.js

If OK, please close Issue. Or tell us.

**Comment by SpedePasanen** [comment]
Thank you, I've installed it with Tampermonkey and I'm currently evaluating it.

**Comment by SthephanShinkufag** [comment]
Hm. Probably need to update chrome extension..
