### ISSUE TITLE
[4chan] Report button

### ISSUE THREAD

**Issue by xsxsx10294** [SthephanShinkufag/Dollchan-Extension-Tools#880]
Firefox полностью крашится при даблклике (второй клик перед обновлением после первого) на "Get new posts".
А возможности репорта с активным скриптом, собственно, давно уже нет.

**Comment by Y0ba** [comment]
https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/issues/873#issuecomment-162231849

**Comment by xsxsx10294** [comment]
Работает, да. Репорт-то запилите мне.

**Comment by Y0ba** [comment]
Что за репорт?

**Comment by xsxsx10294** [comment]
![report](https://cloud.githubusercontent.com/assets/16178538/11616019/cd3c72b6-9c80-11e5-8f91-3edfba4ee2f6.png)
.

**Comment by Dezaimasu** [comment]
Куклачую этого недовольного, иногда репорта оченьма не хватает.
