### ISSUE TITLE
Проблема с localstorage

### ISSUE THREAD

**Issue by VisualKei** [SthephanShinkufag/Dollchan-Extension-Tools#882]
У меня какие-то странности в работе скрипта с localstorage. Оно ессно включено, для чана разрешено постоянное (не сессионное) его использование, но между рестартами браузера данные там не сохраняются. Между закрытием вкладки чана и открытием новой с нуля - сохраняются. И после закрытия браузера в webappsstore.sqlite данных действительно нет. С другими сайтами с аналогично выставленными разрешениями никаких проблем, в том числе с пишущими в localstorage юзерскриптами, например [SpookyX](https://github.com/Fiddlekins/SpookyX).

При этом Firebug с Firestorage Plus! для чана с куклоскриптом вообще показывает пустые localstorage и sessionstorage, хотя судя по работе скрипта он вполне использует соответствующие данные. Опять же, для SpookyX Firestorage Plus! всё показывает. Я заметил такое поведение уже довольно давно - пытаясь посмотреть что кукла пишет в sessionstorage (помню, что когда-то ещё раньше всё показывалось). Видимо это опять некропроблемы, но можно что-то сделать? Потому что теперь это стало реально мешать.

**Comment by SthephanShinkufag** [comment]
Безо всяких куклоскриптов, откройте консоль браузера (Ctrl + Shift + K), введите туда

```js
localStorage['test'] = 1
```

Закройте браузер, откройте снова, и введите в консоль

```js
localStorage['test']
```

Единичка сохраняется?

**Comment by SthephanShinkufag** [comment]
> Firebug с Firestorage Plus!

Поотключайте это merde. Вообще попробуйте отключить все ваши дополнения.

**Comment by VisualKei** [comment]
Отбой, нашёл проблему с обезьяной у себя, теперь вроде всё норм.

Алсо, таки сделайте чтоб в `de-myposts` не срало `null`'ами почём зря, очень некрасивое же поведение.
