### ISSUE TITLE
Отсутствуют кнопки прокрутки страницы

### ISSUE THREAD

**Issue by IndigoHuman** [SthephanShinkufag/Dollchan-Extension-Tools#883]
Firefox 42.0, последняя версия скрипта.
В настройках борды стоит чекбокс на «Показ кнопок перемотки страницы», без скрипта они отображаются в тредах. Со скриптом – нет.

**Comment by Y0ba** [comment]
> В настройках борды

Скрипт не поддерживает работу со скриптами борды и по возможности их отключает. Что за кнопки вообще? Может их можно добавить в скрипт или они уже есть.

**Comment by IndigoHuman** [comment]
Вот такие кнопки:
![2015 12 08_180336](https://cloud.githubusercontent.com/assets/13152405/11656311/1b2ac530-9dd6-11e5-94db-e07ccce4c207.png)
Так проблема в том, что они всегда (!) были, и работали исправно с Куклой. А теперь, после обновления скрипта, их нет.

**Comment by Y0ba** [comment]
С недавних пор кукла удаляет все `jQuery`-события со страницы на `2ch.hk`, чтобы работало быстрее, потому подобные фичи могут и не работать. На панели куклы есть аналоги.

**Comment by SthephanShinkufag** [comment]
Такие же кнопки есть на панели скрипта. Стрелки вверх и вниз. Зачем изобретать велосипед.

**Comment by SthephanShinkufag** [comment]
<a href='http://rghost.net/6yQBrWKnq.view'><img src='http://rghost.net/6yQBrWKnq/image.png' /></a>
