### ISSUE TITLE
Реквест: тултип ютуб-ссылок

### ISSUE THREAD

**Issue by VisualKei** [SthephanShinkufag/Dollchan-Extension-Tools#884]
@Y0ba, добавь плиз в начало сабжа инфу о длительности ролика - иногда хочется узнать её без запуска самого ролика.

**Comment by SthephanShinkufag** [comment]
А что. я не у дел уже, что-ли?

**Comment by Y0ba** [comment]
@SthephanShinkufag лол.

Кстати, в oembed инфы о длительности нет :< Только YT-API.

**Comment by SthephanShinkufag** [comment]
Предлагаю использовать сосачерский ключ по умлочанию (и отображать его в настройках).

**Comment by Y0ba** [comment]
Абу опять обидится и заблочит скрипт. К тому же его поменять - дело пяти минут.

**Comment by SthephanShinkufag** [comment]
Зуб даю, им пользуется 2.5% пользователей скрипта.

**Comment by Y0ba** [comment]
И, кстати, даже в YT-апи я этой инфы сходу не вижу.

**Comment by SthephanShinkufag** [comment]
Заданным ключом в настройках, в смысле.

**Comment by Y0ba** [comment]
Да пофигу. Название загружается? Загружается. А большее это уже для особенных.

**Comment by VisualKei** [comment]
@SthephanShinkufag
Просто он же в ютуб-апи разбирался и это делал, но можешь и ты добавить, лол.

**Comment by VisualKei** [comment]
>И, кстати, даже в YT-апи я этой инфы сходу не вижу.

А это не оно? https://developers.google.com/youtube/v3/docs/videos#contentDetails.duration
