### ISSUE TITLE
[BUG] AJAX обновление тредов поломано

### ISSUE THREAD

**Issue by userneu** [SthephanShinkufag/Dollchan-Extension-Tools#885]
Макаба (может в ней все и дело?)
В избранном счетчик показывает новые посты (и они на самом деле есть), а кнопка "Показать новые" в треде их не подгружает. Пока не нажмешь ф5. ЛИБО. Пока не дождешься автоматической ажакс загрузки новых постов. Они загрузятся! Я намеренно включал счетчик обратного отчета (60 сек) и за 10 секунд до конца нажимал кнопку "Получить новые посты" и счетчик заново начинал с 60, а новые посты нихрена на подгружались. И так сколько угодно раз, пока таки не дождешься автозагрузки или не нажмешь Ф5. По-моему этих сведений должно быть достаточно для ловли этого жучка, ЁБА, ЧИНИ, ПЛЗ.

**Comment by userneu** [comment]
Firefox 43b
Greasemonkey 3.6
v15.11.29.1.da05354

**Comment by SthephanShinkufag** [comment]
Всё работает. Какие настройки (Настройки - Инфо - Отладка)?

**Comment by userneu** [comment]
Что значит работает? Нет не работает, нинада тут. Баг сначала поймать нужно. Сам я пока не нашел закономерности. Но баг есть это точно. Ёба же теребил ажакс обновлялку в последний месяц. 
Отладка вот http://pastebin.com/mmARg9p2

**Comment by SthephanShinkufag** [comment]
Ни разу не встречал.

**Comment by SthephanShinkufag** [comment]
Попытался добиться того, что вы описываете - безрезультатно. Пока я не воспроизведу баг, кина не будет.

**Comment by userneu** [comment]
Как-то нехорошо это, Степан. Не всякий баг легко воспроизводится, уж извините. Это не значит что его нет.

**Comment by userneu** [comment]
Небольшой апдейт инфы. Сабжевый баг появляется только при одновременно 2 и более открытых вкладок с тредами. Если пользовать только одну, то все работает как надо. Возможно это все связано как-то с синхронизацией между вкладками.

**Comment by userneu** [comment]
А нет, вру. И с одной вкладкой появляется. Блиннннн, ну чо такое. Никак прям с этими счетчиками. Задолбало.

**Comment by userneu** [comment]
Ёба, плиз, займися. Печет от этой херни. v15.12.16.0.c3c6e28

**Comment by Y0ba** [comment]
Всё, понял в чём дело. Баг проявляется только если работать с избранным на той же странице. После обновления избранного страница сохраняется в кеш и последующие обновления дают 304 ошибку, которая сигнализирует, что постов нет. И так продолжается пока не появятся новые посты. Автоматическое обновление, кстати, тоже не работает.
