### ISSUE TITLE
[bug] [4chan] некорректно расчитывается ширина div поста

### ISSUE THREAD

**Issue by Dezaimasu** [SthephanShinkufag/Dollchan-Extension-Tools#888]
Если в одном посте есть пик и ютубопревьюшка, то получается пикрилейтед. У дивки с классом "post reply" ширина получается из той, что задаётся в опциях скрипта для ютубоплеера, а пик всё ломает.
![boards 4chan org_v_thread_320267979_can-we-have-webm-thread_-_2015-12-15_23 05 57](https://cloud.githubusercontent.com/assets/1636242/11824133/9c4dcd56-a380-11e5-8cce-c6598207f369.png)

**Comment by SthephanShinkufag** [comment]
Лучше поздно, чем никогда.
