### ISSUE TITLE
Выключается звук в плеере лисы

### ISSUE THREAD

**Issue by YellowSM** [SthephanShinkufag/Dollchan-Extension-Tools#889]
Че-то часто на лисе после перезапуска в плеере звук в "муть"-режиме. Постоянно его включать приходится.

Алсо, по поводу прожорства и фризов лисы. Обновился до 43 версии, поставил x64 билд - пока полет нормальный и памяти жрет меньше и пока фризов не было.

**Comment by AlsaAsksMiley** [comment]
Подтверждаю, очень часто уровень звука стал слетать, стоит даже вкладку переключить, как он переход в режим Mute.

**Comment by mr-rak** [comment]
Тоже есть такая проблема.

**Comment by Y0ba** [comment]
bee673ebda3590b7044c97d333365c90f65067c3
