### ISSUE TITLE
Дублирование ссылки "Ответить" на Модиф. Kusaba (0chan) в Chrome 47

### ISSUE THREAD

**Issue by smilefag-kurisu** [SthephanShinkufag/Dollchan-Extension-Tools#890]
На большинстве борд с движком, названном в списке поддерживаемых борд "Модиф. Kusaba (0chan)" дублируется ссылка "ответить" в конце треда (на трёх из четырёх имиджборд из списка).

Хотелось бы, чтобы при включённом скрипте ссылка "Ответить" борды скрывалась.

Подобное поведение замечено на Chrome 47.0.2526.106; на Firefox всё нормально.

При этом на 0-chan.ru (второй скриншот) вторая ссылка "Ответить" нормально скрывается, в отличие от остальных трёх имиджборд (0chan.cc, 2chan.su (старый claire.ws) и kurisa.ch (новый claire.ws)).

Скриншоты всех четырёх борд прикладываю (на kurisa.ch (четвёртый скриншот) специально для этого ссылку, что создаёт борда, а не скрипт, переименовал в "Ответить1").

Алсо, на Chrome также не работает обнаружение наличия скрипта через ухищрения типа:
  function dollchanPresent() { return (document.getElementById('de-panel-logo')    != null); }
  function dollchanEnabled() { return (document.getElementById('de-panel-refresh') != null); }
(хотел таким образом на стороне движка определять, стоит ли выдавать вторую ссылку, но не сработало).
На Firefox это обнаружение тоже работает.

![316123807_393287068](https://cloud.githubusercontent.com/assets/16463967/12028759/b6b26338-aded-11e5-8fa0-189853b27ea7.jpg)
![316123807_393287118](https://cloud.githubusercontent.com/assets/16463967/12028758/b6b12766-aded-11e5-9816-cfcaf109b869.jpg)
![316123807_393287164](https://cloud.githubusercontent.com/assets/16463967/12028760/b6b40706-aded-11e5-9840-9ddf86f8d9c5.jpg)
![316123807_393287174](https://cloud.githubusercontent.com/assets/16463967/12028761/b6b6eed0-aded-11e5-9827-a2037ec0b58d.jpg)

**Comment by SthephanShinkufag** [comment]
Вообще, в настройках нульчановской кусабы есть опция "Показывать ответы внутри поста".
