### ISSUE TITLE
Отображать title у WebM-файлов

### ISSUE THREAD

**Issue by Kagami** [SthephanShinkufag/Dollchan-Extension-Tools#894]
Для тематических WebM-тредов очень полезно иметь возможность отображения поля title метаданных — большая часть пользователей не знает об альтернативных методах получения информации о видео, а DET установлен у многих.

В качестве примера можно использовать [код из 4chan-x](https://github.com/ccd0/4chan-x/blob/1.11.22.3/src/Images/Metadata.coffee#L41-L62) (MIT). Я портировал его на JS:

```js
function parse(data) {
  function readInt() {
    var n = data[i++];
    var len = 0;
    while (n < (0x80 >> len)) {
      len++;
    }
    n ^= (0x80 >> len);
    while (len-- && i < data.length) {
      n = (n << 8) ^ data[i++];
    }
    return n;
  }

  var i = 0;
  while (i < data.length) {
    var element = readInt();
    var size = readInt();
    if (element === 0x3BA9) { // Title
      var title = '';
      while (size-- && i < data.length) {
        title += String.fromCharCode(data[i++]);
      }
      return decodeURIComponent(escape(title)); // UTF-8 decoding
    } else if (element !== 0x8538067 && element !== 0x549A966) { // Segment, Info
      i += size;
    }
  }
}

var data = require("fs").readFileSync("test.webm");
console.log(parse(data));
```

Всё отлично работает на тестовых файлах.

У вас свой класс для парсинга WebM, поэтому, вероятно, в таком виде оно не пригодно. Могу попробовать портировать на ваш `WebmParser`, если это поможет. (Только код для парсера, целиком реализовать фичу вместе с изменениями в интерфейсе не имею возможности.)

**Comment by Y0ba** [comment]
В скрипте уже есть парсер WebM (который правда работает только с полностью загруженными файлами и некоторые корректные файлы считает сломанными). Так что реализовать поддержку чтения заголовка не составит труда.

Ты хочешь отображать заголовок при раскрытии WebM? А то если для всех видео в треде, то придётся (хоть и частично) скачивать каждый webm и парсить его.

**Comment by Kagami** [comment]
>Ты хочешь отображать заголовок при раскрытии WebM?

Да, в таком виде было бы достаточно.

**Comment by Kagami** [comment]
На всякий случай вот ещё юзерскрипт для голой макабы, может пригодится:

```js
// ==UserScript==
// @name        WebM title
// @namespace   https://2chk.hk/webm-title
// @description Show metadata title of WebM videos on 2ch.hk
// @include     https://2ch.hk/*
// @version     0.0.1
// @grant       none
// ==/UserScript==

// Ported from 4chan-x (MIT).
function parseTitle(data) {
  function readInt() {
    var n = data[i++];
    var len = 0;
    while (n < (0x80 >> len)) {
      len++;
    }
    n ^= (0x80 >> len);
    while (len-- && i < data.length) {
      n = (n << 8) ^ data[i++];
    }
    return n;
  }

  var i = 0;
  while (i < data.length) {
    var element = readInt();
    var size = readInt();
    if (element === 0x3BA9) {  // Title
      var title = "";
      while (size-- && i < data.length) {
        title += String.fromCharCode(data[i++]);
      }
      return decodeURIComponent(escape(title));  // UTF-8 decoding
    } else if (element !== 0x8538067 && element !== 0x549A966) {  // Segment, Info
      i += size;
    }
  }
  return null;
}

function fetchData(url) {
  return new Promise(function(resolve, reject) {
    var xhr = new XMLHttpRequest();
    xhr.open("GET", url, true);
    xhr.setRequestHeader("Range", "bytes=0-9999");
    xhr.responseType = "arraybuffer";
    xhr.onload = function() {
      if (this.status >= 200 && this.status < 400) {
        resolve(new Uint8Array(this.response));
      } else {
        reject(new Error(this.responseText));
      }
    };
    xhr.onerror = reject;
    xhr.send();
  });
}

document.addEventListener("DOMContentLoaded", function() {
  var container = document.getElementById("fullscreen-container");
  if (!container) return;
  var observer = new MutationObserver(function(mutations) {
    mutations.forEach(function(mutation) {
      Array.prototype.filter.call(mutation.addedNodes, function(node) {
        return node.tagName === "VIDEO";
      }).forEach(function(video) {
        var url = video.querySelector("source").src;
        fetchData(url).then(function(data) {
          var title = parseTitle(data);
          if (!title) return;
          var div = document.createElement("div");
          div.textContent = title;
          div.style.textAlign = "center";
          div.style.fontStyle = "italic";
          div.style.padding = "3px";
          video.parentNode.appendChild(div);
        })
      });
    });
  });
  observer.observe(container, {childList: true});
}, false);
```

**Comment by Kagami** [comment]
Спасибо!

>Во многих вебмках, которые постят на сосаче, заголовок отсутствует

Некоторые специализированные программы (например, wybm) автоматически его ставят для всех webm. Т.е. по крайней мере часть вопросов об исходнике видео отпадёт.

**Comment by SthephanShinkufag** [comment]
@Kagami, я смотрю, вы серьезно вебмками занимаетесь, хех.
Я пытался как-то по-другому отображать инфу, кроме как в тултипе, а именно в углу вебмки, но это выглядит очень навязчиво и часто мешает просмотру. Есть еще неудобство, что вебмка должна полностью загрузиться, чтобы можно было считывать массив.

**Comment by Kagami** [comment]
Да так, хобби.
Я считаю, главное это чтобы пользователи скрипта знали, что возможность посмотреть метаданные видео присутствует. А постоянно их отображать в самом деле не обязательно.
А отдельный запросом с хидером Range нельзя (как в примере выше)? Первых нескольких килобайт должно быть достаточно, а такие запросы очень быстро выполняются и трафик/задержки минимальны.

**Comment by SthephanShinkufag** [comment]
Нужно переделывать наш парсер вебмок, Y0ba писал выше. Либо вообще его не использовать, а парсить отдельно.

**Comment by Kagami** [comment]
Можно прямо вот ту функцию `parseTitle`, что выше, взять, она полностью рабочая. Скачивать по второму разу под 20 мегабайт это всё-таки перебор.

Но это так, мелочи. Меня устраивает и в текущем виде.

**Comment by Y0ba** [comment]
Я перепишу парсер webm после того как стандартизируют [Streams API](https://streams.spec.whatwg.org/) и добавят поддержку хоть в один браузер.

Алсо, я хочу переписать код для работы с файлами поверх них. Сейчас как всё работает: файл полностью считывается в память -> обрабатывается -> отправляется при помощи xhr. Как я хочу сделать: файл считывается по кусочкам -> на лету обрабатывается и отправляется.

**Comment by Y0ba** [comment]
> файл считывается по кусочкам -> на лету обрабатывается и отправляется

Ну это только в тех браузерах, в которых будет поддерживаться потоки и соответствующие API у объектов `fetch` и `FileReader`. В остальных всё будет по-старому.
