### ISSUE TITLE
Глючит время в подгружаемых постах

### ISSUE THREAD

**Issue by exelents** [SthephanShinkufag/Dollchan-Extension-Tools#895]
http://joxi.ru/EA4kKnyHD0zKv2
Посты которые подгружены скриптом отображаются по московскому времени, а не по моему локальному. Такая хрень была например на дваче. Что характерно, без скрипта время работает нормально.

**Comment by Y0ba** [comment]
Ммм, а коррекция времени производится силами куклоскрипта или встроенными в макабу скриптами? Если последнее, то так и должно быть.

**Comment by exelents** [comment]
Скорее всего коррекция проводится средствами браузера, иначе такой проблемы бы вообще не возникло. А если бы куклоскрипт попытался бы скорректировать "готовое" время, то у меня бы высветилось не московское время а вообще хрен знает какое.

**Comment by Y0ba** [comment]
> Скорее всего коррекция проводится средствами браузера

Nyet. Такое вот `<span class="posttime">22/01/16 Птн 10:33:17&nbsp;</span>` ни один браузер не сумеет сконвертировать. Да и откуда ему знать разницу во времени?

**Comment by Y0ba** [comment]
Внимательно просмотри настройки макабы (вверху страницы ссылка "Настройка").

**Comment by exelents** [comment]
Да, вижу параметр "коррекция времени", но врядли это говорит о том что операция проводится на сервере, может эта настройка потом улетает и фронтенду. Клиенту передавать данные в том виде что пишешь ты совершенно не обязательно, можно передавать таймстамп как параметр json ответа, благо апи у макаки есть. Для работы с датой в JS есть соответствующие классы - https://learn.javascript.ru/datetime им таймстамп просто скармливаешь. Так что я думаю что всё это происходит в браузере, а Степан просто не прикрутил соответствующую функцию к кукле.

**Comment by Y0ba** [comment]
Да есть у нас этот параметр. Суть в том, что если время корректируют макабовские скрипты, то с автообновлением куклы они работать не будут. Используй коррекцию времени из куклы.

**Comment by exelents** [comment]
Так макаба корректирует только при полной загрузке страницы, а подгружаются они с некорректированным. Как они подгружаются? Через апи? Через какой-то аякс? Может возможно вставить коррекцию чисто в функцию подгрузки?

**Comment by exelents** [comment]
Функция подгрузки макабы корректирует время нормально, а кукла подгружает московское. Так что скорее всего недоработана кукловская подгрузка.

**Comment by Y0ba** [comment]
Кукла не работает с макабовскими функциями. Точка. Выключай макабовскую функцию корректирования времени и используй встроенную в куклоскипт.

**Comment by exelents** [comment]
А всё понял к чему ты. Ну так и сделаю.
