### ISSUE TITLE
Ошибка закачки webm

### ISSUE THREAD

**Issue by YellowSM** [SthephanShinkufag/Dollchan-Extension-Tools#896]
Начиная с коммита https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/commit/f35e4ed38208cc3f9cbb06d5393007795cdcb5d2 вебм не заливаются - пишет "Файл поврежден".

На https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/commit/1d6794e0f959ad6865c714f9b721b47f45b4ad82 - всё нормально

**Comment by Y0ba** [comment]
Любые webm?

**Comment by YellowSM** [comment]
Ну да, любые. Я как конвертировал ffmpeg'ом так и конвертирую.
И старые и новые - не грузятся.
Откатываюсь на https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/commit/1d6794e0f959ad6865c714f9b721b47f45b4ad82 - всё работает.
