### ISSUE TITLE
Капча в разделе /s/

### ISSUE THREAD

**Issue by IndigoHuman** [SthephanShinkufag/Dollchan-Extension-Tools#898]
Модераторы ввели капчу только в раздел **/s/**, а в **/b/**, например, её нет. Скрипт скрывает капчу во всех разделах. Это самому пофиксить можно? В настройках ничего такого не нашел. Пытаюсь обновить скрипт - пишет, что версия последняя уже установлена. Видимо, не обновляли.

**Comment by Y0ba** [comment]
В последней версии исправлено: https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/raw/master/Dollchan_Extension_Tools.user.js

**Comment by Y0ba** [comment]
Суть в том, что версию ещё не апнули. По ссылке выше будет всегда последняя версия. Либо если у тебя хроморасширение, то там надо только ждать. Степан обещал обновить, но куда-то пропал.
