### ISSUE TITLE
Стирание удалённых постов без перезагрузки

### ISSUE THREAD

**Issue by HYBRID-BEING** [SthephanShinkufag/Dollchan-Extension-Tools#899]
Вручную (по-дефолту; например, нажатие на надпись "удалён"), либо автоматически (по настраиваемому таймеру).
PS: возможно ли определить посты удалённые собой? Если да, то для них неплохо было бы иметь отдельный таймер (или даже отдельную опцию).

**Comment by Y0ba** [comment]
Удалить можно средствами CSS:
```css
.de-wrap-removed { display: none; }
```
> возможно ли определить посты удалённые собой?

Можно. Но нужно ли? Можно добавить дополнительный класс и скрывать правилом `.de-wrap-my.de-wrap-removed { display: none; }`

**Comment by HYBRID-BEING** [comment]
> Но нужно ли?
Ну, например, юзер мог бы скрывать посты удалённые собой автоматически, а удалённые другими вручную.
