### ISSUE TITLE
Firefox x64 - всё плохо!

### ISSUE THREAD

**Issue by XakepSDK** [SthephanShinkufag/Dollchan-Extension-Tools#900]
Работает через раз на 64 битной версии firefox.
Загружается только некоторая часть скрипта, а точнее:
Можно зайти в настройки, но кнопки не работают.
Отсутствует задний фон у меню снизу и в настройках.
Посты при наведении появляются, но не исчезают.
И еще много других багов.

**Comment by Y0ba** [comment]
Что за 64-битный Firefox? Официальный или какая-то сборка? Версия лисы какая?

**Comment by XakepSDK** [comment]
44.0.1,  официальная версия.

**Comment by XakepSDK** [comment]
Нашел проблему. Random agent spoofer, При различных агентах скрипт может глючить.
Это в скрипте фиксы для браузеров или greasemonkey шалит?

**Comment by Y0ba** [comment]
Угу. Скрипт некоторые фичи детектирует по UA браузера.

Что касается CSS большую часть костылей уже можно убрать.

**Comment by XakepSDK** [comment]
Добавь возможность изменить UA браузера в самом скрипте.

**Comment by Y0ba** [comment]
Низзя. Скрипт подобное не контролирует. Щас закоммичу исправление в котором лиса > 40 версии сможет работать с любым UA. В твоём случае этого будет достаточно.

**Comment by Y0ba** [comment]
> сможет работать с любым UA

С единственным исключением: в хоткеях не будут работать клавиши `-`, `=`, `;`. В разных браузерах для них разные коды, лол.

**Comment by XakepSDK** [comment]
Ну что, когда там коммит?

**Comment by Y0ba** [comment]
Пробуй: https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/raw/master/Dollchan_Extension_Tools.user.js

Браузерозависимый код ещё остался в некоторых местах, но вроде как больше ломать работу скрипта не должен.

**Comment by XakepSDK** [comment]
Нет, не работает. Заднего фона всё так же нет.

**Comment by XakepSDK** [comment]
http://puu.sh/n4ajG/671c82a00d.png

**Comment by Y0ba** [comment]
Какой именно браузер стоит в Random agent spoofer?

**Comment by Y0ba** [comment]
Пробуй ещё раз: https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/raw/master/Dollchan_Extension_Tools.user.js

**Comment by XakepSDK** [comment]
Спасибо, всё работает, но небольшие проблемы всё же есть.
На некоторых браузерах не видно иконки кнопок(задний фон есть), хотя сами он работают.

**Comment by Y0ba** [comment]
На каких именно?

**Comment by XakepSDK** [comment]
Konqueror  4.14.2 linux. Пока только с ним косяк.

**Comment by XakepSDK** [comment]
Еще если поставить этот UA, зайти в раздел - кнопок не будет. Если же сменить UA и обновить через ctrl+f5, то не поможет. Необходимо пересоздавать вкладку.

**Comment by Y0ba** [comment]
УМВР. Возможно влияние других настроек. Особенно тех, которые инжектируют скрипты.
