### ISSUE TITLE
Не работает скрытие ответов на скрытые посты, если посты были скрыты по спеллу.

### ISSUE THREAD

**Issue by Sweetsound** [SthephanShinkufag/Dollchan-Extension-Tools#904]
Сабж, на харкаче. Проверялось с включённой опцией "удалять скрытые посты".

**Comment by SthephanShinkufag** [comment]
Действительно, опция "Скрывать ответы на скрытые посты*" не работает.
Это из-за коммита 12b80e377836f2c3fd35d724b108647ab1265c41, надо смотреть.

**Comment by Y0ba** [comment]
Я сейчас как раз этим занимаюсь. Точнее не совсем этим, просто переделываю код для сохранения постов. Чтобы (1) можно было удалять все скрытые посты из определённого треда (например если он удалён и выдаёт 404 ошибку) и (2) унифицировать сохранение скрытых и своих постов.

**Comment by SthephanShinkufag** [comment]
Алсо, отсутствует меню "Скрыть с ответами" кнопки скрытия.
