### ISSUE TITLE
При копировании URL webm'ок получается странного вида ссылка.

### ISSUE THREAD

**Issue by ShanellRoR** [SthephanShinkufag/Dollchan-Extension-Tools#905]
К примеру blob:https%3A//2ch.hk/4bf971e8-5db6-450f-b9db-aae690575c6b - результат копирования  одной из вебмок. При их сохранении, так же происходит что-то странное, вот свойста скачаного файла.
![ss 2016-03-06 at 03 29 00](https://cloud.githubusercontent.com/assets/17355822/13551457/983e3ea2-e34b-11e5-97ce-ec7cebb64135.png)

**Comment by SthephanShinkufag** [comment]
А каким образом вы его сохраняете? Чем, по какой ссылке? Что за браузер?

**Comment by ShanellRoR** [comment]
Разобрался. Моя вина была. Включил в кукле пункт "Распознавать встроенные файлы в картинках*" После его отключения ссылки пришли в нормальный вид, как и сохраняемые файлы. Извиняюсь за беспокойство.

**Comment by SthephanShinkufag** [comment]
Если открыть вебмку в новой вкладке, а потом оттуда сохранить, то она будет сохраняться в Лисе как `index.webm`, а в хроме, как указано у вас, `01d7ada8-20ed-4a75-ba99-35d8357e1a30`.

**Comment by SthephanShinkufag** [comment]
Нужно сохранять через конеткстное меню, "Сохранить ссылку как".
