### ISSUE TITLE
При навигации по сслыкам не отображаются картинки на 2ch.hk

### ISSUE THREAD

**Issue by velikain** [SthephanShinkufag/Dollchan-Extension-Tools#907]
![temp](https://cloud.githubusercontent.com/assets/17727938/13608574/7eec13c6-e566-11e5-95d2-210bd24b7d14.jpg)
Собственно пикрелейтед. При нажатии на ссылку картинки выводится ссылка, к примеру, https://2ch.hk/src/365339/14574460223430.jpg По ней ничего не находится. Правильный адрес картинки будет с указанием доски, то есть https://2ch.hk/bi/src/365339/14574460223430.jpg

**Comment by Y0ba** [comment]
Ставь последнюю версию: https://raw.github.com/SthephanShinkufag/Dollchan-Extension-Tools/master/Dollchan_Extension_Tools.user.js

Алсо, если стоит расширение в хроме, то переустанови скрипт вторым или третьим способом: https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/wiki/installation#google-chrome
