### ISSUE TITLE
Положение на странице

### ISSUE THREAD

**Issue by e6opoteh** [SthephanShinkufag/Dollchan-Extension-Tools#909]
При перезагрузке страницы с включенным скриптом сохраняется положение скролла, например если страница была пролистана до конца, то после перезагрузки она так и останется пролистанной до конца. 
Без скрипта положение скролла ставится в ноль как положено.
Это баг или фича? Отключить можно?

--------------------------------------------------
Mozilla/5.0 (Windows NT 6.1; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0 [20160210153822]
v16.3.9.0.d01e97f [Greasemonkey]

**Comment by Y0ba** [comment]
Фича. Вернуть можно в настройках -> Общее -> Всегда скроллить в топ на доске.

@SthephanShinkufag может лучше включить опцию по-умолчанию?

**Comment by e6opoteh** [comment]
Спасибо, извиняюсь за тупость.
