### ISSUE TITLE
[BUG] Возможно некорректная работа функции "Удалять скрытые сообщения"

### ISSUE THREAD

**Issue by userneu** [SthephanShinkufag/Dollchan-Extension-Tools#911]
Проверено на трех бордах (Двощ, Ычан, Доброчан). Схема такая:
1. Заходим на доску с включенной функцией из сабжа
2. Скрываем любой тред
3. Заходим в настройки и отключаем функцию из сабжа
4. Открываем тред, который мы только что скрыли
5. Он раскроется, только без ОП-поста. 
Firefox 43, v16.3.9.0.95850a2

**Comment by Y0ba** [comment]
Проблема скорее всего в том, что скрытые посты синхронизируются (если ты скрыл/раскрыл пост на одной открытой вкладке, то он скроется/раскроется во всех), а вот настройки - нет. Потому и получается, что на разных страницах скрипт ведёт себя по разному. По идее можно синхронизировать настройку "Скрывать ответы на скрытые посты", особенно сейчас, когда она работает без обновления страницы, но стоит ли?

**Comment by Y0ba** [comment]
Хотя по мне так скрытие ОП-поста в открытом треде вообще не имеет смысла и нужно скрипту запретить так делать.

**Comment by userneu** [comment]
Но я все делаю на одной вкладке!

**Comment by Y0ba** [comment]
И правда. В консоли ошибок (Ctrl+Shift+J) после совершения этих действий что-нибудь появляется?

**Comment by Y0ba** [comment]
Только я не понимаю как ты его открываешь. Это сделать не так просто, учитывая что ссылка  `№XXXXXX` не ведёт на него (а должна?)ю

**Comment by userneu** [comment]
Неа, консоль никак не реагирует на эту процедуру. 
>Только я не понимаю как ты его открываешь. Это сделать не так просто, учитывая что ссылка №XXXXXX не ведёт на него (а должна?)ю
Жму на эту ссылку с номером ОП поста. Он открывается. Ааааа, ты не понял. 4 шаг я имел ввиду РАСКРЫВАЕМ тред, а не входим в него.

**Comment by Y0ba** [comment]
А как это выглядит? Можешь сделать скриншот? Плюс запости сюда текст из Настройки -> Инфо -> Отладка.

**Comment by userneu** [comment]
![1](https://cloud.githubusercontent.com/assets/4303295/13731508/e43b77f8-e97b-11e5-83fa-c77f96f6f27c.JPG)
![2](https://cloud.githubusercontent.com/assets/4303295/13731509/e43c2694-e97b-11e5-8a98-18f8e1f280a7.JPG)
ДО и ПОСЛЕ

Отладочная
http://pastebin.com/38ypk1k9

А у тебя что, не воспроизводится?

**Comment by Y0ba** [comment]
О, аонял в чём дело. Это конфликт с опцией `Удалять скрытые посты`. Раньше когда надо было перезагружать страницу его не было видно, а сейчас можно добиться.

**Comment by Y0ba** [comment]
Я почему-то сначала думал что речь про `Скрывать ответы на скрытые посты`, потмоу и не мог воспроизвести. Видимо надо идти спать.
