### ISSUE TITLE
Использовать chaptcha для автоматического ввода капчи на 2ch.hk

### ISSUE THREAD

**Issue by Kagami** [SthephanShinkufag/Dollchan-Extension-Tools#913]
[Пример использования.](https://github.com/Kagami/chaptcha/blob/master/chaptcha.user.js) Демо:

![cap](https://cloud.githubusercontent.com/assets/533383/14257227/da2552dc-faad-11e5-9a5b-5fa54748fe0a.gif)

Сейчас вероятность распознавания достигает 50%.

**Comment by Y0ba** [comment]
Ммм, интересно. А есть возможность скомпилировать всё это в WebAssembly или asm.js? Чтобы без внешних сервисов.

А так могу только сделать API через `window.postMessage`. Хотя и с `MutationObserver` он работает нормально.

**Comment by Kagami** [comment]
Теоретически можно, но вряд ли будет сильно практично — одна нейросеть весит под 9 мегабайт, да и зависимостей полно. Можно переписать на какие-нибудь нативные жс-фреймворки и оптимизировать размер сети (хорошо сжать/перевести в бинарный вид) и может в фоне всё это подгружать, но у меня столько времени под это дело не найдётся.

**Comment by SthephanShinkufag** [comment]
Я не рекомендую каким-либо образом связывать куклоскрипт с распознаванием капчи. Администрация может *крайне* неготивно отнестись к этому, вплоть до блокировки пользователей с куклоскриптом (либо самого скрипта). И для нас это будет заранее проигрышный бой. Давайте жить в мире.
