### ISSUE TITLE
Не работает в Safari 9.1.1 (11601.6.16)

### ISSUE THREAD

**Issue by htthis** [SthephanShinkufag/Dollchan-Extension-Tools#914]
Уже с пол года, как минимум, не работает на Safari, а точнее - не отправляет посты. Выдает ошибку: "bind@[native code]
FormData
html5Submit$
tryCatch
invoke

continuer
continuer@[native code]

spawn
onsubmit"

Не работает ни на одной доске. В хроме такой проблемы нет.

**Comment by SthephanShinkufag** [comment]
Теперь Сафари <10 работают нормально. Проверял в 8 и 9 версии.
