### ISSUE TITLE
[FR] API для сторонних скриптов

### ISSUE THREAD

**Issue by desudesutalk** [SthephanShinkufag/Dollchan-Extension-Tools#917]
Ребята, а можно прикрутить каким-либо образом что-то на подобии API в куклоскрипт?

Пример: куклоскрипт может слушать евенты на `body`. И например если получает `de-submit`, то отправляется форма. А если получает `de-attach`, то берёт из евента урл (blob к примеру) и прикрепляет его к посту как файл.

Ещё хотелось бы добавлять некий препроцессор к сообщению - функция которая парсит пост перед его отправкой (подчищает пустые строки в конце/начале, или заменяет вещи типа `~~потёрто~~` на  `потёрто^H^H^H^H^H^H^H`)

Ну или может сделать что-то типа пользовательского JS. Иногда хочется приделать какие-то мелочи к скрипту.

**Comment by Y0ba** [comment]
Можно. Уже была такая идея. Выглядеть получение АПИ будет так:
```js
function getDollchanAPI() {
	return new Promise((resolve, reject) => {
		var onmessage = ({ data, ports }) => {
			if(ports && ports.length == 1 && data == 'de-answer-api-message') {
				document.defaultView.removeEventListener('message', onmessage);
				resolve(ports[0]);
			}
		};
		document.defaultView.addEventListener('message', onmessage);
		document.defaultView.postMessage('de-request-api-message', '*');
		setTimeout(() => {
			document.defaultView.removeEventListener('message', onmessage);
			reject();
		}, 10000);
	});
}
```
Ну а дальше регистрация на нужные АПИ становится тривиальной:
```JS
getDollchanAPI().then(port => {
	port.onmessage = ({ data }) => {
		switch(data.name) {
			case 'registerapi':
				for(let key in data.data) {
					if(data.data[key]) {
						console.log(`API ${ key } зарегистрирован.`);
					} else {
						console.log(`API ${ key } недоступен.`);
					}
				}
				break;
			case 'sendmessage':
				var newData = handleSendMessage(data.data);
				port.postMessage({ id: data.id, data: newData });
				break;
		}
	};
	port.postMessage({ name: 'registerapi', data: ['sendmessage'] });
}).catch(() => console.log('Старая версия куклы без поддержки АПИ'));
```

**Comment by Y0ba** [comment]
Только надо придумать какие АПИ добавить и какие аргументы им нужны, каким образом сообщать об ошибках (например если пользователь отменил отправку данных нажав ESC, пока сторонний скрипт обрабатывал сообщение и картинки, для этого и используется `data.Id` в ответе вместо имени АПИ) и вообще додумать архитектуру АПИшек.

С пересылкой крупных данных (как картинки) проблем не будет, поскольку все браузеры позволяют отправлять `ArrayBuffer`ы без копирования таким образом:
```JS
var bigData = new Uint8Array(1005000);
<...>.postMessage({ data: bigData }, [bigData.buffer]);
```

**Comment by desudesutalk** [comment]
Ого, звучит круто.

Я на самом деле кроме операций с формой ответа пока других функций не вижу. Отчего вообще тикет завёл: хочется иметь возможность добавлять в форму ответа свои кнопочки, хочется перед отправкой править текст поста и хочется прилеплять сгенерированные скриптом файлы к посту.

Свои кнопки вставить не проблема, благо форма ответа не уничтожается и они не пропадут. А вот с остальным проблема.

Для прикрепления файла думаю хватит самого содержимого и имени файла. А для обработки поста - лишь самого текста (в обе стороны). Больше ничего придумать не могу ибо нет других идей для этого АПИ.

**Comment by Y0ba** [comment]
Т.е. как я понял тебе нужно:

1. Получить текст и данные поста (чтобы самому не возиться с нужными селектами для разных борд).
2. Заменить текст и данные поста.
3. Получить список выбранных пользователем картинок.
4. Зарегистрироваться на событие, которое будет возникать при добавлении/удалении пользователем картинки.
5. Получить содержимое картинки в виде типизированного массива по её ID (ID берётся либо из списка, либо из события добавления).
6. Возможность удалить картинку по ID, либо добавить или заменить картинку отправив типизированный массив с дополнительными метаданными, в которых помимо имени и типа можно будет отключить возможность добавления раржпега и добавление случайных байтов в конец файла.
7. Возможность инициировать отправку поста.

**Comment by desudesutalk** [comment]
Ты как-то прям круто взялся.

Давай проще поступим, вот есть у меня такой [скриптик](https://github.com/desudesutalk/randomtrash/tree/master/sir). Хочется портировать его под куклоскрипт. То есть я ожидаю такого действия:

1. Пользователь пишет пост и жмёт кнопку отправить
2. Мой костылик получает эвент типа "de-before-post" в котором есть поля формы и инфа про наличие аттачмента выбраного пользователем.
3. Костылик чистит текст поста от лишних пустых строк. Возможно делает ещё какие-то замены
4. Если пользователь ничего не выбрал, то костылик берёт либо рандомный файл из выбранных ранее, либо генерит картинку каким-либо образом.
5. Возвращает всё это обратно куклоскрипту
6. Куклоскрипт берёт эти новые значения и использует их при отправке поста.

А для управления своим костыликом я пару кнопочек добавлю в форму. (выбрать пак, включить генератор картинки)

**Comment by desudesutalk** [comment]
И да, возможность инициировать отправку поста с передачей аттачмента тоже круто, но это уже для ДДТ больше.

**Comment by desudesutalk** [comment]
Ах да, ещё вспомнил - было бы неплохо получать эвент при появлении новых постов. Если там ещё будут и соответствующие html-ноды переданы, так вообще супер.

**Comment by desudesutalk** [comment]
Есть новости, парни?

Ещё вот что хотел бы добавить: возможность из скрипта на борде детектить что у юзера куклоскрипт. Но чисто из благих намерений - не запускать свои скрипты, если анону куклоскрипт нравится больше.

Пока детекчу так: `if(!document.querySelector('head style#de-css-dynamic')) init();` - всё правильно делаю? Проверка случается на `DOMContentLoaded` и вроде бы работает.

**Comment by SthephanShinkufag** [comment]
Идея API через postMessage кажется единственно возможной.
Но выше предложенные Йобой функции подразумевают использование юзерами ES6...
Код невероятно усложнится, если это делать в обычных скриптах.

**Comment by Y0ba** [comment]
Нет. Там ES6 не нужен. Только промисы и Channel Messaging API. Проблемы могут быть только с лисой, которая последнее поддерживает только с 41 версии.

**Comment by Y0ba** [comment]
Впрочем учитывая, что на данный момент самая свежая версия лисы 48, то можно спокойно это проигнорировать.

**Comment by SthephanShinkufag** [comment]
Главное, потом хорошо это всё задокументировать, и се про это знали а то так и останется костылём для 1 человека.
Вообще, пора уже мануал по скрипту пейсать. По каждой опции, кнопке, галочке. Описать недокументированные особенности. Есть чем заняться долгими зимними вечерами.

**Comment by Y0ba** [comment]
Уже начал немного пилить API.

**Comment by SthephanShinkufag** [comment]
Круто. Люблю тебя, Йоба. Ты можешь в очень крутые вещи, порой которые мой гзом не способен осилить и постигнуть. Я до сих пор нормально не воспринимаю промисы и асинхронщину. Точнее кое-как воспринимаю, но быстро в этом вязну и теряю общую картину.

**Comment by SthephanShinkufag** [comment]
https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/wiki/dollchan-api

**Comment by VisualKei** [comment]
@Y0ba 
> Впрочем учитывая, что на данный момент самая свежая версия лисы 48, то можно спокойно это проигнорировать.

А можно не игнорировать некролисоюзеров и добавить костыль на отсутствие? А то после [этого коммита](https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/commit/51f7a7d924328032363a322d93cda958099260ca) у меня скрипта тупо нет, в консоли ничего. На сам функционал мне пофиг, просто чтобы остальное работало при отсутствии Channel Messaging API.

**Comment by Y0ba** [comment]
@VisualKei 
А если изменить `if(!MessageChannel) {` на `if(!window.MessageChannel) {` скрипт начинает работать?

**Comment by SthephanShinkufag** [comment]
Лучше `if(!('MessageChannel' in window))`

**Comment by pngcrypt** [comment]
Извините, что вмешиваюсь, господа.
@Y0ba  ответь плиз: https://gist.github.com/Y0ba/4625903

**Comment by VisualKei** [comment]
Да, после обоих вариантов вроде всё норм, спасибо!

**Comment by pngcrypt** [comment]
Немного оффтоп, но по событиям.
Никто не знает как можно при отлове события, добавленного addEventListener, дождаться выполнения всех других обработчиков, слушающих это же событие, и лишь потом выполнить свой код. Т.е. мне нужно обрабатывать событие последним независимо от очереди.
А то я тыких костылей нагородил, что самому страшно.
