### ISSUE TITLE
Отправка поста, "фоновая" загрузка треда.

### ISSUE THREAD

**Issue by insciq** [SthephanShinkufag/Dollchan-Extension-Tools#919]
Суть проблемы:
Борда https://ponyach.ru/b/
При постинге в тред в котором много постов, отправка поста сильно замедляется, потому что доллчанскрипт после POST запроса фоном выкачивает _весь_ тред.
Вот так это выглядит в дебагере:
![](http://i.imgur.com/2wRpFkq.png)

У нас у тредов есть 5-постов версия, раньше отдавалась она, но потом что-то в скрипте изменилось.
Не могли бы вы пожалуйста этот GET запрос, сразу после постинга, перенаправлять на 5-постов версию треда? Версия с 5 постами находится по такому же адресу где и обычный тред, только перед айди треда стоит 005, например:
https://ponyach.ru/b/res/1667280.html - обычный тред
https://ponyach.ru/b/res/0051667280.html - 5-постов версия

**Comment by Y0ba** [comment]
А смысл? Нужно ведь не пять постов, а все посты которые появились после последнего обновления. А то с пятью постами можно и скрипт сломать, если за время отправки будет написано больше пяти постов. Да и тогда все предшествующие посты скрипт просто пометит как удалённые, а потом может вставит их снова (а может и не вставит, я уже не помню от чего это зависит).

Если проблема в меедленной динамике, то делайте как на форчане: отправку постов асинхронной. А сам html-треда обновляйте раз в пару секунд (или до первого запроса, но не чаще), если есть изменения, а не после каждого нового поста.

**Comment by insciq** [comment]
Боюсь что делать асинхронную отправку в нынешнем состоянии нам малореально.  
В таком случае, можно ли добавить этому GET запросу какой-нибудь хедер/параметр, например, по которому можно было бы задетектить его? А мы бы уже исходя из этого отдавали с сервера нужные посты, а не весь тред.

**Comment by Y0ba** [comment]
Это называется JSON-апи. Только продумайте тему с удалением/редактированием постов. Именно удаление мешает полноценно реализовать скрипт поверх API на доброчане.

**Comment by insciq** [comment]
Опять же, реализация полноценного апи и специальный хедер/параметр для решения единственной проблемы это всё же разные вещи.  
Так что если будет возможность реализовать этот хедер/параметр для нас, то мы будем безмерно благодарны.  
Большое спасибо за внимание.

**Comment by Y0ba** [comment]
На самом деле, JSON-апи было бы идеальным решением, поскольку сильно снизило бы нагрузку на сервер при каждом AJAX-обновлении вообще. А сделать их можно очень просто: кукла отправляет на сервер в GET-запросе уникальный номер последнего поста, а в ответ получает что-то вроде:
```json
{
    deleted: [ 989898, 7878777, 777467],
    new: {
        777575: "полный html-поста",
        ...
    }
}
```
Где в `deleted` массив со всеми ноиерами удалённых постов в треде. Алсо, можно выдавать 304-ошибку, если тред с тех пор не изменился. Тогда и само AJAX-обновление станет быстрее (и будет потреблять меньше памяти), поскольку не надо будет каждый раз анализировать весь тред.

**Comment by xcheerilee** [comment]
Привет, Йоба!

Мы согласны с тобой по поводу json-апи.
Мы тоже обдумывали схожие мысли на тему апи, снижения нагрузки и списков удалённых/новых/.. постов и дофига всего другого.

Проблема в том, что в данный момент у нас очень большой и лапшовый движок.
Прикрутить апи к тому, что есть нереально, но мы работаем над этим, парни пилят нормальный движок. С апи и шлюхами.

Хочу предложить вот такой компромисс (пока у нас нет нормального апи):
Не могли бы вы отдавать при запросе аяксом какой-нибудь хедер с номером последнего известного (скачанного) кукле поста?
Мы будем отдавать версию треда с ОП + сколько надо постов.
Наш движок позволяет это легко сделать и работать будет хорошо за счёт кешей там удачных.
