### ISSUE TITLE
спелл отвечающий за замену строчных букв на заглавные не работает

### ISSUE THREAD

**Issue by CTATEH** [SthephanShinkufag/Dollchan-Extension-Tools#920]
я имею в виду этот спелл:

> #outrep(/(>>\d+)\s*(?!\n)/g,$1\n)

я конечно наделал кучу костылей которые делают то же самое, но всё равно некорректно обрабатывается случай, когда надо заменить букву в самом начале поста.

как в регексах обозначить начало строки? я пробовал писать что-то вроде

> #outrep(/\nl/g, \nL)

но это срабатывает только в ответах, когда есть перевод строки после номера поста на который отвечаю. пробовал использовать символ ^ который вроде используется в яваскрипте как символ начала строки, но он так и не заработал.

**Comment by CTATEH** [comment]
бумп.

**Comment by Y0ba** [comment]
> как в регексах обозначить начало строки?

`#outrep(/(^|\n)l/g,$1L)`

Пробел после запятой не нужен.
