### ISSUE TITLE
[BUG] Надоедливые алерты OK на 410chan.org

### ISSUE THREAD

**Issue by deterenkelt** [SthephanShinkufag/Dollchan-Extension-Tools#921]
На входе/выходе из треда, а также при смене доски — но только в случае, если на той доске, куда осуществляется переход, есть мои посты — появялется алерт с текстом «ОК». Проявляется только при включённом DE. Через несколько переходов срабатывает браузерная защита от попапов, но пока она сработает, эта хрень будет раздражать, плюс защита работает только в пределах вкладки, то есть закрыл вкладку, открыл снова — привет, попапы.

DE 16.3.9.0
GM 3.8
FF 39

**Comment by aslian** [comment]
Но в скрипте вообще не используется `alert()`.

```
user@local ~/dev/Dollchan-Extension-Tools $ grep 'alert(' src/Dollchan_Extension_Tools.es6.user.js 
user@local ~/dev/Dollchan-Extension-Tools $ 
```

Что-то у тебя там другое генерирует эту фигню.

**Comment by deterenkelt** [comment]
Я и не говорил, что это доллчан их генерит. Но он как-то триггерит их в движке борды, что они там появляются.

**Comment by aslian** [comment]
Хм, наверное вот здесь?


![screenshot_2016-05-31_06-43-31](https://cloud.githubusercontent.com/assets/3952177/15662607/07776206-26fb-11e6-881c-92d4206ca681.png)

**Comment by aslian** [comment]
В общем, ковырнул ещё это.

![](https://u.nya.is/ucshwd.png)
В автобусе в инлайн-скрипте вызывается `request_faptcha('b')`, которая затем вызывает `handle()`. Эта `handle()` пытается найти инпут для ввода капчи `#faptcha_input`, но кукла его уже убрала. Отсюда и валится в catch-блок.

Соус [сказал, что ничего у себя править не будет](http://410chan.org/d/res/701.html#40).

Что делать?
1. Переопределять handle()
2. Что-то зафиксить в этом механизме отложенной загрузки капчи для автобуса, там, удалять только саму картинку капчи, а не всю строку из формы, только скрывая её, например. Я тут посмотрел `class Captcha` и офигел. Не знаю где там этот код.
