### ISSUE TITLE
TinyIb

### ISSUE THREAD

**Issue by Y0ba** [SthephanShinkufag/Dollchan-Extension-Tools#925]
Пришло мне тут письмо:

Здравствуй, Y0ba.

Вознамерился я тут добавить в Куклоскрипт поддержку движка TinyIB https://github.com/tslocum/TinyIB.
Стадия "пустой страницы" была успешно пройдена вот таким куском кода:
![unnamed](https://cloud.githubusercontent.com/assets/1163958/15789219/ba4c4be6-29d3-11e6-86fa-775bf716440c.png)

А вот дальше застрял. Проблема в том, что Кукла не видит самый последний пост в треде. Выглядит это как-то так https://a.pomf.cat/boojkv.png.

 Тут стоит упомянуть, что TinyIB генерирует такой html-код, где треды не "обёрнуты" в какой-либо отдельный класс, вроде `.thread`. Как и ОП-посты. 
![unnamed1](https://cloud.githubusercontent.com/assets/1163958/15789241/cf589bb6-29d3-11e6-9e14-e59d845b8fc8.png)

То есть отделяются они друг от друга только `<hr>`.

Нашёл в классе дельформы такой метод
![unnamed2](https://cloud.githubusercontent.com/assets/1163958/15789259/e1eb25f0-29d3-11e6-98a2-3828c6439253.png)
Но чёт неосилил подправить.

Ещё метод `aib.getOmitted()` почему-то возвращает на один пост больше. Я попробовал переопределить его в своём классе TinyIB, и декрементировать возвращаемое значение, но это не помогло. Пробовал убавлять/прибавлять единицу к разным счетчикам, которые находил в классах `DelForm`, `Post` и `Thread`... 

Честно говоря, не знаю куда дальше копать. Помоги, пожалуйста

P.S.: Ещё, поясни пожалуйста, чем отличается `cReply` от `qRPost`.

**Comment by aslian** [comment]
А чего перемещать-то?.. Можно было просто поправить и закоммитить :3
Быстро же ты ответил, однако.

**Comment by Y0ba** [comment]
Итак.
> P.S.: Ещё, поясни пожалуйста, чем отличается cReply от qRPost.

`cReply` по большей части используется для взятия фонового цвета постов для разных контролов куклы, а вот `qRPost` уже в запросах для поиска постов. Просто иногда сама борда использует классы постов как в `cReply` для всяких левых элементов, поэтому `qRPost` обычно фильтрует посты более строго.

**Comment by Y0ba** [comment]
> А чего перемещать-то?

Честно, мне так более привычно.

Кстати, вроде поддержка `tinyIb` когда-то была в скрипте. Степан почему-то её убрал.

**Comment by SthephanShinkufag** [comment]
Все борды с этим движком умерли. Неиспользуемый хлам ненужен.

**Comment by aslian** [comment]
@SthephanShinkufag 
Категорично. Но ведь ты же сам как-то говорил, что "Кукла должна работать даже на тех бордах, о которых мы и не подозреваем", и приводил в пример, кажется, Hispachan.

**Comment by SthephanShinkufag** [comment]
Есть ли сейчас борды с этим движком, чтобы посмотреть?

**Comment by aslian** [comment]
Хотелось конечно обойтись без этого, но ладно. `board.d3w.org`

**Comment by SthephanShinkufag** [comment]
Исправлено. Проверяйте.

**Comment by aslian** [comment]
@SthephanShinkufag 
Угу, работает.
Ещё добавьте пожалуйста
```
		this.qError = 'body[align=center] div';

		get css() {
			return `.replymode { display: none; }`;
		}
```

Сожалею, что пришлось делать двойную работу, вылавливая баг-для-одной-аиб (https://github.com/aslian/Dollchan-Extension-Tools/commit/4732ea201944ab03be16ce7ff0ef770acf2fb826?), что-то я вчера морозился отправить коммент (чёрт, вот эта фигня и руинит жизни стеснительных - "меня заметят, меня повысят", лол)

Что заметил из слегка глючащего:
1.
```
Не могу удалить:
Post deleted.
```
Там в сообщениях борды разделения на обычные собщения/ошибки нет как такового. Кукла такое может как-то отлавливать, или и так сойдет?

2.
> Post truncated. Click Reply to view.

Не даёт ссылку на разворот поста, как на Ычане.

**Comment by SthephanShinkufag** [comment]
Давайте уточним еще раз. Это действительно движок, или какое-то поделие для вашего домена, который вы указывали (но потом стрели)? Если это движок, укажите все известные вам домены с этим движком. Иначе я его переведу в разряд доменов.

**Comment by SthephanShinkufag** [comment]
Желательно, чтобы скрипт детектировал вашу борду по домену. А то получается, скрипт будет выполнять лишнюю проверку движков ради одной вашей мелкоборды.

**Comment by aslian** [comment]
Ну да, это действительно движок.
Я что-то не понимаю сути вопроса, разве ссылка на репозиторий, со старами и форками не доказывает это?

Известных доменов с этим движком у меня нет. Можно загуглить `" futallaby + tinyib -"`, но все те борды умерли. Могу сказать, что видел борды на этом движке в торе, например.

И разве более абстрактный код не лучше обработки конкретного случая?

> скрипт будет выполнять лишнюю проверку движков 

Это **действительно** так сильно влияет на производительность?

**Comment by Y0ba** [comment]
> Это действительно так сильно влияет на производительность?

Один лишний `querySelector` на всех сайтах при стандартных настройках.

**Comment by Y0ba** [comment]
Да и на самой борде кукла будет инициализироваться быстрее, поскольку часть кода будет выполняться ещё до загрузки html-содержимого.

**Comment by aslian** [comment]
Хорошо, пущай будет по домену.

**Comment by SthephanShinkufag** [comment]
@aslian, 55543cf07fb0da82e818b57c8fd3a7c31590c538

**Comment by aslian** [comment]
@SthephanShinkufag 
Хорошо. Работает. Спасибо. Можно закрывать issue.
