### ISSUE TITLE
Chrome Web Store: Announcing a Revised User Data Policy

### ISSUE THREAD

**Issue by SthephanShinkufag** [SthephanShinkufag/Dollchan-Extension-Tools#926]
Dear Developer,

We recently announced a policy change aimed at enhancing user transparency and choice over how users’ personal data is handled. Please review the additional language on Developer Program Policy under the section “User Data Privacy.”

The new policy requires Web Store Developers to:

    Disclose their privacy practices for all types of data

    Post a privacy policy and use encryption, when handling personal and sensitive information, and

    Ask users to consent to the collection of personal or sensitive data via a prominent disclosure, when the use of the data isn’t related to a prominent feature.

If required, you must post the privacy policy in the Developer Dashboard.

The User Data Policy also has other requirements, including a new prohibition on the collection of web browsing activity when it’s unrelated to an item’s main functionality. We’ve also prepared a FAQ.

We'll be notifying developers when we discover items that violate the User Data Policy, and they'll have until July 14, 2016 to make any changes. Starting July 15th, 2016, items that violate the policy will also be removed from the Web Store and will need to become compliant to be reinstated.

If you have any questions regarding this change, please reach out to us at chromewebstore-policy@google.com.

Thank you,

Chrome Web Store Team

User Data Policy: https://developers.google.com/chrome/web-store/program_policies#userdata

User Data Policy FAQ: https://developer.chrome.com/webstore/userdata

Developer Terms of Service: https://developers.google.com/chrome/web-store/terms

Program Policies: https://developers.google.com/chrome/web-store/program_policies

Branding Guidelines: https://developers.google.com/chrome/web-store/branding

Unwanted Software Policy: https://www.google.com/about/company/unwanted-software-policy.html

Google Inc., 1600 Amphitheatre Parkway, Mountain View, CA 94043. You are receiving this one-time notification because you are a developer with items in the Chrome Web Store that are potentially impacted by this policy change.

**Comment by SthephanShinkufag** [comment]
Хроморасширение всё.

**Comment by Y0ba** [comment]
А что они конкретно хотят?

**Comment by SthephanShinkufag** [comment]
Разгребаю письма за полгода, только наткнулся. Пытаюсь вникнуть.

**Comment by SthephanShinkufag** [comment]
Я так понял, с середины июля будут введены новые правила игры.
Если расширение не будет удовлетворять **неким** требованиям безопасности, то его завернут.

**Comment by Y0ba** [comment]
Угу. Я просто не пойму что конкретно нарушает скрипт.

**Comment by SthephanShinkufag** [comment]
Никаких писем я больше от chromewebstore-dev-support@google.com не получал, только это.

**Comment by Y0ba** [comment]
Скрипт вообще не собирает никаких персональных данных. Может быть проблема в том, что он запускается везде?

**Comment by SthephanShinkufag** [comment]
Письма получили все хроморазработчики.

> Может быть проблема в том, что он запускается везде?

Да, меня многое смущает.

```
4. What does “web browsing activity” mean?

Web browsing activity means any information about the websites or other web resources a user requests or interacts with, including the domains or URLs the browser interacts with.
```

**Comment by Y0ba** [comment]
Ну, кукла их же никуда не собирает/отправляет, максимум сохраняет у пользователя в хранилище.

**Comment by SthephanShinkufag** [comment]
В том то и дело, что фиг его знает. Они могут заставить шифровать это хранилище, например. Куча неопределенных намеков, а в чем собсно суть новых требований, непонятно.

**Comment by Y0ba** [comment]
Какая разница если ключ придётся хранить в том же хранилище :\
