### ISSUE TITLE
Мультиселект

### ISSUE THREAD

**Issue by CherryPerry** [SthephanShinkufag/Dollchan-Extension-Tools#927]
> ## Abu
> 
> Из хороших новостей: на Дваче файлы выбирать теперь можно не по одному, а сразу 4 штуки. Мультиселект.

Было бы классно, если б в кукле можно было также.

**Comment by SthephanShinkufag** [comment]
Реализовано.
03e10c6acf76cea71fb01766b7e7d2380b0a40a9, #1073
