### ISSUE TITLE
Не включается скрипт на 2ch.hk/vape/

### ISSUE THREAD

**Issue by xzyxzy** [SthephanShinkufag/Dollchan-Extension-Tools#928]
В консоли FF Nightly 49:

> DELFORM ERROR:
> TypeError: sibling is null
>     at $aEnd (Dollchan_Extension_Tools.user.js:3457:3)
>     at Post (Dollchan_Extension_Tools.user.js:13683:19)
>     at Thread (Dollchan_Extension_Tools.user.js:15800:16)
>     at DelForm (Dollchan_Extension_Tools.user.js:19198:12)
>     at runMain$ (Dollchan_Extension_Tools.user.js:20443:38)
>     at tryCatch (Dollchan_Extension_Tools.user.js:2336:37)
>     at invoke (Dollchan_Extension_Tools.user.js:2542:22)
>     at defineIteratorMethods/</prototype[method] (Dollchan_Extension_Tools.user.js:2361:16)
>     at continuer (Dollchan_Extension_Tools.user.js:3644:15)
>     at async/< (Dollchan_Extension_Tools.user.js:3659:11)
>     at EventListener.handleEvent*de_main_func_inner (Dollchan_Extension_Tools.user.js:20525:3)
>     at [122]< (Dollchan_Extension_Tools.user.js:2878:11)
>     at s (Dollchan_Extension_Tools.user.js:21:246)
>     at e (Dollchan_Extension_Tools.user.js:21:425)
>     at de_main_func_outer (Dollchan_Extension_Tools.user.js:21:11)
>     at Dollchan_Extension_Tools.user.js:20:11

**Comment by SthephanShinkufag** [comment]
Альзо, дико капитулировал, зайдя на эту доску.
https://2ch.hk/vape/res/209137.html
Поехавшие какие-то, хех. Фигнербокс нервно курит в сторонке.
