### ISSUE TITLE
KC: тред недоступен если ОП забанен

### ISSUE THREAD

**Issue by e6opoteh** [SthephanShinkufag/Dollchan-Extension-Tools#929]
На краутчане в тредах, ОПа которых забанили, выдает такую вот ошибку при ajax-обновлении.

Тред недоступен (№35224992): ReferenceError: bEl is not defined at bannedPostsData$ (Dollchan_Extension_Tools.user.js:15286:9) at tryCatch (Dollchan_Extension_Tools.user.js:2336:37) at invoke (Dollchan_Extension_Tools.user.js:2542:22) at defineIteratorMethods/

При этом тред не закрыт, в него можно постить, и его можно обновить по F5.

**Comment by SthephanShinkufag** [comment]
0ec121d443812da995327e1aff674b58c1051275
