### ISSUE TITLE
Удаление постов вызывает ошибку (2ch.hk)

### ISSUE THREAD

**Issue by CherryPerry** [SthephanShinkufag/Dollchan-Extension-Tools#930]
> ReferenceError: bEl is not defined
>     at DOMPostsBuilder.bannedPostsData$ (chrome-extension://ipnoalfffblkaodfmipjjgkfbgcfadad/Dollchan_Extension_Tools.user.js:15286:33)
>     at tryCatch (chrome-extension://ipnoalfffblkaodfmipjjgkfbgcfadad/Dollchan_Extension_Tools.user.js:2336:40)
>     at GeneratorFunctionPrototype.invoke [as _invoke] (chrome-extension://ipnoalfffblkaodfmipjjgkfbgcfadad/Dollchan_Extension_Tools.user.js:2542:22)
>     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (chrome-extension://ipnoalfffblkaodfmipjjgkfbgcfadad/Dollchan_Extension_Tools.user.js:2361:21)
>     at Thread._checkBans (chrome-extension://ipnoalfffblkaodfmipjjgkfbgcfadad/Dollchan_Extension_Tools.user.js:15966:26)
>     at Thread._parsePosts (chrome-extension://ipnoalfffblkaodfmipjjgkfbgcfadad/Dollchan_Extension_Tools.user.js:16199:10)
>     at Thread._loadNewFromBuilder (chrome-extension://ipnoalfffblkaodfmipjjgkfbgcfadad/Dollchan_Extension_Tools.user.js:16174:29)
>     at chrome-extension://ipnoalfffblkaodfmipjjgkfbgcfadad/Dollchan_Extension_Tools.user.js:15877:32
>     at chrome-extension://ipnoalfffblkaodfmipjjgkfbgcfadad/Dollchan_Extension_Tools.user.js:3725:22

Ошибка появилась после удаления постов в треде. Дальнейшее обновление треда невозможно.

**Comment by SthephanShinkufag** [comment]
Но ведь на сосаче нельзя удалять посты. Когда модер посты удаляет?

**Comment by CherryPerry** [comment]
> Когда модер посты удаляет?
Да.

**Comment by CherryPerry** [comment]
> ReferenceError: $remove is not defined
    at Thread._checkBans (chrome-extension://ipnoalfffblkaodfmipjjgkfbgcfadad/Dollchan_Extension_Tools.user.js:15986:7)
    at Thread._parsePosts (chrome-extension://ipnoalfffblkaodfmipjjgkfbgcfadad/Dollchan_Extension_Tools.user.js:16204:10)
    at Thread._loadNewFromBuilder (chrome-extension://ipnoalfffblkaodfmipjjgkfbgcfadad/Dollchan_Extension_Tools.user.js:16179:29)
    at chrome-extension://ipnoalfffblkaodfmipjjgkfbgcfadad/Dollchan_Extension_Tools.user.js:15882:32
    at chrome-extension://ipnoalfffblkaodfmipjjgkfbgcfadad/Dollchan_Extension_Tools.user.js:3727:22

Сейчас такая ошибка.

**Comment by Y0ba** [comment]
Там надо просто `$remove` на `$del` поменять.

**Comment by SthephanShinkufag** [comment]
> $remove

wat

**Comment by SthephanShinkufag** [comment]
@Y0ba, ага.
