### ISSUE TITLE
Говно сделал в избранном.

### ISSUE THREAD

**Issue by apan65** [SthephanShinkufag/Dollchan-Extension-Tools#933]
Зачем убрал чекбоксы, теперь лишние телодвижения нужно делать, напрягает.
Плюс нахрена функция сворачивания тредов на доске, если при выходе из меню свернутая доска не сохраняется.
Если так нравится кому-то эта хрень, то сделай хотя бы опциональный выбор.

**Comment by YellowSM** [comment]
На самом деле зачем чекбосы убрали? Места экономится минимум, а неудобств много

**Comment by SthephanShinkufag** [comment]
Чекбоксы нужны только для удаления записей. В остальных случаях они не нужны и мешают восприятию действия. Кто-то может подумать, что можно обновлять треды, выделенные чекбоксами.
Про сворачивание тредов не понял ничего. Что за меню, что за сворачивание.

**Comment by YellowSM** [comment]
> Чекбоксы нужны только для удаления записей.
Ну а, собсно, что мешает заюзать их для всего остального?

Просто сейчас как-то не очевидно всё. Если кнопка "Обновить" применяется ко всему избранному, то логично предположить, что и кнопка Удаление так же сработает - в итоге сомнения (нажимать/не нажимать, удалится/не удалится).
Когда входишь в режим удаления появляется кнопка ОК. Опять не понятно как из него выйти? Нажать кнопку ОК (гениально, хех).  Или нажал ты случайно Удаление, потом глядишь - кнопка ОК какая-то: че за кнопка, нафига она? )

**Comment by SthephanShinkufag** [comment]
> что мешает заюзать их для всего остального?

Ну да, чтобы обновить все треды, придется выделять все галочки. Гениально.

**Comment by apan65** [comment]
> не нужны и мешают восприятию действия
Мне мешают восприятию действия отсутствие чекбоксов.

> Про сворачивание тредов не понял ничего
В избранном, щелки по названию доски, колонка свернется, еще одно бесполезное и неудобное нововведение

**Comment by SthephanShinkufag** [comment]
А мне всё нравится.

**Comment by YellowSM** [comment]
Ну да, херню предложил.
Но Раньше_было_лучше.
Можно тупо кнопку переименовать в Удалить "выделенное"

**Comment by SthephanShinkufag** [comment]
Чёт я бомбанул раньше времени. Отвык я от вас, ребята.
Пусть будет Issue, что-нибудь может еще придумаю.

**Comment by apan65** [comment]
>Чёт я бомбанул раньше времени. Отвык я от вас, ребята.
Пусть будет Issue, что-нибудь может еще придумаю.

Мне в принципе пофиг, и так сойдет, но опционально хотелось бы, чтобы была возможность оставить чекбоксы без кнопки.

**Comment by SthephanShinkufag** [comment]
> нахрена функция сворачивания тредов на доске, если при выходе из меню свернутая доска не сохраняется

Исправил, теперь сохраняется.
dc1fdb2facaaf544cfd9076b8062eb65b98ae687

**Comment by WagonOfDoubt** [comment]
Можно добавить в css-трюки:
```css
#de-fav-delbuttons > input:nth-child(2),  /* кнопка "Отмена" */
#de-fav-buttons > input:nth-child(5)  /* кнопка "Удаление..." */
{
  display: none;
}

#de-fav-delbuttons, #de-fav-buttons, .de-fav-switch {
  display: inline-block !important;
}
```
Только кнопку "Применить" следует переименовать в "Удалить" в любом случае. Применяют изменение записей, а не их добавление/удаление.

**Comment by SthephanShinkufag** [comment]
@WagonOfDoubt

Уже не актуально, я сегодня там всё переделал.
Хочу закрыть этот issue.

**Comment by SthephanShinkufag** [comment]
> Зачем убрал чекбоксы, теперь лишние телодвижения нужно делать, напрягает.

Чекбоксы удаления переделаны в крестики, и теперь отображаются **всегда**.
Если выбран хотя бы один крестик, то появляются кнопки подтверждения `"Удалить"` и `"Отмена"`.

> Чекбоксы нужны только для удаления записей. В остальных случаях они не нужны и мешают восприятию действия. Кто-то может подумать, что можно обновлять треды, выделенные чекбоксами.

Таким образом, противоречия в предназначении чекбоксов теперь больше нет:

![favorites_deletion](https://user-images.githubusercontent.com/1059874/37097082-3d2f4af6-2223-11e8-86a1-53ce89c4f6fd.png)
