### ISSUE TITLE
Куклоскрипт и переход по ссылке на пост

### ISSUE THREAD

**Issue by Garitos** [SthephanShinkufag/Dollchan-Extension-Tools#934]
При переходе по ссылке на пост вида http://_борда_/_доска_/res/_тред_.html#_пост_
Сначала переход к этому посту, а потом внезапно прокручивание на несколько постов выше.

**Comment by SthephanShinkufag** [comment]
Браузер какой?

**Comment by Garitos** [comment]
Только заметил твое письмо.
Chrome 51.0.2704.103 m
Куклоскрипт в виде отдельного приложения

2016-07-19 20:33 GMT+03:00 Sthephan Shi <notifications@github.com>:

**Comment by Garitos** [comment]
Добавлю, в 52.0.2743.82m проблема сохранилась
