### ISSUE TITLE
на iOS не открываются настройки скрипта

### ISSUE THREAD

**Issue by bjgo** [SthephanShinkufag/Dollchan-Extension-Tools#935]
iPad, iOS 7.1.2, твик Userscript Loader
с некоторых пор (сложно сказать, +-полгода) кнопка открытия настроек в углу ничего не делает. нажатие на неё обрабатывается, кнопка подсвечивается, по панель настроек не разворачивается

**Comment by SweetPalma** [comment]
Та же ситуация, но на десктопе - Safari 9.1.2, Mac OS X El Capitan 10.11.6.
