### ISSUE TITLE
Кнопка "Скрытое"

### ISSUE THREAD

**Issue by YellowSM** [SthephanShinkufag/Dollchan-Extension-Tools#936]
Продолжаю нажимать редкие кнопки )
В списке скрытого отображаются скрытые посты, но информативности этот список не несет (дата, id, номер поста). Можно, конечно, вручную раскрывать посты ну не будешь же весь список лопатить?
Может, под каждым скрытым постом в списке выдавать еще 1 строку текста из поста? Ну типа превью, для наглядности.

**Comment by SthephanShinkufag** [comment]
Я бы вообще список скрытых постов убрал, если честно.

**Comment by YellowSM** [comment]
Да пофиг если честно )
Я случайно туда залез. Так, мысли высказал

**Comment by SthephanShinkufag** [comment]
И да, 968d79dbe35b8397179f683307b391e35b02cf93
Окно Скрытое теперь содержит только скрытые треды.
