### ISSUE TITLE
English css tricks page

### ISSUE THREAD

**Issue by Zero---** [SthephanShinkufag/Dollchan-Extension-Tools#937]
Please make an english css tricks page

**Comment by UserNaem** [comment]
Challenge accepted (and completed)
https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/wiki/CSS-tricks-english

**Comment by SthephanShinkufag** [comment]
@UserNaem Thanx!
Sorry, I didn't have enough time for that.

**Comment by Zero---** [comment]
Thanks :)
