### ISSUE TITLE
krautchan.net ban notification not working and redirect problem

### ISSUE THREAD

**Issue by ganego** [SthephanShinkufag/Dollchan-Extension-Tools#938]
Hello, two issues with https://krautchan.net:
1) Since (one of?) the latest version the ban notification (that thing that slides down and gives info) does not show up. Now after uploading the post absolutely nothing happens, no notification and the text box was deleted, so you lost the post.
2) This happened for quite some time: When you go on https://krautchan.net/board/b/ and create a thread dollchan will redirect to https://krautchan.net/board/b/thread-xxxxx.html. But this path does not exist. The thread is at .net/b/thread-xxxxx.hrml (no "/board").

**Comment by SthephanShinkufag** [comment]
1) How to get a ban for one day, for example, to test that issue? When I can ask for that? :D
2) Done. I made an automatic redirection to "/<...>" from the "board/<...>". So, you just can't enter that page, oy vey!

**Comment by SthephanShinkufag** [comment]
Redirection is no longer needed, I solved that easier.
Now u can visit https://krautchan.net/board/x/ as usually.

**Comment by SthephanShinkufag** [comment]
Thx for your help. Please try again with last commit.

**Comment by SthephanShinkufag** [comment]
Wtf happened with krautchan?
Is it closed forever?

**Comment by ganego** [comment]
Nobody really knows, but lots of (false) rumors around. In IRC the topic says it will come back today. Probably some server error.

**Comment by SthephanShinkufag** [comment]
Let's hope that everything will be fine soon.

**Comment by nezouille** [comment]
Alright, hum. Krautchan is dead.
