### ISSUE TITLE
Тема постов 2ch.hk

### ISSUE THREAD

**Issue by CherryPerry** [SthephanShinkufag/Dollchan-Extension-Tools#939]
Сталкиваюсь с проблемой, при которой тема поста не отображается при загрузке новых постов, но если тред полностью перезагрузить, то тема у поста появляется. Ошибки никакой не показывается.

v16.6.17.0.81c1c93

**Comment by Y0ba** [comment]
Обнови скрипт. Уже исправлено в 4c4fea2c9d98972dc6fc6244803a50762e4f2f30.
