### ISSUE TITLE
Автосворачивание превью постов

### ISSUE THREAD

**Issue by YellowSM** [SthephanShinkufag/Dollchan-Extension-Tools#940]
Опять заметил, что вылезла проблемка, когда превьюшки постов не сворачиваются.
Самое интересное, специально повторить это не могу. А когда не задумываясь начинаешь просматривать цепочку ответов, открываешь кучу превьшек, потом колесом скролишь страницу - и закрывается только верхняя превьюха, а остальные все остаются открытые.
Я тут подумал, а можно же, наверное, при сворачивании верхней превьюшки как-то форсированно получить координаты мыши, ну или там событие перемещения мыши сгенерить - чтобы остальные превьюхи тоже его отловили?

Кстати, вот 100%-ный случай, когда превьюхи не сворачиваются - если нажать на ссылку с номером ответа - происходит скролл страницы к этому ответу и закрывается только верхняя превьюха (да и то только когда мышь потеребишь)

**Comment by SthephanShinkufag** [comment]
Не замечал такого. Хром?

**Comment by SthephanShinkufag** [comment]
> если нажать на ссылку с номером ответа - происходит скролл страницы к этому ответу и закрывается только верхняя превьюха

Хм. А вот это действительно баг.

**Comment by YellowSM** [comment]
> Хром?

Не, лиса+gm (x64 если важно).
Не сворачивается именно после прокрутки колесом. Но причину так и не понял. Частенько попадаю на это.

**Comment by YellowSM** [comment]
Сорь. Не видел уведомлений.
С кликом вроде проблема решена. За остальным понаблюдаю.

**Comment by YellowSM** [comment]
Вроде бы пока багов не было с прокруткой
