### ISSUE TITLE
Запили для Microsoft Edge

### ISSUE THREAD

**Issue by YuriBoiko** [SthephanShinkufag/Dollchan-Extension-Tools#941]
Майкрософт запилили конвертер, который преобразует расширения Chrome в расширения Edge, осталось только сконвертировать и залить в магазин. [https://www.microsoft.com/en-us/store/p/microsoft-edge-extension-toolkit/9nblggh4txvb](https://www.microsoft.com/en-us/store/p/microsoft-edge-extension-toolkit/9nblggh4txvb).

**Comment by stetzen1** [comment]
Под Edge вышел Tapemonkey, на который можно поставить скрипт.

**Comment by Kagami** [comment]
Официальная поддержка куклокрипта под Edge также позволит проигрывать в нём вебмки, путём нехитрых манипуляций:

* VP8/Vorbis: https://github.com/brion/ogv.js
* VP9/Opus: https://github.com/Kagami/webmify

**Comment by Kagami** [comment]
Тут говорят, что что-то уже работает через Tampermonkey:

![edge-det](https://cloud.githubusercontent.com/assets/533383/22674751/2389b75c-ecfb-11e6-87ff-f31783a227b6.png)

@SthephanShinkufag есть планы официальной поддержки Edge? В том плане, чтобы исправлять все его специфичные баги (в том числе вебмки).

**Comment by SthephanShinkufag** [comment]
Спасибо, друже! На досуге гляну!

**Comment by SthephanShinkufag** [comment]
1. Исправил имена у сохраняемых файлов: при сохраненнии архива с тредами, при сохранении архива с картинками, при сохранения json-файла с настройками.
2. Куклоскрипт в сохраненных тредах не работает - Microsoft Edge запрещает localStorage  в локальных файлах.
3. Добавил описание установки для Edge: https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/wiki/installation

Поддержку вебмок гляну как будет время. Пишите сюда другие баги для Microsoft Edge. Или создавайте новые Issue, чтобы тут ничего не потерялось и не осталось незамеченным.
