### ISSUE TITLE
Абу капча

### ISSUE THREAD

**Issue by YellowSM** [SthephanShinkufag/Dollchan-Extension-Tools#943]
Макака опять капчу поменял. Че-то там через api намутил.
Кукла теперь ее не видит

**Comment by YellowSM** [comment]
Ребят, поправьте пожалуйста побыстрее. А то с этой макабой я как-будто во времена command.com вернулся

**Comment by SthephanShinkufag** [comment]
Уже исправил. щас отправлю коммит.

**Comment by YellowSM** [comment]
Чет не работает

**Comment by SthephanShinkufag** [comment]
Должно.

**Comment by SthephanShinkufag** [comment]
УМВР.

**Comment by YellowSM** [comment]
Запрос-то старый идет, а там 404

**Comment by SthephanShinkufag** [comment]
Не может быть. Нет там старого запроса. Вы не обновили скрипт.

**Comment by SthephanShinkufag** [comment]
https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/commit/fb324f5570e6d2d0f59a6a3758c6b8ec2ac5ae48#diff-3ffdccae365c029e209bbfa4211be3e6R12599

**Comment by Crimson53** [comment]
Самая последняя версия, удалял, ставил по трём способам. Chrome. Всё-равно не работает. Что ещё делать?
![default](https://cloud.githubusercontent.com/assets/21067790/17714830/2a31808c-640a-11e6-8a34-89d767aa20c1.png)

**Comment by SthephanShinkufag** [comment]
Хроморасширение? Извините, туда не завёз.

**Comment by SthephanShinkufag** [comment]
Хромоги должны страдать.

**Comment by SthephanShinkufag** [comment]
Надо апнуть версию, и залить на сервер гугля. Тогда можно будет постить из хроморасширения.

**Comment by Crimson53** [comment]
Нет, на скриншоте через Tampermonkey.

**Comment by SthephanShinkufag** [comment]
Вы не обновили скрипт по ссылке.
https://raw.github.com/SthephanShinkufag/Dollchan-Extension-Tools/master/Dollchan_Extension_Tools.user.js

**Comment by Crimson53** [comment]
Да, всё заработало, спасибо.

**Comment by SthephanShinkufag** [comment]
Исправил работу с анимекапчей.
