### ISSUE TITLE
[2ch.hk] Абулик капчу сломал для скрипта.

### ISSUE THREAD

**Issue by xzyxzy** [SthephanShinkufag/Dollchan-Extension-Tools#944]
Subj.
Вот что в консоли есть.
http://i.imgur.com/KoEEKEG.png

**Comment by UserNaem** [comment]
Только что смог запостить со свежей куклой (v16.6.17.0.d3b8f7e), 2chaptcha. Возможно, виноват блокировщик рекламы. На чистом профиле Firefox всё работает? Анимекапча не работает, если что.

**Comment by SthephanShinkufag** [comment]
Исправлено вчера в последней версии же.

https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/commit/fb324f5570e6d2d0f59a6a3758c6b8ec2ac5ae48
https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/commit/71775ebcd98b3d7f8c5a7981ec73953817db6ae4

**Comment by SthephanShinkufag** [comment]
Или это со свежей версией не работает?

**Comment by xzyxzy** [comment]
Забыл упомянуть, хром 52.0.2743.116, экстеншн, не тамперманки.
Адблок выключал, стиль выключал.
Вот как выглядит форма.
http://i.imgur.com/GbY1xrY.png

**Comment by UserNaem** [comment]
Разве хроморасширение не было обновлено вчера\сегодня? Так или иначе, лучше пользоваться Tampermonkey.

**Comment by xzyxzy** [comment]
Втф. Только что заработало.
Вот, сука, только что.

**Comment by SthephanShinkufag** [comment]
@xzyxzy Видимо, обнова прилетела, хех.

**Comment by xzyxzy** [comment]
Нет. Постораюсь кратко:
1. Грузишь тред.
2. В нижней форме капчи нет.
3. Берешь любой пост, жмакаешь ответить (нижняя форма скроется) капча грузится во вспылвающей и если открыть нижнюю, там теперь она тоже есть.

**Comment by SthephanShinkufag** [comment]
Капча в формах сверху и снизу появляются по клику в текстовые поля. По умолчанию они скрыты.
Сделано для того, чтобы лишний раз не вызывать капчу, если не собираешься отвечать.

**Comment by SthephanShinkufag** [comment]
Кликните в поле ввода текста, или выберите файл - и капча вызовется. Уже джва года так.

**Comment by xzyxzy** [comment]
Поля для ввода текста-то нет. Тем более вчера капча вроде сразу показывалась.

**Comment by SthephanShinkufag** [comment]
Поле ввода комментария жеб ліл.

**Comment by UserNaem** [comment]
Кстати, почему бы не вызывать капчу не по клику по полю ввода, а по уходу из поля ввода (если такое возможно)? На абучане капча истекает за считанные секунды, всё равно придётся обновлять после написания поста.
> Поля для ввода текста-то нет.
То есть как нет?
![b_-_ _webm- _ _ _ 17 08 16 12-06-13](https://cloud.githubusercontent.com/assets/21028464/17726167/a39cc714-646a-11e6-871c-ad95c00d6fb0.png)

**Comment by SthephanShinkufag** [comment]
@UserNaem это может сбить с толку пользователя. Капчи нет, и рука сразу тянется отправить пост. А тут начнет капча вдруг вылезать. Будет раздражать.

**Comment by Y0ba** [comment]
> а по уходу из поля ввода

Те кто пользуются мышкой соснут, им придётся делать лишний клик. Да и совсем не очевидно, что капча вообще нужна.
> На абучане капча истекает за считанные секунды

В кукле есть таймаут для подобных случаев. Для абучана его можно уменьшить.

**Comment by UserNaem** [comment]
> Те кто пользуются мышкой соснут

Соснут все, кто не успеет настрочить пост за 5-10 секунд, но да, это было бы неочевидно.
> Для абучана его можно уменьшить.

Да, хорошо бы.

**Comment by UserNaem** [comment]
> Да, хорошо бы.

И тут я вспомнил, что интервал обновления капчи уже есть в настройках. И уменьшил его.

**Comment by xzyxzy** [comment]
Блять, я мудак.
Простите.
Да, забыл текст потыкать в комментарии чтобы капча была после ночных отвалов капчи.
