### ISSUE TITLE
Сложная кукломагия

### ISSUE THREAD

**Issue by UserNaem** [SthephanShinkufag/Dollchan-Extension-Tools#945]
Скастовал спелл:
(
    !#op &
    !#exph(/de-mypost/) &
    !#exph(/de-ref-my/)
)
Ожидал, что скроет все посты, кроме ОПа, моих постов (Инспектор Firefox сказал, что мои посты содержат .de-mypost) и постов, на которые я ответил или которые отвечают мне (.de-ref-my).
Получил немного не то: мои посты тоже оказались скрыты.
![default](https://cloud.githubusercontent.com/assets/21028464/17750621/dea43db6-64dc-11e6-85f2-2e94e324c255.png)

Что я делаю не так?

**Comment by SthephanShinkufag** [comment]
`#exph(/de-mypost/)` это не рабочий спелл, тому що класс `.de-mypost` это класс контейнера поста, а `#exph` проверяет только содержимое, а не сам контейнер.

**Comment by UserNaem** [comment]
О, спасибо. Теперь работает.
