### ISSUE TITLE
Макаба и автоподгрузка постов

### ISSUE THREAD

**Issue by zm3y** [SthephanShinkufag/Dollchan-Extension-Tools#946]
Долго сидел на 2016.3.9 пока абизяна не поломал капчу. Суть в чем, на любой версии скрипта выше 2016.3.9 во всех новых постах в треде подгруженных через автообновление треда не открываются картинки/вебм. Когда тыкаешь на вебм проигрывается только звук, а картинки и вовсе не открываются. Хром 52.

**Comment by zm3y** [comment]
Новые подробности. Если отключить спеллы в фильтрах, то картинки/вебм в новых постах начинают открываться.

**Comment by UserNaem** [comment]
Не смог воспроизвести баг на Firefox 50.0a2 на версии 16.8.17.0.d3b8f7e, вебм из подгруженных постов воспроизводятся.

**Comment by zm3y** [comment]
В лисе у меня тоже все в порядке. А именно в хроме на 2ух разных машинах такая проблема. Пробовал отключать все расширения кроме тампермонкей, не помогло, не в них дело. Сбрасывал настройки и флаги в хроме на дефолтные, переставлял его, бесполезно.

**Comment by SthephanShinkufag** [comment]
Обновите скрипт (у кого тамперманки). Должно заработать. Глюк Хрома очень странный был, однако, так нормальный браузер себя вести не должен. Но хром не нормальный. Он особенный.

**Comment by zm3y** [comment]
Заработало. Благодарю!
