### ISSUE TITLE
https://ernstchan.com/b/

### ISSUE THREAD

**Issue by UserNaem** [SthephanShinkufag/Dollchan-Extension-Tools#947]
Запиливал перевод для списка поддерживаемых АИБ, решил обновить счета постов в /b/ и получил пикрелейтед. Зашёл с чистого профиля Firefox 47.0.1 с куклой 16.8.17.0, чтобы убедиться, что виноват не браузер. Кстати, если из body убрать style="display:none;", страница показывается, но очень криво. Пока что уберу эту из списка поддерживаемых АИБ.
![ernstchan_ _b_-_passierschein_a38_-_mozilla_fire 19 08 16 00-48-23](https://cloud.githubusercontent.com/assets/21028464/17786644/2e19643a-659f-11e6-9acf-157f4806112f.png)

**Comment by sirx** [comment]
same problem here

**Comment by SthephanShinkufag** [comment]
Fixed in c34c7e60509bcabeb5254291755db1ad6ca48dad & 7871368c56042cdfd4df12b047cda8cf433349ff
