### ISSUE TITLE
Все посты отображаются как мои на /wh/

### ISSUE THREAD

**Issue by ShanellRoR** [SthephanShinkufag/Dollchan-Extension-Tools#948]
Вчера отправил пост в /wh/ и внезапно все посты на этой досаке стаили отображаться как мои (you). Вот скрин. Может где-то сам накосячил.
![ss 2016-08-19 at 12 54 06](https://cloud.githubusercontent.com/assets/17355822/17809385/dec90d42-661e-11e6-8dc4-1fcbc2d0fa66.png)

**Comment by ShanellRoR** [comment]
Товарищ разраб, а товарищ разраб, почините или у меня что-то не то? Я ж без вахача не могу, сразу за топором тянусь, черепа собирать хочется

**Comment by SthephanShinkufag** [comment]
Как получить этот баг?
