### ISSUE TITLE
Favicon + e10s

### ISSUE THREAD

**Issue by zgwerby** [SthephanShinkufag/Dollchan-Extension-Tools#949]
После переключения на электролиз не рисуются метки-оповещения о новых постах в фавиконе.
![2016-08-24 12-59-35](https://cloud.githubusercontent.com/assets/21217444/17927001/c5f30f9a-6a04-11e6-8661-cec5a4fc4e99.png)
![2016-08-24 13-00-25](https://cloud.githubusercontent.com/assets/21217444/17927000/c5f2c1c0-6a04-11e6-8067-f80e8b97f562.png)

**Comment by UserNaem** [comment]
Не удалось воспроизвести, у меня всё работает, e10s включен.
Fx 50.0a2 (2016-08-24), dE v16.8.17.0.d3b8f7e
Может, дело в Tree Style Tabs?

**Comment by zgwerby** [comment]
Спасибо, глючный аддон TabTree был, отправил баг автору. При замене на TST и очистке кэша появилось. 

Отправлено с моего телефона Cyanogen

25 авг. 2016 г. 10:13 пользователь UserNaem <notifications@github.com> написал:

Не удалось воспроизвести, у меня всё работает, e10s включен.
Fx 50.0a2 (2016-08-24), dE v16.8.17.0.d3b8f7e
Может, дело в Tree Style Tabs?
