### ISSUE TITLE
Поддержка движков fuuka и foolfuuka

### ISSUE THREAD

**Issue by Bfgeshka** [SthephanShinkufag/Dollchan-Extension-Tools#952]
Не думаете попробовать ограниченную поддержку? На этих движках крутится ряд архивов досок, банальные скрытие и вечный скролл были бы им к месту.

**Comment by Y0ba** [comment]
А можно ссылки с бордами?

**Comment by Bfgeshka** [comment]
http://archived.moe/_/articles/faq/
В конце страницы есть список актуальных.

**Comment by koteq** [comment]
```js
class FoolFuuka extends BaseBoard {
	constructor(prot, dm) {
		super(prot, dm);

		this.cReply = 'post_wrapper';
		this.qDForm = '#main';
		this.qImgInfo = '.post_file_metadata';
		this.qPostHeader = 'header';
		this.qPostImg = 'img.post_image';
		this.qPostMsg = '.text';
		this.qPostRef = '.post_data > a[data-function="quote"]';
		this.qPostSubj = '.post_title';
		this.qRPost = '.post[id]';

		this.docExt = '';
		this.res = 'thread/';

		this._qTable = '.thread_tools_bottom';
	}
	get qImgNameLink() {
		return '.post_file_filename';
	}
	get qThread() {
		return '.thread[id]';
	}
	get css() {
		return '.backlink_list { display: none !important; }';
	}
	get isArchived() {
		return true;
	}
	fixHTML(data, isForm) {
		const el = super.fixHTML(data, isForm);
		try {
			const els = $Q('.backlink', el);
			for(let i = 0, tLen = els.length; i < tLen; ++i) {
				els[i].href = els[i].href.replace(document.location, '').replace('/#', '#');
			}
		} catch(e) {}
		return el;
	}
	getTNum(el) {
		return +el.getAttribute('data-thread-num');
	}
	init() {
		defaultCfg.ajaxUpdThr = 0;
		return false;
	}
}
ibDomains['archived.moe'] = FoolFuuka;
```

**Comment by Bfgeshka** [comment]
ping. Хотелка ещё чешется, есть ли какие-то обновления по этому вопросу?

**Comment by VisualKei** [comment]
Двачую данный реквест, оче нужно. А то в скрипте SpookyX попап-превью только на 1 пост вглубь и нет отметки просмотренных постов, что крайне актуально именно для архивных тредов.

Алсо, в этих движках можно постить даже в протухший тред (пост ессно будет только на архивной борде). Думаю, для простоты этим можно вообще не заморачиваться - только ридонли, только хардкор.

**Comment by SthephanShinkufag** [comment]
Проверка:
https://archived.moe/b/
https://rbt.asia/mu/
https://thebarchive.com/b/
https://archiveofsins.com/h/
https://boards.fireden.net/a/
https://desuarchive.org/a/
https://archive.4plebs.org/pol/
http://archive.nyafuu.org/c/

Для https://archived.moe/b/ реализовано отслеживание редиректа картинок.

**Comment by SthephanShinkufag** [comment]
Вообще, `archived.moe` о-о-очень тормозной, страницы открываются жутко медленно, не удивляйтесь, если при попытке развернуть тред с нулевой через раз будете ловить `Ошибка подключения (timeout)`. Щито поделать.

**Comment by Bfgeshka** [comment]
Неплохо, спасибо, что надо - всё работает. Джва года ждал.

**Comment by SthephanShinkufag** [comment]
> Джва года ждал
> 3 Sep 2016

А и таки да. Как-то руки не доходили.
