### ISSUE TITLE
Реквест: Очистка избранного + обновление

### ISSUE THREAD

**Issue by YellowSM** [SthephanShinkufag/Dollchan-Extension-Tools#954]
Совместите плиз очистку избранного с обновлением. Так же удобнее - все равно идут запросы при очистке, но потом еще приходится обновление жать, чтобы посмотреть где есть новые посты. Не айс.

**Comment by WagonOfDoubt** [comment]
Обратное тоже верно. Если избранное уже обновили и были найдены 404-треды, то их можно сразу удалить без обхода.

**Comment by SthephanShinkufag** [comment]
Теперь кнопка "Очистить" в Избранном также обновляет счётчики постов.
