### ISSUE TITLE
В Safari не открываются настройки скрипта

### ISSUE THREAD

**Issue by SweetPalma** [SthephanShinkufag/Dollchan-Extension-Tools#955]
Аналогичная ситуация, но на десктопе:
https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/issues/935
При нажатии на кнопку скрипта менюшка не разворачивается. Safari 9.1.2, Mac OS X El Capitan 10.11.6, используемое расширение - Tampermonkey, версия скрипта - v16.8.17.0.

**Comment by SthephanShinkufag** [comment]
Да, есть такая проблема в Safari <=9

**Comment by SthephanShinkufag** [comment]
Теперь настройки в Сафари<10 открываются.
Отключил анимацию, так как много костылей ради нее придется пилить. Они когда-то в скрипте были для старых webkit движков, но давно выпилены.
Осталось решить проблему с #914. Если это не удастся - тогда я прекращу поддержку Safari до 10 версии.

**Comment by SweetPalma** [comment]
Спасибо, отлично.
