### ISSUE TITLE
Не загружаются картинки на абучан в сафари.

### ISSUE THREAD

**Issue by acedened** [SthephanShinkufag/Dollchan-Extension-Tools#958]
Сафари 10, сиерра. Видео загружаются. Идет прогресс загрузки, а в посте только текст.

**Comment by SthephanShinkufag** [comment]
Отключите пока опции `"Форма"` > `"Возможность отправки одинаковых картинок"`,
`"Удалять EXIF из JPEG"`,  `"Удалять имя файлов"`.
Попытаюсь исправить.

**Comment by SthephanShinkufag** [comment]
*inb4 не прошло и полгода, ліл*

**Comment by SthephanShinkufag** [comment]
Только недавно добрался до Сафарей, сижу играюсь с хакинтошами на виртуальных машинах.

**Comment by SthephanShinkufag** [comment]
Вроде бы всё, с Сафарями разобрался, везде все работает.
Кроме вебмок - Safari не умеет в проигрывание webm.
