### ISSUE TITLE
Вопрос по эвентам

### ISSUE THREAD

**Issue by pngcrypt** [SthephanShinkufag/Dollchan-Extension-Tools#959]
В кукле есть эвент при добавлении новых постов?
Хотелось бы заиметь такой.

**Comment by desudesutalk** [comment]
Да, было бы клёво. И за одно напомню про #917

**Comment by SthephanShinkufag** [comment]
Накарябал статейку:

https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/wiki/dollchan-api
