### ISSUE TITLE
По-ап меню на брчане

### ISSUE THREAD

**Issue by pngcrypt** [SthephanShinkufag/Dollchan-Extension-Tools#960]
Там местное меню есть у постов (жалобы, вот это всё). 
Можно его под куклой тоже показывать?

**Comment by SthephanShinkufag** [comment]
Платиновый вопрос.
Оно генерится скриптами борды. Родные скрипты подавляются куклоскриптом. На многих бордах так.
Это разве что, самому это меню сочинять..

**Comment by pngcrypt** [comment]
Ну я примерно так и думал.
А брчановскую капчу-то можно прикрутить в форму куклы?

**Comment by SthephanShinkufag** [comment]
А разве там есть капча? Народ как-то постит же.

**Comment by pngcrypt** [comment]
Там в настройках борды ее можно включить либо для постов, либо для тредов, либо отключить

**Comment by pngcrypt** [comment]
Вот, например тут для постов включено: https://brchan.org/z0/res/1.html
