### ISSUE TITLE
 [syn-ch.com]: Сломана коррекция времени

### ISSUE THREAD

**Issue by UserNaem** [SthephanShinkufag/Dollchan-Extension-Tools#962]
Формат даты:
Пт 7 окт 2016 00:10:47
Шаблон поиска:
w+dd+m+yyyy+hh+ii+ss
Шаблон замены:
_d._n._Y _h:_i:_s (должно быть 07.10.16 00:10:47)

Сломалось как-то очень странно. Иногда успешно обрабатывает некоторые треды, иногда - нет, например, на https://syn-ch.com/b/res/3729567.html всё на месте, а на https://syn-ch.com/b/res/3748369.html - нет. На нулевой тоже иногда часть тредов успешно обрабатывается. Проверял на Firefox Aurora 50.0a2 (2016-09-04) и на Nightly 52.0a1 (2016-09-30), на Nightly совсем не работает. На других бордах всё на месте.

**Comment by SthephanShinkufag** [comment]
> Пт 7 окт
> 7

Хм. Но там ведь одна цифра. Попробуйте

`w+dd?+m+yyyy+hh+ii+ss`

**Comment by UserNaem** [comment]
> w+dd?+m+yyyy+hh+ii+ss

Попробовал, ничего. Но заметил, что не работает только если дата указана одной цифрой, а не двумя. Тред: https://syn-ch.com/b/res/3729567.html
![b_-_ _ 33_-_firefox_developer_edition 08 10 16 08-16-45](https://cloud.githubusercontent.com/assets/21028464/19209665/a356806a-8d28-11e6-8be6-ac1f0b504b3c.png)
