### ISSUE TITLE
Капча на 4chan 

### ISSUE THREAD

**Issue by pwf63158cdnqacom** [SthephanShinkufag/Dollchan-Extension-Tools#966]
Раньше на форчане была гуглокапча, "выберите все изображения с блинами" которая. А выбрать легаси капчу было нельзя. Теперь всё наоборот, гуглокапчу назад вернуть нельзя. А легаси очень неудобна. 
Раньше там часто показывались просто трехзначные номера, и вводить их было действительно быстро и удобно. Но теперь там постоянно показывает только названия всяких улиц с указателей, причем по две штуки. В итоге в капчу вводить приходится часто больше десяти символов. А еще иногда при открытии формы постинга капча обновляется, и из-за этого текст пишется в поле ввода капчи, приходится его удалять, тянуться до мышки, много лишних действий совершать.
Сделайте возможность выбора, пожалуйста.

**Comment by VisualKei** [comment]
> А еще иногда при открытии формы постинга капча обновляется, и из-за этого текст пишется в поле ввода капчи, приходится его удалять, тянуться до мышки, много лишних действий совершать.

Плюсую это. Самое главное что это бывает не всегда и приходится обращать внимание, где оказался курсор. (А дебильные гамбургеры не нужны, текст вводить гораздо удобнее.)

**Comment by VisualKei** [comment]
Алсо, с порядком обхода постформы по Tab что-то не то, например из поля поста в поле капчи с клавиатуры похоже вообще не перейти - курсор идёт на кнопку `Ответ`, потом чёрти куда, и до поля капчи я так не смог добраться.
(BTW, при выборе английского в настройках кнопка `Ответ` по-русски это как-то не айс.)

**Comment by SthephanShinkufag** [comment]
< Раньше на форчане была гуглокапча, "выберите все изображения с блинами" которая. А выбрать легаси капчу было нельзя. Теперь всё наоборот, гуглокапчу назад вернуть нельзя. А легаси очень неудобна.
> Сделайте возможность выбора, пожалуйста.

Done.

> Алсо, с порядком обхода постформы по Tab что-то не то, например из поля поста в поле капчи с клавиатуры похоже вообще не перейти - курсор идёт на кнопку Ответ

Done.
