### ISSUE TITLE
Символы "+" в тредах с новыми ответами на свои посты

### ISSUE THREAD

**Issue by UserNaem** [SthephanShinkufag/Dollchan-Extension-Tools#969]
Когда-то они были зелёные, а сейчас синие. Долго искал старую версию куклы, чтобы найти там, какой цвет был раньше. Нашёл. 
Было:

```
                drawLines(ctx, [6, 11, 16, 11], [11, 6, 11, 16], '#1C5F23', 4, scale);
                drawLines(ctx, [7, 11, 15, 11], [11, 7, 11, 15], '#00F51B', 2, scale);
```

Стало:

```
                drawLines(ctx, [6, 11, 16, 11], [11, 6, 11, 16], '#1c375f', 4, scale);
                drawLines(ctx, [7, 11, 15, 11], [11, 7, 11, 15], '#0063f5', 2, scale);
```

Нельзя ли сделать выбор между этими вариантами, или указать свой цвет? Зелёный лучше смотрится с тёмной темой браузера на фоне фавиконов syn-ch.com и синих борд 4chan.org, наприме.

**Comment by Y0ba** [comment]
Не зелёными, а жёлтыми. Зелёными и сейчас отображаются новые посты без ответов тебе. Изменил я потому, что между зелёным и жёлтым почти не было разницы.

**Comment by UserNaem** [comment]
> Не зелёными, а жёлтыми.

Я имел в виду ответы на свои посты.

> между зелёным и жёлтым почти не было разницы

Как-то ещё ни разу не спутал жёлтый с зелёным. Так или иначе, был бы очень рад видеть такую настройку, не слишком удобно после каждого обновления искать-заменять.
Спасибо за ответ.

**Comment by SthephanShinkufag** [comment]
Мне тоже синий очень не нравится. Но дело вкуса. Раз Йоба так сделал, ну и ладно.

**Comment by SthephanShinkufag** [comment]
Я зеленый от желтого хорошо различаю.

**Comment by SthephanShinkufag** [comment]
Может, сделаю таки галочку.

**Comment by VisualKei** [comment]
Имхо логично иметь связь цвета плюса в иконке и цвета рамки выделения постов.
Сейчас свои посты выделяются синим - нынешний синий плюс при ответах на свои посты сразу намекает на это. Но так как новые посты выделяются зелёной рамкой, то обычный плюс стоит сделать зелёным вместо нынешнего жёлтого. Да и в общем цвета любых индикаторов красный/жёлтый/зелёный по умолчанию имеют смысл ошибка/временная проблема/всё нормально. Синий тут как раз близко к зелёному и в кассу, а вот жёлтый - нет. Вроде мелочь, но из таких вот мелочей интуитивность UI и складывается.
Только если так делать, то их оба стоит потемнее сделать, а не как нынешний синий и жёлтый и бывший зелёный - они все слишком яркие.

**Comment by Y0ba** [comment]
> Имхо логично иметь связь цвета плюса в иконке и цвета рамки выделения постов.

Нет, не логично. Цвета в иконке должны выделяться на большинстве иконок, а те обычно ярче, чем фон на странице.

**Comment by VisualKei** [comment]
Не вижу противоречия. Я не говорю, что цвет должен быть точно такой же, а лишь того же общего оттенка - конечно они должны быть ярче цвета рамок. Когда плюс был зелёный, он вполне нормально выделялся ничем не хуже жёлтого. И можно не делать плюсы темнее чем сейчас, тут я пожалуй передумал.

**Comment by SthephanShinkufag** [comment]
@VisualKei 
> так как новые посты выделяются зелёной рамкой, то обычный плюс стоит сделать зелёным вместо нынешнего жёлтого

Done.
