### ISSUE TITLE
Canvas: getImageData (белая иконка)

### ISSUE THREAD

**Issue by pngcrypt** [SthephanShinkufag/Dollchan-Extension-Tools#970]
В тор-браузере есть детект попытки получить содержимого канвы (метод getImageData)
Ну там защита от html5 canvas fingerprint. Вылазит предупреждение, что сайт пытается получить изображение, ну вот это всё. 
Во-первых, весьма назойливо (хотя можно отключить - разрешить или запретить, но только до перезапуска браузера. Потом опять будет вылезать).
А во-вторых слегка вводит в паранойю, особенно обывателей.
А в-третьих, если запретить использовать, то кукла будет вместо иконки белый квадрат рисовать.

Так вот, можно ли в кукле отказаться от метода getImageData? Или хотя бы детектить, что он запрещен. 
Правда, там в тор-браузере хитро сделали - метод срабатывает, но выдает все пиксели белые. Для детекта можно просто нарисовать черную точку, потом запросить getImageData и если она белая, значит метод блочится.

Но лучше бы избежать использование getImageData.
Я мельком сырцы глянул - вы всего в двух местах его используете. При рисовании плюса на иконке точно можно без getImageData обойтись - т.е. вместо `ctx.putImageData(original,..)` использовать `ctx.drawImage(icon,...)`
А во втором месте хз. Но вам-то виднее )

**Comment by SthephanShinkufag** [comment]
Дело не в `getImageData` и 'putImageData' вообще, Тор ругается на `ctx.drawImage(icon, 0, 0, wh, wh);` &mdash; на само получение оригинальной иконки, чтобы на ней можно было рисовать плюсы.

**Comment by pngcrypt** [comment]
Ну, насколько я помню, я тестил - ругалось именно на получении изображения через getImageData.
Хотя давно это было, может уже что-то изменилось...
Мое предложение было - не получать иконку, а сразу на ней рисовать. Тогда, как помню, не ругалось.
Т.е. там защита именно от получения изображения, нарисованного на канве, дабы избежать отслеживания по fingerprint.

**Comment by SthephanShinkufag** [comment]
`getImageData` в скрипте вообще нужно для того, чтобы всего-лишь ускорить создание набора иконок на основе оригинала. Я его убрал *вообще*. Сделал каждый раз стирание канваса и отрисовку заново через `ctx.drawImage(icon, 0, 0, wh, wh);`. Уведомление все равно появляется.

> Сразу на ней рисовать

Ну и как это возможно, например? Без считывания иконки.

**Comment by SthephanShinkufag** [comment]
Ну нарисуете вы плюсик в канвасе. И дальше что? Куда вы его вставите? Как наложите на фавикон?

**Comment by SthephanShinkufag** [comment]
Сейчас этот механизм выглядит так: получаем изображение оригинальной иконки, дорисовываем туда плюсик, преобразуем через `iconUrl = canvas.toDataURL('image/png')`, и вставляем в `head` документа как новый `<link rel="shortcut icon" href="' + iconUrl + '">`.
Есть другой механизм?

**Comment by pngcrypt** [comment]
Честно говоря, мне это уже не актуально.
