### ISSUE TITLE
tor browser, не запоминает скрытые треды/сообщения

### ISSUE THREAD

**Issue by userneu** [SthephanShinkufag/Dollchan-Extension-Tools#971]
Какую опцию нужно напердолить? Пробовал в настройках Privacy выбирать опцию Remember my history, но это не помогло.

**Comment by VisualKei** [comment]
about:config->dom.storage.enabled=false? Если да - сделать true, если уже true - то хз.

**Comment by userneu** [comment]
дом стораж включен
куки тоже включены

**Comment by SthephanShinkufag** [comment]
Наконец-то добрался проверить Тор.
Скрытые треды сохраняются даже с высокими настройками безопасности. Фиг знает.

**Comment by SthephanShinkufag** [comment]
Ага, понял. При выходе из тора, и открытии его заново, localStorage очищается. Логчно, это же тор-браузер. тут всё заточено под параноидальность. Зойчем хранить идентифицирующую вас инфу?

**Comment by SthephanShinkufag** [comment]
Ага, понял. Я просто не пытался закрыть Тор. При выходе из Тора, и открытии его заново, localStorage очищается. Логчно, это же тор-браузер. тут всё заточено под параноидальность. Зойчем хранить идентифицирующую вас инфу?

**Comment by SthephanShinkufag** [comment]
Кстати, Избранное и настройки скрипта сохраняется даже после закрытия. Это потому, что они хранятся в GM-настройках Greasemonkey.

**Comment by Y0ba** [comment]
Может как-то можно детектировать тор-браузер и использовать хранилище гризманки для скрытых постов? Там выключены несколько фич в отличии от файрфокса, может детектировать по ним?

**Comment by SthephanShinkufag** [comment]
Там не только скрытые посты. Мои посты, синхронизация между вкладками,.. В общем, все обращения к localStorage и sessionStorage, если по-хорошему.

**Comment by Y0ba** [comment]
> Мои посты

Угу.

> синхронизация между вкладками

А вот это можно оставить как есть. Тут сохранять данные после выхода не нужно.

**Comment by SthephanShinkufag** [comment]
> Тут сохранять данные после выхода не нужно.

А, таки да.

**Comment by Y0ba** [comment]
sessionStorage тоже можно не трогать. Там изначально подразумевается, что после закрытия вкладки все данные будут удалены.

**Comment by SthephanShinkufag** [comment]
`locStorage` в нужных местах нужно обернуть во что-нибудь типа `domStorage.get` и `domStorage.set`, которые будут менять тип хранения в зависимости от того, Тор это или нет. Инициализировать это дело надо в функции `checkStorage`.

**Comment by SthephanShinkufag** [comment]
> Инициализировать это дело надо в функции checkStorage.

Хотя нет, все-таки в `initNavFuncs`, она позже.

**Comment by userneu** [comment]
Да нафиг нужны костыли специально для тора. Выяснили что не в срипте дело и ладно. А очистка локалстоража, интересно, захардкожена или нет? В любом случае это уже другой вопрос, а тред можно закрывать. На ваше усмотрение конечно.

**Comment by soredake** [comment]
Было бы хорошо если бы это исправили, хоть это и не проблема скрипта, так поскрывать хочется.

**Comment by soredake** [comment]
Куда задонатить чтобы это произошло?

**Comment by soredake** [comment]
С 7.0.0 версии перестало забывать.

**Comment by SthephanShinkufag** [comment]
@soredake, тор теперь хранит localStorage пользователя? А как же пароноидальность, анонимность, все дела? Что-то тут не так.

**Comment by soredake** [comment]
@SthephanShinkufag уточнение, хранит теперь только если `browser.privatebrowsing.autostart` = false, в противном случае всё так стирает.

**Comment by SthephanShinkufag** [comment]
@soredake 
Добавил в [описание по установке](https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/wiki/installation#tor-browser).
