### ISSUE TITLE
[420chan.org]: Отсутствуют посты в тредах

### ISSUE THREAD

**Issue by Coschan** [SthephanShinkufag/Dollchan-Extension-Tools#972]
1. Chrome 53.0.2785.143 m
2. v16.8.17.0.d3b8f7e
3. 420chan.org (осторожно, если параноишь, имиджборда посвящена именно 420 и остальным подобным вещам)
4. Зайти в любой раздел -> зайти в любой тред -> увидеть лишь фон.

**Comment by SthephanShinkufag** [comment]
420chan.org теперь перенаправляет на leftypol.org.
