### ISSUE TITLE
8chan: не постит при необходимости ввести капчу

### ISSUE THREAD

**Issue by e6opoteh** [SthephanShinkufag/Dollchan-Extension-Tools#974]
На некоторых бордах (на которых стоит настройка что капчу надо вводить раз в сутки, например /kc/) капча находится не в форме постинга а выводится всплывающим окном. В таком случае при попытке отправить пост (если капча сегодня введена еще не была) скрипт выдает следующее:
SyntaxError: JSON.parse: expected ',' or '}' after property value in object at line 1 column 16 of the JSON data at checkUpload (Dollchan_Extension_Tools.user.js:11973:13) at PostForm/this.form.onsubmit/< (Dollchan_Extension_Tools.user.js:10965:13) at [106]

**Comment by SthephanShinkufag** [comment]
Таки вот теперь как надо.
