### ISSUE TITLE
На брчане шаблон времени поправьте

### ISSUE THREAD

**Issue by pngcrypt** [SthephanShinkufag/Dollchan-Extension-Tools#976]
На такой: `nn+dd+yy+++++hh+ii+ss` а то некоторые буквы юникода не определяются.

**Comment by pngcrypt** [comment]
Вернее в /tudo/ они не работают. Но там, я так понимаю, поддержки нет?

**Comment by SthephanShinkufag** [comment]
В tudo динамическая генерация страницы на лету, там не так все просто.
>nn+dd+yy+++++hh+ii+ss

Сейчас `dd+nn+yy+++++hh+ii+ss`, и он правильный. issue только для tudo?

**Comment by SthephanShinkufag** [comment]
Вообще, зачем менять дни и месяцы местами?

**Comment by pngcrypt** [comment]
Хз. Так у меня там дату показывает.

**Comment by pngcrypt** [comment]
Может формат к ойпи привязывается?

**Comment by SthephanShinkufag** [comment]
Понятия не имею. Но в /rus вот такое время:

17/10/16(Seg)16:07:12

Дни идут первыми.

**Comment by pngcrypt** [comment]
Да ладно, фик с ней с датой

>В tudo динамическая генерация страницы на лету
Это я в курсе. Но там в принципе просто. Треды подгружаются в форму. А отлавливать их можно примерно так (если нужно, конечно):
```
let observer = new MutationObserver( function(mutations) {
	for(let m of mutations) {
		for(let ch of m.addedNodes) { 
			if( ch.nodeName == 'DIV' && ch.id && ch.id.match(/^thread_/) ) // или по классу 'thread'
				setTimeout(onNewThread, 0, ch); 
		}
	}
});
observer.observe(document.querySelector('form[name="postcontrols"]'), {attributes: false, childList: true, characterData: false, subtree: false});
function onNewThread(thread) {
// обработка треда
}
```

**Comment by SthephanShinkufag** [comment]
Отлавливать их это не вопрос. Вопрос обрабатывать этот контент в скрипте.
По сути, писать целый огород с функционалом сродни инфинитискроллу ради одной доски одной борды.

**Comment by pngcrypt** [comment]
Ну ладно. Я и не настаиваю )

**Comment by SthephanShinkufag** [comment]
Меня удивляет, чому все набежали именно на brchan. Была себе никому не нужная слоудоска. Мало того, **не русская**. Зойчем. Почему. Загадка для меня. Были 100500 русских мелкодосок...

**Comment by pngcrypt** [comment]
Хз. Все побежали. И я побежал (с) :)

**Comment by SthephanShinkufag** [comment]
Вы же там на птичьих правах. Когда нибудь местной обезъяне надоест созерцать кириллицу с таким-то траффиком, и он прикроет лавочку. Можете скринить. Странный народ.

**Comment by pngcrypt** [comment]
Да не, там админ обрадовался. У него посещаемость раньше порядка 50-100 постов в /b. В остальных вообще глухо

**Comment by pngcrypt** [comment]
Хотя брчан уже забанили в ркн ) Макака не дремлет
