### ISSUE TITLE
Сохранение блобов, открытых несколько минут назад

### ISSUE THREAD

**Issue by Trubessinum** [SthephanShinkufag/Dollchan-Extension-Tools#979]
Добавьте в скрипт кнопку для сохранения изображения со страницы с открытым блобом ("blob:https://~~"). Пока пройдешься по пикче-треду и наоткрываешь понравившихся картинок, первые успевают устаревать, и сохранить их не получается. Было бы здорово, если бы можно было пройтись по **открытым** вкладкам с блобами и сохранить изображение из каждой.
Если вдруг сделаете - с з/п задоначу на печенье. Добра.

_По мотивам треда из /b/ http://arhivach.org/thread/209918/_

**Comment by Y0ba** [comment]
1. Страница с `blob:`-ссылкой является внутренней страницей браузера и скрипт туда инжектироваться не может.
2. Это видимо багофича лисы, что страница с просмотром изображения хранит слабую ссылку на `blob:`-данные и потому после закрытия вкладки с тредом (где существуют все сильные ссылки) сборщик мусора их уничтожает.

**Comment by Trubessinum** [comment]
Печально, ну ладно. Тогда сам себе скрипт напишу, все-таки не хочется все это вручную делать.
А за ответы все равно спасибо.

**Comment by SthephanShinkufag** [comment]
> Тогда сам себе скрипт напишу

> Страница с blob:-ссылкой является внутренней страницей браузера и скрипт туда инжектироваться не может.

**Comment by Y0ba** [comment]
@SthephanShinkufag с расширением можно.

**Comment by SthephanShinkufag** [comment]
А ведь у нас почти зойпилено расширение... Никак не могу выделить время на скрипт. Щас разгребусь с делами, может чего удастся покодить.

**Comment by Trubessinum** [comment]
> Страница с blob:-ссылкой является внутренней страницей браузера и скрипт туда инжектироваться не может.

Ну, я уже сделал именно то, что и хотел. Просто на вкладке с блобом скрипт переносит изображение в холст, откуда я могу его нормально сохранить.
А можно оно или нельзя - меня это мало волнует, я в вебе не силен.
http://sss.ssmaker.ru/f05ff775.png

**Comment by Y0ba** [comment]
Я про юзерскрипты, которым кукла и является. javascript-букмарклеты могут работать везде.
