### ISSUE TITLE
Глюк формы поста: Ctrl-A + брчан

### ISSUE THREAD

**Issue by pngcrypt** [SthephanShinkufag/Dollchan-Extension-Tools#981]
Достал уже этот баг. Когда в форме поста нажимаешь Ctrl-A, а потом начинаешь писать, то текст не удаляется, и новый добавляется в середину. Без куклы, в родной форме такого бага нет.

Брчан, Тамперманки+Хром 54.0

![111](https://cloud.githubusercontent.com/assets/20708704/19875419/a04460d2-9fdd-11e6-9e3c-7d94413cecee.gif)

**Comment by pngcrypt** [comment]
Во еще какой глюк. Редактирую спеллы, выделяю дабл-кликом слово, начинаю печатать - всё уходит в форму постинга.

![fbg2](https://cloud.githubusercontent.com/assets/20708704/20036693/605c9646-a420-11e6-92e0-954b0275a2f2.gif)

Самое странное, этот глюк может и пропасть и всё начинает работать нормально.

**Comment by SthephanShinkufag** [comment]
Действительно, в Хроме есть такой баг.
Странное поведение.
