### ISSUE TITLE
Реквест: количество скрытых постов

### ISSUE THREAD

**Issue by RosinSmoke** [SthephanShinkufag/Dollchan-Extension-Tools#983]
Было бы удобно, если бы в счётчике постов и картинок можно было включать отображение числа скрытых или нескрытых постов. Или эту статистику сразу по нескрытым вести, если галка отмечена в настройках, всё равно номера постов показывают реальные цифры "до скрытия".

**Comment by SthephanShinkufag** [comment]
`"Настройки"` > `"Общее"` >  `[Без скрытых] Счетчик постов/картинок на панели`

Пробуйте.

**Comment by RosinSmoke** [comment]
Наше Вам спасибо, работает как надо.
