### ISSUE TITLE
Не отображаются картинки на .hk, когда на ссылку наводишь. 

### ISSUE THREAD

**Issue by jc7e** [SthephanShinkufag/Dollchan-Extension-Tools#985]
![screenshot_222](https://cloud.githubusercontent.com/assets/23403582/20220682/821a2456-a83f-11e6-9156-eea0dbb7244c.png)
![screenshot_223](https://cloud.githubusercontent.com/assets/23403582/20220685/85064fd2-a83f-11e6-8105-81367662c233.png)

**Comment by jc7e** [comment]
Теперь при написании поста с картинкой в тред без захода в тред - пикрелейтед
![screenshot_227](https://cloud.githubusercontent.com/assets/23403582/20245177/ccc60d58-a9ac-11e6-8cf0-cb63bec66a46.png)
После обновления страницы картинка отображается нормально.

**Comment by Y0ba** [comment]
Ты точно обновил скрипт. Оригинальный баг был исправлен на стороне самого 2ch.hk, а уже этот баг с незагружающимися картинками исправил я.

**Comment by Y0ba** [comment]
Алсо, исправил раскрытие dashchan-треда. 2841ea15ed7112dd54080f78280750360979ad9a

**Comment by jc7e** [comment]
Когда сам себе буратино. Все ок, спасибо.
