### ISSUE TITLE
Не сохраняются скрытые треды/посты

### ISSUE THREAD

**Issue by onewaycheerio** [SthephanShinkufag/Dollchan-Extension-Tools#986]
Firefox 47.0.1, скрипт последней версии.
После перезапуска браузера все скрытые треды/посты обнуляются. Пробовал чистить куки Ычана и переустанавливать скрипт.

**Comment by SthephanShinkufag** [comment]
Попробуйте отключить спеллы.
Попробуйте нажать кнопку `Сброс` в `Настройках`, и сбросить все конфиги.

**Comment by onewaycheerio** [comment]
Не то. Проблема была в том что у меня стояло "удалять куки при закрытии браузера", и Ычан не был в исключениях. Добавил, теперь сохраняет.
