### ISSUE TITLE
2ch.hk: Неправильный url картинок при дозагрузке треда

### ISSUE THREAD

**Issue by CherryPerry** [SthephanShinkufag/Dollchan-Extension-Tools#987]
Макакий снова что-то нашатал, что у картинок теперь другой url в json, и итоговый url получается неверным.

Url итоговой картинки: https://2ch.hk/a//a/thumb/3392569/14790179836980s.jpg
JSON файла аттача к посту: 
```
{ ... 
path : "/a/src/3392569/14790179836980.jpg", 
thumbnail : "/a/thumb/3392569/14790179836980s.jpg"
... }
```

**Comment by Y0ba** [comment]
Уже исправлено. Обнови скрипт.
