### ISSUE TITLE
Изображения

### ISSUE THREAD

**Issue by Garitos** [SthephanShinkufag/Dollchan-Extension-Tools#988]
Изображения с куклоскриптом прогружаются только после полной перезагрузки страницы
Система: Win 8.1 x64
Браузер: Google Chrome 54.0.2840.99 m
Версия скрипта: v16.8.17.0.d3b8f7e, расширение хромовское.

**Comment by UserNaem** [comment]
Уже починили в последней версии, пользуйтесь Tampermonkey. Настройки можно перенести, сохранив их (кнопка "Файл" на странице настроек скрипта) или скопировав и вставив (кнопка "Править" там же).

**Comment by Garitos** [comment]
То есть хромовское приложение чинить не планируется?

**Comment by UserNaem** [comment]
Хроморасширение обновляется несколько реже юзерскрипта.

**Comment by SthephanShinkufag** [comment]
Обновил хроморасширение.
