### ISSUE TITLE
Как изменить звук оповещения о новых постах?

### ISSUE THREAD

**Issue by UserNaem** [SthephanShinkufag/Dollchan-Extension-Tools#991]
Сабж.

**Comment by SthephanShinkufag** [comment]
Берёте ваш звуковой файл.
Конвертируете в base64 каким-нибудь конвертером. Например,
https://www.opinionatedgeek.com/Codecs/Base64Encoder

Удаляете все пробелы и переносы строк. Копируете результат.

Ищете в коде скрипта строку

```js
    val.src = gitRaw + 'signal.ogg';
```

Заменяете её на

```js
    val.src = 'data:audio/mp3;base64РЕЗУЛЬТАТ';
```

где вместо РЕЗУЛЬТАТ - ваш полученный текст.
Вместо `mp3` изменяете расширение, если оно другое.

**Comment by UserNaem** [comment]
Долго думал, почему не слышно. Немного погуглил. Потом подумал, что тут где-то недостаёт запятой. В итоге получилось так:
`
val.src = 'data:audio/mp3;base64,результат';
`
Спасибо большое.

**Comment by SthephanShinkufag** [comment]
> Потом подумал, что тут где-то недостаёт запятой

Ой вей! Ну, главное, що ви всё правильно поняли.
