### ISSUE TITLE
Добавление тредов в Избранное на Абучане

### ISSUE THREAD

**Issue by Oduvanchik7227** [SthephanShinkufag/Dollchan-Extension-Tools#992]
Автоматически следить за:   своими постами (настройки харкача) - галка снята
 Добавлять тред в избранное при ответе  (настройки куклы) - галка снята

Однако при обновлении страницы галка в настройках Харкача ставится автоматически и треды начинают забивать Избранное. С отключенной куклой такой проблемы не возникает. Как фиксить?

**Comment by SthephanShinkufag** [comment]
Избранное макабы не нужно. Удолил его вообще.
Есть избранное куклы.
