### ISSUE TITLE
Реквест: поддержка m2-ch.ru

### ISSUE THREAD

**Issue by anonimous321** [SthephanShinkufag/Dollchan-Extension-Tools#993]

**Comment by perdolka** [comment]
Думаю, это можно закрывать, по адресу m2-ch.ru вместо борды какой-то говносайт.

**Comment by anonimous321** [comment]
Они переехали на m2ch.hk. Надеюсь, автор когда-нибудь всё же запилит поддержку, а то там очень удобно читать сохранённые треды.
