### ISSUE TITLE
Проблемы при открытии вебм

### ISSUE THREAD

**Issue by qxces** [SthephanShinkufag/Dollchan-Extension-Tools#994]
Короче, один неприятный баг появился (или был?). Если выставить открытие пикч/вебм по центру либо в посте и после чего открыть, а потом прервать несколько вебм, то все страницы перестанут грузиться. И так либо до полной загрузки всех открытых вебм в фоне, либо до закрытия и нового открытия всех вкладок борды.
Webmrelated.
[https://webmshare.com/nG8No](https://webmshare.com/nG8No)

Chrome 54.0.2840.99 m
Последний куклоскрипт [отсюда](https://raw.github.com/SthephanShinkufag/Dollchan-Extension-Tools/master/Dollchan_Extension_Tools.user.js)

**Comment by SthephanShinkufag** [comment]
> получать заголовки webm из метаданных

Отключите.

**Comment by SthephanShinkufag** [comment]
Вообще эту функцию надо как-то переписать, используя частичную загрузку файла.
Сейчас парсеру для полученя заголовка нужно перелопатить весь файл.
Или выпилить этот функционал вообще.

**Comment by SthephanShinkufag** [comment]
AVE!
Я таки сделал отмену загрузки получения метаданных webm.
Теперь, если вы закрываете или переключаетесь на другую картинку/вебм, соединение обрывается.

**Comment by SthephanShinkufag** [comment]
Выяснил, что вебмки сами тоже загружались даже после их удаления.
Теперь их загрузка тоже отменяема, так как сделано в самой макабе.

**Comment by SthephanShinkufag** [comment]
Ну, вроде бы всё. После закрытия вебмки ничего не грузится.

**Comment by qxces** [comment]
О, да. все работает. Спасибо!
