### ISSUE TITLE
Dollchan ломает zadraw.ch

### ISSUE THREAD

**Issue by zbczyvgy** [SthephanShinkufag/Dollchan-Extension-Tools#995]
1) Если навести на сгенерированный линк ответа, то текст внутри ответа может перекраситься в серый. Использую на харкаче стиль Neutron. Может случаться и само по себе.

Update: серый текст в оригинальном ответе появляется всегда, если в сгенерированном этот текст выделить.

2) Актуально для старой версии (~полугодичной давности) не знаю, пофикшено ли в новой.
Если в избранном очень много тредов с разных чанов (харкач, брчан, краутчан, форчан сразу), то скрипт проведет кружочком обновления по всем тредам из списка для раскрытой борды (не чана) и застрянет на последнем. При этом обновления количества постов не произойдет.

Dollchan 16.11.14.0, Chrome 54.0.2840.99 m.

**Comment by zbczyvgy** [comment]
Еще две вещи: с куклоскриптом на харкаче больше не работает двачевалка совсем. С куклоскриптом скрывает содержимое всех борд на Задроуче, работает только главная.

**Comment by Y0ba** [comment]
> Если навести на сгенерированный линк ответа, то текст внутри ответа может перекраситься в серый.

Возможно включён "Отмечать просмотренные посты" в Настройки -> Ссылки.

> проведет кружочком обновления по всем тредам из списка для раскрытой борды (не чана) и застрянет на последнем.

В консоли ошибок (Ctrl+Shift+J) что-нибудь при застревании появляется?

> не работает двачевалка совсем

Это ты про кнопки Двачую/RRRAGE? Они и не тестируются. А при AJAX-обновлении они не обновляются.

> С куклоскриптом скрывает содержимое всех борд на Задроуче, работает только главная.

Я не разбираюсь во всех этих мемсах и названиях. Можешь дать ссылку где не работает?

**Comment by zbczyvgy** [comment]
> мемсах и названиях
Zadraw.ch
> в консоли ошибок
> возможно включен
Сейчас посмотрю.

**Comment by Y0ba** [comment]
> Zadraw.ch

Хм, УМВР. Тоже проверь консоль ошибок при открытии.

**Comment by zbczyvgy** [comment]
Работают фреймы досок, если переходить с главной?
Вот консоль по задрочу: http://puu.sh/skEoJ/04c4b75795.png

**Comment by zbczyvgy** [comment]
Да, отключил "отмечать просмотренные посты", серым больше текст не становится. Другое дело, что в стандартном стиле харкаче он и с галкой не становился серым.
Про обновление - вроде теперь обновляет, но только чан, на котором находишься в данный момент. Он ведь не должен обновлять треды по всем чанам от харкача и до форчана?

**Comment by Y0ba** [comment]
Степан там вроде что-то менял, я не помню уже @SthephanShinkufag ↑

> Вот консоль по задрочу

Может настройка какая ломает скрипт? Можешь скинуть настройки скрипта для этой борды?

**Comment by zbczyvgy** [comment]
Для задроча настройки стандартные, я на него давно не заходил (плюс, они теряли бекапы, сайт был не доступен). Вообще не уверен, что куклоскрипт работал с Задроучен, но он же ломать его так и так не должен?

**Comment by zbczyvgy** [comment]
А по консоли с Update и Clear - огромный лог в консоли, уплывшие треды не чистит, сейчас отредактирую и запощу.

**Comment by zbczyvgy** [comment]
Лог консоли: http://pastebin.com/nUS6sB0y
Скрин консоли: http://rgho.st/private/7GV88jdDK/f4cc3405777c5c8f92e92ad25e594813
Треды, за которые стыдно: http://rgho.st/private/7N5rQyTdk/6301b5c7c7b5a63b5cc98b3c6d0201ec

Такое просходит после того, как нажать на "Clear" - кукла, вероятно, чекает все треды на чане, который открыт в окне, потом прыгает на другой чан и там застревает. При этом, уплывшие треды не удаляются. Если удалить из избранного треды со всех чанов, кроме того, который открыт, то работает нормально.

**Comment by Y0ba** [comment]
Ну с Zadraw.ch всё понятно. Там вся форма для отправки динамически генерируется сриптом и потому конфликтует с скуклой. Исправлять я ничего не буду, пусть либо админ настроит сервер на отдачу сразу нормального html как делают все остальные борды, либо лучше скрипт там не выполнять вообще.

**Comment by Y0ba** [comment]
@zbczyvgy Попробуй обновить скрипт и проверить избранное снова. По крайней мере теперь ошибок должно быть гораздо меньше.

**Comment by zbczyvgy** [comment]
Хромовский экстеншн можно обновить не переустанавливая? Там есть в самой кукле кнопка обновить?

**Comment by Y0ba** [comment]
Нет. Так только со скриптом можно. Что касается расширения, то это тогда ждать степана надо, пока он его обновит.

**Comment by zbczyvgy** [comment]
Сейчас выпилю и поставлю Темперманки.

**Comment by zbczyvgy** [comment]
Отлично! Clear чекает все сайты, удалил два упллывших треда. Насчет Update пока сказать не могу, нужно добавить в избранное много тредов и ждать, пока в них напишут. Но, кажется, кружочек Update чекает только открытый чан, на другие не ходит.

**Comment by Y0ba** [comment]
Видимо проблема была в расширении, а не в самом скрипте :|

**Comment by zbczyvgy** [comment]
Да, Update не работает с неактивными чанами.

**Comment by SthephanShinkufag** [comment]
zadraw.ch был в этом году мною исправлен.
Сейчас проверил - всё работает.
