### ISSUE TITLE
Реквест: автоматическая замена линка с кириллицей.

### ISSUE THREAD

**Issue by zbczyvgy** [SthephanShinkufag/Dollchan-Extension-Tools#999]
Чтобы цифровые обозначения в линке xyu.op/%D0%A5%D1%83%D0%B9/ превращались в xyu.op/хуй/

**Comment by UdongeinChan** [comment]
```
var links = document.getElementsByTagName('a');
for (var i = 0; i < links.length; i++) {
  links[i].innerHTML = decodeURI(links[i].innerHTML);
  links[i].href = decodeURI(links[i].href);
}
```
Надо добавить что-то типа этого (код из моего юзерскрипта) к парсеру постов.

**Comment by SthephanShinkufag** [comment]
Зойпилено.

**Comment by UdongeinChan** [comment]
Эти функции могут вывалить экзепшн, если считают ссылку/текст невалидным и весь скрипт упадёт. Например:
http://iichan.hk/b/res/4325852.html#4326353

Сам вчера нарвался, лол.

**Comment by SthephanShinkufag** [comment]
Интэрэсно девки пляшут! Danke за репорт.
